const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const out='handoff/P18/evidence/revision-01';
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh',acceptDownloads:true});p.setDefaultTimeout(12000);const checks=[],errors=[],metrics=[];p.on('pageerror',e=>errors.push(e.message));
const act=a=>p.locator(`[data-p18="${a}"]`).first(),shot=async n=>{await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.p18-app img[src]')].map(i=>i.decode().catch(()=>{})));scrollTo(0,0);});await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});};
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
const demo=async a=>{await p.locator('.p18-tools').evaluate(e=>e.open=true);await p.click(`[data-p18-demo=${a}]`);};
const snap=async()=>JSON.parse(await p.locator('[data-p18-snapshot]').textContent());
async function login(){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');}
async function capture(id){for(const [width,height] of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});await p.waitForTimeout(100);const m=await p.locator('.p18-app').evaluate(e=>{const s=e.closest('.hn-screen'),r=s.getBoundingClientRect(),body=e.querySelector('.p18-scroll'),footer=e.querySelector('.p18-footer')||s.querySelector('.hn-nav');return {frame:[s.offsetWidth,s.offsetHeight],scaleX:r.width/s.offsetWidth,scaleY:r.height/s.offsetHeight,overflow:body.scrollWidth>body.clientWidth,scrollHeight:body.scrollHeight,clientHeight:body.clientHeight,footerBottom:footer.getBoundingClientRect().bottom,frameBottom:r.bottom,dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(e).fontFamily};});assert.deepEqual(m.frame,[494,950]);assert.ok(Math.abs(m.scaleX-m.scaleY)<.001);assert.equal(m.overflow,false);assert.ok(m.footerBottom<=m.frameBottom+1);metrics.push({id,width,height,...m});await shot(`${id}-${width}x${height}`);}await p.setViewportSize({width:494,height:950});}
try{
await login();
await check('S01/A01 four tasks, cancel/escape/back, retry single task and retain others',async()=>{await demo('files');const before=(await snap()).files;assert.equal(before.length,4);assert.equal(before[1].progress,75);await capture('P18-S01');await act('cancel').click();assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(140);assert.deepEqual((await snap()).files,before);await act('cancel').click();await p.goBack();await p.waitForTimeout(140);assert.deepEqual((await snap()).files,before);await act('retry').dblclick();await p.waitForTimeout(800);const after=(await snap()).files;assert.equal(after[2].state,'ready');assert.deepEqual(after.filter((_,i)=>i!==2),before.filter((_,i)=>i!==2));await act('cancel').click();await p.getByRole('button',{name:'Dừng tải lên',exact:true}).click();await p.waitForTimeout(180);await p.getByRole('button',{name:'Đóng',exact:true}).click();await p.waitForTimeout(180);assert.equal((await snap()).files[1].state,'cancelled');assert.equal((await snap()).files[0].state,'ready');await shot('upload-cancelled');});
await check('A01 UNKNOWN blocks retry and preserves task; menu no deletion',async()=>{await p.selectOption('[data-p18-outcome]','unknown');await act('retry').click();await p.waitForTimeout(800);assert.equal((await snap()).files[1].state,'unknown');assert.equal(await p.locator('[data-file="p18-pn0005-photo1"][data-p18=retry]').count(),0);await act('unknown').click();assert.match(await p.locator('.app-modal-host').innerText(),/không gửi lại/);await p.keyboard.press('Escape');await p.waitForTimeout(140);await act('menu').click();assert.equal(await p.getByRole('button',{name:/Xóa tệp/}).count(),0);await p.keyboard.press('Escape');await p.waitForTimeout(140);});
await check('S02/A02 true PDF renderer, different page bytes/text, correct file download',async()=>{await act('view').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 2');const first=await p.locator('.p18-paper canvas').evaluate(e=>e.toDataURL());await capture('P18-S02');await act('next').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='2 / 2');assert.equal(await act('prev').evaluate(e=>e===document.activeElement),true);assert.notEqual(await p.locator('.p18-paper canvas').evaluate(e=>e.toDataURL()),first);assert.match(await p.locator('.p18-pdf-text').textContent(),/PHIẾU NHẬP KHO/);await shot('viewer-page2');await act('prev').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 2');const dl=p.waitForEvent('download');await act('download').click();const download=await dl;assert.equal(download.suggestedFilename(),'HoSoNhap_PN-0005.pdf');await download.saveAs(path.join(out,'downloaded-HoSoNhap_PN-0005.pdf'));assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(out,'downloaded-HoSoNhap_PN-0005.pdf'))).digest('hex'),crypto.createHash('sha256').update(fs.readFileSync('docs/flows/attachments/assets/HoSoNhap_PN-0005.pdf')).digest('hex'));assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(140);await act('back').click();await p.waitForSelector('[data-panel="P18.S01"]');assert.equal((await snap()).files[1].state,'unknown');});
await check('S03/A03 validations, blocked close, retained form, closed readonly',async()=>{await demo('handoff');await capture('P18-S03');await act('handoff').click();assert.equal(await p.locator('[name=checked]').evaluate(e=>e===document.activeElement),true);await shot('handoff-validation');await p.check('[name=checked]');await p.fill('[name=receiver]','Nguyễn Văn Bình');await p.fill('[name=day]','2026-09-29');await p.fill('[name=note]','Đã kiểm tra thiết bị.');await act('handoff').dblclick();assert.equal(await p.locator('.app-modal-host').count(),1);assert.match(await p.locator('.app-modal-host').innerText(),/chưa ở trạng thái Chờ bàn giao/);assert.equal((await snap()).caseStatus,'Đang kiểm tra');await p.keyboard.press('Escape');await p.waitForTimeout(160);await p.locator('.p18-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('handoff-form-bottom');await demo('ready');await p.check('[name=checked]');await p.fill('[name=receiver]','Nguyễn Văn Bình');await act('handoff').click();assert.match(await p.locator('.app-modal-host').innerText(),/Chưa có chính sách/);assert.equal((await snap()).caseStatus,'Chờ bàn giao');await p.keyboard.press('Escape');await p.waitForTimeout(160);await demo('closed');assert.equal(await act('handoff').isDisabled(),true);assert.equal(await p.locator('[name=receiver]').getAttribute('readonly'),'');await shot('handoff-closed');await demo('handoff');assert.equal(await p.inputValue('[name=receiver]'),'Nguyễn Văn Bình');assert.equal(await p.inputValue('[name=note]'),'Đã kiểm tra thiết bị.');});
await check('S04/A04/A05 unknown source, explicit fixture, selection without location mutation',async()=>{await demo('location');assert.equal(await p.locator('[data-p18=slot]').count(),0);assert.match(await p.locator('.p18-app').innerText(),/Chưa xác minh/);await shot('location-source-unknown');await p.check('[data-p18-capacity]');assert.equal(await p.locator('[data-p18=slot]').count(),6);assert.equal(await p.locator('[data-slot=A2]').getAttribute('aria-pressed'),'true');await capture('P18-S04');await p.locator('[data-slot=B2]').focus();await p.keyboard.press('Enter');assert.equal((await snap()).selected,'B2');assert.equal((await snap()).mutations,0);assert.equal(await p.locator('[data-slot=B2]').evaluate(e=>e===document.activeElement),true);await act('location').click();assert.match(await p.locator('.app-modal-host').innerText(),/không thay vị trí/);await p.keyboard.press('Escape');await p.waitForTimeout(160);await p.uncheck('[data-p18-capacity]');assert.equal(await p.locator('[data-p18=slot]').count(),0);});
await check('P12 actual file uses same ID, viewer and Back restore tab; P18 list entry works',async()=>{await p.click('[data-route=documents]');await p.click('[data-p12-doc="fixture-inbound-0005"]');await p.click('[data-p12-tab=files]');await p.locator('[data-p12-file]').first().click();await p.waitForSelector('[data-panel="P18.S02"]');assert.equal((await snap()).fileId,'b12-attachment-1');await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 1');await act('back').click();await p.waitForSelector('[data-p12-tab=files][aria-selected=true]');await p.click('[data-p12=attachments]');await p.waitForSelector('[data-panel="P18.S01"]');assert.equal((await snap()).docId,'fixture-inbound-0005');assert.deepEqual((await snap()).files.map(f=>f.id),['b12-attachment-1','b12-attachment-2']);assert.equal((await snap()).baseline,false);});
await check('P09/P06 owners navigate with exact case/item and restore on Back',async()=>{await p.evaluate(()=>location.hash='#p02/warranty?panel=3&case=BH-005');await p.click('[data-p09=handoff]');assert.equal((await snap()).caseId,'BH-005');await act('back').click();await p.waitForSelector('[data-p09=handoff]');assert.match(await p.locator('.p09-app').innerText(),/BH-005/);await p.evaluate(()=>location.hash='#p02/lookup?panel=3&item=fixture-component-01');await p.click('[data-p06=location]');assert.equal((await snap()).itemId,'fixture-component-01');await act('back').click();await p.waitForSelector('[data-p06=location]');});
await check('read error retry, late fetch route departure, invalid deep links',async()=>{await p.route('**/HoSoNhap_PN-0005.pdf',r=>r.abort());await demo('files');await act('view').click();await p.waitForSelector('[data-p18=reload]');await shot('viewer-load-error');await p.unroute('**/HoSoNhap_PN-0005.pdf');await act('reload').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 2');await p.evaluate(()=>location.hash='#p02/attachments?panel=2&doc=does-not-exist&file=p18-pn0005-dossier');await p.waitForSelector('.p18-app [role=alert]');assert.equal(await p.locator('.p18-app canvas').count(),0);await p.evaluate(()=>location.hash='#p02/attachments?panel=4&item=fixture-item-HN12345');await p.waitForSelector('.p18-app [role=alert]');assert.equal(await p.locator('[data-p18=location]').count(),0);});
await check('permission/session revoked blocks P18 and Back cannot restore logged out data',async()=>{await demo('files');await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.click('[data-system-demo=deny]');await p.waitForSelector('[data-panel="P15.S03"]');await p.click('[data-system-demo=allow]');await p.waitForTimeout(180);await p.click('[data-system-demo=expired]');await p.waitForSelector('[data-panel="P15.S02"]');await p.goBack();await p.waitForTimeout(200);assert.equal(await p.locator('.p18-app:visible').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){console.log(e);if(await p.locator('.hn-screen').count())await shot('browser-failure');fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
