import {previewScope,scopeGuard,createUploadQueue,handoffErrors,handoffBlock,SLOT_FIXTURE,slotData} from './model.mjs';
import {attachmentFixtures,simulateUpload} from './fixture-adapter.mjs';
import {caseDetails,postedDocuments} from '../warranty/warranty-model.mjs';
import {createLookupFixtureAdapter} from '../lookup/fixture-adapter.mjs';
import {createActionFeedback} from '../shared/action-feedback.mjs';
import {HOME_ICONS} from '../home/icons.mjs';
import {LOOKUP_ICONS} from '../lookup/icons.mjs';
import {INBOUND_ICONS} from '../inbound/icons.mjs';
import {PROFILE_ICONS} from '../profile/icons.mjs';
import {ATTACHMENT_ICONS} from './icons.mjs';
const esc=v=>String(v??'Chưa xác minh').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={...HOME_ICONS,...LOOKUP_ICONS,...INBOUND_ICONS,...PROFILE_ICONS,...ATTACHMENT_ICONS};
const icon=n=>`<svg viewBox="0 0 24 24" class="p18-icon" aria-hidden="true">${icons[n]||icons.document}</svg>`;
const btn=(a,t,cls='',attrs='')=>`<button type="button" data-p18="${a}" class="${cls}" ${attrs}>${t}</button>`;
const tile=(n='document',op='documents')=>`<span class="hn-operation-icon" data-hn-operation="${op}" data-size="md">${icon(n)}</span>`;
const kv=(k,v)=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`;
const day=v=>v?v.split('-').reverse().join('/'):'Chưa xác minh';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date());

export function mountAttachments({root,screen,tools,getState,getDocuments,onHome,onNavigate,onSize}){
 let active=false,disposed=false,scope=null,panel=1,docId=null,fileId=null,caseId=null,itemId=null,page=1,rendered='',generation=0,loadingTask=null,pdf=null,pdfBytes=null,pdfRender=null,controller=null,busyDownload=false,errors={},selected='A2',fixtureSlots=false,baseline=false,uploadOutcome='ready',backPending=false;
 const queues=new Map(),drafts=new Map(),positions=new Map(),cancels=new Set();
 const readDoc=()=>getDocuments().find(d=>d.id===docId&&d.warehouseId===scope?.warehouseId);
 const queueKey=()=>docId+':'+(baseline?'B18':'owner');
 const queue=()=>queues.get(queueKey());
 const files=()=>queue()?.snapshot()||[];
 const file=()=>files().find(f=>f.id===fileId)||(()=>{const f=readDoc()?.attachments?.find(f=>f.id===fileId);return f?{...f,state:'ready',mime:'application/pdf'}:null;})();
 const denied=()=>scopeGuard(getState(),scope);
 const feedback=createActionFeedback({getScreen:()=>screen,tools,isActive:()=>active&&!disposed,key:'hnP18Feedback'});
 const info=(title,message)=>feedback.show({title,message,confirmLabel:'Đóng'});
 const key=()=>[panel,docId,fileId,caseId,itemId].join(':');
 const draft=()=>{if(!drafts.has(caseId))drafts.set(caseId,{checked:false,receiver:'',day:today(),note:''});return drafts.get(caseId);};
 function remember(){if(active)positions.set(key(),root.querySelector('.p18-scroll')?.scrollTop||0);}
 function cleanupRead(){generation++;controller?.abort();controller=null;pdfRender?.cancel();pdfRender=null;loadingTask?.destroy();loadingTask=null;pdf=null;pdfBytes=null;busyDownload=false;}
 function notifyGuard(){const e=denied();if(e){info('Không thể tiếp tục',e);return true;}return false;}
 function go(p,extra={}){if(backPending||notifyGuard())return;remember();onNavigate({panel:p,doc:docId,...(baseline?{sample:'b18'}:{}),...extra});}
 function back(){if(backPending)return;remember();backPending=true;if(history.state?.p18From)history.back();else if(panel===2){backPending=false;go(1);}else onHome();}
 function fileTile(f){return f.mime?.startsWith('image/')?`<img class="p18-thumb" src="${esc(f.url)}" alt="Ảnh kiện hàng minh họa">`:`<span class="p18-file-tile">${icon('document')}<small>PDF</small></span>`;}
 function fileRow(f){
  const labels={uploading:'Đang tải lên…',error:'Tải lên thất bại',unknown:'Chưa xác định kết quả',cancelled:'Đã hủy tải lên'};
  return `<article class="p18-file" data-file-id="${esc(f.id)}" tabindex="-1">${fileTile(f)}<div class="p18-file-copy"><strong data-hn-readable="Tên tệp" data-hn-lines="2">${esc(f.name)}</strong><small class="${['error','unknown'].includes(f.state)?'p18-error':''}">${f.size?esc(f.size)+' · ':''}${esc(labels[f.state]||(f.day?day(f.day):'Sẵn sàng'))}</small>${f.state==='uploading'?`<div class="p18-progress"><progress value="${f.progress}" max="100" aria-label="Tiến độ ${esc(f.name)}"></progress><span>${f.progress}%</span></div>`:f.state==='ready'?`<div class="p18-file-links">${btn('view','Xem','','data-file="'+esc(f.id)+'"')}${btn('download','Tải xuống','','data-file="'+esc(f.id)+'"')}</div>`:['error','cancelled'].includes(f.state)?btn('retry',icon('refresh')+' Thử lại','p18-link','data-file="'+esc(f.id)+'"'):btn('unknown','Cần đối chiếu','p18-link','data-file="'+esc(f.id)+'"')}</div>${btn(f.state==='uploading'?'cancel':'menu',(f.state==='uploading'?icon('x'):'⋮'),'p18-icon-button',`data-file="${esc(f.id)}" aria-label="${f.state==='uploading'?'Hủy tải lên':'Thông tin tệp'} ${esc(f.name)}"`)}</article>`;
 }
 function list(){const d=readDoc();return `<section class="p18-card"><h2>Thông tin ${d.type==='inbound'?'phiếu nhập':'chứng từ'}</h2><div class="p18-context">${tile('document',d.type)}<div><strong>${esc(d.number)}</strong><small>${day(d.day)}</small><p data-hn-readable="Đối tác" data-hn-lines="2">${esc(d.partner)}</p></div></div></section><section class="p18-card"><h2>Danh sách tệp đính kèm (${files().length})</h2><div class="p18-file-list">${files().map(fileRow).join('')||'<p>Chưa có tệp đính kèm.</p>'}</div><aside class="p18-hint">${icon('info')}<p><strong>Lưu ý quyền tải lên</strong><br>PDF, JPG, PNG theo chính sách hệ thống. Chưa có chính sách tải lên được xác minh cho phiên này.</p></aside></section>`;}
 function viewer(){const f=file();return `<div class="p18-card p18-context">${fileTile(f)}<div><strong data-hn-readable="Tên tài liệu" data-hn-lines="2">${esc(f.name)}</strong><small>${esc(f.size||'Kích thước chưa xác minh')}</small></div></div><div class="p18-paper" aria-busy="true"><p role="status">Đang tải tài liệu…</p><canvas hidden aria-label="Nội dung trang PDF"></canvas><img hidden alt="Nội dung tệp ảnh"><div class="p18-pdf-text" tabindex="0" aria-label="Văn bản trang PDF"></div></div>`;}
 function handoff(){const c=caseDetails(caseId),d=draft(),closed=c.closed,parts=postedDocuments(caseId).flatMap(x=>x.lines);
  const error=k=>`<span id="p18-${k}-error" class="p18-error" ${errors[k]?'':'hidden'}>${esc(errors[k]||'')}</span>`;
  return `<section class="p18-card"><h2>Thông tin bảo hành</h2><dl class="p18-kv">${kv('Số phiếu',c.id)}${kv('Ngày tiếp nhận',day(c.events?.[0]?.day))}${kv('Sản phẩm',c.model)}${kv('Số serial',c.serial)}<div><dt>Tình trạng</dt><dd><span class="p18-badge">${esc(c.status)}</span></dd></div></dl><p class="p18-label">Kỹ thuật xử lý</p><p data-hn-readable="Kỹ thuật xử lý" data-hn-lines="3">${esc(c.result||'Chưa có kết quả sửa chữa.')}</p></section><section class="p18-card"><h2>Linh kiện đã xuất (${parts.length})</h2>${parts.length?`<table class="p18-parts"><thead><tr><th>Tên linh kiện</th><th>SL</th></tr></thead><tbody>${parts.map(l=>`<tr><td><span data-hn-readable="Tên linh kiện" data-hn-lines="2">${esc(l.name)}</span><small>${esc(l.sku)}</small></td><td>${l.quantity??'—'}</td></tr>`).join('')}</tbody></table>`:`<p>${c.ledgerKnown?'Chưa có linh kiện đã xuất.':'Chưa có nguồn linh kiện đã xuất.'}</p>`}</section><form id="p18-handoff" novalidate><section class="p18-card"><label class="p18-check"><input type="checkbox" name="checked" ${d.checked?'checked':''} ${closed?'disabled':''} aria-invalid="${!!errors.checked}" aria-describedby="p18-checked-error"><span><strong>Đã kiểm tra hoạt động của thiết bị <em>*</em></strong><small>Thiết bị hoạt động bình thường sau sửa chữa</small></span></label>${error('checked')}</section><section class="p18-card"><h2>Thông tin bàn giao</h2><label class="p18-field">Người nhận <em>*</em><input name="receiver" autocomplete="off" placeholder="Nhập tên người nhận" value="${esc(d.receiver)}" ${closed?'readonly':''} aria-invalid="${!!errors.receiver}" aria-describedby="p18-receiver-error">${error('receiver')}</label><label class="p18-field">Ngày bàn giao <em>*</em><input type="date" name="day" value="${esc(d.day)}" ${closed?'readonly':''} aria-invalid="${!!errors.day}" aria-describedby="p18-day-error">${error('day')}</label><label class="p18-field">Ghi chú <small>Không bắt buộc</small><textarea name="note" maxlength="200" placeholder="Nhập ghi chú…" ${closed?'readonly':''} aria-invalid="${!!errors.note}" aria-describedby="p18-note-error p18-note-count">${esc(d.note)}</textarea>${error('note')}<small id="p18-note-count">${d.note.length}/200 ký tự</small></label></section></form><p class="p18-policy">${closed?'Hồ sơ đã trả khách, chỉ đọc.':'Điều kiện bàn giao cần được xác minh. Kiểm tra thông tin không tự đóng hồ sơ.'}</p>`;
 }
 function locationView(){const item=createLookupFixtureAdapter().item({warehouseId:scope.warehouseId,actorId:scope.actorId},itemId);const d=slotData(selected,{fixture:fixtureSlots});return `<section class="p18-card"><h2>Thông tin linh kiện</h2><dl class="p18-kv">${kv('Mã linh kiện',item.code)}${kv('SKU',item.sku)}${kv('Tên linh kiện',item.name)}${kv('Đơn vị tính',item.unit)}</dl></section><section class="p18-card"><h2>Vị trí lưu trữ (cố định)</h2><dl class="p18-locked">${[['Pallet',fixtureSlots?'PL-01':null],['Khay',fixtureSlots?'K-01':null],['Kho Hoa Nam',scope.warehouseId==='fixture-hoa-nam'?'KHO-HN':null]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd>${icon('lock')}</div>`).join('')}</dl></section><section class="p18-card"><h2>Sơ đồ ${fixtureSlots?'khay K-01':'vị trí'}</h2>${fixtureSlots?`<div class="p18-slots" role="group" aria-label="Chọn ô xem thông tin">${SLOT_FIXTURE.map(s=>btn('slot',`<strong>${s.id}</strong><span>${s.current} / ${s.capacity}</span>`,'p18-slot',`data-slot="${s.id}" data-tone="${s.current===0?'empty':s.current===s.capacity?'full':'space'}" aria-pressed="${selected===s.id}"`)).join('')}</div><div class="p18-legend"><span>● Đang chọn</span><span>◉ Còn chỗ</span><span>● Đầy</span><span>○ Trống</span></div>`:`<div class="p18-unavailable">${tile('pin')}<strong>Chưa có sơ đồ vị trí</strong><p>Nguồn chưa cung cấp khay, ô và sức chứa đã xác minh.</p></div>`}</section><section class="p18-card"><h2>Thông tin vị trí đang chọn</h2><dl class="p18-kv">${kv('Vị trí khay',fixtureSlots?'K-01 · '+selected:item.location)}${kv('Số lượng hiện tại',d.current)}${kv('Sức chứa tối đa',d.capacity)}${kv('Số lượng còn trống',d.free)}</dl></section><p class="p18-policy">Chọn ô để xem thông tin. Chưa có nguồn xác nhận thay đổi vị trí.</p>`;}
 function render(focus=true){if(!active||disposed)return;cleanupRead();const y=positions.get(key())||0;
  const d=readDoc(),c=caseDetails(caseId),item=panel===4?createLookupFixtureAdapter().item({warehouseId:scope?.warehouseId,actorId:scope?.actorId},itemId):null;
  const invalid=denied()||(scope.warehouseId!=='fixture-hoa-nam'?'Không có dữ liệu trong kho hiện tại.':'')||([1,2].includes(panel)&&!d?'Không tìm thấy chứng từ trong kho hiện tại.':panel===2&&(!file()||(file().state&&file().state!=='ready'))?'Tệp chưa sẵn sàng hoặc không thuộc chứng từ.':panel===3&&!c?'Không tìm thấy hồ sơ.':panel===4&&(!item||item.category!=='components')?'Không tìm thấy linh kiện trong kho hiện tại.':'');
  const title=invalid?'Không thể mở nội dung':panel===1?'Tệp đính kèm '+d.number:panel===2?'Xem tài liệu':panel===3?'Bàn giao bảo hành':'Vị trí linh kiện kho';
  screen.classList.toggle('p18-focus-screen',[2,3].includes(panel));
  root.innerHTML=`<section class="p18-app" data-panel="P18.S0${panel}"><header class="p18-header">${btn('back',icon('back'),'p18-icon-button','aria-label="Trở về màn trước"')}<h1 tabindex="-1">${esc(title)}</h1></header><main class="p18-scroll">${invalid?`<div class="p18-card" role="alert">${esc(invalid)}</div>`:[list,viewer,handoff,locationView][panel-1]()}</main>${invalid?'':panel===2?`<footer class="p18-footer"><div class="p18-pager">${btn('prev',icon('back'),'','aria-label="Trang trước" disabled')}<span data-p18-pages role="status">Đang tải</span>${btn('next',icon('chevron'),'','aria-label="Trang sau" disabled')}</div><div class="p18-download">${btn('download',icon('download')+' Tải xuống','p18-primary',`data-file="${esc(fileId)}"`)}${btn('menu','⋮','p18-icon-button',`data-file="${esc(fileId)}" aria-label="Thông tin tài liệu"`)}</div></footer>`:panel===3?`<footer class="p18-footer">${btn('handoff','Xác nhận bàn giao','p18-primary',c.closed?'disabled':'')}</footer>`:panel===4?`<footer class="p18-footer">${btn('location','Xác nhận vị trí','p18-primary','aria-describedby="p18-location-help"')}<span id="p18-location-help" class="p18-sr-only">Chưa có chính sách thay đổi vị trí; không thay đổi tồn kho.</span></footer>`:''}</section>`;
  root.querySelector('.p18-scroll').scrollTop=y;if(focus)root.querySelector('h1')?.focus({preventScroll:true});onSize();syncTools();
  if(!invalid&&panel===2)void loadFile();
 }
 async function bytesFor(f,signal){if(notifyGuard())throw Error('Phiên không còn hợp lệ');const url=new URL(f.url,location.href);if(url.origin!==location.origin)throw Error('Nguồn tệp chưa được xác minh');const r=await fetch(url,{signal});if(!r.ok)throw Error('Không đọc được tệp');const bytes=new Uint8Array(await r.arrayBuffer());if(f.mime==='application/pdf'&&!new TextDecoder().decode(bytes.slice(0,5)).startsWith('%PDF-'))throw Error('Nội dung không phải PDF hợp lệ');return bytes;}
 async function loadFile(){const token=generation,f=file();controller=new AbortController();
  try{const bytes=await bytesFor(f,controller.signal);if(!active||token!==generation||denied())return;pdfBytes=bytes;
   if(f.mime?.startsWith('image/')){const img=root.querySelector('.p18-paper img');img.src=f.url;img.hidden=false;root.querySelector('.p18-paper [role=status]').textContent='';root.querySelector('.p18-paper').setAttribute('aria-busy','false');root.querySelector('[data-p18-pages]').textContent='1 / 1';return;}
   const lib=await import('./vendor/pdf.mjs');if(!active||token!==generation||denied())return;lib.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;loadingTask=lib.getDocument({data:bytes.slice(),isEvalSupported:false});pdf=await loadingTask.promise;if(token!==generation||!active||denied())return;page=Math.min(page,pdf.numPages);await paintPage(token);
  }catch(e){if(!active||token!==generation||e.name==='AbortError')return;const box=root.querySelector('.p18-paper');box.setAttribute('aria-busy','false');box.querySelector('[role=status]').textContent='Không xem được tài liệu. Kiểm tra nguồn rồi thử lại.';box.insertAdjacentHTML('beforeend',btn('reload','Thử lại','p18-link'));root.querySelector('[data-p18-pages]').textContent='Chưa tải được';}
 }
 async function paintPage(token=generation){if(!pdf||!active||denied())return;const targetPage=page,body=root.querySelector('.p18-paper');body.setAttribute('aria-busy','true');pdfRender?.cancel();
  try{const p=await pdf.getPage(targetPage);if(token!==generation||targetPage!==page||denied())return;const canvas=body.querySelector('canvas'),v=p.getViewport({scale:1.5});canvas.width=v.width;canvas.height=v.height;canvas.hidden=false;pdfRender=p.render({canvasContext:canvas.getContext('2d'),viewport:v});await pdfRender.promise;if(token!==generation||targetPage!==page||denied())return;body.querySelector('[role=status]').textContent='';body.setAttribute('aria-busy','false');canvas.setAttribute('aria-label',`Trang ${page} / ${pdf.numPages} · ${file().name}`);const text=await p.getTextContent();if(token!==generation||targetPage!==page)return;body.querySelector('.p18-pdf-text').textContent=text.items.map(x=>x.str).join(' ');root.querySelector('[data-p18-pages]').textContent=page+' / '+pdf.numPages;const focusedPager=document.activeElement;root.querySelector('[data-p18=prev]').disabled=page===1;root.querySelector('[data-p18=next]').disabled=page===pdf.numPages;if(focusedPager?.disabled&&focusedPager.closest('.p18-pager'))root.querySelector('.p18-pager button:not(:disabled)')?.focus({preventScroll:true});
  }catch(e){if(e.name!=='RenderingCancelledException'&&token===generation&&active)info('Không đọc được trang','Giữ nguyên tài liệu. Hãy tải lại để thử đọc trang.');}
 }
 async function download(id){if(busyDownload||notifyGuard())return;const f=files().find(f=>f.id===id)||(panel===2&&fileId===id?file():null);if(!f||f.state&&f.state!=='ready')return;
  busyDownload=true;const token=generation;controller=new AbortController();
  try{const bytes=panel===2&&id===fileId&&pdfBytes?pdfBytes:await bytesFor(f,controller.signal);if(!active||token!==generation||denied())return;const url=URL.createObjectURL(new Blob([bytes],{type:f.mime||'application/pdf'})),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);info('Đã chuyển tệp cho trình duyệt','Trình duyệt đang xử lý tải xuống '+f.name+'. Kiểm tra danh sách tải xuống để xác nhận tệp đã được lưu.');}
  catch(e){if(active&&token===generation&&e.name!=='AbortError')info('Không tải được tệp','Kiểm tra kết nối và quyền xem tệp rồi thử lại.');}
  finally{if(token===generation)busyDownload=false;}
 }
 function rowChanged(){if(!active||panel!==1)return;const focus={...document.activeElement?.dataset},focusedRow=document.activeElement?.closest('[data-file-id]')?.dataset.fileId,y=root.querySelector('.p18-scroll')?.scrollTop;positions.set(key(),y||0);render(false);if(focus?.file||focusedRow){const id=focus.file||focusedRow;(root.querySelector(`[data-file="${CSS.escape(id)}"][data-p18="${focus.p18}"]`)||root.querySelector(`[data-file-id="${CSS.escape(id)}"]`))?.focus({preventScroll:true});}}
 function validateHandoff(){const c=caseDetails(caseId);if(c?.closed){info('Chỉ xem hồ sơ',handoffBlock(c));return;}errors=handoffErrors(draft());remember();render(false);if(Object.keys(errors).length){root.querySelector(`[name="${Object.keys(errors)[0]}"]`)?.focus();return;}info('Chưa thể xác nhận bàn giao',handoffBlock(c));}
 function click(e){if(!active||disposed)return;const b=e.target.closest('[data-p18]');if(!b||!root.contains(b)||b.disabled)return;const a=b.dataset.p18;if(a==='back'){back();return;}if(notifyGuard())return;
  if(a==='view'){page=1;go(2,{file:b.dataset.file});}
  if(a==='download')void download(b.dataset.file);
  if(a==='menu'){const f=files().find(f=>f.id===b.dataset.file)||file();if(f)info('Thông tin tệp',f.name+'\n'+(f.size||'Kích thước chưa xác minh')+'\nĐịnh danh: '+f.id+'\nChứng từ: '+readDoc().number);}
  if(a==='cancel'){const id=b.dataset.file,f=files().find(f=>f.id===id);feedback.show({title:'Hủy tải lên?',message:'Dừng tác vụ tải lên '+f.name+'. Các tệp khác được giữ nguyên.',cancelLabel:'Hủy',confirmLabel:'Dừng tải lên',onConfirm:()=>{if(!notifyGuard()&&queue()?.cancel(id))info('Đã dừng tải lên','Tác vụ mô phỏng đã dừng. Không xóa tệp đã lưu.');}});}
  if(a==='retry'){const request=queue()?.begin(b.dataset.file);if(request)cancels.add(simulateUpload(queue(),request,uploadOutcome));}
  if(a==='unknown')info('Cần đối chiếu tệp','Chưa có nguồn đối chiếu kết quả tải lên. Giữ nguyên định danh tác vụ và không gửi lại.');
  if(a==='prev'||a==='next'){if(!pdf||root.querySelector('.p18-paper').getAttribute('aria-busy')==='true')return;page=Math.max(1,Math.min(pdf.numPages,page+(a==='next'?1:-1)));history.replaceState({...history.state,p18Page:page},'',location.hash);void paintPage();}
  if(a==='reload'){cleanupRead();render(false);}
  if(a==='handoff')validateHandoff();
  if(a==='slot'&&fixtureSlots&&SLOT_FIXTURE.some(s=>s.id===b.dataset.slot)){remember();selected=b.dataset.slot;render(false);root.querySelector(`[data-slot="${selected}"]`)?.focus({preventScroll:true});}
  if(a==='location')info('Chưa thể xác nhận vị trí','Chưa có chính sách và nguồn xác nhận vị trí trên App. Lựa chọn chỉ dùng để xem; không thay vị trí, sức chứa hoặc tồn kho.');
 }
 function input(e){if(!active||panel!==3||denied()||caseDetails(caseId)?.closed)return;const name=e.target.name;if(!['checked','receiver','day','note'].includes(name))return;draft()[name]=name==='checked'?e.target.checked:e.target.value;if(name==='note')root.querySelector('#p18-note-count').textContent=draft().note.length+'/200 ký tự';}
 const review=document.createElement('details');review.className='p18-tools';review.innerHTML='<summary>P18 · Đính kèm / Bàn giao / Vị trí · r01</summary><p>Fixture cục bộ, không kết nối WMS. Mở từ P12 giữ nguyên nguồn tệp P12. Nút S01 dưới đây dùng bộ bốn tệp B18 riêng để kiểm thử; PDF2trang tổng hợp từ PDF P12, ảnh box sẵn có. Tiến độ75% là snapshot fixture; retry phát sự kiện mô phỏng. Chưa có upload policy/close-case/move-location.</p><button data-p18-demo="files">S01 · Bốn tệp mẫu B18</button><button data-p18-demo="handoff">S03 · BH-001</button><button data-p18-demo="ready">S03 · BH-005 Chờ bàn giao</button><button data-p18-demo="closed">S03 · BH-002 Đã trả khách</button><button data-p18-demo="location">S04 · Vị trí linh kiện</button><label><input type="checkbox" data-p18-capacity> Số liệu B18 (chỉ fixture)</label><label>Kết quả retry fixture <select data-p18-outcome><option value="ready">Hoàn tất</option><option value="error">Thất bại</option><option value="unknown">Chưa xác định</option></select></label><pre data-p18-snapshot></pre>';tools.append(review);
 review.addEventListener('click',e=>{const a=e.target.dataset.p18Demo;if(!a)return;onNavigate(a==='files'?{panel:1,doc:'fixture-inbound-0005',sample:'b18'}:a==='location'?{panel:4,item:'fixture-component-01'}:{panel:3,case:a==='ready'?'BH-005':a==='closed'?'BH-002':'BH-001'});});
 review.querySelector('[data-p18-capacity]').onchange=e=>{fixtureSlots=e.target.checked;if(active)render(false);};review.querySelector('select').onchange=e=>uploadOutcome=e.target.value;
 function syncTools(){review.querySelector('pre').textContent=JSON.stringify({panel,docId,fileId,caseId,itemId,files:files(),scope,fixtureSlots,baseline,selected,caseStatus:caseDetails(caseId)?.status,mutations:0},null,2);}
 const submit=e=>{if(active&&e.target.id==='p18-handoff'){e.preventDefault();if(!notifyGuard())validateHandoff();}};
 root.addEventListener('submit',submit);root.addEventListener('click',click);root.addEventListener('input',input);root.addEventListener('change',input);
 return {show(){if(disposed)return;backPending=false;if(active&&rendered===location.hash&&root.querySelector('.p18-app'))return;remember();active=true;scope??=previewScope(getState());const q=new URLSearchParams(location.hash.split('?')[1]);panel=[1,2,3,4].includes(+q.get('panel'))?+q.get('panel'):1;docId=q.get('doc');baseline=q.get('sample')==='b18';fileId=q.get('file');caseId=q.get('case');itemId=q.get('item');page=Number.isInteger(history.state?.p18Page)?history.state.p18Page:1;errors={};const d=readDoc();if(d&&!queues.has(queueKey()))queues.set(queueKey(),createUploadQueue(attachmentFixtures(d,{baseline}),{getState,scope,onChange:rowChanged}));rendered=location.hash;render();},hide(){remember();active=false;feedback.clear();cleanupRead();screen.classList.remove('p18-focus-screen');},dispose(){disposed=true;active=false;cleanupRead();feedback.dispose();queues.forEach(q=>q.dispose());cancels.forEach(f=>f());review.remove();root.removeEventListener('submit',submit);root.removeEventListener('click',click);root.removeEventListener('input',input);root.removeEventListener('change',input);}};
}
