import test from 'node:test';
import assert from 'node:assert/strict';
import {createIssueFlow,quantityError,countIssue} from '../docs/flows/warranty-components/issue-model.mjs';
import {createIssueFixture,ISSUE_ITEMS} from '../docs/flows/warranty-components/issue-fixture.mjs';
import {caseDetails} from '../docs/flows/warranty/warranty-model.mjs';
import {writeWarrantyCase,resetWarrantyCases} from '../docs/flows/shared/warranty-cases.mjs';
const auth=()=>({previewReady:true,session:{authSessionId:'auth-1',actor:{id:'actor-1'},warehouse:{id:'fixture-hoa-nam',name:'Kho Hoa Nam',active:true},permissions:{warehouseOperations:true}}});
function setup(options={}){const state=auth(),adapter=options.adapter||createIssueFixture({delay:0}),posted=[];const flow=createIssueFlow({getState:()=>state,caseId:options.caseId||'BH-001',adapter,onPosted:r=>posted.push(r)});return {state,adapter,flow,posted};}
function fill(f){assert.equal(f.scan('LK0001-HN001').kind,'accepted');assert.equal(f.scan('BOX-LK-0002-01').kind,'quantity');assert.equal(f.quantity('2').kind,'accepted');}
for(const value of ['0','-1','1.1','abc','13','','1e1','Infinity','9007199254740993'])test('reject quantity '+JSON.stringify(value),()=>assert.ok(quantityError(value,12)));
test('P24 unknown availability blocks acceptance without assuming zero',()=>{assert.match(quantityError('2',null),/chưa xác minh/);assert.match(quantityError('2',undefined),/chưa xác minh/);assert.equal(quantityError('12',12),'');});
test('A01 two codes three units, no Post or stock mutation while scanning',()=>{const {flow,adapter}=setup();fill(flow);assert.deepEqual(countIssue(flow.snapshot().lines),{codes:2,quantity:3});assert.equal(adapter.metrics().commits,0);assert.equal(adapter.lookup(ISSUE_ITEMS[1].code).available,12);});
test('cancel new/edit quantity keeps accepted list; duplicate serial remains1',()=>{const {flow}=setup();fill(flow);const before=flow.snapshot().lines;flow.scan(ISSUE_ITEMS[1].code);flow.cancelQuantity();assert.deepEqual(flow.snapshot().lines,before);assert.equal(flow.scan(ISSUE_ITEMS[0].code).kind,'duplicate');assert.equal(flow.snapshot().lines.length,2);});
test('quantity confirmation replaces same box row and increments version',()=>{const {flow}=setup();fill(flow);const v=flow.snapshot().document.version;flow.scan(ISSUE_ITEMS[1].code);flow.quantity('3');assert.equal(flow.snapshot().counts.quantity,4);assert.equal(flow.snapshot().counts.codes,2);assert.equal(flow.snapshot().document.version,v+1);});
test('A03 empty Post rejected; double Post executes adapter only once',async()=>{const {flow,adapter}=setup();assert.equal((await flow.post()).kind,'invalid');fill(flow);const first=flow.post();assert.equal((await flow.post()).kind,'invalid');assert.equal((await first).kind,'posted');assert.equal(adapter.metrics().post,1);assert.equal(adapter.metrics().commits,1);});
test('verified receipt only then callback and refetched stock decrease',async()=>{const {flow,adapter,posted}=setup();fill(flow);const result=await flow.post();assert.equal(result.kind,'posted');assert.equal(posted.length,1);assert.equal(posted[0].requestId,flow.snapshot().request.id);assert.equal(adapter.lookup(ISSUE_ITEMS[1].code).available,10);assert.equal(flow.remove(ISSUE_ITEMS[1].code).kind,'invalid');});
test('A04 explicit failure retains lines without receipt',async()=>{const {flow,adapter,posted}=setup();fill(flow);adapter.setMode('error');assert.equal((await flow.post()).kind,'rejected');assert.equal(flow.snapshot().unknown,false);assert.equal(flow.snapshot().receipt,null);assert.equal(posted.length,0);assert.equal(flow.snapshot().counts.quantity,3);});
test('UNKNOWN preserves request/doc/version/session; all writes blocked',async()=>{const {flow,adapter}=setup();fill(flow);adapter.setMode('unknown');const before=flow.snapshot();assert.equal((await flow.post()).kind,'unknown');const request=flow.snapshot().request;assert.equal((await flow.post()).kind,'invalid');assert.equal(flow.scan(ISSUE_ITEMS[1].code).kind,'invalid');assert.equal(flow.remove(ISSUE_ITEMS[0].code).kind,'invalid');assert.equal((await flow.reconcile()).kind,'unknown');assert.deepEqual(flow.snapshot().request,request);assert.deepEqual(flow.snapshot().document,before.document);assert.equal(flow.snapshot().scanSessionId,before.scanSessionId);assert.equal(adapter.metrics().post,1);});
test('timeout after posted: only read reconciliation confirms, no second commit',async()=>{const {flow,adapter,posted}=setup();fill(flow);adapter.setMode('timeout-posted');assert.equal((await flow.post()).kind,'unknown');assert.equal(flow.snapshot().receipt,null);assert.equal(posted.length,0);assert.equal((await flow.reconcile()).kind,'posted');assert.equal(adapter.metrics().post,1);assert.equal(adapter.metrics().commits,1);assert.equal(posted.length,1);});
test('authoritative not-posted allows explicit retry using same request',async()=>{const {flow,adapter}=setup();fill(flow);adapter.setMode('not-posted');await flow.post();const request=flow.snapshot().request;assert.equal((await flow.reconcile()).kind,'rejected');adapter.setMode('ready');assert.equal((await flow.post()).kind,'posted');assert.deepEqual(flow.snapshot().request,request);});
test('wrong receipt identity stays UNKNOWN',async()=>{const base=createIssueFixture({delay:0}),adapter={...base,async post(req,g){const r=await base.post(req,g);r.receipt.caseId='BH-003';return r;}};const {flow,posted}=setup({adapter});fill(flow);assert.equal((await flow.post()).kind,'unknown');assert.equal(posted.length,0);});
for(const field of ['actor','warehouse','session','permission','expired'])test('guard '+field+' at action boundary',async()=>{const {flow,state,adapter}=setup();fill(flow);if(field==='actor')state.session.actor.id='other';if(field==='warehouse')state.session.warehouse.id='other';if(field==='session')state.session.authSessionId='other';if(field==='permission')state.session.permissions.warehouseOperations=false;if(field==='expired')state.sessionExpired=true;assert.equal((await flow.post()).kind,'invalid');assert.equal(adapter.metrics().post,0);});
test('A05 closed case blocks scan and Post',async()=>{const {flow}=setup({caseId:'BH-002'});assert.equal(flow.scan(ISSUE_ITEMS[0].code).kind,'invalid');assert.equal((await flow.post()).kind,'invalid');});
test('case closes during request: reject before simulated commit',async()=>{const {flow,adapter}=setup();fill(flow);const p=flow.post();writeWarrantyCase({...caseDetails('BH-001'),status:'Đã trả khách'});assert.equal((await p).kind,'rejected');assert.equal(adapter.metrics().commits,0);resetWarrantyCases();});
test('revoked permission while waiting never publishes success',async()=>{const {flow,state,posted,adapter}=setup();fill(flow);const p=flow.post();state.session.permissions.warehouseOperations=false;assert.equal((await p).kind,'unknown');assert.equal(posted.length,0);assert.equal(adapter.metrics().commits,0);});
test('recorded rows cannot be removed or changed by scan/quantity',()=>{const {flow}=setup();assert.equal(flow.restoreRecorded([{...ISSUE_ITEMS[1],quantity:2}]),true);assert.equal(flow.remove(ISSUE_ITEMS[1].code).kind,'invalid');assert.equal(flow.scan(ISSUE_ITEMS[1].code).kind,'invalid');assert.equal(flow.snapshot().lines[0].quantity,2);});
test('dispose during async request cannot emit confirmed receipt',async()=>{const {flow,posted,adapter}=setup();fill(flow);const p=flow.post();flow.dispose();assert.equal((await p).kind,'unknown');assert.equal(posted.length,0);assert.equal(adapter.metrics().commits,0);});
