import test from 'node:test';import assert from 'node:assert/strict';
import {createComponentHistory} from '../docs/flows/warranty-components/history-model.mjs';
import {summarizeReceipt,receiptCodes} from '../docs/flows/warranty-components/history-experience.mjs';
const s={previewReady:true,session:{actor:{id:'fixture'},authSessionId:'test',warehouse:{id:'fixture-hoa-nam',active:true},permissions:{warehouseOperations:true}}};
const row={id:'D',caseId:'BH-001',status:'POSTED',lines:[{sku:'LK',code:'C',quantity:1}]};
function setup(read,extra={}){const m=createComponentHistory({getState:()=>s,adapter:{read},...extra});m.select('BH-001');return m;}
test('A13 hanging read times out, keeps rows/cursor and can retry without mutation',async()=>{let n=0,signal;const m=setup(q=>{n++;signal=q.signal;return n===1?Promise.resolve({caseId:'BH-001',items:[row],hasMore:true,nextCursor:'next'}):new Promise(()=>{});},{timeoutMs:20});await m.load();await Promise.race([m.load(),new Promise(r=>setTimeout(r,60))]);const x=m.snapshot();assert.equal(x.loading,false);assert.ok(x.error);assert.equal(x.items.length,1);assert.equal(x.nextCursor,'next');assert.equal(signal.aborted,true);m.dispose();});
test('A14 cursor cycles are rejected and retain correct failed cursor',async()=>{let n=0;const m=setup(async()=>({caseId:'BH-001',items:[row],hasMore:true,nextCursor:['A','B','A'][n++]}));await m.load();await m.load();await m.load();assert.ok(m.snapshot().error);assert.equal(m.snapshot().nextCursor,'B');assert.equal(m.snapshot().items.length,1);m.dispose();});
test('A15 whitespace-only SKU/code are unknown without destroying original raw code',()=>{const d={id:'D',lines:[{sku:'   ',code:'  ',quantity:1}]};const x=summarizeReceipt(d);assert.equal(x.skuCount,null);assert.equal(x.groups[0].codesKnown,false);assert.match(receiptCodes(d),/Mã linh kiện \/ hộp: Chưa xác minh/);});
test('Known raw codes are never trimmed or normalized',()=>{const code='  QR-< & >\n🧰  ';assert.ok(receiptCodes({id:'D',lines:[{sku:'LK',code,quantity:1}]}).includes(code));});
test('Late non-abortable response after timeout cannot overwrite retry success',async()=>{let resolve,n=0;const m=setup(()=>++n===1?new Promise(r=>resolve=r):Promise.resolve({caseId:'BH-001',items:[row],hasMore:false,nextCursor:null}),{timeoutMs:10});await m.load();assert.ok(m.snapshot().error);await m.load();resolve({caseId:'BH-001',items:[{...row,id:'OLD'}],hasMore:false,nextCursor:null});await new Promise(r=>setTimeout(r,10));assert.deepEqual(m.snapshot().items.map(r=>r.id),['D']);m.dispose();});
test('Cancel hanging non-abortable read settles and leaves no spinner',async()=>{const m=setup(()=>new Promise(()=>{}),{timeoutMs:5000});const pending=m.load();m.cancel();assert.equal(await pending,false);assert.equal(m.snapshot().loading,false);assert.equal(m.snapshot().error,'');m.dispose();});
