import test from 'node:test';
import assert from 'node:assert/strict';
import {DOCUMENTS,initialFilters,selectDocuments,readDocument,totals,documentEvents,creationErrors,recordedDocuments,mergeDocuments,selectLines,warrantyDocuments} from '../docs/flows/documents/document-model.mjs';
import {createInboundFlow} from '../docs/flows/inbound/inbound-flow.mjs';
import {createInboundFixtureAdapter} from '../docs/flows/inbound/fixture-adapter.mjs';
import {INBOUND_SUPPLIERS} from '../docs/flows/inbound/catalogue.mjs';
const doc=readDocument('fixture-inbound-0005');
const auth={previewReady:true,session:{actor:{id:'a',name:'Minh Anh',role:'Nhân viên kho'},warehouse:{id:'fixture-hoa-nam',name:'Kho Hoa Nam',active:true},permissions:{warehouseOperations:true}}};
function flow(){const adapter=createInboundFixtureAdapter({delay:0});return {adapter,f:createInboundFlow({adapter,getState:()=>auth})};}
test('A01 combines query/type/status/range without changing source',()=>{const f={...initialFilters(),q:'minh phat',type:'inbound',status:'waiting',from:'2026-09-09',to:'2026-09-09'};assert.deepEqual(selectDocuments(f).map(r=>r.id),[doc.id]);assert.equal(selectDocuments({...f,status:'posted'}).length,0);assert.equal(DOCUMENTS.length,24);});
test('A01 defaults all dates, status/type remain distinct and sort is explicit',()=>{assert.equal(initialFilters().from,'');assert.equal(selectDocuments(initialFilters())[0].number,'PX-0011');assert.equal(selectDocuments({...initialFilters(),sort:'asc'})[0].number,'PX-0003');assert.equal(selectDocuments({...initialFilters(),status:'posted'}).length,11);});
test('A02 quantity11 distinct from3 SKU and5/4/2 serial counts',()=>{assert.deepEqual(totals(doc.lines),{quantity:11,skuCount:3});assert.deepEqual(doc.lines.map(r=>r.serialCount),[5,4,2]);assert.deepEqual(totals(null),{quantity:null,skuCount:null});assert.equal(totals([{sku:'same',quantity:2},{sku:'same',quantity:3}]).skuCount,1);});
test('Exact ID lookup never treats display prefix/number as authority',()=>{assert.equal(readDocument('PN-0005'),null);assert.equal(readDocument('b12-inbound-0004').status,'posted');assert.equal(readDocument('b12-warranty-002').type,'warranty');assert.equal(readDocument('invalid'),null);});
test('A03 history uses explicit P08 event mapping; missing data stays missing',()=>{assert.equal(documentEvents(doc).length,4);assert.equal(documentEvents(readDocument('b12-outbound-0004')).length,4);assert.ok(readDocument('b12-outbound-0004').lines.length>0);});
test('Creation validates only P12 owned input; supplier cannot be free text',()=>{assert.deepEqual(creationErrors({type:'inbound',supplierId:INBOUND_SUPPLIERS[0].id,note:''}),{});assert.ok(creationErrors({type:'inbound',supplierId:'made-up',note:''}).supplier);assert.ok(creationErrors({type:'outbound',note:'x'.repeat(201)}).note);assert.ok(creationErrors({type:'admin',note:''}).type);});
test('A04 inbound seeds fresh owner draft once; repeated routing retains ID, metadata and codes',()=>{const {f,adapter}=flow();f.start({documentEntry:{supplierId:INBOUND_SUPPLIERS[1].id,note:'P12 note'}});const before=f.snapshot().document;assert.equal(before.supplierId,INBOUND_SUPPLIERS[1].id);assert.equal(before.note,'P12 note');f.next();f.scan('HN12345');f.leave();f.start({documentEntry:{supplierId:INBOUND_SUPPLIERS[2].id,note:'overwrite'}},{newAttempt:true});assert.deepEqual(f.snapshot().document,before);assert.equal(f.snapshot().accepted.length,1);assert.deepEqual(adapter.metrics(),{recordCalls:0,inventoryDelta:0});f.dispose();});
test('A04 UNKNOWN retains request/session/version even when P12 reopens; no retry mutation',async()=>{const {f,adapter}=flow();f.start();f.next();f.scan('HN12345');f.next();adapter.setOutcome('unknown');await f.send();const before=f.snapshot();f.leave();f.start({documentEntry:{supplierId:INBOUND_SUPPLIERS[1].id,note:'overwrite'}},{newAttempt:true});assert.deepEqual(f.snapshot(),before);assert.equal(await f.send(),false);assert.equal(adapter.metrics().recordCalls,1);f.dispose();});
test('A04 next fresh run accepts new P12 metadata only after verified completion',async()=>{const {f}=flow();f.start();f.next();f.scan('HN12345');f.next();await f.send();const old=f.snapshot().document.documentId;f.leave();f.start({documentEntry:{supplierId:INBOUND_SUPPLIERS[1].id,note:'second'}},{newAttempt:true});assert.notEqual(f.snapshot().document.documentId,old);assert.equal(f.snapshot().document.note,'second');f.dispose();});

test('P12 receipt adapter excludes drafts/UNKNOWN/wrong warehouse and never counts scan raw as serial',async()=>{const {f}=flow();f.start();f.next();f.scan('HN12345');const source=()=>[{type:'inbound',runs:[f.snapshot()]}];assert.equal(recordedDocuments(source(),auth.session).length,0);f.next();await f.send();const docs=recordedDocuments(source(),auth.session);assert.equal(docs.length,1);assert.equal(docs[0].id,f.snapshot().document.documentId);assert.equal(docs[0].lines[0].serialCount,null);assert.deepEqual(docs[0].lines[0].codes,['HN12345']);assert.deepEqual(docs[0].attachments,[]);assert.equal(mergeDocuments(docs).filter(d=>d.id===docs[0].id).length,1);assert.equal(recordedDocuments(source(),{...auth.session,warehouse:{id:'wrong'}}).length,0);f.dispose();});

test('r02 24 records have coherent explicit lines, serials, quantities, dates and identities',()=>{assert.equal(new Set(DOCUMENTS.map(r=>r.id)).size,24);for(const type of ['inbound','outbound','warranty'])assert.equal(DOCUMENTS.filter(r=>r.type===type).length,8);for(const r of DOCUMENTS){assert.ok(r.note);assert.ok(r.lines.length);for(const l of r.lines){assert.equal(l.serialCount,l.serials.length);assert.equal(l.quantity,l.serials.length);assert.equal(new Set(l.serials).size,l.serials.length);assert.equal(selectLines(r.lines,l.serials[0])[0].id,l.id);}assert.ok(documentEvents(r).length);assert.ok(Array.isArray(r.attachments));}});
test('r02 warranty rows use the same case states, customer, serial and events as P09',async()=>{const {readWarrantyCases}=await import('../docs/flows/shared/warranty-cases.mjs');for(const c of readWarrantyCases()){const r=warrantyDocuments().find(r=>r.caseId===c.id);assert.equal(r.partner,c.customer);assert.deepEqual(r.events,c.events);assert.deepEqual(r.lines[0].serials,[c.serial]);if(c.status==='Đã trả khách')assert.equal(r.status,'returned');}});
test('r02 merging never fabricates attachments or serials for a newly recorded scan',async()=>{const {f}=flow();f.start();f.next();f.scan('HN12345');f.next();await f.send();const r=recordedDocuments([{type:'inbound',runs:[f.snapshot()]}],auth.session)[0];assert.deepEqual(r.attachments,[]);assert.equal(r.lines[0].serials,undefined);assert.equal(documentEvents(r)[0].label,'Gửi phiếu lên Web');assert.equal(mergeDocuments([r]).length,24);f.dispose();});

test('Source sort retains original source order independently of chronological order',()=>{const filters={...initialFilters(),sort:'source'};assert.deepEqual(selectDocuments(filters).map(d=>d.id),DOCUMENTS.map(d=>d.id));assert.notDeepEqual(selectDocuments(filters).map(d=>d.id),selectDocuments({...filters,sort:'desc'}).map(d=>d.id));});
