import test from 'node:test';
import assert from 'node:assert/strict';
import {mountAttachmentMotion} from '../docs/flows/attachments/motion.mjs';
class Target extends EventTarget{listeners=new Map();addEventListener(t,f,o){super.addEventListener(t,f,o);if(!this.listeners.has(t))this.listeners.set(t,new Set());this.listeners.get(t).add(f);}removeEventListener(t,f,o){super.removeEventListener(t,f,o);this.listeners.get(t)?.delete(f);}get count(){return [...this.listeners.values()].reduce((a,s)=>a+s.size,0);}}
function fixture(mode='auto'){
 const media=new Target();media.matches=false;const doc=new Target();doc.hidden=false;const root=new Target(),animations=[];let overlay=false,active=true;
 root.ownerDocument=doc;root.dataset={};root.getAttribute=()=>null;root.removeAttribute=k=>{if(k==='data-hn-motion-mode')delete root.dataset.hnMotionMode;};root.contains=n=>n.owner===root;root.closest=s=>s==='[inert]'?null:{querySelector:()=>overlay};root.querySelectorAll=()=>[];
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>k.includes('ease')?'linear':k.includes('row-feedback')?'160ms':k.includes('press')?'100ms':'140ms'})};
 const prior=globalThis.MutationObserver;let observers=0;globalThis.MutationObserver=class{constructor(fn){this.fn=fn;}observe(){observers++;}disconnect(){observers--;}};
 const node=()=>({owner:root,isConnected:true,dataset:{},matches:()=>false,animate(frames,options){let done;const a={frames,options,cancelled:false,finished:new Promise(r=>done=r),cancel(){this.cancelled=true;done();}};animations.push(a);return a;}});
 const motion=mountAttachmentMotion({root,requested:mode,active:()=>active,media});
 return {motion,doc,root,media,animations,node,observers:()=>observers,overlay:v=>overlay=v,active:v=>active=v,done(){motion.dispose();if(prior===undefined)delete globalThis.MutationObserver;else globalThis.MutationObserver=prior;}};
}
for(const mode of ['auto','reduced','off'])test(`M18 ${mode}: page ready only for latest explicit request; no replay on Back`,()=>{const f=fixture(mode);try{f.motion.activate();const node=f.node();f.motion.pageReady(node,'file:1');assert.equal(f.animations.length,0);f.motion.pageRequested('file:2');f.motion.pageRequested('file:1');f.motion.pageReady(node,'file:2');assert.equal(f.animations.length,0);f.motion.pageReady(node,'file:1');assert.equal(f.animations.length,mode==='off'?0:1);if(mode!=='off'){assert.equal(f.animations[0].options.duration,mode==='auto'?140:80);assert.ok(f.animations[0].frames.every(k=>!('transform'in k)));}f.motion.pageReady(node,'file:1');f.motion.hide();f.motion.activate();f.motion.pageReady(node,'file:1');assert.equal(f.animations.length,mode==='off'?0:1);}finally{f.done();}assert.equal(f.doc.count+f.media.count+f.observers(),0);});
test('Restored errors/checks are seeded; duplicate input/change does not replay, off/hidden outcomes consumed',()=>{const f=fixture();try{f.motion.activate();const n=f.node();f.motion.validation(n,'c:receiver','Required',{seed:true});f.motion.validation(n,'c:receiver','Required');assert.equal(f.animations.length,0);f.motion.check(n,'c',false,{seed:true});f.motion.check(n,'c',true);f.motion.check(n,'c',true);assert.equal(f.animations.length,1);f.motion.setMode('off');f.motion.validation(n,'c:note','Long');f.motion.check(n,'c',false);f.motion.setMode('auto');f.motion.validation(n,'c:note','Long');f.motion.check(n,'c',false);assert.equal(f.animations.length,1);f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));f.motion.pageRequested('f:2');f.motion.pageReady(n,'f:2');f.doc.hidden=false;f.doc.dispatchEvent(new Event('visibilitychange'));f.motion.pageReady(n,'f:2');assert.equal(f.animations.length,1);}finally{f.done();}});
test('OS reduction, hide, repeated dispose and reactivation cancel handles with balanced listeners/observer',()=>{const f=fixture();try{for(let i=0;i<8;i++){f.motion.activate();f.motion.activate();assert.equal(f.doc.count,2);assert.equal(f.media.count,1);assert.equal(f.observers(),1);f.motion.row(f.node());f.media.matches=true;f.media.dispatchEvent(new Event('change'));assert.ok(f.animations.at(-1).cancelled);f.media.matches=false;f.media.dispatchEvent(new Event('change'));f.motion.hide();f.motion.hide();assert.equal(f.doc.count+f.media.count+f.observers(),0);}f.motion.dispose();f.motion.activate();f.motion.row(f.node());assert.equal(f.doc.count+f.media.count+f.observers(),0);}finally{f.done();}});
