import test from 'node:test';
import assert from 'node:assert/strict';
import {mountScanFlowFeedback} from '../docs/flows/shared/motion/scan-flow-feedback.mjs';
class Target extends EventTarget{listeners=new Map();addEventListener(t,f,o){super.addEventListener(t,f,o);if(!this.listeners.has(t))this.listeners.set(t,new Set());this.listeners.get(t).add(f);}removeEventListener(t,f,o){super.removeEventListener(t,f,o);this.listeners.get(t)?.delete(f);}get count(){return [...this.listeners.values()].reduce((a,s)=>a+s.size,0);}}
function fixture(mode='auto'){
 const media=new Target();media.matches=false;const doc=new Target();doc.hidden=false;const animations=[];let visible=true,overlay=false;
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>k.includes('ease')?'linear':'140ms'})};const root=new Target();root.ownerDocument=doc;root.dataset={};root.hidden=false;root.getAttribute=()=>null;root.removeAttribute=()=>{};root.closest=s=>s==='[inert]'?null:{querySelector:()=>overlay};root.contains=n=>n.owner===root;
 const node=()=>({owner:root,isConnected:true,dataset:{},matches:()=>false,animate(frames,options){let resolve;const a={frames,options,cancelled:false,finished:new Promise(r=>resolve=r),cancel(){this.cancelled=true;resolve();}};animations.push(a);return a;}});
 const text=node(),warning=node(),spinner=node();root.querySelector=s=>s.includes('p17-status-spinner')?spinner:s==='.p17-warning'?warning:s==='.p17-warning>div'?text:null;root.querySelectorAll=()=>[];
 const previous=globalThis.window;globalThis.window={matchMedia:()=>media};const motion=mountScanFlowFeedback({root,prefix:'p04',requested:mode,isActive:()=>visible});
 return {motion,root,doc,media,animations,spinner,hide:()=>visible=false,show:()=>visible=true,overlay:v=>overlay=v,done(){motion.dispose();if(previous===undefined)delete globalThis.window;else globalThis.window=previous;}};
}
const state=(id='scan:1',panel='P17.S01')=>({attempts:[{eventId:id,kind:panel==='P17.S01'?'invalid':'blocked',raw:'BAD'}],accepted:[],exception:{panel,raw:'BAD'},unknown:false,busy:false});
for(const mode of ['auto','reduced','off'])test(`M17 repeated invalid feedback ${mode}: immediate state, no replay/mutation/stack`,()=>{const f=fixture(mode);try{f.motion.activate({attempts:[]});const s=state(),copy=structuredClone(s);f.motion.commit(s);assert.deepEqual(s,copy);assert.equal(f.animations.length,mode==='off'?0:1);if(mode!=='off')assert.equal(f.animations[0].options.duration,mode==='auto'?140:80);f.motion.beforeRender();f.motion.commit(s);assert.equal(f.animations.length,mode==='off'?0:1);f.motion.commit(state('scan:2'));assert.ok(f.animations.filter(a=>!a.cancelled).length<=1);assert.equal(s.accepted.length,0);}finally{f.done();}assert.equal(f.media.count+f.doc.count+f.root.count,0);});
test('M17 restored/off/hidden error events are consumed and never replayed on mount or mode change',()=>{const f=fixture();try{const s=state();f.motion.activate(s);f.motion.commit(s);assert.equal(f.animations.length,0);f.motion.setMode('off');f.motion.commit(state('scan:2'));f.motion.setMode('auto');f.motion.commit(state('scan:2'));f.doc.hidden=true;f.motion.commit(state('scan:3'));f.doc.hidden=false;f.motion.commit(state('scan:3'));assert.equal(f.animations.length,0);}finally{f.done();}});
test('Unknown spinner follows pending read, visibility, overlay and owner lifetime only',()=>{const f=fixture();try{const s={attempts:[],unknown:true,busy:false,request:{requestId:'r'}};f.motion.activate(s);f.motion.commit(s);assert.equal(f.spinner.dataset.running,'false');s.busy=true;f.motion.commit(s);assert.equal(f.spinner.dataset.running,'true');f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(f.spinner.dataset.running,'false');f.doc.hidden=false;f.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(f.spinner.dataset.running,'true');f.overlay(true);f.motion.commit(s);assert.equal(f.spinner.dataset.running,'false');f.overlay(false);f.motion.setMode('off');assert.equal(f.spinner.dataset.running,'false');f.motion.hide();assert.equal(f.doc.count+f.media.count,0);assert.deepEqual(s.request,{requestId:'r'});}finally{f.done();}});
test('P04/P05 repeated activation and disposal never accumulate motion listeners',()=>{const f=fixture();try{for(let i=0;i<10;i++){f.motion.activate({attempts:[]});assert.equal(f.doc.count,2);assert.equal(f.media.count,1);f.motion.activate({attempts:[]});assert.equal(f.doc.count,2);f.motion.hide();assert.equal(f.doc.count+f.media.count,0);}}finally{f.done();}assert.equal(f.root.count,0);});
