import test from 'node:test';
import assert from 'node:assert/strict';
import {mountComponentIssueMotion} from '../docs/flows/warranty-components/issue-motion.mjs';
class Target extends EventTarget{listeners=new Map();addEventListener(t,f,o){super.addEventListener(t,f,o);if(!this.listeners.has(t))this.listeners.set(t,new Set());this.listeners.get(t).add(f);}removeEventListener(t,f,o){super.removeEventListener(t,f,o);this.listeners.get(t)?.delete(f);}get count(){return [...this.listeners.values()].reduce((a,s)=>a+s.size,0);}}
function fixture(mode='auto'){
 const media=new Target();media.matches=false;const doc=new Target();doc.hidden=false;const root=new Target(),animations=[];let overlay=false,active=true;
 root.ownerDocument=doc;root.dataset={};root.getAttribute=()=>null;root.removeAttribute=k=>{if(k==='data-hn-motion-mode')delete root.dataset.hnMotionMode;};root.contains=n=>n.owner===root;root.closest=s=>s==='[inert]'?null:{querySelector:()=>overlay};root.querySelectorAll=()=>[];
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>k.includes('ease')?'linear':k.includes('row-feedback')?'160ms':k.includes('press')?'100ms':'140ms'})};
 const prior=globalThis.MutationObserver;let observers=0;globalThis.MutationObserver=class{constructor(fn){this.fn=fn;}observe(){observers++;}disconnect(){observers--;}};
 const node=()=>({owner:root,isConnected:true,dataset:{},matches:()=>false,animate(frames,options){let done;const a={frames,options,cancelled:false,finished:new Promise(r=>done=r),cancel(){this.cancelled=true;done();}};animations.push(a);return a;}});
 const motion=mountComponentIssueMotion({root,requested:mode,active:()=>active,media});
 return {motion,doc,root,media,animations,node,observers:()=>observers,overlay:v=>overlay=v,active:v=>active=v,done(){motion.dispose();if(prior===undefined)delete globalThis.MutationObserver;else globalThis.MutationObserver=prior;}};
}

for(const mode of ['auto','reduced','off'])test('M19 '+mode+': only explicit accepted event/confirmed receipt; seed and repeat never replay',()=>{const f=fixture(mode);try{f.motion.activate();f.motion.seedReceipt({id:'old'});f.motion.posted(f.node(),{id:'old',status:'POSTED'});f.motion.posted(f.node(),{id:'bad',status:'UNKNOWN'});assert.equal(f.animations.length,0);f.motion.accepted(f.node());f.motion.posted(f.node(),{id:'new',status:'POSTED'});const n=f.animations.length;assert.equal(n,mode==='off'?0:2);f.motion.posted(f.node(),{id:'new',status:'POSTED'});assert.equal(f.animations.length,n);f.overlay(true);f.motion.posted(f.node(),{id:'hidden',status:'POSTED'});f.overlay(false);f.motion.posted(f.node(),{id:'hidden',status:'POSTED'});assert.equal(f.animations.length,n);}finally{f.done();}});
test('M19 hide/dispose/OS/hidden cancel without accumulating listeners',()=>{const f=fixture();try{for(let i=0;i<4;i++){f.motion.activate();f.motion.accepted(f.node());f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(f.animations.at(-1).cancelled,true);f.doc.hidden=false;f.motion.accepted(f.node());f.media.matches=true;f.media.dispatchEvent(new Event('change'));assert.equal(f.animations.at(-1).cancelled,true);f.media.matches=false;f.motion.hide();f.motion.hide();assert.equal(f.doc.count+f.media.count+f.root.count+f.observers(),0);}f.motion.dispose();f.motion.activate();assert.equal(f.doc.count+f.media.count+f.root.count+f.observers(),0);}finally{f.done();}});
test('M19 demo and live receipts sharing display number do not suppress a distinct request result',()=>{const f=fixture();try{f.motion.activate();f.motion.seedReceipt({id:'XLK-DEMO-0001',caseId:'BH-001',requestId:'demo'});f.motion.posted(f.node(),{id:'XLK-DEMO-0001',caseId:'BH-001',requestId:'live',status:'POSTED'});assert.equal(f.animations.length,1);}finally{f.done();}});
