import test from 'node:test';import assert from 'node:assert/strict';
import {mountPostedHistoryMotion} from '../docs/flows/warranty-components/history-motion.mjs';
class Target extends EventTarget{listeners=new Map();addEventListener(t,f,o){super.addEventListener(t,f,o);if(!this.listeners.has(t))this.listeners.set(t,new Set());this.listeners.get(t).add(f);}removeEventListener(t,f,o){super.removeEventListener(t,f,o);this.listeners.get(t)?.delete(f);}get count(){return [...this.listeners.values()].reduce((a,s)=>a+s.size,0);}}
function fixture(mode='auto'){
 const media=new Target();media.matches=false;const doc=new Target();doc.hidden=false;const root=new Target(),animations=[];let overlay=false,active=true;
 root.ownerDocument=doc;root.dataset={};root.getAttribute=()=>null;root.removeAttribute=k=>{if(k==='data-hn-motion-mode')delete root.dataset.hnMotionMode;};root.contains=n=>n.owner===root;root.closest=()=>null;
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>k.includes('ease')?'linear':'140ms'})};
 const prior=globalThis.MutationObserver;let observers=0;globalThis.MutationObserver=class{observe(){observers++;}disconnect(){observers--;}};
 const node=()=>({owner:root,isConnected:true,dataset:{},matches:()=>false,animate(frames,options){let done;const a={frames,options,cancelled:false,finished:new Promise(r=>done=r),cancel(){this.cancelled=true;done();}};animations.push(a);return a;}});
 const motion=mountPostedHistoryMotion({root,screen:{querySelector:()=>overlay},requested:mode,active:()=>active,media});
 return {motion,doc,root,media,animations,node,observers:()=>observers,overlay:v=>overlay=v,active:v=>active=v,done(){motion.dispose();if(prior===undefined)delete globalThis.MutationObserver;else globalThis.MutationObserver=prior;}};
}
for(const mode of ['auto','reduced','off'])test('M20 '+mode+' error/empty opacity only; no loading/ready/Back replay',()=>{const f=fixture(mode);try{f.motion.activate();f.motion.state('caseA','loading',f.node());f.motion.state('caseA','ready',f.node());assert.equal(f.animations.length,0);f.motion.state('caseA','error',f.node());f.motion.state('caseA','error',f.node());f.motion.hide();f.motion.activate();f.motion.state('caseA','error',f.node());f.motion.state('caseB','empty',f.node());assert.equal(f.animations.length,mode==='off'?0:2);for(const a of f.animations){assert.equal(a.options.duration,mode==='reduced'?80:140);assert.ok(a.frames.every(x=>!x.transform));}f.motion.state('caseA','loading',f.node());f.motion.state('caseA','error',f.node());assert.equal(f.animations.length,mode==='off'?0:3);}finally{f.done();}});
test('Hidden/off/overlay outcomes consumed, never replay when visible',()=>{const f=fixture();try{f.motion.activate();f.overlay(true);f.motion.state('A','empty',f.node());f.overlay(false);f.motion.state('A','empty',f.node());f.doc.hidden=true;f.motion.state('B','error',f.node());f.doc.hidden=false;f.motion.state('B','error',f.node());f.motion.setMode('off');f.motion.state('C','empty',f.node());f.motion.setMode('auto');f.motion.state('C','empty',f.node());assert.equal(f.animations.length,0);}finally{f.done();}});
test('Repeated activate/hide/dispose releases all listeners/observers and cancels handles',()=>{const f=fixture();try{for(let i=0;i<8;i++){f.motion.activate();f.motion.activate();f.motion.state(i,'error',f.node());f.media.matches=true;f.media.dispatchEvent(new Event('change'));assert.equal(f.animations.at(-1).cancelled,true);f.media.matches=false;f.motion.hide();f.motion.hide();assert.equal(f.doc.count+f.media.count+f.root.count+f.observers(),0);}f.motion.dispose();f.motion.activate();assert.equal(f.doc.count+f.media.count+f.observers(),0);}finally{f.done();}});
test('Security cancellation suspends effects until owner remounts; hidden spinner policy',()=>{const f=fixture();try{f.motion.activate();f.motion.state('A','error',f.node());f.motion.cancel();assert.equal(f.animations[0].cancelled,true);assert.equal(f.root.dataset.p20MotionPaused,'true');f.motion.state('B','empty',f.node());assert.equal(f.animations.length,1);f.motion.hide();f.motion.activate();f.motion.state('C','empty',f.node());assert.equal(f.animations.length,2);f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(f.animations[1].cancelled,true);}finally{f.done();}});
