import test from 'node:test';import assert from 'node:assert/strict';
import {mountComponentResumeMotion} from '../docs/flows/warranty-components/resume-motion.mjs';
class Target extends EventTarget{listeners=new Map();addEventListener(t,f,o){super.addEventListener(t,f,o);if(!this.listeners.has(t))this.listeners.set(t,new Set());this.listeners.get(t).add(f);}removeEventListener(t,f,o){super.removeEventListener(t,f,o);this.listeners.get(t)?.delete(f);}get count(){return [...this.listeners.values()].reduce((a,s)=>a+s.size,0);}}
function fixture(mode='auto'){
 const media=new Target();media.matches=false;const doc=new Target();doc.hidden=false;const root=new Target(),animations=[];let overlay=false,active=true;
 root.ownerDocument=doc;root.dataset={};root.getAttribute=()=>null;root.removeAttribute=k=>{if(k==='data-hn-motion-mode')delete root.dataset.hnMotionMode;};root.contains=n=>n.owner===root;root.closest=()=>null;
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>k.includes('ease')?'linear':'140ms'})};
 const prior=globalThis.MutationObserver;let observers=0;globalThis.MutationObserver=class{observe(){observers++;}disconnect(){observers--;}};
 const node=()=>({owner:root,isConnected:true,dataset:{},matches:()=>false,animate(frames,options){let done;const a={frames,options,cancelled:false,finished:new Promise(r=>done=r),cancel(){this.cancelled=true;done();}};animations.push(a);return a;}});
 const motion=mountComponentResumeMotion({root,screen:{querySelector:()=>overlay},requested:mode,active:()=>active,media});
 return {motion,doc,root,media,animations,node,observers:()=>observers,overlay:v=>overlay=v,active:v=>active=v,done(){motion.dispose();if(prior===undefined)delete globalThis.MutationObserver;else globalThis.MutationObserver=prior;}};
}
for(const mode of ['auto','reduced','off'])test('M21 '+mode+' checkpoint notice consumed once across Back/hide, opacity only',()=>{const f=fixture(mode);try{f.motion.activate();f.motion.reconcile('doc-checkpoint-conflict',f.node());f.motion.reconcile('doc-checkpoint-conflict',f.node());f.motion.hide();f.motion.activate();f.motion.reconcile('doc-checkpoint-conflict',f.node());assert.equal(f.animations.length,mode==='off'?0:1);if(f.animations[0]){assert.equal(f.animations[0].options.duration,mode==='reduced'?80:140);assert.ok(f.animations[0].frames.every(x=>!x.transform));}}finally{f.done();}});
test('Hidden/off/overlay outcomes consumed without late notice on reveal',()=>{const f=fixture();try{f.motion.activate();f.overlay(true);f.motion.reconcile('A',f.node());f.overlay(false);f.motion.reconcile('A',f.node());f.doc.hidden=true;f.motion.reconcile('B',f.node());f.doc.hidden=false;f.motion.reconcile('B',f.node());f.motion.setMode('off');f.motion.reconcile('C',f.node());f.motion.setMode('auto');f.motion.reconcile('C',f.node());assert.equal(f.animations.length,0);}finally{f.done();}});
test('Eight activate/hide cycles release media/document/root listeners and observer; cancel active handles',()=>{const f=fixture();try{for(let i=0;i<8;i++){f.motion.activate();f.motion.activate();f.motion.reconcile(i+1,f.node());f.media.matches=true;f.media.dispatchEvent(new Event('change'));assert.equal(f.animations.at(-1).cancelled,true);f.media.matches=false;f.motion.hide();f.motion.hide();assert.equal(f.doc.count+f.media.count+f.root.count+f.observers(),0);}f.motion.dispose();f.motion.activate();assert.equal(f.doc.count+f.media.count+f.root.count+f.observers(),0);}finally{f.done();}});
test('Security cancellation blocks effects until remount, visibility cancels active animation',()=>{const f=fixture();try{f.motion.activate();f.motion.reconcile('A',f.node());f.motion.cancel();assert.equal(f.animations[0].cancelled,true);assert.equal(f.root.dataset.p21MotionPaused,'true');f.motion.reconcile('B',f.node());assert.equal(f.animations.length,1);f.motion.hide();f.motion.activate();f.motion.reconcile('C',f.node());assert.equal(f.animations.length,2);f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));assert.equal(f.animations[1].cancelled,true);}finally{f.done();}});
