import test from 'node:test';
import assert from 'node:assert/strict';
import {mountNfcAuditMotion} from '../docs/flows/history/nfc-audit-motion.mjs';
function fixture(){
 const doc=new EventTarget(),media=new EventTarget(),root=new EventTarget();media.matches=false;doc.hidden=false;
 Object.assign(root,{dataset:{},ownerDocument:doc,getAttribute:()=>null,removeAttribute(){delete this.dataset.hnMotionMode;},contains:n=>!!n?.ours,closest:()=>null});
 doc.defaultView={getComputedStyle:()=>({getPropertyValue:k=>({'--hn-motion-press':root.dataset.hnMotionMode==='auto'?'100ms':'0ms','--hn-motion-feedback':'140ms','--hn-motion-ease-standard':'linear'})[k]||''})};
 const animations=[],node=()=>({dataset:{},ours:true,isConnected:true,matches:()=>false,animate(frames,options){let done;const a={frames,options,cancelled:false,finished:new Promise(r=>done=r),cancel(){this.cancelled=true;done();}};animations.push(a);return a;}});
 return {root,doc,media,animations,node};
}
test('M22 filter/indicator only after changed committed filters; seed/Back never entrance',()=>{const f=fixture(),m=mountNfcAuditMotion(f),n=f.node(),t=f.node();m.activate();m.seed('all');m.filter('all',n,t);assert.equal(f.animations.length,0);m.filter('uid',n,t);assert.deepEqual(f.animations.map(a=>a.options.duration),[140,140]);m.filter('uid',n,t);assert.equal(f.animations.length,2);m.seed('uid');m.filter('uid',n,t);assert.equal(f.animations.length,2);m.dispose();assert.ok(f.animations.every(a=>a.cancelled));});
test('M22 OS reduced strips transforms; off/hidden consumed without replay',()=>{const f=fixture(),m=mountNfcAuditMotion(f),n=f.node();m.activate();m.seed('0');m.filter('1',n);f.media.matches=true;f.media.dispatchEvent(new Event('change'));assert.equal(f.animations[0].cancelled,true);m.filter('2',n);assert.equal(f.animations.at(-1).options.duration,80);m.setMode('off');m.filter('3',n);assert.equal(f.animations.length,2);m.setMode('auto');m.filter('3',n);assert.equal(f.animations.length,2);f.doc.hidden=true;f.doc.dispatchEvent(new Event('visibilitychange'));m.filter('4',n);f.doc.hidden=false;m.filter('4',n);assert.equal(f.animations.length,2);m.dispose();});
test('M22 inactive/security owner never plays; cancel contains no domain callback',()=>{const f=fixture();let active=false;const m=mountNfcAuditMotion({...f,active:()=>active}),n=f.node();m.activate();m.seed('0');m.filter('1',n);assert.equal(f.animations.length,0);active=true;m.filter('2',n);m.cancel();assert.equal(f.animations[0].cancelled,true);m.dispose();});
test('M22 repeated lifecycle removes every listener and cancels all handles',()=>{const f=fixture();let count=0;for(const target of [f.doc,f.media,f.root]){const seen=new Map(),add=target.addEventListener.bind(target),remove=target.removeEventListener.bind(target);target.addEventListener=(t,fn,...rest)=>{if(!seen.has(t))seen.set(t,new Set());if(!seen.get(t).has(fn)){seen.get(t).add(fn);count++;}add(t,fn,...rest);};target.removeEventListener=(t,fn,...rest)=>{if(seen.get(t)?.delete(fn))count--;remove(t,fn,...rest);};}const m=mountNfcAuditMotion({...f,hub:true});for(let i=0;i<8;i++){m.activate();m.activate();m.seed('0');m.filter('1',f.node());m.hide();assert.equal(count,0);}m.dispose();m.activate();assert.equal(count,0);assert.ok(f.animations.every(a=>a.cancelled));});
