import test from 'node:test';
import assert from 'node:assert/strict';
import {createNotificationPreview,NOTIFICATION_PAGE_SIZE} from '../docs/flows/notifications/notification-model.mjs';
import {createNotificationPages} from '../docs/flows/notifications/notification-pages.mjs';
const state=()=>({previewReady:true,session:{namespace:'hn-scanner-auth-preview-v1',authSessionId:'s1',actor:{id:'a1'},warehouse:{id:'fixture-hoa-nam'},permissions:{warehouseOperations:true}}});
function setup(){let current=state();const source=createNotificationPreview({getState:()=>current,delay:2});source.useReviewDataset('extended');return {source,pages:createNotificationPages({source}),change:fn=>fn(current)};}
test('10 first, +10 only when requested; 37 ends without extra request',async()=>{const {source,pages}=setup();assert.equal(NOTIFICATION_PAGE_SIZE,10);assert.equal(source.metrics().pageCalls,0);for(const count of [10,20,30,37]){await pages.load('all');assert.equal(pages.snapshot('all').items.length,count);}assert.equal(source.metrics().pageCalls,4);assert.equal(pages.snapshot('all').hasMore,false);await pages.load('all');assert.equal(source.metrics().pageCalls,4);});
test('rapid double click shares one request; all and unread cache independently',async()=>{const {source,pages}=setup();const a=pages.load('all'),b=pages.load('all');assert.equal(a,b);await a;await pages.load('unread');assert.equal(source.metrics().pageCalls,2);assert.equal(pages.snapshot('all').items.length,10);assert.equal(pages.snapshot('unread').items.length,10);assert.equal(source.unread(),24);});
test('page failure preserves existing items/cursor, retry does not skip',async()=>{const {source,pages}=setup();await pages.load('all');const before=pages.snapshot('all');await pages.load('all',{fail:true});assert.deepEqual(pages.snapshot('all').items,before.items);assert.equal(pages.snapshot('all').error,true);await pages.load('all');assert.deepEqual(pages.snapshot('all').items,source.list().slice(0,20));});
test('reading the cursor anchor does not shift offsets or skip unread IDs',async()=>{const {source,pages}=setup();await pages.load('unread');const first=pages.snapshot('unread').items,anchor=first.at(-1).id;await source.markRead(anchor);pages.markRead(anchor);assert.equal(pages.snapshot('unread').items.length,9);assert.equal(source.metrics().pageCalls,1);await pages.load('unread');const expected=source.list().filter(r=>!r.read).slice(0,19);assert.deepEqual(pages.snapshot('unread').items,expected);assert.equal(pages.snapshot('unread').items.length,19);});
test('page response cannot leak after actor/session/warehouse change',async()=>{for(const change of [s=>s.session.actor.id='a2',s=>s.session.authSessionId='s2',s=>s.session.warehouse.id='other']){const {pages,change:mutate}=setup();const pending=pages.load('all');mutate(change);assert.equal((await pending).kind,'stale');assert.equal(pages.snapshot('all').items.length,0);assert.equal(pages.snapshot('all').busy,false);}});
test('dataset reset/dispose discards in-flight pages',async()=>{const {source,pages}=setup();const pending=pages.load('all');source.useReviewDataset('baseline');pages.reset();assert.equal((await pending).kind,'stale');assert.equal(pages.snapshot('all').items.length,0);const second=pages.load('all');pages.dispose();assert.equal((await second).kind,'stale');});
test('overlapping page IDs merge without duplicate cards',async()=>{let calls=0;const source={scope:()=>1,async loadPage(){return ++calls===1?{kind:'page',items:[{id:'a',read:false},{id:'b',read:false}],total:3,nextCursor:'b'}:{kind:'page',items:[{id:'b',read:true},{id:'c',read:false}],total:3,nextCursor:null};}};const pages=createNotificationPages({source});await pages.load('all');await pages.load('all');assert.deepEqual(pages.snapshot('all').items,[{id:'a',read:false},{id:'b',read:true},{id:'c',read:false}]);});
test('short and empty source do not create fake load-more',async()=>{const current=state();for(const seed of [()=>[],undefined]){const source=createNotificationPreview({getState:()=>current,delay:1,...(seed?{seed}:{})}),pages=createNotificationPages({source});await pages.load('all');assert.equal(pages.snapshot('all').items.length,seed?0:5);assert.equal(pages.snapshot('all').hasMore,false);}});
test('cursor cannot be reused across filter or session',async()=>{const {source,change}=setup();const one=await source.loadPage({filter:'all'});assert.equal((await source.loadPage({filter:'unread',cursor:one.nextCursor})).kind,'denied');change(s=>s.session.authSessionId='s2');assert.equal((await source.loadPage({filter:'all',cursor:one.nextCursor})).kind,'denied');});
test('equal timestamps use deterministic ID order',async()=>{const source=createNotificationPreview({getState:state,delay:1,seed:()=>Array.from({length:23},(_,i)=>({id:String(i).padStart(2,'0'),day:'2026-09-09',time:'09:00',read:false}))});const pages=createNotificationPages({source});await pages.load('all');await pages.load('all');await pages.load('all');assert.equal(new Set(pages.snapshot('all').items.map(r=>r.id)).size,23);assert.deepEqual(pages.snapshot('all').items,source.list());});
test('read outside loaded unread page decrements total once without loading replacements',async()=>{const {source,pages}=setup();await pages.load('unread');const id=source.list().filter(r=>!r.read).at(-1).id;await source.markRead(id);pages.markRead(id);pages.markRead(id);assert.equal(pages.snapshot('unread').total,23);assert.equal(pages.snapshot('unread').items.length,10);assert.equal(source.metrics().pageCalls,1);});
