import test from 'node:test';import assert from 'node:assert/strict';
import {createDraftRetention} from '../docs/flows/recovery-shift/draft-retention.mjs';
import {createInboundFlow} from '../docs/flows/inbound/inbound-flow.mjs';
import {createInboundFixtureAdapter} from '../docs/flows/inbound/fixture-adapter.mjs';
import {createOutboundFlow} from '../docs/flows/outbound/outbound-flow.mjs';
import {createOutboundFixtureAdapter} from '../docs/flows/outbound/fixture-adapter.mjs';
const state=()=>({previewReady:true,session:{namespace:'hn-scanner-auth-preview-v1',authSessionId:'fixture-session',actor:{id:'a',name:'Minh Anh'},warehouse:{id:'w',name:'Kho Hoa Nam',active:true},permissions:{warehouseOperations:true}}});
function setup(op){const s=state(),adapter=op==='inbound'?createInboundFixtureAdapter({delay:0}):createOutboundFixtureAdapter({delay:0}),flow=op==='inbound'?createInboundFlow({adapter,getState:()=>s}):createOutboundFlow({adapter,getState:()=>s});flow.start();flow.note('Ghi chú nguyên văn 🌸');return {s,flow,adapter};}
for(const op of ['inbound','outbound'])test(op+' checkpoint survives logout owner disposal and restores exact identity/note/codes',()=>{const original=setup(op),store=createDraftRetention(),run={operation:op,...original.flow.snapshot()};run.accepted=[{raw:'HN12345',sku:'XP-420B',quantity:1}];run.attempts=[{raw:'HN12345',kind:'valid'}];assert.equal(store.retain(original.s,[run]).kind,'retained');original.flow.dispose();const next=state();next.session.authSessionId='new-session';const adapter=op==='inbound'?createInboundFixtureAdapter({delay:0}):createOutboundFixtureAdapter({delay:0}),owner=op==='inbound'?createInboundFlow({adapter,getState:()=>next}):createOutboundFlow({adapter,getState:()=>next});assert.equal(owner.restorePreview(store.read(next)[0]),true);const got=owner.snapshot();assert.deepEqual(got.document,run.document);assert.deepEqual(got.accepted,run.accepted);assert.deepEqual(got.attempts,run.attempts);assert.equal(owner.restorePreview(run),false);assert.notEqual(adapter.makeDocument(next.session).documentId,run.document.documentId);store.acknowledge(next);assert.deepEqual(store.read(next),[]);owner.dispose();});
test('store is account/warehouse/namespace scoped and clones records',()=>{const {s,flow}=setup('inbound'),store=createDraftRetention(),run={operation:'inbound',...flow.snapshot()};store.retain(s,[run]);run.document.note='changed after capture';const copy=store.read(s);assert.equal(copy[0].document.note,'Ghi chú nguyên văn 🌸');copy[0].document.note='changed by reader';assert.equal(store.read(s)[0].document.note,'Ghi chú nguyên văn 🌸');for(const field of ['actor','warehouse']){const other=structuredClone(s);other.session[field].id='other';assert.deepEqual(store.read(other),[]);}const other=structuredClone(s);other.session.namespace='other';assert.deepEqual(store.read(other),[]);flow.dispose();});
test('busy/UNKNOWN/foreign source blocks logout retention without overwriting prior snapshot',()=>{const {s,flow}=setup('inbound'),store=createDraftRetention(),run={operation:'inbound',...flow.snapshot()};store.retain(s,[run]);for(const change of [{busy:true},{unknown:true},{saveUnknown:true},{document:{...run.document,actorId:'other'}}])assert.equal(store.retain(s,[{...run,...change}]).kind,'blocked');assert.equal(store.read(s).length,1);flow.dispose();});
test('new page/reset creates an empty store; restoration rejects missing permissions',()=>{const {s,flow}=setup('inbound'),store=createDraftRetention(),run={operation:'inbound',...flow.snapshot()};store.retain(s,[run]);assert.deepEqual(createDraftRetention().read(s),[]);s.session.permissions.warehouseOperations=false;assert.deepEqual(store.read(s),[]);const owner=createInboundFlow({adapter:createInboundFixtureAdapter({delay:0}),getState:()=>s});assert.equal(owner.restorePreview(run),false);owner.dispose();flow.dispose();});
