import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorkflow,createPreviewAdapter,B14_AGGREGATE,fingerprint} from '../docs/flows/recovery-shift/model.mjs';
function setup(){let auth={previewReady:true,session:{namespace:'preview',authSessionId:'session-1',actor:{id:'a'},warehouse:{id:'w',active:true},permissions:{warehouseOperations:true}}};let rows=[{operation:'inbound',document:{documentId:'pn-1',actorId:'a',warehouseId:'w',scanSessionId:'scan-1',version:3,note:'Ghi chú 🌸'},accepted:[{raw:'serial-1'}],request:null,busy:false,unknown:false}];const adapter=createPreviewAdapter({delay:1,now:()=> '2026-09-29T10:30:00.000Z'});const flow=createWorkflow({adapter,getState:()=>auth,getRecords:()=>rows,id:()=> 'request-1'});return {adapter,flow,auth,rows};}
test('A01 recovery only records support request; username is not display name',async()=>{const {flow}=setup();const r=await flow.run('recovery',' minhanh ');assert.equal(r.request.username,'minhanh');assert.equal(r.kind,'verified');assert.equal(r.time,'2026-09-29T10:30:00.000Z');assert.equal(r.request.action,'recovery');});
test('A02 empty recovery does not call adapter',async()=>{const {flow,adapter}=setup();assert.equal((await flow.run('recovery','  ')).kind,'invalid');assert.equal(adapter.metrics().recovery,0);});
for(const mode of ['error','blocked','unknown'])test('A02 '+mode+' cannot create receipt',async()=>{const {flow,adapter}=setup();adapter.setScenario(mode);await flow.run('recovery','minhanh');assert.equal(flow.snapshot().recovery,null);});
test('A03 unfinished blocks end and preserves exact source',async()=>{const {flow,rows,adapter}=setup(),before=fingerprint(rows);assert.equal((await flow.run('end')).kind,'guarded');assert.equal(adapter.metrics().end,0);assert.equal(fingerprint(rows),before);});
test('A04 successful save preserves IDs/version/codes; end keeps auth and draft',async()=>{const {flow,rows,auth}=setup(),before=fingerprint(rows);await flow.run('save');assert.equal(flow.snapshot().unsaved.length,0);const r=await flow.run('end');assert.equal(r.kind,'verified');assert.equal(fingerprint(rows),before);assert.equal(auth.session.authSessionId,'session-1');assert.equal(flow.snapshot().summary.request.records[0].document.version,3);});
test('A04 failed save never allows end',async()=>{const {flow,adapter}=setup();adapter.setScenario('error');await flow.run('save');assert.equal((await flow.run('end')).kind,'guarded');assert.equal(flow.snapshot().summary,null);});
test('A04 unknown save keeps request, rejects retry until reconciliation',async()=>{const {flow,adapter}=setup();adapter.setScenario('timeout-recorded');await flow.run('save');const pending=flow.snapshot().pending;assert.equal((await flow.run('save')).kind,'guarded');assert.equal(adapter.metrics().save,1);assert.equal((await flow.check()).kind,'verified');assert.equal(flow.snapshot().pending,null);assert.equal(flow.snapshot().unsaved.length,0);assert.equal(pending.records[0].document.scanSessionId,'scan-1');});
test('unresolved UNKNOWN remains blocked even after mode changes',async()=>{const {flow,adapter}=setup();adapter.setScenario('unknown');await flow.run('save');adapter.setScenario('ready');assert.equal((await flow.check()).kind,'unknown');assert.equal((await flow.run('end')).kind,'guarded');});
test('double submission sends once',async()=>{const {flow,adapter}=setup();const first=flow.run('recovery','minhanh');assert.equal((await flow.run('recovery','minhanh')).kind,'guarded');await first;assert.equal(adapter.metrics().recovery,1);});
test('source changes after save invalidate checkpoint',async()=>{const {flow,rows}=setup();await flow.run('save');rows[0].document.note+=' changed';assert.equal(flow.snapshot().unsaved.length,1);assert.equal((await flow.run('end')).kind,'guarded');});
for(const key of ['unknown','busy','saveUnknown'])test('source '+key+' cannot be saved by shift',async()=>{const {flow,rows,adapter}=setup();rows[0][key]=true;assert.equal((await flow.run('save')).kind,'source-unknown');assert.equal(adapter.metrics().save,0);});
test('actor/warehouse/permission guards and session expiry reject writes',async()=>{for(const mutate of [s=>s.auth.session.actor.id='other',s=>s.auth.session.warehouse.id='other',s=>s.auth.session.permissions.warehouseOperations=false,s=>s.auth.session.warehouse.active=false,s=>s.rows[0].document.actorId='other']){const s=setup();mutate(s);assert.equal((await s.flow.run('save')).kind,'guarded');}});
test('late receipt after logout/disposal cannot create summary',async()=>{const {flow,auth}=setup();const p=flow.run('save');auth.session.authSessionId='other';assert.equal((await p).kind,'stale');assert.equal(flow.snapshot().summary,null);const s=setup();const q=s.flow.run('recovery','minhanh');s.flow.dispose();assert.equal((await q).kind,'stale');});
test('A05 aggregate is defined separate 12+6+4+3+5=30, not loaded rows',async()=>{const {flow}=setup();await flow.run('save');await flow.run('end');assert.equal(flow.snapshot().summary.aggregate.total,30);assert.equal(flow.snapshot().records.length,1);assert.equal(B14_AGGREGATE.inbound+B14_AGGREGATE.outbound+B14_AGGREGATE.warranty+B14_AGGREGATE.nfc+B14_AGGREGATE.documents,30);});
test('mismatched adapter receipt cannot signal success',async()=>{const s=setup();s.adapter.request=async request=>({kind:'verified',request:{...request,id:'wrong'},namespace:'hn-recovery-shift-preview-v1',id:'bad',time:new Date().toISOString()});assert.equal((await s.flow.run('save')).kind,'unknown');assert.equal(s.flow.snapshot().unsaved.length,1);});
