import test from 'node:test';
import assert from 'node:assert/strict';
import {createIssueFlow} from '../docs/flows/warranty-components/issue-model.mjs';
import {createIssueFixture} from '../docs/flows/warranty-components/issue-fixture.mjs';
import {createRetainedIssue,createCheckpointFixture} from '../docs/flows/warranty-components/resume-model.mjs';
import {caseDetails} from '../docs/flows/warranty/warranty-model.mjs';
import {writeWarrantyCase,resetWarrantyCases} from '../docs/flows/shared/warranty-cases.mjs';
import {waitingWebResult} from '../docs/flows/shared/waiting-web.mjs';
const auth=()=>({previewReady:true,session:{authSessionId:'p24',actor:{id:'p24-actor'},warehouse:{id:'fixture-hoa-nam',active:true},permissions:{warehouseOperations:true}}});
function setup(){const state=auth(),base=createIssueFixture({delay:0});let available=12,issuable=true;const adapter={...base,lookup(code){const r=base.lookup(code);return code==='BOX-LK-0002-01'?{...r,available,issuable,reason:'Lý do gốc từ nguồn: hộp chưa nhập.'}:r;}};return {state,adapter,stock:v=>available=v,reject:()=>issuable=false,flow:createIssueFlow({getState:()=>state,caseId:'BH-001',adapter})};}
test('A02 adapter rejection keeps document, accepted codes and original reason',()=>{const {flow}=setup();flow.scan('LK0001-HN001');const before=flow.snapshot();const r=flow.scan('BOX-NOT-RECEIVED');assert.equal(r.kind,'unavailable');assert.match(r.error,/chưa được ghi nhận nhập kho/);assert.deepEqual(flow.snapshot(),before);});
test('A01 unknown or changed stock during sheet rejects confirm without line/version changes',()=>{for(const value of [null,undefined,0,1]){const {flow,stock}=setup();flow.scan('BOX-LK-0002-01');const before=flow.snapshot();stock(value);assert.equal(flow.quantity(2).kind,'invalid');assert.deepEqual(flow.snapshot(),before);}});
test('A02 BOX becomes unissuable between lookup, confirmation and Post',async()=>{const {flow,reject,adapter}=setup();flow.scan('BOX-LK-0002-01');reject();assert.match(flow.quantity(2).error,/Lý do gốc/);assert.equal((await flow.post()).kind,'invalid');assert.equal(adapter.metrics().post,0);const x=setup();x.flow.scan('BOX-LK-0002-01');x.flow.quantity(2);x.reject();assert.match((await x.flow.post()).error,/Lý do gốc/);assert.equal(x.adapter.metrics().post,0);});
test('A04 closed case rejects stale sheet, direct submit and retained resume writes',async()=>{const state=auth(),adapter=createIssueFixture({delay:0}),flow=createRetainedIssue({getState:()=>state,caseId:'BH-001',adapter,source:createCheckpointFixture({delay:0})});try{flow.scan('LK0001-HN001');flow.scan('BOX-LK-0002-01');const before=flow.snapshot();writeWarrantyCase({...caseDetails('BH-001'),status:'Đã trả khách'});await flow.verify();assert.equal(flow.quantity(2).kind,'invalid');assert.equal(flow.scan('BOX-LK-0002-01').kind,'invalid');assert.equal((await flow.post()).kind,'invalid');assert.deepEqual(flow.snapshot().lines,before.lines);assert.equal(adapter.metrics().post,0);}finally{flow.dispose();resetWarrantyCases();}});
test('A03 waiting result cannot be fabricated from UNKNOWN, step4 or POSTED',()=>{for(const state of [{step:4},{recorded:true,outcome:'posted'},{recorded:true,outcome:'recorded',unknown:true}])assert.equal(waitingWebResult({state}),'');});
test('A03 result count is distinct accepted codes not quantity; missing time remains unknown; escapes raw values',()=>{const html=waitingWebResult({state:{recorded:true,outcome:'recorded',document:{number:'PN-<1>',warehouseName:'Kho Hoa Nam'},accepted:[{quantity:12}]}});assert.match(html,/1 mã/);assert.doesNotMatch(html,/12 mã/);assert.match(html,/Chưa xác minh/);assert.match(html,/PN-&lt;1&gt;/);});
