import test from 'node:test';
import assert from 'node:assert/strict';
import {createInboundFlow} from '../docs/flows/inbound/inbound-flow.mjs';
import {createInboundFixtureAdapter} from '../docs/flows/inbound/fixture-adapter.mjs';
import {createOutboundFlow} from '../docs/flows/outbound/outbound-flow.mjs';
import {createOutboundFixtureAdapter} from '../docs/flows/outbound/fixture-adapter.mjs';
import {createNfcFlow} from '../docs/flows/nfc/nfc-flow.mjs';
import {createNfcFixtureAdapter} from '../docs/flows/nfc/fixture-adapter.mjs';
import {fixtureGeography,chooseFixtureAddress} from './fixtures/outbound-geography.mjs';
const auth=()=>({previewReady:true,session:{actor:{id:'a',name:'Minh Anh',role:'Nhân viên kho'},warehouse:{id:'fixture-hoa-nam',name:'Kho Hoa Nam',active:true},permissions:{warehouseOperations:true}}});
function stock(outbound=false){const state=auth(),adapter=outbound?createOutboundFixtureAdapter({delay:0}):createInboundFixtureAdapter({delay:0}),flow=outbound?createOutboundFlow({adapter,getState:()=>state,geography:fixtureGeography()}):createInboundFlow({adapter,getState:()=>state});flow.start();if(outbound)chooseFixtureAddress(flow);flow.next();flow.scan('HN12345');return {state,adapter,flow};}
for(const outbound of [false,true]){
 const owner=outbound?'P05':'P04';
 test(`P17.A01 ${owner} invalid raw retained; retry/navigation cannot change existing accepted lines`,()=>{const {flow}=stock(outbound),before=flow.snapshot(),raw=' Không tìm thấy\nĐỒNG '.repeat(8);assert.equal(flow.scan(raw),'invalid');assert.equal(flow.snapshot().exception.panel,'P17.S01');assert.equal(flow.snapshot().exception.raw,raw);assert.deepEqual(flow.snapshot().accepted,before.accepted);flow.dismissException();flow.dismissException();assert.deepEqual(flow.snapshot().document,before.document);assert.equal(flow.scan('HN12345'),'duplicate');assert.deepEqual(flow.snapshot().accepted,before.accepted);});
 test(`P17.A04 ${owner} timeout receipt retains request and single record; never Posts`,async()=>{const {flow,adapter}=stock(outbound);flow.next();adapter.setOutcome('timeout-recorded');await flow.send();const before=flow.snapshot();assert.equal(await flow.send(),false);await Promise.all([flow.check(),flow.check(),flow.send()]);assert.equal(flow.snapshot().outcome,'recorded');assert.deepEqual(flow.snapshot().request,before.request);assert.equal(adapter.metrics().recordCalls,1);assert.equal(adapter.metrics().inventoryDelta,0);});
 test(`P17.A05 ${owner} absent status API never retries or fabricates a result`,async()=>{const {flow,adapter}=stock(outbound);flow.next();adapter.setOutcome('unknown');await flow.send();const before=flow.snapshot();delete adapter.check;assert.equal(flow.canCheck(),false);assert.equal(await flow.check(),false);assert.equal(await flow.send(),false);assert.equal(flow.snapshot().unknown,true);assert.deepEqual(flow.snapshot().request,before.request);assert.match(flow.snapshot().message,/Chưa có nguồn/);assert.equal(adapter.metrics().recordCalls,1);});
 test(`P17 ${owner} not-recorded with mismatched request or absent retry permission stays UNKNOWN`,async()=>{const {flow,adapter}=stock(outbound);flow.next();adapter.setOutcome('unknown');await flow.send();const before=flow.snapshot();for(const result of [{kind:'not-recorded'}, {kind:'not-recorded',request:before.request,retryAllowed:false},{kind:'not-recorded',request:{...before.request,requestId:'other'},retryAllowed:true}]){adapter.check=async()=>result;await flow.check();assert.equal(flow.snapshot().unknown,true);assert.equal(await flow.send(),false);}assert.equal(adapter.metrics().recordCalls,1);});
 test(`P17 ${owner} confirmed absence permits exactly the original request`,async()=>{const {flow,adapter}=stock(outbound);flow.next();adapter.setOutcome('unknown');await flow.send();const before=flow.snapshot();adapter.setOutcome('not-recorded');await flow.check();assert.equal(flow.snapshot().unknown,false);adapter.setOutcome('confirmed');await flow.send();assert.deepEqual(flow.snapshot().request,before.request);assert.equal(adapter.metrics().recordCalls,2);assert.equal(flow.snapshot().outcome,'recorded');});
 test(`P17 ${owner} changed actor or revoked permissions cannot reconcile or resend`,async()=>{const {flow,adapter,state}=stock(outbound);flow.next();adapter.setOutcome('unknown');await flow.send();const before=flow.snapshot();state.session.actor.id='different';assert.equal(await flow.check(),false);state.session.actor.id='a';state.session.permissions.warehouseOperations=false;assert.equal(await flow.check(),false);assert.equal(await flow.send(),false);assert.deepEqual(flow.snapshot().request,before.request);assert.equal(adapter.metrics().recordCalls,1);});
}
test('P17.A02 blocked outbound preserves reserved/source data and never mutates on duplicate actions',async()=>{const {flow,adapter}=stock(true),before=flow.snapshot();flow.scan('HN99999');assert.equal(flow.snapshot().exception.panel,'P17.S02');for(let i=0;i<4;i++){assert.equal(flow.scan('HN99999'),false);assert.equal(await flow.send(),false);}assert.deepEqual(flow.snapshot().accepted,before.accepted);assert.deepEqual(flow.snapshot().document,before.document);assert.equal(adapter.metrics().recordCalls,0);});
test('P17.A03 NFC conflict cancellation and repeated confirmation never overwrite mapping',async()=>{const state=auth(),adapter=createNfcFixtureAdapter({delay:0,scenario:'conflict'}),flow=createNfcFlow({adapter,getState:()=>state});flow.begin();await flow.read();const before=adapter.mapping(flow.scope(),flow.snapshot().read.uid);assert.equal(flow.snapshot().dependency.panel,'P17.S03');for(let i=0;i<4;i++){flow.dismissException();flow.panel(1);flow.panel(2);assert.equal(flow.next(),false);assert.equal(await flow.confirm(),false);}assert.deepEqual(adapter.mapping(flow.scope(),before.uid),before);assert.equal(adapter.stats().mutations,0);state.session.permissions.warehouseOperations=false;assert.equal(flow.detail(before.id),null);});
test('P17 outbound malformed/throwing source preserves accepted data and never invents a reason',()=>{const {flow,adapter}=stock(true),before=flow.snapshot();for(const response of [null,{kind:'valid',raw:'bad',sku:'x',quantity:NaN},{kind:'invalid'},'throw']){adapter.validate=()=>{if(response==='throw')throw Error('source');return response;};assert.equal(flow.scan('bad'),'invalid');assert.deepEqual(flow.snapshot().accepted,before.accepted);assert.equal(flow.snapshot().exception.panel,'P17.S01');assert.match(flow.snapshot().exception.reason,/Chưa xác/);flow.dismissException();}});
