// QA presentation only. No resampling, recoloring, masking or pixel-PASS threshold.
const fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,out=path.join(dir,'evidence');
const crops=[[42,60,415,886],[452,60,819,886],[853,60,1221,886],[1258,60,1632,886]];
const actuals=crops.map((_,i)=>`<img src="evidence/P07-S0${i+1}-494x1000.png" width="494" height="950" alt="Actual P07.S0${i+1}">`).join('');
const panels=crops.map(([x,y,r,b],i)=>`<section><h2>P07.S0${i+1}</h2><div class="compare" id="compare-${i+1}"><div><p>B07 native crop — estimated, ${r-x}×${b-y}</p><div class="crop" style="width:${r-x}px;height:${b-y}px"><img src="evidence/B07-reference.png" style="left:-${x}px;top:-${y}px;width:1672px;height:941px" alt="B07 panel ${i+1}"></div></div><div><p>Actual shell494×950 — no resize</p><img src="evidence/P07-S0${i+1}-494x1000.png" width="494" height="950" alt="Actual"></div></div></section>`).join('');
fs.writeFileSync(path.join(dir,'REVIEW.html'),`<!doctype html><html lang="vi"><meta charset="utf-8"><title>P07 — Visual review</title><style>body{font:16px Arial;color:#153e58;background:#eaf4f8;margin:20px}h1{font-size:26px}.overview,.compare{display:flex;width:max-content;gap:16px}.overview{gap:0}img{display:block;max-width:none}.crop{overflow:hidden;position:relative;flex-shrink:0}.crop img{position:absolute}section{margin-top:30px}p{max-width:950px}</style><h1>P07 — 4 panel actual và baseline</h1><p>Chỉ dùng để review bố cục. B07 có tỷ lệ khác shell494×950 đã chốt; crop loại status bar/caption theo ước lượng. Giữ nguyên kích thước native, không kéo méo, không đặt ngưỡng pixel PASS. Font Arial, icon repo và hộp demo khác tài nguyên Designer. Nội dung dài cuộn trong app.</p><div class="overview">${actuals}</div>${panels}</html>`);
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:2056,height:1100},deviceScaleFactor:1});await page.goto(pathToFileURL(path.join(dir,'REVIEW.html')).href);await page.locator('.overview').screenshot({path:path.join(out,'P07-actual-overview.png')});for(let i=1;i<=4;i++)await page.locator('#compare-'+i).screenshot({path:path.join(out,`comparison-S0${i}.png`)});await browser.close();fs.writeFileSync(path.join(out,'baseline-comparison.json'),JSON.stringify({crops_estimated:crops,resized:false,masked:false,threshold:null,visual_status:'IN_PROGRESS',viewport_css:[494,1000],shell_css:[494,950],DPR:1,zoom:1,font:'Arial system; Designer font UNKNOWN',source:'baseline-source.json'},null,2));console.log('4 native comparisons and actual overview saved.');})();
