'use client';
import {AppDialog,type AppDialogHandle} from './scanner-app-overlay';
import {scrollAppTop} from './scanner-app-shell';
import {useRef,useState} from 'react';
import {Warehouse,CheckCircle2,Users,MapPin,PackageCheck,ArrowRight,Send} from 'lucide-react';
import {agencyAddress,createAgencyFixtures} from '@/lib/agency-demo';
import './scanner-outbound.css';
const recipients=createAgencyFixtures().filter(a=>a.active);
const groups:Record<string,string>={'Đại lý':'agency','Nhà phân phối':'distributor','Khách công trường':'project','Khách lẻ':'retail'};
export type OutboundFields={name:string;group:string;recipient:string;phone:string;address:string;target:string;note:string};
export function outboundErrors(d:OutboundFields){return {name:d.name.trim()?'':'Nhập tên phiếu.',recipient:d.recipient.trim()?'':'Chọn hoặc nhập người nhận.',phone:/^0\d{9}$/.test(d.phone)?'':'Số điện thoại phải có 10 chữ số, bắt đầu bằng 0.',address:d.address.trim()?'':'Nhập địa chỉ giao hàng.',target:Number.isSafeInteger(Number(d.target))&&Number(d.target)>=1&&Number(d.target)<=99999?'':'Số lượng phải là số nguyên từ 1 đến 99.999.'};}
export default function ScannerOutbound({draft,update,onScan,disabled,manual}:{draft:OutboundFields;update:(values:Partial<OutboundFields>)=>void;onScan:()=>void;disabled:boolean;manual:boolean}){
 const [step,setStep]=useState(()=>draft.recipient.trim()&&draft.target.trim()?2:1),[search,setSearch]=useState(''),[errors,setErrors]=useState<Record<string,string>>({});const dialog=useRef<AppDialogHandle>(null);
 const results=recipients.filter(a=>a.type===groups[draft.group]&&`${a.code} ${a.name} ${a.phone}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));
 const validate=(all:boolean)=>{const err=outboundErrors(draft);const keys=all?Object.keys(err):['name','recipient','phone','address'];const first=keys.find(k=>err[k as keyof typeof err]);setErrors(err);if(first){setStep(first==='target'?2:1);setTimeout(()=>document.getElementById('so-'+first)?.focus(),0);return false;}return true;};
 const field=(key:keyof OutboundFields,label:string,type='text')=><label className={`sc-field so-field so-field-${key}`} htmlFor={'so-'+key}><span>{label}</span>{key==='address'||key==='note'?<textarea id={'so-'+key} aria-label={label} value={draft[key]} disabled={disabled} readOnly={!manual&&key==='address'} onChange={e=>update({[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'so-error-'+key:undefined}/>:<input id={'so-'+key} aria-label={label} value={draft[key]} type={type} inputMode={type==='tel'?'tel':type==='number'?'numeric':undefined} min={type==='number'?1:undefined} max={type==='number'?99999:undefined} step={type==='number'?1:undefined} disabled={disabled} readOnly={!manual&&['recipient','phone'].includes(key)} onChange={e=>update({[key]:e.target.value})} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'so-error-'+key:undefined}/>} {errors[key]&&<span className="so-field-error" id={'so-error-'+key}>{errors[key]}</span>}</label>;
 return <><div className="so-warehouse-context" aria-label="Kho xuất"><span><Warehouse aria-hidden="true"/>Kho Hoa Nam</span><span className="so-active"><i aria-hidden="true"/>Đang hoạt động</span></div><div className="sc-stepper so-progress"><b aria-current={step===1?'step':undefined}><span>1</span>Người nhận</b><b aria-current={step===2?'step':undefined}><span>2</span>Số lượng & xác nhận</b></div>
 <form noValidate onSubmit={e=>{e.preventDefault();if(disabled)return;if(validate(step===2)){if(step===1){setStep(2);scrollAppTop();}else onScan();}}}>
 {step===1?<section className="so-surface"><div className="so-section-heading"><div><span className="so-eyebrow">XUẤT KHO</span><h2>Thông tin giao / nhận</h2><p>Chọn người nhận và địa chỉ giao hàng trước khi soạn.</p></div><Users aria-hidden="true"/></div>{field('name','Tên phiếu *')}<label className="sc-field so-field so-field-group"><span>Nhóm đối tượng *</span><select value={draft.group} disabled={disabled} onChange={e=>{update({group:e.target.value,recipient:'',phone:'',address:''});setSearch('');}}>{Object.keys(groups).map(g=><option key={g}>{g}</option>)}</select></label><button type="button" className="so-recipient-trigger" disabled={disabled} onClick={()=>dialog.current?.showModal()}><Users aria-hidden="true"/><span><strong>{draft.recipient||'Chọn người nhận trong danh mục'}</strong><small>{draft.recipient?`${draft.phone} · ${draft.address}`:'Bắt buộc trước khi tiếp tục'}</small></span><ArrowRight aria-hidden="true"/></button>{(draft.recipient||Object.keys(errors).some(key=>['recipient','phone','address'].includes(key)))&&<div className="so-recipient-fields">{field('recipient','Tên người nhận / đơn vị *')}{field('phone','Số điện thoại *','tel')}{field('address','Địa chỉ giao hàng *')}</div>}<p className="so-supporting">{manual?'Bạn có quyền lập yêu cầu xuất thủ công.':'Thông tin người nhận lấy từ danh mục được cấp.'}</p></section>:<section className="so-surface so-quantity-surface"><div className="so-section-heading"><div><span className="so-eyebrow">BƯỚC 2 / 2</span><h2>Số lượng cần soạn</h2><p>Nhập đúng mục tiêu trước khi bắt đầu quét.</p></div><PackageCheck aria-hidden="true"/></div><div className="so-target-focus">{field('target','Tổng số lượng cần soạn *','number')}<strong>cái</strong></div><div className="so-recipient-summary"><MapPin aria-hidden="true"/><span><strong>{draft.recipient}</strong><small>{draft.phone} · {draft.address}</small></span></div>{field('note','Ghi chú')}<p className="so-stock-note">Tồn kho chỉ thay đổi sau khi phiếu được ghi sổ.</p><button type="button" className="so-back-step" onClick={()=>setStep(1)}>Sửa thông tin giao / nhận</button></section>}
 <div className="sc-sticky-actions so-sticky-actions"><button type="submit" className="sc-btn so-continue" disabled={disabled}>{step===1?<><ArrowRight aria-hidden="true"/>Tiếp tục: số lượng</>:<><Send aria-hidden="true"/>Bắt đầu soạn hàng<ArrowRight aria-hidden="true"/></>}</button></div></form>
 <AppDialog variant="sheet" ref={dialog} className="sc-recipient-sheet" aria-labelledby="so-picker-title"><h2 id="so-picker-title">Chọn người nhận</h2><label className="sc-field"><span>Tìm tên, mã hoặc số điện thoại</span><input data-app-autofocus="true" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="so-results">{results.map(a=><button type="button" className="sc-list-card" key={a.id} aria-label={a.name} onClick={()=>{update({recipient:a.contact||a.name,phone:a.phone,address:agencyAddress(a)});setErrors({});dialog.current?.close();}}><span><strong>{a.name}</strong><small>{a.code} · {a.phone||'Chưa có số điện thoại'}</small><small>{agencyAddress(a)}</small></span></button>)}{!results.length&&<p>Không có người nhận phù hợp. Thử tên hoặc mã khác.</p>}</div><button type="button" className="sc-btn secondary" onClick={()=>{setSearch('');}}>Xóa tìm kiếm</button><button type="button" className="sc-btn secondary" onClick={()=>dialog.current?.close()}>Đóng danh mục</button></AppDialog></>;
}
