const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const phase=process.argv[2]||'after',out='handoff/P22/evidence/revision-03/'+phase;
const list='#p02/history?scene=nfc',detail='#p02/history?scene=nfc-detail&event=NFC-E002';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),checks=[];
async function test(id,name,run,inject=''){
 const p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(6500);
 const a=k=>p.locator(`[data-p22="${k}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p22-snapshot]').textContent());
 const route=async hash=>{await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(100);await p.waitForSelector('.p22-app');};
 const source=async mode=>{await p.selectOption('[data-p22-source]',mode);await p.waitForFunction(()=>!document.querySelector('[data-p22=reload]:disabled'));};
 const shot=(name=id)=>p.locator('.hn-screen').screenshot({path:out+'/'+name+'.png'});
 try{
  if(inject)await p.route('**/nfc-audit-fixture.mjs',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('return {available:true,confirmed:true,complete:true,items};',inject)});});
  await p.clock.setFixedTime(new Date('2026-09-30T05:00:00Z'));await p.goto('http://localhost:8766/flows/auth-session/?v=p22-r03-audit');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('.hn-intro');await route(list);await source('fixture');
  await run({p,a,snap,route,source,shot});assert.deepEqual(errors,[]);await shot();checks.push({id,name,status:'PASS',errors});
 }catch(e){await shot().catch(()=>{});checks.push({id,name,status:'FAIL',error:e.message,errors});}
 console.log(checks.at(-1).status+' '+id+' '+name);await p.close();
}
await test('01','Deep-link Back fallback must not invent a caller',async({p,a,route})=>{await route(detail);await a('back').click();await p.waitForSelector('#p22-search');assert.equal(await p.evaluate(()=>!!history.state?.p22From),false);await a('back').click();await p.frameLocator('iframe').locator('[data-action=nfc]').waitFor();});
await test('02','Leaving a refresh is not a read failure',async({p,a,snap})=>{await p.selectOption('[data-p22-read-outcome]','slow');await a('reload').click();await p.locator('[data-p22-event="NFC-E002"]').click();await a('back').click();await p.waitForSelector('#p22-search');assert.notEqual((await snap()).readIssue,'error');assert.match(await p.locator('.p22-read-status').textContent(),/chưa hoàn tất/i);});
await test('03','Cached detail exposes the source warning',async({p,a})=>{await p.selectOption('[data-p22-read-outcome]','error');await a('reload').click();await p.waitForFunction(()=>!document.querySelector('[data-p22=reload]').disabled);await p.locator('[data-p22-event="NFC-E002"]').click();assert.match(await p.locator('.p22-scroll').innerText(),/lần đọc trước/);});
await test('04','A long UID never hides the serial row',async({p,source})=>{await source('long');const visible=await p.locator('[data-p22-event="NFC-E002"]').evaluate(e=>{const walker=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.textContent.includes('HN12346')){const range=document.createRange();range.selectNodeContents(n);const r=range.getBoundingClientRect(),parent=n.parentElement.getBoundingClientRect();return r.bottom<=parent.bottom+1;}}return false;});assert.equal(visible,true);});
await test('05','Long actor is compact on card with full detail path',async({p,shot})=>{await shot('05-list');assert.ok(await p.locator('.p22-actor').first().evaluate(e=>e.offsetHeight<=48));await p.locator('[data-p22-event]').first().click();await p.waitForSelector('[data-hn-readable="Người thực hiện"]');assert.ok((await p.locator('[data-hn-readable="Người thực hiện"]').textContent()).length>250);},"items=items.map(e=>({...e,actor:'Tên người thực hiện '.repeat(40)}));return {available:true,confirmed:true,complete:true,items};");
await test('06','IME lifecycle resets after a tab replaces its input',async({p})=>{await p.locator('#p22-search').evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await p.locator('[data-p22-type="Thay thẻ"]').click();await p.fill('#p22-search','no-match');await p.waitForTimeout(350);assert.equal(await p.locator('[data-p22-event]').count(),0);});
await test('07','Pending query does not repaint underneath a picker',async({p,a})=>{await p.locator('#p22-search').evaluate(e=>{window.keptRow=document.querySelector('[data-p22-event]');e.value='HN12346';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-p22=filter]').click();});await p.waitForSelector('.p08-picker[open]');await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>window.keptRow.isConnected),true);await p.keyboard.press('Escape');await p.waitForTimeout(350);assert.equal(await p.locator('[data-p22-event]').count(),1);});
await test('08','Reload keyboard focus survives request completion',async({p,a})=>{await p.selectOption('[data-p22-read-outcome]','slow');await a('reload').focus();await p.keyboard.press('Enter');await p.waitForTimeout(950);assert.equal(await a('reload').evaluate(e=>e===document.activeElement),true);});
await test('09','Incomplete empty is not a confirmed empty history',async({p})=>{assert.doesNotMatch(await p.locator('.p22-scroll').innerText(),/Chưa có thao tác|Nguồn đã xác nhận kết quả đọc/);assert.match(await p.locator('.p22-scroll').innerText(),/chưa xác minh/i);},'return {available:true,confirmed:true,complete:false,items:[]};');
await test('10','Invalid optional data is unknown, not object text or fake copy action',async({p})=>{await p.locator('[data-p22-event="NFC-E002"]').click();assert.doesNotMatch(await p.locator('.p22-scroll').innerText(),/\[object Object\]/);assert.equal(await p.locator('[data-p22-copy=uid]').count(),0);assert.match(await p.locator('.p22-scroll').innerText(),/Chưa xác minh/);},"items=items.map(e=>({...e,uid:{bad:1},actor:{bad:1},serial:0}));return {available:true,confirmed:true,complete:true,items};");
await test('11','Active status filter has visible filter indicator',async({p,a})=>{await a('filter').click();await p.locator('[name=status][value="Đã thu hồi"]').check();await p.locator('.p08-picker [type=submit]').click();await p.waitForSelector('#p22-search');assert.equal(await p.locator('[data-p22=filter][data-filter-active=true]').count(),1);assert.equal(await p.locator('.p22-controls .p08-filter-dot').evaluate(e=>e.offsetWidth>=9&&e.offsetHeight>=9),true);});
await test('12','Source change does not strand focus in document body',async({p,route})=>{await route(detail);await p.locator('.p22-audit-info summary').click();await p.locator('.p22-audit-info summary').focus();await p.locator('[data-p22-source]').evaluate(e=>{e.value='slow';e.dispatchEvent(new Event('change',{bubbles:true}));});await p.waitForTimeout(1000);assert.equal(await p.locator('.p22-app').evaluate(e=>e.contains(document.activeElement)),true);});
fs.writeFileSync(out+'/audit-results.json',JSON.stringify({phase,checks,passed:checks.filter(c=>c.status==='PASS').length,total:checks.length},null,2));await browser.close();if(phase==='after'&&checks.some(c=>c.status==='FAIL'))process.exitCode=1;
})();
