const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const phase=process.env.P13_AUDIT_PHASE||'after',out='handoff/P13/evidence/revision-07/'+phase;
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),checks=[];
async function run(name,fn){if(process.env.P13_AUDIT_CASE&&!name.startsWith(process.env.P13_AUDIT_CASE))return;const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const original=window.setTimeout;window.setTimeout=(cb,ms,...args)=>original(cb,ms===180?1200:ms,...args);});try{await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await p.locator('[data-p13-loaded=true]').waitFor();await fn(p);assert.deepEqual(errors,[]);await p.screenshot({path:path.join(out,name+'.png')});checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){checks.push({name,status:'FAIL',message:e.message,errors});console.log('FAIL '+name+' '+e.message.slice(0,180));await p.screenshot({path:path.join(out,name+'.png')}).catch(()=>{});fs.writeFileSync(path.join(out,'partial-results.json'),JSON.stringify(checks,null,2));}finally{await p.close();}}
const all=async p=>{await p.click('[data-p13-filter=all]');await p.locator('[data-p13-loaded=true]').waitFor();};
const extended=async p=>{await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset','extended');await p.locator('[data-p13-loaded=true]').waitFor();await p.evaluate(()=>scrollTo(0,0));await all(p);};
await run('A01-load-more-focus',async p=>{await extended(p);await p.locator('[data-p13=more]').focus();await p.locator('[data-p13=more]').evaluate(e=>e.click());assert.ok(await p.locator('[data-p13=more]').evaluate(e=>e===document.activeElement),'focus must stay on request control while loading');});
await run('A02-late-load-steals-focus',async p=>{await extended(p);await p.locator('[data-p13=more]').focus();await p.locator('[data-p13=more]').evaluate(e=>e.click());await p.locator('[data-p13=back]').focus();await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===20);assert.ok(await p.locator('[data-p13=back]').evaluate(e=>e===document.activeElement),'late page may not steal focus from newly selected control');});
await run('A03-reader-survives-read-receipt',async p=>{await all(p);await p.click('[data-p13-event=p13-event-inbound]');await p.click('[data-p13=back]');await p.locator('.p13-excerpt').nth(1).evaluate(e=>e.textContent='Nội dung người dùng đang đọc 🌸\n'.repeat(60));await p.locator('.p13-notification .hn-read-more:visible').waitFor();await p.locator('.p13-notification .hn-read-more:visible').click();await p.waitForFunction(()=>document.querySelector('.hn-bell .hn-count').textContent==='2');await p.waitForTimeout(150);assert.equal(await p.locator('.app-modal-host dialog').count(),1,'late mark-read must not destroy an unrelated reader');await p.locator('.hn-screen').screenshot({path:path.join(out,'reader-preserved.png')});await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-p13-event=p13-event-inbound]').evaluate(e=>e.closest('article').dataset.read),'true');assert.ok(await p.locator('.p13-notification .hn-read-more:visible').evaluate(e=>e===document.activeElement));});
await run('A04-back-restores-row-focus',async p=>{await all(p);await p.click('[data-p13-event=p13-event-outbound]');await p.click('[data-p13=back]');await p.locator('[data-panel="P13.S01"]').waitFor();assert.ok(await p.locator('[data-p13-event=p13-event-outbound]').evaluate(e=>e===document.activeElement),'Back should restore originating row, not header');});
await run('A05-deep-link-back-no-loop',async p=>{await p.evaluate(()=>location.hash='#p02/notifications?panel=2&event=p13-event-outbound');await p.locator('[data-panel="P13.S02"]').waitFor();const length=await p.evaluate(()=>history.length);await p.click('[data-p13=back]');await p.locator('[data-panel="P13.S01"]').waitFor();assert.equal(await p.evaluate(()=>history.length),length,'fallback Back must not push a new forward entry');});
await run('A06-empty-message-overlaid-by-late-page',async p=>{await extended(p);await p.locator('[data-p13=more]').evaluate(e=>e.click());await p.selectOption('#p13-scenario','empty');await p.waitForTimeout(1450);assert.equal(await p.locator('.p13-notification').count(),0,'pending page may not append rows into explicitly selected empty/error state');});
await run('A08-invalid-waiting-document-actions',async p=>{await p.evaluate(()=>location.hash='#p02/notifications?panel=4&doc=b12-warranty-001');await p.locator('[data-panel="P13.S04"]').waitFor();assert.ok((await p.locator('.p13-app').textContent()).includes('Không tìm thấy'));assert.equal(await p.locator('.p13-actions').count(),0,'missing/unsupported stock detail must not expose action dock');});
await run('A07-row-title-scroll-and-footer',async p=>{await p.locator('.p13-notification-copy strong').first().evaluate(e=>e.textContent='TênThôngBáoRấtDài'.repeat(80));await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const m=await p.evaluate(()=>{const s=document.querySelector('.p13-scroll'),n=document.querySelector('.hn-nav').getBoundingClientRect();return {w:s.clientWidth,sw:s.scrollWidth,footer:n.bottom,app:document.querySelector('.hn-screen').getBoundingClientRect().bottom};});assert.equal(m.w,m.sw);assert.ok(m.footer<=m.app+1);});
fs.writeFileSync(path.join(out,'audit-results.json'),JSON.stringify({phase,checks},null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.status==='PASS').length,failed:checks.filter(c=>c.status==='FAIL').length}));await b.close();if(checks.some(c=>c.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
