const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const phase=process.argv[2]||'after',out='handoff/P23/evidence/revision-03/'+phase;
fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true}),results=[];
async function test(id,title,fn){if(process.argv[3]&&!process.argv[3].split(',').includes(id))return;const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
 await p.route('**/warranty-session-fixture.mjs',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text()).replace("if(mode==='unavailable')", "if(globalThis.__p23FixtureOverride)return globalThis.__p23FixtureOverride; if(mode==='unavailable')")});});
 const a=k=>p.locator(`[data-p23="${k}"]`),shot=()=>p.locator('.hn-screen').screenshot({path:out+'/'+id+'.png'});
 async function route(scene,id){await p.evaluate(({scene,id})=>location.hash='#p02/history?'+new URLSearchParams({scene,...(id?{[scene==='warranty-detail'?'case':'session']:id}:{})}),{scene,id});await p.waitForSelector('.p23-app');await p.waitForTimeout(80);}
 async function source(mode='fixture'){await p.selectOption('[data-p23-source]',mode);await p.waitForFunction(()=>!document.querySelector('[data-p23=reload]:disabled'));await p.waitForTimeout(50);}
 async function override(fn){await p.evaluate(async fn=>{const m=await import('../history/warranty-session-fixture.mjs');const f=m.sessionFixture('fixture-hoa-nam','fixture');(0,eval)('('+fn+')')(f);window.__p23FixtureOverride=f;},fn.toString());await source();}
 try{await p.goto('http://localhost:8766/flows/auth-session/?v=p23-r03-audit');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await fn({p,a,route,source,override,shot});assert.deepEqual(errors,[]);results.push({id,title,status:'PASS'});}catch(e){results.push({id,title,status:'FAIL',error:e.message,errors});}finally{await shot().catch(()=>{});await p.close();}console.log(results.at(-1));}
try{
await test('A01','Pending search then Cancel picker updates results',async({p,a,route,source})=>{await route('sessions');await source();await p.fill('#p23-search','PQ-0002');await a('filter').first().click();await p.keyboard.press('Escape');await p.waitForTimeout(400);assert.equal(await p.locator('[data-p23-entity]').count(),1);});
await test('A02','Date filter has active visual and accessible indicator',async({p,a,route,source})=>{await route('sessions');await source();await a('filter').first().click();await p.fill('#pick-from','10/09/2026');await p.fill('#pick-to','10/09/2026');await p.locator('.app-modal-host [type=submit]').click();await p.waitForTimeout(180);assert.equal(await a('filter').first().getAttribute('data-filter-active'),'true');assert.match(await a('filter').first().getAttribute('aria-label'),/đang áp dụng/);});
await test('A03','Detail reload does not drop focus while pending',async({p,a,route,source})=>{await route('sessions');await source();await route('session-detail','PQ-0003');await p.selectOption('[data-p23-outcome]','slow');await a('reload').click();assert.equal(await a('reload').evaluate(e=>document.activeElement===e),true);});
await test('A04','Detail reload preserves newer footer focus identity',async({p,a,route,source})=>{await route('sessions');await source();await route('session-detail','PQ-0003');await p.selectOption('[data-p23-outcome]','slow');await a('reload').click();await p.locator('.p23-footer button').focus();await p.waitForTimeout(800);assert.equal(await p.locator('.p23-footer button').evaluate(e=>document.activeElement===e),true);});
await test('A05','Reader closes after read refresh with focus on same reader',async({p,a,route,source})=>{await route('sessions');await source('long');await route('session-detail','PQ-0003');await p.selectOption('[data-p23-outcome]','slow');await a('reload').click();const reader=p.getByRole('button',{name:'Xem đầy đủ người quét',exact:true});await reader.click();await p.waitForTimeout(800);await p.keyboard.press('Escape');await p.waitForTimeout(200);assert.equal(await reader.evaluate(e=>document.activeElement===e),true);});
await test('A06','Unknown inbound does not claim document sent',async({p,route,override})=>{await route('sessions');await override(f=>{f.items[1].result=null;f.items[1].doc=null;});await route('session-detail','PQ-0002');assert.doesNotMatch(await p.locator('.p23-notice').last().innerText(),/Phiếu đã gửi/);assert.match(await p.locator('.p23-notice').last().innerText(),/chưa xác minh/i);});
await test('A07','Long event heading and time cannot overflow timeline',async({p,route})=>{await p.evaluate(async()=>{const m=await import('../shared/warranty-cases.mjs'),c=m.readWarrantyCases().find(x=>x.id==='BH-001');m.writeWarrantyCase({...c,events:[{id:'long',label:'S'.repeat(260),actor:'Actor',day:'2026-09-10',time:'T'.repeat(260),description:'Note'}]});});await route('warranty-detail','BH-001');assert.equal(await p.locator('.p23-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);});
await test('A08','Malformed owner event cannot crash detail',async({p,route})=>{await p.evaluate(async()=>{const m=await import('../shared/warranty-cases.mjs'),c=m.readWarrantyCases().find(x=>x.id==='BH-001');m.writeWarrantyCase({...c,events:[null,{id:'valid',label:'Tiếp nhận',day:'2026-09-10',time:'10:00',actor:'Minh Anh'}]});});await route('warranty-detail','BH-001');await p.waitForSelector('[data-panel="P23.S02"]');assert.match(await p.locator('.p23-app').innerText(),/Tiếp nhận/);});
await test('A09','Back from linked case names actual session destination',async({p,a,route,source})=>{await route('sessions');await source();await route('session-detail','PQ-0003');await a('related-case').click();await p.waitForSelector('[data-panel="P23.S02"]');assert.match(await p.locator('.p23-footer').innerText(),/phiên quét/);});
await test('A10','Source change clears unrelated scroll context',async({p,route,source,override})=>{await route('sessions');await override(f=>{f.items=Array.from({length:20},(_,i)=>({...f.items[2],id:'SESSION-'+i,events:[]}));});await p.locator('.p23-scroll').evaluate(e=>e.scrollTop=1500);await p.selectOption('[data-p23-source]','long');await p.waitForTimeout(150);assert.equal(await p.locator('.p23-scroll').evaluate(e=>e.scrollTop),0);});
await test('A11','Pending debounce does not discard focus on result card',async({p,route,source})=>{await route('sessions');await source();await p.evaluate(()=>{const e=document.querySelector('#p23-search');e.value='PQ';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-p23-entity="PQ-0003"]').focus();});await p.waitForTimeout(350);assert.equal(await p.locator('[data-p23-entity="PQ-0003"]').evaluate(e=>e===document.activeElement),true);});
await test('A12','Session quantity rejected/duplicate not labelled issued',async({p,route,override})=>{await route('sessions');await override(f=>{f.items[0].events[0].result='rejected';f.items[0].events[0].quantity=1;});await route('session-detail','PQ-0003');assert.doesNotMatch(await p.locator('.p23-code').first().innerText(),/1 linh kiện/);});
await test('A13','Read refresh preserves raw event reader focus by event ID',async({p,a,route,source})=>{await route('sessions');await source('long');await route('session-detail','PQ-0003');await p.selectOption('[data-p23-outcome]','slow');await a('reload').click();const r=p.getByRole('button',{name:'Xem đầy đủ mã gốc',exact:true});await r.focus();await p.waitForTimeout(800);assert.equal(await r.evaluate(e=>e===document.activeElement),true);});
await test('A14','Filter apply restores date-button trigger not search-filter',async({p,a,route,source})=>{await route('sessions');await source();await a('filter').nth(1).click();await p.locator('.app-modal-host [type=submit]').click();await p.waitForTimeout(200);assert.equal(await a('filter').nth(1).evaluate(e=>e===document.activeElement),true);});
}finally{await b.close();const file=out+'/audit.json';const prior=process.argv[3]&&fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):[];fs.writeFileSync(file,JSON.stringify([...prior.filter(r=>!results.some(n=>n.id===r.id)),...results].sort((a,b)=>a.id.localeCompare(b.id)),null,2));console.log(results.filter(r=>r.status==='FAIL').length+' failures / '+results.length);if(phase!=='before'&&results.some(r=>r.status==='FAIL'))process.exitCode=1;}
})();
