const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const phase=process.argv[2]||'after',out='handoff/P20/evidence/revision-03/'+phase;fs.mkdirSync(out,{recursive:true});
if(phase==='before')for(const f of ['docs/flows/warranty-components/history-view.mjs','docs/flows/warranty-components/history.css','docs/flows/warranty-components/history-model.mjs','docs/flows/warranty-components/history-experience.mjs','docs/flows/home/home.mjs','RUN_STATE.json','SCREEN_COVERAGE.csv']){const dest=path.join(out,'source',f);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(f,dest);}
(async()=>{const browser=await chromium.launch(),results=[];let p;
async function setup(modify){p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'});p.setDefaultTimeout(8000);if(phase==='baseline-verified')await p.route('**/flows/**',async r=>{const file='handoff/P20/evidence/revision-03/before/source/docs'+decodeURIComponent(new URL(r.request().url()).pathname);if(fs.existsSync(file)&&fs.statSync(file).isFile())await r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.css')?'text/css':'text/javascript'});else await r.fallback();});if(modify)await p.route('**/history-fixture.mjs',async r=>{const x=await r.fetch();await r.fulfill({response:x,body:modify(await x.text())});});await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p20-tools').evaluate(e=>e.open=true);}
const a=n=>p.locator(`[data-p20="${n}"]`),sleep=()=>p.waitForTimeout(200);
async function route(q){await p.evaluate(q=>location.hash='#p02/component-history?'+q,q);await p.waitForSelector('.p20-app');await sleep();}
async function ready(q){await route(q);await p.waitForFunction(()=>{const s=document.querySelector('[data-p20-snapshot]');return s&&JSON.parse(s.textContent).loaded&&!JSON.parse(s.textContent).loading;});}
async function shot(n){await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});}
async function check(id,title,fn,modify){let result={id,title};try{await setup(modify);await fn();result.status='PASS';}catch(e){result.status='FAIL';result.error=e.message;}await shot(id).catch(()=>{});results.push(result);console.log(result.status+' '+id+' '+title);await p.close();}
try{
await check('A01','Expand keeps focused control inside visible scroller',async()=>{await ready('case=BH-001&sample=long-history');await a('expand').click();await sleep();const g=await a('expand').evaluate(e=>{const s=e.closest('.p20-scroll').getBoundingClientRect(),r=e.getBoundingClientRect();return {visible:r.top>=s.top&&r.bottom<=s.bottom+1,focused:e===document.activeElement};});assert.equal(g.focused,true);assert.equal(g.visible,true);});
await check('A02','Collapse during page request does not leave large permanent blank card',async()=>{await ready('case=BH-001&sample=long-history');await a('expand').click();await p.selectOption('[data-p20-mode]','slow');await a('load').click();await a('expand').click();await p.waitForSelector('.p20-end');const gap=await p.locator('.p20-history').evaluate(e=>e.getBoundingClientRect().bottom-e.querySelector('[data-p20-paging]').getBoundingClientRect().bottom);assert.ok(gap<70,'blank gap '+gap);},s=>s.replace('length:4','length:20'));
await check('A03','Cache return restores focus to selected receipt, not obsolete load control',async()=>{await ready('case=BH-001&sample=history');await a('load').click();await p.waitForSelector('[data-p20=new]');await a('new').click();await p.evaluate(()=>location.hash='#p02/warranty?case=BH-001&panel=3');await p.waitForSelector('.p09-app');await p.goBack();await p.waitForSelector('.p20-app');assert.equal(await p.locator('[data-p20-document="XLK-DEMO-OLDER"]').evaluate(e=>e===document.activeElement),true);});
await check('A04','Large valid quantities do not overflow their column/card',async()=>{await ready('case=BH-001&sample=history');const g=await p.locator('.p20-quantity').first().evaluate(e=>{const r=e.getBoundingClientRect();return {overflow:e.scrollWidth>e.clientWidth+1,width:e.clientWidth};});assert.equal(g.overflow,false,JSON.stringify(g));},s=>s.replace('rows=[...new Map','rows=rows.map(r=>({...r,lines:r.lines.map(l=>({...l,quantity:Number.MAX_SAFE_INTEGER}))})); rows=[...new Map'));
await check('A05','Direct-link Back fallback cannot cycle P20 and P09',async()=>{await p.evaluate(()=>{history.replaceState(null,'','#p02/component-history?case=BH-001');dispatchEvent(new HashChangeEvent('hashchange'));});await p.waitForSelector('.p20-app');await a('back').click();await p.waitForSelector('.p09-app');await p.click('[data-p09=back]');await sleep();assert.equal(await p.locator('.p20-app').count(),0,'Back returned to P20 without a real caller');});
await check('A06','Unknown case Back never opens phantom case/cycles',async()=>{await p.evaluate(()=>{history.replaceState(null,'','#p02/component-history?case=BAD');dispatchEvent(new HashChangeEvent('hashchange'));});await p.waitForSelector('.p20-app');await a('back').click();await sleep();assert.equal(await p.locator('.hn-action-dialog[open]').count(),0,'Unknown case must return to list without another phantom case alert');if(await p.locator('.p09-app').count())await p.click('[data-p09=back]');await sleep();assert.equal(await p.locator('.p20-app').count(),0);});
await check('A07','Switch active case while read dialog open closes stale case overlay',async()=>{await ready('case=BH-001');await a('codes').click();await p.waitForSelector('.p20-codes-dialog[open]');await route('case=BH-002');await sleep();assert.equal(await p.locator('.p20-codes-dialog[open]').count(),0);assert.match(await p.locator('.p20-context').innerText(),/BH-002/);});
await check('A08','Reader trigger for long receipt ID stays below header, no column squeeze',async()=>{await ready('case=BH-001&sample=history');const b=p.getByRole('button',{name:'Xem đầy đủ mã phiếu',exact:true}).first();await b.waitFor();const g=await b.evaluate(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));assert.ok(g.w>=44&&g.h>=44&&g.h<=60,JSON.stringify(g));await b.click();await p.waitForSelector('.hn-readable-dialog[open]');assert.ok((await p.locator('.hn-readable-dialog[open]').innerText()).includes('X'.repeat(250)));},s=>s.replace('rows=[...new Map','rows=rows.map(r=>({...r,id:r.id+"X".repeat(250)})); rows=[...new Map'));
await check('A09','Successful duplicate-only page removes obsolete new-batch marker',async()=>{await ready('case=BH-001&sample=history');await a('load').click();await p.waitForSelector('[data-p20=new]');assert.equal(await p.locator('.p20-batch').count(),1);await a('load').click();await p.waitForSelector('.p20-end');assert.equal(await p.locator('.p20-batch').count(),0);assert.equal(await a('new').count(),0);},s=>s.replace("if(cursor!=='fixture-rest')", "if(cursor==='fixture-last')return {caseId,items:structuredClone(rows),hasMore:false,nextCursor:null}; if(cursor!=='fixture-rest')").replace('return {caseId,items:structuredClone(rows),hasMore:false,nextCursor:null};\n }}','return {caseId,items:structuredClone(rows),hasMore:true,nextCursor:"fixture-last"};\n }}'));
await check('A10','Successive page keeps focus on existing jump control while async completes',async()=>{await ready('case=BH-001&sample=history');await a('load').click();await p.waitForSelector('[data-p20=new]');await p.selectOption('[data-p20-mode]','slow');await a('load').click();await a('new').focus();await p.waitForSelector('.p20-end');assert.equal(await a('new').evaluate(e=>document.activeElement===e),true);assert.equal(await a('new').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.p20-scroll').getBoundingClientRect();return r.top>=s.top&&r.bottom<=s.bottom+1;}),true);},s=>s.replace("if(cursor!=='fixture-rest')", "if(cursor==='fixture-last')return {caseId,items:[...structuredClone(rows),{...rows[1],id:'XLK-THIRD'}],hasMore:false,nextCursor:null}; if(cursor!=='fixture-rest')").replace('return {caseId,items:structuredClone(rows),hasMore:false,nextCursor:null};\n }}','return {caseId,items:structuredClone(rows),hasMore:true,nextCursor:"fixture-last"};\n }}'));
await check('A11','Preview selector reflects per-case source mode',async()=>{await ready('case=BH-001&sample=history');await p.selectOption('[data-p20-mode]','error');await ready('case=BH-002');assert.equal(await p.locator('[data-p20-mode]').inputValue(),'ready');await route('case=BH-001&sample=history');assert.equal(await p.locator('[data-p20-mode]').inputValue(),'error');});
await check('A12','Repeated same-route preview entry does not add Back history step',async()=>{await p.click('[data-p20-open]');await p.waitForSelector('.p20-app');await p.waitForSelector('.p20-end');const n=await p.evaluate(()=>history.length);await p.click('[data-p20-open]');assert.equal(await p.evaluate(()=>history.length),n);});
}finally{fs.writeFileSync(out+'/results.json',JSON.stringify({results,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length},null,2));await browser.close();}if(phase!=='before'&&results.some(r=>r.status==='FAIL'))process.exitCode=1;})();
