const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),before=process.argv.includes('--before'),out=`handoff/P19/evidence/revision-03/${before?'before/audit':'audit'}`;fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),checks=[],errors=[];let p;
const a=n=>p.locator(`[data-p19=${n}]`).first(),pause=()=>p.waitForTimeout(220),snap=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent()),focus=s=>p.locator(s).evaluate(e=>document.activeElement===e),route=async h=>{await p.evaluate(v=>location.hash=v,h);await pause();},enter=async v=>{if(!await p.locator('#p19-code').count())await p.click('[data-scan-action=manual]');await p.fill('#p19-code',v);await p.locator('#p19-code').press('Enter');},quantity=async n=>{await p.fill('#p19-quantity',String(n));await p.locator('.p19-sheet button[type=submit]').click();await pause();};
async function fresh(){await p?.close();p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce'});p.setDefaultTimeout(6000);if(before)await p.route('**/flows/**',async r=>{const path=new URL(r.request().url()).pathname,f='handoff/P19/evidence/revision-03/before/source/docs'+path;if(fs.existsSync(f)&&fs.statSync(f).isFile())await r.fulfill({body:fs.readFileSync(f),contentType:path.endsWith('.css')?'text/css':'text/javascript'});else await r.continue();});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.p19-tools').evaluate(e=>e.open=true);await route('#p02/warranty?panel=3&case=BH-001&tab=parts');await p.click('[data-p09=issue]');await p.waitForSelector('.p19-app');}
async function check(id,name,fn){await fresh();let error;try{await fn();}catch(e){error=e.message;}await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+id+'.png'}).catch(()=>{});checks.push({id,name,status:error?'FAIL':'PASS',...(error?{error}:{})});console.log(`${error?'FAIL':'PASS'} ${id} ${name}${error?' '+error.slice(0,180):''}`);}
try{
await check('A01','Collapse manual restores focus to visible entry control',async()=>{await enter('LK0001-HN001');await p.click('[data-scan-action=collapse]');assert.equal(await focus('[data-scan-action=manual]'),true);});
await check('A02','Review → scan restores input focus/caret and unsubmitted text',async()=>{await enter('LK0001-HN001');await p.fill('#p19-code','BOX-pending');await p.locator('#p19-code').evaluate(e=>e.setSelectionRange(2,5));await a('review').click();await pause();await a('scan').click();await pause();assert.equal(await p.inputValue('#p19-code'),'BOX-pending');assert.equal(await focus('#p19-code'),true);assert.deepEqual(await p.locator('#p19-code').evaluate(e=>[e.selectionStart,e.selectionEnd]),[2,5]);});
await check('A03','Confirmed removal returns keyboard focus to remaining row or scan action',async()=>{await enter('LK0001-HN001');await enter('BOX-LK-0002-01');await quantity(2);await a('review').click();await pause();await a('remove').click();await p.locator('.app-modal-host').getByRole('button',{name:'Bỏ linh kiện',exact:true}).click();await pause();assert.equal((await snap()).lines.length,1);assert.equal(await p.locator('.p19-app').evaluate(e=>e.contains(document.activeElement)&&document.activeElement.matches('button')),true);});
await check('A04','Leaving during IME does not disable Enter in next rendered input',async()=>{await p.click('[data-scan-action=manual]');await p.locator('#p19-code').dispatchEvent('compositionstart');const hash=await p.evaluate(()=>location.hash);await route('#p02/warranty?panel=3&case=BH-001&tab=parts');await route(hash);await enter('LK0001-HN001');assert.equal((await snap()).lines.length,1);});
await check('A05','Most recently accepted BOX moves to top without changing document line order',async()=>{await enter('BOX-LK-0002-01');await quantity(2);await enter('LK0001-HN001');await enter('BOX-LK-0002-01');await quantity(3);assert.equal(await p.locator('.p19-scan-summary .p19-part').first().getAttribute('data-code'),'BOX-LK-0002-01');assert.deepEqual((await snap()).lines.map(l=>l.code),['BOX-LK-0002-01','LK0001-HN001']);});
await check('A06','Long SKU/name/code sheet wraps; footer reachable and body scrolls inside dialog',async()=>{await p.evaluate(async()=>{const {ISSUE_ITEMS}=await import('/flows/warranty-components/issue-fixture.mjs');Object.assign(ISSUE_ITEMS[1],{sku:'SKU'.repeat(150),name:'Adapter\n'+('Thiếtbị'.repeat(350)),code:'BOX-'+('C'.repeat(220))});});await enter('BOX-'+('C'.repeat(220)));await p.waitForSelector('.p19-sheet');const g=await p.locator('.p19-sheet').evaluate(e=>{const body=e.querySelector('.app-modal-body'),f=e.querySelector('footer'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return {wide:e.scrollWidth>e.clientWidth+1,bodyWide:body.scrollWidth>body.clientWidth+1,footer:fr.bottom<=r.bottom+1,scroll:body.scrollHeight>body.clientHeight};});assert.deepEqual(g,{wide:false,bodyWide:false,footer:true,scroll:true});});
await check('A07','Long SKU in manual/review preserves full text without horizontal overflow',async()=>{await p.evaluate(async()=>{const {ISSUE_ITEMS}=await import('/flows/warranty-components/issue-fixture.mjs');ISSUE_ITEMS[0].sku='SKU'.repeat(180);ISSUE_ITEMS[0].name='Tên '.repeat(150);});await enter('LK0001-HN001');await a('review').click();await pause();assert.equal(await p.locator('.p19-scroll').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);assert.ok(await p.locator('.p19-part [data-hn-read-trigger]:not([hidden])').count());});
await check('A08','IME Enter in quantity does not confirm unfinished composition',async()=>{await enter('BOX-LK-0002-01');await p.locator('#p19-quantity').dispatchEvent('compositionstart');await p.locator('#p19-quantity').press('Enter');assert.equal(await p.locator('.p19-sheet').count(),1);assert.equal((await snap()).lines.length,0);await p.locator('#p19-quantity').dispatchEvent('compositionend');await p.locator('#p19-quantity').press('Enter');await pause();assert.equal((await snap()).lines.length,1);});
await check('A09','Blank scan input validates at field without opening generic dialog',async()=>{await p.click('[data-scan-action=manual]');await p.locator('#p19-code').press('Enter');assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('#p19-code').getAttribute('aria-invalid'),'true');assert.equal(await focus('#p19-code'),true);});
await check('A10','Returning to case then P09 Back does not bounce into P19',async()=>{await enter('LK0001-HN001');await a('back').click();await p.waitForSelector('.p09-app');await p.click('[data-p09=back]');await pause();assert.equal(await p.locator('.p19-app').count(),0);});
await check('A11','Confirm unchanged BOX retains document version and request identity',async()=>{await enter('BOX-LK-0002-01');await quantity(2);await a('review').click();await pause();await p.selectOption('[data-p19-outcome]','error');await a('post').click();await p.waitForSelector('.app-modal-host .hn-action-dialog');await p.getByRole('button',{name:'Đóng',exact:true}).click();await pause();const s=await snap();await a('edit-quantity').click();await quantity(2);const after=await snap();assert.equal(after.document.version,s.document.version);assert.deepEqual(after.request,s.request);});
await check('A12','Back/delete/sheet close targets are at least44 CSS pixels',async()=>{await enter('BOX-LK-0002-01');let g=await p.locator('.p19-sheet [data-p19=close]').first().evaluate(e=>[e.offsetWidth,e.offsetHeight]);assert.ok(g.every(n=>n>=44),JSON.stringify(g));await quantity(2);await a('review').click();await pause();for(const n of ['back','remove']){g=await a(n).evaluate(e=>[e.offsetWidth,e.offsetHeight]);assert.ok(g.every(n=>n>=44),JSON.stringify({n,g}));}});

await check('A13','Quantity field with long metadata is visible immediately inside scrolling sheet',async()=>{await p.evaluate(async()=>{const {ISSUE_ITEMS}=await import('/flows/warranty-components/issue-fixture.mjs');ISSUE_ITEMS[1].name='Tên linh kiện dài '.repeat(160);});await enter('BOX-LK-0002-01');assert.equal(await p.locator('#p19-quantity').evaluate(e=>{const r=e.getBoundingClientRect(),b=e.closest('.app-modal-body').getBoundingClientRect();return r.top>=b.top&&r.bottom<=b.bottom;}),true);assert.equal(await focus('#p19-quantity'),true);});
await check('A14','Posting has accurate busy text and focus; rejected result returns to action',async()=>{await enter('LK0001-HN001');await a('review').click();await pause();await p.selectOption('[data-p19-outcome]','error');await a('post').click();assert.match(await a('post').innerText(),/Đang xuất linh kiện/);assert.equal(await p.locator('.p19-app').evaluate(e=>e.contains(document.activeElement)),true);await p.waitForSelector('.app-modal-host .hn-action-dialog');await p.getByRole('button',{name:'Đóng',exact:true}).click();await pause();assert.equal(await focus('[data-p19=post]'),true);});
await check('A15','Deleting last line disables Post; scan return stays usable',async()=>{await enter('LK0001-HN001');await a('review').click();await pause();await a('remove').click();await p.locator('.app-modal-host').getByRole('button',{name:'Bỏ linh kiện',exact:true}).click();await pause();assert.equal((await snap()).counts.quantity,0);assert.equal(await a('post').isDisabled(),true);assert.equal(await focus('[data-p19=scan]'),true);await a('scan').click();await pause();await enter('LK0001-HN001');assert.equal((await snap()).counts.quantity,1);});
await check('A16','Route away while request pending never opens result/dialog over another case',async()=>{await enter('LK0001-HN001');await a('review').click();await pause();await p.selectOption('[data-p19-outcome]','timeout-posted');await a('post').click();const hash=await p.evaluate(()=>location.hash);await route('#p02/warranty?panel=3&case=BH-003&tab=parts');await p.waitForTimeout(500);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('[data-p09=resume-issue]').count(),0);await route(hash);assert.equal((await snap()).unknown,true);assert.equal(await a('scan').isDisabled(),true);assert.equal((await snap()).metrics.post,1);});
await check('A17','Quantity browser Forward over dismissed sheet cannot confirm or stack overlays',async()=>{await enter('BOX-LK-0002-01');await p.goBack();await pause();assert.equal((await snap()).lines.length,0);await p.goForward();await pause();assert.equal(await p.locator('.p19-sheet').count(),0);assert.equal((await snap()).lines.length,0);await enter('BOX-LK-0002-01');assert.equal(await p.locator('.app-modal-host').count(),1);await quantity(2);assert.equal((await snap()).lines.length,1);});
await check('A18','Repeated invalid then valid quantity keeps one overlay; backdrop and Escape preserve rows',async()=>{await enter('BOX-LK-0002-01');for(const v of ['','0','-2','1.5','abc','13']){await p.fill('#p19-quantity',v);await p.locator('.p19-sheet button[type=submit]').click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.equal((await snap()).lines.length,0);}await p.locator('.app-modal-host').evaluate(e=>e.click());assert.equal(await p.locator('.p19-sheet').count(),1);await p.keyboard.press('Escape');await pause();assert.equal((await snap()).lines.length,0);await enter('BOX-LK-0002-01');await quantity(12);assert.equal((await snap()).counts.quantity,12);});

await check('A19','New BOX quantity fits remaining stock1; exhausted BOX does not open impossible form',async()=>{await enter('BOX-LK-0002-01');await quantity(11);await a('review').click();await pause();await a('post').click();await p.waitForSelector('[data-panel="P19.S04"]');await a('case').click();await p.click('[data-p09=issue]');await enter('BOX-LK-0002-01');assert.equal(await p.inputValue('#p19-quantity'),'1');assert.equal(await a('plus').isDisabled(),true);assert.equal(await a('minus').isDisabled(),true);await quantity(1);await a('review').click();await pause();await a('post').click();await p.waitForSelector('[data-panel="P19.S04"]');await a('case').click();await p.click('[data-p09=issue]');await enter('BOX-LK-0002-01');assert.equal(await p.locator('.p19-sheet').count(),0);assert.equal((await snap()).lines.length,0);await p.waitForSelector('.app-modal-host .hn-action-dialog');});
fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));if(!before&&(checks.some(c=>c.status!=='PASS')||errors.length))process.exitCode=1;
}finally{await b.close();}})();
