const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const phase=process.env.P18_AUDIT_PHASE||'before',out='handoff/P18/evidence/revision-03/'+phase;fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),observations=[],errors=[];p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
const act=a=>p.locator(`[data-p18="${a}"]`).first(),demo=async n=>{await p.locator('.p18-tools').evaluate(e=>e.open=true);await p.click(`[data-p18-demo=${n}]`);},painted=()=>p.waitForFunction(()=>document.querySelector('.p18-paper')?.getAttribute('aria-busy')==='false');
const note=(id,pass,evidence)=>{observations.push({id,status:pass?'PASS':'FAIL',evidence});console.log(id+': '+(pass?'PASS':'FAIL')+' '+JSON.stringify(evidence));};
const shot=async n=>{await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});};
try{await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
await demo('ready');const footerY=await p.locator('.p18-footer').evaluate(e=>e.getBoundingClientRect().top);await p.check('[name=checked]');await p.fill('[name=receiver]','Nguyễn Văn Bình');const footerY2=await p.locator('.p18-footer').evaluate(e=>e.getBoundingClientRect().top);note('R03-01 stable form footer',Math.abs(footerY-footerY2)<=1,{before:footerY,after:footerY2});await shot('form-filled');
await demo('location');await p.check('[data-p18-capacity]');await p.locator('.p18-location-details summary').click();await p.click('[data-slot=B2]');const open=await p.locator('.p18-location-details').evaluate(e=>e.open);note('R03-02 location expansion retained',open,{open});const nav=await p.locator('.hn-nav [aria-current=page]').getAttribute('data-tab');note('R03-03 owner nav identity',nav==='lookup',{nav});await shot('location-after-selection');
await demo('files');await p.locator('.p18-file-name').first().click();await painted();const hiddenStop=await p.locator('.p18-pdf-text[tabindex="0"]').count();note('R03-04 no invisible expanding keyboard stop',hiddenStop===0,{hiddenStop});if(hiddenStop){await p.locator('.p18-pdf-text').focus();await shot('pdf-hidden-focus');await act('back').click();await p.locator('.p18-file-name').first().click();await painted();}
let plusFont=await act('zoom-in').evaluate(e=>getComputedStyle(e).fontSize),plusSvg=await act('zoom-in').locator('svg').count();note('R03-05 readable zoom icon',plusSvg>0||parseFloat(plusFont)>=20,{plusFont,plusSvg});
for(let i=0;i<6;i++){await act('zoom-in').click();await painted();}const focus=await p.evaluate(()=>document.activeElement?.dataset.p18||document.activeElement?.tagName);note('R03-06 focus at zoom limit',['zoom-in','zoom-out'].includes(focus),{focus});
await p.selectOption('[data-p18-fit]','width');await painted();await act('zoom-in').click();await painted();await act('zoom-in').click();await painted();await p.locator('.p18-document-viewport').evaluate(e=>{e.scrollLeft=80;e.scrollTop=140;});const center=()=>p.locator('.p18-document-viewport').evaluate(e=>{const paper=e.querySelector('.p18-paper');return {x:(e.scrollLeft+e.clientWidth/2)/paper.offsetWidth,y:(e.scrollTop+e.clientHeight/2)/paper.offsetHeight};});const c1=await center();await act('zoom-in').click();await painted();const c2=await center();note('R03-07 reading point on zoom',Math.abs(c1.x-c2.x)<.005&&Math.abs(c1.y-c2.y)<.005,{before:c1,after:c2});await shot('zoom-point');
await p.evaluate(async()=>{const m=await import('/flows/documents/document-model.mjs');window.auditDoc=m.DOCUMENTS.find(d=>d.id==='fixture-inbound-0005');window.auditAttachments=structuredClone(auditDoc.attachments);auditDoc.attachments=null;location.hash='#p02/attachments?panel=1&doc=fixture-inbound-0005';});await p.waitForSelector('[data-panel="P18.S01"]');const text=await p.locator('.p18-app').innerText();note('R03-08 unknown is not empty',!/Danh sách tệp đính kèm \(0\)|Chưa có tệp đính kèm/.test(text),{body:text});await shot('missing-list-source');
await p.evaluate(()=>{auditDoc.attachments=auditAttachments;location.hash='#home';});await p.waitForSelector('#hn-home:not([hidden])');await p.evaluate(()=>location.hash='#p02/attachments?panel=1&doc=fixture-inbound-0005');await p.waitForSelector('[data-panel="P18.S01"]');await p.waitForTimeout(200);const recovered=await p.locator('[data-p18=download]').count();note('R03-09 recovered source is refreshed',recovered===2,{recovered});await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.evaluate(async()=>{const m=await import('/flows/documents/document-model.mjs');window.auditDoc=m.DOCUMENTS.find(d=>d.id==='fixture-inbound-0005');window.auditAttachments=structuredClone(auditDoc.attachments);location.hash='#p02/attachments?panel=1&doc=fixture-inbound-0005';});await p.waitForSelector('[data-p18=download]');let downloads=0;const listener=()=>downloads++;p.on('download',listener);await p.evaluate(()=>auditDoc.attachments=[]);await act('download').click();await p.waitForTimeout(600);p.off('download',listener);note('R03-10 removed source file cannot download',downloads===0,{downloads});if(await p.locator('.app-modal-host').count()){await p.keyboard.press('Escape');await p.waitForTimeout(120);}await p.evaluate(()=>auditDoc.attachments=auditAttachments);
fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify({phase,observations,errors},null,2));if(phase==='after'){assert.deepEqual(errors,[]);assert.ok(observations.every(x=>x.status==='PASS'),JSON.stringify(observations.filter(x=>x.status!=='PASS')));}
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({observations,errors,error:e.stack},null,2));await shot('failure').catch(()=>{});throw e;}finally{await b.close();}})();
