const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const phase=process.env.SHARED_UX_PHASE||'before',out=path.resolve(`handoff/ux-audit-2026-09-30-r02/shared/${phase}`);fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),p=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});p.setDefaultTimeout(12000);const results=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const settle=()=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.stack});await p.screenshot({path:path.join(out,`${name}.png`),fullPage:true});console.log('FAIL '+name+': '+e.message.slice(0,250));}finally{await p.evaluate(()=>window.__auditModal?.close());await settle();}}
try{
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-nav').waitFor();
 await check('long-action-title-keeps-decision-actions-visible',async()=>{await p.evaluate(async()=>{const {openActionDialog}=await import('/flows/shared/action-dialog.mjs');window.__auditTitle=('Tên đối tượng dài Ánh <&>\n').repeat(80);window.__auditModal=openActionDialog({screen:document.querySelector('.hn-screen'),title:window.__auditTitle,message:'Giá trị đầy đủ vẫn phải đọc được trước khi xác nhận.',cancelLabel:'Hủy',confirmLabel:'Xác nhận'});});await settle();await p.locator('.hn-screen').screenshot({path:path.join(out,'long-title.png')});const m=await p.evaluate(()=>{const d=document.querySelector('dialog[open]'),r=d.getBoundingClientRect(),b=d.querySelector('.app-modal-footer').getBoundingClientRect(),s=document.querySelector('.hn-screen').getBoundingClientRect();return{dialog:r.toJSON(),footer:b.toJSON(),shell:s.toJSON(),title:d.querySelector('h2').textContent===window.__auditTitle,bodyHeight:d.querySelector('.app-modal-body').clientHeight};});results.push({measurement:'long-title',...m});assert.ok(m.title);assert.ok(m.footer.bottom<=m.shell.bottom+1&&m.footer.top>=m.dialog.top&&m.bodyHeight>0,JSON.stringify(m));});
 await check('long-picker-scope-does-not-push-close-or-footer-away',async()=>{await p.evaluate(async()=>{const {openHistoryPicker}=await import('/flows/history/history-picker.mjs');window.__auditModal=openHistoryPicker({screen:document.querySelector('.hn-screen'),mode:'filter',filters:{type:'all',status:'all',from:'',to:''},day:'2026-09-30',scopeLabel:'MÃ-'+('ABCDEFGHÁnh').repeat(250),quickRanges:true,onApply:()=>{},onClose:()=>{}});});await settle();await p.locator('.hn-screen').screenshot({path:path.join(out,'long-picker-scope.png')});const m=await p.evaluate(()=>{const d=document.querySelector('dialog[open]'),s=document.querySelector('.hn-screen').getBoundingClientRect(),f=d.querySelector('footer').getBoundingClientRect(),h=d.querySelector('header').getBoundingClientRect(),c=d.querySelector('header [data-cancel]').getBoundingClientRect();return{footer:f.toJSON(),header:h.toJSON(),close:c.toJSON(),shell:s.toJSON(),body:d.querySelector('.app-modal-body').getBoundingClientRect().toJSON(),overflow:d.scrollWidth>d.clientWidth+1};});results.push({measurement:'picker-scope',...m});assert.ok(!m.overflow&&m.close.right<=m.shell.right+1&&m.footer.bottom<=m.shell.bottom+1&&m.body.height>=80,JSON.stringify(m));});
 await check('long-picker-scope-is-readable-without-horizontal-clipping',async()=>{await p.evaluate(async()=>{const {openHistoryPicker}=await import('/flows/history/history-picker.mjs');window.__scopeText='MÃ-'+('ABCDEFGHÁnh').repeat(250);window.__auditModal=openHistoryPicker({screen:document.querySelector('.hn-screen'),mode:'filter',filters:{type:'all',status:'all',from:'',to:''},day:'2026-09-30',scopeLabel:window.__scopeText,quickRanges:true,onApply:()=>{},onClose:()=>{}});});await settle();const m=await p.locator('.p08-picker-context').evaluate(n=>({textMatches:n.textContent===window.__scopeText,width:n.clientWidth,scrollWidth:n.scrollWidth,height:n.clientHeight,scrollHeight:n.scrollHeight,focusable:n.tabIndex,overflow:getComputedStyle(n).overflowY}));results.push({measurement:'scope-readable',...m});await p.locator('.hn-screen').screenshot({path:path.join(out,'scope-readable.png')});assert.ok(m.textMatches&&m.scrollWidth<=m.width+1);assert.ok(m.height>=m.scrollHeight||m.focusable===0&&m.overflow==='auto',JSON.stringify(m));});
 await check('touch-minimum-responds-to-shell-transform-without-window-resize',async()=>{await p.evaluate(()=>location.hash='#p02/lookup');await p.locator('.p06-app').waitFor();await settle();const before=await p.locator('[data-p06="back"]').boundingBox();await p.locator('.hn-screen').evaluate(n=>n.style.transform='scale(0.6)');await p.waitForTimeout(150);const after=await p.locator('[data-p06="back"]').boundingBox();results.push({measurement:'style-only-scale',before,after});assert.ok(after.width>=43.8&&after.height>=43.8,JSON.stringify(after));});
}catch(e){results.push({name:'runner',status:'FAIL',error:e.stack});}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({phase,results,errors},null,2));console.log(JSON.stringify({phase,checks:results.filter(r=>r.name).map(r=>({name:r.name,status:r.status})),errors}));await browser.close();}})();
