const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const phase=process.env.P15_AUDIT_PHASE||'after',out=`handoff/P15/evidence/revision-03/${phase}`;fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'});p.setDefaultTimeout(10000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const panel=()=>p.locator('.p15-app:visible'),a=k=>panel().locator(`[data-p15=${k}]`).first(),modal=()=>p.locator('.app-modal-host dialog');
const check=async(name,run)=>{try{await run();checks.push({name,status:'PASS'});}catch(e){checks.push({name,status:'FAIL',error:String(e)});}console.log(checks.at(-1));};
async function close(){if(await modal().count()){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));}await p.evaluate(()=>window.audit?.hide());await p.waitForTimeout(100);}
try{await p.goto((process.env.P15_BASE_URL||'http://localhost:8766/flows/auth-session/'));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-screen').waitFor();
await p.evaluate(async()=>{const {mountSystem}=await import('/flows/system/view.mjs');const {createDeviceAccess}=await import('/flows/system/model.mjs');window.deviceState={camera:'not-requested',nfc:'not-requested',pending:false};window.deniedGuards=0;window.audit=mountSystem({routeKey:'hnP15Audit',screen:document.querySelector('.hn-screen'),tools:document.querySelector('.hn-tools'),getContext:()=>null,onHome(){},onLogin(){},onExpire(){},onForbidden(){window.deniedGuards++},deviceAccess:{snapshot:()=>({...deviceState}),async requestCamera(){deviceState.pending=true;await new Promise(r=>window.finishCamera=r);deviceState.pending=false;deviceState.camera='granted';return 'granted';},reportFailure(type,error){deviceState[type]=error.name==='NotAllowedError'?'denied':'hardware-error';}}});});
await check('F01 no-source guidance restores focus to its CTA',async()=>{await p.evaluate(()=>audit.show('connection'));await a('retry').click();await modal().waitFor();await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await a('retry').evaluate(e=>e===document.activeElement));});await close();
await check('F02 pending camera keeps scroll and indicates busy without dropping focus',async()=>{await p.addStyleTag({content:'.p15-device-heading p{font-size:24px!important;line-height:36px!important}'});await p.evaluate(()=>audit.show('device'));await panel().locator('.p15-body').evaluate(e=>e.scrollTop=40);const top=await panel().locator('.p15-body').evaluate(e=>e.scrollTop);assert.ok(top>0);await a('camera').click();assert.equal(await panel().locator('.p15-body').evaluate(e=>e.scrollTop),top);assert.equal(await panel().getAttribute('aria-busy'),'true');assert.ok(await panel().evaluate(e=>e.contains(document.activeElement)));await p.evaluate(()=>finishCamera());await modal().waitFor();});await close();
// Settle the controllable prompt even when the old implementation failed above.
await p.evaluate(()=>{window.finishCamera?.();deviceState.pending=false;deviceState.camera='granted'});
await check('F03 granted camera copy no longer asks user to grant again',async()=>{await p.evaluate(()=>audit.show('device'));assert.doesNotMatch(await panel().locator('.p15-device-heading').first().innerText(),/Cấp quyền để/);});await close();
await check('F04 denied NFC instructions specifically explain permissions',async()=>{await p.evaluate(()=>{deviceState.nfc='denied';audit.show('device')});await a('nfc-guide').click();assert.match(await modal().innerText(),/quyền NFC/);await p.locator('.hn-screen').screenshot({path:out+'/nfc-denied-guide.png'});});await close();
await check('F05 read 403 activates caller guard, not just presentation',async()=>{await p.evaluate(()=>audit.show('connection',{intent:'read',read:async()=>{throw {status:403}}}));await a('retry').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>deniedGuards),1);});await close();
await check('F06 camera action cannot run from detached/hidden panel',async()=>{await p.evaluate(()=>{deviceState.camera='not-requested';audit.show('device');audit.hide();document.querySelector('.p15-app:last-child [data-p15=camera]').click()});assert.equal(await p.evaluate(()=>deviceState.pending),false);});await p.evaluate(()=>{window.finishCamera?.();deviceState.pending=false});await close();
await check('F07 closing system state consumes temporary history entry',async()=>{await p.evaluate(()=>{history.replaceState({caller:'audit'},'',location.hash);audit.show('connection');audit.hide()});await p.waitForTimeout(100);await p.goBack();await p.waitForTimeout(100);assert.notEqual(await p.evaluate(()=>history.state?.caller),'audit');});
await p.evaluate(()=>window.audit?.dispose());
await check('F08 no runtime browser errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(out+'/audit-results.json',JSON.stringify({phase,checks,errors},null,2));if(phase==='after')assert.ok(checks.every(c=>c.status==='PASS'));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
