const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const phase=process.argv[2]||'after',out=`handoff/P21/evidence/revision-03/${phase}/audit`;
fs.mkdirSync(out,{recursive:true});
// Deterministic slow reads and malformed display snapshots at the view boundary only.
// No test hooks are written into shipped modules; native owner actions stay real.
(async()=>{const browser=await chromium.launch(),results=[];
async function test(id,name,run){if(process.argv[3]&&!process.argv[3].split(',').includes(id))return;const p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),errors=[];p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));
try{await p.route('**/resume-view.mjs',async route=>{const r=await route.fetch();let s=await r.text();s=s.replace(' let active=false',` const getOriginalOwner=getOwner;getOwner=(...args)=>{const o=getOriginalOwner(...args);if(o&&!o.__audit){o.__audit=true;const original=o.snapshot;o.snapshot=()=>{const s=original();return window.__display?window.__display(s):s;};window.__owner=o;}return o;};\n let active=false`);await route.fulfill({response:r,body:s});});
await p.route('**/issue-view.mjs',async route=>{const r=await route.fetch();const s=(await r.text()).replace('createCheckpointFixture({delay:180})','createCheckpointFixture({delay:900})');await route.fulfill({response:r,body:s});});
await p.goto('http://localhost:8766/flows/auth-session/?v=p21-r03-audit');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p21-tools').evaluate(e=>e.open=true);
const a=n=>p.locator(`[data-p21="${n}"]`),demo=async name=>{await p.click(`[data-p21-demo="${name}"]`);await p.waitForSelector('.p21-app');},ready=()=>p.waitForSelector('[data-p21=scan]:not(:disabled)'),snap=()=>p.evaluate(()=>window.__owner.snapshot());
await run({p,a,demo,ready,snap});assert.deepEqual(errors,[]);results.push({id,name,status:'PASS'});
}catch(e){results.push({id,name,status:'FAIL',error:e.message,errors});}finally{await p.locator('.hn-screen').screenshot({path:`${out}/${id}.png`}).catch(()=>{});await p.close();console.log(results.at(-1).status+' '+id+' '+name);fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));}}
try{
await test('F01','Read completion preserves current Back focus',async({p,a,demo,ready})=>{await demo('resume');await a('back').focus();await ready();assert.equal(await a('back').evaluate(e=>e===document.activeElement),true);});
await test('F02','Read completion preserves user scroll',async({p,demo,ready})=>{await p.evaluate(()=>window.__display=s=>({...s,lines:Array.from({length:15},(_,i)=>({...s.lines[0],code:'CODE-'+i}))}));await demo('resume');await p.locator('.p21-scroll').evaluate(e=>e.scrollTop=400);await ready();assert.ok(await p.locator('.p21-scroll').evaluate(e=>e.scrollTop>=399));});
await test('F03','Reader remains open across read completion; focus returns to reader',async({p,demo})=>{await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs'),c=m.readWarrantyCases().find(c=>c.id==='BH-001');m.writeWarrantyCase({...c,model:'Nội dung < & >\n'+'Dữ liệu dài '.repeat(220)});});await demo('resume');const read=p.getByRole('button',{name:'Xem đầy đủ sản phẩm bảo hành',exact:true});await read.click();await p.waitForTimeout(1100);assert.equal(await p.locator('.hn-action-dialog[open]').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(200);assert.equal(await read.evaluate(e=>e===document.activeElement),true);});
await test('F04','No focus stolen from simulator when read completes',async({p,demo,ready})=>{await demo('resume');await p.locator('[data-p21-source]').focus();await ready();assert.equal(await p.locator('[data-p21-source]').evaluate(e=>e===document.activeElement),true);});
await test('F05','Invalid checkpoint date shows unverified without render crash',async({p,demo})=>{await p.evaluate(()=>window.__display=s=>({...s,checkpoint:{...s.checkpoint,savedAt:'invalid-date'}}));await demo('reconcile');await p.waitForSelector('[data-panel="P21.S03"]');await p.waitForTimeout(1100);assert.match(await p.locator('.p21-app').innerText(),/Lần giữ gần nhất[\s\S]*Chưa xác minh/);});
await test('F06','Long quantity cannot push row outside card',async({p,demo,ready})=>{await p.evaluate(()=>window.__display=s=>({...s,lines:s.lines.map(l=>({...l,quantity:'9'.repeat(60)}))}));await demo('resume');await ready();const inside=await p.locator('.p19-part').evaluate(e=>{const r=e.getBoundingClientRect();return [...e.querySelectorAll('*')].filter(n=>n.getClientRects().length).every(n=>{const b=n.getBoundingClientRect();return b.right<=r.right+1&&b.left>=r.left-1;});});assert.equal(inside,true);});
await test('F07','Long totals keep fixed footer inside app',async({p,demo,ready})=>{await p.evaluate(()=>window.__display=s=>({...s,counts:{codes:'9'.repeat(60),quantity:'8'.repeat(60)}}));await demo('resume');await ready();assert.equal(await p.locator('.p21-footer').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);});
await test('F08','Unknown counts never rendered null or undefined',async({p,demo,ready})=>{await p.evaluate(()=>window.__display=s=>({...s,counts:{codes:null,quantity:undefined}}));await demo('resume');await ready();const value=await p.locator('.p21-ready-summary').innerText();assert.doesNotMatch(value,/null|undefined/);assert.match(value,/Chưa xác minh/);});
await test('F09','Checkpoint pending export icon keeps neutral status',async({p,demo,ready})=>{await demo('resume');await ready();const colors=await p.locator('.p21-checkpoint').evaluate(e=>[...e.querySelectorAll('svg')].map(n=>getComputedStyle(n).color));assert.notEqual(colors[2],colors[0]);});
for(const close of ['Escape','Back'])await test('F10'+close,`Confirmed not-posted can resume after ${close}`,async({p,a,ready})=>{await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-001');await p.waitForSelector('#p19-manual-form',{state:'attached'}).catch(()=>{});await p.click('[data-scan-action=manual]');await p.fill('#p19-code','LK0001-HN001');await p.locator('#p19-manual-form button[type=submit]').click();await p.click('[data-p19=review]');await p.locator('.p19-tools').evaluate(e=>e.open=true);await p.selectOption('[data-p19-outcome]','not-posted');await p.click('[data-p19=post]');await p.getByRole('button',{name:'Để sau',exact:true}).click();await p.waitForTimeout(180);await p.click('[data-p19=back]');await a('check').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Đã xác minh chưa xuất/);if(close==='Escape')await p.keyboard.press('Escape');else await p.goBack();await ready();});
await test('F11','Stale copy feedback suppressed if same owner changes',async({p,a,demo})=>{await demo('post-check');await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>window.__copyDone=r)}}));await a('identity').click();await p.getByRole('button',{name:'Sao chép thông tin đối chiếu',exact:true}).click();await p.waitForFunction(()=>typeof window.__copyDone==='function');await p.evaluate(()=>{window.__display=s=>({...s,document:{...s.document,version:s.document.version+1}});window.__copyDone();});await p.waitForTimeout(250);assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);});
await test('F12','Same-document return restores bottom reader focus and scroll',async({p,a,demo,ready})=>{await p.evaluate(()=>window.__display=s=>({...s,lines:s.lines.map(l=>({...l,code:'Gốc <&>\n'+'x'.repeat(250)}))}));await demo('resume');await ready();const read=p.getByRole('button',{name:'Xem đầy đủ mã đã lưu',exact:true});await read.click();await p.keyboard.press('Escape');await p.waitForTimeout(180);await p.evaluate(()=>window.__owner.scan('BOX-LK-0002-01'));await p.waitForTimeout(120);assert.equal(await read.evaluate(e=>e===document.activeElement),true);});
await test('F13','Header Back consumes matching list entry without native Back loop',async({p,a,demo,ready})=>{await demo('drafts');await a('open').click();await ready();await a('back').click();await p.waitForSelector('[data-panel="P21.S01"]');await p.goBack();await p.waitForTimeout(1100);assert.equal(await p.locator('.p21-app').count(),0);});
await test('F14','Pending copy result never interrupts a newer full-text dialog',async({p,a,demo})=>{await demo('post-check');await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>window.__copyDone=r)}}));await a('identity').click();await p.getByRole('button',{name:'Sao chép thông tin đối chiếu',exact:true}).click();await p.waitForFunction(()=>typeof window.__copyDone==='function');await a('guide').click();await p.evaluate(()=>window.__copyDone());await p.waitForTimeout(200);assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Hướng dẫn đối chiếu/);assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Escape');await p.waitForFunction(()=>document.querySelector('.hn-action-dialog[open]')?.textContent.includes('Đã sao chép'));await p.keyboard.press('Escape');await p.waitForTimeout(200);assert.equal(await a('guide').evaluate(e=>e===document.activeElement),true);});
await test('F15','Reconciliation and copy-failure dialogs preserve raw line breaks and scroll',async({p,a,demo})=>{await demo('post-check');await p.evaluate(()=>window.__display=s=>({...s,lines:[{...s.lines[0],code:'GỐC <&>  hai khoảng trắng\n'+'Mã Ω '.repeat(450)}]}));await a('identity').click();const message=p.locator('.hn-action-dialog[open] .app-modal-body p');assert.equal(await message.evaluate(e=>getComputedStyle(e).whiteSpace),'pre-wrap');assert.ok((await message.textContent()).includes('GỐC <&>  hai khoảng trắng\n'));await p.locator('.hn-action-dialog[open] .app-modal-body').evaluate(e=>e.scrollTop=e.scrollHeight);assert.equal(await p.locator('.hn-action-dialog[open]').evaluate(e=>{const r=e.getBoundingClientRect();return [...e.querySelectorAll('button')].every(b=>{const z=b.getBoundingClientRect();return z.top>=r.top&&z.bottom<=r.bottom+1;});}),true);await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(Error('denied'))}}));await p.getByRole('button',{name:'Sao chép thông tin đối chiếu',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.hn-action-dialog[open]')?.textContent.includes('Chưa sao chép được'));assert.equal(await message.evaluate(e=>getComputedStyle(e).whiteSpace),'pre-wrap');assert.ok((await message.textContent()).includes('GỐC <&>  hai khoảng trắng\n'));assert.equal(await p.locator('.app-modal-host').count(),1);assert.equal(await p.locator('.hn-action-dialog[open]').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);});
}finally{await browser.close();}const failed=results.filter(r=>r.status==='FAIL');console.log(JSON.stringify({total:results.length,failed:failed.length}));if(phase!=='before'&&failed.length)process.exitCode=1;
})();
