const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const {mockGeography,choose,address}=require('./outbound_geography_helpers.cjs');
const phase=process.argv[2]||'before',filter=process.argv[3],out='handoff/P24/evidence/revision-03/'+phase;fs.mkdirSync(out,{recursive:true});
const long='Đ'.repeat(1600),result=[];
(async()=>{const browser=await chromium.launch();
async function run(id,title,fn,overrides={}){if(filter&&id!==filter)return;const p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:'reduce'}),errors=[];p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);if(phase==='before')await p.route('**/flows/**',r=>{const file='handoff/P24/evidence/revision-03/before/source/docs'+decodeURIComponent(new URL(r.request().url()).pathname);if(fs.existsSync(file)&&/\.(mjs|css)$/.test(file))return r.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.css')?'text/css':'text/javascript'});return r.continue();});for(const [file,transform]of Object.entries(overrides))await p.route('**/flows/'+file+'*',r=>r.fulfill({body:transform(fs.readFileSync((phase==='before'?'handoff/P24/evidence/revision-03/before/source/docs/flows/':'docs/flows/')+file,'utf8')),contentType:'text/javascript'}));
 const pause=()=>p.waitForTimeout(220),snap=async pre=>JSON.parse(await p.locator(`[data-${pre}-snapshot]`).textContent());
 const shot=async()=>{await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+id+'.png'});};
 async function input(code){if(!await p.locator('#p19-code').count())await p.click('[data-scan-action=manual]');await p.fill('#p19-code',code);await p.locator('#p19-manual-form [type=submit]').click();}
 async function historyCase(id='BH-002',sample='history'){await p.evaluate(({id,sample})=>location.hash='#p02/component-history?'+new URLSearchParams({case:id,...(sample?{sample}:{})}),{id,sample});await p.waitForSelector('[data-p20-document]');}
 async function stock(kind){const pre=kind==='inbound'?'p04':'p05';await p.evaluate(()=>location.hash='#home');await p.click(`.hn-task[data-route=${kind}]`);await p.locator('.'+pre+'-tools').evaluate(e=>e.open=true);if(pre==='p05'){await choose(p,'source','board-0005');await p.getByRole('button',{name:'Đổi phiếu',exact:true}).click();await pause();await address(p);}await p.click(`[data-${pre}=next]`);await p.click(`[data-${pre}=batch]`);if(pre==='p05'){await p.click('[data-p05=manual]');for(const c of ['HN12352','HN12353','HN12354']){await p.fill('#p05-code',c);await p.locator('.p05-manual [type=submit]').click();}}await p.click(`[data-${pre}=next]`);await p.click(`[data-${pre}=send]`);await p.waitForSelector('.hn-waiting-web');return pre;}
 const row={id,title};try{await p.goto('http://localhost:8766/flows/auth-session/?v=p24-r03-audit');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p19-tools').evaluate(e=>e.open=true);await fn({p,pause,snap,shot,input,historyCase,stock});assert.deepEqual(errors,[]);row.status='PASS';}catch(e){row.status='FAIL';row.error=e.message;row.errors=errors;}finally{await shot().catch(()=>{});result.push(row);console.log(id+' '+row.status+' '+title+(row.error?' :: '+row.error.split('\n')[0]:''));fs.writeFileSync(out+(filter?'/audit-'+filter+'.json':'/audit.json'),JSON.stringify(result,null,2));await p.close();}}
await run('A01','Entering S02 starts at top instead of inherited scan scroll',async({p,input})=>{await p.click('[data-p19-open]');for(let i=0;i<6;i++)await input('AUDIT-U'+i);const prior=await p.locator('#p19-manual-form').evaluate(e=>{const f=e.querySelector('input');f.value='BOX-NOT-RECEIVED';f.dispatchEvent(new Event('input',{bubbles:true}));const sc=document.querySelector('.p19-scroll');sc.scrollTop=180;const top=sc.scrollTop;e.requestSubmit();return top;});assert.ok(prior>50,'Setup: scan must be scrollable');assert.equal(await p.locator('.p19-scroll').evaluate(e=>e.scrollTop),0);},{'warranty-components/issue-fixture.mjs':s=>s.replace('Object.freeze([',"Object.freeze([...Array.from({length:6},(_,i)=>({kind:'UNIT',code:'AUDIT-U'+i,sku:'AUDIT-'+i,name:'Linh kiện thử '+i,available:1})),")});
await run('A02','Leaving rejection by a different route renders the requested destination',async({p,pause})=>{await p.click('[data-p19-demo=scan-error]');await p.evaluate(()=>location.hash='#home');await pause();assert.equal(await p.locator('#hn-home').isVisible(),true);});
await run('A03','Closed-case footer geometry stays stable during load-more',async({p,historyCase,shot})=>{await historyCase();await p.locator('.p20-tools').evaluate(e=>e.open=true);await p.selectOption('[data-p20-mode]','slow');const before=await p.locator('.p20-footer').evaluate(e=>({h:e.offsetHeight,button:e.querySelector('[data-p20=history]').offsetHeight}));await p.click('[data-p20=load]');const after=await p.locator('.p20-footer').evaluate(e=>({h:e.offsetHeight,button:e.querySelector('[data-p20=history]').offsetHeight}));await shot();assert.deepEqual(after,before);});
await run('A04','Read completion reflects newly closed case consistently',async({p,historyCase})=>{await historyCase('BH-001');await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.writeWarrantyCase({...m.readWarrantyCases().find(c=>c.id==='BH-001'),status:'Đã trả khách'});});await p.click('[data-p20=load]');await p.waitForSelector('.p20-end');assert.match(await p.locator('.p20-context').innerText(),/Đã trả khách/);assert.equal(await p.locator('.p24-closed-note').count(),1);assert.equal(await p.locator('[data-p20=history]').count(),1);assert.equal(await p.locator('[data-p20=issue]').isVisible(),false);});
await run('A05','Long receipt time wraps and has a full-text reader',async({p,historyCase})=>{await historyCase();assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);assert.equal(await p.locator('.p20-time + .hn-read-more').count(),1);},{'warranty-components/history-fixture.mjs':s=>s.replace('rows=[...new Map',`rows=rows.map(r=>({...r,at:${JSON.stringify(long)}}));rows=[...new Map`)});
async function longCase({p}){await p.evaluate(async raw=>{const m=await import('/flows/shared/warranty-cases.mjs');m.writeWarrantyCase({...m.readWarrantyCases().find(c=>c.id==='BH-001'),id:raw});location.hash='#p02/component-issue?'+new URLSearchParams({case:raw,panel:1});},'BH-'+long);await p.waitForSelector('.p19-app');}
await run('A06','Long case ID in rejection context stays contained and readable',async(ctx)=>{await longCase(ctx);await ctx.input('BOX-NOT-RECEIVED');assert.equal(await ctx.p.locator('.p19-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);});
await run('A07','Long case context cannot overflow quantity sheet help',async(ctx)=>{await longCase(ctx);await ctx.input('BOX-LK-0002-01');assert.equal(await ctx.p.locator('.p19-sheet .app-modal-body').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);});
for(const [id,kind]of [['A08','inbound'],['A09','outbound']])await run(id,'Document Back restores '+kind+' result CTA focus',async({p,stock})=>{const pre=await stock(kind);await p.click(`[data-${pre}=document]`);await p.waitForSelector('.p12-app');await p.goBack();await p.waitForSelector('.hn-waiting-web');await p.waitForTimeout(100);assert.equal(await p.locator(`[data-${pre}=document]`).evaluate(e=>e===document.activeElement),true);});
await run('A10','Outbound result restores inner scroll after document Back',async({p,stock})=>{await stock('outbound');await p.locator('.p05-scroll').evaluate(e=>e.scrollTop=70);const top=await p.locator('.p05-scroll').evaluate(e=>e.scrollTop);assert.ok(top>20,'Setup: result is scrollable');await p.click('[data-p05=document]');await p.waitForSelector('.p12-app');await p.goBack();await p.waitForSelector('.hn-waiting-web');await p.waitForTimeout(100);assert.ok(Math.abs(await p.locator('.p05-scroll').evaluate(e=>e.scrollTop)-top)<2);},{'outbound/fixture-adapter.mjs':s=>s.replace('warehouseName:session.warehouse.name',`warehouseName:${JSON.stringify('Kho '+long)}`).replace("sentAt:'09/09/2026 14:32'",`sentAt:${JSON.stringify(long)}`)});
await run('A11','Timeline components shortcut returns same history source and loaded pages',async({p,historyCase})=>{await historyCase();await p.click('[data-p20=load]');await p.waitForSelector('.p20-end');const origin=new URL(p.url()).hash,ids=await p.locator('[data-p20-document]').evaluateAll(es=>es.map(e=>e.dataset.p20Document));await p.click('[data-p20=timeline]');await p.waitForSelector('.p23-app');await p.click('[data-p23=components]');await p.waitForSelector('.p20-app');assert.equal(new URL(p.url()).hash,origin);assert.deepEqual(await p.locator('[data-p20-document]').evaluateAll(es=>es.map(e=>e.dataset.p20Document)),ids);});
await run('A12','Keyboard stepper reaching limit keeps focus inside sheet',async({p})=>{await p.click('[data-p19-demo=quantity]');await p.fill('#p19-quantity','11');await p.locator('.p19-sheet [data-p19=plus]').focus();await p.keyboard.press('Enter');assert.equal(await p.inputValue('#p19-quantity'),'12');assert.equal(await p.locator('.p19-sheet').evaluate(e=>e.contains(document.activeElement)),true);});
await run('A13','Depleted single component is not called a box in validation',async({p,input})=>{await p.click('[data-p19-open]');await input('LK0001-HN001');await p.waitForSelector('.hn-action-dialog[open]');assert.doesNotMatch(await p.locator('.hn-action-dialog[open]').innerText(),/của hộp/);},{'warranty-components/issue-fixture.mjs':s=>s.replace("code:'LK0001-HN001',available:1", "code:'LK0001-HN001',available:0")});
for(const [id,kind]of [['A14','inbound'],['A15','outbound']])await run(id,'History Back retains '+kind+' verified result and focus',async({p,stock})=>{const pre=await stock(kind);await p.click(`[data-${pre}=history]`);await p.waitForSelector('.p08-app');await p.goBack();await p.waitForSelector(`.${pre}-app`);await p.waitForTimeout(100);assert.equal(await p.locator('.hn-waiting-web').count(),1);assert.equal(await p.locator(`[data-${pre}=history]`).evaluate(e=>e===document.activeElement),true);});
await run('A16','Forward to old receipt then Back keeps new inbound draft interactive',async({p,stock,snap,pause})=>{await stock('inbound');await p.click('[data-p04=document]');await p.waitForSelector('.p12-app');await p.goBack();await p.waitForSelector('.hn-waiting-web');await p.click('[data-p04=new-run]');await p.waitForSelector('[data-panel="P04.S01"]');const id=(await snap('p04')).document.documentId;await p.goForward();await p.waitForSelector('.p12-app');await p.goBack();await pause();await p.click('[data-p04=next]');assert.equal((await snap('p04')).step,2);assert.equal((await snap('p04')).document.documentId,id);});
await browser.close();console.log(JSON.stringify({phase,pass:result.filter(r=>r.status==='PASS').length,fail:result.filter(r=>r.status==='FAIL').length}));if(phase==='after'&&result.some(r=>r.status==='FAIL'))process.exitCode=1;})();
