const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path');
const out='handoff/P16/evidence/revision-03/before';
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),observations=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/home/home.mjs*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('docs/flows/home/home.mjs','utf8').replace('onSystemError:showSystem,supplierHistory','readList:window.auditRead,onSystemError:showSystem,supplierHistory')}));
await p.addInitScript(()=>{window.mode='ready';window.pending=[];window.auditRead=()=>mode==='pending'?new Promise(resolve=>pending.push(resolve)):rows;});
try{
await p.goto('http://localhost:8766/flows/auth-session/');await p.evaluate(async()=>window.rows=(await import('/flows/documents/document-model.mjs')).mergeDocuments([]));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#home-app');await p.evaluate(()=>location.hash='#p02/documents');await p.waitForSelector('#p12-query');
const query=async q=>{await p.fill('#p12-query',q);await p.press('#p12-query','Enter');};const shot=async name=>{await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});};
await query('Từ khóa kiểm tra dài / Unicode 📦 '.repeat(90));await shot('long-query');observations.push({case:'long-query',...await p.locator('.p12-scroll').evaluate(e=>({height:e.clientHeight,scroll:e.scrollHeight,reader:!!e.querySelector('[data-p12=read-query]'),actionTop:e.querySelector('.p16-actions').getBoundingClientRect().top,footerTop:document.querySelector('.hn-nav').getBoundingClientRect().top}))});
await query('');await p.evaluate(()=>mode='pending');await p.press('#p12-query','Enter');await p.locator('[data-p12=scan]').first().focus();await p.evaluate(()=>pending.shift()(rows));await p.waitForTimeout(80);observations.push({case:'toolbar-focus',focus:await p.evaluate(()=>({tag:document.activeElement.tagName,action:document.activeElement.dataset.p12||null}))});
await p.press('#p12-query','Enter');await p.locator('[data-p12=sort]').click();await p.evaluate(()=>pending.shift()(rows));await p.waitForTimeout(60);await p.keyboard.press('Escape');await p.waitForTimeout(120);observations.push({case:'modal-return-after-read',focus:await p.evaluate(()=>({tag:document.activeElement.tagName,action:document.activeElement.dataset.p12||null}))});
await p.press('#p12-query','Enter');await p.locator('[data-p12-doc]').first().focus();await p.evaluate(()=>pending.shift()([]));await p.waitForTimeout(80);observations.push({case:'removed-row-focus',focus:await p.evaluate(()=>document.activeElement.tagName)});
await p.evaluate(()=>mode='ready');await query('');await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=500);await p.locator('[data-p12-doc]').nth(8).dispatchEvent('click');await p.locator('[data-p12=back]').click();await p.waitForSelector('#p12-query');observations.push({case:'back-scroll',value:await p.locator('.p12-scroll').evaluate(e=>e.scrollTop)});
await query('PN-9999');await p.locator('[data-p12=filter]').first().click();await p.fill('#pick-from','01/09/2026');await p.fill('#pick-to','02/09/2026');await p.locator('.p08-picker [type=submit]').click();await p.waitForTimeout(100);observations.push({case:'filter-apply-focus',focus:await p.evaluate(()=>({tag:document.activeElement.tagName,action:document.activeElement.dataset.p12||null}))});await shot('combined');
fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify({observations,errors},null,2));console.log(JSON.stringify({observations,errors},null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
