const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path');
const phase=process.env.INBOUND_CAPTURE_PHASE||'before',base=process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8774';
const out=path.resolve('handoff/P04/evidence/revision-08',phase);fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});const metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
// Match the actual manual attempt clock visible in the before capture.
if(phase==='after')await page.addInitScript(()=>{Date.prototype.toLocaleTimeString=()=> '01:45:00';});
async function capture(panel){for(const [w,h]of [[494,1000],[390,844]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.evaluate(()=>{scrollTo(0,0);document.querySelector('.p04-scroll').scrollTop=0;});await page.locator('.hn-screen').screenshot({path:path.join(out,`${panel}-${w}x${h}.png`)});metrics.push(await page.evaluate(panel=>({panel,viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,zoom:visualViewport.scale,shell:[document.querySelector('.hn-screen').offsetWidth,document.querySelector('.hn-screen').offsetHeight]}),panel));}await page.setViewportSize({width:494,height:1000});}
try{await page.goto(base+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();await capture('S01');await page.locator('[data-p04="next"]').click();await page.locator('.p04-tools summary').click();await page.locator('[data-p04="batch"]').click();await page.locator('[data-p04="manual"]').click();await page.fill('#p04-code','NOT-A-CODE');await page.locator('#p04-code').press('Enter');await page.locator('[data-p04="close-manual"]').click();await capture('S02');await page.locator('[data-p04="next"]').click();await capture('S03');await page.locator('[data-p04="send"]').click();await page.locator('[data-panel="P04.S04"]').waitFor();await capture('S04');fs.writeFileSync(path.join(out,'metrics.json'),JSON.stringify({metrics,errors},null,2));console.log(JSON.stringify({phase,captures:metrics.length,errors}));}finally{await browser.close();}})();
