const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const out='handoff/P24/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));const shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'}),pause=()=>p.waitForTimeout(180),snap=async pre=>JSON.parse(await p.locator(`[data-${pre}-snapshot]`).textContent());
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p24-r01');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p24-tools').evaluate(e=>e.open=true);
await test('External P24 tools S01/IME/Back/cancel keeps existing list and returns focus',async()=>{await p.click('[data-p24-demo=quantity-invalid]');const before=(await snap('p19')).lines;await p.fill('#p19-quantity','2');await p.locator('#p19-quantity').dispatchEvent('compositionstart');await p.locator('.p19-sheet form').evaluate(e=>e.requestSubmit());assert.deepEqual((await snap('p19')).lines,before);await p.locator('#p19-quantity').dispatchEvent('compositionend');await p.goBack();await pause();assert.equal(await p.locator('.app-modal-host').count(),0);assert.deepEqual((await snap('p19')).lines,before);});
await test('S02 long reason and raw code readable; Back closes reader first; no horizontal overflow',async()=>{await p.click('[data-p24-demo=scan-error]');const raw=('Lý do nguồn <>&\nUnicode Đặng 🧰 '+ 'X'.repeat(120)+'\n').repeat(14);await p.locator('[data-hn-readable="Lý do mã chưa thể xuất"]').evaluate((e,raw)=>e.textContent=raw,raw);await p.waitForSelector('.p24-rejection .hn-read-more');const trigger=p.locator('.p24-rejection .hn-read-more');await trigger.click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok((await p.locator('.app-modal-host').innerText()).includes(raw));await shot('long-reader');await p.goBack();await pause();assert.equal(await p.locator('[data-panel="P24.S02"]').count(),1);assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.p19-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await p.goBack();await pause();assert.equal(await p.locator('#p19-code').count(),1);});
await test('Stale quantity submit after case closes cannot add lines or Post',async()=>{await p.click('[data-p24-demo=quantity-invalid]');const before=await snap('p19');await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.writeWarrantyCase({...m.readWarrantyCases().find(c=>c.id==='BH-001'),status:'Đã trả khách'});});await p.fill('#p19-quantity','2');await p.locator('.p19-sheet form').evaluate(e=>e.requestSubmit());assert.match(await p.locator('#p19-quantity-error').innerText(),/chỉ được xem/);assert.deepEqual((await snap('p19')).lines,before.lines);await shot('closed-stale-sheet');await p.keyboard.press('Escape');await pause();await p.evaluate(async()=>{(await import('/flows/shared/warranty-cases.mjs')).resetWarrantyCases();});});
await test('Record timeout never shows S03 until same request reconciles; busy double click one record',async()=>{await p.evaluate(()=>location.hash='#home');await p.click('.hn-task[data-route=inbound]');await p.locator('.p04-tools').evaluate(e=>e.open=true);await p.click('[data-p04=next]');await p.click('[data-p04=batch]');await p.click('[data-p04=next]');await p.selectOption('[data-p04-outcome]','timeout-recorded');await p.locator('[data-p04=send]').evaluate(e=>{e.click();e.click();});await p.waitForSelector('.p17-app');const before=await snap('p04');assert.equal(before.unknown,true);assert.equal(before.metrics.recordCalls,1);assert.equal(await p.locator('.hn-waiting-web').count(),0);await shot('record-unknown');const control=p.locator('[data-p04=check]');await control.click();await p.waitForSelector('.hn-waiting-web');assert.deepEqual((await snap('p04')).request,before.request);assert.equal((await snap('p04')).metrics.recordCalls,1);assert.equal((await snap('p04')).metrics.inventoryDelta,0);});
await test('S03 document link opens exact record; result Back retains identity, no auto new draft',async()=>{const before=await snap('p04');await p.click('[data-p04=document]');await p.waitForSelector('.p12-app');assert.match(await p.locator('.p12-app').innerText(),/PN-0005/);await p.goBack();await p.waitForSelector('.hn-waiting-web');assert.equal((await snap('p04')).document.documentId,before.document.documentId);});
await test('Logout then browser Back never restores P24 result or authenticated data',async()=>{await p.locator('#hn-logout').evaluate(e=>e.click());await p.waitForSelector('#login-form');await p.goBack();await pause();assert.equal(await p.locator('.hn-waiting-web,.p19-app,.p20-app').count(),0);assert.equal(await p.locator('#login-form').isVisible(),true);});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
