const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.LOOKUP_RECENT_EVIDENCE_DIR||'handoff/ux-upgrade-2026-09-30/p06');
const phase=process.env.LOOKUP_RECENT_PHASE||'after';fs.mkdirSync(path.join(out,phase),{recursive:true});
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],metrics=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-30T06:00:00Z'));
const panel=n=>page.locator(`[data-panel="P06.S0${n}"]`),a=n=>page.locator(`[data-p06="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p06-snapshot]').textContent());
async function ready(){await page.waitForFunction(()=>!history.state?.hnP06Picker);}
async function capture(name){await page.locator('.p06-app img').evaluateAll(es=>Promise.all(es.map(e=>e.decode().catch(()=>{}))));await page.locator('.hn-screen').screenshot({path:path.join(out,phase,name+'.png')});metrics.push({name,...await page.evaluate(()=>{const s=document.querySelector('.hn-screen').getBoundingClientRect(),scroll=document.querySelector('.p06-scroll'),d=document.querySelector('dialog[open]')?.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],pageOverflow:document.documentElement.scrollWidth>innerWidth,contentOverflow:scroll.scrollWidth>scroll.clientWidth,header:document.querySelector('.p06-header').getBoundingClientRect().top,nav:document.querySelector('.hn-nav').getBoundingClientRect().bottom,dialog:d?{inFrame:d.left>=s.left-1&&d.top>=s.top-1&&d.right<=s.right+1&&d.bottom<=s.bottom+1,footerVisible:document.querySelector('dialog[open] footer').getBoundingClientRect().bottom<=d.bottom+1}:null};})});}
async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-scanner').waitFor();await page.click('.hn-scanner');await panel(1).waitFor();}
async function check(name,run){await run();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await login();
for(const code of ['HN12345','HN12346','HN12347']){await page.locator(`.p06-list [data-p06-item="fixture-item-${code}"]`).click();await panel(2).waitFor();await a('back').click();await panel(1).waitFor();}
await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=0);await capture('recent-list-494x1000');
await page.setViewportSize({width:360,height:800});await capture('recent-list-360x800');await page.setViewportSize({width:494,height:1000});
await page.locator('.p06-list [data-p06-item="fixture-item-HN12346"]').click();await a('history').click();await panel(4).waitFor();await capture('history-default');await a('dates').click();await capture('date-picker-494x1000');await page.setViewportSize({width:360,height:800});await capture('date-picker-360x800');await page.setViewportSize({width:494,height:1000});await page.keyboard.press('Escape');await ready();
if(phase==='before'){fs.writeFileSync(path.join(out,phase,'results.json'),JSON.stringify({checks,metrics,errors},null,2));await browser.close();return;}
// Further behavior checks are below so the same entry always captures identical before/after conditions.
await check('Default history is All dates; quick ranges stay draft until Apply',async()=>{
assert.deepEqual((await snap()).filters,{type:'all',from:'',to:''});await a('dates').click();assert.equal(await page.locator('[data-quick-range]').count(),4);await page.click('[data-quick-range="7"]');assert.equal(await page.inputValue('#pick-from'),'24/09/2026');assert.equal(await page.inputValue('#pick-to'),'30/09/2026');assert.deepEqual((await snap()).filters,{type:'all',from:'',to:''});await page.locator('dialog [data-cancel]').last().click();await ready();assert.deepEqual((await snap()).filters,{type:'all',from:'',to:''});
});
await check('Apply quick range and type; Back/Escape/Reset do not commit drafts',async()=>{
await a('dates').click();await page.click('[data-quick-range="30"]');await page.locator('dialog input[value="warranty"]').check();await page.locator('dialog [type=submit]').click();await ready();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p06-snapshot]').textContent).filters.type==='warranty');const committed=(await snap()).filters;assert.deepEqual(committed,{type:'warranty',from:'2026-09-01',to:'2026-09-30'});
await a('dates').click();await page.click('[data-quick-range="90"]');assert.equal(await page.inputValue('#pick-from'),'03/07/2026');await page.goBack();await ready();assert.deepEqual((await snap()).filters,committed);assert.ok(await a('dates').evaluate(e=>e===document.activeElement));
await a('dates').click();await page.click('[data-reset]');assert.equal(await page.inputValue('#pick-from'),'30/09/2026');assert.ok(await page.locator('dialog input[value="all"]').isChecked());await page.keyboard.press('Escape');await ready();assert.deepEqual((await snap()).filters,committed);await a('clear-filters').click();
});
await check('Manual date bounds and calendar Today retain shared picker semantics',async()=>{
await a('dates').click();await page.fill('#pick-from','01/07/2026');assert.ok(await page.locator('dialog [type=submit]').isDisabled());await page.fill('#pick-from','02/07/2026');await page.fill('#pick-to','01/10/2026');assert.ok(await page.locator('dialog [type=submit]').isDisabled());await page.fill('#pick-to','30/09/2026');assert.equal(await page.locator('dialog [type=submit]').isDisabled(),false);await page.click('[data-calendar="from"]');await page.click('[data-today]');await page.click('[data-calendar-back]');assert.equal(await page.inputValue('#pick-from'),'02/07/2026');await page.keyboard.press('Escape');await ready();
});
await check('Picker constrained and keyboard focus contained across six viewports',async()=>{
for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width,height});await a('dates').click();await capture(`picker-${width}x${height}`);for(let i=0;i<14;i++)await page.keyboard.press('Tab');assert.ok(await page.locator('dialog[open]').evaluate(e=>e.contains(document.activeElement)));await page.keyboard.press('Escape');await ready();}await page.setViewportSize({width:494,height:1000});
});
await a('back').click();await a('back').click();await panel(1).waitFor();
await check('Recent max3 MRU unique with current source; normal list count unchanged',async()=>{
assert.equal(await page.locator('[data-p06-recent]').count(),3);assert.deepEqual(await page.locator('[data-p06-recent]').evaluateAll(es=>es.map(e=>e.dataset.p06Item)),['fixture-item-HN12346','fixture-item-HN12347','fixture-item-HN12345']);assert.equal(await page.locator('.p06-list>.p06-card').count(),5);await page.locator('[data-p06-recent]').first().click();await panel(2).waitFor();assert.equal((await snap()).itemId,'fixture-item-HN12346');await a('back').click();await panel(1).waitFor();assert.ok(await page.locator('[data-p06-recent]').first().evaluate(e=>e===document.activeElement));
await page.locator('.p06-list [data-p06-item="fixture-item-HN12348"]').click();await a('back').click();await panel(1).waitFor();assert.deepEqual(await page.locator('[data-p06-recent]').evaluateAll(es=>es.map(e=>e.dataset.p06Item)),['fixture-item-HN12348','fixture-item-HN12346','fixture-item-HN12347']);
});
await check('Query/category/IME keep recent controls scoped and results stable',async()=>{
await page.fill('#p06-search','HN12346');assert.equal(await page.locator('[data-p06-recent]').count(),0);await page.locator('#p06-search').dispatchEvent('keydown',{key:'Enter',isComposing:true});assert.equal((await snap()).panel,1);await a('clear').click();assert.equal(await page.locator('[data-p06-recent]').count(),3);await page.click('[data-p06-category="components"]');assert.equal(await page.locator('[data-p06-recent]').count(),0);await page.locator('.p06-list [data-p06-item="fixture-component-01"]').click();await a('back').click();assert.equal(await page.locator('[data-p06-recent]').count(),1);await page.click('[data-p06-category="products"]');assert.equal(await page.locator('[data-p06-recent]').count(),3);
});
await check('Unavailable source hides recent entries; stale catalogue cannot open',async()=>{
await page.locator('.p06-tools summary').click();await page.selectOption('[data-p06-scenario]','read-error');assert.equal(await page.locator('[data-p06-recent]').count(),0);await page.locator('.p06-list [data-p06-item]').first().click();assert.equal((await snap()).panel,1);await page.locator('[data-action-dialog="confirm"]').click();await page.waitForFunction(()=>!document.querySelector('dialog[open]'));await a('retry-read').click();assert.equal(await page.locator('[data-p06-recent]').count(),3);
});
await check('Recent internal scrolling preserves shell header and footer',async()=>{
for(const [width,height]of [[494,1000],[360,800],[340,420]]){await page.setViewportSize({width,height});await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=0);const before=await page.locator('.hn-nav').boundingBox();await page.locator('.p06-scroll').hover();await page.mouse.wheel(0,900);await page.waitForTimeout(250);assert.deepEqual(await page.locator('.hn-nav').boundingBox(),before);await capture(`recent-bottom-${width}x${height}`);}await page.setViewportSize({width:494,height:1000});
});
await check('Logout clears recents; new login and Back cannot expose old list',async()=>{
await page.locator('.hn-nav [data-route="profile"]').click();await page.click('[data-p10="logout"]');await page.click('[data-p10="dialog-confirm"]');await page.locator('#login-form').waitFor();await page.goBack();assert.equal(await page.locator('.p06-app').count(),0);await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-scanner').waitFor();await page.click('.hn-scanner');await panel(1).waitFor();assert.equal(await page.locator('[data-p06-recent]').count(),0);
});
await check('NFC picker opens the same recent exact ID and returns without navigating to product detail',async()=>{
await page.locator('.p06-list [data-p06-item="fixture-item-HN12346"]').click();await panel(2).waitFor();await page.locator('.hn-nav [data-tab="home"]').click();await page.click('[data-route="nfc"]');await page.click('[data-p07="begin"]');await page.click('[data-p07="product"]');await panel(1).waitFor();await a('clear').click();assert.equal(await page.locator('[data-p06-recent]').count(),1);await page.locator('[data-p06-recent][data-p06-item="fixture-item-HN12346"]').click();await page.locator('[data-panel="P07.S02"]').waitFor();const nfc=JSON.parse(await page.locator('[data-p07-snapshot]').textContent());assert.equal(nfc.itemId,'fixture-item-HN12346');assert.match(await page.locator('.p07-product').textContent(),/SN-XP420B-BK-0008/);
});
assert.deepEqual(errors,[]);for(const m of metrics){assert.equal(m.pageOverflow,false);assert.equal(m.contentOverflow,false);if(m.dialog){assert.equal(m.dialog.inFrame,true);assert.equal(m.dialog.footerVisible,true);}}
fs.writeFileSync(path.join(out,phase,'results.json'),JSON.stringify({checks,metrics,errors,fixtureOnly:true},null,2));
}catch(e){await page.screenshot({path:path.join(out,phase,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,phase,'failure.json'),JSON.stringify({checks,metrics,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
