const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.UX_TOUCH_EDGE_OUT||'handoff/ux-upgrade-2026-09-30/touch/edges');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch();const p=await browser.newPage({viewport:{width:360,height:800},deviceScaleFactor:1});p.setDefaultTimeout(20000);const checks=[],errors=[],geometry=[];p.on('pageerror',e=>errors.push(e.message));
const settle=()=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function route(hash,selector){await p.evaluate(h=>location.hash=h,hash);await p.locator(selector).waitFor();await settle();}
async function points(name){await settle();const result=await p.evaluate(()=>[...document.querySelectorAll('[data-hn-touch-layout]')].filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&!n.closest('[hidden],[inert]')&&r.top>=0&&r.bottom<=innerHeight;}).map(n=>{const r=n.getBoundingClientRect(),points=[.25,.5,.75].flatMap(x=>[.25,.5,.75].map(y=>{const el=document.elementFromPoint(r.x+r.width*x,r.y+r.height*y);return {x,y,ok:n===el||n.contains(el),hit:el?.outerHTML.slice(0,120)};}));return {id:n.id||n.getAttribute('aria-label')||n.textContent.trim().slice(0,25),r:r.toJSON(),points};}));geometry.push({name,result});assert.ok(result.length>0,'No measured targets: '+name);assert.ok(result.every(r=>r.r.width>=43.8&&r.r.height>=43.8),JSON.stringify(result));assert.ok(result.every(r=>r.points.every(p=>p.ok)),JSON.stringify(result));}
async function check(name,fn){try{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){checks.push({name,status:'FAIL',error:e.stack});console.log('FAIL '+name+': '+e.message);await p.screenshot({path:path.join(out,`failure-${checks.length}.png`),fullPage:true});}}
try{
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.locator('#username').waitFor();
await check('P01 password eye actual target and raw preservation',async()=>{await p.fill('#password','  sample <&>  ');await points('login');await p.click('#toggle-password');assert.equal(await p.inputValue('#password'),'  sample <&>  ');assert.equal(await p.getAttribute('#password','type'),'text');});
await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.locator('#start').waitFor();await p.click('#start');await p.locator('.hn-nav').waitFor();
await check('Home compact targets hit correctly and locked nav stays independent',async()=>{await p.setViewportSize({width:340,height:420});await points('home');assert.equal(await p.locator('.hn-nav [data-hn-touch-layout]').count(),0);await p.screenshot({path:path.join(out,'home-compact.png')});});
await check('P03 picker close and discard dialog actions fit at compact viewport',async()=>{for(const mode of ['picker','discard']){await p.locator(`[data-p03-open="${mode}"]`).evaluate(b=>b.click());await p.locator('.p03-dialog').waitFor();await p.evaluate(()=>scrollTo(0,0));await points('P03-'+mode);if(mode==='picker')assert.equal(await p.evaluate(()=>{const a=document.querySelector('.p03-close').getBoundingClientRect(),b=document.querySelector('.p03-operation').getBoundingClientRect();return a.bottom>b.top+1;}),false);await p.locator('.hn-screen').screenshot({path:path.join(out,`P03-${mode}.png`)});await p.keyboard.press('Escape');if(mode==='discard'){await p.locator('[data-panel="P03.S02"]').waitFor();await p.keyboard.press('Escape');}await p.locator('.p03-dialog').waitFor({state:'detached'});}});
await check('P04/P05 Back is not covered by the first content card',async()=>{for(const key of ['inbound','outbound']){await route('#p02/'+key, key==='inbound'?'.p04-app':'.p05-app');await points(key);await p.locator(key==='inbound'?'[data-p04="back"]':'[data-p05="back"]').click();await p.locator('#hn-home:visible').waitFor();}});
await check('P06 clear, focus, Escape and dialog targets',async()=>{await route('#p02/lookup','.p06-app');await p.fill('#p06-search','HN12345');await points('P06 search');await p.click('[data-p06="clear"]');assert.equal(await p.inputValue('#p06-search'),'');await p.click('[data-p06="filter"]');await p.locator('dialog[open]').waitFor();await points('P06 dialog');await p.keyboard.press('Escape');await p.locator('dialog[open]').waitFor({state:'detached'});});
await check('P07 detail copy/close targets and native Back returns to same query',async()=>{await route('#p02/nfc','.p07-app');await p.fill('#p07-search','NFC');await p.locator('[data-p07-tag]').first().click();await p.locator('dialog[open]').waitFor();await points('P07 detail');await p.locator('.hn-screen').screenshot({path:path.join(out,'P07-detail.png')});await p.goBack();await p.locator('dialog[open]').waitFor({state:'detached'});assert.equal(await p.inputValue('#p07-search'),'NFC');});
await check('P08 record copy and filter controls stay clickable',async()=>{await route('#p02/history-list','.p08-app');await points('P08 list');await p.locator('[data-p08-record]').first().click();await p.locator('[data-p08="copy"]').waitFor();await points('P08 detail');});
await check('P11 password eye geometry and value does not normalize',async()=>{await route('#p02/security?panel=1','.p11-app');await p.fill('#p11-current',' A b <&> ');await p.locator('.p11-scroll').evaluate(e=>e.scrollTop=0);await points('P11 password');await p.click('[data-p11-eye="current"]');assert.equal(await p.inputValue('#p11-current'),' A b <&> ');});
await check('P10 existing controller is not double mounted; later boards opt out',async()=>{await p.fill('#p11-current','');await route('#p02/profile','.p10-app');assert.equal(await p.locator('[data-hn-touch-layout]').count(),0);await route('#p02/documents','.p12-app');assert.equal(await p.locator('[data-hn-touch-layout]').count(),0);});
assert.deepEqual(errors,[]);
}catch(e){checks.push({name:'runner',status:'FAIL',error:e.stack});}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,geometry,errors},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();if(checks.some(r=>r.status==='FAIL'))process.exitCode=1;}})();
