const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');const out=process.env.P14_LOGOUT_DIR||'handoff/P14/evidence/revision-05';fs.mkdirSync(path.join(out,'after'),{recursive:true});
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);const a=k=>p.locator(`[data-p14="${k}"]`).first(),modal=()=>p.locator('.app-modal-host dialog');
const check=async(name,f)=>{await f();checks.push({name,status:'PASS'});console.log('PASS '+name);};
async function login(){await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home').waitFor({state:'visible'});}
async function shift(){await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await p.locator('.p14-app').waitFor();}
async function finish(){await a('save').click();await modal().getByRole('button',{name:'Lưu nháp',exact:true}).click();await modal().getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await a('end').click();await modal().getByRole('button',{name:'Kết thúc ca',exact:true}).click();await p.locator('[data-panel="P14.S04"]').waitFor();}
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,'after',n+'.png')});}
try{await p.goto('http://localhost:8766/flows/auth-session/');await login();await p.click('[data-tab=profile]');assert.deepEqual(await p.locator('[data-p10=logout]').evaluate(e=>{const s=getComputedStyle(e);return [s.color,s.backgroundColor,s.fontSize,e.offsetHeight];}),['rgb(255, 255, 255)','rgb(180, 35, 24)','19px',56]);await shift();const id=await p.locator('[data-document]').getAttribute('data-document');await a('continue').click();await p.locator('[data-p04-note]').waitFor();await p.fill('[data-p04-note]','Nháp trước khi đăng xuất — giữ nguyên 🌸');await p.goBack();await p.locator('[data-panel="P14.S03"]').waitFor();await finish();
await check('Summary replaces Home CTA with History + existing P10 logout; six viewports',async()=>{assert.equal(await p.locator('[data-p14=home]').count(),0);assert.equal(await p.locator('.p14-summary-actions .hn-logout-button').count(),1);for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.waitForTimeout(60);const m=await p.locator('.p14-app').evaluate(app=>{const buttons=[...app.querySelectorAll('.p14-summary-actions button')],screen=app.closest('.hn-screen'),scroll=app.querySelector('.p14-scroll'),r=e=>e.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],labels:buttons.map(e=>e.textContent.trim()),heights:buttons.map(e=>e.offsetHeight),within:r(buttons[1]).bottom<=r(screen.querySelector('.hn-nav')).top,widths:buttons.map(e=>e.offsetWidth),background:getComputedStyle(buttons[1]).backgroundColor,noOverflow:scroll.clientWidth===scroll.scrollWidth};});assert.deepEqual(m.labels,['Xem lịch sử','Đăng xuất']);assert.deepEqual(m.heights,[56,56]);assert.deepEqual(m.widths,[446,446]);assert.equal(m.background,'rgb(180, 35, 24)');assert.ok(m.within&&m.noOverflow);metrics.push(m);await shot(`summary-${width}x${height}`);}await p.setViewportSize({width:494,height:950});});
await check('History opens existing P08; nested Back and return preserve summary, count, scroll, focus',async()=>{await p.locator('.p14-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const top=await p.locator('.p14-scroll').evaluate(e=>e.scrollTop);await a('history').click();await p.locator('[data-panel="P08.S01"]').waitFor();await p.locator('[data-p08-record]').first().click();await p.locator('[data-panel="P08.S02"]').waitFor();await p.click('[data-p08=back]');await p.locator('[data-panel="P08.S01"]').waitFor();await p.click('[data-p08=back]');await p.locator('[data-panel="P14.S04"]').waitFor();await p.waitForFunction(y=>document.querySelector('.p14-scroll').scrollTop===y,top);assert.ok(await a('history').evaluate(e=>e===document.activeElement));assert.equal(await p.locator('.p14-drafts strong').textContent(),'1');});
await check('Logout confirms once; Cancel/Back/Escape/backdrop preserve summary and focus',async()=>{for(const how of ['cancel','back','escape']){await a('logout').click();await modal().waitFor();assert.match(await modal().textContent(),/Ca làm việc đã kết thúc/);assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Tab');assert.ok(await modal().evaluate(e=>e.contains(document.activeElement)));await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await modal().count(),1);await shot('logout-confirm');if(how==='cancel')await modal().getByRole('button',{name:'Hủy',exact:true}).click();else if(how==='back')await p.goBack();else await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-panel="P14.S04"]').count(),1);assert.ok(await a('logout').evaluate(e=>e===document.activeElement));}});
await check('Confirmed logout reaches login; Back cannot revive protected session or late P14 handlers',async()=>{await a('logout').click();await modal().getByRole('button',{name:'Đăng xuất',exact:true}).click();await p.locator('#username').waitFor();assert.equal(await p.locator('.p14-app').count(),0);await p.goBack();await p.locator('#username').waitFor();assert.equal(await p.locator('.p14-app,.app-modal-host').count(),0);});
await check('Same-account login restores exact draft ID and note into owner',async()=>{await login();await shift();await p.locator('[data-panel="P14.S03"]').waitFor();assert.equal(await p.locator('[data-document]').getAttribute('data-document'),id);await a('continue').click();await p.locator('[data-p04-note]').waitFor();assert.equal(await p.inputValue('[data-p04-note]'),'Nháp trước khi đăng xuất — giữ nguyên 🌸');await p.goBack();await p.locator('[data-panel="P14.S03"]').waitFor();});
await check('Reload deliberately resets prototype retained data and requires login',async()=>{await p.reload();await p.locator('#username').waitFor();await login();await shift();await a('continue').click();await p.locator('[data-p04-note]').waitFor();assert.equal(await p.inputValue('[data-p04-note]'),'');});
await p.route('**/recovery-shift/draft-retention.mjs',async route=>{const r=await route.fetch();const body=(await r.text()).replace("const scope=key(s);if(!scope)return {kind:'blocked'};", "const scope=key(s);return {kind:'blocked'};");await route.fulfill({response:r,body});});
await check('Retention failure keeps session and summary; does not claim logout success',async()=>{await p.reload();await p.locator('#username').waitFor();await login();await shift();await finish();await a('logout').click();await modal().getByRole('button',{name:'Đăng xuất',exact:true}).click();await modal().getByRole('button',{name:'Đóng',exact:true}).waitFor();assert.match(await modal().textContent(),/Chưa thể đăng xuất/);assert.equal(await p.locator('[data-panel="P14.S04"]').count(),1);assert.equal(await p.locator('#username:visible').count(),0);await shot('retention-blocked');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'logout-results.json'),JSON.stringify({status:'PASS',checks,metrics,errors},null,2));console.log('TOTAL '+checks.length);
}catch(e){await p.screenshot({path:path.join(out,'logout-failure.png')});fs.writeFileSync(path.join(out,'logout-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
