const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.NOTIFICATION_PAGES_EVIDENCE_DIR||'handoff/P13/evidence/revision-03';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[],metrics=[];p.on('pageerror',e=>errors.push(e.message));
const rows=()=>p.locator('.p13-notification'),more=()=>p.locator('[data-p13=more]'),scroller=()=>p.locator('.p13-scroll'),dialog=()=>p.locator('.app-modal-host dialog');
const count=async n=>p.waitForFunction(n=>document.querySelectorAll('.p13-notification').length===n,n);
const ready=()=>p.locator('[data-p13-loaded=true][aria-busy=false]').waitFor();
const calls=async()=>parseInt(await p.locator('#p13-page-calls').textContent());
async function shot(name){await p.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function dataset(v){await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset',v);await ready();await p.evaluate(()=>scrollTo(0,0));}
async function filter(v){await p.click(`[data-p13-filter=${v}]`);await ready();}
async function mode(v){await p.selectOption('#p13-scenario',v);await p.evaluate(()=>scrollTo(0,0));}
try{
await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await ready();
await check('Short datasets show actual 3/5 and no dead load-more button',async()=>{await count(3);assert.equal(await more().count(),0);await shot('after-unread-494x950');await filter('all');await count(5);assert.equal(await more().count(),0);await scroller().evaluate(e=>e.scrollTop=0);await shot('after-all-494x950');await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);await shot('short-end');});
await check('Both filters load only10; source unread24 does not become visible-count10; no auto-load',async()=>{await dataset('extended');await count(10);const before=await calls();await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);await p.waitForTimeout(300);assert.equal(await calls(),before);assert.equal(await rows().count(),10);assert.equal(await more().textContent(),'Xem thêm');assert.equal(await more().getAttribute('aria-label'),'Tải thêm 10 thông báo');await shot('all-first10-bottom');await filter('unread');await count(10);assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),'Chưa đọc (24)');assert.ok((await p.locator('.p13-page-control').textContent()).includes('10 / 24'));await shot('unread-first10');});
await check('Rapid repeated load sends one page; rows append without scroll jump and focus first added',async()=>{await filter('all');await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);const top=await scroller().evaluate(e=>e.scrollTop),firstIds=await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event)),before=await calls();await more().focus();await more().evaluate(e=>{e.click();e.click();});assert.ok(await more().isDisabled());await shot('loading-more');await count(20);assert.equal(await calls(),before+1);assert.equal(await scroller().evaluate(e=>e.scrollTop),top);assert.deepEqual((await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event))).slice(0,10),firstIds);assert.equal(await p.locator('[data-p13-event]').nth(10).evaluate(e=>e===document.activeElement),true);await shot('after-append20');});
await check('Each tab preserves loaded pages and scroll; detail Back preserves count/context',async()=>{const allTop=await scroller().evaluate(e=>e.scrollTop),before=await calls();await filter('unread');assert.equal(await rows().count(),10);await scroller().evaluate(e=>e.scrollTop=220);await filter('all');assert.equal(await rows().count(),20);assert.equal(await scroller().evaluate(e=>e.scrollTop),allTop);assert.equal(await calls(),before);await p.locator('[data-p13-event]').nth(12).dispatchEvent('click');await p.locator('[data-panel="P13.S02"]').waitFor();await p.click('[data-p13=back]');await ready();await count(20);assert.equal(await scroller().evaluate(e=>e.scrollTop),allTop);await filter('unread');assert.equal(await scroller().evaluate(e=>e.scrollTop),220);});
await check('Load-more failure retains20 rows/cursor/scroll; dialog, retry same page then end37',async()=>{await filter('all');await mode('page-error');await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);const ids=await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event)),top=await scroller().evaluate(e=>e.scrollTop);await more().click();await dialog().waitFor();assert.deepEqual(await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event)),ids);assert.equal(await scroller().evaluate(e=>e.scrollTop),top);await shot('page-error-dialog');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await more().textContent(),'Thử tải thêm');await mode('ready');await more().click();await count(30);await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);assert.equal(await more().textContent(),'Xem thêm');assert.equal(await more().getAttribute('aria-label'),'Tải thêm 7 thông báo');await more().click();await count(37);assert.equal(await more().count(),0);assert.equal(new Set(await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event))).size,37);await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);await shot('all-end37');});
await check('Reading an unread row removes only that row; next explicit page does not skip',async()=>{await dataset('extended');await filter('unread');await count(10);const ids=await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event)),before=await calls();await p.locator('[data-p13-event]').last().dispatchEvent('click');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));await p.click('[data-p13=back]');await ready();await count(9);assert.equal(await calls(),before);await more().click();await count(19);const after=await p.locator('[data-p13-event]').evaluateAll(es=>es.map(e=>e.dataset.p13Event));assert.equal(new Set(after).size,19);assert.deepEqual(after.slice(0,9),ids.slice(0,9));await more().click();await count(23);assert.equal(await more().count(),0);assert.ok((await p.locator('.p13-page-control').textContent()).includes('Đã tải đủ 23 thông báo'));});
await check('Load result after tab switch never appends into the other filter',async()=>{await dataset('extended');await filter('all');await more().evaluate(e=>e.click());await p.locator('[data-p13-filter=unread]').evaluate(e=>e.click());await ready();await count(10);assert.equal(await p.locator('[data-p13-filter=unread]').getAttribute('aria-pressed'),'true');await filter('all');await count(20);});
await check('Load-more is reachable above footer and controls do not overflow at six sizes',async()=>{for(const [width,height]of [[494,950],[360,800],[430,932],[459,874],[1440,900],[340,420]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await scroller().evaluate(e=>e.scrollTop=e.scrollHeight);const m=await p.evaluate(()=>{const s=document.querySelector('.p13-scroll'),r=document.querySelector('[data-p13=more]').getBoundingClientRect(),nav=document.querySelector('.hn-nav').getBoundingClientRect(),dock=document.querySelector('.p13-filter-dock').getBoundingClientRect();return {viewport:[innerWidth,innerHeight],width:s.clientWidth,scrollWidth:s.scrollWidth,moreBottom:r.bottom,navTop:nav.top,dockTop:dock.top,moreTop:r.top};});assert.equal(m.width,m.scrollWidth);assert.ok(m.moreBottom<m.navTop);assert.ok(m.moreTop>m.dockTop);metrics.push(m);await shot(`load-more-${width}x${height}`);}await p.setViewportSize({width:494,height:950});});
await check('Logout with pending page cannot repopulate UI after Back',async()=>{await more().evaluate(e=>e.click());await p.locator('.hn-tools details').first().evaluate(e=>e.open=true);await p.click('#hn-logout');await p.locator('#username').waitFor();await p.goBack();await p.waitForTimeout(250);assert.equal(await rows().count(),0);assert.equal(await p.locator('.p13-app').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'pagination-browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'pagination-browser-failure.json'),JSON.stringify({message:e.message,checks,errors},null,2));await shot('pagination-failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
