const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const before=process.env.INBOUND_AUDIT_BEFORE==='1',base=process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8774';
const out=path.resolve(process.env.INBOUND_UI_AUDIT_DIR||('handoff/P04/evidence/revision-09/'+(before?'before':'after')));fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const a=n=>page.locator(`[data-p04="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
async function check(name,fn){try{await fn();checks.push({name,status:'PASS'});}catch(e){checks.push({name,status:'FAIL',error:e.message});await page.screenshot({path:path.join(out,'failure-'+checks.length+'.png'),fullPage:true});if(!before)throw e;}}
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function shot(n){await settle();await page.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function visibleInScroll(selector){return page.locator(selector).evaluate(e=>{const r=e.getBoundingClientRect(),b=document.querySelector('.p04-scroll').getBoundingClientRect();return r.top>=b.top-1&&r.bottom<=b.bottom+1;});}
try{
await page.goto(base+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();await a('next').click();await page.locator('.p04-tools summary').click();await a('batch').click();await a('all').click();
await check('Back from review restores scan position and expanded list',async()=>{await page.locator('.p04-scroll').evaluate(e=>e.scrollTop=440);const old=await page.locator('.p04-scroll').evaluate(e=>e.scrollTop);const original=await snap();await a('next').click();await a('back').click();await settle();const current=await page.locator('.p04-scroll').evaluate(e=>e.scrollTop);await shot('01-back-scroll');assert.ok(Math.abs(current-old)<2,`scroll ${old} -> ${current}`);assert.equal(await page.locator('.p04-attempt').count(),12);assert.deepEqual((await snap()).accepted,original.accepted);});
await check('Filtering immediately reveals a matching row without another scroll',async()=>{await page.locator('[data-p04-filter="duplicate"]').click();await settle();await shot('02-filter');assert.equal(await page.locator('.p04-attempt').count(),1);assert.ok(await visibleInScroll('.p04-attempt'),'matching row is below scroll viewport');});
await check('Manual filter rerender preserves unsent raw input',async()=>{await a('manual').click();await page.fill('#p04-code','HN12346');await page.locator('[data-p04-filter="valid"]').click();assert.equal(await page.locator('#p04-code').inputValue(),'HN12346');await a('close-manual').click();});
await a('next').click();for(const sku of ['XP-420B','ZD421','DS2208'])await page.locator(`[data-p04-sku="${sku}"]`).click();
await check('Collapsing an expanded SKU keeps its trigger visible and focused',async()=>{await page.locator('.p04-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await page.locator('[data-p04-sku="XP-420B"]').click();await settle();await shot('03-collapse');assert.ok(await visibleInScroll('[data-p04-sku="XP-420B"]'));assert.equal(await page.locator('[data-p04-sku="XP-420B"]').evaluate(e=>e===document.activeElement),true);});
await check('SKU disclosure retains all eleven accepted codes',async()=>{const state=await snap();assert.equal(state.accepted.length,11);assert.equal(await page.locator('.p04-serials li').count(),11);});
await shot('04-review');
if(!before){
await check('P17 invalid-code round trip preserves raw input, accepted rows, filter and scroll',async()=>{
 await a('back').click();await a('manual').click();await page.fill('#p04-code','BAD-CODE');const original=await snap();
 await page.locator('.p04-scroll').evaluate(e=>e.scrollTop=120);const y=await page.locator('.p04-scroll').evaluate(e=>e.scrollTop);
 await page.locator('#p04-code').evaluate(e=>e.form.requestSubmit());await page.locator('[data-panel="P17.S01"]').waitFor();await a('exception-manual').click();
 assert.equal(await page.locator('#p04-code').inputValue(),'BAD-CODE');assert.equal(await page.locator('#p04-code').evaluate(e=>e===document.activeElement),true);assert.deepEqual((await snap()).accepted,original.accepted);assert.equal(await page.locator('[data-p04-filter="valid"]').getAttribute('aria-pressed'),'true');assert.ok(Math.abs(await page.locator('.p04-scroll').evaluate(e=>e.scrollTop)-y)<2);
});
await check('P17 UNKNOWN blocks new-run and preserves exact request until reconciliation',async()=>{
 await a('next').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await a('send').click();await page.locator('[data-panel="P17.S04"]').waitFor();const pending=await snap();assert.equal(await a('new-run').count(),0);await a('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.deepEqual((await snap()).request,pending.request);assert.equal((await snap()).metrics.recordCalls,pending.metrics.recordCalls);await a('new-run').click();assert.equal((await snap()).step,1);assert.equal((await snap()).accepted.length,0);assert.equal(await page.locator('.p04-scroll').evaluate(e=>e.scrollTop),0);
});
}
// A separate isolated supplier response exercises the presentation contract.
const long=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});long.on('pageerror',e=>errors.push(e.message));const fullName='Nhà cung cấp rất dài '.repeat(110)+'<giữ nguyên>🌿';
await long.route('**/inbound/catalogue.mjs',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace("'Công ty Minh Phát'",JSON.stringify(fullName)),contentType:'text/javascript'});});
if(!before)await long.route('**/inbound/fixture-adapter.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('serial: serials[index]','serial: serials[index]+"X".repeat(2100)'),contentType:'text/javascript'});});
await long.goto(base+'/flows/auth-session/');await long.fill('#username','minhanh');await long.fill('#password','preview');await long.click('#submit');await long.click('#start');await long.locator('.hn-task[data-route="inbound"]').click();
await check('Long selected supplier stays compact in form with a full reader outside trigger',async()=>{const trigger=long.locator('[data-p04-select="supplier"]');const h=await trigger.evaluate(e=>e.offsetHeight);await long.locator('.hn-screen').screenshot({path:path.join(out,'05-long-selected.png')});assert.ok(h<110,`selected supplier height=${h}`);const field=trigger.locator('..');assert.equal(await trigger.locator('button').count(),0);await field.locator('[data-hn-read-trigger]').click();const modal=long.locator('.hn-action-dialog[open]');await modal.waitFor();assert.equal(await modal.locator('.app-modal-body p').textContent(),fullName);await long.keyboard.press('Escape');await modal.waitFor({state:'detached'});});
await long.locator('[data-p04="next"]').click();await long.locator('.p04-tools summary').click();await long.locator('[data-p04="batch"]').click();await long.locator('[data-p04="next"]').click();
await check('Long supplier in review is compact with full-text reader, not an enormous row',async()=>{const row=long.locator('.p04-review-summary .p04-summary-row').filter({hasText:'Nhà cung cấp'});const height=await row.evaluate(e=>e.offsetHeight);await long.locator('.hn-screen').screenshot({path:path.join(out,'05-long-supplier.png')});assert.ok(height<170,`supplier row height=${height}`);await row.locator('[data-hn-read-trigger]').click();const dialog=long.locator('.hn-action-dialog[open]');await dialog.waitFor();assert.equal(await dialog.locator('.app-modal-body p').textContent(),fullName);await long.goBack();await dialog.waitFor({state:'detached'});});
if(!before){
await check('Long serial has a separate reader, intact quantity and no row overflow',async()=>{await long.locator('[data-p04-sku="XP-420B"]').click();const row=long.locator('.p04-serials li:visible').first();await row.locator('[data-hn-read-trigger]').waitFor();const r=await row.boundingBox(),b=await row.locator('[data-hn-read-trigger]').boundingBox(),q=await row.locator('small').boundingBox();assert.ok(b.x+b.width<=r.x+r.width+1);assert.ok(q.x+q.width<=r.x+r.width+1);await row.locator('[data-hn-read-trigger]').click();const dialog=long.locator('.hn-action-dialog[open]');await dialog.waitFor();assert.equal(await dialog.locator('.app-modal-body p').textContent(),'HN12345'+'X'.repeat(2100));await long.keyboard.press('Escape');await dialog.waitFor({state:'detached'});});
await check('Long result metadata stays compact and full reader works at six viewports',async()=>{await long.locator('[data-p04="send"]').click();await long.locator('[data-panel="P04.S04"]').waitFor();for(const [width,height]of [[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]]){await long.setViewportSize({width,height});await long.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const row=long.locator('.p04-result-summary .p04-summary-row').filter({hasText:'Nhà cung cấp'});assert.ok(await row.evaluate(e=>e.offsetHeight)<170);await row.locator('[data-hn-read-trigger]').click();const dialog=long.locator('.hn-action-dialog[open]');await dialog.waitFor();assert.equal(await dialog.locator('.app-modal-body p').textContent(),fullName);const fits=await dialog.evaluate(d=>{const r=d.getBoundingClientRect(),f=d.querySelector('footer').getBoundingClientRect(),s=document.querySelector('.hn-screen').getBoundingClientRect();return r.left>=s.left-1&&r.right<=s.right+1&&r.bottom<=s.bottom+1&&f.bottom<=r.bottom+1;});assert.ok(fits);await long.keyboard.press('Escape');await dialog.waitFor({state:'detached'});await long.locator('.hn-screen').screenshot({path:path.join(out,`06-result-${width}x${height}.png`)});}});
}
await long.close();
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));
}catch(e){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
