const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out=path.resolve(process.env.M11_OUT||`handoff/motion/M11/${before?'before':'evidence'}`);fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/security/security.mjs','docs/flows/security/security-model.mjs','docs/flows/security/preview-adapter.mjs','docs/flows/security/style.css','docs/flows/security/motion.mjs','docs/flows/home/home.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
const original='handoff/motion/M11/before/source';
const inputFile=f=>before&&fs.existsSync(path.join(original,f))?path.join(original,f):f;
const inputFiles=files.filter(f=>fs.existsSync(inputFile(f))&&(!before||f!=='docs/flows/security/motion.mjs'));
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(inputFiles.map(file=>({file,bytes:fs.statSync(inputFile(file)).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(inputFile(file))).digest('hex')})),null,2));
if(before)for(const f of inputFiles){const dest=path.join(out,'source',f);fs.mkdirSync(path.dirname(dest),{recursive:true});if(!fs.existsSync(dest))fs.copyFileSync(inputFile(f),dest);}
(async()=>{const browser=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
const c=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.setDefaultTimeout(18000);p.on('pageerror',e=>r.errors.push(e.message));
await p.clock.setFixedTime(new Date('2026-10-01T06:00:00Z'));
if(before)for(const f of ['docs/flows/security/security.mjs','docs/flows/home/home.mjs'])await p.route('**/'+f.replace('docs/','')+'*',route=>route.fulfill({status:200,contentType:'text/javascript',body:fs.readFileSync(path.join(original,f),'utf8')}));
await p.addInitScript(()=>{
 window.qaCalls={password:0,revoke:0,list:0,reconcile:0};window.qaResults=[];window.qaEffects=[];window.qaFrames=[];window.qaHolds={};window.qaRelease={};window.qaVisibility=0;window.qaHardware=0;
 const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVisibility++;return add.call(this,t,f,o);};
 EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVisibility--;return remove.call(this,t,f,o);};
 const native=Element.prototype.animate;Element.prototype.animate=function(frames,opts){const a=native.call(this,frames,opts),primitive=this.dataset.motionPrimitive;if(!primitive?.startsWith('Secure')&&!primitive?.startsWith('SecuritySettings'))return a;const record={primitive,duration:opts.duration,frames,cancelled:false};qaEffects.push(record);const cancel=a.cancel.bind(a);a.cancel=()=>{record.cancelled=true;cancel();};const start=performance.now(),node=this;function sample(){qaFrames.push({primitive,elapsed:performance.now()-start,opacity:getComputedStyle(node).opacity,connected:node.isConnected});if(node.isConnected&&performance.now()-start<180)requestAnimationFrame(sample);}requestAnimationFrame(sample);return a;};
 if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('Hardware disabled in test');};
});
await p.route('**/security/preview-adapter.mjs',async route=>{const response=await route.fetch();let body=await response.text();body=body.replace('export function createSecurityAdapter(','function createSecurityAdapter(');body+=`\nconst originalSecurityFactory=createSecurityAdapter;export {instrumentedSecurityFactory as createSecurityAdapter};function instrumentedSecurityFactory(options){const adapter=originalSecurityFactory(options);for(const [method,key] of [['changePassword','password'],['revokeSession','revoke'],['listSessions','list'],['reconcile','reconcile']]){const fn=adapter[method];adapter[method]=async(...args)=>{window.qaCalls[key]++;if(window.qaHolds[key])await new Promise(resolve=>window.qaRelease[key]=resolve);const result=await fn(...args);window.qaResults.push({action:key,kind:result.kind});return result;};}return adapter;}\n`;await route.fulfill({response,body});});
const settle=async()=>{await p.waitForTimeout(250);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(r)));};
const act=k=>p.locator(`[data-p11="${k}"]`).first();
const scenario=async value=>{await p.locator('.p11-tools details').evaluate(e=>e.open=true);await p.selectOption('#p11-scenario',value);await p.waitForFunction(()=>document.querySelector('.p11-app')?.getAttribute('aria-busy')==='false');};
const goto=async panel=>{await p.evaluate(n=>location.hash='#p02/security?panel='+n,panel);await p.locator(`[data-panel="P11.S0${panel}"]`).waitFor();};
const fill=async mismatch=>{await p.fill('#p11-current','preview');await p.fill('#p11-next','fixture-motion-next');await p.fill('#p11-confirm',mismatch?'fixture-mismatch':'fixture-motion-next');};
const acknowledge=async()=>{await p.locator('.p11-dialog [data-p11=confirm]').click();await p.waitForFunction(()=>!history.state?.hnSecurityDialog&&!document.querySelector('.p11-dialog'));};
const check=async(name,fn)=>{await fn();r.checks.push({name,status:'PASS'});console.log(mode+' PASS '+name);};
const shot=async panel=>{await settle();await p.evaluate(()=>{document.activeElement.blur();scrollTo(0,0);});r.geometry[panel]=await p.locator('.p11-app').evaluate(app=>{const nodes=['.p11-header','.p11-scroll','.p11-footer','.p11-success-mark','.p11-summary','.p11-device'],scale=app.closest('.hn-screen').getBoundingClientRect().width/494;return{panel:app.dataset.panel,frame:[app.closest('.hn-screen').offsetWidth,app.closest('.hn-screen').offsetHeight],nodes:nodes.flatMap(s=>[...app.querySelectorAll(s)].map(n=>({selector:s,box:[n.getBoundingClientRect().width/scale,n.getBoundingClientRect().height/scale],count:n.querySelectorAll('*').length}))),text:app.innerText,rows:[...app.querySelectorAll('[data-session-row]')].map(n=>n.dataset.sessionRow)};});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+panel+'.png'),mask:[p.locator('.p11-input input')]});};
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.click('[data-tab=profile]');await p.click('[data-p10=security]');await p.click('[data-p10=password]');await scenario('baseline');await shot('P11.S01');
await fill(true);await p.click('[data-p11-save]');await p.locator('[data-panel="P11.S02"]').waitFor();await shot('P11.S02');assert.equal(await p.evaluate(()=>qaCalls.password),0);
await p.fill('#p11-confirm','fixture-motion-next');await p.evaluate(()=>qaHolds.password=true);await p.click('[data-p11-save]');await p.waitForFunction(()=>qaCalls.password===1);
// Never trace fill/value/visibility calls or DOM snapshots containing secrets.
if(!before)await c.tracing.start({screenshots:false,snapshots:false,sources:false});
await p.evaluate(()=>{qaHolds.password=false;qaRelease.password();});await p.locator('[data-panel="P11.S03"]').waitFor();await shot('P11.S03');await act('back').click();await p.locator('[data-panel="P10.S04"]').waitFor();await p.click('[data-p10=sessions]');await p.locator('[data-session-row]').first().waitFor();await shot('P11.S04');
if(!before)await run({p,c,r,mode,out,act,check,settle,scenario,goto,fill,acknowledge});
r.calls=await p.evaluate(()=>qaCalls);r.outcomes=await p.evaluate(()=>qaResults);r.effects=await p.evaluate(()=>qaEffects);r.frames=await p.evaluate(()=>qaFrames);r.hardware=await p.evaluate(()=>qaHardware);assert.deepEqual(r.errors,[]);await c.close();
}if(!before){const prior=JSON.parse(fs.readFileSync('handoff/motion/M11/before-complete/results.json','utf8'));for(const r of results)assert.deepEqual(r.geometry,prior.find(x=>x.mode===r.mode).geometry,'Settled geometry/content differs '+r.mode);for(const r of results.slice(1)){assert.deepEqual(r.calls,results[0].calls,'Mode operation counts differ');assert.deepEqual(r.outcomes,results[0].outcomes,'Mode domain outcomes differ');}}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));console.error(e.message);process.exitCode=1;}finally{await browser.close();}})();

async function run({p,c,r,mode,out,act,check,settle,scenario,goto,fill,acknowledge}){
 await check('Confirmed password check fades160 once; session rows have no entrance/replay',async()=>{const effects=await p.evaluate(()=>qaEffects),success=effects.filter(e=>e.primitive==='SecureSuccess');assert.equal(success.length,mode==='auto'?1:0);if(success.length)assert.equal(success[0].duration,160);assert.ok(effects.every(e=>e.frames.every(f=>!f.transform)));assert.equal(await p.locator('[data-session-row]').count(),2);});
 await check('Revoke Cancel/Back preserve IDs; confirmation alone performs and verifies one revoke',async()=>{const rows=await p.locator('[data-session-row]').evaluateAll(ns=>ns.map(n=>n.dataset.sessionRow));await p.locator('[data-p11-revoke]').click();await act('cancel').click();await p.waitForFunction(()=>!history.state?.hnSecurityDialog);assert.equal(await p.evaluate(()=>qaCalls.revoke),0);assert.deepEqual(await p.locator('[data-session-row]').evaluateAll(ns=>ns.map(n=>n.dataset.sessionRow)),rows);await p.locator('[data-p11-revoke]').click();await p.goBack();await p.waitForFunction(()=>!history.state?.hnSecurityDialog);assert.equal(await p.evaluate(()=>qaCalls.revoke),0);await p.locator('[data-p11-revoke]').click();await p.evaluate(()=>qaHolds.revoke=true);await act('confirm').click();await p.waitForFunction(()=>qaCalls.revoke===1);assert.equal(await p.locator('[data-session-row]').count(),2);await p.evaluate(()=>{qaHolds.revoke=false;qaRelease.revoke();});await p.locator('.p11-dialog[data-tone=success]').waitFor();assert.equal(await p.locator('[data-session-row]').count(),1);await acknowledge();const count=await p.evaluate(()=>qaEffects.filter(e=>e.primitive==='SecureSuccess').length);await goto(3);await settle();assert.equal(await p.evaluate(()=>qaEffects.filter(e=>e.primitive==='SecureSuccess').length),count);});
 await check('Error field semantics immediate; focus opacity140/80/0; mode/OS cancellation',async()=>{await scenario('baseline');await goto(1);await p.locator('#p11-current').focus();await p.click('[data-p11-save]');assert.equal(await p.locator('#p11-current').getAttribute('aria-invalid'),'true');assert.match(await p.locator('#p11-current-error').textContent(),/Vui lòng/);const effects=await p.evaluate(()=>qaEffects.filter(e=>e.primitive==='SecureFormError'));assert.ok(mode==='off'?effects.length===0:effects.some(e=>e.duration===(mode==='auto'?140:80)));await p.selectOption('#home-motion-mode','off');assert.equal(await p.locator('.p11-app').evaluate(n=>n.getAnimations({subtree:true}).length),0);assert.equal(await p.locator('#p11-current').getAttribute('aria-invalid'),'true');await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.locator('#p11-next').focus();await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(40);assert.equal(await p.locator('.p11-app').evaluate(n=>n.getAnimations({subtree:true}).some(a=>a.effect.getKeyframes().some(f=>f.transform&&f.transform!=='none'))),false);await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});});
 await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});
 await check('Visibility toggle preserves connected inputs, caret, focus; mismatch never clears fields',async()=>{await fill(true);await p.locator('#p11-current').evaluate(n=>{window.qaInput=n;n.focus();n.setSelectionRange(1,3);});await p.locator('[data-p11-eye=current]').click();await p.evaluate(()=>new Promise(r=>requestAnimationFrame(r)));assert.ok(await p.locator('#p11-current').evaluate(n=>n===qaInput&&n===document.activeElement&&n.selectionStart===1&&n.selectionEnd===3));await p.locator('[data-p11-eye=current]').click();await p.click('[data-p11-save]');assert.equal(await p.evaluate(()=>qaCalls.password),1);assert.ok(await p.locator('#p11-current').evaluate(n=>n===qaInput&&n.value.length>0));assert.match(await p.locator('#p11-confirm-error').textContent(),/khớp/);});
 await check('Double submit and rapid navigate-away while pending do not change account twice',async()=>{await p.fill('#p11-confirm','fixture-motion-next');await p.evaluate(()=>qaHolds.password=true);await p.click('[data-p11-save]');await p.waitForFunction(()=>qaCalls.password===2);await p.evaluate(()=>{document.querySelector('#p11-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));location.hash='#home';});await p.waitForTimeout(60);assert.equal(await p.evaluate(()=>qaCalls.password),2);assert.equal(await p.locator('.p11-app').count(),1);await p.evaluate(()=>{qaHolds.password=false;qaRelease.password();});await p.locator('[data-panel="P11.S03"]').waitFor();assert.equal(await p.evaluate(()=>qaResults.filter(x=>x.action==='password'&&x.kind==='changed').length),2);});
 await check('Revoke failure retains source IDs; UNKNOWN reconciles without duplicate revoke',async()=>{await scenario('revoke-failed');await goto(4);await p.locator('[data-p11-revoke]').waitFor();const ids=await p.locator('[data-session-row]').evaluateAll(ns=>ns.map(n=>n.dataset.sessionRow));await p.locator('[data-p11-revoke]').click();await act('confirm').click();await p.locator('.p11-dialog[data-tone=error]').waitFor();assert.deepEqual(await p.locator('[data-session-row]').evaluateAll(ns=>ns.map(n=>n.dataset.sessionRow)),ids);await acknowledge();await scenario('revoke-unknown');await p.locator('[data-p11-revoke]').waitFor();await p.locator('[data-p11-revoke]').click();await act('confirm').click();await p.getByText('Chưa xác định kết quả',{exact:true}).waitFor();const revokes=await p.evaluate(()=>qaCalls.revoke);await act('cancel').click();await p.waitForFunction(()=>!history.state?.hnSecurityDialog);await act('reconcile').click();await p.locator('.p11-dialog[data-tone=success]').waitFor();assert.equal(await p.evaluate(()=>qaCalls.revoke),revokes);assert.equal(await p.locator('[data-session-row]').count(),1);await acknowledge();});
 await check('Native compact scroll, small session list, hide/dispose and hidden cleanup',async()=>{await scenario('baseline');await goto(4);await p.locator('[data-session-row]').first().waitFor();await p.setViewportSize({width:360,height:420});await p.locator('.p11-scroll').evaluate(n=>n.scrollTop=n.scrollHeight);const m=await p.locator('.p11-app').evaluate(n=>({rows:n.querySelectorAll('[data-session-row]').length,nodes:n.querySelectorAll('*').length,overflow:n.scrollWidth>n.clientWidth,frame:[n.closest('.hn-screen').offsetWidth,n.closest('.hn-screen').offsetHeight]}));assert.equal(m.rows,2);assert.equal(m.overflow,false);assert.deepEqual(m.frame,[494,950]);r.listProfile=m;await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-compact-sessions.png')});await p.setViewportSize({width:494,height:950});await p.click('[data-tab=home]');const listeners=await p.evaluate(()=>qaVisibility);for(let i=0;i<10;i++){await goto(1);await p.locator('#p11-current').focus();await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home:visible').waitFor();assert.equal(await p.evaluate(()=>qaVisibility),listeners);}await goto(1);await p.locator('#p11-next').focus();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p11-app').evaluate(n=>n.getAnimations({subtree:true}).length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.locator('[data-system-demo=expired]').evaluate(e=>e.click());await p.locator('.p15-host:not([hidden]),[data-panel="P15.S02"]').first().waitFor();assert.equal(await p.locator('.p11-app').evaluate(n=>n.getAnimations({subtree:true}).length),0);await p.locator('[data-p15=login]').click();await p.locator('#username').waitFor();await p.goBack();await p.locator('#username').waitFor();assert.equal(await p.locator('.p11-app').isVisible(),false);assert.ok(await p.locator('.p11-input input').evaluateAll(ns=>ns.every(n=>n.value==='')));assert.equal(await p.evaluate(()=>qaHardware),0);});
}
