const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.OUTBOUND_EVIDENCE_DIR||'handoff/P05/evidence/revision-11/edges-before');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Không tải được prototype'))errors.push(m.text());});await mockGeography(page);const sel=n=>page.locator(`[data-p05-select="${n}"]`),act=n=>page.locator(`[data-p05="${n}"]`).first(),popup=()=>page.locator('.p05-select-popup:not([hidden])');async function check(name,fn){try{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){checks.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);if(!process.env.P05_AUDIT_BEFORE)throw e;}}
try{await page.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="outbound"]').click();await address(page);
await check('province search keeps its anchor/height when results shrink to one or zero',async()=>{await sel('province').click();const before=await popup().boundingBox();await popup().locator('input').fill('ho chi minh');const after=await popup().boundingBox();await page.locator('.hn-screen').screenshot({path:path.join(out,'search-one-result.png')});assert.deepEqual(after,before);await popup().locator('input').fill('zzzz');assert.deepEqual(await popup().boundingBox(),before);});await page.locator('.hn-screen').screenshot({path:path.join(out,'search-position.png')});await page.keyboard.press('Escape');
await check('ArrowUp from search selects last matching option, not second-last',async()=>{await sel('province').click();const last=await popup().locator('[role=option]').last().getAttribute('data-p05-option');await popup().locator('input').press('ArrowUp');assert.equal(await page.evaluate(()=>document.activeElement.dataset.p05Option),last);});await page.keyboard.press('Escape');
await check('End opens a closed province picker with last option focused AND visibly scrolled into view',async()=>{await sel('province').focus();await sel('province').press('End');const last=popup().locator('[role=option]').last();assert.equal(await last.evaluate(e=>document.activeElement===e),true);assert.equal(await last.evaluate(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return a.top>=b.top-1&&a.bottom<=b.bottom+1;}),true);});await page.keyboard.press('Escape');
await check('reopening searched province list reveals current selection rather than stale last scroll',async()=>{await sel('province').click();await popup().locator('[role=listbox]').evaluate(e=>e.scrollTop=e.scrollHeight);await page.keyboard.press('Escape');await sel('province').click();assert.equal(await popup().locator('[aria-selected="true"]').evaluate(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return a.top>=b.top-1&&a.bottom<=b.bottom+1;}),true);});await page.keyboard.press('Escape');
await check('six viewports: filtering never shifts popup or form and Back/Escape retain original location',async()=>{for(const viewport of [{width:340,height:420},{width:390,height:844},{width:494,height:1000},{width:768,height:1024},{width:1440,height:1000},{width:1869,height:940}]){await page.setViewportSize(viewport);await sel('province').click();const start=await popup().boundingBox(),footer=await page.locator('.p05-footer').boundingBox();for(const q of ['ho chi minh','zzzz','']){await popup().locator('input').fill(q);assert.deepEqual(await popup().boundingBox(),start);assert.deepEqual(await page.locator('.p05-footer').boundingBox(),footer);}await page.locator('.hn-screen').screenshot({path:path.join(out,`stable-${viewport.width}.png`)});await page.keyboard.press('Escape');assert.equal(await sel('province').getAttribute('data-value'),'79');}await page.setViewportSize({width:494,height:1000});});
await check('field caret survives delayed unrelated repaint of open manual input',async()=>{await act('next').click();await act('manual').click();await page.fill('#p05-code','HN12345');await page.locator('#p05-code').evaluate(e=>e.setSelectionRange(2,4));await page.locator('.p05-tools summary').click();await page.locator('#p05-code').focus();await page.locator('#p05-code').evaluate(e=>e.setSelectionRange(2,4));await page.selectOption('[data-p05-outcome]','failed');assert.equal(await page.inputValue('#p05-code'),'HN12345');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));}catch(e){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
