const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const before=process.argv.includes('--before'),out=path.resolve('handoff/P07/evidence/revision-12/'+(before?'before':'after'));fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1,permissions:['clipboard-write','clipboard-read']}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));const act=n=>page.locator(`[data-p07="${n}"]`).first(),snap=()=>page.locator('[data-p07-snapshot]').evaluate(e=>JSON.parse(e.textContent));
 const capture=async name=>{await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});};
 const read=async()=>{await page.click('[data-p07-demo-read]');await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).busy);};
 const close=async()=>{await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP07Feedback&&!history.state?.hnP07Detail);};
 try{
 await page.goto((process.env.PREVIEW_ORIGIN||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route="nfc"]');await capture('list');
 await page.fill('#p07-search','NO-MATCH');await capture('empty');
 if(!before){await act('clear-filters').click();assert.equal((await snap()).query,'');assert.equal((await snap()).tab,'all');checks.push('empty reset clears query/tab');}else await page.fill('#p07-search','');
 await page.click('[data-p07-tag="fixture-tag-002"]');await capture('detail');
 if(!before){const hash=await page.evaluate(()=>location.hash);await act('copy').click();assert.equal(await page.locator('dialog[open]').count(),1);assert.equal(await act('copy').getAttribute('data-copied'),'true');await capture('copied');await page.goBack();await page.locator('dialog[open]').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>location.hash),hash);checks.push('copy stays in detail; Back closes before route');}else await close();
 await act('begin').click();await capture('ready');await read();await capture('read');await act('next').click();await capture('verify');await act('confirm').click();await page.locator('[data-panel="P07.S04"]').waitFor();await capture('success');await act('new-link').click();await capture('next-product');
 if(!before){assert.match(await page.locator('.p07-product-hint').textContent(),/Đang liên kết tiếp/);assert.equal((await snap()).read,null);assert.equal(await act('change-product').isVisible(),true);checks.push('next link retains explicit product and requires fresh read');}
 await page.locator('.p07-tools>details>summary').click();await page.selectOption('[data-p07-scenario]','read-error');await read();await page.locator('.hn-action-dialog[open]').waitFor();await capture('read-error');
 if(!before){assert.equal(await page.locator('[data-action-dialog="confirm"]').textContent(),'Đọc lại');checks.push('read error has contextual retry');}await close();
 await page.selectOption('[data-p07-scenario]','unknown');await read();await act('next').click();await act('confirm').click();await page.locator('.hn-action-dialog[open]').waitFor();await capture('unknown-dialog');await close();await capture('unknown-pending');
 if(!before){assert.equal((await snap()).unknown,true);assert.equal(await act('reconcile').isEnabled(),true);checks.push('UNKNOWN remains pending with reconcile action');}
 if(!before){
  const pending=(await snap()).request;await act('reconcile').click();await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,pending.requestId);
  await act('new-link').click();await act('change-product').click();await page.locator('[data-p06-item="fixture-item-HN12345"]').click();assert.equal((await snap()).itemId,'fixture-item-HN12345');assert.equal((await snap()).read,null);checks.push('change product reuses P06; preserves independent fields and clears read');
  await page.selectOption('[data-p07-scenario]','read-error');await read();const reads=(await snap()).stats.reads;await page.locator('[data-action-dialog="confirm"]').click();await page.waitForFunction(n=>JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).stats.reads>n,reads);await page.locator('.hn-action-dialog[open]').waitFor();assert.equal((await snap()).stats.mutations,2);await close();checks.push('contextual retry executes one read, no link');
  await page.selectOption('[data-p07-scenario]','conflict');await read();await page.locator('.hn-action-dialog[open]').waitFor();await capture('conflict');assert.equal(await page.locator('[data-action-dialog="confirm"]').textContent(),'Chọn thẻ khác');await page.locator('[data-action-dialog="confirm"]').click();await page.locator('dialog[open]').waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP07Feedback);assert.equal((await snap()).read,null);assert.equal((await snap()).stats.mutations,2);assert.equal(await page.locator('[data-p07-scenario]').inputValue(),'conflict');checks.push('choose another tag does not silently reset failure scenario or write');
  for(const scenario of ['unsupported','permission','link-denied']){await page.selectOption('[data-p07-scenario]',scenario);await read();await page.locator('.hn-action-dialog[open]').waitFor();await capture(scenario);await close();assert.equal(await act('next').isDisabled(),true);assert.doesNotMatch(await page.locator('.p07-read-guide').textContent(),/Sẵn sàng đọc/);}checks.push('unavailable states never advertise ready or enable Continue');
  await page.selectOption('[data-p07-scenario]','ready');
  const sizes=[[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]];
  async function matrix(name){for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.locator('.p07-app').evaluate(app=>{const scroll=app.querySelector('.p07-scroll'),footer=app.querySelector('.p07-footer');return {overflow:scroll.scrollWidth>scroll.clientWidth,footer:!footer||scroll.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1,touch:[...app.querySelectorAll('.p07-header button,.p07-copy,.p07-clear-query:not([hidden]),.p07-dialog-back')].map(e=>({w:e.offsetWidth,h:e.offsetHeight}))};});assert.equal(m.overflow,false);assert.equal(m.footer,true);for(const t of m.touch){assert.ok(t.w>=44&&t.h>=44);}await capture(`${name}-${width}x${height}`);}}
  await matrix('ready');await read();await act('next').click();await matrix('verify');await act('confirm').click();await page.locator('[data-panel="P07.S04"]').waitFor();await matrix('success');await act('back').click();await page.locator('[data-panel="P07.S01"]').waitFor();await page.fill('#p07-search','TAG');await matrix('search');
  await act('clear-query').click();assert.equal((await snap()).query,'');await page.click('[data-p07-tab="unlinked"]');await page.fill('#p07-search','NO-MATCH');await act('clear-filters').click();assert.equal((await snap()).tab,'all');assert.equal((await snap()).query,'');checks.push('24 viewport captures; touch targets44px; no horizontal overflow; reset is atomic');
  await page.click('[data-p07-tag="fixture-tag-002"]');const uid=(await snap()).selectedUid;await act('close-detail').first().click();await page.locator('dialog[open]').waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP07Detail);assert.equal((await snap()).selectedUid,uid);assert.equal(await page.locator('[data-p07-tag="fixture-tag-002"]').evaluate(e=>e===document.activeElement),true);checks.push('UI Back returns focus without changing selected NFC');
  await page.click('[data-p07-tag="fixture-tag-002"]');const height=await page.locator('dialog[open]').evaluate(e=>e.offsetHeight);await act('copy').click();assert.equal(await page.locator('dialog[open]').evaluate(e=>e.offsetHeight),height);await page.waitForFunction(()=>!document.querySelector('[data-p07="copy"]').dataset.copied);assert.equal(await page.locator('.p07-copy-note').textContent(),'');
  await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));await act('copy').click();await page.locator('.hn-action-dialog[open]').waitFor();assert.equal(await page.locator('dialog[open]').count(),1);await capture('copy-denied');await page.keyboard.press('Escape');await page.locator('#p07-detail-title').waitFor();assert.equal(await page.locator('dialog[open]').count(),1);await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'detached'});checks.push('copy badge resets without reflow; failure uses one dialog then returns to detail');
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({before,checks,errors},null,2));console.log('PASS '+(before?'before captures':checks.length+' UX checks'));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png')});throw e;}finally{await browser.close();}
})();

