const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out=path.resolve('handoff/motion/M08/evidence'+(before?'/before':''));fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/history/history.mjs','docs/flows/history/history-model.mjs','docs/flows/history/history-source.mjs','docs/flows/history/business-history-data.mjs','docs/flows/history/motion.mjs','docs/flows/history/style.css','docs/flows/home/home.mjs','docs/flows/home/motion.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css','docs/flows/shared/history-fixtures.js'];
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(files.filter(f=>fs.existsSync(f)).map(file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),bytes:fs.statSync(file).size})),null,2));
if(before){for(const file of files.filter(f=>fs.existsSync(f))){const to=path.join(out,'source',file);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(file,to);}fs.copyFileSync('handoff/motion/MOTION_RUN_STATE.json','handoff/motion/M08/INPUT_MOTION_RUN_STATE.json');}
(async()=>{const browser=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
 const context=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await context.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.stack));await context.tracing.start({screenshots:true,snapshots:true,sources:true});await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
 await p.addInitScript(()=>{window.qaAnimations=[];window.qaFrames=[];window.qaListeners=0;window.qaHardware=0;const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners--;return remove.call(this,t,f,o);};
 const native=Element.prototype.animate;Element.prototype.animate=function(frames,opts){const entry={node:this.id||this.className,primitive:this.dataset.motionPrimitive,frames,duration:opts.duration,cancelled:false};qaAnimations.push(entry);const a=native.call(this,frames,opts),cancel=a.cancel.bind(a);a.cancel=()=>{entry.cancelled=true;cancel();};if(entry.primitive?.startsWith('History')){const node=this,start=performance.now();const tick=()=>{qaFrames.push({primitive:entry.primitive,elapsed:performance.now()-start,opacity:getComputedStyle(node).opacity,connected:node.isConnected});if(node.isConnected&&performance.now()-start<180)requestAnimationFrame(tick);};requestAnimationFrame(tick);}return a;};
 if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('No hardware in history');};window.NDEFReader=class{constructor(){qaHardware++;throw Error('No NFC in history');}};
 });
 const a=n=>p.locator(`[data-p08="${n}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p08-snapshot]').textContent()),settle=()=>p.waitForTimeout(240);
 if(!before)await p.route('**/history-picker.mjs',async route=>{const response=await route.fetch(),body=await response.text();assert.ok(body.includes('handle.close();onApply(draft);'));await route.fulfill({response,body:body.replace('handle.close();onApply(draft);','handle.close();if(window.qaDelayPicker){window.qaLatePicker=()=>onApply(draft);}else onApply(draft);')});});
 async function route(panel,extra=''){await p.evaluate(h=>location.hash=h,'#p02/history-list?panel='+panel+extra);await p.locator(`[data-panel="P08.S0${panel}"]`).waitFor();await settle();}
 async function capture(panel){await settle();await p.evaluate(()=>scrollTo(0,0));r.geometry[panel]=await p.locator('.p08-app').evaluate(app=>{const shell=app.closest('.hn-screen'),base=shell.getBoundingClientRect();return Object.fromEntries(['.p08-header','.p08-scroll','.p08-list','.p08-detail-hero','.p08-counters','.p08-day-overview','.hn-nav'].map(s=>{const e=shell.querySelector(s);if(!e)return[s,null];const q=e.getBoundingClientRect();return[s,[q.x-base.x,q.y-base.y,q.width,q.height]];}));});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+panel+'.png')});}
 async function check(name,fn){await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);}
 await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');
 await route(1);await capture('P08.S01');r.profile=await p.locator('.p08-app').evaluate(e=>({nodes:e.querySelectorAll('*').length,rows:e.querySelectorAll('.p08-row').length,scroll:'native'}));
 await route(2,'&record=LS-0001');await capture('P08.S02');await route(3,'&session=PQ-0001');await capture('P08.S03');await route(4);await capture('P08.S04');
 if(!before)await runChecks({p,r,a,snap,route,settle,check,capture,mode,out});
 assert.deepEqual(r.errors,[]);await context.tracing.stop({path:path.join(out,mode+'-trace.zip')});await context.close();
}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
async function runChecks({p,r,a,snap,route,settle,check,mode,out}){
 const clearLog=()=>p.evaluate(()=>qaAnimations=[]),localLog=()=>p.evaluate(()=>qaAnimations.filter(e=>e.primitive?.startsWith('History')));
 async function applyDay(day){await a('filter').click();await p.fill('[name=from]',day);await p.fill('[name=to]',day);await p.locator('.p08-picker [type=submit]').click();await p.waitForFunction(()=>!history.state?.hnP08Picker&&!document.querySelector('.p08-picker'));}
 await check('filter140/tab140; input stays connected and no shell replay for query/type',async()=>{
  await route(1);if(await a('clear').count())await a('clear').click();await settle();await p.locator('#p08-search').evaluate(e=>{window.qaInput=e;e.focus();});await clearLog();await p.fill('#p08-search','PN');await settle();assert.equal(await p.locator('#p08-search').evaluate(e=>e===qaInput&&e===document.activeElement),true);await p.click('[data-p08-type=inbound]');await settle();const effects=await localLog();assert.ok(mode==='off'?effects.length===0:effects.some(x=>x.primitive==='HistoryFilter')&&effects.some(x=>x.primitive==='HistoryTab'));assert.ok(effects.every(x=>x.duration===(mode==='auto'?140:80)));assert.equal(await p.evaluate(()=>qaAnimations.filter(e=>e.node==='hn-destination').length),0);await a('clear').click();await settle();
 });
 await check('load more appends stable rows; detail Back retains order/count/scroll and no row entrances',async()=>{
  await route(1);await p.evaluate(()=>{window.qaRows=[...document.querySelectorAll('.p08-row')];});await clearLog();await p.locator('.p08-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await p.waitForFunction(()=>document.querySelectorAll('.p08-row').length>6);assert.equal(await p.evaluate(()=>qaRows.every(n=>n.isConnected)),true);await p.locator('.p08-scroll').evaluate(e=>e.scrollTop=180);await settle();const ids=await p.locator('.p08-row').evaluateAll(es=>es.map(e=>e.dataset.p08Record)),top=await p.locator('.p08-scroll').evaluate(e=>e.scrollTop);r.listProfile={rows:ids.length,nodes:await p.locator('.p08-app *').count()};await p.locator('.p08-row').nth(1).evaluate(e=>e.click());await p.locator('[data-panel="P08.S02"]').waitFor();await a('back').click();await p.locator('[data-panel="P08.S01"]').waitFor();assert.deepEqual(await p.locator('.p08-row').evaluateAll(es=>es.map(e=>e.dataset.p08Record)),ids);assert.ok(Math.abs(await p.locator('.p08-scroll').evaluate(e=>e.scrollTop)-top)<2);assert.equal((await localLog()).length,0);
 });
 await check('S02 route uses shell once; table ordering and tab keyboard/Back semantics unchanged',async()=>{
  await clearLog();await route(2,'&record=LS-0001');assert.equal(await p.evaluate(()=>qaAnimations.filter(e=>e.node==='hn-destination').length),mode==='auto'?1:0);r.labels=await p.locator('.p08-detail-kv dt').allTextContents();await clearLog();await p.locator('[data-p08-tab=info]').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('[data-p08-tab=timeline]').getAttribute('aria-selected'),'true');await settle();assert.equal(await p.evaluate(()=>qaAnimations.filter(e=>e.node==='hn-destination').length),0);assert.equal((await localLog()).length,mode==='off'?0:1);r.timelineIds=await p.locator('[data-event-id]').evaluateAll(es=>es.map(e=>e.dataset.eventId));
 });
 await check('S03 historical events immediate and static; expand/Back never generates or replays events',async()=>{
  await route(3,'&session=PQ-0001');r.counters=await p.locator('.p08-counters strong').allTextContents();await clearLog();await a('codes').click();const ids=await p.locator('[data-scan-id]').evaluateAll(es=>es.map(e=>e.dataset.scanId));assert.equal(ids.length,19);await a('p23').click();await p.locator('[data-panel="P08.S01"]').waitFor();await a('back').click();await p.locator('[data-panel="P08.S03"]').waitFor();assert.deepEqual(await p.locator('[data-scan-id]').evaluateAll(es=>es.map(e=>e.dataset.scanId)),ids);assert.equal((await localLog()).length,0);r.scanIds=ids;
 });
 await check('S04 dates/counters update immediately; fade content only and retain native scroll',async()=>{
  await route(4);await p.locator('.p08-scroll').evaluate(e=>e.scrollTop=100);await settle();await a('filter').evaluate(e=>e.click());const top=await p.locator('.p08-scroll').evaluate(e=>e.scrollTop);await p.fill('[name=from]','09/09/2026');await p.fill('[name=to]','09/09/2026');await clearLog();await p.locator('.p08-picker [type=submit]').click();await p.waitForFunction(()=>!history.state?.hnP08Picker&&!document.querySelector('.p08-picker'));assert.deepEqual(await p.locator('.p08-grid strong').allTextContents(),['12','6','4','3','5','30']);assert.ok(Math.abs(await p.locator('.p08-scroll').evaluate(e=>e.scrollTop)-top)<2);await settle();const effects=await localLog();assert.equal(effects.length,mode==='off'?0:1);if(effects.length)assert.match(effects[0].node,/p08-day-activities/);assert.equal(await p.evaluate(()=>qaAnimations.some(e=>/p08-stat|p08-grid|p08-counters/.test(e.node))),false);r.dayCounts=await p.locator('.p08-grid strong').allTextContents();
 });
 await check('obsolete deferred date callback cannot replace a newer date or survive leaving module',async()=>{
  await p.evaluate(()=>qaDelayPicker=true);await applyDay('08/09/2026');await p.evaluate(()=>qaDelayPicker=false);await applyDay('09/09/2026');await p.evaluate(()=>qaLatePicker());await settle();assert.equal((await snap()).dayFilters.from,'2026-09-09');assert.equal(await p.locator('.p08-grid strong').last().textContent(),'30');await p.evaluate(()=>qaDelayPicker=true);await applyDay('08/09/2026');await p.click('[data-tab=home]');await p.evaluate(()=>qaLatePicker());await settle();assert.equal(await p.locator('.p08-app').count(),0);await p.evaluate(()=>qaDelayPicker=false);
 });
 await check('mode switch, OS reduction, hidden page and rapid route cancel obsolete animation',async()=>{
  await route(1);await p.fill('#p08-search','PN');await p.selectOption('#home-motion-mode','off');assert.equal(await p.locator('.p08-list').evaluate(e=>e.getAnimations().length),0);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),mode==='off'?'off':'reduced');await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.fill('#p08-search','PX');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p08-list').evaluate(e=>e.getAnimations().length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));document.querySelector('[data-tab=home]').click();});await route(2,'&record=LS-0001');
 });
 await check('P12 document and P18 attachment edges return correct P08 record; no physical service calls',async()=>{
  await a('document').click();await p.locator('.p12-app').waitFor();await p.goBack();await p.locator('.p08-app').waitFor();assert.equal((await snap()).recordId,'LS-0001');await p.click('[data-p08-tab=attachments]');await a('attachments').click();await p.locator('.p18-app').waitFor();await p.goBack();await p.locator('.p08-app').waitFor();assert.equal((await snap()).recordId,'LS-0001');assert.equal(await p.evaluate(()=>qaHardware),0);
 });
 await check('ten enter/leave cycles return listener count; error/unknown data modes remain truthful',async()=>{
  await p.click('[data-tab=home]');const count=await p.evaluate(()=>qaListeners);for(let i=0;i<10;i++){await route(1);assert.equal(await p.evaluate(()=>qaListeners),count+1);await p.click('[data-tab=home]');assert.equal(await p.evaluate(()=>qaListeners),count);}await route(1);for(const scenario of ['loading','error','unavailable','empty']){await p.selectOption('[data-p08-scenario]',scenario);assert.equal(await p.locator('.p08-row').count(),0);assert.match(await p.locator('.p08-state').innerText(),/lịch sử|hoạt động|kết quả/i);}await p.selectOption('[data-p08-scenario]','ready');
 });
 r.frames=await p.evaluate(()=>qaFrames);if(mode==='auto')assert.ok(r.frames.some(e=>Number(e.opacity)<1&&e.connected),'real intermediate opacity frame');r.effects=await p.evaluate(()=>qaAnimations);
 r.domain=await p.evaluate(async()=>{const m=await import('/flows/history/history-model.mjs');return {ids:m.DATA.records.map(r=>r.activityId),sessions:m.DATA.sessions.map(s=>({id:s.id,eventIds:s.events.map(e=>e.id),total:s.total,accepted:s.accepted,duplicate:s.duplicate})),hardware:qaHardware};});
 await check('logout immediately removes protected history and Back never restores it',async()=>{await p.fill('#p08-search','PN');await p.click('#hn-logout');await p.locator('#login-form').waitFor();assert.equal(await p.locator('.p08-app').count(),0);await p.goBack();assert.equal(await p.locator('.p08-app').count(),0);});
}
