const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out='handoff/motion/M12/evidence'+(before?'/before':'');fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/documents/documents.mjs','docs/flows/documents/document-model.mjs','docs/flows/documents/style.css','docs/flows/documents/motion.mjs','docs/flows/home/home.mjs','docs/flows/home/motion.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(files.filter(f=>fs.existsSync(f)).map(file=>({file,bytes:fs.statSync(file).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')})),null,2));
if(before)for(const file of files.filter(f=>fs.existsSync(f))){const to=path.join(out,'source',file);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(file,to);}
(async()=>{const b=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
 const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));await c.tracing.start({screenshots:true,snapshots:true,sources:true});await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
 await p.addInitScript(()=>{window.qaAnimations=[];window.qaFrames=[];window.qaListeners=0;window.qaHardware=0;window.qaLongTasks=[];
  const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners--;return remove.call(this,t,f,o);};
  const native=Element.prototype.animate;Element.prototype.animate=function(frames,options){const entry={node:this.id||this.className,primitive:this.dataset.motionPrimitive,duration:options.duration,frames,time:performance.now(),cancelled:false};qaAnimations.push(entry);const a=native.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{entry.cancelled=true;cancel();};if(entry.primitive?.startsWith('Document')){const node=this,start=performance.now();const tick=()=>{qaFrames.push({primitive:entry.primitive,time:performance.now()-start,opacity:getComputedStyle(node).opacity,connected:node.isConnected});if(node.isConnected&&performance.now()-start<200)requestAnimationFrame(tick);};requestAnimationFrame(tick);}return a;};
  new PerformanceObserver(list=>qaLongTasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});
  if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('No hardware in P12');};window.NDEFReader=class{constructor(){qaHardware++;throw Error('No hardware in P12');}};
 });
 async function settle(){await p.waitForTimeout(250);}async function route(h){await p.evaluate(h=>location.hash=h,h);await p.locator('.p12-app').waitFor();await settle();}async function capture(name){await settle();r.geometry[name]=await p.locator('.p12-app').evaluate(app=>{const shell=app.closest('.hn-screen'),base=shell.getBoundingClientRect();return Object.fromEntries(['.p12-header','.p12-scroll','.p12-detail-dock','.p12-totals','.p12-footer','.hn-nav'].map(s=>{const e=shell.querySelector(s);if(!e)return[s,null];const b=e.getBoundingClientRect();return[s,[b.x-base.x,b.y-base.y,b.width,b.height]];}));});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+name+'.png')});}
 async function check(name,fn){await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);}
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');
 await route('#p02/documents');await p.locator('.p12-record').first().waitFor();await capture('P12.S01');r.profile=await p.locator('.p12-app').evaluate(e=>({nodes:e.querySelectorAll('*').length,rows:e.querySelectorAll('.p12-record').length}));
 await route('#p02/documents?panel=2&doc=fixture-inbound-0005');await capture('P12.S02');await p.click('[data-p12-tab=products]');await capture('P12.S03');assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['11','3']);
 await route('#p02/documents?panel=4');await capture('P12.S04');
 if(!before)await runChecks({p,c,r,mode,route,capture,settle,check,out});
 r.animations=await p.evaluate(()=>qaAnimations);r.frames=await p.evaluate(()=>qaFrames);r.longTasks=await p.evaluate(()=>qaLongTasks);assert.deepEqual(r.errors,[]);await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});await c.close();
 }fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
async function runChecks({p,c,r,mode,route,capture,settle,check,out}){

 const act=a=>p.locator('[data-p12="'+a+'"]').first(),tab=t=>p.locator('[data-p12-tab="'+t+'"]'),effects=primitive=>p.evaluate(x=>qaAnimations.filter(a=>a.primitive===x),primitive);
 const home=async()=>{await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home:visible').waitFor();await settle();};
 const close=async()=>{if(await p.locator('.app-modal-host').count()){await p.keyboard.press('Escape');await p.locator('.app-modal-host').waitFor({state:'detached'});await p.waitForTimeout(100);}};
 const docs=()=>route('#p02/documents'),products=()=>route('#p02/documents?panel=3&doc=fixture-inbound-0005');
 await check('Filter commits once at140/80/0, preserves input and final status data',async()=>{
  await docs();await p.evaluate(()=>qaAnimations=[]);await p.click('[data-p12-type=inbound]');await p.waitForFunction(()=>document.querySelectorAll('.p12-record').length===8);await settle();
  const log=await effects('DocumentFilter');assert.equal(log.length,mode==='off'?0:1);if(log.length)assert.equal(log[0].duration,mode==='auto'?140:80);
  await p.evaluate(()=>window.qaInput=document.querySelector('#p12-query'));await p.fill('#p12-query','PN-0005');await p.waitForFunction(()=>document.querySelectorAll('.p12-record').length===1);assert.ok(await p.locator('#p12-query').evaluate(e=>e===qaInput&&e===document.activeElement));assert.equal(await p.locator('.p12-record-copy strong').textContent(),'PN-0005');assert.equal(await p.locator('.p12-badge').textContent(),'Chờ xử lý trên Web');
  assert.ok((await p.evaluate(()=>qaAnimations)).every(a=>!String(a.node).includes('p12-badge')));
  await act('clear').click();await p.waitForFunction(()=>document.querySelectorAll('.p12-record').length===24);
 });
 await check('Date/status Apply fades only committed results; Cancel and rapid taps do not replay obsolete lists',async()=>{
  const n=(await effects('DocumentFilter')).length;await act('filter').click();await p.fill('#pick-from','09/09/2026');await p.fill('#pick-to','09/09/2026');await p.locator('.p08-picker footer [data-cancel]').click();await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);await settle();assert.equal((await effects('DocumentFilter')).length,n);
  await act('filter').click();await p.fill('#pick-from','09/09/2026');await p.fill('#pick-to','09/09/2026');await p.check('[name=status][value=waiting]');await p.locator('.p08-picker [type=submit]').click();await p.waitForFunction(()=>!history.state?.hnDocumentsDialog&&document.querySelectorAll('.p12-record').length===1);await settle();assert.equal((await effects('DocumentFilter')).length,n+(mode==='off'?0:1));assert.equal(await p.locator('.p12-record-copy strong').textContent(),'PN-0005');
  await act('clear').click();await p.evaluate(()=>{for(const t of ['inbound','outbound','warranty','all'])document.querySelector('[data-p12-type='+t+']').click();});await p.waitForFunction(()=>document.querySelectorAll('.p12-record').length===24);await settle();assert.equal(await p.locator('[data-p12-type=all]').getAttribute('aria-selected'),'true');
 });
 await check('Notification -> exact document -> products -> Back retains source and11/3 immediately',async()=>{
  await p.evaluate(()=>location.hash='#p02/notifications');await p.locator('[data-p13-event=p13-event-inbound]').click();await p.locator('[data-panel="P13.S02"]').waitFor();const from=await p.evaluate(()=>location.hash);await p.evaluate(()=>qaAnimations=[]);await p.click('[data-p13=document]');await p.locator('.p12-context').waitFor();assert.match(await p.evaluate(()=>location.hash),/fixture-inbound-0005/);assert.equal(await p.locator('.p12-context h2').textContent(),'PN-0005');
  const nav=(await p.evaluate(()=>qaAnimations)).filter(a=>a.node==='hn-destination');assert.equal(nav.length,mode==='auto'?1:0);if(nav.length)assert.equal(nav[0].duration,180);const count=nav.length;
  await tab('products').click();assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['11','3']);assert.equal((await p.evaluate(()=>qaAnimations.filter(a=>a.node==='hn-destination'))).length,count);await act('back').click();await p.locator('[data-panel="P13.S02"]').waitFor();assert.equal(await p.evaluate(()=>location.hash),from);
 });
 await check('Selected product feedback leaves rows,counters and serials unchanged; close never submits',async()=>{
  await products();await p.evaluate(()=>qaAnimations=[]);const row=p.locator('[data-p12-line]').first(),before=await row.boundingBox();await row.click();assert.equal(await p.locator('.p12-serials li').count(),5);assert.deepEqual(await row.boundingBox(),before);assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['11','3']);const log=await effects('DocumentSelection');assert.equal(log.length,mode==='auto'?1:0);if(log.length)assert.equal(log[0].duration,160);await close();await p.fill('#p12-product-query','DS2208');assert.equal(await p.locator('.p12-product').count(),1);assert.match(await p.locator('.p12-product-count').textContent(),/1/);await tab('info').click();await tab('products').click();assert.equal(await p.inputValue('#p12-product-query'),'DS2208');await p.fill('#p12-product-query','');
 });
 await check('Form validation is immediate; mount and dismiss do not allocate drafts',async()=>{
  await route('#p02/documents?panel=4');const owner=await p.locator('[data-p04-snapshot]').textContent();assert.ok(!owner||!JSON.parse(owner).document);await p.evaluate(()=>qaAnimations=[]);await p.locator('#p12-note').evaluate(e=>{e.value='A'.repeat(201);e.dispatchEvent(new Event('input',{bubbles:true}));});await act('continue').click();assert.equal(await p.locator('#p12-note').getAttribute('aria-invalid'),'true');assert.ok(await p.locator('#p12-note').evaluate(e=>e===document.activeElement));const log=await effects('DocumentFormError');assert.equal(log.length,mode==='off'?0:1);if(log.length)assert.equal(log[0].duration,mode==='auto'?140:80);
  await p.fill('#p12-note','Motion keeps this draft');await act('supplier').click();await p.check('[name=choice][value=fixture-supplier-003]');await p.goBack();await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);assert.match(await p.locator('#p12-supplier-value').textContent(),/Minh Phát/);assert.equal(await p.inputValue('#p12-note'),'Motion keeps this draft');assert.ok(!await p.locator('[data-p04-snapshot]').textContent()||!JSON.parse(await p.locator('[data-p04-snapshot]').textContent()).document);
 });
 await check('Failing owner request retains draft and request across resume; motion adds zero operations',async()=>{
  await act('continue').click();await p.locator('[data-panel="P04.S02"]').waitFor();const snap=async()=>JSON.parse(await p.locator('[data-p04-snapshot]').textContent());assert.equal((await snap()).metrics.recordCalls,0);await p.click('[data-p04=manual]');await p.fill('#p04-code','HN12345');await p.press('#p04-code','Enter');await p.locator('[data-p04=next]').first().click();await p.selectOption('[data-p04-outcome]','failed',{force:true});await p.locator('[data-p04=send]').dblclick();await p.waitForFunction(()=>JSON.parse(document.querySelector('[data-p04-snapshot]').textContent).outcome==='not-recorded');await close();const failed=await snap();assert.equal(failed.metrics.recordCalls,1);await route('#p02/documents?panel=4');await p.locator('[data-p12-resume=inbound]').click();await p.locator('[data-panel="P04.S03"]').waitFor();const resumed=await snap();assert.deepEqual(resumed.document,failed.document);assert.deepEqual(resumed.request,failed.request);assert.equal(resumed.metrics.recordCalls,1);assert.equal(resumed.metrics.inventoryDelta,0);r.domain={note:resumed.document.note,supplier:resumed.document.supplierId,accepted:resumed.accepted.map(x=>({sku:x.sku,quantity:x.quantity})),outcome:resumed.outcome,recordCalls:resumed.metrics.recordCalls,inventoryDelta:resumed.metrics.inventoryDelta};
 });
 await check('Native list Back restores scroll and never replays row/filter entrance',async()=>{
  await docs();await p.locator('.p12-record').first().waitFor();await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=180);const y=await p.locator('.p12-scroll').evaluate(e=>e.scrollTop),n=(await effects('DocumentFilter')).length;await p.locator('.p12-record').last().dispatchEvent('click');await p.goBack();await p.locator('.p12-record').first().waitFor();await settle();assert.equal(await p.locator('.p12-scroll').evaluate(e=>e.scrollTop),y);assert.equal((await effects('DocumentFilter')).length,n);
  await p.setViewportSize({width:360,height:420});await products();await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const m=await p.locator('.p12-app').evaluate(e=>({width:e.scrollWidth,client:e.clientWidth,frame:[e.closest('.hn-screen').offsetWidth,e.closest('.hn-screen').offsetHeight]}));assert.equal(m.width,m.client);assert.deepEqual(m.frame,[494,950]);await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-compact.png')});await p.setViewportSize({width:494,height:950});
 });
 await check('Loading,error,read-only and PDF busy are immediate and mode-safe; hidden decoration pauses',async()=>{
  await docs();await p.locator('[data-p16-demo=loading]').evaluate(e=>e.click());await p.locator('.p16-spinner').first().waitFor();const spinner=p.locator('.p16-spinner').first();assert.equal(await spinner.evaluate(e=>getComputedStyle(e).animationName),mode==='auto'?'p16-spin':'none');
  await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await spinner.evaluate(e=>getComputedStyle(e).animationPlayState),'paused');await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
  await p.locator('[data-p16-demo=error]').evaluate(e=>e.click());await p.locator('[data-p12=retry]').waitFor();assert.equal(await p.locator('.p12-record').count(),0);await p.locator('[data-p16-demo=ready]').evaluate(e=>e.click());await p.locator('.p12-record').first().waitFor();
  await p.locator('#p16-readonly').evaluate(e=>{e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));});await route('#p02/documents?panel=4');assert.equal(await p.locator('.p12-app').getAttribute('data-panel'),'P12.S01');assert.equal(await p.locator('[data-p12=create]').count(),0);await p.locator('#p16-readonly').evaluate(e=>{e.checked=false;e.dispatchEvent(new Event('change',{bubbles:true}));});
  await route('#p02/documents?panel=2&doc=fixture-inbound-0005&tab=files');let held;await p.route('**/documents/assets/*.pdf',r=>{held=r;});try{await p.locator('[data-p12-download]').first().click();assert.equal(await p.locator('[data-p12-download]').first().getAttribute('aria-busy'),'true');assert.equal(await p.locator('.p12-file-spinner').evaluate(e=>getComputedStyle(e).animationName),mode==='auto'?'p12-file-spin':'none');await act('back').click();await p.locator('#p12-query').waitFor();}finally{await held?.abort().catch(()=>{});await p.unroute('**/documents/assets/*.pdf');}assert.equal(await p.locator('.app-modal-host').count(),0);
 });
 await check('Live mode/OS change,hidden state and10 navigation cycles clean up effects and listeners',async()=>{
  await home();const listeners=await p.evaluate(()=>qaListeners);for(let i=0;i<10;i++){await docs();await p.locator('.p12-record').first().waitFor();await p.click('[data-p12-type=inbound]');await home();assert.equal(await p.evaluate(()=>qaListeners),listeners);}
  await docs();await p.selectOption('#home-motion-mode','auto');await p.emulateMedia({reducedMotion:'reduce'});await p.click('[data-p12-type=all]');await settle();assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),'reduced');await p.selectOption('#home-motion-mode','off');assert.equal(await p.locator('.p12-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');
  await p.click('[data-p12-type=inbound]');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p12-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);assert.equal(await p.locator('#hn-destination').getAttribute('data-document-motion-hidden'),'true');await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await settle();
  await p.locator('[data-system-demo=expired]').evaluate(e=>e.click());await p.locator('.p15-host:not([hidden]),[data-panel="P15.S02"]').first().waitFor();assert.equal(await p.locator('.p12-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.locator('[data-p15=login]').click();await p.locator('#username').waitFor();assert.equal(await p.evaluate(()=>qaHardware),0);
 });
 const reference=JSON.parse(fs.readFileSync('handoff/motion/M12/evidence/before/results.json','utf8')).find(x=>x.mode===mode);assert.deepEqual(r.geometry,reference.geometry,'settled baseline geometry');

}
