const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='handoff/P22/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1});const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.setFixedTime(new Date('2026-09-30T05:00:00Z'));
const a=k=>p.locator(`[data-p22="${k}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p22-snapshot]').textContent());
const shot=n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});
async function route(hash){await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(180);}
async function test(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p22-r01');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');
await test('Home recent Xem tất cả remains P12',async()=>{await p.locator('[data-home-documents]').click();await p.waitForSelector('.p12-app');assert.match(p.url(),/documents/);});
await route('#p02/history?scene=nfc');await p.selectOption('[data-p22-source]','fixture');await p.waitForSelector('#p22-search');
await test('Date draft Reset/Cancel/Apply, bounds Vietnam',async()=>{const before=(await snap()).filters;await a('filter').click();await p.fill('[name=from]','10/09/2026');await p.fill('[name=to]','10/09/2026');await p.click('[data-cancel]');await p.waitForTimeout(180);assert.deepEqual((await snap()).filters,before);await a('filter').click();await p.fill('[name=from]','10/09/2026');await p.fill('[name=to]','10/09/2026');await p.locator('.p08-picker [type=submit]').click();await p.waitForSelector('#p22-search');assert.equal((await snap()).count,3);await a('filter').click();await p.click('[data-reset]');await p.keyboard.press('Escape');await p.waitForTimeout(180);assert.equal((await snap()).filters.from,'2026-09-10');await a('filter').click();await p.fill('[name=from]','01/07/2026');assert.equal(await p.locator('.p08-picker [type=submit]').isDisabled(),true);await p.fill('[name=from]','02/07/2026');await p.fill('[name=to]','01/10/2026');assert.equal(await p.locator('.p08-picker [type=submit]').isDisabled(),true);await p.fill('[name=to]','30/09/2026');assert.equal(await p.locator('.p08-picker [type=submit]').isEnabled(),true);await shot('date-bounds');await p.keyboard.press('Escape');await p.waitForTimeout(180);await a('clear').click();});
await test('Scroll retained when returning from event; keyboard tabs',async()=>{await p.locator('.p22-scroll').evaluate(e=>e.scrollTop=250);await p.locator('[data-p22-event="NFC-E001"]').focus();const top=await p.locator('.p22-scroll').evaluate(e=>e.scrollTop);await p.locator('[data-p22-event="NFC-E001"]').press('Enter');await p.waitForSelector('[data-panel="P22.S03"]');await p.goBack();await p.waitForSelector('#p22-search');assert.equal(await p.locator('.p22-scroll').evaluate(e=>e.scrollTop),top);await p.locator('[data-p22-type=all]').focus();await p.keyboard.press('ArrowRight');assert.equal((await snap()).filters.type,'Gán thẻ');await p.keyboard.press('End');assert.equal((await snap()).filters.type,'Thu hồi thẻ');});
await test('Read timeout15 seconds keeps query; duplicate retry blocked',async()=>{await p.fill('#p22-search','HN12347');await p.press('#p22-search','Enter');await p.selectOption('[data-p22-source]','timeout');assert.equal(await a('reload').isDisabled(),true);await p.waitForSelector('[data-p22=reload]:not(:disabled)',{timeout:18000});assert.equal((await snap()).source,'error');assert.equal((await snap()).filters.q,'HN12347');await shot('read-timeout');});
await test('Read completion does not steal focus from external tools',async()=>{await p.selectOption('[data-p22-source]','slow');await p.locator('[data-p22-source]').focus();await p.waitForSelector('#p22-search');assert.equal(await p.locator('[data-p22-source]').evaluate(e=>e===document.activeElement),true);});
await test('P08 dependency exact event retained; old NFC URL migrates',async()=>{await route('#p02/history-list?business=nfc&panel=2&record=NFC-B08-004');await p.waitForSelector('[data-panel="P22.S03"]');assert.match(p.url(),/event=NFC-B08-004/);assert.match(await p.locator('.p22-app').innerText(),/LS-0004/);});
await test('Hub other owners unchanged; NFC Back returns to same entry',async()=>{for(const [action,panel]of [['history-general','P08.S01'],['history-daily','P08.S04'],['documents','P08.S01'],['warranty','P23.S01'],['sessions','P23.S03']]){await route('#p02/history');await p.frameLocator('iframe').locator('[data-action="'+action+'"]').click();await p.waitForSelector('[data-screen-id="'+panel+'"]');}await route('#p02/history');await p.frameLocator('iframe').locator('[data-action=nfc]').click();await p.waitForSelector('.p22-app');await a('back').click();await p.frameLocator('iframe').locator('[data-action=nfc]').waitFor();assert.equal(await p.frameLocator('iframe').locator('[data-action=nfc]').evaluate(e=>e===e.ownerDocument.activeElement),true);});
await test('Reload new login has no retained event fixture or filters',async()=>{await p.reload();await p.waitForSelector('#username');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('.hn-intro');await route('#p02/history?scene=nfc-detail&event=NFC-E003');await p.waitForSelector('.p22-app');assert.equal((await snap()).source,'unavailable');assert.equal((await snap()).filters.q,'');});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure');fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
