const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P24/evidence/revision-03/guards';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.setDefaultTimeout(9000);p.on('pageerror',e=>errors.push(e.message));const pause=()=>p.waitForTimeout(200),shot=async name=>p.locator('.hn-screen').screenshot({path:out+'/'+name+'.png'});
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{const raw='Thời gian nguyên bản\n'+('Đặng <>& '+ 'X'.repeat(70)+'\n').repeat(25);await p.route('**/history-fixture.mjs',r=>r.fulfill({body:fs.readFileSync('docs/flows/warranty-components/history-fixture.mjs','utf8').replace('rows=[...new Map',`rows=rows.map(r=>({...r,at:${JSON.stringify(raw)}}));rows=[...new Map`),contentType:'text/javascript'}));await p.goto('http://localhost:8766/flows/auth-session/?v=p24-r03');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
await test('Context refresh waits while receipt reader open; one overlay, exact raw, return focus',async()=>{await p.evaluate(()=>location.hash='#p02/component-history?case=BH-001&sample=history');await p.waitForSelector('[data-p20-document]');await p.locator('.p20-tools').evaluate(e=>e.open=true);await p.selectOption('[data-p20-mode]','slow');await p.click('[data-p20=load]');const reader=p.getByRole('button',{name:'Xem đầy đủ thời gian xuất',exact:true}).first();await reader.click();await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.writeWarrantyCase({...m.readWarrantyCases().find(c=>c.id==='BH-001'),status:'Đã trả khách'});});await p.waitForTimeout(2000);assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok((await p.locator('.app-modal-host').innerText()).includes(raw));assert.equal(await p.locator('.app-modal-host').evaluate(e=>e.contains(document.activeElement)),true);await shot('reader-during-refresh');await p.keyboard.press('Escape');await p.waitForSelector('.p24-closed-note');assert.match(await p.locator('.p20-context').innerText(),/Đã trả khách/);assert.equal(await reader.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('[data-p20-document]').count(),2);});
await test('Closed context can become readable active context without stale disabled footer',async()=>{await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.resetWarrantyCases();location.hash='#home';});await p.evaluate(()=>location.hash='#p02/component-history?case=BH-001&sample=history');await p.waitForSelector('.p20-app');assert.equal(await p.locator('.p24-closed-note').count(),0);assert.equal(await p.locator('[data-p20=history]').count(),0);assert.equal(await p.locator('[data-p20=issue]').isVisible(),true);assert.equal(await p.locator('[data-p20=issue]').isDisabled(),false);});
await test('Min stepper keeps keyboard focus, no accidental quantity commit',async()=>{await p.locator('.p19-tools').evaluate(e=>e.open=true);await p.click('[data-p19-demo=quantity]');await p.fill('#p19-quantity','2');await p.locator('.p19-sheet [data-p19=minus]').focus();await p.keyboard.press('Enter');assert.equal(await p.inputValue('#p19-quantity'),'1');assert.equal(await p.locator('#p19-quantity').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');await pause();const s=JSON.parse(await p.locator('[data-p19-snapshot]').textContent());assert.equal(s.lines.length,1);});
await test('Shared result return never takes focus from a later user choice',async()=>{const result=await p.evaluate(async()=>{const {createWaitingResultReturn}=await import('/flows/shared/waiting-web.mjs');const root=document.createElement('section');root.innerHTML='<div class="audit-scroll" style="height:20px;overflow:auto"><div style="height:300px"></div></div><button data-audit="document">Kết quả</button><button class="later">Lựa chọn mới</button>';document.body.append(root);const state={document:{documentId:'d'},recorded:true,outcome:'recorded'},c=createWaitingResultReturn({root,namespace:'audit',getSnapshot:()=>state,isActive:()=>true});c.remember('document');c.restore({documentId:'d'});root.querySelector('.later').focus();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r))));const kept=document.activeElement===root.querySelector('.later');c.dispose();root.remove();return kept;});assert.equal(result,true);});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
