const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_FAULT_EVIDENCE_DIR||'handoff/P09/evidence/revision-03');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
const act=a=>page.locator(`[data-p09="${a}"]`).first(),pick=()=>page.locator('.p09-fault-picker'),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function choose(id){await act('fault').click();await pick().locator(`input[value="${id}"]`).click();}
async function capture(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function audit(name){const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),app=document.querySelector('.p09-app'),scroll=app.querySelector('.p09-scroll'),footer=app.querySelector('.p09-footer'),d=document.querySelector('.p09-fault-picker'),r=s.getBoundingClientRect(),dr=d?.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,font:getComputedStyle(app).fontFamily,shell:[s.offsetWidth,s.offsetHeight],pageOverflow:document.documentElement.scrollWidth>innerWidth,scrollOverflow:scroll.scrollWidth>scroll.clientWidth,footerInside:footer.getBoundingClientRect().bottom<=r.bottom+1,contentAboveFooter:scroll.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1,modalCount:document.querySelectorAll('.app-modal-host').length,dialogInside:!d||(dr.left>=r.left&&dr.right<=r.right+1&&dr.top>=r.top&&dr.bottom<=r.bottom+1),dialogOverflow:!!d&&d.scrollWidth>d.clientWidth,modalFooterInside:!d||d.querySelector('footer').getBoundingClientRect().bottom<=dr.bottom+1,fields:[...app.querySelectorAll('#p09-fault-select,.p09-intake-fields textarea')].map(e=>({name:e.name||'fault',left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right,height:e.offsetHeight,radius:getComputedStyle(e).borderRadius}))};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.pageOverflow&&!m.scrollOverflow&&!m.dialogOverflow&&m.footerInside&&m.contentAboveFooter&&m.dialogInside&&m.modalFooterInside);assert.ok(m.modalCount<=1);assert.ok(m.fields.every(f=>Math.abs(f.left-m.fields[0].left)<1&&Math.abs(f.right-m.fields[0].right)<1&&f.radius==='8px'));assert.ok(m.fields.filter(f=>f.name!=='fault').every(f=>f.height===88));metrics.push({name,...m});await capture(name);}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route=warranty]');await act('begin').click();
await check('18 searchable options; no default; accent-insensitive results and empty search state',async()=>{await act('fault').click();assert.equal(await pick().locator('input[type=radio]').count(),18);assert.equal(await pick().locator('[type=submit]').count(),0);assert.equal(await page.locator('[name=faultOther]').count(),0);assert.equal(await pick().getByRole('searchbox').evaluate(e=>e===document.activeElement),true);await pick().getByRole('searchbox').fill('nguon');assert.equal(await pick().locator('.p08-options label:visible').count(),2);await capture('search-nguon');await pick().getByRole('searchbox').fill('khong-co-tinh-trang-nay');assert.equal(await pick().locator('.p08-options label:visible').count(),0);assert.equal(await pick().locator('[data-empty]').isVisible(),true);await pick().getByRole('searchbox').fill('');await pick().locator('[data-cancel]').last().click();assert.equal((await snap()).draft.faultId,'');assert.equal(await act('fault').evaluate(e=>e===document.activeElement),true);});
await check('Standard symptom selection hides textarea; Cancel/Escape leave selection unchanged',async()=>{await choose('power-off');assert.equal(await page.locator('[name=faultOther]').count(),0);assert.equal((await snap()).draft.fault,'Máy không lên nguồn');await act('fault').click();await pick().getByRole('searchbox').fill('khac');await page.keyboard.press('Escape');assert.equal((await snap()).draft.faultId,'power-off');await page.locator('.p09-intake-fields').scrollIntoViewIfNeeded();await capture('standard-fault');});
await check('Other opens immediately; all17 standard choices hide it; reselecting the same option closes picker',async()=>{await act('fault').click();const ids=await pick().locator('input[type=radio]').evaluateAll(es=>es.map(e=>e.value).filter(v=>v!=='other'));await page.keyboard.press('Escape');assert.equal(ids.length,17);for(const id of ids){await choose('other');assert.equal(await pick().count(),0);assert.equal(await page.locator('[name=faultOther]').count(),1);await choose(id);assert.equal(await pick().count(),0);assert.equal(await page.locator('[name=faultOther]').count(),0);}await act('fault').click();await pick().locator('input[value="physical"]').click();assert.equal(await pick().count(),0);});
await check('Other reveals required text, preserves cached draft through choices and Back',async()=>{await choose('other');assert.equal(await page.locator('[name=faultOther]').isVisible(),true);assert.equal(await page.locator('[name=faultOther]').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('[name=faultOther]').getAttribute('aria-invalid'),'false');await page.fill('[name=faultOther]','   ');assert.equal(await page.locator('[name=faultOther]').getAttribute('aria-invalid'),'true');assert.match(await page.locator('#p09-fault-error').textContent(),/Mô tả/);await page.fill('[name=faultOther]','Máy có tiếng rít khi khởi động');await page.fill('[name=note]','Lỗi xuất hiện sau khi bật máy');await page.fill('[name=accessories]','Adapter nguồn, cáp USB');await choose('wifi');assert.equal(await page.locator('[name=faultOther]').count(),0);assert.equal((await snap()).draft.fault,'Không kết nối Wi-Fi');await choose('other');assert.equal(await page.locator('[name=faultOther]').inputValue(),'Máy có tiếng rít khi khởi động');await act('back').click();await act('begin').click();assert.equal(await page.locator('[name=faultOther]').inputValue(),'Máy có tiếng rít khi khởi động');assert.equal(await page.locator('[name=note]').inputValue(),'Lỗi xuất hiện sau khi bật máy');});
await check('Fault and form layout at six viewports; dialog inside app with keyboard focus trap',async()=>{for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await page.locator('[name=accessories]').evaluate(e=>e.blur());await audit(`form-${w}x${h}`);await act('fault').click();await audit(`options-${w}x${h}`);for(let i=0;i<4;i++)await page.keyboard.press('Shift+Tab');assert.equal(await pick().evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Escape');}await page.setViewportSize({width:494,height:1000});});
await check('Other whitespace invalidates CTA and forced handler cannot submit; 200-char limit and correct confirmation',async()=>{await page.click('[data-scan-action=manual]');await page.fill('#p09-code','SN-XP420B-BK-0008');await page.locator('#p09-code').press('Enter');await page.fill('[name=faultOther]','   ');assert.equal(await act('intake').isDisabled(),true);await act('intake').evaluate(e=>{e.disabled=false;e.click();});assert.equal(await page.locator('.p09-dialog').count(),0);assert.equal((await snap()).request,null);await page.fill('[name=faultOther]','z'.repeat(201));assert.equal((await page.locator('[name=faultOther]').inputValue()).length,200);await page.fill('[name=faultOther]','Máy có tiếng rít <lớn> & rung khi bật nguồn');await act('intake').click();assert.match(await page.locator('.p09-dialog').textContent(),/Máy có tiếng rít <lớn> & rung khi bật nguồn/);assert.equal(await page.locator('.p09-dialog script').count(),0);await capture('confirmation-other');await page.keyboard.press('Escape');});
await check('UNKNOWN freezes fault selection/text and reconciliation persists the correct symptom',async()=>{await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]','unknown');await act('intake').click();await page.click('.p09-dialog [type=submit]');await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const before=await snap();assert.equal(await act('fault').isDisabled(),true);assert.equal(await page.locator('[name=faultOther]').getAttribute('readonly'),'');await act('fault').evaluate(e=>{e.disabled=false;e.click();});assert.equal(await pick().count(),0);assert.deepEqual((await snap()).request,before.request);await act('reconcile').click();await page.locator('[data-panel="P09.S03"]').waitFor();assert.match(await page.locator('.p09-table').textContent(),/Máy có tiếng rít <lớn> & rung khi bật nguồn/);assert.equal((await snap()).receipt.requestId,before.request.id);});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'fault-results.json'),JSON.stringify({checks,errors,externalRequests:external,production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'fault-metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
