const auditOrigin=process.env.PREVIEW_ORIGIN||'http://127.0.0.1:8766';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.NFC_EVIDENCE_DIR||'handoff/P07/evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:494,height:1000},deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();
 const checks=[],errors=[],external=[],metrics=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(auditOrigin)&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{window.__nfcHardwareCalls=0;window.NDEFReader=class{constructor(){window.__nfcHardwareCalls++;throw Error('Hardware must not be invoked');}};});
 const act=a=>page.locator(`[data-p07="${a}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p07-snapshot]').textContent());
 const feedback=()=>page.locator('.hn-action-dialog[open]');
 async function closeFeedback(cancel=false){await page.locator('[data-action-dialog="'+(cancel||await page.locator('[data-action-dialog="cancel"]').count()?'cancel':'confirm')+'"]').click();await feedback().waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP07Feedback);}
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 async function login(){await page.goto(auditOrigin+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route="nfc"]');await page.locator('[data-panel="P07.S01"]').waitFor();await page.locator('.p07-tools > details > summary').click();}
 async function read(){await page.click('[data-p07-demo-read]');await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).busy);}
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const app=document.querySelector('.p07-app'),s=document.querySelector('.hn-screen'),scroll=app.querySelector('.p07-scroll'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,screen:{width:r.width,height:r.height},pageOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,scrollOverflow:scroll.scrollWidth>scroll.clientWidth,contentBottom:scroll.getBoundingClientRect().bottom,footerTop:app.querySelector('.p07-footer')?.getBoundingClientRect().top,navHidden:getComputedStyle(document.querySelector('.hn-nav')).display==='none',badText:[...app.querySelectorAll('dd,small,strong,h1,input')].filter(e=>e.scrollWidth>e.clientWidth+1&&getComputedStyle(e).display!=='inline').map(e=>({tag:e.tagName,text:e.textContent?.slice(0,40)}))};});metrics.push({name,...m});assert.equal(m.pageOverflow,false);assert.equal(m.scrollOverflow,false);assert.deepEqual(m.badText,[]);if(m.footerTop)assert.ok(m.contentBottom<=m.footerTop+1);}
 async function matrix(name){for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await capture(name+'-'+w+'x'+h);}await page.setViewportSize({width:494,height:1000});}
 try{
 await login();
 await check('S01 Home entry, 30 demo cards, counts30/16/9, search and tabs',async()=>{assert.equal(await page.locator('.p07-tag').count(),30);assert.match(await page.locator('.p07-tabs').textContent(),/30.*16.*9/);await matrix('P07-S01');for(const q of ['NFC-3F7D9A','Đầu in','PAPER-80','TAG-030','NFC-DEMO-020','SN-DEMO-019']){await page.fill('#p07-search',q);assert.equal(await page.locator('.p07-tag').count(),1);}await page.fill('#p07-search','');await page.click('[data-p07-tab="linked"]');assert.equal(await page.locator('.p07-tag').count(),16);await page.click('[data-p07-tab="unlinked"]');assert.equal(await page.locator('.p07-tag').count(),9);await page.locator('[data-p07-tab="unlinked"]').press('Home');assert.equal((await snap()).tab,'all');await act('filter').click();assert.match(await feedback().textContent(),/chưa có tiêu chí/);await closeFeedback();});
 await check('tag ID detail, Escape/backdrop, focus and clipboard',async()=>{await page.click('[data-p07-tag="fixture-tag-002"]');await page.locator('.p07-dialog[open]').waitFor();assert.match(await page.locator('.p07-dialog[open]').textContent(),/NFC-3F7D9A/);await act('copy').click();await page.waitForFunction(()=>document.querySelector('[data-p07=copy]')?.dataset.copied==='true');assert.equal(await act('copy').getAttribute('data-copied'),'true');assert.equal(await feedback().count(),0);assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'NFC-3F7D9A');await page.locator('#p07-detail-title').waitFor();await page.keyboard.press('Escape');await page.locator('.p07-dialog[open]').waitFor({state:'detached'});assert.equal(await page.locator('.p07-dialog[open]').count(),0);assert.equal(await page.locator('[data-p07-tag="fixture-tag-002"]').evaluate(e=>e===document.activeElement),true);});
 await check('S02 unread CTA disabled; read alone does not map or succeed',async()=>{await act('begin').click();assert.equal(await act('next').isDisabled(),true);assert.equal((await snap()).receipt,null);await matrix('P07-S02');await read();assert.equal(await act('next').isEnabled(),true);assert.equal((await snap()).stats.mutations,0);assert.equal((await snap()).panel,2);});
 await check('S03 confirm guarded; S04 only fixture receipt; same tag detail/list; duplicate submit once',async()=>{await act('next').click();await matrix('P07-S03');await act('confirm').evaluate(e=>{e.click();e.click();});await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal((await snap()).stats.mutations,1);await matrix('P07-S04');const id=(await snap()).receipt.tagId;await act('detail').click();assert.match(await page.locator('.p07-dialog[open]').textContent(),/NFC-8A2F.*Đã liên kết/);await page.keyboard.press('Escape');await act('back').click();assert.equal(await page.locator(`[data-p07-tag="${id}"]`).count(),1);await page.locator(`[data-p07-tag="${id}"]`).click();assert.match(await page.locator('.p07-dialog[open]').textContent(),/HN12345/);await act('close-detail').click();});
 await check('fresh attempt, P06 pick uses exact item ID and serial; normal P06 remains detail navigation',async()=>{await act('begin').click();assert.equal((await snap()).read,null);await act('product').click();await page.locator('[data-panel="P06.S01"]').waitFor();await page.fill('#p06-search','SN-XP420B-BK-0008');await page.click('[data-p06-item="fixture-item-HN12346"]');await page.locator('[data-panel="P07.S02"]').waitFor();assert.equal((await snap()).itemId,'fixture-item-HN12346');assert.match(await page.locator('.p07-product').textContent(),/SN-XP420B-BK-0008/);await act('back').click();await page.click('[data-tab="home"]');await page.click('.hn-scanner');await page.click('[data-p06-item="fixture-item-HN12346"]');await page.locator('[data-panel="P06.S02"]').waitFor();await page.click('[data-tab="home"]');await page.click('[data-route="nfc"]');});
 await check('unsupported/permission/read error/conflict/locked are distinct; no overwrite',async()=>{await act('begin').click();for(const [mode,reason]of [['unsupported','nfc-unsupported'],['permission','nfc-permission-denied'],['read-error','nfc-read-error']]){await page.selectOption('[data-p07-scenario]',mode);await read();assert.equal((await snap()).dependency.reason,reason);assert.equal(await act('next').isDisabled(),true);await capture('P07-'+mode);await closeFeedback();}for(const mode of ['conflict','locked']){await page.selectOption('[data-p07-scenario]',mode);await read();assert.equal(await act('next').isDisabled(),true);assert.equal((await snap()).panel,2);assert.equal((await snap()).stats.mutations,1);await capture('P07-'+mode);await closeFeedback();}assert.equal((await snap()).receipt,null);});
 await check('UNKNOWN cannot resubmit or select product; reconcile single request',async()=>{await login();await act('begin').click();await page.selectOption('[data-p07-scenario]','unknown');await read();await act('next').click();await act('confirm').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).unknown);const id=(await snap()).request.requestId;assert.equal(await act('confirm').count(),0);await capture('P07-unknown');await closeFeedback(true);await act('reconcile').click();await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,id);assert.equal((await snap()).stats.mutations,1);});
 await check('warehouse stop blocks confirm and retains UID; restores after active',async()=>{await login();await act('begin').click();await read();await act('next').click();const uid=(await snap()).read.uid;await page.locator('.p03-tools summary').click();await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await act('confirm').click();assert.match(await feedback().textContent(),/Kho tạm dừng/);await closeFeedback();assert.equal((await snap()).read.uid,uid);assert.equal((await snap()).stats.mutations,0);await page.selectOption('[data-p03-fixture="warehouse"]','active');await page.selectOption('[data-p07-scenario]','ready');await act('confirm').click();await page.locator('[data-panel="P07.S04"]').waitFor();});
 await check('native Back/Forward keeps read identity; protected success deep link does not bypass receipt',async()=>{await login();await page.evaluate(()=>location.hash='#p02/nfc?panel=4');await page.locator('[data-panel="P07.S01"]').waitFor();assert.equal((await snap()).receipt,null);await act('begin').click();await read();await act('next').click();const uid=(await snap()).read.uid;await page.goBack();await page.locator('[data-panel="P07.S02"]').waitFor();assert.equal((await snap()).read.uid,uid);await page.goForward();await page.locator('[data-panel="P07.S03"]').waitFor();assert.equal((await snap()).read.uid,uid);await act('back').click();await page.locator('[data-panel="P07.S02"]').waitFor();await act('back').click();await page.locator('[data-panel="P07.S01"]').waitFor();});
 await check('long text and internal scroll stay above footer; keyboard dialog trap/backdrop',async()=>{await act('begin').click();await read();await act('next').click();await page.setViewportSize({width:360,height:800});await page.locator('.p07-tag-hero strong').evaluate(e=>e.textContent='NFC-'+('ABCD1234'.repeat(14)));await page.locator('.p07-product small').evaluate(e=>e.textContent='SKU: '+('LONGCODE'.repeat(12))+' | SN: '+('SERIAL'.repeat(10)));await capture('P07-long-identifiers');await page.locator('.p07-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await capture('P07-scroll-end');await act('back').click();await act('back').click();await page.locator('[data-panel="P07.S01"]').waitFor();await page.click('[data-p07-tag="fixture-tag-002"]');for(let i=0;i<5;i++)await page.keyboard.press('Tab');assert.equal(await page.locator('.p07-dialog[open]').evaluate(e=>e.contains(document.activeElement)),true);await page.screenshot({path:path.join(out,'P07-detail-mobile.png')});const backdrop=await page.locator('.app-modal-host').boundingBox();await page.mouse.click(backdrop.x+2,backdrop.y+2);assert.equal(await page.locator('#p07-detail-title').count(),1);await page.keyboard.press('Escape');await page.locator('#p07-detail-title').waitFor({state:'detached'});await page.setViewportSize({width:494,height:1000});});
 await check('P03 scan tab one overlay and focus restore; logout and Back cannot restore NFC',async()=>{if((await snap()).panel!==1)await act('back').click();await page.click('[data-tab="lookup"]');await page.locator('[data-panel="P03.S01"]').waitFor();assert.equal(await page.locator('.p03-dialog').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('[data-panel="P07.S01"]').count(),1);assert.equal(await page.locator('[data-tab="lookup"]').evaluate(e=>e===document.activeElement),true);await page.locator('.hn-tools>details').first().locator('summary').click();await page.click('#hn-logout');await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p07-app').count(),0);assert.equal(await page.evaluate(()=>window.__nfcHardwareCalls),0);});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external,hardware:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));
 }catch(e){await page.screenshot({path:path.join(out,'browser-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
