const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_DETAIL_EVIDENCE_DIR||'handoff/P09/evidence/revision-06');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
const act=a=>page.locator(`[data-p09="${a}"]`).first(),tab=t=>page.locator(`[data-p09-tab="${t}"]`);
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function audit(name){const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),app=document.querySelector('.p09-app'),scroll=app.querySelector('.p09-scroll'),footer=app.querySelector('.p09-footer'),r=s.getBoundingClientRect(),controls=[...app.querySelectorAll('.p09-tabs button')],heights=controls.map(e=>e.offsetHeight),widths=controls.map(e=>e.offsetWidth);return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,font:getComputedStyle(app).fontFamily,shell:[s.offsetWidth,s.offsetHeight],overflow:scroll.scrollWidth>scroll.clientWidth,pageOverflow:document.documentElement.scrollWidth>innerWidth,footerInside:footer.getBoundingClientRect().bottom<=r.bottom+1,contentAboveFooter:scroll.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1,tabHeights:heights,tabWidths:widths,selected:controls.filter(e=>e.getAttribute('aria-selected')==='true').length,buttonOverflow:[...footer.querySelectorAll('button'),...app.querySelectorAll('.p09-component-actions button')].some(e=>e.scrollWidth>e.clientWidth),summaryLeft:app.querySelector('.p09-case-summary').getBoundingClientRect().left,tabsLeft:app.querySelector('.p09-tabs').getBoundingClientRect().left};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.overflow&&!m.pageOverflow&&!m.buttonOverflow&&m.footerInside&&m.contentAboveFooter);assert.equal(m.selected,1);assert.ok(m.tabHeights.every(h=>h>=48));assert.ok(Math.max(...m.tabWidths)-Math.min(...m.tabWidths)<=1);assert.ok(Math.abs(m.summaryLeft-m.tabsLeft)<1);metrics.push({name,...m});await shot(name);}
async function styles(selector){return page.locator(selector).evaluate(e=>{const s=getComputedStyle(e);return Object.fromEntries(['fontSize','lineHeight','color','backgroundColor','backgroundImage','borderRadius','borderBottomWidth','paddingTop','paddingBottom','boxShadow','fontWeight','minHeight'].map(k=>[k,s[k]]));});}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home:visible').waitFor();await page.evaluate(()=>location.hash='#p02/history-list?panel=2&record=LS-0001');await page.locator('.p08-detail-tabs').waitFor();const reference={active:await styles('#p08-tab-info'),inactive:await styles('#p08-tab-timeline')};await shot('history-tab-reference');await page.click('[data-tab=home]');await page.click('[data-route=warranty]');await page.click('[data-p09-case=BH-001]');
await check('Case tabs match approved P08 detail tab styles exactly, including active underline',async()=>{assert.deepEqual(await styles('#p09-tab-info'),reference.active);assert.deepEqual(await styles('#p09-tab-parts'),reference.inactive);assert.equal(await page.locator('.p09-tabs button').count(),3);assert.equal(await tab('parts').locator('.hn-tab-count').textContent(),'3');assert.equal(await tab('events').locator('.hn-tab-count').textContent(),'3');});
await check('All three tabs: six viewports, equal tab widths, stable footer, no horizontal overflow',async()=>{for(const t of ['info','parts','events']){await tab(t).click();for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=0);await tab(t).evaluate(e=>e.blur());await audit(`${t}-${w}x${h}`);}}await page.setViewportSize({width:494,height:1000});});
await check('POSTED ledger distinguishes1 document/2 codes/3 parts; pending actions disabled; footer contextual',async()=>{await tab('parts').click();assert.equal(await page.locator('.p09-document').count(),1);assert.equal(await page.locator('.p09-part').count(),2);assert.deepEqual(await page.locator('.p09-part-quantity b').allTextContents(),['1','2']);assert.match(await page.locator('.p09-section-caption').textContent(),/3 linh kiện/);assert.match(await page.locator('.p09-section-heading .p08-count-badge').textContent(),/1.*phiếu/);assert.equal(await act('issue').isDisabled(),true);assert.equal(await act('drafts').isDisabled(),true);assert.equal(await page.locator('.p09-footer [data-p09=parts]').count(),0);await act('info').click();assert.equal(await tab('info').getAttribute('aria-selected'),'true');assert.equal(await act('update').isEnabled(),true);});
await check('Keyboard tab order and sticky tabs preserve accessible content and own scroll positions',async()=>{await tab('info').press('End');assert.equal(await tab('events').getAttribute('aria-selected'),'true');await tab('events').press('ArrowLeft');assert.equal(await tab('parts').getAttribute('aria-selected'),'true');await tab('parts').press('Home');assert.equal(await tab('info').getAttribute('aria-selected'),'true');await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const old=await page.locator('.p09-scroll').evaluate(e=>e.scrollTop);assert.ok(old>0);const sticky=await page.evaluate(()=>{const t=document.querySelector('.p09-tabs').getBoundingClientRect(),s=document.querySelector('.p09-scroll').getBoundingClientRect();return t.top>=s.top-1;});assert.ok(sticky);await tab('parts').click();await tab('info').click();assert.ok(Math.abs(await page.locator('.p09-scroll').evaluate(e=>e.scrollTop)-old)<2);await shot('info-scroll-restored');});
await check('Long identifiers and model wrap without clipping or shifting footer',async()=>{await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=0);await page.locator('.p09-hero strong').evaluate(e=>e.textContent='BH-'+('LONG'.repeat(20)));await page.locator('.p09-hero b').evaluate(e=>e.textContent='Máy in nhiệt '+('XP420B'.repeat(24)));await page.locator('.p09-hero small span').evaluate(e=>e.textContent='SN-'+('ABCDEFGH'.repeat(20)));await audit('long-identifiers');await tab('parts').click();});
await check('Closed case is read-only; authored empty ledger displays zero correctly',async()=>{await act('back').click();await page.fill('#p09-query','BH-004');await page.click('[data-p09-case=BH-004]');assert.equal(await act('update').isDisabled(),true);assert.equal(await tab('parts').locator('.hn-tab-count').textContent(),'0');await tab('parts').click();assert.equal(await page.locator('.p09-document').count(),0);assert.match(await page.locator('.p09-detail-empty').textContent(),/Chưa xuất linh kiện/);assert.equal(await act('issue').isDisabled(),true);assert.match(await page.locator('.p09-readonly-note').textContent(),/Chỉ xem/);await audit('closed-no-ledger');});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'detail-results.json'),JSON.stringify({checks,reference,errors,externalRequests:external,production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'detail-metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'detail-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'detail-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
