const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.LOOKUP_UX_EVIDENCE_DIR||'handoff/P06/ux-upgrade-2026-09-29/evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),page=await b.newPage({viewport:{width:494,height:1000}}),checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-29T06:00:00Z'));
const a=n=>page.locator(`[data-p06="${n}"]`).first(),panel=n=>page.locator(`[data-panel="P06.S0${n}"]`),snap=async()=>JSON.parse(await page.locator('[data-p06-snapshot]').textContent());
const footer=()=>page.locator('.hn-nav').evaluate(el=>{const c=getComputedStyle(el),s=getComputedStyle(el.querySelector('.hn-scan-circle'));return {background:c.backgroundColor,radius:c.borderTopLeftRadius,padding:c.padding,minHeight:c.minHeight,scanWidth:s.width,scanBackground:s.backgroundColor};});let originalFooter;
async function check(name,run){await run();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function capture(name){assert.deepEqual(await footer(),originalFooter);await page.locator('.p06-app img').evaluateAll(es=>Promise.all(es.map(e=>e.decode())));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const screen=document.querySelector('.hn-screen'),r=screen.getBoundingClientRect(),scroll=document.querySelector('.p06-scroll'),dialog=screen.querySelector('dialog[open]'),d=dialog?.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],screen:[r.width,r.height],overflow:scroll.scrollWidth>scroll.clientWidth,pageOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,dialog:d?{left:d.left>=r.left-1,right:d.right<=r.right+1,top:d.top>=r.top-1,bottom:d.bottom<=r.bottom+1,overflow:dialog.scrollWidth>dialog.clientWidth}:null,nav:document.querySelector('.hn-nav').getBoundingClientRect().bottom<=r.bottom+1};});metrics.push({name,...m});assert.equal(m.overflow,false);assert.equal(m.pageOverflow,false);assert.ok(m.nav);if(m.dialog){for(const k of ['left','right','top','bottom'])assert.equal(m.dialog[k],true);assert.equal(m.dialog.overflow,false);}}
async function closeModal(){await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP06Picker);}
async function ready(){await page.waitForFunction(()=>!history.state?.hnP06Picker);}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-scanner').waitFor();originalFooter=await footer();await page.click('.hn-scanner');await panel(1).waitFor();
await check('Search count, single-result Enter and visible shortcuts',async()=>{await capture('after-list');assert.match(await page.locator('.p06-search-context').textContent(),/5 kết quả trong dữ liệu đã tải/);await page.fill('#p06-search','SN-XP420B-BK-0008');await page.locator('#p06-search').press('Enter');await panel(2).waitFor();assert.equal((await snap()).itemId,'fixture-item-HN12346');await capture('after-detail');for(const button of ['stock','history'])assert.ok((await a(button).boundingBox()).y<400);});
await check('Image dialog: loaded full image, next/previous, Back/Escape, one overlay, footer intact',async()=>{await page.click('[data-p06-image="0"]');await page.locator('.p06-large-image').evaluate(e=>e.decode());await capture('image-dialog');await page.click('[data-image-next]');assert.match(await page.locator('.p06-large-image').getAttribute('src'),/box.png/);const host=await page.locator('.app-modal-host').boundingBox();await page.mouse.click(host.x+2,host.y+2);assert.equal(await page.locator('dialog[open]').count(),1);await page.goBack();await ready();assert.equal(await page.locator('[data-p06-image="0"]').evaluate(e=>e===document.activeElement),true);assert.equal((await snap()).panel,2);await page.click('[data-p06-image="0"]');await closeModal();});
await check('Back restores query and highlights the viewed row; multiple and zero results never auto-open',async()=>{await a('back').click();await panel(1).waitFor();assert.equal(await page.locator('#p06-search').inputValue(),'SN-XP420B-BK-0008');assert.equal(await page.locator('.p06-recently-viewed').getAttribute('data-p06-item'),'fixture-item-HN12346');await page.fill('#p06-search','XP-420B');await page.locator('#p06-search').press('Enter');assert.equal((await snap()).panel,1);assert.ok(await page.locator('.p06-list [data-p06-item]').first().evaluate(e=>e===document.activeElement));await page.fill('#p06-search','does-not-exist');await page.locator('#p06-search').press('Enter');await capture('search-empty');assert.equal((await snap()).panel,1);await page.locator('.p06-clear-empty').click();assert.equal(await page.locator('.p06-card').count(),5);});
await check('IME Enter ignored and category retained on clear',async()=>{await page.click('[data-p06-category="components"]');await page.fill('#p06-search','SN-LK-0001');await page.locator('#p06-search').dispatchEvent('keydown',{key:'Enter',isComposing:true});assert.equal((await snap()).panel,1);await a('clear').click();assert.equal((await snap()).category,'components');await page.click('[data-p06-category="products"]');await page.click('.p06-list [data-p06-item="fixture-item-HN12346"]');});
await check('Shared P08 date picker, cancel/Back preserve filters and selected item',async()=>{await a('history').click();await panel(4).waitFor();await capture('after-history');const old=(await snap()).filters;await a('dates').click();assert.equal(await page.locator('.p08-picker').count(),1);await page.fill('#pick-from','03/09/2026');await closeModal();assert.deepEqual((await snap()).filters,old);await a('dates').click();await page.goBack();await ready();assert.equal((await snap()).panel,4);assert.deepEqual((await snap()).filters,old);});
await check('Shared validation blocks reversed/future ranges; Apply combines type/range; clear is outside dialog',async()=>{await a('dates').click();await page.fill('#pick-from','09/09/2026');await page.fill('#pick-to','01/09/2026');assert.equal(await page.locator('.p08-picker [type=submit]').isDisabled(),true);await capture('invalid-range');await page.fill('#pick-from','01/09/2026');await page.fill('#pick-to','30/09/2026');assert.equal(await page.locator('.p08-picker [type=submit]').isDisabled(),true);await page.fill('#pick-to','09/09/2026');await page.locator('.p08-picker input[value="warranty"]').check();await page.locator('.p08-picker [type=submit]').click();await ready();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p06-snapshot]').textContent).filters.type==='warranty');assert.equal(await page.locator('.p06-event').count(),2);await capture('active-filter');await a('clear-filters').click();assert.equal(await page.locator('.p06-event').count(),6);assert.deepEqual((await snap()).filters,{type:'all',from:'',to:''});});
await check('Empty filtered history offers reset without changing item',async()=>{await a('dates').click();await page.fill('#pick-from','29/09/2026');await page.fill('#pick-to','29/09/2026');await page.locator('.p08-picker [type=submit]').click();await ready();await page.locator('.p06-clear-empty').waitFor();await capture('history-empty');await page.locator('.p06-clear-empty').click();assert.equal((await snap()).itemId,'fixture-item-HN12346');assert.equal(await page.locator('.p06-event').count(),6);});
await check('Read error retains scoped history/list; retry does not write or infer success; Enter blocked on stale results',async()=>{await page.locator('.p06-tools summary').click();await page.selectOption('[data-p06-scenario]','read-error');assert.equal(await page.locator('.p06-event').count(),6);assert.equal(await page.locator('.p06-read-error').count(),1);await capture('history-read-error');await a('retry-read').click();assert.equal(await page.locator('.p06-read-error').count(),0);await a('back').click();await a('back').click();await panel(1).waitFor();await page.fill('#p06-search','HN12346');await page.selectOption('[data-p06-scenario]','read-error');await page.locator('#p06-search').press('Enter');assert.equal((await snap()).panel,1);await page.fill('#p06-search','HN12347');assert.equal(await page.locator('.p06-card').count(),0);await a('retry-read').click();assert.equal(await page.locator('.p06-card').count(),1);assert.equal(await page.locator('.p06-card').getAttribute('data-p06-item'),'fixture-item-HN12347');});
await check('Responsive picker/gallery, focus trapping and footer unchanged at six viewports',async()=>{await page.fill('#p06-search','HN12346');await page.locator('#p06-search').press('Enter');await panel(2).waitFor();for(const [w,h] of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.click('[data-p06-image="0"]');await capture(`image-${w}x${h}`);for(let i=0;i<8;i++)await page.keyboard.press('Tab');assert.ok(await page.locator('dialog[open]').evaluate(e=>e.contains(document.activeElement)));await closeModal();await a('history').click();await a('dates').click();await capture(`picker-${w}x${h}`);await page.click('[data-calendar="from"]');await capture(`calendar-${w}x${h}`);await closeModal();await a('back').click();await panel(2).waitFor();}await page.setViewportSize({width:494,height:1000});});
await check('Logout clears modal content and native Back cannot restore protected data',async()=>{await page.locator('.hn-tools > details').first().locator('summary').click();await page.click('#hn-logout');const confirm=page.locator('[data-action-dialog="confirm"]');if(await confirm.count())await confirm.click();else if(await page.locator('dialog[open]').count())await page.getByRole('button',{name:'Đăng xuất',exact:true}).last().click();await page.locator('#login-form').waitFor();await page.goBack();assert.equal(await page.locator('.p06-app, .p06-image-dialog').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,fixtureOnly:true,originalFooter},null,2));fs.writeFileSync(path.join(out,'metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await b.close();}})();
