const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.NOTIFICATIONS_EVIDENCE_DIR||'handoff/P13/evidence/revision-02';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true});const p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const action=a=>p.locator(`[data-p13="${a}"]`),dialog=()=>p.locator('.app-modal-host dialog');
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function route(hash){await p.evaluate(h=>location.hash=h,hash);await p.waitForFunction(h=>location.hash===h&&!!document.querySelector('.p13-app'),hash);await p.waitForTimeout(70);}
async function scenario(v){await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-scenario',v);await p.evaluate(()=>scrollTo(0,0));}
try{
await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');try{await p.locator('#username').waitFor({timeout:30000});}catch(e){if(await p.locator('#preview-startup-status').isVisible())throw e;console.log('Preview module startup pending; reload once before any login action');await p.reload();await p.locator('#username').waitFor({timeout:30000});}await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await p.locator('.p13-app').waitFor();await p.locator('[data-p13-loaded=true]').waitFor();
await check('A01 Home bell reaches S01; unread filter backed by three events',async()=>{assert.equal(await p.locator('.p13-notification').count(),3);assert.equal(await p.locator('[data-p13-filter=unread]').getAttribute('aria-pressed'),'true');await shot('P13-S01');});
await check('A03 Notification resolves exact P12 ID, read acknowledgment updates shared badge',async()=>{await p.click('[data-p13-event=p13-event-inbound]');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));assert.ok((await p.locator('.p13-summary').textContent()).includes('PN-0005'));await shot('P13-S02');await action('document').click();await p.locator('.p12-app').waitFor();assert.ok(p.url().includes('doc=fixture-inbound-0005'));await p.goBack();await p.locator('[data-panel="P13.S02"]').waitFor();await action('back').click();await p.locator('[data-panel="P13.S01"]').waitFor();assert.equal(await p.locator('.p13-notification').count(),2);assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');});
await check('A05 Mark-read failure keeps event/count/filter and reports in modal',async()=>{await scenario('read-error');await p.click('[data-p13-event=p13-event-warehouse]');await dialog().waitFor();assert.ok((await dialog().textContent()).includes('Chưa đánh dấu'));assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');assert.equal(await p.locator('.app-modal-host').count(),1);await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await shot('mark-read-error');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await action('back').click();await p.locator('[data-panel="P13.S01"]').waitFor();assert.equal(await p.locator('.p13-notification').count(),2);assert.equal(await p.locator('[data-p13-filter=unread]').getAttribute('aria-pressed'),'true');await scenario('ready');});
await check('A05 All filter retains read/unread events; load-error retry retains filter',async()=>{await p.click('[data-p13-filter=all]');await p.locator('[data-p13-loaded=true]').waitFor();assert.equal(await p.locator('.p13-notification').count(),5);for(const state of ['loading','empty','error']){await scenario(state);assert.equal(await p.locator('.p13-notification').count(),0);await shot('state-'+state);}await action('retry').click();assert.equal(await p.locator('.p13-notification').count(),5);assert.equal(await p.locator('[data-p13-filter=all]').getAttribute('aria-pressed'),'true');});
await check('A01/A02 S03 lists only scoped waiting stock documents; filter and Back survive',async()=>{await p.click('[data-p13-event=p13-event-inbound]');await action('waiting').click();assert.equal(await p.locator('.p13-waiting-record').count(),5);await shot('P13-S03');await p.click('[data-p13-type=inbound]');assert.equal(await p.locator('.p13-waiting-record').count(),3);await p.click('[data-p13-doc=fixture-inbound-0005]');await p.locator('[data-panel="P13.S04"]').waitFor();assert.deepEqual(await p.locator('.p13-lines tbody tr td:nth-child(2)').allTextContents(),['5','4','2']);await shot('P13-S04');assert.equal(await p.locator('.p13-app button').filter({hasText:/^(Duyệt|Từ chối|Ghi sổ)$/}).count(),0);assert.equal(await p.locator('.p13-app textarea').count(),0);});
await check('A04 Web guidance without fabricated URL; keyboard/backdrop/Back/focus',async()=>{await action('web').click();await dialog().waitFor();assert.ok((await dialog().textContent()).includes('Chưa có URL'));assert.equal(await dialog().locator('a').count(),0);assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert));await p.keyboard.press('Shift+Tab');assert.ok(await dialog().evaluate(d=>d.contains(document.activeElement)));await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await shot('web-guidance');await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-panel="P13.S04"]').count(),1);assert.ok(await action('web').evaluate(e=>e===document.activeElement));});
await check('P13 product CTA opens P12 S03 exact ID and Back restores waiting filter',async()=>{await action('products').click();await p.locator('[data-panel="P12.S03"]').waitFor();assert.ok(p.url().includes('fixture-inbound-0005'));assert.deepEqual(await p.locator('.p12-qty strong').allTextContents(),['5','4','2']);await p.goBack();await p.locator('[data-panel="P13.S04"]').waitFor();await action('back').click();await p.locator('[data-panel="P13.S03"]').waitFor();assert.equal(await p.locator('[data-p13-type=inbound]').getAttribute('aria-pressed'),'true');});
await check('A03 Missing/cross-scope ID exposes no document action',async()=>{await route('#p02/notifications?panel=4&doc=PN-0005');assert.ok((await p.locator('.p13-app').textContent()).includes('Không tìm thấy'));assert.equal(await action('document').count(),0);await route('#p02/notifications?panel=2&event=missing');assert.equal(await action('document').count(),0);});
await check('Four panels fit locked shell and footer across six viewports',async()=>{for(const panel of [1,2,3,4]){await route(`#p02/notifications?panel=${panel}${panel===2?'&event=p13-event-inbound':panel===4?'&doc=fixture-inbound-0005':''}`);for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(40);const m=await p.evaluate(()=>{const shell=document.querySelector('.hn-screen'),s=document.querySelector('.p13-scroll'),r=shell.getBoundingClientRect();return {panel:document.querySelector('.p13-app').dataset.panel,viewport:[innerWidth,innerHeight],shell:[shell.offsetWidth,shell.offsetHeight],width:s.clientWidth,scrollWidth:s.scrollWidth,height:s.clientHeight,scrollHeight:s.scrollHeight,within:r.width<=innerWidth+1&&r.height<=innerHeight+1,footer:getComputedStyle(document.querySelector('.hn-nav')).display};});assert.deepEqual(m.shell,[494,950]);assert.equal(m.width,m.scrollWidth,JSON.stringify(m));assert.ok(m.within);assert.notEqual(m.footer,'none','User r05: all four P13 panels retain navigation');metrics.push(m);await shot(`S0${panel}-${width}x${height}`);}}await p.setViewportSize({width:494,height:950});});
await check('Readable note 250/2000 Unicode/newlines/unbroken preserved; dialog Back restores',async()=>{for(const text of ['Ghi chú kiểm tra dài. '.repeat(15),'Tiếng Việt 🌸\n\n'+('Nội_dung_không_mất_'.repeat(125))]){await p.evaluate(async text=>{const m=await import('/flows/documents/document-model.mjs');m.DOCUMENTS.find(d=>d.id==='fixture-inbound-0005').note=text;},text);await route('#p02/notifications?panel=3');await route('#p02/notifications?panel=4&doc=fixture-inbound-0005');const more=p.locator('.p13-app [data-hn-read-trigger]:visible');await more.waitFor({state:'visible'});await more.click();await dialog().waitFor();assert.equal(await dialog().locator('.app-modal-body').textContent(),text);assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Tab');assert.ok(await dialog().evaluate(d=>d.contains(document.activeElement)));await shot(text.length>2000?'reader-2000':'reader-250');await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-panel="P13.S04"]').count(),1);assert.ok(await more.evaluate(e=>e===document.activeElement));} });
await check('Waiting list scroll restored and header/footer remain fixed',async()=>{await route('#p02/notifications?panel=3');await p.click('[data-p13-type=all]');const yHeader=await p.locator('.p13-header').evaluate(e=>e.getBoundingClientRect().top),yNav=await p.locator('.hn-nav').evaluate(e=>e.getBoundingClientRect().top);await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=250);const top=await p.locator('.p13-scroll').evaluate(e=>e.scrollTop);assert.ok(top>0);assert.equal(await p.locator('.p13-header').evaluate(e=>e.getBoundingClientRect().top),yHeader);assert.equal(await p.locator('.hn-nav').evaluate(e=>e.getBoundingClientRect().top),yNav);await p.locator('[data-p13-doc]').first().dispatchEvent('click');await p.goBack();await p.locator('[data-panel="P13.S03"]').waitFor();assert.equal(await p.locator('.p13-scroll').evaluate(e=>e.scrollTop),top);});
await check('Home/P03/P13 share locked footer; scan cancel restores P13 and all-read hides badge',async()=>{const paint=()=>p.locator('.hn-nav').evaluate(n=>{const c=n.querySelector('.hn-scan-circle'),s=n.querySelector('[aria-current=page]'),a=getComputedStyle(n),b=getComputedStyle(c),d=getComputedStyle(s);return [a.backgroundColor,a.borderRadius,a.minHeight,a.padding,b.width,b.height,b.backgroundColor,b.borderTopWidth,d.backgroundColor,d.color];});const expected=['rgba(255, 255, 255, 0.98)','23px 23px 0px 0px','75px','8px','62px','62px','rgb(0, 115, 153)','3px','rgb(238, 249, 251)','rgb(0, 85, 119)'];assert.deepEqual(await paint(),expected);await p.click('[data-tab=lookup]');await p.locator('.p03-dialog').waitFor();assert.deepEqual(await paint(),expected);await p.keyboard.press('Escape');await p.locator('.p13-app').waitFor({state:'visible'});assert.deepEqual(await paint(),expected);await route('#p02/notifications?panel=2&event=p13-event-warehouse');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));await route('#p02/notifications?panel=2&event=p13-event-warranty');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home').waitFor({state:'visible'});assert.deepEqual(await paint(),expected);assert.equal(await p.locator('.hn-bell .hn-count').isVisible(),false);await p.click('.hn-bell');await p.click('[data-p13-filter=unread]');assert.equal(await p.locator('.p13-notification').count(),0);assert.ok((await p.locator('.p13-empty').textContent()).includes('chưa đọc'));});
await check('Late mark-read receipt after fast Back updates list and badge together',async()=>{await p.reload();await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await p.click('[data-p13-event=p13-event-inbound]');await action('back').click();await p.locator('[data-panel="P13.S01"]').waitFor();await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===2);assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),'Chưa đọc (2)');});
await check('Logout then Back cannot restore notifications',async()=>{await p.locator('.hn-tools details').first().evaluate(e=>e.open=true);await p.click('#hn-logout');await p.locator('#username').waitFor();await p.goBack();assert.equal(await p.locator('.p13-app').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(`${checks.length} groups PASS`);
}catch(e){fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
