const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const origin=process.env.PREVIEW_ORIGIN||'http://127.0.0.1:8766';
const out=path.resolve(process.env.SYNC_P0607_EVIDENCE_DIR||'handoff/dialog-sync-2026-09-28/p06-p07');fs.mkdirSync(out,{recursive:true});
const viewports=[[1869,940],[1495,752],[685,872],[494,1000],[360,800],[340,420]];
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[],metrics=[];
 page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-28T06:00:00Z'));
 const p6=a=>page.locator(`[data-p06="${a}"]`).first(),p7=a=>page.locator(`[data-p07="${a}"]`).first();
 const feedback=()=>page.locator('.hn-action-dialog[open]');
 const snap=()=>page.locator('[data-p07-snapshot]').evaluate(e=>JSON.parse(e.textContent));
 const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
 const settle=()=>page.waitForFunction(()=>!history.state?.hnP06Feedback&&!history.state?.hnP07Feedback);
 const close=async()=>{await page.locator('[data-action-dialog="confirm"]').click();await feedback().waitFor({state:'detached'});await settle();};
 const read=async()=>{await page.click('[data-p07-demo-read]');await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).busy);};
 async function matrix(prefix,short=false){
  for(const [width,height]of viewports){
   await page.setViewportSize({width,height});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForTimeout(100);
   const m=await page.locator(`[data-panel="${prefix}"]`).evaluate(app=>{const s=app.querySelector('.p06-scroll,.p07-scroll'),screen=app.closest('.hn-screen'),r=screen.getBoundingClientRect(),fixed=[app.querySelector('header'),app.querySelector('footer'),screen.querySelector('.hn-nav')].filter(Boolean);return {width:innerWidth,height:innerHeight,clientHeight:s.clientHeight,scrollHeight:s.scrollHeight,scrollWidth:s.scrollWidth,clientWidth:s.clientWidth,outerOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,screen:{left:r.left,right:r.right,top:r.top,bottom:r.bottom},fixed:fixed.map(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom}))};});
   assert.equal(m.outerOverflow,false,JSON.stringify(m));assert.ok(m.scrollWidth<=m.clientWidth+1,prefix+' horizontal');if(short)assert.ok(m.scrollHeight<=m.clientHeight+1,prefix+' no short-page scroll');
   await page.locator(`.${prefix.startsWith('P06')?'p06':'p07'}-scroll`).hover();await page.mouse.wheel(0,800);await page.waitForTimeout(40);
   const fixed=await page.locator(`[data-panel="${prefix}"]`).evaluate(app=>[app.querySelector('header'),app.querySelector('footer'),app.closest('.hn-screen').querySelector('.hn-nav')].filter(Boolean).map(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom})));
   assert.deepEqual(fixed,m.fixed,prefix+' stable header/footer/nav');metrics.push({panel:prefix,...m});
   await page.locator(`.${prefix.startsWith('P06')?'p06':'p07'}-scroll`).evaluate(e=>e.scrollTop=0);
   await page.locator('.hn-screen').screenshot({path:path.join(out,`${prefix}-${width}x${height}.png`)});
  }
  await page.setViewportSize({width:494,height:1000});
 }
 async function modalContract(name,restore){
  await feedback().waitFor();assert.equal(await page.locator('.app-modal-host').count(),1);assert.equal(await feedback().getAttribute('aria-modal'),'true');
  assert.equal(await page.locator('.hn-tools').evaluate(e=>e.inert),true);
  const initial=await feedback().locator('button').first().evaluate(e=>document.activeElement===e);assert.equal(initial,true);
  await page.keyboard.press('Shift+Tab');assert.equal(await feedback().evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Tab');
  const current=await page.locator('.p06-scroll,.p07-scroll').evaluate(e=>e.scrollTop);const host=page.locator('.app-modal-host');await host.click({position:{x:2,y:2}});assert.equal(await feedback().count(),1);await host.hover({position:{x:2,y:2}});await page.mouse.wheel(0,500);assert.equal(await page.locator('.p06-scroll,.p07-scroll').evaluate(e=>e.scrollTop),current);
  for(const [width,height]of viewports){await page.setViewportSize({width,height});const contained=await feedback().evaluate(e=>{const d=e.getBoundingClientRect(),s=e.closest('.hn-screen').getBoundingClientRect();return d.left>=s.left-1&&d.right<=s.right+1&&d.top>=s.top-1&&d.bottom<=s.bottom+1;});assert.equal(contained,true,name+' viewport containment');}
  await page.setViewportSize({width:494,height:1000});await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});
  await page.keyboard.press('Escape');await feedback().waitFor({state:'detached'});await settle();if(restore)assert.equal(await restore.evaluate(e=>document.activeElement===e),true);
 }
 try{
  await page.goto(origin+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('.hn-scanner');
  await check('P06 four IDs, six viewports, stable header/nav and readable long content',async()=>{await matrix('P06.S01');await page.click('[data-p06-item="fixture-item-HN12345"]');await matrix('P06.S02');await p6('stock').click();await matrix('P06.S03',true);await p6('back').click();await p6('history').click();await matrix('P06.S04');await p6('back').click();await p6('back').click();});
  await check('P06 feedback dialog backdrop, focus trap, six viewport containment, Escape focus restore',async()=>{await p6('filter').click();assert.match(await feedback().textContent(),/chưa có tiêu chí/);assert.equal(await page.locator('.p06-feedback').count(),0);await modalContract('P06-filter-dialog',p6('filter'));});
  await check('P06 native Back closes dialog without losing query/category/scroll',async()=>{await page.fill('#p06-search','XP-420B');await p6('filter').click();const before=await page.evaluate(()=>location.hash);await page.goBack();await feedback().waitFor({state:'detached'});assert.equal(await page.evaluate(()=>location.hash),before);assert.equal(await page.locator('#p06-search').inputValue(),'XP-420B');await p6('clear').click();});
  await check('P06 missing serial and blocked document use dialog; range validation stays at field',async()=>{await page.click('[data-p06-item="fixture-item-HN12345"]');await p6('warranty').click();assert.match(await feedback().textContent(),/chưa có serial/);await close();await p6('history').click();await p6('dates').click();await page.fill('#pick-from','09/09/2026');await page.fill('#pick-to','01/09/2026');assert.equal(await page.locator('.p08-picker [type=submit]').isDisabled(),true);assert.equal(await page.locator('#pick-from-error').isVisible(),true);assert.equal(await feedback().count(),0);await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP06Picker);await page.locator('.p06-event').first().click();assert.match(await feedback().textContent(),/Chưa xác nhận quyền/);await close();});
  await page.click('[data-tab="home"]');await page.click('[data-route="nfc"]');
  await check('P07 list, read, verify, confirmed result preserve four IDs and fit six viewports',async()=>{await matrix('P07.S01');await p7('begin').click();await matrix('P07.S02',true);await read();await p7('next').click();await matrix('P07.S03');await p7('confirm').click();await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal(await feedback().count(),0);await matrix('P07.S04',true);});
  await check('P07 copy result replaces detail without stacking; returns to same detail; Back consumes rich dialog',async()=>{await p7('detail').click();await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{}}}));await page.locator('.p07-dialog:not(.hn-action-dialog) [data-p07="copy"]').click();assert.match(await feedback().textContent(),/Đã sao chép/);assert.equal(await page.locator('.app-modal-host').count(),1);assert.equal(await page.locator('[data-p07-copy-feedback]').count(),0);await page.locator('.hn-screen').screenshot({path:path.join(out,'P07-copy-success.png')});await close();await page.locator('#p07-detail-title').waitFor();assert.match(await page.locator('#p07-detail-title').textContent(),/Thông tin thẻ/);await page.goBack();await page.locator('#p07-detail-title').waitFor({state:'detached'});await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal(await p7('detail').evaluate(e=>document.activeElement===e),true);});
  await check('P07 denied clipboard result remains modal and supports retry',async()=>{await p7('detail').click();await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));await page.locator('.p07-dialog:not(.hn-action-dialog) [data-p07="copy"]').click();assert.match(await feedback().textContent(),/Không thể sao chép/);await close();await page.locator('#p07-detail-title').waitFor();await page.keyboard.press('Escape');await page.locator('#p07-detail-title').waitFor({state:'detached'});});
  await check('P07 permission failure is dialog, background scroll unchanged, no message banner',async()=>{await p7('new-link').click();await page.locator('.p07-tools>details>summary').click();await page.selectOption('[data-p07-scenario]','permission');await read();assert.match(await feedback().textContent(),/từ chối/);assert.equal(await page.locator('.p07-feedback').count(),0);await modalContract('P07-permission-dialog');});
  await check('P07 UNKNOWN cancel preserves exact request; footer reconcile produces verified S04 only once',async()=>{await page.selectOption('[data-p07-scenario]','unknown');await read();await p7('next').click();await p7('confirm').click();await feedback().waitFor();const before=await snap();assert.equal(before.unknown,true);assert.equal(await page.locator('[data-action-dialog="cancel"]').textContent(),'Để sau');await page.locator('[data-action-dialog="cancel"]').click();await settle();assert.deepEqual((await snap()).request,before.request);assert.equal((await snap()).stats.mutations,before.stats.mutations);assert.equal(await p7('confirm').count(),0);await p7('reconcile').click();await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,before.request.requestId);assert.equal(await feedback().count(),0);});
  await check('P07 UNKNOWN direct dialog action reconciles once and keeps request identity',async()=>{await p7('new-link').click();await page.selectOption('[data-p07-scenario]','unknown');await read();await p7('next').click();await p7('confirm').click();await feedback().waitFor();const request=(await snap()).request;await page.locator('.hn-screen').screenshot({path:path.join(out,'P07-unknown-dialog.png')});await page.locator('[data-action-dialog="confirm"]').dblclick();await page.locator('[data-panel="P07.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,request.requestId);assert.equal(await feedback().count(),0);});
  await check('NFC product picker keeps a static instruction and returns exact item without a notification overlay',async()=>{await p7('new-link').click();await p7('product').click();await page.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await page.locator('.p06-selection-hint').isVisible(),true);assert.equal(await feedback().count(),0);await page.click('[data-p06-item="fixture-item-HN12346"]');await page.locator('[data-panel="P07.S02"]').waitFor();assert.equal((await snap()).itemId,'fixture-item-HN12346');assert.equal((await snap()).read,null);});
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,metrics,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}
})();
