const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=process.env.FINAL_URL||'http://127.0.0.1:8766/review/';
const phase=process.env.UX_PHASE||'before',out=path.resolve('handoff/ux-audit-2026-10-01/'+phase);
const expectedBuild=JSON.parse(fs.readFileSync('docs/review/catalog.json')).build;
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch(),checks=[];
 async function check(name,run){
  const context=await browser.newContext({viewport:{width:1440,height:950},permissions:['clipboard-read','clipboard-write']});
  const page=await context.newPage(),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
  await context.tracing.start({screenshots:true,snapshots:true});
  try{await run(page);assert.deepEqual(errors,[]);checks.push({name,status:'PASS'});}catch(e){checks.push({name,status:'FAIL',error:e.message,errors});}
  await page.screenshot({path:path.join(out,name+'.png')}).catch(()=>{});
  await context.tracing.stop({path:path.join(out,name+'.zip')});await context.close();
  fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({base,phase,expectedBuild,checks},null,2));console.log(checks.at(-1));
 }
 const ready=(p,id)=>p.waitForFunction(id=>document.querySelector('#status')?.textContent.startsWith('Đã mở '+id),id,{timeout:55000});
 const open=async(p,id='P04.S02')=>{await p.goto(base+'?view=review&flow=closed&panel='+id);await ready(p,id);assert.ok((await p.locator('#build').textContent()).includes(expectedBuild),'Served build must match the audited source');};
 const frame=p=>p.frames().find(f=>f.url().includes('/auth-session/'));
 const snap=p=>frame(p).locator('[data-p04-snapshot]').textContent().then(JSON.parse);
 await check('01-live-link-context',async p=>{await open(p);await frame(p).locator('[data-p04=next]').first().click();await frame(p).locator('[data-panel="P04.S03"]').waitFor();await p.click('#copy');const link=await p.evaluate(()=>navigator.clipboard.readText());assert.equal(new URL(link).searchParams.get('panel'),'P04.S03');await p.click('#bug');assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/Panel: P04.S03/);});
 await check('02-pending-scenario-not-applied',async p=>{await open(p);await p.selectOption('#scenario','other-user');await p.click('#copy');assert.equal(new URL(await p.evaluate(()=>navigator.clipboard.readText())).searchParams.get('scenario'),'default');});
 await check('03-mode-switch-preserves-draft',async p=>{await open(p);const original=await snap(p);const token=await frame(p).evaluate(()=>window.auditToken=crypto.randomUUID());await p.click('#app-link');assert.equal(await frame(p).evaluate(()=>window.auditToken),token);assert.deepEqual((await snap(p)).accepted,original.accepted);await p.click('#review-link');assert.equal(await frame(p).evaluate(()=>window.auditToken),token);});
 await check('04-mobile-drawer-keyboard',async p=>{await p.setViewportSize({width:360,height:800});await open(p);await p.click('#toggle');assert.equal(await p.locator('main').evaluate(e=>e.inert),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#controls').isVisible(),false);assert.equal(await p.evaluate(()=>document.activeElement.id),'toggle');assert.equal(await p.locator('main').evaluate(e=>e.inert),false);});
 await check('05-load-controls-locked',async p=>{await open(p);await p.route('**/runtime/flows/auth-session/?*',async route=>{await new Promise(r=>setTimeout(r,650));await route.continue();});await p.click('#next');await p.locator('#confirm [value=reset]').click();assert.equal(await p.locator('#scenario').isDisabled(),true);assert.equal(await p.locator('#board').isDisabled(),true);await ready(p,'P04.S03');assert.equal(await p.locator('#scenario').isDisabled(),false);});
 await check('06-reload-cross-board-follow',async p=>{await open(p);await p.click('#flow-toggle');for(const id of ['P09.S03','P04.S02']){await p.selectOption('#board',id.slice(0,3));await p.selectOption('#panel',id);await p.click('#launch');await p.locator('#confirm [value=reset]').click();await ready(p,id);}await frame(p).evaluate(()=>location.hash='#p02/warranty');await frame(p).locator('.p09-app').waitFor();await p.waitForFunction(()=>document.querySelector('#flow-board').value==='P09');});
 await check('07-image-retry',async p=>{let blocked=true;await p.route('**/P04_User_Flow.png',r=>blocked?r.abort():r.continue());await open(p);await p.click('#flow-toggle');await p.waitForFunction(()=>document.querySelector('#flow-message').textContent.includes('Chưa tải'));blocked=false;await p.locator('#flow-retry').click();await p.waitForFunction(()=>{const i=document.querySelector('#flow-image');return i.complete&&i.naturalWidth>0&&!i.hidden;});});
 await check('08-cancel-rapid-launch',async p=>{await open(p);const original=await snap(p);await p.evaluate(()=>{document.querySelector('#next').click();document.querySelector('#previous').click();});await p.keyboard.press('Escape');await p.waitForTimeout(250);assert.equal(await p.locator('#confirm').evaluate(e=>e.open),false);assert.deepEqual((await snap(p)).accepted,original.accepted);assert.equal(await p.locator('#launch').isDisabled(),false);});
 await check('09-landscape-diagram-space',async p=>{await p.setViewportSize({width:640,height:360});await open(p,'P01.S01');await p.click('#flow-toggle');await p.waitForFunction(()=>document.querySelector('#flow-image').naturalWidth>0);assert.ok(await p.locator('#flow-viewport').evaluate(e=>e.clientHeight>=80),'Diagram viewport must remain usable on a short screen');await p.locator('#flow-download').scrollIntoViewIfNeeded();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);});
 await check('10-mobile-focus-cycle',async p=>{await p.setViewportSize({width:390,height:800});await open(p,'P01.S01');await p.click('#toggle');await p.locator('#board').focus();for(let i=0;i<24;i++){await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.querySelector('#controls').contains(document.activeElement)),true);}await p.setViewportSize({width:1440,height:950});assert.equal(await p.locator('main').evaluate(e=>e.inert),false);});
 await check('11-cancel-target-keeps-applied-context',async p=>{await open(p);await p.selectOption('#board','P09');await p.selectOption('#scenario','other-user');await p.click('#launch');await p.keyboard.press('Escape');await p.click('#copy');const link=new URL(await p.evaluate(()=>navigator.clipboard.readText()));assert.equal(link.searchParams.get('panel'),'P04.S02');assert.equal(link.searchParams.get('scenario'),'default');assert.equal((await snap(p)).accepted.length,11);});
 await check('12-closed-diagram-refresh-keeps-selection',async p=>{await open(p,'P01.S01');await p.click('#flow-toggle');await p.selectOption('#flow-board','P00');await p.click('#flow-data');await p.click('#flow-close');await p.reload();await ready(p,'P01.S01');await p.click('#flow-toggle');assert.equal(await p.inputValue('#flow-board'),'P00');assert.equal(await p.locator('#flow-data').getAttribute('aria-selected'),'true');assert.equal(await p.locator('#flow-follow').isChecked(),false);assert.equal(await p.locator('#flow-user').getAttribute('tabindex'),'-1');});
 await check('13-runtime-failure-releases-controls',async p=>{await open(p);let fail=true;await p.route('**/runtime/flows/auth-session/?*',route=>fail?route.abort():route.continue());await p.click('#launch');await p.locator('#confirm [value=reset]').click();await p.waitForFunction(()=>!document.querySelector('#launch').disabled,null,{timeout:22000});fail=false;await p.click('#launch');await p.locator('#confirm [value=reset]').click();await ready(p,'P04.S02');assert.equal((await snap(p)).accepted.length,11);});
 await browser.close();process.exitCode=checks.some(c=>c.status==='FAIL')?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
