const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),out='handoff/P23/evidence/revision-03/guards';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
await p.route('**/warranty-session-fixture.mjs',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text()).replace("if(mode==='unavailable')","globalThis.__reads=(globalThis.__reads||0)+1; if(globalThis.__override)return globalThis.__override; if(mode==='unavailable')")});});
const a=k=>p.locator(`[data-p23=${k}]`),shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});
async function route(scene,id){await p.evaluate(({scene,id})=>location.hash='#p02/history?'+new URLSearchParams({scene,...(id?{[scene==='warranty-detail'?'case':'session']:id}:{})}),{scene,id});await p.waitForSelector('.p23-app');await p.waitForTimeout(100);}
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p23-r03-guards');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await route('sessions');await p.selectOption('[data-p23-source]','long');await route('session-detail','PQ-0003');
await test('Busy reload keeps focus but blocks repeated mouse/keyboard activation',async()=>{await p.selectOption('[data-p23-outcome]','slow');const n=await p.evaluate(()=>window.__reads);await a('reload').click();assert.equal(await a('reload').getAttribute('aria-disabled'),'true');await a('reload').evaluate(e=>{e.click();e.click();});await p.keyboard.press('Enter');await p.waitForSelector('[data-p23=reload]:not([aria-disabled=true])');assert.equal(await p.evaluate(()=>window.__reads),n+1);assert.equal(await a('reload').evaluate(e=>e===document.activeElement),true);});
await test('Read completion never takes newer focus outside P23',async()=>{await a('reload').click();await p.locator('[data-p23-outcome]').focus();await p.waitForTimeout(850);assert.equal(await p.locator('[data-p23-outcome]').evaluate(e=>e===document.activeElement),true);});
await test('Removed event reader falls back safely and retains new source truth',async()=>{await p.evaluate(async()=>{window.__override=(await import('../history/warranty-session-fixture.mjs')).sessionFixture('fixture-hoa-nam','long');window.__override.items[0].events=[];});await a('reload').click();await p.getByRole('button',{name:'Xem đầy đủ mã gốc',exact:true}).focus();await p.waitForTimeout(900);assert.equal(await p.locator('.p23-app h1').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.p23-code').count(),0);await shot('removed-event');});
await test('Ten additional long-heading/long-ID layouts and full raw reader',async()=>{await p.evaluate(async()=>{const m=await import('../shared/warranty-cases.mjs');m.writeWarrantyCase({...m.readWarrantyCases()[0],id:'BH-LONG',events:[{id:'raw',label:'S'.repeat(260),day:'2026-09-10',time:'T'.repeat(260),actor:' A<>&🌸\n'.repeat(250),description:'N'.repeat(2000)}]});m.writeWarrantyCase({...m.readWarrantyCases()[0],id:'BH-'+('X'.repeat(300)),model:'M'.repeat(300),serial:'Z'.repeat(300),status:'Đang kiểm tra'});});const layouts=[];for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const scene of ['warranty','warranty-detail']){await route(scene,scene==='warranty-detail'?'BH-LONG':null);const m=await p.locator('.hn-screen').evaluate(e=>{const app=e.querySelector('.p23-app'),s=e.querySelector('.p23-scroll'),f=e.querySelector('.p23-footer');return {w:e.offsetWidth,h:e.offsetHeight,overflow:s.scrollWidth>s.clientWidth+1||app.scrollWidth>app.clientWidth+1,small:[...app.querySelectorAll('button')].filter(b=>b.getClientRects().length&&(b.offsetHeight<44||b.offsetWidth<44)).length,footer:f.getBoundingClientRect().bottom<=e.getBoundingClientRect().bottom+1};});assert.equal(m.w,494);assert.equal(m.h,950);assert.equal(m.overflow,false);assert.equal(m.small,0);assert.equal(m.footer,true);layouts.push({viewport:[width,height],scene,...m});await shot(scene+'-'+width);}}fs.writeFileSync(out+'/layout.json',JSON.stringify(layouts,null,2));await p.setViewportSize({width:494,height:950});await route('warranty-detail','BH-LONG');for(const [label,raw]of [['sự kiện','S'.repeat(260)],['thời gian sự kiện','10/09/2026 · '+'T'.repeat(260)]]){const reader=p.getByRole('button',{name:'Xem đầy đủ '+label,exact:true});await reader.click();assert.ok((await p.locator('.hn-action-dialog[open]').textContent()).includes(raw));await p.keyboard.press('Escape');await p.waitForTimeout(150);assert.equal(await reader.evaluate(e=>e===document.activeElement),true);}await shot('long-readers');});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
