const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.HISTORY_EVIDENCE_DIR||'handoff/P08/evidence/revision-02');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),ctx=await browser.newContext({viewport:{width:494,height:1000},deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']}),page=await ctx.newPage();
 const checks=[],metrics=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
 const act=x=>page.locator(`[data-p08="${x}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p08-snapshot]').textContent());
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 async function panel(n){await page.click(`[data-p08-preview="${n}"]`);await page.locator(`[data-panel="P08.S0${n}"]`).waitFor();await page.locator('.p08-scroll').evaluate(e=>e.scrollTop=0);}
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),app=document.querySelector('.p08-app'),scroll=app.querySelector('.p08-scroll'),nav=s.querySelector('.hn-nav'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,css:[s.offsetWidth,s.offsetHeight],bounds:[r.width,r.height],pageOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,scrollOverflow:scroll.scrollWidth>scroll.clientWidth+1,scrollbar:getComputedStyle(scroll).scrollbarWidth,contentBottom:scroll.getBoundingClientRect().bottom,navTop:nav.getBoundingClientRect().top,bad:[...app.querySelectorAll('strong,small,dd,input,button')].filter(e=>getComputedStyle(e).display!=='inline'&&e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,text:e.textContent.slice(0,40)}))};});metrics.push({name,...m});assert.deepEqual(m.css,[494,950]);assert.equal(m.pageOverflow,false);assert.equal(m.scrollOverflow,false);assert.ok(m.contentBottom<=m.navTop+1);assert.equal(m.scrollbar,'none');assert.deepEqual(m.bad,[]);}
 try{
 await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');
 await check('Home remains P22 hub; P08 is subview; history nav active',async()=>{await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="history-general"]').click();await page.locator('[data-panel="P08.S01"]').waitFor();assert.equal(await page.locator('[data-tab="history"]').getAttribute('aria-current'),'page');assert.equal(await page.locator('.p08-row').count(),6);});
 await check('4 panels at 6 viewports: shell, no overflow, internal scroll and fixed nav',async()=>{for(let p=1;p<=4;p++){await panel(p);for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await capture(`P08-S0${p}-${w}x${h}`);}await page.setViewportSize({width:494,height:1000});}});
 await check('A01 query/date/status stay in category; keyboard tabs, filter focus trap/error',async()=>{await panel(1);await page.click('[data-p08-type="inbound"]');await page.fill('#p08-search','Minh Anh');await page.selectOption('#p08-status','waiting');await act('filter').click();await page.fill('.p08-dialog [name="from"]','2026-09-10');await page.fill('.p08-dialog [name="to"]','2026-09-09');await page.click('.p08-dialog [type="submit"]');assert.match(await page.locator('.p08-dialog [data-error]').textContent(),/không được/);for(let i=0;i<8;i++)await page.keyboard.press('Tab');assert.equal(await page.locator('.p08-dialog').evaluate(e=>e.contains(document.activeElement)),true);await page.fill('.p08-dialog [name="from"]','2026-09-09');await page.click('.p08-dialog [type="submit"]');assert.equal((await snap()).filters.type,'inbound');assert.equal(await page.locator('.p08-row').count(),6);assert.match(await page.locator('.p08-result-count').textContent(),/12 kết quả/);await act('filter').click();await page.keyboard.press('Escape');assert.equal(await act('filter').evaluate(e=>e===document.activeElement),true);await page.fill('#p08-search','PX-0005');assert.equal(await page.locator('.p08-row').count(),0);assert.equal((await snap()).filters.type,'inbound');await page.fill('#p08-search','HN12345');assert.equal(await page.locator('.p08-row').count(),1);});
 await check('A02 exact document/timeline/copy/attachments; Back restores query and scroll',async()=>{await page.click('[data-p08-record="LS-0001"]');assert.match(await page.locator('.p08-kv').textContent(),/PN-0005/);assert.equal(await page.locator('[data-event-id]').count(),0);assert.match(await page.locator('.p08-latest').textContent(),/Gửi phiếu lên Web/);assert.equal(await page.locator('[data-p08="document"]').count(),0);await act('copy').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'PN-0005');await page.click('[data-p08-tab="attachments"]');assert.match(await page.locator('[role="tabpanel"]').textContent(),/Chưa có tệp nguồn/);await page.click('[data-p08-tab="timeline"]');assert.equal(await page.locator('[data-event-id]').count(),4);await page.goBack();await page.locator('[data-panel="P08.S01"]').waitFor();assert.equal(await page.inputValue('#p08-search'),'HN12345');assert.equal((await snap()).filters.type,'inbound');});
 await check('A03 19/18/1 with 19 rows; A05 P23 uses same PQ-0001, browser Back preserves view',async()=>{await panel(3);assert.deepEqual(await page.locator('.p08-counters strong').allTextContents(),['19','18','1']);await act('codes').click();assert.equal(await page.locator('[data-scan-id]').count(),19);await page.locator('.p08-scroll').evaluate(e=>e.scrollTop=350);const top=await page.locator('.p08-scroll').evaluate(e=>e.scrollTop);await act('p23').click();const frame=page.frameLocator('iframe');await frame.locator('[data-session="PQ-0001"]').waitFor();assert.equal(await frame.locator('h1').textContent(),'Lịch sử phiên quét');assert.equal(await frame.locator('[data-session="PQ-0001"]').getAttribute('aria-current'),'true');assert.equal(await frame.locator('[data-session="PQ-0001"] .badge.amber').count(),1);assert.match(await frame.locator('[data-session="PQ-0001"]').textContent(),/19 lượt · 18 hợp lệ · 1 trùng/);await frame.locator('[data-session="PQ-0001"]').click();await page.locator('[data-panel="P08.S03"]').waitFor();assert.deepEqual(await page.locator('.p08-counters strong').allTextContents(),['19','18','1']);await act('back').click();await page.frameLocator('iframe').locator('[data-session="PQ-0001"]').waitFor();await page.goBack();await page.locator('[data-panel="P08.S03"]').waitFor();assert.equal(await page.locator('[data-scan-id]').count(),19);assert.ok(await page.locator('.p08-scroll').evaluate(e=>e.scrollTop)>=top);});
 await check('A04 date changes full aggregates and category drilldown',async()=>{await panel(4);assert.deepEqual(await page.locator('.p08-grid strong').allTextContents(),['12','6','4','3','5','30']);await page.fill('#p08-day','2026-09-08');assert.deepEqual(await page.locator('.p08-grid strong').allTextContents(),['3','2','1','1','1','8']);await page.locator('.p08-group[data-p08-group="warranty"]').click();assert.equal((await snap()).filters.type,'warranty');assert.equal((await snap()).filters.from,'2026-09-08');assert.equal(await page.locator('.p08-row').count(),1);await page.goBack();await page.locator('[data-panel="P08.S04"]').waitFor();assert.equal(await page.inputValue('#p08-day'),'2026-09-08');await page.fill('#p08-day','2026-10-01');assert.equal(await page.locator('.p08-grid').count(),0);assert.match(await page.locator('.p08-state').textContent(),/Chưa có nguồn tổng hợp/);});
 await check('A05 NFC immutable event ID/date/serial; application Back returns context',async()=>{await panel(1);await page.click('[data-p08-type="nfc"]');await page.fill('#p08-search','');await page.selectOption('#p08-status','all');await act('filter').click();await page.fill('.p08-dialog [name="from"]','2026-09-03');await page.fill('.p08-dialog [name="to"]','2026-09-09');await page.click('.p08-dialog [type="submit"]');await page.click('[data-p08-record="LS-0004"]');await act('nfc').click();const frame=page.frameLocator('iframe');await frame.locator('.event-detail-heading').waitFor();assert.match(await frame.locator('.summary-card').textContent(),/09\/09\/2026 · 11:05/);assert.match(await frame.locator('.summary-card').textContent(),/HN12345/);await frame.locator('[data-action="nfc"]').first().click();await page.locator('[data-panel="P08.S02"]').waitFor();assert.equal((await snap()).recordId,'LS-0004');});
 await check('loading/error/empty/unavailable and retry do not invent data',async()=>{await panel(1);for(const mode of ['loading','error','empty','unavailable']){await page.selectOption('[data-p08-scenario]',mode);assert.equal(await page.locator('.p08-row').count(),0);await capture('P08-state-'+mode);}await page.selectOption('[data-p08-scenario]','error');await act('retry').click();assert.ok(await page.locator('.p08-row').count()>0);});
 await check('list pagination/sort and exact list scroll restored after detail Back',async()=>{await page.locator('[data-p08-type="nfc"]').press('Home');assert.equal((await snap()).filters.type,'all');await page.selectOption('#p08-sort','desc');assert.equal((await snap()).filters.sort,'desc');await page.selectOption('#p08-sort','asc');assert.equal((await snap()).filters.sort,'asc');await act('more').click();assert.equal(await page.locator('.p08-row').count(),18);await page.locator('.p08-scroll').evaluate(e=>e.scrollTop=400);await page.locator('.p08-row').nth(7).scrollIntoViewIfNeeded();const before=await page.locator('.p08-scroll').evaluate(e=>e.scrollTop);await page.locator('.p08-row').nth(7).click();assert.equal(await page.locator('.p08-header h1').evaluate(e=>e===document.activeElement),true);await act('back').click();await page.locator('[data-panel="P08.S01"]').waitFor();assert.equal(await page.locator('.p08-scroll').evaluate(e=>e.scrollTop),before);assert.equal((await snap()).filters.sort,'asc');});

 await check('R02 shared embedded shell, one Back, no fake statusbar, category scoped entry and clear',async()=>{
   await page.click('[data-tab="history"]');const frame=page.frameLocator('iframe');await frame.locator('[data-action="documents"]').waitFor();
   for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.locator('.hn-screen').screenshot({path:path.join(out,`P22-hub-${w}x${h}.png`)});const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),f=s.querySelector('iframe'),d=f.contentDocument,p=d.querySelector('.phone'),body=d.querySelector('.body');return {css:[s.offsetWidth,s.offsetHeight],font:getComputedStyle(p).fontFamily,visibleBacks:[...d.querySelectorAll('[data-action="exit"]')].filter(e=>e.getClientRects().length).length,statusVisible:[...d.querySelectorAll('.statusbar')].filter(e=>e.getClientRects().length).length,outerBack:s.querySelectorAll('.hn-hub>[data-return]').length,overflow:body.scrollWidth>body.clientWidth+1,frameBottom:f.getBoundingClientRect().bottom,navTop:s.querySelector('.hn-nav').getBoundingClientRect().top};});metrics.push({name:'hub',viewport:[w,h],...m});assert.deepEqual(m.css,[494,950]);assert.equal(m.font,'Arial, sans-serif');assert.equal(m.visibleBacks,1);assert.equal(m.statusVisible,0);assert.equal(m.outerBack,0);assert.equal(m.overflow,false);assert.ok(m.frameBottom<=m.navTop+1);}
   await page.setViewportSize({width:494,height:1000});await frame.locator('[data-action="documents"]').click();await page.locator('[data-panel="P08.S01"]').waitFor();assert.equal((await snap()).filters.scope,'documents');assert.deepEqual(await page.locator('[data-p08-type]').evaluateAll(es=>es.map(e=>e.dataset.p08Type)),['all','inbound','outbound']);
   await page.fill('#p08-search','ZZ-NO-MATCH');assert.match(await page.locator('.p08-result-count').textContent(),/0 kết quả/);assert.equal(await page.locator('[data-p08-type="all"]').textContent(),'Tất cả');
   await act('clear').click();assert.equal((await snap()).filters.scope,'documents');assert.equal((await snap()).filters.from,'');assert.equal((await snap()).filters.q,'');assert.ok((await page.locator('.p08-row-bottom b').allTextContents()).every(t=>['Nhập kho','Xuất kho'].includes(t)));
   assert.match(await page.locator('.p08-result-count').textContent(),/29 kết quả · Tổng nguồn 29/);
   await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="history-general"]').click();await page.locator('[data-panel="P08.S01"]').waitFor();assert.equal((await snap()).filters.scope,'all');assert.equal(await page.locator('[data-p08-type]').count(),5);
 });
 await check('R02 badges for every record; honest missing source; noninteractive grid; technical notes outside app',async()=>{
   assert.equal(await page.locator('[data-p08-record="LS-0001"] .p08-chip').count(),1);assert.equal(await page.locator('[data-p08-record="LS-0005"] .p08-chip').count(),1);
   for(let p=1;p<=4;p++){await panel(p);assert.equal(await page.locator('.p08-demo-label').textContent(),'Dữ liệu mô phỏng');assert.doesNotMatch(await page.locator('.p08-app').textContent(),/P18|P23|Quantity fixture|production|UNKNOWN/);}
   await page.fill('#p08-day','2026-09-09');assert.equal(await page.locator('.p08-grid button').count(),0);assert.equal(await page.locator('.p08-grid .p08-stat').count(),6);assert.equal(await page.locator('.p08-group').count(),5);
   await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="sessions"]').click();await page.frameLocator('iframe').locator('[data-session="PQ-0002"]').click();await page.locator('[data-panel="P08.S03"]').waitFor();assert.equal((await snap()).sessionId,'PQ-0002');assert.equal(await page.locator('.p08-person strong').nth(0).textContent(),'Chưa có dữ liệu');assert.equal(await page.locator('.p08-person strong').nth(1).textContent(),'Chưa có dữ liệu');await capture('P08-missing-actor-warehouse');
   await act('back').click();const frame=page.frameLocator('iframe');await frame.locator('[data-action="filter"][data-value="Xuất linh kiện"]').click();await frame.locator('[data-session="PQ-0003"]').click();await page.locator('[data-panel="P08.S03"]').waitFor();await act('back').click();assert.equal(await page.frameLocator('iframe').locator('[data-action="filter"].active').getAttribute('data-value'),'Xuất linh kiện');assert.equal(await page.frameLocator('iframe').locator('[data-session]').count(),1);
   await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="history-general"]').click();await panel(1);await act('more').click();
 });
 await check('R02 embedded session/NFC layouts, scanner cancel and standalone isolation',async()=>{
   for(const scene of ['sessions','nfc']){
     await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="'+scene+'"]').click();
     for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){
       await page.setViewportSize({width:w,height:h});const frame=page.frameLocator('iframe');await frame.locator('.phone[data-history-embedded="true"]').waitFor();
       await page.locator('.hn-screen').screenshot({path:path.join(out,'P22-'+scene+'-'+w+'x'+h+'.png')});
       const m=await page.locator('iframe').evaluate(f=>{const d=f.contentDocument,b=d.querySelector('.body');return {width:b.clientWidth,overflow:b.scrollWidth>b.clientWidth+1,scrollbar:f.contentWindow.getComputedStyle(b).scrollbarWidth,footer:d.querySelector('.phone-footer').getClientRects().length,statusbar:d.querySelector('.statusbar').getClientRects().length};});
       metrics.push({name:scene,viewport:[w,h],...m});assert.equal(m.overflow,false);assert.equal(m.scrollbar,'none');assert.equal(m.footer,0);assert.equal(m.statusbar,0);
     }
     await page.setViewportSize({width:494,height:1000});await page.click('[data-tab="lookup"]');await page.locator('[data-panel="P03.S01"]').waitFor();assert.equal(await page.locator('.p03-dialog').count(),1);await page.keyboard.press('Escape');assert.equal(await page.locator('.hn-screen').evaluate(e=>e.classList.contains('p08-embedded-screen')),true);
   }
   const isolated=await ctx.newPage();await isolated.goto('http://127.0.0.1:8766/flows/warranty-components/?mode=screen&scene=history-hub');assert.equal(await isolated.locator('.phone').getAttribute('data-history-embedded'),'false');assert.equal(await isolated.locator('.statusbar').isVisible(),true);assert.equal(await isolated.locator('.phone-footer').isVisible(),true);await isolated.close();
   await page.click('[data-tab="history"]');await page.frameLocator('iframe').locator('[data-action="history-general"]').click();await act('more').click();
 });
 await check('keyboard scroll, P03 one overlay and logout Back cannot restore',async()=>{await page.locator('.p08-scroll').focus();await page.keyboard.press('PageDown');await page.waitForTimeout(200);assert.ok(await page.locator('.p08-scroll').evaluate(e=>e.scrollTop)>0);await page.click('[data-tab="lookup"]');await page.locator('[data-panel="P03.S01"]').waitFor();assert.equal(await page.locator('.p03-dialog').count(),1);await page.keyboard.press('Escape');await page.locator('[data-panel="P08.S01"]').waitFor();await page.locator('.hn-tools>details').first().locator('summary').click();await page.click('#hn-logout');await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p08-app').count(),0);});
 await check('standalone P22 document reader shares source, no invented quantity or date; unknown event/session fail closed',async()=>{const isolated=await ctx.newPage();await isolated.goto('http://127.0.0.1:8766/flows/warranty-components/?mode=screen&scene=documents');await isolated.locator('[data-document="PN-0005"]').click();assert.match(await isolated.locator('.summary-card').textContent(),/09\/09\/2026 · 08:32/);assert.match(await isolated.locator('.summary-card').textContent(),/Chưa có nguồn số lượng/);for(const [scene,field]of [['nfc-detail','event'],['session-detail','session']]){await isolated.goto(`http://127.0.0.1:8766/flows/warranty-components/?mode=screen&scene=${scene}&${field}=not-found`);assert.match(await isolated.locator('.body').textContent(),/Không tìm thấy/);}await isolated.close();});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({revision:'P08-r02',checks,errors,externalRequests:external,integration:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
