const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),{mockGeography,address}=require('./outbound_geography_helpers.cjs');
const out='handoff/P17/evidence/revision-03/navigation';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce'}),checks=[],errors=[];p.setDefaultTimeout(20000);p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);
const act=(o,a)=>p.locator(`[data-${o}="${a}"]`).first(),snap=async o=>JSON.parse(await p.locator(`[data-${o}-snapshot]`).textContent());
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
const shot=async n=>{await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});};
async function login(route){await p.goto('http://localhost:8766/flows/auth-session/');await p.waitForSelector('#username',{timeout:60000});await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click(`[data-route=${route}]`);if(['inbound','outbound'].includes(route))await p.locator(route==='inbound'?'.p04-tools':'.p05-tools').evaluate(e=>e.open=true);}
async function scan(o,value){await p.fill(`#${o}-code`,value);await p.press(`#${o}-code`,'Enter');}
try{
await login('inbound');await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');await act('p04','next').click();await p.selectOption('[data-p04-outcome]','status-unavailable');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');
await check('Unavailable status dock opens/focuses reconciliation details without a read or record',async()=>{const before=await snap('p04');await act('p04','review-reconciliation').click();assert.equal(await p.locator('.p17-identity').evaluate(e=>e.open),true);assert.equal(await p.locator('.p17-identity summary').evaluate(e=>e===document.activeElement),true);assert.ok(await p.locator('.p17-identity summary').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.p17-scroll').getBoundingClientRect();return r.top>=s.top&&r.bottom<=s.bottom;}));assert.equal(await act('p04','send').isDisabled(),true);assert.deepEqual((await snap('p04')).request,before.request);assert.equal((await snap('p04')).metrics.recordCalls,1);await shot('reconciliation-open');});
await login('inbound');await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');await scan('p04','BAD');
await check('Native Back/Forward and Escape do not replay scan or add duplicate exception history',async()=>{const before=await snap('p04');await p.goBack();await p.waitForSelector('[data-panel="P04.S02"]');await p.goForward();await p.waitForTimeout(160);assert.equal(await p.locator('.p17-app').count(),0);assert.deepEqual((await snap('p04')).attempts,before.attempts);await scan('p04','BAD-2');await p.keyboard.press('Escape');await p.waitForSelector('[data-panel="P04.S02"]');assert.deepEqual((await snap('p04')).accepted,before.accepted);await shot('native-back-restored');});
await check('Long invalid raw uses reader; Back closes reader first; six viewport geometry stays in app',async()=>{const raw='Đặng Ánh '.repeat(220)+'W'.repeat(300);await scan('p04',raw);await p.waitForSelector('.p17-reason .hn-read-more:not([hidden])');for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.locator('.p17-reason .hn-read-more:not([hidden])').first().click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok((await p.locator('.app-modal-host').innerText()).includes(raw));assert.ok(await p.locator('.app-modal-host dialog').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.hn-screen').getBoundingClientRect();return r.left>=s.left-1&&r.right<=s.right+1&&r.top>=s.top-1&&r.bottom<=s.bottom+1;}));await shot('long-reader-'+width);await p.goBack();await p.waitForTimeout(100);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('[data-panel="P17.S01"]').count(),1);}await p.goBack();await p.waitForSelector('[data-panel="P04.S02"]');assert.equal((await snap('p04')).attempts.at(-1).raw,raw);await p.setViewportSize({width:494,height:950});});
await login('outbound');await address(p);await act('p05','next').click();await act('p05','manual').click();await scan('p05','HN99999');
await check('Outbound blocked-code Back retains document and never records',async()=>{const before=await snap('p05');await p.goBack();await p.waitForSelector('[data-panel="P05.S02"]');assert.deepEqual((await snap('p05')).document,before.document);assert.equal((await snap('p05')).metrics.recordCalls,0);await scan('p05','HN99999');await p.keyboard.press('Escape');await p.waitForSelector('[data-panel="P05.S02"]');await shot('outbound-back');});
await login('nfc');await act('p07','begin').click();await p.locator('.p07-tools details').first().evaluate(e=>e.open=true);await p.selectOption('[data-p07-scenario]','conflict');await p.click('[data-p07-demo-read]');await p.waitForSelector('[data-panel="P17.S03"]');
await check('NFC detail then exception consumes one Back each; mapping unchanged on return and Forward',async()=>{const before=await snap('p07');await act('p07','exception-detail').click();await p.goBack();await p.waitForTimeout(120);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('[data-panel="P17.S03"]').count(),1);await p.goBack();await p.waitForSelector('[data-panel="P07.S02"]');assert.equal((await snap('p07')).stats.mutations,before.stats.mutations);await p.goForward();await p.waitForTimeout(120);assert.equal(await p.locator('.p17-app').count(),0);assert.equal((await snap('p07')).stats.mutations,0);await shot('nfc-back');});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));await p.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await b.close();}})();
