const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.NOTIFICATION_COUNTS_EVIDENCE_DIR||'handoff/P13/evidence/revision-04';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const ready=()=>p.locator('[data-p13-loaded=true][aria-busy=false]').waitFor();
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function dataset(v){await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset',v);await ready();await p.evaluate(()=>scrollTo(0,0));}
try{
await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await ready();
await check('Caps0/1/9/10/99/100/999/1000 retain exact count, source pages stay10',async()=>{for(const n of [0,1,9,10,99,100,999,1000]){await dataset('count-'+n);assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),`Chưa đọc (${n>99?'99+':n})`);assert.equal(await p.locator('[data-p13-filter=unread]').getAttribute('aria-label'),`Chưa đọc: ${n.toLocaleString('vi-VN')} thông báo chưa đọc`);assert.equal(await p.locator('.p13-notification').count(),Math.min(n,10));if(n===0){assert.equal(await p.locator('.p13-page-control').count(),0);}else{assert.equal(await p.locator('.p13-page-control p').count(),1);assert.equal(await p.locator('.p13-list-end').count(),0);}for(const [width,height]of [[494,950],[360,800],[1440,900]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));const tab=await p.locator('[data-p13-filter=unread]').evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert.equal(tab.width,tab.scroll);await p.click('[data-tab=home]');await p.locator('#hn-home').waitFor({state:'visible'});const badge=p.locator('.hn-bell .hn-count');assert.equal(await badge.isVisible(),n!==0);assert.equal(await badge.textContent(),n>9?'9+':String(n));assert.equal(await p.locator('.hn-bell').getAttribute('title'),`${n.toLocaleString('vi-VN')} thông báo chưa đọc`);const m=await p.evaluate(()=>{const button=document.querySelector('.hn-bell'),badge=button.querySelector('.hn-count'),avatar=document.querySelector('.hn-avatar'),r=badge.getBoundingClientRect(),a=avatar.getBoundingClientRect(),c=getComputedStyle(badge);return{viewport:[innerWidth,innerHeight],badgeWidth:c.width,badgeHeight:c.height,inside:r.right<a.left,noOverflow:document.querySelector('.hn-screen').scrollWidth===494};});assert.equal(m.badgeWidth,'22px');assert.equal(m.badgeHeight,'18px');assert.ok(m.inside);assert.ok(m.noOverflow);metrics.push({n,...m});if(width===494){await shot('home-count-'+n);await p.locator('.hn-brand-row').screenshot({path:path.join(out,'bell-count-'+n+'.png')});}await p.click('.hn-bell');await ready();}if(n===1000){await p.setViewportSize({width:494,height:950});await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('count1000-page10');}}});
await check('Reading across thresholds updates9+ to9 and99+ to99; raw counts preserved',async()=>{for(const [n,after]of [[10,9],[100,99]]){await dataset('count-'+n);await p.locator('[data-p13-event]').first().click();await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));await p.click('[data-p13=back]');await ready();assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),`Chưa đọc (${after})`);assert.equal(await p.locator('.p13-notification').count(),9);assert.equal(await p.locator('.hn-bell .hn-count').textContent(),after>9?'9+':String(after));assert.equal(await p.locator('.hn-bell').getAttribute('title'),`${after} thông báo chưa đọc`);}});
await check('1000-source loads10 then20 without bulk DOM or unread changes',async()=>{await dataset('count-1000');assert.equal(await p.locator('.p13-notification').count(),10);await p.click('[data-p13=more]');await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===20);assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),'Chưa đọc (99+)');assert.ok((await p.locator('.p13-page-control').textContent()).includes('20 / 1.000'));assert.equal(await p.locator('[data-p13=more]').textContent(),'Xem thêm');await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('count1000-page20');});
await check('End has one truthful status, button is absent, unread is not cleared by loading',async()=>{await dataset('extended');await p.click('[data-p13-filter=all]');await ready();await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('after-all-first10-bottom');for(const n of [20,30,37]){await p.click('[data-p13=more]');await p.waitForFunction(n=>document.querySelectorAll('.p13-notification').length===n,n);}assert.equal(await p.locator('.p13-page-control').textContent(),'Đã tải đủ 37 thông báo');assert.equal(await p.locator('[data-p13=more]').count(),0);assert.equal(await p.locator('[data-p13-filter=unread]').textContent(),'Chưa đọc (24)');await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('after-all-end37');});
await check('Unknown remains unknown; no fake zero or source truncation',async()=>{await p.click('[data-tab=home]');await p.locator('.hn-tools details').first().evaluate(e=>e.open=true);await p.selectOption('#hn-scenario','unknown');assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'?');assert.ok((await p.locator('.hn-bell').getAttribute('aria-label')).includes('Chưa xác định'));await p.selectOption('#hn-scenario','baseline');assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'9+');assert.equal(await p.locator('.hn-bell').getAttribute('title'),'24 thông báo chưa đọc');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'count-browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'count-browser-failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('count-failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
