const base=process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8766';
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.INBOUND_EVIDENCE_DIR || 'handoff/P04/evidence'); fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:340,height:847},deviceScaleFactor:1});
 const checks=[],errors=[],external=[],metrics=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{window.__cameraRequests=0;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{window.__cameraRequests++;throw Error('No auto camera');};});
 const act=n=>page.locator(`[data-p04="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});}
 async function login(){await page.goto(base+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home').waitFor({state:'visible'});}
 async function enter(){await page.locator('.hn-task[data-route="inbound"]').click();await page.locator('.p04-tools summary').click();}
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const app=document.querySelector('.p04-app'),s=document.querySelector('.hn-screen'),r=s.getBoundingClientRect();return{viewport:[innerWidth,innerHeight],clientWidth:document.documentElement.clientWidth,dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,transform:s.style.transform,screen:{width:r.width,height:r.height,bottom:r.bottom},overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,controls:[...app.querySelectorAll('.p04-footer button')].map(b=>{let r=b.getBoundingClientRect();return{bottom:r.bottom,right:r.right,left:r.left}})};});metrics.push({name,...m});assert.equal(m.overflow,false);const fit=Math.min(1,m.clientWidth/494,m.viewport[1]/950);assert.ok(Math.abs(m.screen.width-494*fit)<1,name+' locked Home width');assert.ok(Math.abs(m.screen.height-950*fit)<1,name+' locked Home height');assert.ok(m.controls.every(c=>c.bottom<=m.screen.bottom+1));}
 async function captureReference(name) {
  await capture(name);
  for(const [w,h] of [[360,800],[430,932],[1440,900],[340,420]]) {
   await page.setViewportSize({width:w,height:h}); await capture(name.replace('-340',`-${w}x${h}`));
  }
  await page.setViewportSize({width:340,height:847});
 }
 try{
 await login();await enter();
 await check('S01 required/read-only metadata and source session',async()=>{await captureReference('P04-S01-340');assert.equal(await page.locator('[aria-label="Kho nhập"]').inputValue(),'Kho Hoa Nam');assert.equal(await page.locator('[aria-label="Mã phiếu nhập"]').getAttribute('readonly'),'');await page.locator('[data-p04-note]').fill('Kiểm tra bao bì');});
 await check('S02 fixture 12=11+1 and raw history',async()=>{await act('next').click();await act('batch').click();assert.equal((await snap()).attempts.length,12);assert.equal((await snap()).accepted.length,11);await captureReference('P04-S02-340');await act('all').click();assert.equal(await page.locator('.p04-attempt').count(),12);await capture('P04-S02-expanded-stable');await act('all').click();});
 await check('S03 back retains codes/identity and edits note',async()=>{await act('next').click();let before=await snap();await act('back').click();await act('back').click();assert.equal(await page.locator('[data-p04-note]').inputValue(),'Kiểm tra bao bì');await page.locator('[data-p04-note]').fill('');await act('next').click();await act('next').click();assert.deepEqual((await snap()).accepted,before.accepted);await captureReference('P04-S03-340');});
 await check('A03 single confirmed record + S04 links exact P12 receipt without inventory change',async()=>{await act('send').dblclick();await page.locator('[data-panel="P04.S04"]').waitFor();assert.equal((await snap()).metrics.recordCalls,1);assert.equal((await snap()).metrics.inventoryDelta,0);await captureReference('P04-S04-340');const id=(await snap()).document.documentId;await act('document').click();await page.locator('.p12-app').waitFor();assert.ok(page.url().includes(encodeURIComponent(id)));await page.locator('[data-p12=back]').first().click();await page.locator('[data-panel="P04.S04"]').waitFor();await act('home').click();await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).step,1);assert.equal((await snap()).accepted.length,0);assert.equal((await snap()).request,null);});
 await check('result dependency notice remains accessible at reduced height',async()=>{for(const [w,h] of [[360,800],[430,932],[1440,900],[340,420]]){await page.setViewportSize({width:w,height:h});await capture(`P04-dependency-${w}x${h}`);}});
 await login();await enter();
 await check('manual/camera fixture validation same pipeline, keyboard input, invalid preserved',async()=>{await act('next').click();await act('manual').click();await page.locator('#p04-code').fill('HN12345');await page.locator('#p04-code').press('Enter');await page.locator('#p04-code').fill('HN12345');await page.locator('#p04-code').press('Enter');await page.locator('#p04-code').fill('<invalid>');await page.locator('#p04-code').press('Enter');assert.deepEqual((await snap()).attempts.map(a=>a.kind),['valid','duplicate','invalid']);await page.locator('[data-panel="P17.S01"]').waitFor();assert.equal(await page.locator('.p17-app script').count(),0);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement.closest('.p17-app')),true);await act('exception-manual').click();await page.locator('#p04-code').waitFor();assert.equal(await page.inputValue('#p04-code'),'<invalid>');await act('close-manual').click();});
 await check('timeout preserves request, disables retry; P17 reconciles receipt',async()=>{await act('next').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await act('send').click();await page.locator('[data-panel="P17.S04"]').waitFor();const before=(await snap()).request;assert.equal(await act('send').isDisabled(),true);assert.equal(await act('back').count(),0);await capture('P04-timeout');await act('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.deepEqual((await snap()).request,before);assert.equal((await snap()).metrics.recordCalls,1);});
 await login();await enter();
 await check('Home/native Back preserves in-memory draft',async()=>{await page.locator('[data-p04-note]').fill('Giữ phiếu');await act('next').click();await act('batch').click();const doc=(await snap()).document;await page.goBack();await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).step,2);assert.deepEqual((await snap()).document,doc);assert.equal((await snap()).accepted.length,11);});
 await check('warehouse stop blocks record via P03 without logout',async()=>{await act('next').click();await page.locator('.p03-tools summary').click();await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await act('send').click();await page.locator('[data-panel="P03.S03"]').waitFor();assert.equal((await snap()).metrics.recordCalls,0);await page.locator('[data-p03-action="home"]').click();assert.equal(await page.locator('#hn-home').isVisible(),true);});
 await check('P03 resumes P04 without requesting camera',async()=>{await page.selectOption('[data-p03-fixture="warehouse"]','active');await page.locator('[data-tab="lookup"]').click();await page.locator('[data-p03-action="resume"]').click();await page.locator('.p04-app').waitFor();assert.equal(await page.evaluate(()=>window.__cameraRequests),0);});
 await check('logout/back cannot restore P04 authenticated data',async()=>{await page.locator('.hn-tools > details > summary').first().click();await page.locator('#hn-logout').click();await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p04-app').count(),0);});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));console.log(JSON.stringify({groups:checks.length,errors,external}));
 }catch(e){await page.screenshot({path:path.join(out,'browser-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
