const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,choose,address}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.MANUAL_UX_OUTPUT||'handoff/ux-upgrade-2026-09-30/p04-p05/after');fs.mkdirSync(out,{recursive:true});
const before=process.env.MANUAL_UX_BEFORE==='1',sizes=[[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]];
(async()=>{const browser=await chromium.launch({headless:true}),checks=[],layouts=[],errors=[];let page;
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log(name);};
try{for(const [p,route] of [['p04','inbound'],['p05','outbound']]){
 page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));await mockGeography(page);
 await page.goto((process.env.MANUAL_UX_BASE||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator(`.hn-task[data-route="${route}"]`).click();
 const act=n=>page.locator(`[data-${p}="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator(`[data-${p}-snapshot]`).textContent()),dialog=()=>page.locator('.hn-action-dialog[open]');
 const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 async function close(label){await dialog().getByRole('button',{name:label,exact:true}).click();await dialog().waitFor({state:'detached'});await page.waitForFunction(()=>!Object.keys(history.state||{}).some(k=>k.includes('Feedback')));}
 if(p==='p05'){
   await page.locator('[data-p05-note]').fill('Giao trước 17 giờ.\nGọi trước khi giao.');await address(page);const original=(await snap()).document;
   await choose(page,'source','demo-0006');await dialog().waitFor();await page.locator('.hn-screen').screenshot({path:path.join(out,'p05-change-source.png')});
   await check('P05 source cancel preserves complete original document',async()=>{assert.deepEqual((await snap()).document,original);if(!before){const text=await dialog().textContent();for(const val of ['Đại lý Minh Phát','Cửa hàng An Bình','1 → 2','Máy in nhiệt','Máy in ZD421','Giao trước 17 giờ.','Chưa chọn'])assert.ok(text.includes(val),val);}await close('Hủy');assert.deepEqual((await snap()).document,original);});
   if(!before){
    await check('P05 long replacement details remain full text in one scrollable dialog at six viewports; Escape and Back cancel',async()=>{
     await choose(page,'recipient','walk-in');const long='<Tên> & tiếng Việt\n'+'Dài'.repeat(700);await page.fill('[data-p05-field="recipient"]',long);const expected=(await snap()).document;await choose(page,'source','demo-0006');await dialog().waitFor();assert.ok((await dialog().textContent()).includes(expected.recipient));assert.equal(await page.locator('.app-modal-host').count(),1);
     for(const [width,height]of sizes){await page.setViewportSize({width,height});await settle();const m=await dialog().evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.hn-screen').getBoundingClientRect(),f=e.querySelector('footer').getBoundingClientRect(),b=e.querySelector('.app-modal-body');return{inside:r.left>=s.left-1&&r.right<=s.right+1&&r.top>=s.top-1&&r.bottom<=s.bottom+1,footer:f.bottom<=r.bottom+1&&f.top>=r.top,scroll:b.scrollHeight>b.clientHeight,overflow:b.scrollWidth>b.clientWidth+1};});assert.deepEqual(m,{inside:true,footer:true,scroll:true,overflow:false});await page.locator('.hn-screen').screenshot({path:path.join(out,`p05-source-long-${width}x${height}.png`)});}
     await page.keyboard.press('Escape');await dialog().waitFor({state:'detached'});await page.waitForFunction(()=>!Object.keys(history.state||{}).some(k=>k.includes('Feedback')));assert.deepEqual((await snap()).document,expected);await choose(page,'source','demo-0006');await dialog().waitFor();await page.goBack();await dialog().waitFor({state:'detached'});assert.deepEqual((await snap()).document,expected);await page.setViewportSize({width:494,height:1000});
    });
    await check('P05 stale confirmation keeps newer draft and requires a new decision',async()=>{
     await choose(page,'source','demo-0006');await dialog().waitFor();await page.locator('[data-p05-note]').evaluate(e=>{e.value='Bản nhập mới trong lúc đối chiếu';e.dispatchEvent(new Event('input',{bubbles:true}));});const latest=(await snap()).document;await dialog().getByRole('button',{name:'Đổi phiếu',exact:true}).click();await page.getByRole('heading',{name:'Thông tin phiếu đã thay đổi'}).waitFor();assert.deepEqual((await snap()).document,latest);await close('Đã hiểu');
    });
   }
   await choose(page,'source','board-0005');await close('Đổi phiếu');await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p05-snapshot]').textContent).document.sourceId==='board-0005');await address(page);
 }
 await act('next').click();await act('manual').click();await page.fill(`#${p}-code`,'HN12345');await page.locator(`#${p}-code`).press('Enter');
 for(const [width,height]of sizes){await page.setViewportSize({width,height});await settle();await page.locator(`.${p}-scroll`).evaluate(e=>e.scrollTop=0);const m=await page.evaluate(p=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};},app=document.querySelector('.hn-screen'),scroll=document.querySelector(`.${p}-scroll`);return{app:rect(app),shell:[app.offsetWidth,app.offsetHeight],cameraHeight:document.querySelector(`.${p}-camera`).offsetHeight,scroll:rect(scroll),manual:rect(document.querySelector(`.${p}-manual`)),counter:rect(document.querySelector(`.${p}-counter`)),latest:document.querySelector(`.${p}-attempt`)&&rect(document.querySelector(`.${p}-attempt`)),header:rect(document.querySelector(`.${p}-header`)),footer:rect(document.querySelector(`.${p}-footer`)),horizontal:document.documentElement.scrollWidth>innerWidth};},p);layouts.push({p,viewport:[width,height],...m});assert.deepEqual(m.shell,[494,950]);assert.equal(m.horizontal,false);if(!before){assert.ok(m.cameraHeight<=56);assert.ok(m.manual.bottom<=m.scroll.bottom+1,'input visible');assert.ok(m.counter.bottom<=m.scroll.bottom+1,'counter visible');if(height>=844)assert.ok(m.latest.bottom<=m.scroll.bottom+1,'latest entry visible');}await page.locator('.hn-screen').screenshot({path:path.join(out,`${p}-manual-${width}x${height}.png`)});}
 if(!before){
 await page.setViewportSize({width:494,height:1000});await settle();
 await check(`${p} continuous entry preserves input DOM, focus and counts`,async()=>{await page.locator(`#${p}-code`).evaluate(e=>{window.manualNode=e;});await page.fill(`#${p}-code`,'HN12348');await page.locator(`#${p}-code`).press('Enter');assert.equal(await page.locator(`#${p}-code`).evaluate(e=>e===window.manualNode&&e===document.activeElement),true);assert.equal(await page.locator(`#${p}-code`).inputValue(),'');assert.equal((await snap()).accepted.length,2);});
 await check(`${p} IME Enter and form submit never add an unfinished composition`,async()=>{await page.fill(`#${p}-code`,'HN12349');await page.locator(`#${p}-code`).dispatchEvent('compositionstart');await page.locator(`#${p}-code`).dispatchEvent('keydown',{key:'Enter',keyCode:229,isComposing:true});await page.locator(`.${p}-manual`).dispatchEvent('submit');assert.equal((await snap()).accepted.length,2);await page.locator(`#${p}-code`).dispatchEvent('compositionend');await page.locator(`#${p}-code`).press('Enter');assert.equal((await snap()).accepted.length,3);});
 await check(`${p} collapse/reopen and review Back preserve draft`,async()=>{await page.fill(`#${p}-code`,'CHƯA-GỬI');await page.locator(`#${p}-code`).press('Escape');assert.equal(await page.locator(`#${p}-code`).count(),0);await act('manual').click();assert.equal(await page.locator(`#${p}-code`).inputValue(),'CHƯA-GỬI');await act('next').click();await act('back').click();assert.equal(await page.locator(`#${p}-code`).inputValue(),'CHƯA-GỬI');assert.equal((await snap()).accepted.length,3);});
 await check(`${p} UNKNOWN remains in P17 with same request; manual and source cannot bypass`,async()=>{
  if(p==='p05'){for(const code of ['HN12350','HN12351','HN12346','HN12347','HN12352','HN12353','HN12354']){await page.fill('#p05-code',code);await page.locator('#p05-code').press('Enter');}}
  await act('next').click();await page.locator(`.${p}-tools summary`).click();await page.selectOption(`[data-${p}-outcome]`,'unknown');await act('send').click();await page.locator('[data-panel="P17.S04"]').waitFor();const pending=await snap();assert.ok(pending.request);assert.equal(await page.locator(`#${p}-code`).count(),0);assert.equal(await page.locator(`[data-${p}-select="source"]`).count(),0);assert.equal(pending.metrics.recordCalls,1);assert.equal(pending.metrics.inventoryDelta,0);await page.locator('.hn-screen').screenshot({path:path.join(out,`${p}-unknown.png`)});await act('check').click();await page.waitForFunction(p=>!JSON.parse(document.querySelector(`[data-${p}-snapshot]`).textContent).busy,p);assert.deepEqual((await snap()).request,pending.request);assert.equal((await snap()).metrics.recordCalls,1);
 });
 }
 await page.close();page=null;
}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({before,checks,layouts,errors},null,2));console.log(JSON.stringify({groups:checks.length,layouts:layouts.length,errors}));
}catch(e){if(page)await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,layouts,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
