const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_UPDATE_EVIDENCE_DIR||'handoff/P09/evidence/revision-07');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const act=a=>page.locator(`[data-p09="${a}"]`).first(),dlg=()=>page.locator('.p09-update-dialog'),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
const panel=p=>page.locator(`[data-panel="${p}"]`).waitFor();
async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route=warranty]');await panel('P09.S01');}
async function openCase(id='BH-007'){await page.fill('#p09-query',id);await page.click(`[data-p09-case="${id}"]`);await panel('P09.S03');}
async function save(){await dlg().locator('[type=submit]').click();}
async function mode(value){if(await page.locator('.p09-tools details').getAttribute('open')===null)await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]',value);}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function audit(name){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>{const screen=document.querySelector('.hn-screen'),app=document.querySelector('.p09-app'),d=document.querySelector('.p09-update-dialog'),r=screen.getBoundingClientRect(),dr=d?.getBoundingClientRect(),f=d?.querySelector('footer'),mainFooter=app.querySelector('.p09-footer');return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,shell:[screen.offsetWidth,screen.offsetHeight],pageOverflow:document.documentElement.scrollWidth>innerWidth,contentOverflow:app.querySelector('.p09-scroll').scrollWidth>app.querySelector('.p09-scroll').clientWidth,dialogInside:!d||(dr.left>=r.left&&dr.right<=r.right+1&&dr.top>=r.top&&dr.bottom<=r.bottom+1),footerInside:!d||f.getBoundingClientRect().bottom<=dr.bottom+1,mainFooterInside:mainFooter.getBoundingClientRect().bottom<=r.bottom+1,fields:d?[...d.querySelectorAll('textarea')].map(e=>({left:e.offsetLeft,width:e.offsetWidth,height:e.offsetHeight,resize:getComputedStyle(e).resize})):[],buttons:[...(d?f:mainFooter).querySelectorAll('button')].map(e=>({width:e.clientWidth,scroll:e.scrollWidth,height:e.offsetHeight}))};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.pageOverflow&&!m.contentOverflow&&m.dialogInside&&m.footerInside&&m.mainFooterInside,JSON.stringify(m));assert.ok(m.buttons.every(b=>b.width>=b.scroll&&b.height>=48));if(m.fields.length){assert.equal(m.fields[0].left,m.fields[1].left);assert.equal(m.fields[0].width,m.fields[1].width);assert.ok(m.fields.every(f=>f.height===100&&f.resize==='none'));}metrics.push({name,...m});await capture(name);}
async function matrix(name){for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await audit(name+'-'+w+'x'+h);}await page.setViewportSize({width:494,height:1000});}
try{
await login();await act('filter').click();await page.locator('.p08-picker input[value="Đang kiểm tra"]').check();await page.locator('.p08-picker [type=submit]').click();await openCase();await page.click('[data-p09-tab=events]');
await check('Update dialog identifies exact case/serial; one border per field, fixed actions at six sizes',async()=>{await act('update').click();assert.match(await dlg().locator('.p09-update-context').textContent(),/BH-007.*SN-XP420B-206/);assert.equal(await dlg().locator('.p09-field').count(),0);assert.equal(await dlg().locator('[type=submit]').isDisabled(),true);await matrix('dialog-empty');});
await check('Inline required/length validation, counters and focus; no request for blank result',async()=>{await dlg().locator('[name=result]').fill('   ');assert.equal(await dlg().locator('[name=result]').getAttribute('aria-invalid'),'true');await dlg().locator('[type=submit]').evaluate(e=>{e.disabled=false;e.click();});assert.equal((await snap()).request,null);assert.equal(await dlg().locator('[name=result]').evaluate(e=>e===document.activeElement),true);await dlg().locator('[name=diagnosis]').fill('Lỗi phần mềm');await dlg().locator('[name=result]').fill('Đã sửa xong, máy hoạt động bình thường');assert.equal(await dlg().locator('[type=submit]').isEnabled(),true);assert.match(await dlg().locator('[data-counter=result]').textContent(),/\/200/);await capture('dialog-ready');});
await check('Cancel/browser Back preserve update draft and caller tab',async()=>{await page.goBack();await dlg().waitFor({state:'detached'});assert.equal(await page.locator('[data-p09-tab=events]').getAttribute('aria-selected'),'true');await act('update').click();assert.equal(await dlg().locator('[name=diagnosis]').inputValue(),'Lỗi phần mềm');assert.match(await dlg().locator('[name=result]').inputValue(),/Đã sửa xong/);await dlg().locator('[data-cancel]').click();await dlg().waitFor({state:'detached'});assert.equal((await snap()).writes,0);});
await check('Failed save opens feedback dialog, retains request; retry success commits once despite double click',async()=>{await mode('error');await act('update').click();await save();await page.waitForFunction(()=>document.querySelector('.hn-action-dialog[open]')?.textContent.includes('Chưa cập nhật'));assert.equal(await dlg().count(),0);assert.equal(await page.locator('.hn-action-dialog[open]').count(),1);assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);const id=(await snap()).request.id;await capture('dialog-save-error');await page.keyboard.press('Escape');await mode('ready');await act('update').click();await dlg().locator('[type=submit]').evaluate(e=>{e.click();e.click();});await panel('P09.S04');assert.equal((await snap()).writes,1);assert.equal((await snap()).receipt.requestId,id);});
await check('Result has View case + Return to list; footer fits six sizes; filtered list context survives',async()=>{assert.equal(await act('view').count(),1);assert.equal(await act('list').count(),1);await matrix('result');await act('list').evaluate(e=>{e.click();e.click();});await panel('P09.S01');assert.equal(await page.locator('#p09-query').inputValue(),'BH-007');assert.match(await page.locator('.p09-controls').textContent(),/Đang kiểm tra/);assert.equal(await page.locator('.p09-case').count(),0);assert.match(await page.locator('.p09-list-return-note').textContent(),/BH-007.*Chờ bàn giao/);assert.equal((await snap()).writes,1);await capture('return-preserves-filter');await act('back').click();await page.locator('#hn-home:visible').waitFor();});
await check('Waiting-handover case also has Return to list; list Back never loops into result',async()=>{await page.click('[data-route=warranty]');await act('filter').click();await page.locator('.p08-picker input[value=all]').check();await page.locator('.p08-picker [type=submit]').click();await page.click('[data-p09-case=BH-007]');await panel('P09.S03');assert.equal(await act('list').isEnabled(),true);await page.click('[data-p09-tab=parts]');await act('list').click();await panel('P09.S01');assert.equal(await page.locator('#p09-query').inputValue(),'BH-007');await act('back').click();await page.locator('#hn-home:visible').waitFor();assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);});
await check('Direct case route without an earlier warranty list safely normalizes to list',async()=>{await page.evaluate(()=>location.hash='#p02/warranty?panel=3&case=BH-001');await panel('P09.S03');await act('update').click();await dlg().locator('[name=result]').fill('Đã sửa máy');await save();await panel('P09.S04');await act('list').click();await panel('P09.S01');await act('back').click();await page.locator('#hn-home:visible').waitFor();});
await check('UNKNOWN dialog freezes inputs and reconciles same request; closing then reconciling from list keeps navigation sound',async()=>{await login();await openCase();await mode('unknown');await act('update').click();await dlg().locator('[name=result]').fill('Đã khắc phục');await save();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const before=(await snap()).request;assert.equal(await dlg().count(),0);await page.locator('.hn-action-dialog[open]').waitFor();assert.equal(await act('update').isDisabled(),true);assert.equal(await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').textContent(),'Đối chiếu');await capture('dialog-unknown');await page.keyboard.press('Escape');await act('back').click();await panel('P09.S01');assert.deepEqual((await snap()).request,before);await act('reconcile').click();await panel('P09.S04');assert.equal((await snap()).receipt.requestId,before.id);assert.equal((await snap()).writes,1);await act('list').click();await panel('P09.S01');await act('back').click();await page.locator('#hn-home:visible').waitFor();});
await check('Back during save cannot be revived by a late result; confirmed waiting case keeps list exit',async()=>{await login();await openCase();await act('update').click();await dlg().locator('[name=result]').fill('Đã kiểm tra xong');await save();await page.goBack();await dlg().waitFor({state:'detached'});await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).busy);await panel('P09.S03');assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);assert.equal((await snap()).writes,1);assert.equal(await act('list').isEnabled(),true);await act('list').click();await panel('P09.S01');});
await check('Forward over a dismissed dialog cannot corrupt the return-list depth',async()=>{await login();await openCase();await act('update').click();await page.goBack();await dlg().waitFor({state:'detached'});await page.goForward();await panel('P09.S03');assert.equal(await dlg().count(),0);await act('update').click();await dlg().locator('[name=result]').fill('Đã kiểm tra lại');await save();await panel('P09.S04');await act('list').click();await panel('P09.S01');await act('back').click();await page.locator('#hn-home:visible').waitFor();});
await check('P06 intake origin without list returns to management list, then original lookup rather than result',async()=>{await page.click('.hn-scanner');await page.fill('#p06-search','SN-XP420B-BK-0008');await page.click('[data-p06-item=fixture-item-HN12346]');await page.click('[data-p06=warranty]');await panel('P09.S02');await act('fault').click();await page.click('.p09-fault-picker input[value=power-off]');await act('intake').click();await page.click('.p09-dialog [type=submit]');await panel('P09.S03');await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});await act('update').click();await dlg().locator('[name=result]').fill('Đã sửa xong');await save();await panel('P09.S04');await act('list').click();await panel('P09.S01');await act('back').click();await panel('P06.S02');assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'update-results.json'),JSON.stringify({checks,errors,production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'update-metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'update-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'update-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
