const previewBase=process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_NAVIGATION_EVIDENCE_DIR||'handoff/P09/evidence/revision-05');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const act=a=>page.locator(`[data-p09="${a}"]`).first(),p06=a=>page.locator(`[data-p06="${a}"]`).first();
const waitPanel=p=>page.locator(`[data-panel="${p}"]`).waitFor(),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
async function login(){await page.goto(previewBase+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route=warranty]');await waitPanel('P09.S01');}
async function begin(){await act('begin').click();await waitPanel('P09.S02');}
async function fault(){await act('fault').click();await page.click('.p09-fault-picker input[value=power-off]');await page.waitForFunction(()=>!history.state?.p09Modal);}
async function serial(v='HN12345'){await page.click('[data-scan-action=manual]');await page.fill('#p09-code',v);await page.locator('#p09-code').press('Enter');}
async function back(panel){await act('back').click();await waitPanel(panel);}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function capture(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
try{
await login();await begin();await fault();await page.fill('[name=note]','Nháp cần giữ khi tra cứu');await serial();await act('change-product').click();await page.fill('#p09-code','Chưa kiểm tra');
await check('Intake → lookup → header/browser Back restores exact draft/manual/scroll, never Home',async()=>{await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=270);const y=await page.locator('.p09-scroll').evaluate(e=>e.scrollTop);await act('lookup').click();await waitPanel('P06.S01');await p06('back').click();await waitPanel('P09.S02');assert.equal(await page.locator('[name=note]').inputValue(),'Nháp cần giữ khi tra cứu');assert.equal(await page.locator('#p09-code').inputValue(),'Chưa kiểm tra');assert.equal((await snap()).draft.faultId,'power-off');assert.ok(Math.abs(await page.locator('.p09-scroll').evaluate(e=>e.scrollTop)-y)<2);await act('lookup').click();await waitPanel('P06.S01');await page.goBack();await waitPanel('P09.S02');await capture('lookup-back-to-intake');});
await check('Nested P06 product/stock/history Back follows its own steps then returns to P09',async()=>{await act('lookup').click();await page.fill('#p06-search','SN-XP420B-BK-0008');await page.click('[data-p06-item=fixture-item-HN12346]');await p06('stock').click();await waitPanel('P06.S03');await p06('back').click();await waitPanel('P06.S02');await p06('history').click();await waitPanel('P06.S04');await page.goBack();await waitPanel('P06.S02');await p06('back').click();await waitPanel('P06.S01');assert.equal(await page.locator('#p06-search').inputValue(),'SN-XP420B-BK-0008');await p06('back').click();await waitPanel('P09.S02');});
await check('Choose serial in P06 returns to original intake, consumes bridge and keeps fields',async()=>{await act('lookup').click();await page.click('[data-p06-item=fixture-item-HN12346]');await p06('warranty').click();await waitPanel('P09.S02');assert.equal((await snap()).draft.item.serial,'SN-XP420B-BK-0008');assert.equal(await page.locator('[name=note]').inputValue(),'Nháp cần giữ khi tra cứu');assert.equal(await page.locator('.hn-scan-entry').count(),0);assert.equal(await act('change-product').count(),1);await back('P09.S01');assert.equal(await page.locator('.p06-app').count(),0);});
await check('Browser Back closes fault/filter/confirmation overlays before leaving the current step',async()=>{await act('filter').click();await page.goBack();await page.locator('.app-modal-host').waitFor({state:'detached'});await waitPanel('P09.S01');await begin();await act('fault').click();await page.goBack();await page.locator('.app-modal-host').waitFor({state:'detached'});await waitPanel('P09.S02');assert.equal((await snap()).draft.faultId,'power-off');await act('intake').click();await page.locator('.p09-dialog').waitFor();await page.goBack();await page.locator('.p09-dialog').waitFor({state:'detached'});await waitPanel('P09.S02');assert.equal((await snap()).writes,0);assert.equal((await snap()).request,null);await capture('confirmation-back-keeps-form');});
await check('Confirmed intake → case → Back returns to intake; next Back returns list; no loop',async()=>{await act('intake').click();await page.click('.p09-dialog [type=submit]');await waitPanel('P09.S03');assert.equal((await snap()).writes,1);await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});await back('P09.S02');assert.equal((await snap()).draft.item.serial,'SN-XP420B-BK-0008');assert.equal(await page.locator('[name=note]').inputValue(),'Nháp cần giữ khi tra cứu');await back('P09.S01');});
await check('Case Events tab → processing dialog → browser Back restores tab and unsent result',async()=>{await page.fill('#p09-query','BH-001');await page.click('[data-p09-case=BH-001]');await page.click('[data-p09-tab=events]');await act('update').click();await page.fill('.p09-dialog [name=result]','Kết quả dở cần giữ');await page.goBack();await page.locator('.p09-dialog').waitFor({state:'detached'});assert.equal(await page.locator('[data-p09-tab=events]').getAttribute('aria-selected'),'true');await act('update').click();assert.equal(await page.locator('.p09-dialog [name=result]').inputValue(),'Kết quả dở cần giữ');await page.click('.p09-dialog [type=submit]');await waitPanel('P09.S04');await act('view').click();await waitPanel('P09.S03');assert.equal(await page.locator('[data-p09-tab=events]').getAttribute('aria-selected'),'true');await capture('result-back-to-events');});
await check('Result browser Back preserves calling Parts tab; subsequent Back restores case list filter',async()=>{await page.click('[data-p09-tab=parts]');await act('update').click();await page.fill('.p09-dialog [name=result]','Đã kiểm tra hoàn tất');await page.click('.p09-dialog [type=submit]');await waitPanel('P09.S04');await page.goBack();await waitPanel('P09.S03');assert.equal(await page.locator('[data-p09-tab=parts]').getAttribute('aria-selected'),'true');await back('P09.S01');assert.equal(await page.locator('#p09-query').inputValue(),'BH-001');assert.equal(await page.locator('[data-p09-case=BH-001]').evaluate(e=>e===document.activeElement),true);});
await check('Standalone P06 → warranty → Back returns P06 item, without poisoning future Home lookup',async()=>{await page.click('[data-tab=home]');await page.click('.hn-scanner');await page.fill('#p06-search','SN-XP420B-BK-0008');await page.click('[data-p06-item=fixture-item-HN12346]');await p06('warranty').click();await waitPanel('P09.S02');await back('P06.S02');assert.match(await page.locator('.p06-hero').textContent(),/SN-XP420B-BK-0008/);await p06('back').click();await waitPanel('P06.S01');assert.equal(await page.locator('#p06-search').inputValue(),'SN-XP420B-BK-0008');await p06('back').click();await page.locator('#hn-home:visible').waitFor();});
await check('Rapid double Back consumes one step instead of jumping Home',async()=>{await login();await begin();await act('lookup').click();await waitPanel('P06.S01');await p06('back').evaluate(e=>{e.click();e.click();});await waitPanel('P09.S02');await act('back').evaluate(e=>{e.click();e.click();});await waitPanel('P09.S01');assert.equal(await page.locator('#hn-home').isVisible(),false);});
await check('UNKNOWN keeps request/session/version across Back/Forward, without reapplying serial',async()=>{await login();await begin();await serial('SN-XP420B-BK-0008');await fault();await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]','unknown');await act('intake').click();await page.click('.p09-dialog [type=submit]');await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const before=(await snap()).request;await page.goBack();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});await waitPanel('P09.S02');await page.goBack();await waitPanel('P09.S01');await page.goForward();await waitPanel('P09.S02');assert.deepEqual((await snap()).request,before);assert.equal(await act('intake').isDisabled(),true);await act('reconcile').click();await waitPanel('P09.S03');assert.equal((await snap()).receipt.requestId,before.id);await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});await back('P09.S02');assert.deepEqual((await snap()).request,before);});
await check('Forward over dismissed dialog cannot submit; logout then Back cannot resurrect journey',async()=>{await act('fault').click();await page.goBack();await page.locator('.app-modal-host').waitFor({state:'detached'});const writes=(await snap()).writes;await page.goForward();await waitPanel('P09.S02');assert.equal(await page.locator('.app-modal-host').count(),0);assert.equal((await snap()).writes,writes);await page.locator('.hn-tools>details').first().locator('summary').click();await page.click('#hn-logout');await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p09-app').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'navigation-results.json'),JSON.stringify({checks,errors,production:'NOT_RUN'},null,2));
}catch(e){await page.screenshot({path:path.join(out,'navigation-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'navigation-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
