const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const out=process.env.P17_EVIDENCE_DIR||'handoff/P17/evidence/revision-01';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[],metrics=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(9000);await mockGeography(p);
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
const snap=async owner=>JSON.parse(await p.locator(`[data-${owner}-snapshot]`).textContent());
const act=(owner,name)=>p.locator(`[data-${owner}="${name}"]`).first();
async function login(route){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click(`[data-route=${route}]`);if(route==='inbound'||route==='outbound')await p.locator(route==='inbound'?'.p04-tools':'.p05-tools').evaluate(e=>e.open=true);}
async function scan(owner,code){await p.fill(`#${owner}-code`,code);await p.press(`#${owner}-code`,'Enter');}
async function shot(n){await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function capturePanel(id){
 for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){
  await p.setViewportSize({width,height});await p.waitForTimeout(70);
  const m=await p.locator('.p17-app').evaluate(e=>{const screen=e.closest('.hn-screen'),r=screen.getBoundingClientRect(),s=e.querySelector('.p17-scroll'),foot=e.querySelector('.p17-footer').getBoundingClientRect();return {panel:e.dataset.panel,frame:[screen.offsetWidth,screen.offsetHeight],scale:r.width/screen.offsetWidth,verticalScale:r.height/screen.offsetHeight,overflow:s.scrollWidth>s.clientWidth,scrollHeight:s.scrollHeight,clientHeight:s.clientHeight,scroll:s.scrollTop,font:getComputedStyle(e).fontFamily,footerBottom:foot.bottom,frameBottom:r.bottom,controls:[...e.querySelectorAll('.p17-footer button')].map(b=>({height:b.offsetHeight,bottom:b.getBoundingClientRect().bottom})),dpr:devicePixelRatio,zoom:visualViewport.scale};});
  assert.equal(m.panel,id);assert.deepEqual(m.frame,[494,950]);assert.equal(m.overflow,false);if(process.env.P17_FIT_DEFAULT==='1')assert.ok(m.scrollHeight<=m.clientHeight+1,`${id}: default content ${m.scrollHeight} > ${m.clientHeight}`);assert.ok(Math.abs(m.scale-m.verticalScale)<.001);assert.ok(m.footerBottom<=m.frameBottom+1);assert.ok(m.controls.every(c=>c.height>=44&&c.bottom<=m.frameBottom+1));metrics.push({width,height,...m});await shot(id.replace('.','-')+`-${width}x${height}`);
 }await p.setViewportSize({width:494,height:950});
}
try{
await login('inbound');await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');let before=await snap('p04');
await check('P17.A01 invalid scan retains raw, accepted quantity and draft; S01 renders at five viewports',async()=>{await scan('p04','HN-NOT-FOUND');await p.waitForSelector('[data-panel="P17.S01"]');let s=await snap('p04');assert.deepEqual(s.accepted,before.accepted);assert.deepEqual(s.document,before.document);assert.equal(s.exception.raw,'HN-NOT-FOUND');assert.equal(await p.locator('.app-modal-host').count(),0);await capturePanel('P17.S01');await act('p04','exception-manual').click();assert.equal(await p.inputValue('#p04-code'),'HN-NOT-FOUND');assert.equal(await p.locator('#p04-code').evaluate(e=>e===document.activeElement),true);await scan('p04','HN12345');assert.equal((await snap('p04')).accepted.length,1);assert.equal((await snap('p04')).attempts.at(-1).kind,'duplicate');});
await check('S01 keyboard Quét lại and native Back preserve owner draft',async()=>{await scan('p04','HN-NOT-FOUND');await act('p04','exception-back').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('[data-panel="P04.S02"]').count(),1);await p.goBack();await p.waitForSelector('#hn-home:not([hidden])');await p.click('[data-route=inbound]');assert.deepEqual((await snap('p04')).document,before.document);assert.deepEqual((await snap('p04')).accepted,before.accepted);});
await check('P17.A04 UNKNOWN locks resend, stable request, single status read, then exact existing record',async()=>{await act('p04','next').click();await p.selectOption('[data-p04-outcome]','timeout-recorded');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');assert.equal(await act('p04','send').isDisabled(),true);assert.equal(await p.locator('.app-modal-host').count(),0);before=await snap('p04');await capturePanel('P17.S04');await act('p04','check').dblclick();await p.waitForSelector('[data-panel="P04.S04"]');let s=await snap('p04');assert.deepEqual(s.request,before.request);assert.equal(s.metrics.recordCalls,1);assert.equal(s.metrics.inventoryDelta,0);await act('p04','document').click();await p.waitForSelector('.p12-app');assert.match(await p.locator('.p12-app').innerText(),/PN-0005/);assert.ok(await p.locator('.p12-app').innerText().then(t=>t.includes('Chờ xử lý trên Web')));await shot('verified-existing-document');});
await login('inbound');await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');await act('p04','next').click();
await check('P17.A05 unavailable status remains UNKNOWN and retains request across Home/resume',async()=>{await p.selectOption('[data-p04-outcome]','status-unavailable');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');before=await snap('p04');assert.equal(await act('p04','review-reconciliation').isEnabled(),true);assert.match(await p.locator('.p17-scroll').innerText(),/Chưa có nguồn tra trạng thái/);await shot('status-unavailable');await act('p04','send').dispatchEvent('click');assert.equal((await snap('p04')).metrics.recordCalls,1);await act('p04','home').click();await p.click('[data-route=inbound]');assert.deepEqual((await snap('p04')).request,before.request);assert.equal((await snap('p04')).unknown,true);});
await login('outbound');await address(p);await act('p05','next').click();await act('p05','manual').click();await scan('p05','HN12345');before=await snap('p05');
await check('P17.A02 already exported source reason blocks mutations and preserves current document',async()=>{await scan('p05','HN99999');await p.waitForSelector('[data-panel="P17.S02"]');const s=await snap('p05');assert.deepEqual(s.accepted,before.accepted);assert.equal(s.metrics.recordCalls,0);assert.equal(s.exception.reason,'Sản phẩm đã được xuất theo phiếu PX-0004.');await capturePanel('P17.S02');await act('p05','exception-back').click();assert.equal((await snap('p05')).exception,null);assert.deepEqual((await snap('p05')).document,before.document);});
await login('nfc');await act('p07','begin').click();await p.locator('.p07-tools details').first().evaluate(e=>e.open=true);await p.selectOption('[data-p07-scenario]','conflict');await p.click('[data-p07-demo-read]');
await check('P17.A03 NFC conflict read-only detail, no stacked overlay, Escape/Back/cancel preserve mapping',async()=>{await p.waitForSelector('[data-panel="P17.S03"]');before=await snap('p07');assert.equal(before.stats.mutations,0);assert.equal(await p.locator('.app-modal-host').count(),0);await capturePanel('P17.S03');await act('p07','exception-detail').click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.match(await p.locator('.p07-dialog[open]').innerText(),/HN12346/);await p.keyboard.press('Escape');await p.waitForTimeout(100);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await act('p07','exception-detail').evaluate(e=>e===document.activeElement),true);await act('p07','exception-detail').click();await p.goBack();await p.waitForTimeout(100);assert.equal(await p.locator('.app-modal-host').count(),0);await act('p07','exception-cancel').click();assert.equal(await p.locator('[data-panel="P07.S02"]').count(),1);assert.equal((await snap('p07')).stats.mutations,0);await p.goBack();assert.equal(await p.locator('[data-panel="P07.S01"]').count(),1);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,metrics},null,2));console.log(checks.length+' groups PASS');
}catch(e){await shot('failure');fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();

