const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_SCAN_EVIDENCE_DIR||'handoff/P09/evidence/revision-02');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[],metrics=[];page.on('pageerror',e=>errors.push(e.message));
const code=()=>page.locator('#p09-code'),act=a=>page.locator(`[data-p09="${a}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
const scan=async v=>{await code().fill(v);await code().press('Enter');};
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function capture(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function geometry(prefix){return page.evaluate(p=>{const selector=p==='hn'?'.hn-scan-':'.'+p+'-',camera=document.querySelector(selector+'camera'),row=document.querySelector(p==='hn'?'.hn-scan-code-row':'.'+p+'-code-row'),input=row?.querySelector('input'),button=row?.querySelector('button');return {camera:camera.offsetHeight,input:input?.offsetHeight,button:button?.offsetHeight,width:button?.offsetWidth,radius:input&&getComputedStyle(input).borderRadius};},prefix);}
try{
await mockGeography(page);await page.addInitScript(()=>{window.hardwareCalls=0;navigator.mediaDevices.getUserMedia=()=>{window.hardwareCalls++;throw Error('No hardware');};});
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');
let p04,p05;
await check('P04/P05 current upgraded manual dimensions remain the source',async()=>{await page.click('[data-route=inbound]');await page.click('[data-p04=next]');await page.click('[data-p04=manual]');p04=await geometry('p04');await capture('reference-P04');await page.click('.p04-header [data-p04=back]');await page.click('.p04-header [data-p04=back]');await page.click('[data-route=outbound]');await address(page);await page.click('[data-p05=next]');await page.click('[data-p05=manual]');p05=await geometry('p05');await capture('reference-P05');assert.deepEqual(p04,p05);await page.click('.p05-header [data-p05=back]');await page.click('.p05-header [data-p05=back]');});
await page.click('[data-route=warranty]');await act('begin').click();
await check('P09 idle camera/actions/header align and hardware stays disabled',async()=>{assert.equal(await page.locator('.hn-scan-actions button').first().isDisabled(),true);assert.equal(await page.locator('.hn-scan-camera').evaluate(e=>e.offsetHeight),220);assert.equal(await page.locator('.p09-header').evaluate(e=>e.offsetHeight),63);assert.equal(await page.locator('.p09-dialog').count(),0);assert.match(await page.locator('.p09-scan-empty').textContent(),/Chưa xác định sản phẩm/);await page.mouse.click(5,970);await capture('01-idle');});
await check('Inline form matches P04/P05 measured geometry; empty/invalid are local only',async()=>{await page.click('[data-scan-action=manual]');assert.deepEqual(await geometry('hn'),p05);assert.equal(await code().evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.p09-dialog').count(),0);await scan('  ');assert.equal(await code().getAttribute('aria-invalid'),'true');assert.equal((await snap()).draft.item,null);assert.equal((await snap()).writes,0);await scan('XP-420B');assert.match(await page.locator('#p09-code-feedback').textContent(),/SKU/);assert.equal(await code().inputValue(),'XP-420B');assert.equal(await page.locator('.p09-feedback').count(),0);await capture('02-invalid');});
await check('Valid clears code/focus; same serial is not a second product; draft fields survive',async()=>{await page.click('[data-p09=fault]');await page.locator('.p09-fault-picker input[value="power-off"]').click();await page.fill('[name=note]','Giữ nguyên ghi chú');await scan('HN12345');assert.equal(await code().inputValue(),'');assert.equal(await code().evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('#p09-code-feedback').getAttribute('data-tone'),'valid');assert.equal(await act('intake').isEnabled(),true);assert.equal(await page.locator('[name=note]').inputValue(),'Giữ nguyên ghi chú');await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=0);await code().evaluate(e=>e.blur());await capture('03-valid');await scan('HN12345');assert.equal(await page.locator('#p09-code-feedback').getAttribute('data-tone'),'duplicate');assert.equal(await code().getAttribute('aria-invalid'),'false');assert.equal((await snap()).writes,0);assert.equal((await snap()).draft.item.serial,'HN12345');});
await check('Escape/Collapse/Back preserve raw and fault; unverified replacement cannot submit',async()=>{await code().fill('SN-XP420B-BK-0008');assert.equal(await act('intake').isDisabled(),true);await act('intake').evaluate(e=>{e.disabled=false;e.click();});assert.equal(await page.locator('.p09-dialog').count(),0);await code().press('Escape');assert.equal(await code().count(),0);assert.equal(await page.locator('[data-scan-action=manual]').evaluate(e=>e===document.activeElement),true);await page.click('[data-scan-action=manual]');assert.equal(await code().inputValue(),'SN-XP420B-BK-0008');await page.click('[data-scan-action=collapse]');await act('back').click();await act('begin').click();await page.click('[data-scan-action=manual]');assert.equal(await code().inputValue(),'SN-XP420B-BK-0008');assert.equal(await page.locator('#p09-fault-value').textContent(),'Máy không lên nguồn');});
await check('IME Enter does not select or submit; changing serial updates exact context only',async()=>{const before=(await snap()).draft.item.serial;await code().evaluate(e=>e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true})));assert.equal((await snap()).draft.item.serial,before);await code().press('Enter');assert.equal((await snap()).draft.item.serial,'SN-XP420B-BK-0008');assert.equal((await snap()).writes,0);assert.equal(await page.locator('[name=note]').inputValue(),'Giữ nguyên ghi chú');});
await check('Six viewports preserve shell, input/CTA geometry, internal scroll and footer',async()=>{await scan('HN12345');for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=0);await code().evaluate(e=>e.blur());const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),a=document.querySelector('.p09-app'),scroll=a.querySelector('.p09-scroll'),f=a.querySelector('.p09-footer'),row=a.querySelector('.hn-scan-code-row'),b=row.querySelector('button'),r=s.getBoundingClientRect();return{viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],dpr:devicePixelRatio,font:getComputedStyle(a).fontFamily,overflow:scroll.scrollWidth>scroll.clientWidth||document.documentElement.scrollWidth>innerWidth,rowOverflow:row.scrollWidth>row.clientWidth,buttonOverflow:b.scrollWidth>b.clientWidth,footerInside:f.getBoundingClientRect().bottom<=r.bottom+1,contentAboveFooter:scroll.getBoundingClientRect().bottom<=f.getBoundingClientRect().top+1,camera:a.querySelector('.hn-scan-camera').offsetHeight,input:row.querySelector('input').offsetHeight};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.overflow&&!m.rowOverflow&&!m.buttonOverflow&&m.footerInside&&m.contentAboveFooter);assert.equal(m.camera,128);assert.equal(m.input,52);metrics.push(m);await capture(`manual-${w}x${h}`);}await page.setViewportSize({width:494,height:1000});await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await capture('form-bottom');});
await check('UNKNOWN locks manual selection while retaining request and draft; no camera requests',async()=>{await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]','unknown');await act('intake').click();await page.click('.p09-dialog [type=submit]');await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const before=await snap();assert.equal(await page.locator('[data-scan-action=manual]').isDisabled(),true);assert.equal(await code().getAttribute('readonly'),'');assert.equal(await act('lookup').isDisabled(),true);await page.locator('#p09-manual-form').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.deepEqual((await snap()).request,before.request);assert.equal((await snap()).draft.item.serial,before.draft.item.serial);assert.equal(await page.evaluate(()=>window.hardwareCalls),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'scan-results.json'),JSON.stringify({checks,errors,sourceGeometry:{P04:p04,P05:p05},hardware:'NOT_RUN',production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'scan-metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'scan-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'scan-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
