const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P21/evidence/revision-01';fs.mkdirSync(out+'/after',{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));
const snap=async()=>JSON.parse(await p.locator('[data-p21-snapshot]').textContent()),issue=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent()),a=n=>p.locator(`[data-p21="${n}"]`);
async function shot(name){await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/after/'+name+'.png'});}
async function test(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function demo(scene){await p.click(`[data-p21-demo="${scene}"]`);await p.waitForSelector('.p21-app');await p.waitForTimeout(350);}
async function route(q){await p.evaluate(q=>location.hash='#p02/component-resume?'+q,q);await p.waitForSelector('.p21-app');await p.waitForTimeout(350);}
try{
// Capture existing source at the same browser conditions. Legacy viewport is390px (recorded, not stretched).
for(const scene of ['drafts','resume','reconcile','post-check']){await p.goto('http://localhost:8766/flows/warranty-components/?mode=screen&scene='+scene);await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:out+'/before/'+scene+'.png'});}
await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p21-tools').evaluate(e=>e.open=true);
await test('All four P21 panels rendered and captured',async()=>{for(const [i,scene]of ['drafts','resume','reconcile','post-check'].entries()){await demo(scene);await p.waitForSelector(`[data-panel="P21.S0${i+1}"]`);await shot('P21-S0'+(i+1)+'-494x950');}});
await test('A01/A02 resume owner ID/version/session and recorded locks through P19',async()=>{await demo('resume');const before=(await snap()).current;assert.equal(before.verification,'verified');await a('review').click();await p.waitForSelector('[data-panel="P19.S03"]');assert.equal(await p.locator('[data-p19=remove]').count(),0);assert.equal((await issue()).document.documentId,before.document.documentId);await p.goBack();await p.waitForSelector('.p21-app');await p.waitForTimeout(300);const after=(await snap()).current;assert.deepEqual(after.document,before.document);assert.deepEqual(after.scanSessionId,before.scanSessionId);await a('scan').click();await p.waitForSelector('[data-panel="P19.S01"]');assert.equal((await issue()).document.documentId,'XLK-0002');});
await test('A03 unknown codes keep references and block scan; guide Back/Escape/backdrop/focus',async()=>{await demo('reconcile');const before=(await snap()).current;assert.equal(await a('scan').count(),0);await a('guide').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/XLK-0002/);await p.locator('.app-modal-host').click({position:{x:3,y:3},force:true});assert.equal(await p.locator('.hn-action-dialog[open]').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(160);assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);await a('guide').click();await p.goBack();await p.waitForTimeout(160);assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);assert.equal(await a('guide').evaluate(e=>e===document.activeElement),true);assert.deepEqual((await snap()).current.document,before.document);await p.selectOption('[data-p21-source]','ready');await a('reload').click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');});
await test('A04 timeout Post check opens same confirmed receipt, no resubmit',async()=>{await demo('post-check');const before=(await snap()).current;await a('check').evaluate(e=>{e.click();e.click();});await p.waitForSelector('[data-panel="P19.S04"]');const after=await issue();assert.equal(after.receipt.requestId,before.request.id);assert.equal(after.receipt.lines.length,2);assert.equal(after.receipt.request.documentId,'XLK-0002');assert.equal(await p.locator('[data-p19=post]').count(),0);await shot('A04-confirmed');});
await test('P19 live → P21 reopen → P20 pending uses exact document; Home link',async()=>{await p.locator('.p19-tools:not(.p21-tools)').evaluate(e=>e.open=true);await p.click('[data-p19-open]');await p.click('[data-scan-action=manual]');await p.fill('#p19-code','LK0001-HN001');await p.locator('#p19-manual-form button[type=submit]').click();const before=await issue();await p.click('[data-p19=back]');await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.equal((await snap()).current.document.documentId,before.document.documentId);await a('back').click();await p.waitForSelector('[data-panel="P21.S01"]');assert.equal((await snap()).drafts.length,1);await a('back').click();await p.waitForSelector('#hn-home:not([hidden])');await p.click('[data-resume-operation=warranty]');await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.equal((await snap()).current.document.documentId,before.document.documentId);await p.evaluate(()=>location.hash='#p02/component-history?case=BH-001');await p.waitForSelector('[data-p20=issue]');await p.click('[data-p20=issue]');await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.equal((await snap()).current.document.documentId,before.document.documentId);});
await test('Version conflict blocks deep linked P19 without losing draft',async()=>{await p.selectOption('[data-p21-source]','conflict');await a('back').click();await a('open').click();await p.waitForSelector('[data-panel="P21.S03"]');const before=(await snap()).current;await p.evaluate(s=>location.hash='#p02/component-issue?'+new URLSearchParams({case:s.caseId,doc:s.document.documentId,panel:1}),before);await p.waitForSelector('.p19-blocked');assert.equal(await p.locator('[data-p19=post]').count(),0);await route('panel=2&doc='+encodeURIComponent(before.document.documentId));await p.selectOption('[data-p21-source]','ready');await a('reload').click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.deepEqual((await snap()).current.lines,before.lines);});
await test('Closed case UNKNOWN is read-only and check still works',async()=>{await a('review').click();await p.selectOption('[data-p19-outcome]','timeout-posted');await p.click('[data-p19=post]');await p.waitForSelector('.hn-action-dialog[open]');await p.getByRole('button',{name:'Để sau',exact:true}).click();await p.waitForTimeout(200);const before=await issue();await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(c=>c.id==='BH-001');m.writeWarrantyCase({...c,status:'Đã trả khách'});});await p.click('[data-p19=back]');await p.waitForSelector('[data-panel="P21.S04"]');await a('check').click();await p.waitForSelector('[data-panel="P19.S04"]');const after=await issue();assert.equal(after.metrics.post,before.metrics.post);assert.equal(after.receipt.requestId,before.request.id);await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.resetWarrantyCases();});});
await test('Missing ID cannot create; posted draft cannot scan through Back',async()=>{await route('panel=2&doc=NONEXISTENT');assert.match(await p.locator('.p21-app').innerText(),/Không tìm thấy đúng phiếu/);assert.equal(await a('scan').count(),0);await route('panel=1');assert.equal((await snap()).drafts.length,0);});
await test('20 panel/viewport combinations preserve494×950 and footer; all actions44px',async()=>{const metrics=[];for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const scene of ['drafts','resume','reconcile','post-check']){await demo(scene);const m=await p.locator('.hn-screen').evaluate(e=>{const sc=e.querySelector('.p21-scroll'),f=e.querySelector('.p21-footer'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return {width:e.offsetWidth,height:e.offsetHeight,overflow:sc.scrollWidth>sc.clientWidth+1,footer:fr.bottom<=r.bottom+1&&fr.top>=r.top,smallTargets:[...e.querySelectorAll('.p21-app button')].filter(b=>b.getClientRects().length&&b.offsetHeight<44).map(b=>b.dataset.p21)};});assert.equal(m.width,494);assert.equal(m.height,950);assert.equal(m.overflow,false);assert.equal(m.footer,true);assert.deepEqual(m.smallTargets,[]);metrics.push({viewport:[width,height],scene,...m});}await shot('viewport-'+width+'x'+height);}fs.writeFileSync(out+'/after/layout.json',JSON.stringify(metrics,null,2));});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/after/browser-results.json',JSON.stringify({checks,errors},null,2));
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/after/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();

