const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8774',out=path.resolve('handoff/P04/evidence/revision-08/qa');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}});const checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const act=n=>page.locator(`[data-p04="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});};
const shot=async name=>{await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});};
async function login(){await page.goto(base+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();}
async function dismiss(){const dialog=page.locator('.hn-action-dialog[open]');await dialog.getByRole('button',{name:'Đã hiểu',exact:true}).click();await dialog.waitFor({state:'detached'});}
async function scan(raw){await page.fill('#p04-code',raw);await page.locator('#p04-code').press('Enter');}
try{
 await login();await act('next').click();
 await check('Context presents exact document/type/supplier; shared dialog Back/focus/no backdrop dismissal',async()=>{assert.match(await page.locator('.p04-scan-context').textContent(),/PN-0005.*Nhập sản phẩm.*Minh Phát/);const before=await snap();await act('context').click();const dialog=page.locator('.hn-action-dialog[open]');await dialog.waitFor();assert.match(await dialog.textContent(),/NCC-001/);await page.locator('.app-modal-host').dispatchEvent('click');assert.equal(await dialog.count(),1);await page.keyboard.press('Tab');assert.equal(await dialog.evaluate(e=>e.contains(document.activeElement)),true);await page.goBack();await dialog.waitFor({state:'detached'});assert.equal(await act('context').evaluate(e=>e===document.activeElement),true);assert.deepEqual(await snap(),before);await shot('01-context');});
 await check('Empty filters have reset path without data changes',async()=>{await page.locator('[data-p04-filter="invalid"]').click();assert.match(await page.locator('#p04-scan-list').textContent(),/Chưa có mã/);assert.equal((await snap()).attempts.length,0);await page.locator('[data-p04-filter="all"]').click();});
 await page.locator('.p04-tools summary').click();await act('batch').click();await act('manual').click();await scan('NOT-A-CODE');await act('close-manual').click();
 await check('Counter filters display correct subsets, keep all totals and payload unchanged',async()=>{const original=await snap();for(const [kind,n]of [['valid',4],['duplicate',1],['invalid',1],['all',4]]){await page.locator(`[data-p04-filter="${kind}"]`).click();assert.equal(await page.locator('.p04-attempt').count(),n);assert.equal(await page.locator(`[data-p04-filter="${kind}"]`).getAttribute('aria-pressed'),'true');assert.deepEqual(await snap(),original);await shot(`02-filter-${kind}`);}await page.locator('[data-p04-filter="valid"]').click();await act('all').click();assert.equal(await page.locator('.p04-attempt').count(),11);assert.deepEqual((await snap()).accepted,original.accepted);});
 await check('Latest row highlight is bounded, reduced-motion safe, and input focus remains',async()=>{await page.locator('[data-p04-filter="all"]').click();await act('manual').click();await page.emulateMedia({reducedMotion:'reduce'});await scan('HN12345');assert.equal(await page.locator('#p04-code').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.p04-recent-attempt').count(),1);assert.equal(await page.locator('.p04-recent-attempt').evaluate(e=>getComputedStyle(e).animationName),'none');await page.waitForFunction(()=>!document.querySelector('.p04-recent-attempt'));await page.locator('[data-p04-filter="invalid"]').click();assert.equal(await page.locator('.p04-recent-attempt').count(),0);await page.emulateMedia({reducedMotion:'no-preference'});});
 await check('SKU disclosures only contain matching accepted serials, independent of scan filter',async()=>{await act('next').click();assert.equal(await page.locator('[data-p04-sku]').count(),3);for(const [sku,n]of [['XP-420B',5],['ZD421',4],['DS2208',2]]){const b=page.locator(`[data-p04-sku="${sku}"]`);await b.click();const region=page.locator('#'+await b.getAttribute('aria-controls'));assert.equal(await region.locator('li').count(),n);assert.equal(await b.getAttribute('aria-expanded'),'true');}assert.equal(await page.locator('.p04-serials li:visible').count(),11);assert.equal(await page.locator('.p04-serials').getByText('HN12345',{exact:true}).count(),1);await shot('03-serials');await page.locator('[data-p04="back"]').first().click();await act('next').click();assert.equal(await page.locator('[data-p04-sku][aria-expanded="true"]').count(),3);});
 await check('Success new-run button returns clean step1 with fresh identity and no extra record',async()=>{await act('send').click();await page.locator('[data-panel="P04.S04"]').waitFor();const done=await snap();await shot('04-completed');await act('new-run').click();const fresh=await snap();assert.equal(fresh.step,1);assert.notEqual(fresh.document.documentId,done.document.documentId);assert.equal(fresh.request,null);assert.equal(fresh.metrics.recordCalls,done.metrics.recordCalls);assert.equal(fresh.attempts.length,0);assert.equal(fresh.document.note,'');await act('next').click();assert.equal(await page.locator('[data-p04-filter="all"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#p04-code').count(),0);});
 await check('Resuming draft identifies document and retained count without creating a new run',async()=>{await act('manual').click();await scan('HN12345');const draft=await snap();await page.goBack();await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).document.documentId,draft.document.documentId);assert.match(await page.locator('.p04-scan-context').textContent(),/Tiếp tục phiếu dở.*Đã giữ 1 mã hợp lệ/);await shot('05-resume');});
 await check('UNKNOWN blocks next-run; explicit reconciliation then enables it',async()=>{await act('next').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await act('send').click();await page.locator('.hn-action-dialog[open]').waitFor();assert.equal(await act('new-run').count(),0);await page.getByRole('button',{name:'Để sau',exact:true}).click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});const original=await snap();await act('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.deepEqual((await snap()).request,original.request);assert.equal((await snap()).metrics.recordCalls,original.metrics.recordCalls);await act('new-run').click();assert.equal((await snap()).step,1);});
 await check('Confirmed failure uses shared dialog and offers guarded new run without retry',async()=>{await act('next').click();await act('manual').click();await scan('HN12345');await act('next').click();await page.selectOption('[data-p04-outcome]','failed');await act('send').click();await page.locator('.hn-action-dialog[open]').waitFor();await dismiss();const failed=await snap();await shot('06-failed');await act('new-run').click();assert.equal((await snap()).step,1);assert.equal((await snap()).metrics.recordCalls,failed.metrics.recordCalls);assert.notEqual((await snap()).document.documentId,failed.document.documentId);});
 await check('Six viewport matrix keeps context, filters, SKU controls and result CTA in locked shell',async()=>{await act('next').click();await act('batch').click();for(const [w,h]of [[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.evaluate(()=>scrollTo(0,0));const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),r=s.getBoundingClientRect(),footer=document.querySelector('.p04-footer').getBoundingClientRect();return{viewport:[innerWidth,innerHeight],layout:[s.offsetWidth,s.offsetHeight],overflow:document.documentElement.scrollWidth>innerWidth,footer:footer.bottom<=r.bottom+1};});assert.deepEqual(m.layout,[494,950]);assert.equal(m.overflow,false);assert.ok(m.footer);metrics.push(m);await shot(`07-scan-${w}x${h}`);}await act('next').click();await page.locator('[data-p04-sku="XP-420B"]').click();await shot('08-review-expanded');});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({groups:checks.length,viewports:metrics.length,errors}));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
