const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.SYNC_ROOT_EVIDENCE_DIR||'handoff/dialog-sync-2026-09-28/root/evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const sizes=[[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]],dialog=()=>page.locator('.app-modal-host dialog[open]');
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function close(){await dialog().locator('button').last().click();await page.waitForFunction(()=>!document.querySelector('.app-modal-host')&&!Object.keys(history.state||{}).some(k=>/Feedback|hnNameDialog/.test(k)));}
async function fresh(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.locator('#username').waitFor();}
async function login(){await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.locator('#start').waitFor();}
async function home(){await page.click('#start');await page.locator('#hn-home:visible').waitFor();}
async function capture(name,shell='.hn-screen'){await page.evaluate(()=>scrollTo(0,0));await page.locator(shell).screenshot({path:path.join(out,name+'.png')});}
async function audit(name,shell,content,footer){await page.evaluate(()=>{scrollTo(0,0);return new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});const m=await page.evaluate(({shell,content,footer})=>{const s=document.querySelector(shell),c=document.querySelector(content),f=document.querySelector(footer),r=s.getBoundingClientRect(),fr=f.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],fits:r.bottom<=innerHeight+1&&r.left>=-1&&r.right<=innerWidth+1,overflow:document.documentElement.scrollWidth>innerWidth,content:[c?.clientHeight,c?.scrollHeight],footerInside:fr.bottom<=r.bottom+1};},{shell,content,footer});assert.deepEqual(m.shell,[494,950]);assert.ok(m.fits&&!m.overflow&&m.footerInside,JSON.stringify(m));const beforeFooter=(await page.locator(footer).boundingBox()).y;await page.locator(content).hover();await page.mouse.wheel(0,900);await page.waitForTimeout(70);assert.ok(Math.abs((await page.locator(footer).boundingBox()).y-beforeFooter)<=1,name+' wheel footer stable');assert.equal(await page.evaluate(()=>scrollY),0,name+' no outer scroll');if(m.content[1]<=m.content[0]+1)assert.equal(await page.locator(content).evaluate(e=>e.scrollTop),0,name+' no surplus scrolling');await page.mouse.wheel(0,-900);await page.waitForTimeout(70);metrics.push({name,...m,wheelStable:true});await capture(name,shell);}
async function auditAll(prefix,shell,content,footer){for(const [w,h]of sizes){await page.setViewportSize({width:w,height:h});await audit(`${prefix}-${w}x${h}`,shell,content,footer);}await page.setViewportSize({width:494,height:1000});}
async function contained(){return dialog().evaluate(d=>{const r=d.getBoundingClientRect(),s=d.closest('.screen,.hn-screen').getBoundingClientRect();return r.left>=s.left&&r.top>=s.top&&r.right<=s.right+1&&r.bottom<=s.bottom+1;});}
async function p03(kind){await page.locator('.p03-tools').evaluate(e=>e.open=true);await page.locator(`[data-p03-open=${kind}]`).click();await page.locator('.p03-dialog').waitFor();}
try{
await fresh();
await check('P01 S01 uniform shell and fixed footer across six viewports',()=>auditAll('P01-S01','#app .screen','#login-form','#app .footer'));
await check('P01 required fields remain field validation without action dialog',async()=>{await page.click('#submit');assert.equal(await page.locator('#username').getAttribute('aria-invalid'),'true');assert.equal(await dialog().count(),0);});
await check('P01 rejected credentials use contained dialog, no shifting body message, Back keeps login',async()=>{await page.fill('#username','minhanh');await page.fill('#password','not-correct');await page.click('#submit');await dialog().waitFor();assert.ok(await contained());assert.equal(await page.locator('#message').textContent(),'');await capture('P01-login-rejected','#app .screen');await page.goBack();await dialog().waitFor({state:'detached'});await page.locator('#username').waitFor();});
await check('P01 recovery notice is dialog; backdrop keeps focus and Escape cancels',async()=>{await page.click('#forgot');await dialog().waitFor();await page.locator('.app-modal-host').click({position:{x:1,y:1}});assert.equal(await dialog().count(),1);await page.keyboard.press('Escape');await dialog().waitFor({state:'detached'});});
await login();
await check('P01 S02 fits six viewports and no inherited action error shifts it',()=>auditAll('P01-S02','#app .screen','#app .card','#app .footer'));
await check('P01 logout confirmation supports cancel with session kept',async()=>{await page.click('#logout');await dialog().waitFor();assert.ok(await contained());assert.equal(await dialog().locator('[data-action-dialog=cancel]').count(),1);await capture('P01-logout-confirm','#app .screen');await dialog().locator('[data-action-dialog=cancel]').click();await page.waitForFunction(()=>!history.state?.hnAuthFeedback);await page.locator('#start').waitFor();});
await home();
await check('P02 Home retains shell/nav in six viewports',()=>auditAll('P02-S01','.hn-screen','.hn-main','.hn-nav'));
await check('P02 full-name dialog remains inside app and native Back closes first',async()=>{await page.click('.hn-name');await dialog().waitFor();assert.ok(await contained());assert.equal(await page.locator('#hn-full-name').textContent(),'Minh Anh');await capture('P02-name-dialog');await page.goBack();await dialog().waitFor({state:'detached'});assert.equal(await page.locator('.hn-name').evaluate(e=>e===document.activeElement),true);});
await check('P02 pending destinations report dialog over current screen without invented panel',async()=>{await page.click('[data-route=notifications]');await dialog().waitFor();assert.ok((await dialog().innerText()).includes('P13'));assert.equal(await page.locator('#hn-home:visible').count(),1);await close();});
await check('P03 four preserved panel IDs and fixed header/nav across six viewports',async()=>{for(const [kind,p]of [['picker',1],['local',2],['stopped',3],['discard',4]]){await p03(kind);assert.equal(await page.locator('.p03-dialog').getAttribute('data-panel'),`P03.S0${p}`);await auditAll(`P03-S0${p}`,'.hn-screen','.p03-dialog','.hn-nav');if(p===4){assert.ok(await page.locator('.hn-nav').evaluate(e=>e.inert));assert.equal(await page.locator('[data-p03-action=cancel]').evaluate(e=>e===document.activeElement),true);await page.click('[data-p03-action=cancel]');}if(p===3){await page.click('[data-p03-action=home]');await page.selectOption('[data-p03-fixture=warehouse]','active');}else await page.click('[data-p03-action=cancel]');}});
await check('P03 verified local discard presents result dialog without appended toast',async()=>{await p03('discard');await page.click('[data-p03-action=confirmDiscard]');await dialog().waitFor();assert.match(await dialog().innerText(),/Đã bỏ/);assert.equal(await page.locator('.p03-feedback').count(),0);await capture('P03-discard-result');await close();});
await check('P03 save failure updates the existing dialog body, preserving draft and retry',async()=>{await page.selectOption('[data-p03-fixture=save]','failed');await p03('local');const before=JSON.parse(await page.locator('[data-p03-snapshot]').textContent()).document;await page.click('[data-p03-action=save]');await page.waitForFunction(()=>document.querySelector('#p03-description')?.textContent.includes('Chưa lưu'));assert.equal(await page.locator('.app-modal-host').count(),0);assert.equal(await page.locator('.p03-feedback').count(),0);assert.deepEqual(JSON.parse(await page.locator('[data-p03-snapshot]').textContent()).document,before);await capture('P03-save-failed');await page.click('[data-p03-action=cancel]');});
await check('P03 confirmed save presents acknowledgment on Home after modal route settles',async()=>{await page.selectOption('[data-p03-fixture=save]','confirmed');await p03('local');await page.click('[data-p03-action=save]');await dialog().waitFor();assert.match(await dialog().innerText(),/Đã lưu nháp/);assert.equal(await page.locator('.p03-dialog').count(),0);await close();});
await check('P03 UNKNOWN retains identity and exposes reconcile in its existing dialog',async()=>{await page.selectOption('[data-p03-fixture=save]','unknown');await p03('local');const before=JSON.parse(await page.locator('[data-p03-snapshot]').textContent()).document;await page.click('[data-p03-action=save]');await page.locator('[data-p03-action=checkSave]:visible').waitFor();assert.match(await page.locator('#p03-description').textContent(),/Chưa xác định/);assert.deepEqual(JSON.parse(await page.locator('[data-p03-snapshot]').textContent()).document,before);await page.click('[data-p03-action=cancel]');});
await page.click('[data-tab=profile]');
await check('P10 four panels retain layout in six viewports',async()=>{for(const p of [1,2,3,4]){if(p!==1)await page.click(`[data-p10=${p===2?'edit':p===3?'rights':'security'}]`);await auditAll(`P10-S0${p}`,'.hn-screen','.p10-scroll',p===2?'.p10-footer':'.hn-nav');if(p!==1)await page.click('[data-p10=back]');}});
await check('P10 shared logout dialog locks backdrop, cancels with Back, preserves red confirm',async()=>{await page.click('[data-p10=logout]');await dialog().waitFor();assert.ok(await contained());assert.equal(await dialog().locator('[data-p10=dialog-confirm]').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(180, 35, 24)');await page.locator('.app-modal-host').click({position:{x:1,y:1}});assert.equal(await dialog().count(),1);await capture('P10-logout-confirm');await page.goBack();await dialog().waitFor({state:'detached'});assert.equal(await page.locator('[data-panel="P10.S01"]').count(),1);});
await check('P01 UNKNOWN exposes defer/reconcile guidance without replaying start',async()=>{await fresh();await page.locator('.preview-tools details').evaluate(e=>e.open=true);await page.selectOption('#scenario','start-unknown');await login();await page.click('#start');await dialog().waitFor();assert.equal(await dialog().locator('[data-action-dialog=cancel]').textContent(),'Để sau');assert.equal(await dialog().locator('[data-action-dialog=confirm]').textContent(),'Đối chiếu');await dialog().locator('[data-action-dialog=confirm]').click();await page.getByRole('heading',{name:'Đối chiếu phiên',exact:true}).waitFor();assert.ok(await page.locator('#start').isDisabled());await capture('P01-unknown-guidance','#app .screen');await close();assert.ok(await page.locator('#start').isDisabled());});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(`${checks.length} groups PASS; ${metrics.length} panel viewport captures`);
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
