const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.LONG_DIALOG_OUT||'handoff/ux-audit-2026-09-30-r02/shared/long-regression');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),p=await browser.newPage({viewport:{width:494,height:1000}});p.setDefaultTimeout(20000);const checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
try{await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-screen').waitFor();
for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width:w,height:h});await p.evaluate(async()=>{const {openActionDialog}=await import('/flows/shared/action-dialog.mjs');window.__longTitle=('Đối tượng <&> rất dài\n').repeat(100);window.__message='Dòng 1\n\nDòng 3 giữ khoảng trắng  và hậu quả cần đọc.';window.__actionCount=0;window.__auditModal=openActionDialog({screen:document.querySelector('.hn-screen'),title:window.__longTitle,message:window.__message,cancelLabel:'Hủy',confirmLabel:'Xác nhận',onConfirm:()=>window.__actionCount++});});await p.waitForTimeout(70);const heading=p.locator('dialog[open] h2');await heading.focus();await p.keyboard.press('End');await p.keyboard.press('PageDown');await p.waitForTimeout(160);const m=await p.locator('dialog[open]').evaluate(d=>{const a=document.querySelector('.hn-screen').getBoundingClientRect(),head=d.querySelector('h2'),body=d.querySelector('.app-modal-body'),footer=d.querySelector('footer').getBoundingClientRect();return{headScrolled:head.scrollTop>0,titleExact:head.textContent===window.__longTitle,messageExact:body.querySelector('p').textContent===window.__message,whiteSpace:getComputedStyle(body.querySelector('p')).whiteSpace,bodyHeight:body.clientHeight,footerInside:footer.bottom<=a.bottom+1,viewport:[innerWidth,innerHeight]};});metrics.push(m);assert.ok(m.headScrolled&&m.titleExact&&m.messageExact&&m.bodyHeight>0&&m.footerInside&&m.whiteSpace==='pre-wrap',JSON.stringify(m));await p.locator('.hn-screen').screenshot({path:path.join(out,`dialog-${w}x${h}.png`)});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>window.__actionCount),0);}checks.push({name:'Long title full keyboard scroll and exact message in six viewports',status:'PASS'});
await p.setViewportSize({width:360,height:800});await p.evaluate(async()=>{const {openHistoryPicker}=await import('/flows/history/history-picker.mjs');window.__scope=('MÃ-không-cắt-Ánh<&>').repeat(180);window.__auditModal=openHistoryPicker({screen:document.querySelector('.hn-screen'),mode:'filter',filters:{type:'all',status:'all',from:'',to:''},day:'2026-09-30',scopeLabel:window.__scope,quickRanges:true,onApply:()=>{},onClose:()=>{}});});await p.locator('.p08-picker-context').focus();await p.keyboard.press('End');await p.waitForTimeout(160);assert.ok(await p.locator('.p08-picker-context').evaluate(n=>n.scrollTop>0&&n.scrollWidth<=n.clientWidth+1&&n.textContent===window.__scope));await p.locator('.hn-screen').screenshot({path:path.join(out,'picker-scope-scrolled.png')});await p.keyboard.press('Escape');checks.push({name:'Long picker context full keyboard read without horizontal clipping',status:'PASS'});
assert.deepEqual(errors,[]);
}catch(e){checks.push({name:'runner',status:'FAIL',error:e.stack});process.exitCode=1;await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({checks,metrics,errors}));await browser.close();}})();
