const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const before=process.argv.includes('--before'),out='handoff/motion/M18/'+(before?'before':'evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'}),p=await c.newPage(),r={mode,checks:[],geometry:{},text:{},errors:[]};results.push(r);p.setDefaultTimeout(16000);p.on('pageerror',e=>r.errors.push(e.message));await c.tracing.start({screenshots:true,snapshots:true,sources:true});await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
await p.addInitScript(()=>{window.fx=[];window.samples=[];window.progressFrames=[];window.calls={begin:0,event:0,cancel:0,caseWrites:0,hardware:0,httpWrites:0};window.longTasks=[];window.motionListeners=0;const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){const rec={primitive:this.dataset.motionPrimitive||'',duration:options.duration,frames,cancelled:false};fx.push(rec);const a=animate.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{rec.cancelled=true;return cancel();};if(rec.primitive.startsWith('Attachment')||rec.primitive.startsWith('Viewer')||rec.primitive.startsWith('Handoff')){const node=this,start=performance.now();const tick=()=>{samples.push({primitive:rec.primitive,ms:performance.now()-start,opacity:getComputedStyle(node).opacity});if(node.isConnected&&performance.now()-start<190)requestAnimationFrame(tick);};requestAnimationFrame(tick);}return a;};const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','attachmentVisibility'].includes(f?.name))motionListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','attachmentVisibility'].includes(f?.name))motionListeners--;return remove.call(this,t,f,o);};new PerformanceObserver(l=>longTasks.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{calls.hardware++;throw Error('No M18 hardware');};window.NDEFReader=class{constructor(){calls.hardware++;throw Error('No M18 NFC');}};window.sampleProgress=id=>{const start=performance.now();const tick=()=>{const row=document.querySelector(`[data-file-id="${id}"]`),bar=row?.querySelector('progress'),fill=row?.querySelector('.p18-progress-fill'),track=row?.querySelector('.p18-progress-track');if(bar&&fill&&track)progressFrames.push({ms:performance.now()-start,confirmed:bar.value,visual:100*fill.getBoundingClientRect().width/track.getBoundingClientRect().width,text:row.querySelector('[data-progress-text]')?.textContent,mode:row.closest('[data-hn-motion-mode]')?.dataset.hnMotionMode});if(performance.now()-start<180)requestAnimationFrame(tick);};requestAnimationFrame(tick);};});
p.on('request',q=>{if(!['GET','HEAD','OPTIONS'].includes(q.method()))r.httpWriteRequest=q.url();});
await p.route('**/attachments/model.mjs',async route=>{const response=await route.fetch();let s=await response.text();s=s.replace('begin(id){','begin(id){window.calls.begin++;').replace('cancel(id){','cancel(id){window.calls.cancel++;').replace('event({id,taskId,token,loaded,total,result}){','event({id,taskId,token,loaded,total,result}){window.calls.event++;if(!result)window.sampleProgress(id);');await route.fulfill({response,body:s});});
await p.route('**/shared/warranty-cases.mjs',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('export function writeWarrantyCase(row){','export function writeWarrantyCase(row){window.calls.caseWrites++;')});});
const act=a=>p.locator(`[data-p18="${a}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p18-snapshot]').textContent()),painted=()=>p.waitForFunction(()=>document.querySelector('.p18-paper')?.getAttribute('aria-busy')==='false');
async function demo(name){await p.locator('.p18-tools').evaluate(e=>e.open=true);await p.click(`[data-p18-demo=${name}]`);}
async function capture(id){await p.waitForTimeout(260);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.p18-app img[src]')].map(i=>i.decode().catch(()=>{})));scrollTo(0,0);});r.geometry[id]=await p.locator('.p18-app').evaluate(app=>{const shell=app.closest('.hn-screen'),s=shell.getBoundingClientRect();return {frame:[shell.offsetWidth,shell.offsetHeight],rects:Object.fromEntries(['.p18-header','.p18-scroll','.p18-footer','.p18-context','.p18-paper','.p18-slots','.hn-nav'].map(q=>{const e=shell.querySelector(q);if(!e)return[q,null];const b=e.getBoundingClientRect();return[q,[b.x-s.x,b.y-s.y,b.width,b.height]];})),overflow:app.querySelector('.p18-scroll').scrollWidth>app.querySelector('.p18-scroll').clientWidth};});r.text[id]=await p.locator('.p18-app').innerText();await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});}
const check=async(name,fn)=>{await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);};
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.locator('#motion-mode').evaluate(e=>{for(let n=e;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
await demo('files');await capture('P18.S01');await p.locator('.p18-file-name').first().click();await painted();await capture('P18.S02');await demo('handoff');await capture('P18.S03');await demo('location');await p.check('[data-p18-capacity]');await capture('P18.S04');
r.baselineProfile=await p.evaluate(()=>({longTasks:[...longTasks],appNodes:document.querySelector('.p18-app').querySelectorAll('*').length,resources:performance.getEntriesByType('resource').filter(e=>e.name.includes('/attachments/')).map(e=>({name:new URL(e.name).pathname,bytes:e.decodedBodySize,duration:e.duration}))}));
// Same initial four-panel journey is profiled before behavioral stress.
if(!before){await runChecks({p,r,mode,act,snap,painted,demo,check});}
r.metrics=await p.evaluate(()=>({calls,fx,samples,progressFrames,longTasks,listeners:motionListeners,appNodes:document.querySelector('.p18-app')?.querySelectorAll('*').length||0,resources:performance.getEntriesByType('resource').filter(e=>e.name.includes('/attachments/')).map(e=>({name:new URL(e.name).pathname,bytes:e.decodedBodySize,duration:e.duration}))}));assert.deepEqual(r.errors,[]);assert.ok(!r.httpWriteRequest);await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});await c.close();}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));if(!before){const baseline=JSON.parse(fs.readFileSync('handoff/motion/M18/before/results.json','utf8'));for(const r of results){const old=baseline.find(x=>x.mode===r.mode);assert.deepEqual(r.geometry,old.geometry);assert.deepEqual(r.text,old.text);}assert.deepEqual(results.map(r=>r.domain),results.map(()=>results[0].domain));console.log('M18 geometry/text + domain parity PASS');}
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})();
async function runChecks({p,r,mode,act,snap,painted,demo,check}){
 const ownerFX=()=>p.evaluate(()=>fx.filter(x=>/^(Attachment|Viewer|Handoff)/.test(x.primitive)));
 const route=async hash=>{await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(240);};
 await check('S01 task-local failed retry/progress; same row on ticks, no speculative percentage',async()=>{
  await demo('files');const start=await snap();await p.selectOption('[data-p18-outcome]','error');await act('retry').click();await p.locator('[data-file-id="p18-pn0005-handover"]').evaluate(e=>{window.savedRow=e;window.savedProgress=e.querySelector('progress');});
  await p.waitForFunction(()=>document.querySelector('[data-file-id="p18-pn0005-handover"] progress')?.value===50);
  assert.equal(await p.locator('[data-file-id="p18-pn0005-handover"]').evaluate(e=>e===savedRow&&e.querySelector('progress')===savedProgress),true);
  assert.equal(await p.locator('[data-file-id="p18-pn0005-handover"] [data-progress-text]').textContent(),'50%');await p.waitForTimeout(530);const after=await snap();assert.equal(after.files[2].state,'error');assert.equal(after.files[1].state,'uploading');assert.equal(after.files[1].progress,75);assert.deepEqual(after.files.filter((_,i)=>i!==2),start.files.filter((_,i)=>i!==2));const frames=await p.evaluate(()=>progressFrames);assert.ok(frames.length>1);assert.ok(frames.every(f=>f.visual<=f.confirmed+.15));if(mode==='auto')assert.ok(frames.some(f=>f.visual>0&&f.visual<49.9));else assert.ok(frames.every(f=>Math.abs(f.visual-f.confirmed)<.15));
  await act('cancel').click();await p.locator('.app-modal-host').getByRole('button',{name:'Dừng tải lên',exact:true}).click();await p.locator('.app-modal-host').getByRole('button',{name:'Đóng',exact:true}).click();await p.waitForTimeout(130);assert.equal((await snap()).files[1].state,'cancelled');
 });
 await check('S02 latest ready page only; rapid prev/next, no zoom fade or delayed old PDF',async()=>{
  await p.locator('.p18-file-name').first().click();await painted();const initial=(await ownerFX()).filter(x=>x.primitive==='ViewerShell').length;assert.equal(initial,0);
  for(let i=0;i<2;i++){await act('next').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='2 / 2');await act('prev').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 2');}
  await act('next').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='2 / 2');const identity=await snap(),image=await p.locator('canvas').evaluate(e=>e.toDataURL());await p.waitForTimeout(230);assert.equal(await p.locator('canvas').evaluate(e=>e.toDataURL()),image);assert.equal((await snap()).fileId,identity.fileId);assert.match(await p.locator('.p18-pdf-text').textContent(),/PHIẾU NHẬP KHO/);
  const fades=(await ownerFX()).filter(x=>x.primitive==='ViewerShell');assert.equal(fades.length,mode==='off'?0:5);for(const f of fades){assert.equal(f.duration,mode==='auto'?140:80);assert.ok(f.frames.every(k=>!('transform'in k)));}
  const prior=fades.length;await act('zoom-in').click();await painted();assert.equal((await ownerFX()).filter(x=>x.primitive==='ViewerShell').length,prior);await act('back').click();await p.waitForSelector('[data-panel="P18.S01"]');await p.locator('.p18-file-name').first().click();await painted();assert.equal(await p.locator('[data-p18-pages]').textContent(),'2 / 2');assert.equal((await ownerFX()).filter(x=>x.primitive==='ViewerShell').length,prior);
 });
 await check('S03 feedback has immediate validation/checkbox and no case mutation; no replay on Back',async()=>{
  await demo('ready');const before=(await ownerFX()).filter(x=>x.primitive.startsWith('Handoff')).length;await act('next-field').click();assert.equal(await p.locator('[name=checked]').getAttribute('aria-invalid'),'true');assert.equal(await p.locator('[name=checked]').evaluate(e=>e===document.activeElement),true);await p.check('[name=checked]');await p.fill('[name=receiver]','Nguyễn Văn Bình');assert.equal(await act('handoff').isDisabled(),true);assert.equal((await snap()).caseStatus,'Chờ bàn giao');assert.equal(await p.evaluate(()=>calls.caseWrites),0);const current=(await ownerFX()).filter(x=>x.primitive.startsWith('Handoff')).length;assert.ok(mode==='off'?current===0:current>before);
  await demo('files');await p.goBack();await p.waitForSelector('[data-panel="P18.S03"]');await p.waitForTimeout(180);assert.equal(await p.inputValue('[name=receiver]'),'Nguyễn Văn Bình');assert.equal((await ownerFX()).filter(x=>x.primitive.startsWith('Handoff')).length,current);
 });
 await check('S04 immediate selection, 140ms outline only, unchanged cells/occupancy',async()=>{
  await demo('location');const node=p.locator('[data-slot=B2]'),box=await node.boundingBox();await node.click();assert.equal(await node.getAttribute('aria-pressed'),'true');assert.match(await p.locator('.p18-selection').innerText(),/K-01 · B2/);assert.equal((await snap()).mutations,0);assert.equal(await p.evaluate(()=>calls.caseWrites),0);const css=await node.evaluate(e=>({duration:getComputedStyle(e).transitionDuration,property:getComputedStyle(e).transitionProperty,transform:getComputedStyle(e).transform}));assert.equal(css.duration,mode==='auto'?'0.14s':'0s');assert.equal(css.property,'border-color, box-shadow');assert.equal(css.transform,'none');await p.waitForTimeout(180);assert.deepEqual(await node.boundingBox(),box);r.selectionCss=css;await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await node.evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
 });
 await check('Mode/OS/hidden/overlay cancellation, native focus, no motion replay',async()=>{
  await demo('files');await p.locator('.p18-file-name').first().click();await painted();await act('prev').click();await p.waitForFunction(()=>document.querySelector('[data-p18-pages]')?.textContent==='1 / 2');await act('read-text').click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.equal(await p.locator('.p18-page-surface').evaluate(e=>e.getAnimations().length),0);await p.keyboard.press('Escape');await p.waitForTimeout(130);assert.equal(await act('read-text').evaluate(e=>e===document.activeElement),true);
  await p.locator('#home-motion-mode').evaluate(e=>{e.value='off';e.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),'off');const before=(await ownerFX()).length;await act('next').click();await painted();assert.equal((await ownerFX()).length,before);
  await p.locator('#home-motion-mode').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('change',{bubbles:true}));},mode==='off'?'off':'auto');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),mode==='off'?'off':'reduced');await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});
  await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('#hn-destination').getAttribute('data-attachment-motion-hidden'),'true');const count=(await ownerFX()).length;await act('prev').click();await painted();await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await ownerFX()).length,count);
 });
 await check('P12/P09/P06 context, lifecycle disposal and final permissions remain unchanged',async()=>{
  await route('#p02/documents?panel=2&doc=fixture-inbound-0005&tab=files');await p.locator('[data-p12-file]').first().click();await painted();assert.equal((await snap()).fileId,'b12-attachment-1');await act('back').click();await p.waitForSelector('[data-p12-tab=files][aria-selected=true]');
  await route('#p02/warranty?panel=3&case=BH-005');await p.click('[data-p09=handoff]');assert.equal((await snap()).caseId,'BH-005');await act('back').click();await p.waitForSelector('[data-p09=handoff]');
  await route('#p02/lookup?panel=3&item=fixture-component-01');await p.click('[data-p06=location]');assert.equal((await snap()).itemId,'fixture-component-01');await act('back').click();await p.waitForSelector('[data-p06=location]');
  await route('#home');const baseline=await p.evaluate(()=>motionListeners);for(let i=0;i<4;i++){await demo('files');await route('#home');assert.equal(await p.evaluate(()=>motionListeners),baseline);}r.cleanupListeners=baseline;
  await demo('files');await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.click('[data-system-demo=expired]');await p.waitForSelector('[data-panel="P15.S02"]');assert.equal(await p.locator('.p18-app:visible').count(),0);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>/^(Attachment|Viewer|Handoff)/.test(a.effect?.target?.dataset?.motionPrimitive||'')).length),0);assert.equal(await p.evaluate(()=>calls.hardware),0);
 });
 r.domain=await p.evaluate(()=>calls);
}

