const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const out=process.env.P15_UX_DIR||'handoff/P15/evidence/revision-02';
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'});const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
 const check=async(name,f)=>{await f();checks.push({name,status:'PASS'});console.log('PASS '+name)};const panel=()=>p.locator('.p15-app:visible'),a=k=>panel().locator(`[data-p15=${k}]`).first(),modal=()=>p.locator('.app-modal-host dialog');
 const shot=async n=>{await p.evaluate(()=>window.scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:out+'/after/'+n+'.png'})};
 try{await p.goto((process.env.P15_BASE_URL||'http://localhost:8766/flows/auth-session/'));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-screen').waitFor({state:'visible'});
 // Isolated browser fixture of the same reusable component; no production hook.
 await p.evaluate(async()=>{const {mountSystem}=await import('/flows/system/view.mjs');const {createDeviceAccess}=await import('/flows/system/model.mjs');window.uxDevice=createDeviceAccess();window.uxContext=null;window.uxReads=0;window.uxExpired=false;window.ux=mountSystem({routeKey:'hnP15Audit',screen:document.querySelector('.hn-screen'),tools:document.querySelector('.hn-tools'),getContext:()=>window.uxContext,deviceAccess:window.uxDevice,onHome(){},onLogin(){},onExpire(){window.uxExpired=true},isExpired:()=>window.uxExpired,contact:{label:'Kênh thử nghiệm',value:'Hỗ trợ nội bộ (fixture)'}})});
 await check('Read retry label and verified callback; duplicate requests remain blocked',async()=>{await p.evaluate(()=>ux.show('connection',{intent:'read',read:()=>{window.uxReads++;return new Promise(r=>window.uxFinish=r)}}));assert.equal(await a('retry').innerText(),'Tải lại');await a('retry').click();assert.equal(await a('retry').isDisabled(),true);assert.equal(await p.evaluate(()=>uxReads),1);await shot('read-loading');await p.evaluate(()=>uxFinish({kind:'verified'}));await panel().waitFor({state:'hidden'});});
 await check('Context UNKNOWN changes CTA; fixed dock/reader/escape at five viewports',async()=>{
  await p.evaluate(()=>{window.uxContext={number:'PN-0005',label:'Phiếu nhập',unknown:true,status:'Chưa xác định kết quả gửi'};ux.show('connection',{intent:'reconcile',read:async()=>({kind:'unknown'})})});assert.match(await panel().innerText(),/PN-0005/);assert.equal(await a('retry').innerText(),'Đối chiếu kết quả');assert.match(await panel().locator('.p15-state-actions').innerText(),/Quay lại phiếu/);await shot('unknown-context');
  for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});await p.waitForTimeout(60);const r=await panel().evaluate(e=>{const scroll=e.querySelector('.p15-state-scroll'),dock=e.querySelector('.p15-state-actions'),nav=e.parentElement.querySelector('.hn-nav'),rect=x=>x.getBoundingClientRect();return {overflow:scroll.scrollWidth>scroll.clientWidth,bottom:rect(dock).bottom,navTop:rect(nav).top}});assert.ok(!r.overflow&&r.bottom<=r.navTop);}
  await p.setViewportSize({width:494,height:950});await p.evaluate(()=>{uxContext.number='Phiếu 🌸\n'+'Đ'.repeat(2000);ux.show('connection',{intent:'reconcile',read:async()=>({kind:'unknown'})})});await panel().getByRole('button',{name:'Xem đầy đủ số phiếu'}).click();assert.match(await modal().innerText(),/Đ{2000}/);await shot('long-context-reader');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await panel().getByRole('button',{name:'Xem đầy đủ số phiếu'}).evaluate(e=>e===document.activeElement));await p.evaluate(()=>ux.hide());
 });
 await check('Known forbidden action copy and configured contact remain a display-only dialog',async()=>{await p.evaluate(()=>{uxContext.number='PN-0005';ux.show('forbidden',{actionLabel:'gửi phiếu này'})});assert.match(await panel().innerText(),/Bạn chưa có quyền gửi phiếu này/);await shot('forbidden-action');await a('contact').click();assert.match(await modal().innerText(),/Kênh thử nghiệm: Hỗ trợ nội bộ/);assert.equal(await modal().locator('a').count(),0);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await p.evaluate(()=>ux.hide());});
 await check('Denied camera prioritizes guidance; NFC unsupported has exactly one guide; camera unsupported has correct help',async()=>{
  await p.evaluate(()=>{uxDevice.reportFailure('camera',{name:'NotAllowedError'});ux.show('device')});assert.equal(await panel().locator('.p15-device-actions').first().locator('button').first().innerText(),'Hướng dẫn cấp quyền');assert.equal(await panel().locator('.p15-device-actions').nth(1).locator('button').count(),1);await shot('device-denied');await a('camera-guide').click();assert.match(await modal().innerText(),/Kiểm tra lại camera/);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await p.evaluate(()=>{uxDevice.reportFailure('camera',{name:'NotSupportedError'});ux.show('device')});assert.equal(await panel().locator('[data-p15=camera]').count(),0);await a('camera-guide').click();assert.match(await modal().innerText(),/thiết bị có camera/);assert.doesNotMatch(await modal().innerText(),/hỗ trợ NFC/);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await p.evaluate(()=>ux.hide());
 });
 await check('Expired context explains same-account continuation without claiming server save',async()=>{await p.evaluate(()=>ux.show('expired'));assert.match(await panel().innerText(),/Đăng nhập lại để tiếp tục phiếu đang làm/);assert.match(await panel().innerText(),/Phiếu được giữ trong trang này/);assert.doesNotMatch(await panel().innerText(),/đã lưu thành công/i);await shot('expired-context');await p.evaluate(()=>{ux.hide();ux.dispose()});});
 await check('Real owner context projected into system; return restores same draft',async()=>{await p.click('.hn-task[data-route=inbound]');await p.fill('[data-p04-note]','Ngữ cảnh phiếu thật trong fixture');const before=JSON.parse(await p.locator('[data-p04-snapshot]').textContent());await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.click('[data-system-demo=connection]');assert.match(await panel().locator('.p15-context').innerText(),new RegExp(before.document.number));await panel().locator('.p15-state-actions [data-p15=back]').click();await p.locator('.p04-app').waitFor({state:'visible'});assert.equal(await p.inputValue('[data-p04-note]'),'Ngữ cảnh phiếu thật trong fixture');});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/ux-results.json',JSON.stringify({status:'PASS',checks,errors},null,2));console.log('TOTAL '+checks.length);
 }catch(e){await p.screenshot({path:out+'/ux-failure.png',fullPage:true});fs.writeFileSync(out+'/ux-failure.json',JSON.stringify({checks,errors,error:String(e)},null,2));throw e;}finally{await b.close()}
})().catch(e=>{console.error(e);process.exit(1)});
