const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_EVIDENCE_DIR||'handoff/P09/evidence/revision-01');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const b=await chromium.launch({headless:true}),page=await b.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});
 const checks=[],metrics=[],errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{window.__hardware=0;navigator.mediaDevices.getUserMedia=()=>{window.__hardware++;throw Error('Camera not authorized');};});
 const act=a=>page.locator(`[data-p09="${a}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route="warranty"]');await page.locator('[data-panel="P09.S01"]').waitFor();}
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const app=document.querySelector('.p09-app'),s=document.querySelector('.hn-screen'),el=app.querySelector('.p09-scroll'),r=s.getBoundingClientRect(),f=app.querySelector('.p09-footer');return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,screen:{width:r.width,height:r.height},scrollTop:el.scrollTop,overflow:el.scrollWidth>el.clientWidth,pageOverflow:document.documentElement.scrollWidth>innerWidth,footer:f?.getBoundingClientRect().top,contentBottom:el.getBoundingClientRect().bottom};});metrics.push({name,...m});assert.equal(m.overflow,false);assert.equal(m.pageOverflow,false);if(m.footer)assert.ok(m.contentBottom<=m.footer+1);}
 async function matrix(name){await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=0);await page.locator('.p09-header h1').focus();for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await capture(name+'-'+w+'x'+h);}await page.setViewportSize({width:494,height:1000});}
 async function openCase(id){await page.fill('#p09-query',id);await page.click(`[data-p09-case="${id}"]`);await page.locator('[data-panel="P09.S03"]').waitFor();}
 async function read(serial){await page.locator('[data-scan-action=manual]').click();await page.fill('#p09-code',serial);await page.locator('#p09-code').press('Enter');}
 async function update(text='Đã sửa chữa, máy hoạt động bình thường'){await act('update').click();await page.fill('.p09-dialog [name=result]',text);await page.click('.p09-dialog [type=submit]');}
 try{
 await login();
 await check('S01 list/search/status/sort/cancel and responsive',async()=>{assert.equal(await page.locator('.p09-case').count(),8);await matrix('P09-S01');await page.fill('#p09-query','khong-co');assert.equal(await page.locator('.p09-case').count(),0);await page.fill('#p09-query','');await act('filter').click();await page.locator('.p08-dialog input[value="Đã trả khách"]').check();await page.locator('.p08-dialog [type=submit]').click();assert.equal(await page.locator('.p09-case').count(),4);await act('filter').click();await page.keyboard.press('Escape');assert.equal(await page.locator('.p09-case').count(),4);await act('filter').click();await page.locator('.p08-dialog input[value="all"]').check();await page.locator('.p08-dialog [type=submit]').click();await act('sort').click();await page.locator('.p08-dialog input[value="asc"]').check();await page.locator('.p08-dialog [type=submit]').click();assert.equal(await page.locator('.p09-case').first().getAttribute('data-p09-case'),'BH-002');});
 await check('S02 A01 serial validation, retained draft, keyboard and intake confirmation',async()=>{await act('begin').click();assert.equal(await act('intake').isDisabled(),true);await read('XP-420B');assert.match(await page.locator('#p09-code-feedback').textContent(),/SKU/);await page.fill('#p09-code','HN12345');await page.locator('#p09-code').press('Enter');await page.click('[data-p09=fault]');await page.locator('.p09-fault-picker input[value="power-off"]').click();await page.fill('[name=note]','Khách hàng yêu cầu kiểm tra tổng thể và vệ sinh máy.');await matrix('P09-S02');await act('back').click();await act('begin').click();assert.equal(await page.locator('#p09-fault-value').textContent(),'Máy không lên nguồn');await act('intake').click();assert.match(await page.locator('.p09-dialog').textContent(),/Bước 2\/2/);await page.locator('.p09-dialog [type=submit]').evaluate(e=>{e.click();e.click();});await page.locator('[data-panel="P09.S03"]').waitFor();assert.equal((await snap()).writes,0);assert.equal((await snap()).receipt.caseId,'BH-001');});
 await check('S03 A02 POSTED ledger count and shared case timeline, six viewports',async()=>{await matrix('P09-S03');await act('parts').click();assert.match(await page.locator('#p09-tabpanel').textContent(),/XLK-0002/);assert.equal(await page.locator('.p09-part').count(),2);assert.match(await page.locator('[data-p09-tab=parts]').textContent(),/3/);await page.locator('[data-p09-tab=parts]').press('ArrowRight');assert.match(await page.locator('#p09-tabpanel').textContent(),/Đã tiếp nhận/);await page.locator('[data-p09-tab=events]').press('Home');assert.equal(await page.locator('[data-p09-tab=info]').getAttribute('aria-selected'),'true');});
 await check('S04 A03 confirmed update is waiting handover, not closed; modal focus trap',async()=>{await act('update').click();await page.locator('.p09-dialog [name=diagnosis]').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('.p09-dialog [name=result]').evaluate(e=>e===document.activeElement),true);await page.fill('.p09-dialog [name=result]','Đã sửa chữa, máy hoạt động bình thường');await page.click('.p09-dialog [type=submit]');await page.locator('[data-panel="P09.S04"]').waitFor();assert.equal((await snap()).writes,1);assert.match(await page.locator('.p09-app').textContent(),/Chờ bàn giao/);await matrix('P09-S04');await act('view').click();assert.equal(await act('update').isEnabled(),true);await page.locator('[data-p09-tab=events]').click();assert.match(await page.locator('#p09-tabpanel').textContent(),/Hoàn tất sửa chữa/);});
 await check('A04 closed case blocks writes, A05 case data never leaks',async()=>{await act('back').click();await page.locator('[data-panel="P09.S02"]').waitFor();await act('back').click();await page.locator('[data-panel="P09.S01"]').waitFor();await openCase('BH-002');assert.equal(await act('update').isDisabled(),true);assert.match(await page.locator('.p09-app').textContent(),/Đại lý Thành Công/);assert.doesNotMatch(await page.locator('.p09-app').textContent(),/Công ty Minh Phát/);await act('parts').click();assert.equal(await act('issue').isDisabled(),true);assert.equal(await page.locator('.p09-part').count(),1);assert.match(await page.locator('.p09-document').textContent(),/XLK-0003/);await capture('closed-case');await act('back').click();await openCase('BH-003');assert.match(await page.locator('.p09-app').textContent(),/SN-XP420B-202/);await page.locator('[data-p09-tab=events]').click();assert.doesNotMatch(await page.locator('#p09-tabpanel').textContent(),/Hoàn tất sửa chữa/);});
 await check('UNKNOWN preserves request, blocks retry and reconciles once',async()=>{await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]','unknown');await update();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const id=(await snap()).request.id;assert.equal(await act('update').isDisabled(),true);await capture('unknown');await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('[data-panel="P09.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,id);assert.equal((await snap()).writes,2);});
 await check('Failure preserves result draft and retry request; deep success link cannot fabricate receipt',async()=>{await act('view').click();await page.selectOption('[data-p09-mode]','error');await update('Kiểm tra lại nguồn');await page.waitForFunction(()=>document.querySelector('.hn-action-dialog[open]')?.textContent.includes('Chưa cập nhật'));const id=(await snap()).request.id;assert.equal((await snap()).updateDraft.result,'Kiểm tra lại nguồn');assert.equal(await page.locator('.p09-dialog').count(),0);await page.keyboard.press('Escape');await page.selectOption('[data-p09-mode]','ready');await act('update').click();await page.click('.p09-dialog [type=submit]');await page.locator('[data-panel="P09.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,id);await login();await page.evaluate(()=>location.hash='#p02/warranty?panel=4&case=BH-001');await page.locator('[data-panel="P09.S03"]').waitFor();assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);});
 await check('Native Back restores query/scroll and detail tabs, new serial creates exactly one case',async()=>{await act('back').click();await page.fill('#p09-query','BH-00');await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=250);const y=await page.locator('.p09-scroll').evaluate(e=>e.scrollTop);await page.click('[data-p09-case="BH-001"]');await page.goBack();await page.locator('#p09-query').waitFor();assert.equal(await page.locator('#p09-query').inputValue(),'BH-00');assert.ok(await page.locator('.p09-scroll').evaluate(e=>e.scrollTop)>=y);await act('begin').click();await read('SN-XP420B-BK-0008');await page.click('[data-p09=fault]');await page.locator('.p09-fault-picker input[value="power-off"]').click();await act('intake').click();await page.locator('.p09-dialog [type=submit]').click();await page.locator('[data-panel="P09.S03"]').waitFor();assert.match(await page.locator('.p09-hero').textContent(),/BH-009/);assert.equal((await snap()).writes,1);await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});});
 await check('P06 context bridge keeps exact serial; P08 reads same case/events after update',async()=>{await page.evaluate(()=>location.hash='#p02/lookup?panel=2&item=fixture-item-HN12346');await page.locator('[data-p06=warranty]').click();await page.locator('[data-panel="P09.S02"]').waitFor();assert.match(await page.locator('.p09-table').textContent(),/SN-XP420B-BK-0008/);await page.evaluate(()=>location.hash='#p02/history-list?panel=1&business=warranty');await page.locator('#p08-search').fill('BH-009');assert.match(await page.locator('.p08-app').textContent(),/BH-009/);});
 await check('P03 modal coexistence, logout and native Back cannot restore warranty',async()=>{await page.evaluate(()=>location.hash='#p02/warranty');await page.locator('[data-panel="P09.S01"]').waitFor();await page.click('[data-tab=lookup]');await page.locator('[data-panel="P03.S01"]').waitFor();await page.keyboard.press('Escape');await page.locator('[data-panel="P09.S01"]').waitFor();await page.locator('.hn-tools>details').first().locator('summary').click();await page.click('#hn-logout');await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p09-app').count(),0);assert.equal(await page.evaluate(()=>window.__hardware),0);});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external,hardware:'NOT_RUN',production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await b.close();}
})();
