const{chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');const out='handoff/P15/evidence/revision-03';
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1});p.setDefaultTimeout(20000);const checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const check=async(name,f)=>{await f();checks.push({name,status:'PASS'});console.log('PASS '+name)};
const open=async kind=>{await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.click(`[data-system-demo=${kind}]`);await p.locator('.p15-app').waitFor({state:'visible'})};
try{await p.goto(process.env.P15_BASE_URL||'http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-screen').waitFor();
await check('Footer navigation waits for system history close, URL matches Documents; Back returns Home',async()=>{await open('connection');await p.click('[data-tab=documents]');await p.locator('[data-panel="P12.S01"]').waitFor();await p.waitForTimeout(150);assert.match(new URL(p.url()).hash,/#p02\/documents/);await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});assert.equal(new URL(p.url()).hash,'#home');});
await check('Closing via Home CTA has no stale system history; subsequent nav works',async()=>{await open('connection');await p.click('[data-p15=home]');await p.locator('.p15-app').waitFor({state:'hidden'});await p.waitForTimeout(150);assert.equal(new URL(p.url()).hash,'#home');await p.click('[data-tab=profile]');await p.locator('[data-panel="P10.S01"]').waitFor();assert.match(new URL(p.url()).hash,/#p02\/profile/);await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});});
await check('Device guide closes once with Back, restores trigger; Back then leaves panel',async()=>{await open('device');await p.click('[data-p15=camera-guide]');await p.locator('.app-modal-host').waitFor();await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await p.locator('[data-p15=camera-guide]').evaluate(e=>e===document.activeElement));await p.goBack();await p.locator('.p15-app').waitFor({state:'hidden'});await p.locator('#hn-home').waitFor({state:'visible'});});
await check('Expiry replaces active P15 without stale close callback hiding it; reauth remains required',async()=>{await open('connection');await open('expired');await p.locator('[data-panel="P15.S02"]').waitFor();await p.waitForTimeout(150);assert.equal(await p.locator('.p15-app:visible').count(),1);await p.click('[data-tab=documents]');assert.equal(await p.locator('.p15-app').getAttribute('data-panel'),'P15.S02');await p.click('[data-p15=login]');await p.locator('#username').waitFor();});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/navigation-results.json',JSON.stringify({checks,errors},null,2));}catch(e){await p.screenshot({path:out+'/navigation-failure.png',fullPage:true});throw e;}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
