const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const phase=process.env.UX_TOUCH_PHASE||'after';
const out=path.resolve(process.env.UX_TOUCH_OUT||`handoff/ux-upgrade-2026-09-30/touch/${phase}`);fs.mkdirSync(out,{recursive:true});
const measures=[],checks=[],errors=[];
const viewports=[[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]];
const targets='[data-hn-touch-layout]';
const settle=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
(async()=>{const browser=await chromium.launch();const p=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));
try{
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.locator('#username').waitFor();
 async function sample(name){for(const [width,height]of viewports){await p.setViewportSize({width,height});await settle(p);await p.waitForTimeout(80);const m=await p.evaluate(({name,targets})=>{const s=document.querySelector('#home-app:not([hidden]) .hn-screen')||document.querySelector('#app:not([hidden]) .screen'),box=s.getBoundingClientRect();const controls=[...s.querySelectorAll(targets)].filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&!n.closest('[hidden]')&&r.top>=box.top-1&&r.bottom<=box.bottom+1;}).map(n=>{const r=n.getBoundingClientRect();return {id:n.id||n.getAttribute('aria-label')||n.textContent.trim().slice(0,35),x:r.x,y:r.y,w:r.width,h:r.height,clipped:n.closest('[inert]')!==null};});const overlaps=[];controls.forEach((a,i)=>controls.slice(i+1).forEach(b=>{if(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>1&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>1)overlaps.push([a.id,b.id]);}));return{name,viewport:[innerWidth,innerHeight],frame:[s.offsetWidth,s.offsetHeight],pageOverflow:document.documentElement.scrollWidth>innerWidth+1,controls,overlaps};},{name,targets});measures.push(m);if(phase==='after'){assert.deepEqual(m.frame,[494,950]);assert.ok(!m.pageOverflow,JSON.stringify(m));assert.equal(m.overlaps.length,0,JSON.stringify(m));assert.ok(m.controls.filter(c=>!c.clipped).every(c=>c.w>=43.8&&c.h>=43.8),JSON.stringify(m));}if(width===494||width===360||height===420)await p.locator('#home-app:not([hidden]) .hn-screen,#app:not([hidden]) .screen').screenshot({path:path.join(out,`${name}-${width}x${height}.png`)});}checks.push({name,status:phase==='before'?'CAPTURED':'PASS'});await p.setViewportSize({width:494,height:1000});}
 await sample('P01-login');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.locator('#start').waitFor();await sample('P01-confirm');await p.click('#start');await p.locator('.hn-nav').waitFor();await sample('P02-home');
 const footer=()=>p.locator('.hn-nav').evaluate(n=>{const c=getComputedStyle(n);return Object.fromEntries(['backgroundColor','borderRadius','minHeight','padding'].map(k=>[k,c[k]]));});const nav=await footer();
 async function route(hash,selector){await p.evaluate(h=>{location.hash=h;},hash);await p.locator(selector).waitFor();await settle(p);}
 for(const [name,hash,selector]of[['P04-form','#p02/inbound','[data-panel="P04.S01"]'],['P05-form','#p02/outbound','[data-panel="P05.S01"]'],['P06-list','#p02/lookup','[data-panel="P06.S01"]'],['P07-list','#p02/nfc','[data-panel="P07.S01"]'],['P08-list','#p02/history-list','[data-panel="P08.S01"]'],['P09-list','#p02/warranty','[data-panel="P09.S01"]'],['P11-password','#p02/security?panel=1','[data-panel="P11.S01"]']]){await route(hash,selector);await sample(name);}
 await route('#p02/lookup','[data-panel="P06.S01"]');await p.fill('#p06-search','HN12345');await p.click('[data-p06="clear"]');assert.equal(await p.inputValue('#p06-search'),'');await p.click('[data-p06="filter"]');await p.locator('dialog[open]').waitFor();await sample('P06-feedback');await p.keyboard.press('Escape');await p.locator('dialog[open]').waitFor({state:'detached'});
 await route('#home','#hn-home:visible');assert.deepEqual(await footer(),nav);checks.push({name:'Footer unchanged; clear search and Escape work',status:'PASS'});
 assert.deepEqual(errors,[]);
}catch(e){checks.push({name:'run',status:'FAIL',error:e.stack});await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({phase,checks,measures,errors},null,2));console.log(JSON.stringify({phase,checks,measurements:measures.length,errors}));await browser.close();}})();
