const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),base=process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766',out=path.join(process.env.M13_EVIDENCE_DIR||'D:/CodexTemp/ScannerHNApp-M13/evidence',before?'before':'after');fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/notifications/notifications.mjs','docs/flows/notifications/notification-model.mjs','docs/flows/notifications/notification-pages.mjs','docs/flows/notifications/style.css','docs/flows/notifications/motion.mjs','docs/flows/home/home.mjs','docs/flows/home/motion.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(files.filter(f=>fs.existsSync(f)).map(file=>({file,bytes:fs.statSync(file).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')})),null,2));
if(before)for(const file of files.filter(f=>fs.existsSync(f))){const to=path.join(out,'source',file);fs.mkdirSync(path.dirname(to),{recursive:true});fs.copyFileSync(file,to);}
(async()=>{assert.equal(JSON.parse(fs.readFileSync('handoff/flow/FLOW_GATE.json')).gate_status,'PASS');const b=await chromium.launch(),results=[];
try{for(const mode of ['auto','os-reduced','off']){
 const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[],writeRequests:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));p.on('request',q=>{if(!['GET','HEAD'].includes(q.method()))r.writeRequests.push([q.method(),q.url()]);});
 await c.tracing.start({screenshots:true,snapshots:true,sources:false});await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
 // Observation only: count distinct existing local mark-read dispatches, after its dedup guard.
 await c.route('**/notifications/notification-model.mjs',async route=>{const response=await route.fetch(),body=await response.text(),needle='const version=row.version,requestGeneration=generation;';assert.ok(body.includes(needle));await route.fulfill({response,body:body.replace(needle,'window.qaReadOps++;'+needle)});});
 await p.addInitScript(()=>{window.qaReadOps=0;window.qaHardware=0;window.qaMotion=[];window.qaSamples=[];window.qaLong=[];window.qaListeners=0;
 const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners--;return remove.call(this,t,f,o);};
 const native=Element.prototype.animate;Element.prototype.animate=function(frames,options){const e={node:this.id||this.className,primitive:this.dataset.motionPrimitive,duration:options.duration,frames,cancelled:false,time:performance.now()};qaMotion.push(e);const a=native.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{e.cancelled=true;cancel();};if(e.primitive?.startsWith('Notification')||e.primitive==='WaitingWebState'){const node=this,start=performance.now();const tick=()=>{qaSamples.push({primitive:e.primitive,t:performance.now()-start,opacity:getComputedStyle(node).opacity});if(node.isConnected&&performance.now()-start<210)requestAnimationFrame(tick);};requestAnimationFrame(tick);}return a;};
 new PerformanceObserver(list=>qaLong.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('No hardware during P13');};window.NDEFReader=class{constructor(){qaHardware++;throw Error('No NFC during P13');}};
 });
 const ready=()=>p.locator('[data-p13-loaded=true][aria-busy=false]').waitFor();const settle=()=>p.waitForTimeout(260);
 async function route(q){await p.evaluate(q=>location.hash='#p02/notifications'+(q?'?'+q:''),q);await p.locator('.p13-app').waitFor();await settle();}
 async function capture(name){await settle();r.geometry[name]=await p.locator('.p13-app').evaluate(app=>{const shell=app.closest('.hn-screen'),base=shell.getBoundingClientRect();return Object.fromEntries(['.p13-header','.p13-scroll','.p13-filter-dock','.p13-actions','.hn-nav','.hn-scan-circle'].map(s=>{const e=shell.querySelector(s);if(!e)return[s,null];const b=e.getBoundingClientRect();return[s,[b.x-base.x,b.y-base.y,b.width,b.height]];}));});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+name+'.png')});}
 async function check(name,fn){await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);}
 async function dataset(value){await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset',value);await ready();await p.evaluate(()=>scrollTo(0,0));}
 await p.goto(base+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.click('.hn-bell');await ready();await capture('P13.S01');
 await p.click('[data-p13-event=p13-event-inbound]');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));await capture('P13.S02');await p.click('[data-p13=waiting]');await capture('P13.S03');await p.click('[data-p13-doc=fixture-inbound-0005]');await capture('P13.S04');r.initialAnimations=await p.evaluate(()=>qaMotion);if(!before){const state=r.initialAnimations.filter(x=>x.primitive==='WaitingWebState');assert.equal(state.length,mode==='off'?0:1);if(state.length)assert.equal(state[0].duration,mode==='auto'?140:80);}
 await route('panel=1');await dataset('count-1000');await p.click('[data-p13-filter=all]');await ready();await settle();const t=await p.evaluate(()=>performance.now());await p.click('[data-p13=more]');await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===20);r.profile=await p.locator('.p13-app').evaluate((e,t)=>({rows:e.querySelectorAll('.p13-notification').length,nodes:e.querySelectorAll('*').length,appendWallMs:performance.now()-t}),t);await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await capture('profile1000-page20');
 if(!before)await runChecks({p,c,r,mode,check,route,capture,ready,settle,dataset});
 r.finalDomain=await p.evaluate(()=>({readOperations:qaReadOps,hardware:qaHardware,pageCalls:document.querySelector('#p13-page-calls')?.textContent}));r.animations=await p.evaluate(()=>qaMotion);r.samples=await p.evaluate(()=>qaSamples);r.longTasks=await p.evaluate(()=>qaLong);assert.deepEqual(r.errors,[]);assert.deepEqual(r.writeRequests,[]);await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});await c.close();
 }fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});

async function runChecks({p,c,r,mode,check,route,capture,ready,settle,dataset}){
 const effects=()=>p.evaluate(()=>qaMotion.filter(x=>x.primitive==='NotificationList'||x.primitive==='WaitingWebState'));
 await check('S01 filter140/80/off; guards and count immediate; no repeat selected filter',async()=>{await route('panel=1');await dataset('baseline');await p.click('[data-p13-filter=all]');await ready();await settle();await p.evaluate(()=>qaMotion=[]);await p.click('[data-p13-filter=unread]');await ready();assert.equal(await p.locator('.p13-notification').count(),3);await settle();const e=await effects();assert.equal(e.length,mode==='off'?0:1);if(e.length)assert.equal(e[0].duration,mode==='auto'?140:80);await p.click('[data-p13-filter=unread]');await settle();assert.equal((await effects()).length,e.length);});
 await check('S02 one mark-read even rapid click; route only shell; exact P12 ID and Back',async()=>{const calls=await p.evaluate(()=>qaReadOps);await p.locator('[data-p13-event=p13-event-inbound]').evaluate(e=>{e.click();e.click();});await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));assert.equal(await p.evaluate(()=>qaReadOps),calls+1);assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');assert.equal(await p.locator('.p13-related strong').textContent(),'PN-0005');await p.click('[data-p13=document]');await p.locator('.p12-app').waitFor();assert.ok(p.url().includes('fixture-inbound-0005'));assert.equal(await p.locator('.app-modal-exit').count(),0);await p.goBack();await p.locator('.p13-app').waitFor();assert.equal(await p.evaluate(()=>qaReadOps),calls+1);r.domain={readOps:await p.evaluate(()=>qaReadOps),badge:await p.locator('.hn-bell .hn-count').textContent(),doc:await p.locator('.p13-related strong').textContent()};});
 await check('Read error preserves source/notification; dialog keyboard Back and retry',async()=>{await route('panel=1');await p.selectOption('#p13-scenario','read-error');await p.click('[data-p13-event=p13-event-warehouse]');await p.locator('.app-modal-host dialog').waitFor();assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');await p.keyboard.press('Tab');assert.ok(await p.locator('.app-modal-host dialog').evaluate(e=>e.contains(document.activeElement)));await p.goBack();await p.locator('.app-modal-host').waitFor({state:'detached'});await p.click('[data-p13=back]');await ready();assert.equal(await p.locator('[data-p13-event=p13-event-warehouse]').count(),1);await p.selectOption('#p13-scenario','ready');});
 await check('S03/S04 MIGRATED list/state only; no approval; no state replay on Back',async()=>{await route('panel=3');await p.evaluate(()=>qaMotion=[]);await p.click('[data-p13-type=inbound]');assert.equal(await p.locator('.p13-waiting-record').count(),3);await settle();const list=await effects();assert.equal(list.length,mode==='off'?0:1);await p.click('[data-p13-doc=fixture-inbound-0005]');assert.deepEqual(await p.locator('.p13-lines tbody tr td:nth-child(2)').allTextContents(),['5','4','2']);assert.equal(await p.locator('.p13-app button').filter({hasText:/^(Duyệt|Từ chối|Post|Ghi sổ)$/}).count(),0);await p.click('[data-p13=document]');await p.locator('.p12-app').waitFor();const n=(await effects()).length;await p.goBack();await p.locator('[data-panel="P13.S04"]').waitFor();await settle();assert.equal((await effects()).length,n);});
 await check('Native long list append/Back keep scroll; old rows never replay',async()=>{await route('panel=1');await dataset('extended');await p.click('[data-p13-filter=all]');await ready();await settle();const n=(await effects()).length;await p.locator('.p13-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const y=await p.locator('.p13-scroll').evaluate(e=>e.scrollTop);await p.click('[data-p13=more]');await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===20);assert.equal(await p.locator('.p13-scroll').evaluate(e=>e.scrollTop),y);assert.equal((await effects()).length,n);await p.locator('[data-p13-event]').nth(8).dispatchEvent('click');await p.locator('[data-panel="P13.S02"]').waitFor();await p.goBack();await ready();await settle();assert.equal(await p.locator('.p13-scroll').evaluate(e=>e.scrollTop),y);assert.equal((await effects()).length,n);await p.setViewportSize({width:360,height:420});await capture('compact');assert.ok(await p.locator('.p13-scroll').evaluate(e=>e.clientWidth===e.scrollWidth));await p.setViewportSize({width:494,height:950});});
 await check('Rapid routes and motion cancellation keep final scope; no exit overlay over link',async()=>{await p.evaluate(()=>{document.querySelector('[data-p13-filter=unread]').click();document.querySelector('[data-p13-filter=all]').click();document.querySelector('[data-p13-filter=unread]').click();});await ready();await settle();assert.equal(await p.locator('[data-p13-filter=unread]').getAttribute('aria-pressed'),'true');await route('panel=2&event=p13-event-inbound');await p.click('[data-p13=document]');await p.locator('.p12-app').waitFor();await settle();assert.ok(await p.locator('.p12-app').evaluate(e=>!e.closest('[inert]')));assert.equal(await p.locator('.p13-app').count(),0);assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target?.dataset.motionPrimitive?.startsWith('Notification')).length),0);});
 await check('Permission loss blocks document link immediately with no stale exit layer',async()=>{await route('panel=2&event=p13-event-inbound');await p.locator('[data-system-demo=deny]').evaluate(e=>e.click());assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert||e.hidden||!!e.closest('[inert]')));await p.locator('[data-p13=document]').evaluate(e=>e.click());assert.equal(await p.locator('.p12-app').count(),0);await p.locator('[data-system-demo=allow]').evaluate(e=>e.click());await route('panel=1');await ready();});
 await check('Live OS/mode change and hidden cancel;10 cycles release listeners; expiry immediate',async()=>{await route('panel=1');await ready();await p.selectOption('#home-motion-mode','auto');await p.emulateMedia({reducedMotion:'no-preference'});await p.click('[data-p13-filter=all]');await ready();await p.locator('[data-p13-filter=unread]').evaluate(e=>e.click());await p.emulateMedia({reducedMotion:'reduce'});await settle();assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),'reduced');await p.selectOption('#home-motion-mode','off');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});await settle();assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&a.effect?.target?.dataset.motionPrimitive==='NotificationList').length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home:visible').waitFor();await settle();const baseline=await p.evaluate(()=>qaListeners);for(let i=0;i<10;i++){await p.click('.hn-bell');await p.locator('.p13-app').waitFor();await p.click('[data-tab=home]');await p.locator('#hn-home:visible').waitFor();}await settle();assert.equal(await p.evaluate(()=>qaListeners),baseline);assert.equal(await p.evaluate(()=>qaHardware),0);await p.click('.hn-bell');await ready();await p.locator('[data-system-demo=expired]').evaluate(e=>e.click());await settle();assert.equal(await p.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running'&&(a.effect?.target?.dataset.motionPrimitive==='NotificationList'||a.effect?.target?.id==='hn-destination')).length),0);assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert||e.hidden||!!e.closest('[inert]')));});
}
