const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const out='handoff/P14/evidence/revision-04';
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const action=a=>p.locator(`[data-p14="${a}"]`).first(),modal=()=>p.locator('.app-modal-host dialog');
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function enter(){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await p.locator('[data-panel="P14.S03"]').waitFor();}
async function finish(){await action('save').click();await modal().getByRole('button',{name:'Lưu nháp',exact:true}).click();await modal().getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-panel="P14.S04"]').count(),0);assert.ok(await action('end').isEnabled());await action('end').click();await modal().getByRole('button',{name:'Kết thúc ca',exact:true}).click();await p.locator('[data-panel="P14.S04"]').waitFor();}
try{await p.clock.setFixedTime(new Date('2026-09-29T08:30:00+07:00'));await enter();
await check('S03 controls grouped in dock, one row resume, no duplicate hint; six viewports',async()=>{assert.equal(await p.locator('[data-p14=continue-first],.p14-end-action').count(),0);assert.equal(await p.locator('.p14-row-action').textContent(),'Tiếp tục ');assert.ok(await action('end').isDisabled());assert.equal(await action('end').getAttribute('aria-describedby'),'p14-shift-status');for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.waitForTimeout(70);const m=await p.evaluate(()=>{const root=document.querySelector('.p14-app'),dock=root.querySelector('.p14-actions'),save=root.querySelector('[data-p14=save]'),end=root.querySelector('[data-p14=end]'),s=root.querySelector('.p14-scroll'),screen=root.closest('.hn-screen'),rect=e=>e.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],group:dock.contains(save)&&dock.contains(end),heights:[save.offsetHeight,end.offsetHeight],gap:parseFloat(getComputedStyle(save.parentElement).gap),widths:[save.offsetWidth,end.offsetWidth],noOverflow:s.clientWidth===s.scrollWidth,within:rect(end).bottom<=rect(screen.querySelector('.hn-nav')).top&&rect(screen).height<=innerHeight+1};});assert.ok(m.group&&m.noOverflow&&m.within);assert.deepEqual(m.heights,[56,56]);assert.deepEqual(m.widths,[446,446]);assert.equal(m.gap,12);metrics.push(m);await p.locator('.hn-screen').screenshot({path:path.join(out,`after/S03-${width}x${height}.png`)});}await p.setViewportSize({width:494,height:950});});
await check('S04 warehouse spans top; date/time two columns with16/18 typography and20/12 spacing',async()=>{await finish();const m=await p.evaluate(()=>{const meta=document.querySelector('.p14-shift-meta'),w=meta.querySelector('.p14-shift-warehouse'),d=meta.querySelector('.p14-shift-date'),t=meta.querySelector('.p14-shift-time'),h=document.querySelector('.p14-label'),k=document.querySelector('.p14-kpis'),r=e=>e.getBoundingClientRect();return {warehouse:[r(w).x,r(w).width],date:[r(d).x,r(d).y,r(d).width],time:[r(t).x,r(t).y,r(t).width],padding:getComputedStyle(meta).padding,fonts:[getComputedStyle(d.querySelector('dt')).fontSize,getComputedStyle(d.querySelector('dd')).fontSize],gap:Math.round(r(h).top-r(meta).bottom),kpiGap:Math.round(r(k).top-r(h).bottom)};});assert.equal(m.date[1],m.time[1]);assert.ok(m.date[0]<m.time[0]&&m.warehouse[1]>m.date[2]);assert.equal(m.padding,'16px');assert.deepEqual(m.fonts,['16px','18px']);assert.equal(m.gap,20);assert.equal(m.kpiGap,12);metrics.push(m);await p.locator('.hn-screen').screenshot({path:path.join(out,'after/S04-layout.png')});});
await check('S04 footer remains fixed while new metadata and draft content scroll',async()=>{const before=await action('home').boundingBox();await p.locator('.p14-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);assert.deepEqual(await action('home').boundingBox(),before);assert.ok(await p.locator('.p14-drafts').isVisible());await p.locator('.hn-screen').screenshot({path:path.join(out,'after/S04-bottom.png')});});
await check('Overnight uses full-width time field and preserves both dates',async()=>{await p.clock.setFixedTime(new Date('2026-09-28T23:30:00+07:00'));await enter();await p.clock.setFixedTime(new Date('2026-09-29T07:30:00+07:00'));await finish();assert.equal(await p.locator('.p14-shift-time.p14-meta-wide').count(),1);assert.match(await p.locator('.p14-shift-time dd').textContent(),/23:30 · 28\/09\/2026 – 07:30 · 29\/09\/2026/);const m=await p.locator('.p14-shift-meta').evaluate(e=>({warehouse:e.querySelector('.p14-shift-warehouse').offsetWidth,time:e.querySelector('.p14-shift-time').offsetWidth,scroll:e.closest('.p14-scroll').scrollWidth,client:e.closest('.p14-scroll').clientWidth}));assert.equal(m.warehouse,m.time);assert.equal(m.scroll,m.client);await p.locator('.hn-screen').screenshot({path:path.join(out,'after/S04-overnight.png')});});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'layout-results.json'),JSON.stringify({status:'PASS',checks,metrics,errors},null,2));}catch(e){await p.screenshot({path:path.join(out,'layout-failure.png')});fs.writeFileSync(path.join(out,'layout-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
