const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const {mockGeography,choose,address}=require('./outbound_geography_helpers.cjs');
const out='handoff/P24/evidence/revision-01/after';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:'reduce'}),checks=[],errors=[],layout=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);
const snap=async pre=>JSON.parse(await p.locator(`[data-${pre}-snapshot]`).textContent()),pause=()=>p.waitForTimeout(180),a=(pre,n)=>p.locator(`[data-${pre}="${n}"]`).first();
async function shot(n){await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});}
async function test(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function login(sample=''){await p.goto('http://localhost:8766/flows/auth-session/?v=p24-r01'+(sample?'&sample='+sample:''));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p19-tools').evaluate(e=>e.open=true);}
async function input(code){if(!await p.locator('#p19-code').count())await p.click('[data-scan-action=manual]');await p.fill('#p19-code',code);await p.locator('#p19-manual-form [type=submit]').click();}
async function measure(name){for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});await pause();const g=await p.locator('.hn-screen').evaluate(e=>{const f=e.querySelector('.p19-sheet-footer')||e.querySelector('.p19-footer,.p04-footer,.p05-footer'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect(),sc=e.querySelector('.app-modal-body')||e.querySelector('.p19-scroll,.p04-scroll,.p05-scroll');return {w:e.offsetWidth,h:e.offsetHeight,small:[...e.querySelectorAll('button')].filter(b=>b.getClientRects().length&&!b.closest('[inert]')&&(b.offsetWidth<44||b.offsetHeight<44)).map(b=>b.outerHTML),overflow:sc.scrollWidth>sc.clientWidth+1,footer:fr.bottom<=r.bottom+1&&fr.top>=r.top};});assert.deepEqual(g,{w:494,h:950,small:[],overflow:false,footer:true},JSON.stringify({name,width,height,g}));layout.push({name,width,height,...g});await shot(name+'-'+width+'x'+height);}await p.setViewportSize({width:494,height:950});}
async function stock(kind){const pre=kind==='inbound'?'p04':'p05';await p.evaluate(()=>location.hash='#home');await p.click(`.hn-task[data-route=${kind}]`);await p.locator('.'+pre+'-tools').evaluate(e=>e.open=true);if(kind==='outbound'){await choose(p,'source',p.url().includes('sample=b24')?'b24-0004':'board-0005');await p.getByRole('button',{name:'Đổi phiếu',exact:true}).click();await pause();await address(p);}await a(pre,'next').click();await a(pre,'batch').click();if(kind==='outbound'){await a(pre,'manual').click();for(const c of ['HN12352','HN12353','HN12354']){await p.fill('#p05-code',c);await p.locator('.p05-manual [type=submit]').click();}}await a(pre,'next').click();await a(pre,'send').click();await p.waitForSelector(`[data-panel="${pre.toUpperCase()}.S04"]`);return pre;}
try{await login();
await test('A01 quantity invalid, numeric validation, cancel, keyboard/focus, 5 layouts',async()=>{await p.click('[data-p19-demo=quantity-invalid]');const before=(await snap('p19')).lines;assert.equal(await p.inputValue('#p19-quantity'),'13');assert.equal(await p.locator('#p19-quantity').evaluate(e=>getComputedStyle(e).color),'rgb(180, 35, 24)');await measure('S01');for(const v of ['13','0','-1','1.5','abc']){await p.fill('#p19-quantity',v);await p.locator('.p19-sheet [type=submit]').click();assert.equal(await p.locator('#p19-quantity').getAttribute('aria-invalid'),'true');assert.deepEqual((await snap('p19')).lines,before);}await p.locator('.p19-sheet').evaluate(e=>e.parentElement.click());assert.equal(await p.locator('.p19-sheet').count(),1);await p.keyboard.press('Tab');assert.equal(await p.locator('.p19-sheet').evaluate(e=>e.contains(document.activeElement)),true);await p.fill('#p19-quantity','12');await p.locator('.p19-sheet [type=submit]').click();await pause();assert.equal((await snap('p19')).counts.quantity,13);assert.equal((await snap('p19')).receipt,null);});
await test('A02 unreceived BOX keeps accepted lines/id/version; Back and manual retry',async()=>{await p.click('[data-p19-demo=scan-error]');await p.waitForSelector('[data-panel="P24.S02"]');const before=await snap('p19');assert.equal(before.lines.length,1);await measure('S02');await a('p19','retry-code').click();await pause();assert.equal(await p.inputValue('#p19-code'),'BOX-NOT-RECEIVED');assert.equal(await p.locator('#p19-code').evaluate(e=>e===document.activeElement),true);await input('BOX-NOT-RECEIVED');await p.goBack();await pause();assert.deepEqual((await snap('p19')).document,before.document);assert.deepEqual((await snap('p19')).lines,before.lines);await input('BOX-NOT-RECEIVED');await a('p19','other-code').click();await pause();assert.equal(await p.locator('#p19-code').count(),0);});
await test('A04 closed history no issue; paging keeps rows, info and warranty-history routes',async()=>{await p.evaluate(()=>location.hash='#p02/component-history?case=BH-002&sample=history');await p.waitForSelector('[data-p20-document]');assert.equal(await a('p20','issue').isVisible(),false);await shot('S04-sample');const id=await p.locator('[data-p20-document]').first().getAttribute('data-p20-document');await a('p20','load').click();await p.waitForSelector('.p20-end');assert.equal(await p.locator('[data-p20-document]').count(),2);assert.equal(await p.locator('[data-p20-document]').first().getAttribute('data-p20-document'),id);await a('p20','info').click();await p.waitForSelector('.p09-app');assert.match(await p.locator('.p09-app').innerText(),/BH-002/);await p.evaluate(()=>location.hash='#p02/component-history?case=BH-002');await p.waitForSelector('.p20-app');await p.waitForSelector('.p20-end');await measure('S04');assert.match(await p.locator('.p20-app').innerText(),/XLK-0003/);assert.doesNotMatch(await p.locator('.p20-app').innerText(),/XLK-0002/);await a('p20','history').click();await p.waitForSelector('[data-panel="P23.S01"]');await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-002&panel=3');await p.waitForSelector('.p19-app');assert.equal(await a('p19','post').count(),0);assert.match(await p.locator('.p19-app').innerText(),/Hồ sơ đã trả khách/);});
await test('A03 default PN/PX record, inventory delta zero, actual IDs/counts, history',async()=>{for(const kind of ['inbound','outbound']){const pre=await stock(kind),s=await snap(pre);assert.equal(s.metrics.inventoryDelta,0);assert.equal(s.outcome,'recorded');assert.equal(s.accepted.length,kind==='inbound'?11:10);assert.match(await p.locator('.hn-waiting-web').innerText(),/Chờ xử lý trên Web/);assert.doesNotMatch(await p.locator('.hn-waiting-web').innerText(),/Đã xuất/);await measure('S03-'+kind);await a(pre,'history').click();await p.waitForSelector('.p08-app');}});
await test('B24 opt-in PN0005/12 codes and PX0004/10 codes from record owner',async()=>{await login('b24');for(const kind of ['inbound','outbound']){const pre=await stock(kind),s=await snap(pre);assert.equal(s.document.number,kind==='inbound'?'PN-0005':'PX-0004');assert.equal(s.accepted.length,kind==='inbound'?12:10);assert.equal(s.metrics.inventoryDelta,0);await shot('B24-S03-'+kind);}});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,layout,errors},null,2));console.log(checks.length+' groups, '+layout.length+' layouts PASS');
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,layout,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
