const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out=path.resolve(process.env.MOTION_P09_EVIDENCE_DIR||'handoff/motion/M09/'+(before?'before':'evidence'));fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/warranty/warranty.mjs','docs/flows/warranty/style.css','docs/flows/warranty/warranty-model.mjs','docs/flows/shared/warranty-cases.mjs','docs/flows/home/home.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
if(before)for(const f of files){const dst=path.join(out,'source',f);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(f,dst);}
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(files.map(f=>({file:f,bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')})),null,2));
(async()=>{const b=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
 const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));
 await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));await c.tracing.start({screenshots:true,snapshots:true,sources:true});
 await p.addInitScript(()=>{window.qaAnimations=[];window.qaFrames=[];window.qaHardware=0;window.qaListeners=0;const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaListeners--;return remove.call(this,t,f,o);};const native=Element.prototype.animate;Element.prototype.animate=function(frames,opts){const row={node:this.id||this.className,primitive:this.dataset.motionPrimitive,frames,duration:opts.duration,cancelled:false};qaAnimations.push(row);const a=native.call(this,frames,opts),cancel=a.cancel.bind(a);a.cancel=()=>{row.cancelled=true;cancel();};if(row.primitive?.startsWith('Case')||row.primitive?.startsWith('Warranty')){const n=this,start=performance.now();function tick(){qaFrames.push({primitive:row.primitive,opacity:getComputedStyle(n).opacity,connected:n.isConnected});if(n.isConnected&&performance.now()-start<180)requestAnimationFrame(tick);}requestAnimationFrame(tick);}return a;};if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('Hardware not authorized');};});
 const a=n=>p.locator(`[data-p09="${n}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p09-snapshot]').textContent()),settle=()=>p.waitForTimeout(250);
 async function route(panel,extra=''){await p.evaluate(h=>location.hash=h,'#p02/warranty?panel='+panel+extra);await p.locator(`[data-panel="P09.S0${panel}"]`).waitFor();await settle();}
 async function capture(id){await settle();await p.evaluate(()=>scrollTo(0,0));r.geometry[id]=await p.locator('.p09-app').evaluate(app=>{const shell=app.closest('.hn-screen'),base=shell.getBoundingClientRect();return Object.fromEntries(['.p09-header','.p09-scroll','.p09-footer','.p09-tabs','.p09-case-summary','.p09-success','.hn-nav'].map(s=>{const n=shell.querySelector(s);if(!n)return[s,null];const q=n.getBoundingClientRect();return[s,[q.x-base.x,q.y-base.y,q.width,q.height]];}));});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});}
 async function check(name,fn){await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);}
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');
 await route(1);await capture('P09.S01');r.profile=await p.locator('.p09-app').evaluate(e=>({rows:e.querySelectorAll('.p09-case').length,nodes:e.querySelectorAll('*').length}));await a('begin').click();await capture('P09.S02');await route(3,'&case=BH-001&tab=info');await capture('P09.S03');await a('update').click();await p.fill('.p09-update-dialog [name=result]','Đã sửa chữa, kiểm tra ổn định.');await p.click('.p09-update-dialog [type=submit]');await p.locator('[data-panel="P09.S04"]').waitFor();await capture('P09.S04');r.initialResult=(await snap()).writes;
 if(!before)await runChecks({p,r,a,snap,settle,route,capture,check,mode,out});
 assert.deepEqual(r.errors,[]);r.hardware=await p.evaluate(()=>qaHardware);await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});await c.close();
 }fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})();
async function runChecks({p,r,a,snap,settle,route,check,mode,out}){
 const clear=()=>p.evaluate(()=>qaAnimations=[]),effects=()=>p.evaluate(()=>qaAnimations.filter(e=>/^(Warranty|CaseTabs)/.test(e.primitive||'')));
 const tab=t=>p.locator(`[data-p09-tab="${t}"]`);
 await check('S01 press100/filter140, stable search input and no row/route replay',async()=>{
  await route(1);await p.locator('#p09-query').evaluate(e=>{window.qaQuery=e;e.focus();});await clear();await p.fill('#p09-query','BH-00');await settle();assert.equal(await p.locator('#p09-query').evaluate(e=>e===qaQuery&&e===document.activeElement),true);await p.locator('[data-p09-status="Đang kiểm tra"]').dispatchEvent('pointerdown');await p.click('[data-p09-status="Đang kiểm tra"]');await settle();const log=await effects();assert.ok(mode==='off'?log.length===0:log.some(e=>e.primitive==='WarrantyFilter'));assert.ok(log.every(e=>e.duration===(e.primitive==='WarrantyPress'?100:mode==='auto'?140:80)));assert.equal(await p.evaluate(()=>qaAnimations.some(e=>e.node==='hn-destination')),false);await p.click('[data-p09-status="Đang kiểm tra"]');await p.fill('#p09-query','');
 });
 await check('S03 selected indicator140, rapid tabs keep one case/CTA and independent scroll',async()=>{
  await route(3,'&case=BH-001&tab=info');await p.locator('.p09-scroll').evaluate(e=>e.scrollTop=130);const top=await p.locator('.p09-scroll').evaluate(e=>e.scrollTop);await clear();for(const t of ['parts','events','info','parts','info'])await tab(t).click();assert.match(await p.locator('.p09-case-summary').textContent(),/BH-001/);assert.equal(await p.locator('.p09-footer [data-p09=update]').count(),1);assert.equal(await tab('info').getAttribute('aria-selected'),'true');assert.ok(Math.abs(await p.locator('.p09-scroll').evaluate(e=>e.scrollTop)-top)<2);await settle();const log=(await effects()).filter(e=>e.primitive==='CaseTabs');assert.ok(mode==='off'?log.length===0:log.length===5);assert.ok(log.every(e=>e.duration===(mode==='auto'?140:80)));assert.equal(await p.evaluate(()=>qaAnimations.some(e=>e.node==='hn-destination')),false);r.parts=await tab('parts').locator('.hn-tab-count').textContent();
 });
 await check('S02 invalid serial fades only error slot; camera/form/input remain connected at compact viewport',async()=>{
  await route(2);await p.click('[data-scan-action=manual]');await p.fill('[name=note]','Ghi chú phải giữ nguyên');await p.locator('#p09-code').evaluate(e=>{window.qaCode=e;window.qaCamera=document.querySelector('.hn-scan-camera');window.qaNote=document.querySelector('[name=note]');});await clear();await p.fill('#p09-code','SKU-NOT-SERIAL');await p.locator('#p09-code').press('Enter');assert.equal(await p.evaluate(()=>qaCode.isConnected&&qaCamera.isConnected&&qaNote.isConnected&&qaCode===document.activeElement),true);await settle();let log=await effects();assert.ok(mode==='off'?log.length===0:log.some(e=>e.primitive==='WarrantyFormFeedback'));assert.ok(log.every(e=>!e.node.includes('camera')));await p.setViewportSize({width:360,height:420});await p.locator('[name=note]').focus();await p.locator('[name=note]').press('End');await p.locator('[name=note]').pressSequentially(' ✓');assert.equal(await p.evaluate(()=>qaNote.isConnected&&qaNote===document.activeElement),true);assert.ok(await p.locator('[name=note]').inputValue().then(v=>v.endsWith('✓')));await p.setViewportSize({width:494,height:950});
 });
 await check('Intake failure retains request/serial/note/DOM and returns focus; retry writes once',async()=>{
  await p.fill('#p09-code','SN-XP420B-BK-0008');await p.locator('#p09-code').press('Enter');await a('fault').click();await p.click('.p09-fault-picker input[value=usb]');await p.locator('[name=note]').evaluate(e=>window.qaIntakeNote=e);await p.locator('.p09-tools details').evaluate(e=>e.open=true);await p.selectOption('[data-p09-mode]','error');await a('intake').click();await p.click('.p09-intake-confirm [type=submit]');await p.locator('.hn-action-dialog[open]').waitFor();const id=(await snap()).request.id;assert.equal(await p.evaluate(()=>qaIntakeNote.isConnected),true);assert.equal((await snap()).draft.item.serial,'SN-XP420B-BK-0008');await p.keyboard.press('Escape');await p.waitForFunction(()=>document.activeElement?.dataset.p09==='intake');await p.selectOption('[data-p09-mode]','ready');await a('intake').click();await p.click('.p09-intake-confirm [type=submit]');await p.locator('[data-panel="P09.S03"]').waitFor();await p.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await settle();assert.equal((await snap()).receipt.requestId,id);assert.equal((await snap()).writes,2);r.newCase=(await snap()).receipt.caseId;
 });
 await check('S04 success160 occurs once after receipt, status remains waiting and Back never replays',async()=>{
  await a('update').click();await p.fill('.p09-update-dialog [name=result]','Đã kiểm tra và sửa xong.');await clear();await p.click('.p09-update-dialog [type=submit]');await p.locator('[data-panel="P09.S04"]').waitFor();await settle();const log=(await effects()).filter(e=>e.primitive==='WarrantySuccess');assert.equal(log.length,mode==='auto'?1:0);if(log.length)assert.equal(log[0].duration,160);assert.match(await p.locator('.p09-success').innerText(),/Chờ bàn giao/);assert.doesNotMatch(await p.locator('.p09-success').innerText(),/Đã trả khách/);await a('view').click();await p.locator('[data-panel="P09.S03"]').waitFor();await clear();await p.goForward();await p.locator('[data-panel="P09.S04"]').waitFor();await settle();assert.equal((await effects()).length,0);assert.equal((await snap()).writes,3);
 });
 await check('UNKNOWN blocks duplicate update and reconciles exact request independently of motion',async()=>{
  await route(3,'&case=BH-007&tab=info');await p.selectOption('[data-p09-mode]','unknown');await a('update').click();await p.fill('.p09-update-dialog [name=result]','Đã sửa lỗi kết nối.');await p.click('.p09-update-dialog [type=submit]');await p.locator('.hn-action-dialog[open]').waitFor();assert.equal((await snap()).unknown,true);const id=(await snap()).request.id;assert.equal(await a('update').isDisabled(),true);assert.equal(await p.locator('[data-panel="P09.S04"]').count(),0);await p.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await p.locator('[data-panel="P09.S04"]').waitFor();assert.equal((await snap()).receipt.requestId,id);assert.equal((await snap()).writes,4);await p.selectOption('[data-p09-mode]','ready');
 });
 await check('Closed case during P19 quantity sheet blocks mutation before any presentation',async()=>{
  await route(3,'&case=BH-003&tab=parts');await a('issue').click();await p.locator('.p19-app').waitFor();await p.click('[data-scan-action=manual]');await p.fill('#p19-code','BOX-LK-0002-01');await p.locator('#p19-code').press('Enter');await p.locator('.p19-sheet').waitFor();await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');window.qaOldCase=m.readWarrantyCases().find(c=>c.id==='BH-003');m.writeWarrantyCase({...qaOldCase,status:'Đã trả khách',version:qaOldCase.version+1});});await p.fill('#p19-quantity','2');await p.locator('.p19-sheet [type=submit]').click();await settle();const state=JSON.parse(await p.locator('[data-p19-snapshot]').textContent());assert.equal(state.lines.length,0);assert.equal(state.metrics.post,0);assert.match(await p.locator('.hn-screen').innerText(),/đã trả|đóng|chỉ xem/i);await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.writeWarrantyCase(qaOldCase);});if(await p.locator('dialog[open]').count())await p.keyboard.press('Escape');
 });
 await check('Mode/OS/hidden interruptions cancel; ten route cycles clean listeners; no camera startup',async()=>{
  await route(1);await p.fill('#p09-query','BH');await p.selectOption('#home-motion-mode','off');assert.equal(await p.locator('.p09-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.selectOption('#home-motion-mode','auto');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),'reduced');await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.fill('#p09-query','BH-0');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p09-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.click('[data-tab=home]');const n=await p.evaluate(()=>qaListeners);for(let i=0;i<10;i++){await route(1);assert.equal(await p.evaluate(()=>qaListeners),n+1);await p.click('[data-tab=home]');assert.equal(await p.evaluate(()=>qaListeners),n);}assert.equal(await p.evaluate(()=>qaHardware),0);
 });
 await route(3,'&case=BH-001&tab=info');await a('handoff').click();await p.locator('.p18-app').waitFor();await p.goBack();await p.locator('.p09-app').waitFor();assert.match(await p.locator('.p09-case-summary').textContent(),/BH-001/);
 r.domain=await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');return {cases:m.readWarrantyCases().map(c=>({id:c.id,serial:c.serial,status:c.status,version:c.version,events:c.events.map(e=>e.label)})),ledger:m.WARRANTY_LEDGER.map(d=>({id:d.id,quantity:d.lines.reduce((n,l)=>n+l.quantity,0)}))};});r.operations=(await snap()).writes;r.frames=await p.evaluate(()=>qaFrames);r.effects=await effects();if(mode==='auto')assert.ok(r.frames.some(e=>e.connected&&Number(e.opacity)<1));
 await check('Logout/security immediately removes protected content and Back cannot restore it',async()=>{await p.click('#hn-logout');await p.locator('#login-form').waitFor();assert.equal(await p.locator('.p09-app').count(),0);await p.goBack();assert.equal(await p.locator('.p09-app').count(),0);});
}
