const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.PROFILE_EDGE_EVIDENCE_DIR||'handoff/P10/evidence/revision-10/after');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[]; let auditPage=null;
const settle=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r)))));
async function check(name,fn){const fresh=!auditPage;const p=auditPage||(auditPage=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}));await p.setViewportSize({width:494,height:1000});p.setDefaultTimeout(15000);p.setDefaultNavigationTimeout(30000);const errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.addInitScript(()=>{window.__testHeight=0;Object.defineProperty(window.visualViewport,'height',{get:()=>window.__testHeight||innerHeight});});if(fresh)await p.goto('http://127.0.0.1:8766/flows/auth-session/');else await p.evaluate(()=>{window.__testHeight=0;document.querySelector('#reset').click();});await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('[data-tab=profile]');await fn(p);assert.deepEqual(errors,[]);results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message,errors});console.log('FAIL '+name+': '+e.message.split('\n')[0]);await p.screenshot({path:path.join(out,`failure-${results.length}.png`),fullPage:true});}finally{p.removeAllListeners('pageerror');}}
const act=(p,a)=>p.locator(`[data-p10=${a}]`).first();
await check('Compact-height account menu has disjoint hit areas for adjacent actions',async p=>{await p.setViewportSize({width:340,height:420});await settle(p);const overlap=await p.evaluate(()=>{const scale=document.querySelector('.hn-screen').getBoundingClientRect().width/494;const boxes=[...document.querySelectorAll('.p10-account-group button,.p10-shift-section button,[data-p10=logout]')].map(e=>{const b=e.getBoundingClientRect(),c=getComputedStyle(e,'::before');return{x:b.x+parseFloat(c.left)*scale,y:b.y+parseFloat(c.top)*scale,w:parseFloat(c.width)*scale,h:parseFloat(c.height)*scale};});return boxes.flatMap((a,i)=>boxes.slice(i+1).filter(b=>Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>1&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>1));});assert.equal(overlap.length,0);await p.locator('.hn-screen').screenshot({path:path.join(out,'compact-profile.png')});});
await check('Partially clipped avatar cannot project a hit area into the next form field',async p=>{await p.setViewportSize({width:360,height:800});await act(p,'edit').click();await p.evaluate(()=>{const s=document.querySelector('.p10-scroll'),b=document.querySelector('[data-p10=avatar]'),scale=document.querySelector('.hn-screen').getBoundingClientRect().width/494;s.scrollTop+=(b.getBoundingClientRect().bottom-s.getBoundingClientRect().top-2)/scale;});await settle(p);const r=await p.evaluate(()=>{const b=document.querySelector('[data-p10=avatar]'),r=b.getBoundingClientRect(),c=getComputedStyle(b,'::before'),scale=document.querySelector('.hn-screen').getBoundingClientRect().width/494;return{hitBottom:r.y+(parseFloat(c.top)+parseFloat(c.height))*scale,cardBottom:b.closest('.p10-avatar-card').getBoundingClientRect().bottom};});assert.ok(r.hitBottom<=r.cardBottom+1,JSON.stringify(r));});
await check('Closing software-keyboard viewport clears added blank scroll room even after Done',async p=>{await act(p,'edit').click();await p.fill('#p10-phone','0909 111 222');await p.evaluate(()=>{window.__testHeight=320;visualViewport.dispatchEvent(new Event('resize'));});await settle(p);assert.ok(await p.locator('.p10-scroll').evaluate(e=>parseFloat(e.style.getPropertyValue('--hn-form-keyboard-inset'))>0));await p.locator('#p10-phone').press('Enter');await p.evaluate(()=>{window.__testHeight=0;visualViewport.dispatchEvent(new Event('resize'));});await settle(p);const inset=await p.locator('.p10-scroll').evaluate(e=>parseFloat(e.style.getPropertyValue('--hn-form-keyboard-inset'))||0);assert.equal(inset,0);assert.equal(await p.locator('.p10-dialog').count(),0);});
await check('Avatar response is ignored when the route changes before the result arrives',async p=>{await act(p,'edit').click();await p.evaluate(()=>{document.querySelector('[data-p10=avatar]').click();location.hash='#p02/profile?panel=3';});await p.locator('[data-panel="P10.S03"]').waitFor();await settle(p);assert.equal(await p.locator('.p10-dialog').count(),0);});
await check('Shift Back consumes the actual caller entry instead of re-opening Shift on native Back',async p=>{await act(p,'shift').click();await p.locator('[data-panel="P14.S03"]').waitFor();await p.click('[data-p14=back]');await p.locator('[data-panel="P10.S01"]').waitFor();await p.goBack();await p.locator('#hn-home:visible').waitFor();});
await check('Compact confirmation targets stay within their action footer, away from explanatory text',async p=>{await p.setViewportSize({width:340,height:420});await act(p,'logout').click();await settle(p);const rects=await p.evaluate(()=>{const d=document.querySelector('.p10-dialog'),f=d.querySelector('.app-modal-footer').getBoundingClientRect(),scale=document.querySelector('.hn-screen').getBoundingClientRect().width/494;return [...d.querySelectorAll('button')].map(e=>{const r=e.getBoundingClientRect(),c=getComputedStyle(e,'::before');return{top:r.top+parseFloat(c.top)*scale,bottom:r.top+(parseFloat(c.top)+parseFloat(c.height))*scale,footerTop:f.top,footerBottom:f.bottom};});});assert.ok(rects.every(r=>r.top>=r.footerTop-1&&r.bottom<=r.footerBottom+1),JSON.stringify(rects));await p.locator('.hn-screen').screenshot({path:path.join(out,'compact-dialog.png')});});
await check('Rapid avatar then navigation away and re-entry does not resurrect an old dialog',async p=>{await act(p,'edit').click();await p.evaluate(()=>{document.querySelector('[data-p10=avatar]').click();document.querySelector('[data-tab=home]').click();document.querySelector('[data-tab=profile]').click();});await p.locator('[data-panel="P10.S01"]').waitFor();await settle(p);assert.equal(await p.locator('.p10-dialog').count(),0);});
await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length},null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;})();
