const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out='handoff/motion/M16/evidence'+(before?'/before':'');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];let p;
try{for(const mode of ['auto','os-reduced','off']){
 const context=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'});p=await context.newPage();p.setDefaultTimeout(25000);
 const r={mode,checks:[],geometry:{},errors:[],writes:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));p.on('request',req=>{if(!['GET','HEAD'].includes(req.method()))r.writes.push(req.method()+' '+req.url());});
 await p.route('**/home/home.mjs*',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync('docs/flows/home/home.mjs','utf8').replace('onSystemError:showSystem,supplierHistory','readList:window.m16Read,onSystemError:showSystem,supplierHistory')}));
 await p.addInitScript(()=>{
  window.m16Source='hold';window.m16Reads=[];window.m16Animations=[];window.m16Samples=[];window.m16Long=[];window.m16Hardware=0;window.m16Listeners=0;
  window.m16Read=ctx=>{const request={ctx};m16Reads.push(request);if(m16Source==='hold')return new Promise((resolve,reject)=>Object.assign(request,{resolve,reject}));if(m16Source==='error')throw Error('fixture read failure');return m16Source==='empty'?[]:window.m16Rows;};
  const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')m16Listeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')m16Listeners--;return remove.call(this,t,f,o);};
  const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){const entry={primitive:this.dataset.motionPrimitive||'',duration:options.duration,frames,cancelled:false};m16Animations.push(entry);const effect=animate.call(this,frames,options),cancel=effect.cancel.bind(effect);effect.cancel=()=>{entry.cancelled=true;cancel();};if(['EmptyState','DataState'].includes(entry.primitive)){const node=this,start=performance.now();const sample=()=>{m16Samples.push({primitive:entry.primitive,time:performance.now()-start,opacity:getComputedStyle(node).opacity});if(node.isConnected&&performance.now()-start<170)requestAnimationFrame(sample);};requestAnimationFrame(sample);}return effect;};
  new PerformanceObserver(l=>m16Long.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});
  if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{m16Hardware++;throw Error('not used')};window.NDEFReader=class{constructor(){m16Hardware++;}};
 });
 await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
 const act=a=>p.locator(`[data-p12="${a}"]`).first();
 const query=async value=>{await p.fill('#p12-query',value);await p.press('#p12-query','Enter');};
 const settle=()=>p.waitForTimeout(260),check=async(name,fn)=>{await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);};
 const effects=()=>p.evaluate(()=>m16Animations.filter(x=>['EmptyState','DataState'].includes(x.primitive)));
 async function capture(id){await settle();await p.evaluate(()=>scrollTo(0,0));r.geometry[id]=await p.locator('.p12-app').evaluate(app=>{const shell=app.closest('.hn-screen'),base=shell.getBoundingClientRect();return {text:app.innerText,rects:Object.fromEntries(['.p12-header','.p12-list-controls','.p12-scroll','.p16-state','.p16-art','.p16-actions','.p16-loading','.hn-nav'].map(s=>{const e=shell.querySelector(s),r=e?.getBoundingClientRect();return[s,r?[r.x-base.x,r.y-base.y,r.width,r.height]:null]})),nodes:app.querySelectorAll('*').length};});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});}
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.locator('#motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.evaluate(async()=>m16Rows=(await import('/flows/documents/document-model.mjs')).mergeDocuments([]));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#home-app:visible');
 if(!before)await context.tracing.start({screenshots:true,snapshots:true,sources:false});
 await p.click('[data-tab=documents]');await p.waitForSelector('[data-panel="P16.S01"]');await capture('P16.S01');
 if(!before)await check('S01 fixed skeleton/no shimmer; spinner only pending; mode fallback',async()=>{assert.equal(await p.locator('.p16-skeleton').count(),6);assert.equal(await p.locator('.p12-records').getAttribute('aria-busy'),'true');assert.equal(await p.locator('.p16-spinner').evaluate(e=>getComputedStyle(e).animationName),mode==='auto'?'p16-spin':'none');assert.ok(await p.locator('.p16-skeleton').evaluateAll(es=>es.every(e=>getComputedStyle(e).animationName==='none')));});
 await p.evaluate(()=>m16Reads.at(-1).resolve([]));await p.waitForSelector('[data-panel="P16.S02"]');await capture('P16.S02');
 await p.evaluate(()=>m16Source='ready');await query('PN-9999');await p.waitForSelector('[data-panel="P16.S03"]');await capture('P16.S03');
 await p.evaluate(()=>m16Source='error');await query('');await p.waitForSelector('[data-panel="P16.S04"]');await capture('P16.S04');
 if(!before){
 await check('S02/S03 opacity140/80/off only, error/CTA immediate and static',async()=>{const list=await effects();assert.equal(list.length,mode==='off'?0:4);for(const e of list){assert.equal(e.duration,mode==='auto'?140:80);assert.ok(e.frames.every(f=>f.opacity>0&&!('transform'in f)));}assert.equal(await p.locator('.p16-state').evaluate(e=>e.getAnimations({subtree:true}).length),0);assert.ok(await act('retry').isEnabled());});
 await check('Retry one read, preserves filter/input/focus, no intermediate empty; no extra domain operations',async()=>{await query('PN-0005');await p.evaluate(()=>{m16Source='hold';window.retryCount=m16Reads.length;window.oldInput=document.querySelector('#p12-query');window.intermediateEmpty=false;window.watch=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1&&(n.matches?.('[data-panel="P16.S02"]')||n.querySelector?.('[data-panel="P16.S02"]')))intermediateEmpty=true;});watch.observe(document.querySelector('.p12-records'),{childList:true,subtree:true});const b=document.querySelector('[data-p12=retry]');b.click();b.click();});assert.equal(await p.evaluate(()=>m16Reads.length-retryCount),1);await p.evaluate(()=>m16Reads.at(-1).resolve(m16Rows));await p.waitForSelector('.p12-record');assert.equal(await p.locator('.p12-record').count(),1);assert.equal(await p.inputValue('#p12-query'),'PN-0005');assert.ok(await p.locator('#p12-query').evaluate(e=>e===oldInput));assert.equal(await p.evaluate(()=>intermediateEmpty),false);await p.evaluate(()=>watch.disconnect());});
 await check('A slow/B fast; stale A after exit cannot overwrite state or animate',async()=>{await p.evaluate(()=>m16Source='hold');await query('A');await p.evaluate(()=>window.requestA=m16Reads.at(-1));await p.evaluate(()=>m16Source='ready');await query('PN-0005');assert.equal(await p.locator('.p12-record').count(),1);const n=(await effects()).length;await p.click('[data-tab=home]');await p.evaluate(()=>requestA.resolve([]));await settle();assert.equal(await p.locator('.p12-app').count(),0);assert.equal((await effects()).length,n);await p.click('[data-tab=documents]');assert.equal(await p.inputValue('#p12-query'),'PN-0005');});
 await check('No replay after Back or repaint; debouncing is text-only until request starts',async()=>{await query('PN-9999');await settle();const n=(await effects()).length;await p.click('[data-tab=home]');await p.click('[data-tab=documents]');await settle();assert.equal((await effects()).length,n);await p.fill('#p12-query','new-search');assert.equal(await p.locator('.p16-spinner').evaluate(e=>getComputedStyle(e).animationName),'none');await p.press('#p12-query','Enter');await settle();});
 await check('Mid-animation off/OS change/hidden/route cancellation; no delayed action or replay',async()=>{
  await p.evaluate(()=>{m16Source='ready';const input=document.querySelector('#p12-query');input.value='mode-cancel';input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));const select=document.querySelector('#home-motion-mode');select.value='off';select.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('.p12-app').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);
  await p.locator('#home-motion-mode').evaluate((e,m)=>{e.value=m==='off'?'off':'auto';e.dispatchEvent(new Event('change',{bubbles:true}));},mode);
  const n=(await effects()).length;await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await query('hidden-state');assert.equal((await effects()).length,n);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.press('#p12-query','Enter');await settle();assert.equal((await effects()).length,n);
  await query('os-cancel');if(mode==='auto'){await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.p12-app').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await p.emulateMedia({reducedMotion:'no-preference'});}
 });
 await check('Stale refresh retains anchor; ten navigation cycles clean listeners; small viewport and reader Back',async()=>{
  await p.evaluate(()=>m16Source='ready');await act('clear').click();await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=500);const y=await p.locator('.p12-scroll').evaluate(e=>e.scrollTop);
  await p.evaluate(()=>{m16Source='error';const b=document.createElement('button');b.dataset.p12='retry';document.querySelector('.p12-app').append(b);b.click();b.remove();});assert.equal(await p.locator('.p12-record').count(),24);assert.equal(await p.locator('[data-data-state=stale]').count(),1);await p.evaluate(()=>m16Source='hold');await act('retry').evaluate(e=>e.click());assert.equal(await p.locator('.p12-record').count(),24);await p.evaluate(()=>m16Reads.at(-1).resolve(m16Rows));await settle();assert.ok(Math.abs(await p.locator('.p12-scroll').evaluate(e=>e.scrollTop)-y)<2);
  await p.evaluate(()=>m16Source='ready');await p.click('[data-tab=home]');const count=await p.evaluate(()=>m16Listeners);for(let i=0;i<10;i++){await p.click('[data-tab=documents]');await p.click('[data-tab=home]');}assert.equal(await p.evaluate(()=>m16Listeners),count);await p.click('[data-tab=documents]');await p.setViewportSize({width:360,height:420});await query('Dữ liệu dài 📦 '.repeat(180));await act('read-query').click();assert.equal(await p.locator('.app-modal-host').count(),1);await p.goBack();await p.waitForSelector('.app-modal-host',{state:'detached'});assert.ok(await act('read-query').evaluate(e=>e===document.activeElement));await p.setViewportSize({width:494,height:950});
 });
 await check('Readonly empty creates nothing; expiry cancels current data motion immediately',async()=>{await p.evaluate(()=>m16Source='empty');await query('readonly');await p.locator('.p16-tools').evaluate(e=>e.open=true);await p.check('#p16-readonly');assert.equal(await p.locator('[data-p12=create]').count(),0);await p.uncheck('#p16-readonly');await p.evaluate(()=>{m16Source='ready';const i=document.querySelector('#p12-query');i.value='expiry';i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));document.querySelector('[data-system-demo=expired]').click();});assert.equal(await p.locator('[data-panel="P15.S02"]').count(),1);assert.equal(await p.locator('#hn-destination').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);});
 await context.tracing.stop({path:path.join(out,mode+'-trace.zip')});
 }
 r.animations=await p.evaluate(()=>m16Animations);r.samples=await p.evaluate(()=>m16Samples);r.longTasks=await p.evaluate(()=>m16Long);r.domain=await p.evaluate(()=>({readCalls:m16Reads.length,hardware:m16Hardware,seed:m16Rows.map(r=>[r.id,r.status,r.lines?.map(l=>l.quantity)]),writes:0}));assert.deepEqual(r.errors,[]);assert.deepEqual(r.writes,[]);await context.close();
}
if(!before){const old=JSON.parse(fs.readFileSync('handoff/motion/M16/evidence/before/results.json'));for(const r of results){assert.deepEqual(r.geometry,old.results.find(x=>x.mode===r.mode).geometry,'settled geometry/text/node equality');assert.deepEqual(r.domain,results[0].domain,'same domain results and operations across modes');}}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({before,results},null,2));console.log('PASS M16 '+results.reduce((n,r)=>n+r.checks.length,0)+' groups');
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results},null,2));await p?.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
