const {mockGeography,address:prepareAddress}=require('./outbound_geography_helpers.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.OUTBOUND_EVIDENCE_DIR || 'handoff/P05/evidence'); fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});
 const checks=[],errors=[],external=[],metrics=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:')&&!r.url().startsWith('https://provinces.open-api.vn/api/v1/'))external.push(r.url());});
 await page.addInitScript(()=>{window.__cameraRequests=0;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{window.__cameraRequests++;throw Error('no camera');};});
 const act=n=>page.locator(`[data-p05="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p05-snapshot]').textContent());
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home').waitFor({state:'visible'});}
 async function enter(){await page.locator('.hn-task[data-route="outbound"]').click();await page.locator('.p05-tools summary').click();}
 async function manual(code){if(!await page.locator('#p05-code').count())await act('manual').click();await page.locator('#p05-code').fill(code);await page.locator('#p05-code').press('Enter');}
 async function seven(){await prepareAddress(page);await page.fill('[data-p05-field="planned"]','10');await act('next').click();await act('batch').click();}
 async function full(){await seven();for(const c of ['HN12352','HN12353','HN12354'])await manual(c);await act('close-manual').click();await act('next').click();}
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const app=document.querySelector('.p05-app'),s=document.querySelector('.hn-screen'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],clientWidth:document.documentElement.clientWidth,dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,screen:{width:r.width,height:r.height,bottom:r.bottom},overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,controls:[...app.querySelectorAll('.p05-footer button')].map(b=>{const r=b.getBoundingClientRect();return {bottom:r.bottom,right:r.right,left:r.left};})};});metrics.push({name,...m});assert.equal(m.overflow,false);const fit=Math.min(1,m.clientWidth/494,m.viewport[1]/950);assert.ok(Math.abs(m.screen.width-494*fit)<1,name+' width');assert.ok(Math.abs(m.screen.height-950*fit)<1,name+' height');assert.ok(m.controls.every(c=>c.bottom<=m.screen.bottom+1&&c.right<=m.clientWidth+1));}
 async function matrix(name){for(const [w,h] of [[494,1000],[360,800],[430,932],[1440,900],[340,420]]){await page.setViewportSize({width:w,height:h});await capture(name+'-'+w+'x'+h);}await page.setViewportSize({width:494,height:1000});}
 try{
 await mockGeography(page);await login();await enter();
 await check('S01 metadata session lock, required phone/address and notes',async()=>{await matrix('P05-S01');assert.equal(await page.locator('[aria-label="Kho xuất"]').inputValue(),'Kho Hoa Nam');assert.equal(await page.locator('[aria-label="Số lượng cần soạn"]').inputValue(),'1');await page.locator('[data-p05-field="phone"]').fill('');await act('next').click();assert.equal((await snap()).step,1);await page.locator('[data-p05-field="phone"]').fill('0901 234 567');});
 await check('A01 S02 seven of ten, one duplicate, no implicit completion',async()=>{await seven();assert.equal((await snap()).accepted.length,7);assert.equal((await snap()).attempts.length,8);await matrix('P05-S02');await act('all').click();assert.equal(await page.locator('.p05-attempt').count(),8);await act('all').click();});
 await check('S03 missing three, groups 5+2, send disabled, back retains identity',async()=>{await act('next').click();assert.equal(await act('send').isDisabled(),true);assert.match(await page.locator('.p05-warning').textContent(),/Còn thiếu 3/);assert.deepEqual(await page.locator('.p05-product > div:last-child strong').allTextContents(),['5','2']);await matrix('P05-S03');const d=(await snap()).document;await act('back').click();await act('back').click();await page.locator('[data-p05-note]').fill('Giao hàng theo phiếu gốc');await act('next').click();assert.equal((await snap()).document.documentId,d.documentId);assert.equal((await snap()).accepted.length,7);});
 await check('A04 P17.S02 keeps draft and accepted codes, focus returns',async()=>{const before=await snap();await manual('HN99999');await page.locator('[data-panel="P17.S02"]').waitFor();assert.deepEqual((await snap()).accepted,before.accepted);await capture('P17-S02-from-P05');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'H1');await act('exception-back').click();assert.equal(await page.evaluate(()=>document.activeElement.dataset.p05),'manual');});
 await check('A03 add three by manual pipeline, keyboard and no loss after invalid',async()=>{await manual('HN-WRONG-WAREHOUSE');assert.equal((await snap()).accepted.length,7);for(const c of ['HN12352','HN12353','HN12354'])await manual(c);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.tagName),'BUTTON');await act('close-manual').click();await act('next').click();assert.equal((await snap()).accepted.length,10);assert.equal(await act('send').isEnabled(),true);await capture('P05-S03-complete');});
 await check('A02/A05 record once; result 10/10 waiting Web, no stock mutation',async()=>{await act('send').dblclick();await page.locator('[data-panel="P05.S04"]').waitFor();assert.equal((await snap()).metrics.recordCalls,1);assert.equal((await snap()).metrics.inventoryDelta,0);assert.match(await page.locator('.p05-result-summary').textContent(),/Chờ xử lý trên Web/);assert.equal(await page.locator('.p05-app').getByText('Đã xuất',{exact:true}).count(),0);await matrix('P05-S04');assert.equal(await page.locator('.hn-nav').isVisible(),true);await act('document').click();assert.match(await page.locator('.p05-feedback').textContent(),/P12.*PX-0005/);});
 await check('fresh reentry from Home and picker; no auto camera or previous IDs substituted',async()=>{const id=(await snap()).document.documentId;await act('home').click();await page.locator('.hn-record[data-id="PX-0004"]').click();assert.match(await page.locator('#hn-destination').textContent(),/PX-0004/);assert.equal(await page.locator('.p05-app').count(),0);await page.locator('[data-return]').click();await page.locator('[data-tab="lookup"]').click();await page.locator('[data-p03-operation="outbound"]').click();assert.equal((await snap()).step,1);assert.notEqual((await snap()).document.documentId,id);assert.equal((await snap()).accepted.length,0);assert.equal(await page.evaluate(()=>window.__cameraRequests),0);});
 await check('UNKNOWN navigation preserves request; reconcile does not record twice',async()=>{await full();await page.selectOption('[data-p05-outcome]','timeout-recorded');await act('send').click();await page.locator('.p05-unknown').waitFor();const before=(await snap()).request;assert.equal(await act('send').isDisabled(),true);assert.equal(await act('back').isDisabled(),true);await capture('P05-unknown');await page.goBack();await page.locator('.hn-task[data-route="outbound"]').click();assert.deepEqual((await snap()).request,before);await act('check').click();await page.locator('[data-panel="P05.S04"]').waitFor();assert.equal((await snap()).metrics.records,2);assert.equal((await snap()).metrics.recordCalls,2);await act('home').click();await page.locator('.hn-task[data-route="outbound"]').click();assert.equal((await snap()).step,1);});
 await check('draft survives Home Back and long note/manual reduced viewport CTA stays accessible',async()=>{await page.locator('[data-p05-note]').fill('Ghi chú dài '.repeat(18));await seven();const before=await snap();await page.goBack();await page.locator('.hn-task[data-route="outbound"]').click();assert.deepEqual((await snap()).document,before.document);assert.deepEqual((await snap()).accepted,before.accepted);await page.setViewportSize({width:340,height:420});await act('manual').click();await page.locator('#p05-code').fill('HN12352');await capture('P05-keyboard-340x420');await act('close-manual').click();await act('next').click();await capture('P05-long-note-340x420');await page.setViewportSize({width:494,height:1000});});
 await check('warehouse stop uses P03, no write/no logout; restoring returns correct shell',async()=>{await page.locator('.p03-tools summary').click();await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await act('back').click();await act('manual').click();await page.locator('#p05-code').fill('HN12352');await page.locator('#p05-code').press('Enter');await page.locator('[data-panel="P03.S03"]').waitFor();await page.locator('[data-p03-action="home"]').click();assert.equal(await page.locator('#hn-home').isVisible(),true);await page.selectOption('[data-p03-fixture="warehouse"]','active');});
 await check('P04 regression: 12/11+1 and waiting-Web unaffected',async()=>{await page.locator('.hn-task[data-route="inbound"]').click();await page.locator('.p04-tools summary').click();await page.locator('[data-p04="next"]').click();await page.locator('[data-p04="batch"]').click();await page.locator('[data-p04="next"]').click();await page.locator('[data-p04="send"]').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.equal(JSON.parse(await page.locator('[data-p04-snapshot]').textContent()).accepted.length,11);assert.equal(await page.locator('.p04-success h2').textContent(),'Đã gửi phiếu nhập');await page.locator('[data-p04="home"]').click();});
 await check('logout/back hides outbound and inbound session data',async()=>{await page.locator('.hn-tools > details > summary').first().click();await page.locator('#hn-logout').click();await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p05-app,.p04-app').count(),0);});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));
 }catch(e){await page.screenshot({path:path.join(out,'browser-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
