const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out='handoff/readable-content-2026-09-28/evidence/audit';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],errors=[],metrics=[];page.on('pageerror',e=>errors.push(e.message));await mockGeography(page);
const long='Đối chiếu thông tin và giữ nguyên nội dung nguồn.\n'.repeat(55)+'📦 <img src=x onerror=window.hnInjected=true>';let seq=0;
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}async function shot(name){const loc=page.locator('#home-app:not([hidden]) .hn-screen,#app:not([hidden]) .screen').first();await loc.screenshot({path:path.join(out,name+'.png')});}
async function route(hash,selector){await page.evaluate(h=>location.hash=h,hash);await page.locator(selector).first().waitFor();await page.waitForTimeout(50);}
async function close(){await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnAuthReadable&&!history.state?.hnAppReadable);}
async function reader(selector,name,{matrix=false}={}){const node=page.locator(selector).first();await node.waitFor();const original=await node.textContent();await node.evaluate((e,value)=>e.textContent=value,long);await page.waitForFunction(sel=>{const e=document.querySelector(sel),b=e?.dataset.hnReadOutside==='true'?e.closest('[data-hn-readable-group]')?.querySelector('.hn-read-more'):e?.nextElementSibling;return b?.classList.contains('hn-read-more')&&!b.hidden;},selector);
const id='read-'+(++seq);await node.evaluate((e,id)=>{const b=e.dataset.hnReadOutside==='true'?e.closest('[data-hn-readable-group]').querySelector('.hn-read-more'):e.nextElementSibling;b.dataset.hnQa=id;},id);const button=page.locator('[data-hn-qa='+id+']');
const sizes=matrix?[[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]:[[494,950]];
for(const [width,height]of sizes){await page.setViewportSize({width,height});await button.click();const dialog=page.locator('.hn-readable-dialog');await dialog.waitFor();assert.equal(await dialog.locator('.app-modal-body p').textContent(),long);assert.equal(await dialog.locator('img').count(),0);assert.equal(await page.locator('.app-modal-host').count(),1);assert.equal(await dialog.locator('button').count(),1);assert.equal(await dialog.locator('button').textContent(),'Đóng');const bounds=await dialog.evaluate(d=>{const shell=d.closest('.hn-screen,.screen').getBoundingClientRect(),r=d.getBoundingClientRect(),s=d.querySelector('.app-modal-body'),f=d.querySelector('footer').getBoundingClientRect();return {within:r.left>=shell.left&&r.right<=shell.right+1&&r.top>=shell.top&&r.bottom<=shell.bottom+1,footer:f.bottom<=shell.bottom+1,body:[s.clientWidth,s.scrollWidth,s.clientHeight,s.scrollHeight]};});assert.ok(bounds.within&&bounds.footer,JSON.stringify(bounds));assert.equal(bounds.body[0],bounds.body[1]);metrics.push({name,width,height,...bounds});await shot(name+'-'+width+'x'+height);await page.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog.count(),1);await close();assert.ok(await button.evaluate(e=>e===document.activeElement));assert.equal(await node.textContent(),long);}
await page.setViewportSize({width:494,height:950});await node.evaluate((e,value)=>e.textContent=value,original);return original;}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');
await check('P01.S01 secret input is excluded, even with an accidental reader marker',async()=>{await page.fill('#password','SENSITIVE-LOCAL-ONLY');await page.locator('#password').evaluate(e=>e.setAttribute('data-hn-readable','Never read password'));await page.waitForTimeout(60);assert.equal(await page.locator('#password').getAttribute('class'),null);assert.equal(await page.locator('#login-form .hn-read-more').count(),0);assert.doesNotMatch(await page.locator('#app').textContent(),/SENSITIVE-LOCAL-ONLY/);assert.equal(await page.inputValue('#password'),'SENSITIVE-LOCAL-ONLY');await page.locator('#password').evaluate(e=>e.removeAttribute('data-hn-readable'));await page.locator('#username-error').evaluate(e=>{e.setAttribute('role','alert');e.setAttribute('data-hn-readable','Validation must stay complete');e.textContent='Thông tin bắt buộc. '.repeat(100);});await page.waitForTimeout(40);assert.equal(await page.locator('#username-error').evaluate(e=>e.classList.contains('hn-readable-excerpt')),false);await page.locator('#username-error').evaluate(e=>{e.removeAttribute('data-hn-readable');e.textContent='';});await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.locator('.confirmation').waitFor();});
await check('P01.S02 complete identity accessible without changing session or input',async()=>{await reader('#app .identity [data-hn-readable="Họ tên"]','P01-identity');assert.equal(await page.locator('#start').isEnabled(),true);await page.click('#start');await page.waitForSelector('#hn-home');});
await check('P02 keeps the existing full-name dialog; no duplicate viewer',async()=>{await page.locator('.hn-name').click();await page.locator('.hn-name-dialog[open]').waitFor();assert.equal(await page.locator('.app-modal-host').count(),1);assert.equal(await page.locator('.hn-readable-dialog').count(),0);await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnNameDialog);await shot('P02-baseline');});
await check('P03 consequences stay complete in the existing modal and remain scrollable',async()=>{await page.click('[data-tab=lookup]');await page.locator('.p03-dialog').waitFor();await page.locator('#p03-description').evaluate((e,t)=>e.textContent=t,long);const m=await page.locator('.p03-dialog').evaluate(d=>({full:d.querySelector('#p03-description').textContent,more:d.querySelectorAll('.hn-read-more').length,width:d.clientWidth,scroll:d.scrollWidth}));assert.equal(m.full,long);assert.equal(m.more,0);assert.equal(m.width,m.scroll);await page.keyboard.press('Escape');await page.locator('.p03-dialog').waitFor({state:'detached'});});
await check('P04 input limit200 retained; saved-note reader does not change draft/codes/request',async()=>{await page.click('.hn-task[data-route=inbound]');await page.locator('[data-p04-note]').fill('Kiểm tra theo phiếu. '.repeat(9));assert.equal(await page.locator('[data-p04-note]').getAttribute('maxlength'),'200');await page.click('[data-p04=next]');await page.locator('.p04-tools').evaluate(e=>e.open=true);await page.click('[data-p04=batch]');await page.click('[data-p04=next]');const before=await page.locator('[data-p04-snapshot]').textContent();await reader('.p04-saved-note [data-hn-readable]','P04-note',{matrix:true});assert.equal(await page.locator('[data-p04-snapshot]').textContent(),before);});
await check('P05 input and saved-note readable while exact outbound draft retained',async()=>{await route('#p02/outbound','.p05-app');await address(page);await page.locator('[data-p05-note]').fill('Đối chiếu serial trước khi giao hàng.');await page.click('[data-p05=next]');await page.click('[data-p05=manual]');await page.fill('#p05-code','HN12345');await page.press('#p05-code','Enter');await page.click('[data-p05=next]');const before=await page.locator('[data-p05-snapshot]').textContent();await reader('.p05-saved-note [data-hn-readable]','P05-note');assert.equal(await page.locator('[data-p05-snapshot]').textContent(),before);});
await check('P06 description and transaction text have full readers without nested buttons',async()=>{await route('#p02/lookup','.p06-app');await page.click('[data-p06-item="fixture-item-HN12345"]');await reader('.p06-section [data-hn-readable="Mô tả"]','P06-description');await page.click('[data-p06=history]');await reader('.p06-event [data-hn-readable="Mô tả giao dịch"]','P06-transaction');assert.equal(await page.locator('.p06-event button').count(),0);});
await check('P07 verification product readable; existing NFC detail remains complete, no new write',async()=>{await route('#p02/nfc','.p07-app');await page.click('[data-p07=begin]');await page.click('[data-p07-demo-read]');await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).busy);await page.click('[data-p07=next]');const before=await page.locator('[data-p07-snapshot]').textContent();await reader('.p07-product [data-hn-readable]','P07-product');assert.equal(await page.locator('[data-p07-snapshot]').textContent(),before);});
await check('P08 history note uses the shared reader and Back preserves route/scroll',async()=>{await route('#p02/history-list?panel=2&record=LS-0001','.p08-detail-note');await reader('.p08-detail-note [data-hn-readable]','P08-note');const hash=await page.evaluate(()=>location.hash);const n=page.locator('.p08-detail-note [data-hn-readable]');await n.evaluate((e,t)=>e.textContent=t,long);await page.waitForTimeout(50);await n.locator('xpath=following-sibling::button[1]').click();await page.goBack();await page.waitForFunction(()=>!history.state?.hnAppReadable);assert.equal(await page.evaluate(()=>location.hash),hash);});
await check('Shared preview handles empty/short/250/2000+/Unicode/line breaks and derives button from real overflow',async()=>{const node=page.locator('.p08-detail-note [data-hn-readable]'),original=await node.textContent();for(const text of ['', 'Nội dung ngắn.', 'Đ'.repeat(250), 'X'.repeat(2200), 'Dòng 1\n\nDòng 2\n'.repeat(120), '📦 Đối chiếu tiếng Việt '.repeat(100)]){await node.evaluate((e,t)=>e.textContent=t,text);await page.waitForTimeout(40);const shape=await node.evaluate(e=>({h:e.clientHeight,line:parseFloat(getComputedStyle(e).lineHeight),w:e.clientWidth,sw:e.scrollWidth,hidden:e.nextElementSibling.hidden}));assert.equal(shape.w,shape.sw);assert.ok(shape.h<=shape.line*2+1);if(text.length<30)assert.equal(shape.hidden,true);else{assert.equal(shape.hidden,false);await node.locator('xpath=following-sibling::button[1]').click();assert.equal(await page.locator('.hn-readable-dialog .app-modal-body p').textContent(),text);await close();}}await node.evaluate((e,t)=>e.textContent=t,original);});
await check('P09 note/diagnosis/result/accessories and timeline share bounded full readers',async()=>{await route('#p02/warranty?panel=3&case=BH-001','.p09-case-kv');for(const label of ['Ghi chú','Chẩn đoán','Kết quả sửa chữa','Phụ kiện'])await reader('.p09-case-kv [data-hn-readable="'+label+'"]','P09-'+({'Ghi chú':'note','Chẩn đoán':'diagnosis','Kết quả sửa chữa':'result','Phụ kiện':'accessories'}[label]));await page.click('[data-p09-tab=events]');await reader('.p09-event-description[data-hn-readable]','P09-event');});
await check('P10 long identity retains profile routing and full text access',async()=>{await route('#p02/profile','.p10-app');await reader('.p10-person [data-hn-readable="Họ tên"]','P10-identity');await page.click('[data-p10=edit]');const profileName=await page.inputValue('#p10-name');await page.fill('#p10-name','Bản nhập chưa lưu');assert.equal(await page.inputValue('#p10-name'),'Bản nhập chưa lưu');assert.equal(await page.locator('#p10-name').getAttribute('data-hn-readable'),null);await page.fill('#p10-name',profileName);await page.click('[data-p10=back]');});
await check('P11 session metadata readable and password fields stay untouched',async()=>{await route('#p02/security?panel=4','.p11-device');await reader('.p11-device-name [data-hn-readable="Thiết bị đăng nhập"]','P11-device');await reader('.p11-device-meta [data-hn-readable="Vị trí đăng nhập"]','P11-location');await route('#p02/security?panel=1','#p11-next');await page.fill('#p11-next','DO-NOT-READ-THIS');await page.locator('#p11-next').evaluate(e=>e.setAttribute('data-hn-readable','Do not inspect'));await page.waitForTimeout(60);assert.equal(await page.locator('.p11-input .hn-read-more').count(),0);assert.equal(await page.inputValue('#p11-next'),'DO-NOT-READ-THIS');assert.doesNotMatch(await page.locator('.p11-app').textContent(),/DO-NOT-READ-THIS/);await page.locator('#p11-next').evaluate(e=>e.removeAttribute('data-hn-readable'));await page.fill('#p11-next','');});
await check('P12 keeps validated adapter and shared overflow primitive, full749-char source',async()=>{await route('#p02/documents?panel=2&doc=p12-stock-PN-0010','.p12-note-preview');await page.click('[data-p12=read-note]');assert.equal((await page.locator('.p12-full-text').textContent()).length,749);assert.equal(await page.locator('.hn-readable-dialog').count(),0);await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnDocumentsDialog);});
await check('Reader never writes storage; repeated route/observer lifecycle produces no stale overlay',async()=>{const before=await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage]));for(let i=0;i<3;i++){await route('#p02/history-list?panel=2&record=LS-0001','.p08-detail-note');await reader('.p08-detail-note [data-hn-readable]','lifecycle-'+i);await route('#p02/documents','.p12-app');}assert.equal(await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage])),before);assert.equal(await page.locator('.app-modal-host').count(),0);await page.locator('.hn-tools>details').first().evaluate(e=>e.open=true);await page.click('#hn-logout');await page.waitForSelector('#username');await page.goBack();assert.equal(await page.locator('.hn-readable-dialog').count(),0);assert.equal(await page.locator('#home-app').isVisible(),false);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
