const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const stage=process.env.P14_AUDIT_STAGE||'before',out='handoff/P14/evidence/revision-06/'+stage;fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];async function check(name,fn){const p=await browser.newPage({viewport:{width:494,height:950},timezoneId:'Asia/Ho_Chi_Minh'}),errors=[];p.setDefaultTimeout(30000);p.on('pageerror',e=>errors.push(e.message));await p.clock.setFixedTime(new Date('2026-09-29T02:21:00+07:00'));try{await p.goto('http://localhost:8766/flows/auth-session/');await fn(p);assert.deepEqual(errors,[]);results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:String(e),url:p.url(),errors});}await p.screenshot({path:path.join(out,name+'.png')});await p.close();console.log(results.at(-1).status+' '+name);}
const login=async p=>{await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home').waitFor({state:'visible'});};const shift=async p=>{await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await p.locator('[data-panel="P14.S03"]').waitFor();};const modal=p=>p.locator('.app-modal-host dialog');
await check('01-back-history',async p=>{await login(p);await shift(p);await p.click('[data-p14=back]');await p.locator('[data-panel="P10.S01"]').waitFor();await p.goBack();assert.ok(p.url().endsWith('#home'),'Back must not resurrect the screen just exited');});
await check('02-recovery-error-focus',async p=>{await p.click('#forgot');await p.locator('.p14-tools details').evaluate(e=>e.open=true);await p.selectOption('[data-p14-scenario]','error');await p.fill('#p14-username','minhanh');await p.keyboard.press('Enter');await modal(p).waitFor();await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.evaluate(()=>document.activeElement?.id),'p14-username');});
await check('03-unique-receipt',async p=>{const ids=[];for(let i=0;i<2;i++){await p.click('#forgot');await p.fill('#p14-username','minhanh');await p.locator('.p14-app button[type=submit]').click();await p.locator('[data-panel="P14.S02"]').waitFor();ids.push(await p.locator('[data-hn-readable="Mã yêu cầu"]').textContent());await p.click('[data-p14=login]');await p.locator('#username').waitFor();}assert.notEqual(ids[0],ids[1]);assert.match(ids[0],/^RQ-20260929-/);});
await check('04-details-keyboard',async p=>{await login(p);await shift(p);await p.click('[data-p14=save]');await modal(p).getByRole('button',{name:'Lưu nháp',exact:true}).click();await modal(p).getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));await p.click('[data-p14=end]');await modal(p).getByRole('button',{name:'Kết thúc ca',exact:true}).click();await p.locator('[data-panel="P14.S04"]').waitFor();await p.locator('[data-p14=drafts]').first().click();await modal(p).waitFor();await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement?.tagName),'SUMMARY');await p.keyboard.press('Enter');assert.equal(await p.locator('.p14-dialog-record details[open]').count(),1);});
await check('05-reauth-save',async p=>{await login(p);await shift(p);await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.click('[data-system-demo=expired]');await p.click('[data-p15=login]');await p.locator('#username').waitFor();await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('[data-panel="P14.S03"]').waitFor();await p.click('[data-p14=save]');await modal(p).getByRole('button',{name:'Lưu nháp',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.app-modal-heading')?.textContent==='Đã lưu nháp',null,{timeout:3000});});
fs.writeFileSync(path.join(out,'audit-results.json'),JSON.stringify({stage,results},null,2));await browser.close();if(stage==='after'&&results.some(r=>r.status==='FAIL'))process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
