const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.HOME_UX_EVIDENCE_DIR||'handoff/P02/evidence/revision-15-ux');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await mockGeography(page);
 const snap=()=>page.locator('[data-p04-snapshot]').evaluate(n=>JSON.parse(n.textContent));
 const home=async()=>{await page.evaluate(()=>{location.hash='#home';});await page.locator('#hn-home').waitFor({state:'visible'});};
 const shot=async name=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png')});};
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 try{
  await page.clock.setFixedTime(new Date('2026-09-28T01:15:20Z'));await page.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-record').first().waitFor();
  await check('Home stays clean without drafts and uses Vietnam relative time',async()=>{assert.equal(await page.locator('.hn-resume').isVisible(),false);assert.match(await page.locator('.hn-record time').first().textContent(),/Hôm qua/);await shot('after-home');});
  await page.click('.hn-task[data-route=inbound]');await page.locator('[data-p04=next]').first().click();await page.locator('[data-p04=manual]').first().click();
  await check('Consecutive manual input retains focus; duplicate/invalid never increase accepted codes',async()=>{
   await page.fill('#p04-code','HN12345');await page.locator('#p04-code').press('Enter');assert.equal(await page.locator('#p04-code').inputValue(),'');assert.equal(await page.locator('#p04-code').evaluate(n=>n===document.activeElement),true);assert.equal((await snap()).accepted.length,1);
   await page.fill('#p04-code','HN12345');await page.locator('#p04-code').press('Enter');assert.equal((await snap()).accepted.length,1);assert.equal(await page.locator('#p04-code').inputValue(),'HN12345');
   await page.fill('#p04-code','BAD-CODE');await page.locator('#p04-code').press('Enter');assert.equal((await snap()).accepted.length,1);await page.locator('[data-panel="P17.S01"]').waitFor();await page.locator('[data-p04=exception-manual]').click();
   await page.fill('#p04-code','HN12348');await page.locator('#p04-code').press('Enter');assert.equal((await snap()).accepted.length,2);assert.equal(await page.locator('#p04-code').evaluate(n=>n===document.activeElement),true);await shot('scan-ready');
  });
  const before=await snap();await home();
  await check('Resume shortcut opens the exact document/session/version/codes without a new run',async()=>{
   await page.locator('[data-resume-operation=inbound]').waitFor();await shot('home-draft');await page.locator('[data-resume-operation=inbound]').click();await page.locator('[data-panel="P04.S02"]').waitFor();const after=await snap();assert.deepEqual(after.document,before.document);assert.deepEqual(after.accepted,before.accepted);assert.deepEqual(after.request,before.request);await home();
  });
  await check('Home inner scroll and focus return from recent detail; footer stays visible',async()=>{
   await page.locator('.hn-record:last-child').scrollIntoViewIfNeeded();const top=await page.locator('.hn-main').evaluate(n=>n.scrollTop);assert.ok(top>0);const id=await page.locator('.hn-record:last-child').getAttribute('data-recent-document');await page.locator('.hn-record:last-child').click();await page.locator('[data-panel="P12.S02"]').waitFor();await page.locator('[data-p12=back]').click();await page.locator('#hn-home').waitFor({state:'visible'});assert.ok(Math.abs(await page.locator('.hn-main').evaluate(n=>n.scrollTop)-top)<2);assert.equal(await page.locator(`[data-recent-document="${id}"]`).evaluate(n=>n===document.activeElement),true);assert.equal(await page.locator('.hn-record').count(),3);
   await page.click('[data-tab=lookup]');await page.locator('.p03-dialog').waitFor();await page.keyboard.press('Escape');await page.locator('#hn-home').waitFor({state:'visible'});assert.ok(Math.abs(await page.locator('.hn-main').evaluate(n=>n.scrollTop)-top)<2);
  });
  await check('Unknown resume retains request and requires reconciliation, with no blind resend',async()=>{
   await page.locator('[data-resume-operation=inbound]').click();await page.locator('[data-p04=next]').first().click();await page.locator('.p04-tools summary').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await page.locator('[data-p04=send]').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p04-snapshot]').textContent).unknown);await page.locator('[data-panel="P17.S04"]').waitFor();const unknown=await snap();await home();assert.match(await page.locator('[data-resume-operation=inbound]').textContent(),/Cần đối chiếu/);await shot('home-unknown');await page.locator('[data-resume-operation=inbound]').click();await page.locator('[data-panel="P17.S04"]').waitFor();assert.deepEqual((await snap()).request,unknown.request);assert.equal((await snap()).unknown,true);
   await page.selectOption('[data-p04-outcome]','confirmed');await page.locator('[data-p04=check]').click();await page.locator('[data-panel="P04.S04"]').waitFor();await home();assert.equal(await page.locator('.hn-resume').isVisible(),false);
  });
  await check('No-result recovery works in Documents, Warranty, NFC and Lookup without mutating data',async()=>{
   for(const [route,input,emptyButton,rows]of [['documents','#p12-query','.hn-clear-filters','.p12-record'],['warranty','#p09-query','.hn-clear-filters','.p09-case'],['nfc','#p07-search','[data-p07=clear-filters]','.p07-tag'],['lookup','#p06-search','.p06-clear-empty','.p06-card']]){
    await page.evaluate(r=>{location.hash='#p02/'+r;},route);await page.locator(input).waitFor();await page.fill(input,'NO-MATCH-XYZ');const recovery=route==='documents'?page.getByRole('button',{name:'Xóa bộ lọc',exact:true}):page.locator(emptyButton);await recovery.waitFor();assert.equal(await page.locator(rows).count(),0);await shot('empty-'+route);await recovery.click();assert.equal(await page.locator(input).inputValue(),'');await page.locator(rows).first().waitFor();assert.ok(await page.locator(rows).count()>0);await home();
   }
  });
  await check('History empty results offer recovery and retain business scope',async()=>{
   await page.evaluate(()=>location.hash='#p02/history-list?panel=1');await page.locator('#p08-search').waitFor();await page.fill('#p08-search','NO-MATCH-XYZ');await page.locator('[data-p08=relax]').waitFor();await shot('empty-history');await page.locator('[data-p08=relax]').click();assert.equal(await page.locator('#p08-search').inputValue(),'');assert.ok(await page.locator('.p08-row').count()>0);await home();
  });
  await check('Unread notification empty state can return to All without inventing notifications',async()=>{
   await page.click('.hn-bell');await page.locator('.p13-app').waitFor();await page.locator('.p13-tools summary').click();await page.selectOption('#p13-dataset','count-0');await page.locator('.p13-filters [data-p13-filter=unread]').click();await page.locator('.hn-clear-filters').waitFor();await shot('empty-notifications');await page.locator('.hn-clear-filters').click();assert.equal(await page.locator('.p13-filters [data-p13-filter=all]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.p13-notification').count(),0);await home();
  });
  await check('Tile feedback preserves geometry and footer locked paint',async()=>{const tile=page.locator('.hn-task[data-route=inbound]'),before=await tile.boundingBox();await tile.hover();await page.waitForFunction(()=>getComputedStyle(document.querySelector('.hn-task[data-route=inbound]')).backgroundColor==='rgb(240, 247, 250)');assert.deepEqual(await tile.boundingBox(),before);assert.equal(await page.locator('.hn-nav').evaluate(n=>getComputedStyle(n).backgroundColor),'rgba(255, 255, 255, 0.98)');await shot('tile-hover');});
  await check('Outbound scanning and resume preserve exact data; two drafts stay separate on a small screen',async()=>{
   await page.click('.hn-task[data-route=outbound]');await address(page);await page.fill('[data-p05-field=planned]','2');await page.locator('[data-p05=next]').first().click();await page.locator('[data-p05=manual]').first().click();await page.fill('#p05-code','HN12345');await page.locator('#p05-code').press('Enter');assert.equal(await page.locator('#p05-code').inputValue(),'');assert.equal(await page.locator('#p05-code').evaluate(n=>n===document.activeElement),true);
   const outgoing=JSON.parse(await page.locator('[data-p05-snapshot]').textContent());await home();await page.locator('[data-resume-operation=outbound]').click();await page.locator('[data-panel="P05.S02"]').waitFor();const resumed=JSON.parse(await page.locator('[data-p05-snapshot]').textContent());assert.deepEqual(resumed.document,outgoing.document);assert.deepEqual(resumed.accepted,outgoing.accepted);await home();
   await page.click('.hn-task[data-route=inbound]');await page.locator('[data-panel="P04.S01"]').waitFor();await home();assert.equal(await page.locator('.hn-resume-row').count(),2);assert.equal(await page.locator('.hn-record').count(),3);await page.setViewportSize({width:360,height:800});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await shot('two-drafts-360');await page.locator('.hn-record:last-child').scrollIntoViewIfNeeded();const last=await page.locator('.hn-record:last-child').boundingBox(),nav=await page.locator('.hn-nav').boundingBox();assert.ok(last.y+last.height<=nav.y);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  });
  await check('Logout removes draft shortcuts and protected Back cannot restore them',async()=>{
   await page.getByText('Kịch bản kiểm tra P02',{exact:true}).click();await page.click('#hn-logout');await page.locator('#username').waitFor();assert.equal(await page.locator('.hn-resume').count(),0);await page.goBack();await page.locator('#username').waitFor();assert.equal(await page.locator('.hn-resume-row').count(),0);
  });
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,fixtureClock:'2026-09-28T01:15:20Z',realHardware:'NOT_RUN'},null,2));
 }catch(e){await shot('failure');fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,checks,errors},null,2));throw e;}finally{await browser.close();}
})();
