const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve('handoff/motion/M06/evidence'),base=process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766';fs.mkdirSync(out,{recursive:true});
const before=JSON.parse(fs.readFileSync(path.join(out,'before/geometry.json')));
const injected=`
export function createLookupFixtureAdapter(options){const a=baseLookupFixtureAdapter(options),search=a.search.bind(a),history=a.history.bind(a);window.qaReads={search:0,history:0};window.qaPending={};window.qaHistoryLimit=null;window.qaHistoryChanged=false;
a.search=(scope,opts)=>{window.qaReads.search++;const data=search(scope,opts);if(window.qaDelay&&opts.query)return new Promise(resolve=>window.qaPending[opts.query]=()=>resolve(data));return data;};
a.history=(...args)=>{window.qaReads.history++;const data=history(...args);if(window.qaHistoryChanged&&data.items[0])data.items[0]={...data.items[0],description:'Nguồn đã cập nhật mô tả',quantity:21};return window.qaHistoryLimit==null?data:{...data,items:data.items.slice(0,window.qaHistoryLimit)};};return a;}
`;
async function geometry(p){return p.locator('.p06-app').evaluate(el=>{const names=['.hn-screen','.p06-header','.p06-body','.p06-scroll','.hn-nav','.p06-hero','.p06-stock-strip'];return Object.fromEntries(names.map(s=>{const n=document.querySelector(s);if(!n)return[s,null];const r=n.getBoundingClientRect();return[s,[r.x,r.y,r.width,r.height]];}));});}
(async()=>{const browser=await chromium.launch(),all=[];try{for(const mode of ['auto','os-reduced','off']){
const context=await browser.newContext({viewport:{width:494,height:950},reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'}),p=await context.newPage(),row={mode,checks:[],errors:[],geometry:{}};all.push(row);
p.on('pageerror',e=>row.errors.push(e.message));await p.clock.setFixedTime(new Date('2026-09-30T01:15:20Z'));await context.tracing.start({screenshots:true,snapshots:true,sources:true});
await p.addInitScript(()=>{window.qaAnimations=[];window.qaHardware=0;window.qaMotionListeners=0;const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(type,listener,options){if(type==='visibilitychange'&&listener?.name==='visibility')qaMotionListeners++;return add.call(this,type,listener,options);};EventTarget.prototype.removeEventListener=function(type,listener,options){if(type==='visibilitychange'&&listener?.name==='visibility')qaMotionListeners--;return remove.call(this,type,listener,options);};const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){window.qaAnimations.push({node:this.id||this.className,primitive:this.dataset.motionPrimitive,duration:options.duration,frames});return animate.call(this,frames,options);};if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{window.qaHardware++;throw Error('Hardware not enabled');};});
await p.route('**/lookup/fixture-adapter.mjs*',async route=>{const response=await route.fetch(),body=(await response.text()).replace('export function createLookupFixtureAdapter','function baseLookupFixtureAdapter')+injected;await route.fulfill({response,body});});
const a=n=>p.locator(`[data-p06="${n}"]`).first(),snap=()=>p.locator('[data-p06-snapshot]').evaluate(e=>JSON.parse(e.textContent));
const settle=()=>p.waitForTimeout(250),clearLog=()=>p.evaluate(()=>{qaAnimations=[];});
const check=async(name,fn)=>{try{await fn();row.checks.push(name);console.log('PASS '+mode+' '+name);}catch(e){row.failure={name,error:e.stack};await p.screenshot({path:path.join(out,mode+'-failure.png'),fullPage:true});throw e;}};
const route=async n=>{await p.evaluate(n=>location.hash=`#p02/lookup${n===1?'':`?panel=${n}&item=fixture-item-HN12345`}`,n);await p.locator(`[data-panel="P06.S0${n}"]`).waitFor();};
await p.goto(base+'/flows/auth-session/');await p.locator('.preview-tools details summary').click();await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-scanner');await settle();
await check('four panels settle to pre-motion geometry and identical fixture content',async()=>{for(const n of [1,2,3,4]){await route(n);await settle();row.geometry[n]=await geometry(p);if(n===1)row.initialProfile=await p.locator('.p06-app').evaluate(el=>({nodes:el.querySelectorAll('*').length,rows:el.querySelectorAll('.p06-card').length,scrollController:'native'}));assert.deepEqual(row.geometry[n],before[n]);await p.locator('.p06-app img').evaluateAll(es=>Promise.all(es.map(e=>e.decode())));await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-P06.S0'+n+'.png')});}assert.equal(await p.locator('.p06-event').count(),7);});
await route(1);await settle();
await check('SearchFeedback targets results only; input stays connected with caret/IME',async()=>{await p.evaluate(()=>{window.keptInput=document.querySelector('#p06-search');window.disconnected=false;window.inputObserver=new MutationObserver(()=>{if(!keptInput.isConnected)disconnected=true;});inputObserver.observe(document.querySelector('#hn-destination'),{subtree:true,childList:true});});await p.locator('#p06-search').focus();await clearLog();await p.fill('#p06-search','HN12346');assert.equal(await p.locator('.p06-card').count(),1);const log=await p.evaluate(()=>qaAnimations.filter(x=>x.primitive==='SearchFeedback'));assert.equal(log.length,mode==='off'?0:1);if(log.length)assert.equal(log[0].duration,mode==='auto'?140:80);
row.feedbackFrames=await p.locator('.p06-list').evaluate(async node=>{const values=[];for(let i=0;i<14;i++){await new Promise(requestAnimationFrame);values.push(Number(getComputedStyle(node).opacity));}return values;});
await p.locator('#p06-search').evaluate(e=>{e.setSelectionRange(2,4);e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='HN12345';e.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));});assert.equal((await snap()).query,'HN12346');await p.locator('#p06-search').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));assert.equal((await snap()).query,'HN12345');assert.equal(await p.evaluate(()=>keptInput===document.querySelector('#p06-search')&&!disconnected),true);});
await check('latest B response wins even when cancelled A resolves after the fade',async()=>{await p.evaluate(()=>{qaDelay=true;});await p.fill('#p06-search','HN12346');await p.fill('#p06-search','HN12347');await p.evaluate(()=>qaPending.HN12347());await p.locator('.p06-card[data-p06-item="fixture-item-HN12347"]').waitFor();await settle();const bBefore=await p.locator('.p06-list').innerText();await clearLog();await p.evaluate(()=>qaPending.HN12346());await settle();assert.equal(await p.locator('.p06-list').innerText(),bBefore);assert.equal(await p.evaluate(()=>qaAnimations.filter(x=>x.primitive==='SearchFeedback').length),0);await p.evaluate(()=>{qaDelay=false;});});
await check('tab feedback never translates layout or replaces the search input',async()=>{await a('clear').click();await clearLog();await p.click('[data-p06-category="components"]');assert.equal((await snap()).category,'components');const log=await p.evaluate(()=>qaAnimations.filter(x=>x.primitive==='TabFeedback'));assert.equal(log.length,mode==='off'?0:1);if(log.length){assert.equal(log[0].duration,mode==='auto'?140:80);assert.ok(log[0].frames.every(f=>!f.transform));}assert.equal(await p.evaluate(()=>keptInput===document.querySelector('#p06-search')),true);await p.click('[data-p06-category="products"]');});
await check('list-detail-stock-Back keeps query anchor/focus; shell owns one route fade',async()=>{await p.fill('#p06-search','XP-420B');const style=await p.addStyleTag({content:'.p06-card{min-height:250px!important}'});await p.locator('.p06-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const button=p.locator('.p06-list [data-p06-item="fixture-item-HN12348"]');await button.scrollIntoViewIfNeeded();const top=await p.locator('.p06-scroll').evaluate(e=>e.scrollTop);await clearLog();await button.click();const routeLog=await p.evaluate(()=>qaAnimations.filter(x=>x.node==='hn-destination'));assert.equal(routeLog.length,mode==='auto'?1:0);if(routeLog.length)assert.equal(routeLog[0].duration,180);await a('back').click();await p.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await p.locator('#p06-search').inputValue(),'XP-420B');assert.ok(Math.abs(await p.locator('.p06-scroll').evaluate(e=>e.scrollTop)-top)<2);await style.evaluate(e=>e.remove());});
await check('stock never counts through intermediate values',async()=>{await route(2);await settle();await clearLog();await a('stock').click();assert.deepEqual(await p.locator('.p06-stock-strip strong').allTextContents(),['12','10','1','1']);await settle();assert.deepEqual(await p.locator('.p06-stock-strip strong').allTextContents(),['12','10','1','1']);assert.equal(await p.evaluate(()=>qaAnimations.some(x=>/stock-strip|p06-location/.test(x.node))),false);});
await check('history append keeps existing DOM and scroll; error changes footer only',async()=>{await p.evaluate(()=>{qaHistoryLimit=3;});await route(4);await settle();await p.locator('.p06-tools summary').click();await p.selectOption('[data-p06-scenario]','demo');assert.equal(await p.locator('.p06-event').count(),3);const style=await p.addStyleTag({content:'.p06-event{min-height:240px!important}'});await p.locator('.p06-scroll').evaluate(e=>e.scrollTop=160);await p.evaluate(()=>{window.keptRows=[...document.querySelectorAll('[data-event-id]')];window.historyTop=document.querySelector('.p06-scroll').scrollTop;qaAnimations=[];qaHistoryLimit=null;});await p.selectOption('[data-p06-scenario]','demo');assert.equal(await p.locator('.p06-event').count(),7);assert.equal(await p.evaluate(()=>keptRows.every(n=>n.isConnected&&document.querySelector(`[data-event-id="${n.dataset.eventId}"]`)===n)),true);assert.ok(Math.abs(await p.locator('.p06-scroll').evaluate(e=>e.scrollTop)-await p.evaluate(()=>historyTop))<2);await p.selectOption('[data-p06-scenario]','read-error');assert.equal(await p.locator('.p06-history-feedback .p06-read-error').count(),1);assert.equal(await p.evaluate(()=>keptRows.every(n=>n.isConnected)),true);assert.equal(await p.locator('.p06-event').count(),7);assert.equal(await p.evaluate(()=>qaAnimations.filter(x=>x.primitive||/event/.test(x.node)).length),0);await a('retry-read').click();await p.evaluate(()=>{qaHistoryChanged=true;});await p.selectOption('[data-p06-scenario]','demo');assert.match(await p.locator('.p06-event').first().innerText(),/Nguồn đã cập nhật mô tả/);assert.equal(await p.locator('.p06-event-result b').first().innerText(),'+ 21');assert.equal(await p.evaluate(()=>keptRows[0].isConnected),true);await p.evaluate(()=>{qaHistoryChanged=false;});await p.selectOption('[data-p06-scenario]','demo');await style.evaluate(e=>e.remove());});
await check('rapid navigation, mode/OS changes and hidden state cancel local animations',async()=>{await route(1);await p.fill('#p06-search','HN');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),mode==='off'?'off':'reduced');await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.locator('.hn-tools > details').first().locator('summary').click();await p.selectOption('#home-motion-mode','off');assert.equal(await p.locator('.p06-list').evaluate(e=>e.getAnimations().length),0);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.fill('#p06-search','HN12346');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p06-list').evaluate(e=>e.getAnimations().length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.evaluate(()=>{document.querySelector('[data-p06-item="fixture-item-HN12346"]').click();document.querySelector('[data-p06=stock]').click();document.querySelector('[data-p06=back]').click();});await p.locator('[data-panel="P06.S02"]').waitFor();});
await check('invalid ID does not auto-open a product; print remains blocked in every mode',async()=>{await p.evaluate(()=>location.hash='#p02/lookup?panel=2&item=missing-id');await p.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await p.locator('.p06-hero').count(),0);await route(2);assert.equal(await a('print').isDisabled(),true);await p.evaluate(()=>{window.qaPrints=0;window.print=()=>qaPrints++;const button=document.querySelector('[data-p06=print]');button.disabled=false;button.click();button.disabled=true;});await p.locator('.hn-action-dialog[open]').waitFor();assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Không có quyền in/);await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnP06Feedback);assert.equal(await p.evaluate(()=>qaPrints),0);});
await check('in-flight search leaving route cannot repaint Home or issue camera calls',async()=>{await route(1);await p.evaluate(()=>{qaDelay=true;});await p.fill('#p06-search','HN12348');await p.click('[data-tab=home]');await p.evaluate(()=>qaPending.HN12348());await settle();assert.equal(await p.locator('.p06-app').count(),0);assert.equal(await p.locator('#hn-destination').getAttribute('data-hn-motion-mode'),null);assert.equal(await p.evaluate(()=>qaHardware),0);await p.click('.hn-scanner');await p.evaluate(()=>{qaDelay=false;});});
await check('repeated Home/lookup cycles do not accumulate motion listeners',async()=>{await p.evaluate(()=>{qaDelay=false;});await p.click('[data-tab=home]');const baseListeners=await p.evaluate(()=>qaMotionListeners);for(let i=0;i<3;i++){await p.click('.hn-scanner');assert.equal(await p.evaluate(()=>qaMotionListeners),baseListeners+1);await p.click('[data-tab=home]');assert.equal(await p.evaluate(()=>qaMotionListeners),baseListeners);}await p.click('.hn-scanner');});
row.listProfile=await p.locator('.p06-app').evaluate(el=>({nodes:el.querySelectorAll('*').length,rows:el.querySelectorAll('.p06-card').length,scrollController:'native'}));
row.domain={stock:[12,10,1,1],history:7,hardware:await p.evaluate(()=>qaHardware),reads:await p.evaluate(()=>qaReads)};
await check('logout cancels motion and removes protected content immediately',async()=>{await p.fill('#p06-search','HN');await p.click('#hn-logout');await p.locator('#login-form').waitFor();await p.evaluate(()=>qaPending.HN12348?.());assert.equal(await p.locator('.p06-app').count(),0);await p.goBack();assert.equal(await p.locator('.p06-app').count(),0);await p.evaluate(()=>inputObserver.disconnect());});
assert.deepEqual(row.errors,[]);await context.tracing.stop({path:path.join(out,mode+'-trace.zip')});await context.close();
}assert.deepEqual(all[1].domain,all[0].domain);assert.deepEqual(all[2].domain,all[0].domain);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(all,null,2));console.log('M06 modes equivalent');}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify(all,null,2));throw e;}finally{await browser.close();}})();
