const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.P13_DETAIL_EVIDENCE_DIR||'handoff/P13/evidence/revision-05';
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const nav=()=>p.locator('.hn-nav'),scroll=()=>p.locator('.p13-scroll'),dialog=()=>p.locator('.app-modal-host dialog');
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function route(query){await p.evaluate(q=>location.hash='#p02/notifications?'+q,query);await p.waitForFunction(q=>location.hash==='#p02/notifications?'+q&&!!document.querySelector('.p13-app'),query);await p.waitForTimeout(240);await p.evaluate(()=>scrollTo(0,0));}
const paint=()=>nav().evaluate(n=>{const s=getComputedStyle(n),c=getComputedStyle(n.querySelector('.hn-scan-circle'));return [s.backgroundColor,s.borderRadius,s.minHeight,s.padding,c.width,c.height,c.backgroundColor,c.borderTopWidth];});
try{await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');const locked=await paint();await p.click('.hn-bell');await p.locator('[data-p13-loaded=true]').waitFor();
await check('Warehouse/document/NFC/missing/S04 details retain one locked nav at7 viewports; CTA clears scan circle',async()=>{for(const [name,query]of [['warehouse','panel=2&event=p13-event-warehouse'],['document','panel=2&event=p13-event-inbound'],['nfc','panel=2&event=p13-event-nfc'],['missing','panel=2&event=missing'],['waiting','panel=4&doc=fixture-inbound-0005']]){await route(query);for(const [width,height]of [[494,950],[465,875],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(25);assert.equal(await nav().count(),1);assert.ok(await nav().isVisible());assert.deepEqual(await paint(),locked);assert.equal(await nav().locator('[data-tab]').count(),5);const m=await p.evaluate(()=>{const rect=e=>e.getBoundingClientRect(),s=document.querySelector('.hn-screen'),n=rect(document.querySelector('.hn-nav')),c=rect(document.querySelector('.hn-scan-circle')),v=document.querySelector('.p13-scroll'),buttons=[...document.querySelectorAll('.p13-actions button')];return {viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],nav:[n.top,n.bottom],scanTop:c.top,width:v.clientWidth,scrollWidth:v.scrollWidth,buttons:buttons.map(b=>({bottom:rect(b).bottom,top:rect(b).top})),appBottom:rect(s).bottom};});assert.deepEqual(m.shell,[494,950]);assert.equal(m.width,m.scrollWidth);assert.ok(m.nav[1]<=m.appBottom+1);for(const button of m.buttons)assert.ok(button.bottom<m.scanTop,'CTA intersects scan-circle');metrics.push({name,...m});await shot(`${name}-${width}x${height}`);}}await p.setViewportSize({width:494,height:950});});
await check('Detail scan entry and Escape/browser Back restore exact panel, ID, scroll and nav',async()=>{await route('panel=4&doc=fixture-inbound-0005');await scroll().evaluate(e=>e.scrollTop=200);const top=await scroll().evaluate(e=>e.scrollTop),hash=await p.evaluate(()=>location.hash);for(const exit of ['Escape','Back']){await p.click('[data-tab=lookup]');await p.locator('.p03-dialog').waitFor();assert.deepEqual(await paint(),locked);if(exit==='Escape')await p.keyboard.press('Escape');else await p.goBack();await p.locator('.p13-app').waitFor({state:'visible'});assert.equal(await p.evaluate(()=>location.hash),hash);assert.equal(await scroll().evaluate(e=>e.scrollTop),top);assert.ok(await nav().isVisible());assert.deepEqual(await paint(),locked);}});
await check('Detail menu Home/Documents/Profile/History opens destination and Back restores detail',async()=>{for(const tab of ['home','documents','profile','history']){await route('panel=2&event=p13-event-warehouse');await p.click('[data-tab='+tab+']');await p.waitForFunction(()=>!document.querySelector('.p13-app'));if(tab==='documents')await p.locator('.p12-app').waitFor();if(tab==='profile')await p.locator('.p10-app').waitFor();if(tab==='history')await p.locator('#hn-destination iframe').waitFor();await p.goBack();await p.locator('[data-panel="P13.S02"]').waitFor();assert.ok((await p.locator('.p13-summary').textContent()).includes('Thông báo từ Kho Hoa Nam'));assert.ok(await nav().isVisible());}});
await check('Long detail reader keeps navigation inert, Back closes reader first and returns focus',async()=>{await route('panel=2&event=p13-event-warehouse');const text='Nội dung bàn giao 🌸\n\n'+('Nội_dung_dài_cần_đọc_đầy_đủ_'.repeat(100));await p.locator('.p13-narrative [data-hn-readable]').evaluate((e,t)=>e.textContent=t,text);const reader=p.locator('.p13-app .hn-read-more:visible');await reader.waitFor();await reader.click();await dialog().waitFor();assert.equal(await dialog().locator('.app-modal-body').textContent(),text);assert.ok(await nav().evaluate(e=>e.inert));await shot('detail-reader-nav-inert');await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.locator('[data-panel="P13.S02"]').count(),1);assert.ok(await nav().isVisible());assert.equal(await nav().evaluate(e=>e.inert),false);assert.ok(await reader.evaluate(e=>e===document.activeElement));});
await check('20 loaded rows and All-tab scroll survive opening detail and Back',async()=>{await route('panel=1');await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset','extended');await p.locator('[data-p13-loaded=true]').waitFor();await p.click('[data-p13-filter=all]');await p.locator('[data-p13-loaded=true]').waitFor();await p.click('[data-p13=more]');await p.waitForFunction(()=>document.querySelectorAll('.p13-notification').length===20);await scroll().evaluate(e=>e.scrollTop=750);const top=await scroll().evaluate(e=>e.scrollTop);await p.locator('[data-p13-event]').nth(6).dispatchEvent('click');await p.locator('[data-panel="P13.S02"]').waitFor();assert.ok(await nav().isVisible());await p.click('[data-p13=back]');await p.locator('[data-panel="P13.S01"]').waitFor();assert.equal(await p.locator('.p13-notification').count(),20);assert.equal(await p.locator('[data-p13-filter=all]').getAttribute('aria-pressed'),'true');assert.equal(await scroll().evaluate(e=>e.scrollTop),top);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'detail-nav-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'detail-nav-failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('detail-nav-failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
