const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P20/evidence/revision-02/ux';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[],layouts=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);
const longCode='DEMO-< & >\n🧰'+('Z'.repeat(2100));
await p.route('**/warranty-components/history-fixture.mjs',async route=>{const res=await route.fetch();await route.fulfill({response:res,body:(await res.text()).replace("code:'DEMO-CODE-'+i","code:i===0?"+JSON.stringify(longCode)+":'DEMO-CODE-'+i")});});
const a=n=>p.locator(`[data-p20="${n}"]`),snap=async()=>JSON.parse(await p.locator('[data-p20-snapshot]').textContent()),issue=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent()),pause=()=>p.waitForTimeout(200);
async function shot(n){await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});}
async function route(q){await p.evaluate(q=>location.hash='#p02/component-history?'+q,q);await p.waitForSelector('.p20-app');await pause();}
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function geometry(label){const g=await p.locator('.hn-screen').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.querySelector('.p20-scroll'),f=e.querySelector('.p20-footer'),dialog=e.querySelector('.p20-codes-dialog[open]'),fr=(dialog?.querySelector('.app-modal-footer')||f).getBoundingClientRect();return {width:e.offsetWidth,height:e.offsetHeight,overflow:s.scrollWidth>s.clientWidth+1,footerFits:fr.top>=r.top&&fr.bottom<=r.bottom+1,dialog:!!dialog};});assert.equal(g.overflow,false);assert.equal(g.footerFits,true);layouts.push({label,viewport:p.viewportSize(),...g});}
try{await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p20-tools').evaluate(e=>e.open=true);await p.locator('.p19-tools').evaluate(e=>e.open=true);
await check('UX1 link immediately below context; short receipt summary accurate and no fold control',async()=>{await route('case=BH-001');await p.waitForSelector('.p20-end');assert.equal(await a('info').innerText(),'Xem thông tin hồ sơ');const positions=await p.locator('.p20-scroll').evaluate(e=>[...e.children].map(c=>c.className));assert.match(positions[1],/p20-info/);assert.match(await p.locator('.p20-receipt-summary').innerText(),/2 loại linh kiện · Tổng số lượng 3/);assert.equal(await a('expand').count(),0);await a('codes').click();await p.waitForSelector('.p20-codes-dialog[open]');assert.match(await p.locator('.p20-codes-dialog[open]').innerText(),/LK0001-HN001/);await shot('codes-normal');await p.keyboard.press('Escape');await pause();});
await check('UX2 large receipt3/6 rows; expand/collapse preserves ID, focus and remembered state per case',async()=>{await route('case=BH-001&sample=long-history');await p.waitForSelector('[data-p20=expand]');assert.equal(await p.locator('.p20-line').count(),3);await shot('receipt-collapsed');await a('expand').click();assert.equal(await p.locator('.p20-line').count(),6);assert.equal(await a('expand').getAttribute('aria-expanded'),'true');await shot('receipt-expanded');await a('info').click();await p.waitForSelector('.p09-app');await p.goBack();await p.waitForSelector('.p20-app');assert.equal(await p.locator('.p20-line').count(),6);await route('case=BH-002');await p.waitForSelector('.p20-end');await route('case=BH-001&sample=long-history');assert.equal(await p.locator('.p20-line').count(),6);await a('expand').click();assert.equal(await p.locator('.p20-line').count(),3);assert.equal(await a('expand').evaluate(e=>document.activeElement===e),true);});
await check('UX3 source code dialog exact incl2100+, Unicode/HTML; backdrop/Tab/Escape/Back restore exact trigger',async()=>{await a('codes').click();await p.waitForSelector('.p20-codes-dialog[open]');const d=p.locator('.p20-codes-dialog[open]');assert.ok((await d.locator('.app-modal-body').textContent()).includes(longCode));assert.equal(await p.locator('.app-modal-host').count(),1);await p.locator('.app-modal-host').evaluate(e=>e.click());assert.equal(await d.count(),1);await p.keyboard.press('Tab');assert.equal(await d.evaluate(e=>e.contains(document.activeElement)),true);await shot('codes-long');await geometry('codes494');await p.keyboard.press('Escape');await pause();assert.equal(await a('codes').evaluate(e=>document.activeElement===e),true);await a('codes').click();await p.goBack();await pause();assert.equal(await p.locator('.p20-codes-dialog[open]').count(),0);assert.equal(await a('codes').evaluate(e=>document.activeElement===e),true);});
await check('UX6 overlap marks one new ID, keeps top; explicit jump focuses new row, not duplicate',async()=>{await route('case=BH-001&sample=history');await p.waitForSelector('[data-p20=load]:not(:disabled)');await p.locator('.p20-scroll').evaluate(e=>e.scrollTop=40);const top=await p.locator('.p20-scroll').evaluate(e=>e.scrollTop);await a('load').evaluate(e=>e.click());await p.waitForSelector('[data-p20=new]');assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollTop),top);assert.equal(await p.locator('.p20-batch').count(),1);assert.equal(await a('new').innerText(),'Đến phiếu vừa tải (1)');await a('new').click();assert.equal(await p.locator('[data-p20-document="XLK-DEMO-OLDER"]').evaluate(e=>document.activeElement===e),true);await shot('new-batch');});
await check('UX4 exact verified receipt via P19→P09→P20 highlighted once; Back preserves new scroll',async()=>{await route('case=BH-001');await a('issue').click();await p.waitForSelector('.p19-app:not(.p20-app)');await p.click('[data-scan-action=manual]');await p.fill('#p19-code','LK0001-HN001');await p.locator('#p19-manual-form button[type=submit]').click();await p.click('[data-p19=review]');await p.click('[data-p19=post]');await p.waitForSelector('[data-panel="P19.S04"]');const r=(await issue()).receipt;await p.click('[data-p19=case]');await p.waitForSelector('.p09-app');await p.click('[data-p09=component-history]');await p.waitForSelector('.p20-fresh-label');const row=p.locator('[data-p20-document="'+r.id+'"]');assert.equal(await row.evaluate(e=>document.activeElement===e),true);assert.equal(await p.locator('.p20-fresh-label').count(),1);await shot('fresh-receipt');await p.locator('.p20-scroll').evaluate(e=>e.scrollTop=0);await a('info').click();await p.waitForSelector('.p09-app');await p.goBack();await p.waitForSelector('.p20-app');assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollTop),0);await route('case=BH-002&receipt='+r.id);await p.waitForSelector('.p20-end');assert.equal(await p.locator('.p20-fresh-label').count(),0);});
await check('UX5 pending footer exact draft ID +1code/2units and resume same document',async()=>{await route('case=BH-003');await p.waitForSelector('.p20-empty');await a('issue').click();await p.waitForSelector('.p19-app:not(.p20-app)');await p.click('[data-scan-action=manual]');await p.fill('#p19-code','BOX-LK-0002-01');await p.locator('#p19-manual-form button[type=submit]').click();await p.locator('.p19-sheet button[type=submit]').click();await route('case=BH-003');const pending=(await p.locator('[data-p20-pending]').innerText());assert.match(pending,/Phiếu đang làm/);const before=await issue();assert.ok(pending.includes(before.document.documentId));assert.ok(pending.includes(before.counts.codes+' mã/hộp'));assert.ok(pending.includes(before.counts.quantity+' linh kiện'));await shot('pending-footer');await a('issue').click();assert.equal((await issue()).document.documentId,before.document.documentId);});
await check('UNKNOWN CTA routes same request to reconciliation without another Post',async()=>{await p.click('[data-p19=review]');await p.selectOption('[data-p19-outcome]','unknown');await p.click('[data-p19=post]');await p.waitForSelector('.hn-action-dialog[open]');await p.getByRole('button',{name:'Để sau',exact:true}).click();await pause();const before=await issue();await route('case=BH-003');assert.match(await a('issue').innerText(),/Đối chiếu/);assert.match(await p.locator('[data-p20-block]').innerText(),/trước khi gửi lại/);await shot('unknown-footer');await a('issue').click();await p.waitForSelector('[data-p19=reconcile]');const after=await issue();assert.equal(after.request.id,before.request.id);assert.equal(after.metrics.post,before.metrics.post);});
await check('5 viewports long receipt/raw-code dialog/pending footer geometry',async()=>{for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});await route('case=BH-001&sample=long-history');await geometry('long-receipt');await a('codes').click();await p.waitForSelector('.p20-codes-dialog[open]');await geometry('raw-dialog');await p.keyboard.press('Escape');await pause();await route('case=BH-003');await geometry('pending');await shot('pending-'+width+'x'+height);}});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors,layouts},null,2));console.log(checks.length+' UX groups PASS');
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack,layouts},null,2));throw e;}finally{await b.close();}})();
