const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out=path.resolve('handoff/motion/M10/'+(before?'before':'evidence'));fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/profile/profile.mjs','docs/flows/profile/profile-model.mjs','docs/flows/profile/style.css','docs/flows/profile/motion.mjs','docs/flows/home/home.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
fs.writeFileSync(path.join(out,'source.json'),JSON.stringify(files.filter(f=>fs.existsSync(f)).map(file=>({file,bytes:fs.statSync(file).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')})),null,2));
if(before)for(const f of files.filter(f=>fs.existsSync(f))){const target=path.join(out,'source',f);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(f,target);}
(async()=>{const b=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));
await c.tracing.start({screenshots:true,snapshots:true,sources:true});
await p.addInitScript(()=>{window.qaEffects=[];window.qaAllEffects=[];window.qaFrames=[];window.qaPayloads=[];window.qaSaves=0;window.qaHardware=0;window.qaVisibility=0;window.qaHold=false;window.qaReject=false;
 const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVisibility++;return add.call(this,t,f,o);};
 EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVisibility--;return remove.call(this,t,f,o);};
 const native=Element.prototype.animate;Element.prototype.animate=function(frames,opts){const e={primitive:this.dataset.motionPrimitive,node:this.id||this.className,duration:opts.duration,frames,cancelled:false};qaEffects.push(e);qaAllEffects.push(e);const a=native.call(this,frames,opts),cancel=a.cancel.bind(a);a.cancel=()=>{e.cancelled=true;cancel();};if(e.primitive?.startsWith('Profile')){const node=this,start=performance.now();function sample(){qaFrames.push({primitive:e.primitive,elapsed:performance.now()-start,opacity:getComputedStyle(node).opacity,connected:node.isConnected});if(node.isConnected&&performance.now()-start<170)requestAnimationFrame(sample);}requestAnimationFrame(sample);}return a;};
 if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaHardware++;throw Error('No hardware');};});
// Fault injection into the existing read-only preview adapter, not a new API/fixture.
if(!before)await p.route('**/profile/profile-model.mjs',async route=>{const response=await route.fetch();let body=await response.text();body=body.replace('async save(){return','async save(){window.qaSaves++;window.qaPayloads.push(structuredClone(arguments[0]));if(window.qaHold)await new Promise(resolve=>window.qaRelease=resolve);if(window.qaReject)throw Error("QA save failure");return').replace('role:session.actor.role','role:window.qaRole??session.actor.role');await route.fulfill({response,body});});
const act=n=>p.locator(`[data-p10="${n}"]`).first(),settle=()=>p.waitForTimeout(240);
async function check(name,fn){await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);}
async function panel(n){if(n===1){await p.click('[data-tab=profile]');}else{if(await p.locator('.p10-app').getAttribute('data-panel')!=='P10.S01')await act('back').click();await act({2:'edit',3:'rights',4:'security'}[n]).click();}await p.locator(`[data-panel="P10.S0${n}"]`).waitFor();await settle();}
async function capture(n){await settle();r.geometry['P10.S0'+n]=await p.locator('.p10-app').evaluate(app=>{const shell=app.closest('.hn-screen'),s=shell.getBoundingClientRect();return{rects:Object.fromEntries(['.p10-header','.p10-scroll','.p10-footer','.p10-person','.p10-permissions','.hn-nav'].map(q=>{const node=shell.querySelector(q);if(!node)return[q,null];const r=node.getBoundingClientRect();return[q,[r.x-s.x,r.y-s.y,r.width,r.height]];})),nodes:app.querySelectorAll('*').length,text:app.innerText};});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-P10.S0'+n+'.png')});}
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await p.click('[data-tab=profile]');
for(const n of [1,2,3,4]){if(n!==1)await panel(n);await capture(n);}if(!before)await run({p,r,act,panel,check,settle,mode,out});
assert.deepEqual(r.errors,[]);r.operations=await p.evaluate(()=>qaSaves);r.hardware=await p.evaluate(()=>qaHardware);r.effects=await p.evaluate(()=>qaAllEffects);r.payloads=await p.evaluate(()=>qaPayloads);r.frames=await p.evaluate(()=>qaFrames);await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});await c.close();
}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})();
async function run({p,r,act,panel,check,settle,mode,out}){
const clear=()=>p.evaluate(()=>qaEffects=[]),effects=()=>p.evaluate(()=>qaEffects.filter(e=>e.primitive?.startsWith('Profile'))),close=async()=>{await act('dialog-close').click();await p.waitForFunction(()=>!history.state?.hnProfileDialog);};
await check('Settings press100; avatar/permissions static; disabled and off do not animate',async()=>{await panel(1);await clear();await act('rights').dispatchEvent('pointerdown');await settle();let e=await effects();assert.ok(mode==='auto'?e.some(x=>x.primitive==='ProfileSettingsPress'&&x.duration===100):e.length===0);assert.ok(e.every(x=>!x.frames.some(f=>f.transform)));await clear();await act('edit-avatar').dispatchEvent('pointerdown');await act('edit-avatar').click();await p.locator('[data-panel="P10.S02"]').waitFor();await settle();assert.equal((await effects()).length,0);await clear();await p.locator('[data-p10-save]').dispatchEvent('pointerdown');assert.equal((await effects()).length,0);});
await check('IME/caret/value survive form feedback; no route fade per field value',async()=>{await clear();await p.locator('#p10-name').evaluate(e=>{window.qaInput=e;e.focus();e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='Nguyễn Minh Ánh';e.setSelectionRange(7,7);e.dispatchEvent(new InputEvent('input',{bubbles:true,data:'Á',isComposing:true}));e.dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,key:'Enter',isComposing:true}));});assert.equal(await p.locator('#p10-name').evaluate(e=>e===qaInput&&e===document.activeElement&&e.selectionStart===7),true);await p.locator('#p10-name').dispatchEvent('compositionend',{data:'Á'});await settle();const e=await effects();assert.ok(e.every(x=>x.node==='p10-unsaved-status'));assert.equal(await p.evaluate(()=>qaEffects.some(e=>e.node==='hn-destination')),false);assert.equal(await p.inputValue('#p10-name'),'Nguyễn Minh Ánh');});
await check('Pending fixed slot, reject then retry: one request each, no animation callback mutation',async()=>{const box=await p.locator('.p10-footer').boundingBox();await p.evaluate(()=>{qaHold=true;qaReject=true;});await p.click('[data-p10-save]');assert.equal(await p.evaluate(()=>qaSaves),1);assert.equal(await p.locator('[data-p10-save]').isDisabled(),true);assert.match(await p.locator('#p10-unsaved-status').textContent(),/Đang lưu/);assert.deepEqual(await p.locator('.p10-footer').boundingBox(),box);await p.evaluate(()=>document.querySelector('#p10-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(await p.evaluate(()=>qaSaves),1);await p.evaluate(()=>qaRelease());await p.locator('.p10-dialog').waitFor();assert.equal(await p.inputValue('#p10-name'),'Nguyễn Minh Ánh');await close();await p.evaluate(()=>{qaHold=false;qaReject=false;});await p.click('[data-p10-save]');await p.locator('.p10-dialog').waitFor();await close();assert.equal(await p.evaluate(()=>qaSaves),2);assert.equal(await p.locator('#p10-name').evaluate(e=>e===qaInput),true);assert.equal(await p.inputValue('#p10-name'),'Nguyễn Minh Ánh');await act('back').click();await act('dialog-confirm').click();await p.locator('[data-panel="P10.S01"]').waitFor();});
await check('Read-only identity update fades140 only; mode off/Back grants no permission and no replay',async()=>{await panel(3);await clear();await p.evaluate(()=>{qaRole='Nhân viên kiểm kê';dispatchEvent(new PopStateEvent('popstate',{state:history.state}));});await settle();const e=await effects();assert.ok(mode==='off'?e.length===0:e.some(x=>x.primitive==='ProfileIdentity'&&x.duration===(mode==='auto'?140:80)));assert.equal(await p.locator('.p10-permissions button,.p10-permissions input').count(),0);assert.equal(await p.locator('.p10-permissions [data-status=unknown]').count(),6);await clear();await p.evaluate(()=>dispatchEvent(new PopStateEvent('popstate',{state:history.state})));await act('back').click();await act('rights').click();await settle();assert.equal((await effects()).filter(x=>x.primitive==='ProfileIdentity').length,0);await p.click('[data-tab=home]');await p.evaluate(()=>location.hash='#p02/profile?panel=3');await p.locator('[data-panel="P10.S03"]').waitFor();assert.equal(await p.locator('.p10-permissions button,.p10-permissions input').count(),0);r.permissionState=await p.locator('.p10-permissions').innerText();});
await check('S04/P11 caller history, rapid navigation, native Back remain exact',async()=>{await panel(4);await act('password').click();await p.locator('.p11-app').waitFor();await p.locator('[data-p11=back]').first().click();await p.locator('[data-panel="P10.S04"]').waitFor();await act('back').click();await p.locator('[data-panel="P10.S01"]').waitFor();await p.evaluate(()=>{document.querySelector('[data-p10=rights]').click();document.querySelector('[data-p10=back]').click();});await p.locator('[data-panel="P10.S01"]').waitFor();await settle();assert.equal(await p.locator('.p10-app').count(),1);});
await check('Mode/OS cancellation and10 hide cycles release all consumer effects/listeners',async()=>{await p.click('[data-tab=home]');const baseline=await p.evaluate(()=>qaVisibility);for(let i=0;i<10;i++){await p.click('[data-tab=profile]');await act('rights').dispatchEvent('pointerdown');await p.click('[data-tab=home]');assert.equal(await p.evaluate(()=>qaVisibility),baseline);}await p.click('[data-tab=profile]');await act('rights').dispatchEvent('pointerdown');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p10-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await act('rights').dispatchEvent('pointerdown');await p.emulateMedia({reducedMotion:'reduce'});await settle();assert.equal(await p.locator('.p10-app').evaluate(e=>e.getAnimations({subtree:true}).length),0);await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.selectOption('#home-motion-mode','off');await clear();await act('rights').dispatchEvent('pointerdown');await act('rights').click();await settle();assert.equal((await effects()).length,0);await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');});
await check('Compact viewport keeps native scrolling, focus, CTA, and complete data',async()=>{await panel(2);await p.setViewportSize({width:360,height:420});await p.fill('#p10-phone',' 0901 234 567 ');await p.locator('#p10-phone').press('Enter');await settle();assert.equal(await p.inputValue('#p10-phone'),' 0901 234 567 ');assert.equal(await p.locator('.p10-dialog').count(),0);const m=await p.evaluate(()=>{const app=document.querySelector('.p10-app'),scroll=app.querySelector('.p10-scroll'),s=app.closest('.hn-screen').getBoundingClientRect(),f=app.querySelector('.p10-footer').getBoundingClientRect();return {overflow:scroll.scrollWidth>scroll.clientWidth,footer:f.bottom<=s.bottom+1,shell:[app.closest('.hn-screen').offsetWidth,app.closest('.hn-screen').offsetHeight]};});assert.deepEqual(m,{overflow:false,footer:true,shell:[494,950]});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-compact.png')});await p.setViewportSize({width:494,height:950});await act('back').click();await act('dialog-confirm').click();await p.locator('[data-panel="P10.S01"]').waitFor();});
await check('Logout cancels motion and protected content immediately; Back cannot revive it',async()=>{await act('rights').dispatchEvent('pointerdown');await act('logout').click();await act('dialog-confirm').click();await p.locator('#username').waitFor();assert.equal(await p.locator('.p10-app').count(),0);await p.goBack();await p.locator('#username').waitFor();assert.equal(await p.locator('#home-app').isVisible(),false);assert.equal(await p.evaluate(()=>qaHardware),0);});
}
