const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const out=process.env.P14_UPGRADE_DIR||'handoff/P14/evidence/revision-03';fs.mkdirSync(path.join(out,'after'),{recursive:true});
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
const a=v=>p.locator(`[data-p14="${v}"]`).first(),dialog=()=>p.locator('.app-modal-host dialog');
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function close(){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));}
async function mode(v){await p.locator('.p14-tools details').evaluate(e=>e.open=true);await p.selectOption('[data-p14-scenario]',v);await p.evaluate(()=>scrollTo(0,0));}
async function login(){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home').waitFor({state:'visible'});}
async function shift(){await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await p.locator('.p14-app').waitFor();}
async function save(){await a('save').click();await dialog().getByRole('button',{name:'Lưu nháp',exact:true}).click();await dialog().getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));}
async function shot(n){await p.locator('.p14-app').locator('xpath=ancestor::*[contains(@class,"screen")][1]').screenshot({path:path.join(out,'after',n+'.png')});}
try{
await check('S01 Enter submits through dock; UNKNOWN copy/action is recovery-specific and singular',async()=>{await p.goto('http://localhost:8766/flows/auth-session/');await p.click('#forgot');await mode('unknown');await p.fill('#p14-username','minhanh');await p.keyboard.press('Enter');await dialog().waitFor();assert.doesNotMatch(await dialog().textContent(),/phiếu/);await close();assert.equal(await p.locator('.p14-actions [data-p14=check]').count(),1);assert.equal(await p.locator('.p14-app button[type=submit]').count(),0);assert.doesNotMatch(await p.locator('.p14-pending').textContent(),/phiếu/);await shot('S01-unknown');});
await p.clock.setFixedTime(new Date('2026-09-28T23:30:00+07:00'));await login();await shift();
await check('S03 domain list uses one contained dialog with Back/focus and no exposed technical dump',async()=>{await a('all').click();await dialog().waitFor();assert.equal(await p.locator('.p14-dialog-record').count(),1);assert.equal(await p.locator('.p14-dialog-record details[open]').count(),0);await p.keyboard.press('Tab');assert.ok(await dialog().evaluate(e=>e.contains(document.activeElement)));await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await shot('S03-record-list');await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await a('all').evaluate(e=>document.activeElement===e));});
await check('S03 save then UNKNOWN end uses warning and reconciliation, never ready green',async()=>{await save();await mode('timeout-recorded');await p.clock.setFixedTime(new Date('2026-09-29T07:30:00+07:00'));await a('end').click();await dialog().getByRole('button',{name:'Kết thúc ca',exact:true}).click();await dialog().waitFor();await close();assert.equal(await p.locator('.p14-app').getAttribute('data-shift-state'),'pending');assert.equal(await p.locator('.p14-scroll>.p14-notice.success').count(),0);assert.match(await p.locator('.p14-scroll>.p14-notice').textContent(),/Chưa xác định ca đã kết thúc/);assert.ok(await a('end').isDisabled());assert.equal(await p.locator('.p14-actions [data-p14=check]').count(),1);await shot('S03-end-unknown');await a('all').click();await dialog().waitFor();assert.equal(await p.locator('[data-record-choose]').count(),0);assert.match(await dialog().textContent(),/Đối chiếu kết quả trước/);await close();});
await check('S04 overnight start/end have complete dates and stable summary dock',async()=>{await a('check').click();await p.locator('[data-panel="P14.S04"]').waitFor();const text=await p.locator('.p14-shift-meta').textContent();assert.match(text,/23:30 · 28\/09\/2026/);assert.match(text,/07:30 · 29\/09\/2026/);assert.equal(await a('drafts').evaluate(e=>e.offsetHeight),44);await shot('S04-overnight');});
await check('S04 historical count and details remain one after a new outbound draft exists',async()=>{await p.click('[data-tab=home]');await p.click('.hn-task[data-route=outbound]');await p.locator('[data-panel="P05.S01"]').waitFor();await p.click('[data-p05=back]');await p.locator('#hn-home').waitFor({state:'visible'});await shift();assert.equal(await p.locator('.p14-drafts strong').textContent(),'1');await a('drafts').click();await dialog().waitFor();assert.equal(await p.locator('.p14-dialog-record').count(),1);assert.doesNotMatch(await dialog().textContent(),/fixture-outbound/);assert.equal(await p.locator('[data-record-choose]').count(),0);assert.match(await dialog().textContent(),/thời điểm kết thúc ca/);await shot('S04-snapshot-list');await close();});
// Additional states come only from a browser-local source override; owners stay unchanged.
await p.route('**/home/home.mjs*',async route=>{const r=await route.fetch();let body=await r.text();assert.ok(body.includes('getRecords:shiftRecords'));body=body.replace('getRecords:shiftRecords','getRecords:()=>{const rows=shiftRecords();window.__p14Actual=rows;return window.__p14AuditRecords||rows;}');await route.fulfill({response:r,body});});
await login();await shift();
await check('S03 zero and owner-UNKNOWN sources have correct action/guard',async()=>{await p.evaluate(()=>{window.__p14Saved=structuredClone(window.__p14Actual);window.__p14AuditRecords=[];location.hash='#home';});await p.locator('#hn-home').waitFor({state:'visible'});await shift();assert.match(await p.locator('.p14-scroll>.p14-notice').textContent(),/Không có phiếu/);assert.ok(await a('end').isEnabled());await p.evaluate(()=>{window.__p14AuditRecords=[{...window.__p14Saved[0],unknown:true}];location.hash='#home';});await p.locator('#hn-home').waitFor({state:'visible'});await shift();assert.equal(await p.locator('.p14-app').getAttribute('data-shift-state'),'source-unknown');assert.equal(await p.locator('[data-p14=save]').count(),0);assert.ok(await a('end').isDisabled());await shot('S03-owner-unknown');});
await check('S03 many/long rows clamp to2 lines; reader retains full250/2200 values',async()=>{await p.evaluate(()=>{const original=window.__p14Saved[0];window.__p14AuditRecords=Array.from({length:12},(_,i)=>({...structuredClone(original),document:{...structuredClone(original.document),documentId:i===11?original.document.documentId:original.document.documentId+'-'+i,number:Array.from('Mã_dài🌸_'.repeat(400)).slice(0,i?250:2200).join('')}}));location.hash='#home';});await p.locator('#hn-home').waitFor({state:'visible'});await shift();assert.equal(await p.locator('.p14-record').count(),12);const marker=p.locator('.p14-record [data-hn-readable]').first();await p.waitForFunction(()=>document.querySelector('.p14-record [data-hn-readable]').dataset.hnTruncated==='true');assert.ok(await p.locator('.p14-record').first().evaluate(e=>e.offsetHeight<160));const text=await marker.textContent();await p.locator('.p14-record-group [data-hn-read-trigger]').first().click();await dialog().waitFor();assert.equal(await dialog().locator('.app-modal-body').textContent(),text);await close();await shot('S03-many-long');});
await check('S03 Back after choosing exact owner restores scroll and trigger focus',async()=>{const target=p.locator('.p14-record').last();await target.scrollIntoViewIfNeeded();const before=await p.locator('.p14-scroll').evaluate(e=>e.scrollTop);assert.ok(before>0);await target.click();await p.locator('[data-panel="P04.S01"]').waitFor();await p.goBack();await p.locator('[data-panel="P14.S03"]').waitFor();await p.waitForFunction(y=>document.querySelector('.p14-scroll').scrollTop===y,before);assert.equal(await p.locator('.p14-scroll').evaluate(e=>e.scrollTop),before);assert.ok(await p.locator('.p14-record').last().evaluate(e=>document.activeElement===e));});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'upgrade-results.json'),JSON.stringify({checks,errors,status:'PASS',note:'Additional source injection isolated to browser; real-backend policy unverified.'},null,2));console.log('TOTAL '+checks.length);
}catch(e){fs.writeFileSync(path.join(out,'upgrade-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));await p.screenshot({path:path.join(out,'upgrade-failure.png')});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
