const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const phase=process.env.LOOKUP_NFC_AUDIT_PHASE||'after',out=path.resolve(process.env.LOOKUP_NFC_AUDIT_DIR||`handoff/ux-audit-2026-09-30-r02/p06-p07/${phase}`);fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];
async function run(name,fn,setup){const page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-30T06:00:00Z'));
try{if(setup)await setup(page);await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-scanner').waitFor();await fn(page);assert.deepEqual(errors,[]);results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.stack,errors});}finally{await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')}).catch(()=>{});await page.close();}console.log(name,results.at(-1).status);}
const lookup=async p=>{await p.click('.hn-scanner');await p.locator('[data-panel="P06.S01"]').waitFor();};
const nfc=async p=>{await p.click('[data-route="nfc"]');await p.locator('[data-panel="P07.S01"]').waitFor();};
const back=p=>p.locator('[data-p06="back"]');
for(const mode of ['clear','category'])await run(`lookup-ime-after-${mode}`,async p=>{await lookup(p);await p.fill('#p06-search','HN12346');await p.locator('#p06-search').dispatchEvent('compositionstart');if(mode==='clear')await p.click('.p06-search [data-p06="clear"]');else await p.click('[data-p06-category="components"]');const value=mode==='clear'?'HN12347':'LK0001';await p.fill('#p06-search',value);assert.equal(await p.locator('[data-p06-snapshot]').evaluate(e=>JSON.parse(e.textContent).query),value);assert.equal(await p.locator('.p06-list .p06-card').count(),1);});
await run('lookup-image-recovery-repairs-gallery',async p=>{await lookup(p);await p.locator('.p06-list [data-p06-item="fixture-item-HN12345"]').click();await p.locator('.p06-gallery [data-p06-image-source]').first().waitFor();await p.unroute('**/lookup/assets/demo/*.png');await p.click('[data-p06-image="0"]');await p.locator('.p06-large-image').evaluate(e=>e.decode());await p.waitForTimeout(100);assert.equal(await p.locator('[data-p06-image="0"] [data-p06-image-source]').count(),0);assert.equal(await p.locator('[data-p06-image="0"] img').count(),1);},async p=>{await p.route('**/lookup/assets/demo/*.png',r=>r.fulfill({status:404,body:''}));});
await run('nfc-repeated-back-keeps-parent',async p=>{await nfc(p);await p.locator('[data-p07="begin"]').first().click();await p.click('[data-p07-demo-read]');await p.locator('[data-p07="next"]:not(:disabled)').waitFor();await p.click('[data-p07="next"]');await p.locator('[data-panel="P07.S03"]').waitFor();await p.locator('[data-p07="back"]').evaluate(e=>{e.click();e.click();});await p.waitForTimeout(300);assert.equal(await p.locator('[data-panel="P07.S02"]').count(),1);assert.match(p.url(),/nfc\?panel=2$/);});
for(const status of ['error','stale'])await run(`nfc-${status}-row-click-guard`,async p=>{await nfc(p);await p.fill('#p07-search','NFC-3F7D9A');const row=p.locator('[data-p07-tag]').first();if(await row.count())await row.click();assert.equal(await p.locator('#p07-detail-title').count(),0);assert.match(await p.locator('.p07-list').innerText(),/Chưa|chưa|Thử|thử/);},async p=>{await p.route('**/nfc/fixture-adapter.mjs*',async r=>{const response=await r.fetch(),body=await response.text();await r.fulfill({response,body:body.replace("status:'ready'",status==='stale'?"status:'ready',stale:true":"status:'error'")});});});
await run('lookup-back-restores-normal-duplicate-row',async p=>{await lookup(p);for(const id of ['HN12345','HN12346','HN12347']){await p.locator(`.p06-list [data-p06-item="fixture-item-${id}"]`).click();await back(p).click();await p.locator('[data-panel="P06.S01"]').waitFor();}const row=p.locator('.p06-list [data-p06-item="fixture-item-HN12346"]');await row.focus();const before=await p.locator('.p06-scroll').evaluate(e=>e.scrollTop);await row.click();await back(p).click();await p.locator('[data-panel="P06.S01"]').waitFor();assert.ok(await row.evaluate(e=>e===document.activeElement));assert.equal(await p.locator('.p06-scroll').evaluate(e=>e.scrollTop),before);});
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results},null,2));await browser.close();if(phase!=='before'&&results.some(r=>r.status==='FAIL'))process.exitCode=1;})();
