const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='handoff/P22/evidence/revision-03/combinations';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],errors=[],layout=[];p.on('pageerror',e=>errors.push(e.message));
const a=k=>p.locator(`[data-p22="${k}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p22-snapshot]').textContent());
const shot=n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});
const route=async h=>{await p.evaluate(h=>location.hash=h,h);await p.waitForTimeout(120);};
const wait=()=>p.waitForFunction(()=>{const n=document.querySelector('[data-p22-snapshot]');return n&&!JSON.parse(n.textContent).refreshing&&JSON.parse(n.textContent).source!=='loading';});
const source=async v=>{await p.selectOption('[data-p22-source]',v);await wait();};
async function test(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function reset(){while(await p.locator('[data-p22-remove]').count())await p.locator('[data-p22-remove]').first().click();if(await p.locator('.p22-query-clear:not([hidden])').count())await a('clear-query').click();}
try{await p.clock.setFixedTime(new Date('2026-09-30T05:00:00Z'));await p.goto('http://localhost:8766/flows/auth-session/?v=p22-r03');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('.hn-intro');await route('#p02/history?scene=nfc');await source('fixture');
await test('Deferred query commits once after Cancel with clear button and scope intact',async()=>{await p.locator('#p22-search').evaluate(e=>{e.value='HN12346';e.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-p22=filter]').focus();document.querySelector('[data-p22=filter]').click();});await p.waitForTimeout(350);await p.getByRole('button',{name:'Hủy',exact:true}).click();await p.waitForTimeout(200);assert.equal((await snap()).count,1);assert.equal(await a('clear-query').isVisible(),true);assert.equal(await p.locator('[data-p22=filter]').first().evaluate(e=>e===document.activeElement),true);await p.locator('[data-p22-event="NFC-E002"]').click();await a('back').click();await p.waitForSelector('#p22-search');assert.equal(await p.inputValue('#p22-search'),'HN12346');await reset();});
await test('Read focus never steals a newer input, external control, or pointer choice',async()=>{await p.selectOption('[data-p22-read-outcome]','slow');for(const target of ['#p22-search','[data-p22-source]']){await a('reload').click();await p.locator(target).focus();await wait();assert.equal(await p.locator(target).evaluate(e=>e===document.activeElement),true);}await a('reload').click();await p.locator('.p22-app h1').click();await wait();assert.equal(await a('reload').evaluate(e=>e===document.activeElement),false);});
await test('Refresh error deferred under filter; Apply retains query and failure context',async()=>{await a('reload').click();await a('filter').click();await p.fill('[name=from]','10/09/2026');await p.fill('[name=to]','10/09/2026');await p.waitForTimeout(900);await p.locator('.p08-picker [type=submit]').click();await p.waitForSelector('#p22-search');await p.selectOption('[data-p22-read-outcome]','error');await a('reload').click();await wait();assert.match(await p.locator('.p22-read-status').innerText(),/lần đọc trước/);await a('filter').click();await p.locator('[name=status][value="Đã thu hồi"]').check();await p.locator('.p08-picker [type=submit]').click();await p.waitForSelector('#p22-search');assert.equal((await snap()).count,1);assert.equal((await snap()).readIssue,'error');await reset();});
await test('Cancelled refresh stays interrupted after late completion and retry recovers',async()=>{await p.selectOption('[data-p22-read-outcome]','slow');await a('reload').click();await p.locator('[data-p22-event="NFC-E002"]').click();await p.waitForTimeout(950);assert.match(await p.locator('.p22-detail-read-status').innerText(),/chưa hoàn tất/);await a('back').click();await p.waitForSelector('#p22-search');assert.equal((await snap()).readIssue,'interrupted');await p.selectOption('[data-p22-read-outcome]','ready');await a('reload').click();await wait();assert.equal((await snap()).readIssue,null);});
await test('Double Back consumes one entry; Forward returns to exact event',async()=>{await p.locator('[data-p22-event="NFC-E002"]').click();await a('back').evaluate(e=>{e.click();e.click();});await p.waitForSelector('#p22-search');assert.equal(await p.locator('.p22-viewed').getAttribute('data-p22-event'),'NFC-E002');await p.goForward();await p.waitForSelector('.p22-replacement');assert.match(p.url(),/event=NFC-E002/);await a('back').click();await p.waitForSelector('#p22-search');});
await test('Late clipboard does not stack over reader; reader Escape returns focus',async()=>{await source('long');await p.locator('[data-p22-event="NFC-E002"]').click();await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>window.resolveClipboard=r)}}));await p.locator('[data-p22-copy=uid]').click();const reader=p.getByRole('button',{name:'Xem đầy đủ thẻ thay thế',exact:true});await reader.click();await p.waitForSelector('.hn-readable-dialog[open]');await p.evaluate(()=>window.resolveClipboard());await p.waitForTimeout(160);assert.equal(await p.locator('dialog[open]').count(),1);assert.equal(await p.locator('.hn-readable-dialog[open]').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(180);assert.equal(await reader.evaluate(e=>e===document.activeElement),true);await a('back').click();await p.waitForSelector('#p22-search');});
await test('Long query and active filters / error detail fit5viewports with stable header-footer',async()=>{await a('filter').click();await p.fill('[name=from]','02/07/2026');await p.fill('[name=to]','30/09/2026');await p.locator('[name=status][value="Thành công"]').check();await p.locator('.p08-picker [type=submit]').click();await p.waitForSelector('#p22-search');await p.locator('[data-p22-type="Thay thẻ"]').click();await p.fill('#p22-search','NFC-7B10'+'-UID'.repeat(50));await p.press('#p22-search','Enter');await p.selectOption('[data-p22-read-outcome]','error');await a('reload').click();await wait();for(const viewport of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width:viewport[0],height:viewport[1]});for(const scene of ['filtered-list','cached-detail']){if(scene==='cached-detail'){await p.locator('[data-p22-event="NFC-E002"]').click();await p.waitForSelector('.p22-replacement');}const m=await p.locator('.p22-app').evaluate(e=>{const s=e.querySelector('.p22-scroll'),f=e.querySelector('.p22-footer'),header=e.querySelector('header'),app=e.closest('.hn-screen'),controls=e.querySelector('.p22-controls');const rect=x=>x.getBoundingClientRect();return{shell:[app.offsetWidth,app.offsetHeight],overflow:s.scrollWidth>s.clientWidth+1,controlsOverflow:!!controls&&controls.scrollWidth>controls.clientWidth+1,small:[...e.querySelectorAll('button,summary')].filter(x=>x.getClientRects().length&&x.offsetHeight<44).map(x=>x.textContent),footer:rect(f).bottom<=rect(app).bottom+1&&rect(s).bottom<=rect(f).top+1,header:rect(header).top>=rect(app).top-1};});assert.deepEqual(m.shell,[494,950]);assert.equal(m.overflow,false);assert.equal(m.controlsOverflow,false);assert.deepEqual(m.small,[]);assert.equal(m.footer,true);assert.equal(m.header,true);layout.push({viewport,scene,...m});await shot(scene+'-'+viewport.join('x'));if(scene==='cached-detail'){await a('back').click();await p.waitForSelector('#p22-search');}}}});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors,layout},null,2));}catch(e){await shot('failure');fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
