const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.INBOUND_LONG_EVIDENCE_DIR||'handoff/P04/evidence/revision-08/long-content');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const checks=[],errors=[];try{for(const length of [250,2100]){
 const page=await browser.newPage({viewport:{width:390,height:844}});page.on('pageerror',e=>errors.push(e.message));const name=('Nhà cung cấp Đặng 🌿 <NCC>\n'+'TênLiền'.repeat(40)).repeat(10).slice(0,length);
 await page.route('**/inbound/catalogue.mjs',async route=>{const response=await route.fetch();const body=(await response.text()).replace("'Công ty Minh Phát'",JSON.stringify(name));await route.fulfill({response,body,contentType:'text/javascript'});});
 await page.goto((process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8774')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();await page.locator('[data-p04="next"]').click();
 const text=page.locator('.p04-context-supplier');assert.equal(await text.textContent(),name);await page.locator('.p04-scan-context .hn-read-more').waitFor();await page.locator('.p04-scan-context .hn-read-more').click();const dialog=page.locator('.hn-action-dialog[open]');await dialog.waitFor();assert.equal(await dialog.locator('.app-modal-body p').textContent(),name);assert.equal(await page.locator('NCC').count(),0);await page.goBack();await dialog.waitFor({state:'detached'});assert.equal(await page.locator('.p04-scan-context .hn-read-more').evaluate(e=>e===document.activeElement),true);
 await page.locator('[data-p04="context"]').click();await dialog.waitFor();assert.ok((await dialog.locator('.app-modal-body p').textContent()).includes(name));const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen').getBoundingClientRect(),d=document.querySelector('.hn-action-dialog[open]').getBoundingClientRect(),f=document.querySelector('.hn-action-dialog[open] footer').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,inside:d.left>=s.left-1&&d.right<=s.right+1&&d.bottom<=s.bottom+1,footer:f.bottom<=d.bottom+1};});assert.equal(m.overflow,false);assert.ok(m.inside&&m.footer);await page.locator('.hn-screen').screenshot({path:path.join(out,`context-${length}.png`)});await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});checks.push({length,status:'PASS',geometry:m});await page.close();
 }assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,source:'Isolated catalogue response mock; no production source/data modification'},null,2));console.log(JSON.stringify({cases:checks.length,errors}));}finally{await browser.close();}})();
