const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='handoff/P22/evidence/revision-01/after';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const a=k=>p.locator(`[data-p22="${k}"]`),shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'}),snap=async()=>JSON.parse(await p.locator('[data-p22-snapshot]').textContent());
async function route(q){await p.evaluate(q=>location.hash='#p02/history?'+q,q);await p.waitForSelector('.p22-app');}
async function source(mode){await p.selectOption('[data-p22-source]',mode);await p.waitForFunction(()=>!document.querySelector('[data-p22=reload]:disabled'));}
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p22-r01');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');
await test('S01 approved hub6 no draft shortcut; default NFC unavailable',async()=>{await p.click('[data-tab=history]');await p.frameLocator('iframe').locator('.history-link').first().waitFor();assert.equal(await p.frameLocator('iframe').locator('.history-link').count(),6);assert.equal(await p.frameLocator('iframe').locator('.resume-shortcut').count(),0);await shot('S01');await p.frameLocator('iframe').locator('[data-action=nfc]').click();await p.waitForSelector('[data-panel="P22.S04"]');await shot('S04');await a('reload').click();await p.waitForSelector('[data-p22=reload]:not(:disabled)');assert.equal((await snap()).source,'unavailable');});
await test('S02 fixture type/query and Back retain focus; S03 exact event fields',async()=>{await source('fixture');await shot('S02');await p.locator('[data-p22-type="Thay thẻ"]').click();await p.fill('#p22-search','HN12346');await p.press('#p22-search','Enter');assert.equal(await p.locator('[data-p22-event]').count(),1);await p.click('[data-p22-event="NFC-E002"]');await p.waitForSelector('[data-panel="P22.S03"]');assert.match(await p.locator('.p22-app').innerText(),/Lan Nguyễn/);assert.match(await p.locator('.p22-app').innerText(),/NFC-OLD-7B10/);await shot('S03');await a('back').first().click();await p.waitForSelector('#p22-search');assert.equal(await p.inputValue('#p22-search'),'HN12346');assert.equal((await snap()).filters.type,'Thay thẻ');assert.equal(await p.locator('[data-p22-event="NFC-E002"]').evaluate(e=>e===document.activeElement),true);});
await test('Invalid event ID has no fallback; missing source never fake empty',async()=>{await route('scene=nfc-detail&event=DOES-NOT-EXIST');assert.match(await p.locator('.p22-app').innerText(),/Không tìm thấy thao tác NFC/);await shot('invalid-id');await source('unavailable');assert.match(await p.locator('.p22-app').innerText(),/Chưa có dữ liệu lịch sử/);assert.doesNotMatch(await p.locator('.p22-app').innerText(),/Chưa có thao tác/);});
await test('Verified empty/no-match/error distinct; retry remains read',async()=>{await route('scene=nfc');await source('empty');await a('clear').click();assert.match(await p.locator('.p22-app').innerText(),/Chưa có thao tác/);await shot('empty');await source('fixture');await p.fill('#p22-search','nothing-matches');await p.press('#p22-search','Enter');assert.match(await p.locator('.p22-app').innerText(),/Không có kết quả phù hợp/);await shot('no-match');await source('error');assert.match(await p.locator('.p22-app').innerText(),/Không tải được lịch sử/);await shot('error');await a('reload').click();await p.waitForSelector('[data-p22=reload]:not(:disabled)');assert.equal((await snap()).source,'error');});
await test('Reader keeps raw long Unicode text; Escape Back backdrop focus',async()=>{await source('long');await a('clear').click();await p.click('[data-p22-event="NFC-E003"]');await p.waitForSelector('[data-hn-read-trigger]:not([hidden])');const reader=p.getByRole('button',{name:'Xem đầy đủ nội dung thao tác',exact:true});await reader.click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Tiếng Việt <>& — 🌸/);await shot('reader');await p.locator('.app-modal-host').click({position:{x:2,y:2},force:true});assert.equal(await p.locator('.hn-action-dialog[open]').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(180);assert.equal(await reader.evaluate(e=>e===document.activeElement),true);await reader.click();await p.goBack();await p.waitForTimeout(180);assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);assert.equal(await p.locator('[data-panel="P22.S03"]').count(),1);});
await test('Late reads cannot reopen route; IME search stable',async()=>{await route('scene=nfc');await p.selectOption('[data-p22-source]','slow');await a('back').first().click();await p.waitForTimeout(1000);assert.equal(await p.locator('.p22-app').count(),0);await route('scene=nfc');await source('fixture');if(await a('clear').count())await a('clear').click();const input=p.locator('#p22-search');await input.focus();await input.evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='HN12346';e.dispatchEvent(new Event('input',{bubbles:true}));});await p.waitForTimeout(300);assert.equal(await p.locator('[data-p22-event]').count(),4);await input.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await p.waitForTimeout(300);assert.equal(await p.locator('[data-p22-event]').count(),1);assert.equal(await input.evaluate(e=>e===document.activeElement),true);});
await test('20 panel/viewport checks shell/footer/touch/overflow',async()=>{const metrics=[];for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const panel of ['S01','S02','S03','S04']){if(panel==='S01'){await p.evaluate(()=>location.hash='#p02/history');await p.frameLocator('iframe').locator('.history-link').first().waitFor();}else{await route(panel==='S03'?'scene=nfc-detail&event=NFC-E003':'scene=nfc');await source(panel==='S04'?'unavailable':'fixture');if(panel==='S02'&&await a('clear').count())await a('clear').click();}const m=await p.locator('.hn-screen').evaluate(e=>{const s=e.querySelector('.p22-scroll'),f=e.querySelector('.p22-footer'),r=e.getBoundingClientRect();return {w:e.offsetWidth,h:e.offsetHeight,overflow:s?s.scrollWidth>s.clientWidth+1:false,footer:f?f.getBoundingClientRect().bottom<=r.bottom+1:true,small:[...e.querySelectorAll('.p22-app button')].filter(x=>x.getClientRects().length&&x.offsetHeight<44).map(x=>x.outerHTML)};});assert.equal(m.w,494);assert.equal(m.h,950);assert.equal(m.overflow,false);assert.equal(m.footer,true);assert.deepEqual(m.small,[]);metrics.push({viewport:[width,height],panel,...m});await shot(panel+'-'+width+'x'+height);}}fs.writeFileSync(out+'/layout.json',JSON.stringify(metrics,null,2));});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));
}catch(e){await shot('failure');fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
