const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('handoff/P08/evidence/revision-06');fs.mkdirSync(out,{recursive:true});
function contrast(a,b){const lum=c=>{const v=c.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;});return v[0]*.2126+v[1]*.7152+v[2]*.0722;};const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-tab=history]');await page.frameLocator('iframe').locator('[data-action=history-general]').click();
 for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){
  await page.setViewportSize({width:w,height:h});
  const m=await page.locator('.p08-app').evaluate(app=>{const rows=[...app.querySelectorAll('.p08-row')],screen=app.closest('.hn-screen'),scroll=app.querySelector('.p08-scroll');return {shell:[screen.offsetWidth,screen.offsetHeight],overflow:scroll.scrollWidth>scroll.clientWidth+1,navSafe:scroll.getBoundingClientRect().bottom<=screen.querySelector('.hn-nav').getBoundingClientRect().top+1,rows:rows.map(r=>{const tile=r.querySelector('.p08-tile'),svg=tile.querySelector('svg'),strong=r.querySelector('strong'),name=r.querySelector('b'),small=r.querySelector('small');return {tile:[tile.offsetWidth,tile.offsetHeight],icon:[getComputedStyle(svg).width,getComputedStyle(svg).height,getComputedStyle(svg).strokeWidth,getComputedStyle(svg).color],title:[getComputedStyle(strong).fontSize,getComputedStyle(strong).fontWeight,getComputedStyle(strong).color],name:[getComputedStyle(name).fontSize,getComputedStyle(name).fontWeight,getComputedStyle(name).color],small:getComputedStyle(small).color,bg:getComputedStyle(r).backgroundColor,tileBg:getComputedStyle(tile).backgroundColor,bad:[...r.querySelectorAll('strong,small,b,time')].filter(e=>e.clientWidth&&e.scrollWidth>e.clientWidth+1).map(e=>e.textContent)};})};});
  assert.deepEqual(m.shell,[494,950]);assert.equal(m.overflow,false);assert.equal(m.navSafe,true);assert.equal(m.rows.length,6);
  for(const r of m.rows){assert.deepEqual(r.tile,[56,56]);assert.deepEqual(r.icon.slice(0,3),['30px','30px','1.8px']);assert.equal(r.title[1],'600');assert.equal(r.name[1],'500');assert.deepEqual(r.bad,[]);for(const c of [r.title[2],r.name[2],r.small])assert.ok(contrast(c,r.bg)>=4.5);assert.ok(contrast(r.icon[3],r.tileBg)>=3);}
  assert.equal(new Set(m.rows.map(r=>r.icon[3])).size,1);metrics.push({viewport:[w,h],...m});await page.locator('.hn-screen').screenshot({path:path.join(out,'list-'+w+'x'+h+'.png')});
 }
 await page.setViewportSize({width:494,height:1000});await page.locator('[data-p08-record="LS-0003"] .p08-tile').click();assert.match(await page.locator('.p08-detail-document').textContent(),/BH-001/);assert.equal(await page.locator('.p08-detail-glyph svg').evaluate(e=>getComputedStyle(e).width),'32px');await page.locator('.hn-screen').screenshot({path:path.join(out,'detail-unchanged.png')});await page.locator('[data-p08=back]').click();await page.locator('[data-p08-record="LS-0003"]').waitFor();assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'visual-results.json'),JSON.stringify({revision:'P08-r06',status:'PASS',metrics,errors,behavior:'Existing record ID and Back retained',integration:'NOT_RUN'},null,2));console.log('PASS six list viewports, typography/icon scope, contrast, detail navigation and Back');
}finally{await browser.close();}})();
