const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='handoff/P23/evidence/revision-01/after';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
const a=k=>p.locator(`[data-p23="${k}"]`),shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});
const text=()=>p.locator('.p23-app').innerText();
async function route(scene,id){await p.evaluate(({scene,id})=>location.hash='#p02/history?'+new URLSearchParams({scene,...(id?{[scene==='warranty-detail'?'case':'session']:id}:{})}),{scene,id});await p.waitForSelector('.p23-app');await p.waitForTimeout(80);}
async function source(mode){await p.selectOption('[data-p23-source]',mode);await p.waitForFunction(()=>!document.querySelector('[data-p23=reload]:disabled'));}
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p23-r01');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');
await test('Hub six entries routes S01; owner BH001/BH002 exact timeline and closed P20',async()=>{await p.click('[data-tab=history]');const frame=p.frameLocator('iframe');await frame.locator('.history-link').first().waitFor();assert.equal(await frame.locator('.history-link').count(),6);await frame.locator('[data-action=warranty]').click();await p.waitForSelector('[data-panel="P23.S01"]');await shot('S01');await p.fill('#p23-search','HN12345');await p.press('#p23-search','Enter');await p.click('[data-p23-entity="BH-001"]');assert.match(await text(),/Đang kiểm tra/);assert.equal(await p.locator('[data-p23-event-id^="BH-002"]').count(),0);await shot('S02');await a('back').first().click();await p.waitForSelector('#p23-search');assert.equal(await p.inputValue('#p23-search'),'HN12345');assert.equal(await p.locator('[data-p23-entity="BH-001"]').evaluate(e=>e===document.activeElement),true);await p.fill('#p23-search','HN12346');await p.press('#p23-search','Enter');await p.click('[data-p23-entity="BH-002"]');assert.match(await text(),/Đã trả khách chỉ đọc/i);assert.equal(await p.locator('[data-p23-event-id^="BH-001"]').count(),0);await shot('closed-case');await a('components').click();await p.waitForSelector('.p20-app');assert.match(await p.locator('.p20-app').innerText(),/BH-002/);assert.equal(await p.locator('[data-p20=issue]:not(:disabled)').count(),0);await p.locator('[data-p20=back]').first().click();await p.waitForSelector('[data-panel="P23.S02"]');assert.match(await text(),/BH-002/);});
await test('Default unavailable then S03/S04 B23 source, all three outcomes correct',async()=>{await route('sessions');assert.match(await text(),/Nguồn phiên và sự kiện quét chưa khả dụng/);await shot('unavailable');await source('fixture');await shot('S03');await p.click('[data-p23-entity="PQ-0003"]');assert.match(await text(),/Đã xuất/);assert.deepEqual(await p.locator('.p23-stats strong').allTextContents(),['2','0','3']);assert.equal(await p.locator('[data-p23-event-id]').count(),2);await shot('S04');await a('back').first().click();await p.waitForSelector('[data-p23-entity="PQ-0002"]');await p.click('[data-p23-entity="PQ-0002"]');assert.match(await text(),/Chờ xử lý trên Web/);assert.match(await text(),/chưa ghi sổ/);await shot('inbound-recorded');await a('back').first().click();await p.waitForSelector('[data-p23-entity="PQ-0001"]');await p.click('[data-p23-entity="PQ-0001"]');assert.match(await text(),/Tra cứu/);assert.doesNotMatch(await text(),/PN-0005/);await shot('lookup-ended');});
await test('Unknown IDs no fallback and legacy business deep link migrates',async()=>{await route('session-detail','BAD');assert.match(await text(),/Không tìm thấy phiên quét/);await shot('invalid-session');await route('warranty-detail','BAD');assert.match(await text(),/Không tìm thấy hồ sơ/);await p.evaluate(()=>location.hash='#p02/history-list?panel=2&business=warranty&record=BH-002');await p.waitForSelector('[data-panel="P23.S02"]');assert.match(await text(),/BH-002/);});
await test('Filter independent, query IME/Enter and keyboard tabs',async()=>{await route('sessions');await p.locator('[data-p23-type="Tra cứu"]').click();assert.equal(await p.locator('[data-p23-entity]').count(),1);await route('warranty');assert.equal(await p.inputValue('#p23-search'),'HN12346');await route('sessions');assert.equal(await p.locator('[data-p23-entity]').count(),1);await a('clear').click();const input=p.locator('#p23-search');await input.focus();await input.evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='PQ-0002';e.dispatchEvent(new Event('input',{bubbles:true}));});await p.waitForTimeout(300);assert.equal(await p.locator('[data-p23-entity]').count(),3);await input.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await p.waitForTimeout(300);assert.equal(await p.locator('[data-p23-entity]').count(),1);assert.equal(await input.evaluate(e=>e===document.activeElement),true);await a('clear').click();await p.locator('[data-p23-type=all]').focus();await p.keyboard.press('End');assert.equal(await p.locator('[data-p23-type="Tra cứu"]').getAttribute('aria-selected'),'true');});
await test('Shared date picker Cancel/Escape/Back no commit',async()=>{await a('filter').first().click();await p.waitForSelector('.app-modal-host');await shot('picker');await p.keyboard.press('Escape');await p.waitForTimeout(120);assert.equal(await p.locator('.app-modal-host').count(),0);await a('filter').first().click();await p.goBack();await p.waitForTimeout(120);assert.equal(await p.locator('.app-modal-host').count(),0);assert.match(await text(),/Tất cả ngày/);});
await test('Empty, error, missing metrics distinct; reload cache preserved',async()=>{await a('clear').click();await source('empty');assert.match(await text(),/Chưa có phiên/);await shot('empty');await source('error');assert.match(await text(),/Không tải được lịch sử/);await shot('error');await source('missing');await p.click('[data-p23-entity="PQ-0003"]');assert.deepEqual(await p.locator('.p23-stats strong').allTextContents(),['Chưa xác minh','Chưa xác minh','Chưa xác minh']);assert.match(await text(),/Chưa xác minh kết quả/);await shot('missing');await source('fixture');await p.selectOption('[data-p23-outcome]','error');await a('reload').click();await p.waitForSelector('[data-p23=reload]:not(:disabled)');assert.match(await text(),/lần đọc trước/);assert.equal(await p.locator('[data-p23-event-id]').count(),2);await shot('cache-error');await p.selectOption('[data-p23-outcome]','ready');});
await test('Long Unicode raw reader in-app, backdrop/Escape/focus and Back',async()=>{await source('long');await p.waitForSelector('[data-hn-read-trigger]:not([hidden])');const r=p.getByRole('button',{name:'Xem đầy đủ người quét',exact:true});await r.click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Tiếng Việt <>& 🌸/);await shot('reader');await p.locator('.app-modal-host').click({position:{x:2,y:2},force:true});assert.equal(await p.locator('.hn-action-dialog[open]').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(160);assert.equal(await r.evaluate(e=>e===document.activeElement),true);await r.click();await p.goBack();await p.waitForTimeout(160);assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);assert.equal(await p.locator('[data-panel="P23.S04"]').count(),1);});
await test('Stale read cannot reopen route; case timeline uses live P09 owner',async()=>{await route('sessions');await p.selectOption('[data-p23-source]','slow');await a('back').first().click();await p.waitForTimeout(850);assert.equal(await p.locator('.p23-app').count(),0);await p.evaluate(async()=>{const m=await import('../shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(x=>x.id==='BH-001');m.writeWarrantyCase({...c,status:'Chờ bàn giao',events:[...c.events,{id:'P23-TEST-OWNER',label:'Hoàn tất sửa chữa',day:'2026-09-30',time:'12:30',actor:'Minh Anh',description:'Sự kiện từ owner P09'}]});});await route('warranty-detail','BH-001');assert.match(await text(),/Chờ bàn giao/);assert.equal(await p.locator('[data-p23-event-id="P23-TEST-OWNER"]').count(),1);await p.evaluate(async()=>{(await import('../shared/warranty-cases.mjs')).resetWarrantyCases();});});
await test('20 layout combinations fixed shell, footer and touch targets',async()=>{const metrics=[];for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const [panel,scene,id]of [['S01','warranty'],['S02','warranty-detail','BH-001'],['S03','sessions'],['S04','session-detail','PQ-0003']]){await route(scene,id);if(scene==='sessions')await source('fixture');if(!scene.endsWith('detail')&&await a('clear').count())await a('clear').click();const m=await p.locator('.hn-screen').evaluate(e=>{const s=e.querySelector('.p23-scroll'),f=e.querySelector('.p23-footer'),r=e.getBoundingClientRect();return {w:e.offsetWidth,h:e.offsetHeight,overflow:s.scrollWidth>s.clientWidth+1,footer:f.getBoundingClientRect().bottom<=r.bottom+1,small:[...e.querySelectorAll('.p23-app button')].filter(x=>x.getClientRects().length&&x.offsetHeight<44).map(x=>x.outerHTML)};});assert.equal(m.w,494);assert.equal(m.h,950);assert.equal(m.overflow,false);assert.equal(m.footer,true);assert.deepEqual(m.small,[]);metrics.push({viewport:[width,height],panel,...m});await shot(panel+'-'+width+'x'+height);}}fs.writeFileSync(out+'/layout.json',JSON.stringify(metrics,null,2));});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));
}catch(e){await shot('failure');fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
