const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const out='handoff/P23/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(8000);await p.clock.install({time:new Date('2026-09-30T12:00:00+07:00')});
const a=k=>p.locator(`[data-p23="${k}"]`),shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'}),snap=async()=>JSON.parse(await p.locator('[data-p23-snapshot]').textContent());
async function route(scene,id){await p.evaluate(({scene,id})=>location.hash='#p02/history?'+new URLSearchParams({scene,...(id?{[scene==='warranty-detail'?'case':'session']:id}:{})}),{scene,id});await p.waitForSelector('.p23-app');await p.waitForTimeout(100);}
async function source(mode){await p.selectOption('[data-p23-source]',mode);await p.waitForFunction(()=>!document.querySelector('[data-p23=reload]:disabled'));}
async function test(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/?v=p23-edges');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
await test('Dates Apply-only; reset/cancel keep prior; bounds Vietnam 90 days',async()=>{await route('sessions');await source('fixture');await a('filter').first().click();await p.fill('#pick-from','10/09/2026');await p.fill('#pick-to','10/09/2026');await p.locator('.app-modal-host button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal((await snap()).filters.sessions.from,'2026-09-10');await a('filter').first().click();await p.locator('[data-reset]').click();await p.locator('.app-modal-host footer [data-cancel]').click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal((await snap()).filters.sessions.from,'2026-09-10');await a('filter').first().click();await p.fill('#pick-from','01/07/2026');assert.equal(await p.locator('.app-modal-host button[type=submit]').isDisabled(),true);assert.equal(await p.locator('.app-modal-host').count(),1);assert.match(await p.locator('.app-modal-host').innerText(),/Chọn ngày từ 02\/07\/2026 đến 30\/09\/2026/);await shot('date-validation');await p.keyboard.press('Escape');await p.waitForTimeout(100);await a('clear').click();});
await test('Scroll and focus restore by case ID; fallback Back has no fake caller loop',async()=>{await route('warranty');await p.locator('.p23-scroll').evaluate(e=>e.scrollTop=650);const row=p.locator('[data-p23-entity="BH-003"]');await row.scrollIntoViewIfNeeded();await row.focus();const y=await p.locator('.p23-scroll').evaluate(e=>e.scrollTop);await row.click();await a('back').first().click();await p.waitForSelector('[data-panel="P23.S01"]');assert.ok(Math.abs(await p.locator('.p23-scroll').evaluate(e=>e.scrollTop)-y)<2);assert.equal(await row.evaluate(e=>e===document.activeElement),true);await p.evaluate(()=>{history.replaceState(null,'','#p02/history?scene=session-detail&session=PQ-0003');dispatchEvent(new HashChangeEvent('hashchange'));});await p.waitForSelector('[data-panel="P23.S04"]');await a('back').first().click();await p.waitForSelector('[data-panel="P23.S03"]');assert.equal(await p.evaluate(()=>history.state?.p23From),undefined);await a('back').first().click();await p.frameLocator('iframe').locator('.history-link').first().waitFor();});
await test('Reload during typing/IME retains input identity and caret; newer focus not stolen',async()=>{await route('sessions');await source('fixture');await p.selectOption('[data-p23-outcome]','slow');await a('reload').click();await p.fill('#p23-search','PQ-0001');await p.locator('#p23-search').evaluate(e=>{window.p23TestInput=e;e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await p.waitForTimeout(800);assert.equal(await p.locator('#p23-search').evaluate(e=>e===window.p23TestInput&&e===document.activeElement),true);await p.locator('#p23-search').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await p.waitForTimeout(300);assert.equal(await p.locator('[data-p23-entity]').count(),1);assert.equal(await p.locator('#p23-search').evaluate(e=>e===document.activeElement),true);await a('clear').click();});
await test('Read response under picker deferred; Back closes overlay then updates data',async()=>{await a('reload').click();await a('filter').first().click();await p.waitForTimeout(800);assert.equal(await p.locator('.app-modal-host').count(),1);await p.goBack();await p.waitForTimeout(180);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await a('reload').isDisabled(),false);assert.equal(await p.locator('[data-p23-entity]').count(),3);});
await test('Read timeout preserves cache; late callbacks cannot change route',async()=>{await p.selectOption('[data-p23-outcome]','timeout');await a('reload').click();await p.clock.fastForward(15100);await p.waitForSelector('[data-p23=reload]:not(:disabled)');assert.match(await p.locator('.p23-app').innerText(),/Không tải lại được/);assert.equal(await p.locator('[data-p23-entity]').count(),3);await shot('read-timeout');await p.selectOption('[data-p23-outcome]','ready');});
await test('250/2000 notes and code with no spaces preserve raw; 10 long layouts',async()=>{await p.evaluate(async()=>{const m=await import('../shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(x=>x.id==='BH-001');m.writeWarrantyCase({...c,model:'M'.repeat(250),serial:'SN'+('X'.repeat(250)),events:[{id:'P23-LONG-1',label:'Đã tiếp nhận',day:'2026-09-10',time:'10:00',actor:'Tên '.repeat(100),description:'Tiếng Việt <>& 🌸\n'+('N'.repeat(2000))}]});});const metrics=[];for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const scene of ['warranty-detail','session-detail']){await route(scene,scene==='warranty-detail'?'BH-001':'PQ-0003');if(scene==='session-detail')await source('long');await p.waitForTimeout(80);const m=await p.locator('.p23-scroll').evaluate(e=>({overflow:e.scrollWidth>e.clientWidth+1,small:[...e.querySelectorAll('button')].filter(b=>b.getClientRects().length&&b.offsetHeight<44).length}));assert.equal(m.overflow,false);assert.equal(m.small,0);metrics.push({viewport:[width,height],scene,...m});await shot(scene+'-'+width);}}fs.writeFileSync(out+'/layout-long.json',JSON.stringify(metrics,null,2));await p.setViewportSize({width:494,height:950});await route('warranty-detail','BH-001');await p.getByRole('button',{name:'Xem đầy đủ ghi chú sự kiện',exact:true}).click();assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/N{2000}/);await shot('long-note-reader');await p.keyboard.press('Escape');await p.waitForTimeout(100);await p.evaluate(async()=>{(await import('../shared/warranty-cases.mjs')).resetWarrantyCases();});});
await test('Legacy P08 generic session retains its source; logout/back cannot restore P23',async()=>{await p.evaluate(()=>location.hash='#p02/history-list?panel=3&session=PQ-0001');await p.waitForSelector('.p08-app');assert.equal(await p.locator('.p23-app').count(),0);await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');await p.evaluate(()=>location.hash='#p02/profile');await p.waitForSelector('.p10-app');const logout=p.locator('[data-p10=logout]');await logout.click();await p.locator('.hn-action-dialog[open] [data-action-dialog="confirm"]').click();await p.waitForSelector('#username');await p.goBack();await p.waitForTimeout(200);assert.equal(await p.locator('.p23-app').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
