const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const before=process.argv.includes('--before'),out=path.resolve(process.env.NFC_R13_EVIDENCE_DIR||'handoff/P07/evidence/revision-13/'+(before?'before':'after'));fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),results=[];
 async function run(name,fn){const page=await browser.newPage({viewport:{width:494,height:1000},permissions:['clipboard-write','clipboard-read']});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const act=a=>page.locator(`[data-p07="${a}"]`).first(),snap=()=>page.locator('[data-p07-snapshot]').evaluate(e=>JSON.parse(e.textContent));
  try{await page.goto((process.env.PREVIEW_ORIGIN||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route="nfc"]');await fn({page,act,snap});assert.deepEqual(errors,[]);results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',error:e.message,errors});}finally{await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')}).catch(()=>{});await page.close();}
 }
 await run('conflict-detail',async({page,act})=>{await act('begin').click();await page.locator('.p07-tools>details>summary').click();await page.selectOption('[data-p07-scenario]','conflict');await page.click('[data-p07-demo-read]');await page.locator('[data-panel="P17.S03"]').waitFor();await act('exception-detail').click();await page.locator('#p07-detail-title').waitFor({timeout:3000});assert.equal(await page.locator('dialog[open]').count(),1);await page.keyboard.press('Escape');await page.locator('#p07-detail-title').waitFor({state:'detached'});assert.equal(await act('exception-detail').evaluate(e=>e===document.activeElement),true);});
 await run('picker-back',async({page,act})=>{await act('begin').click();await act('change-product').click();await page.locator('.p06-card[data-p06-item="fixture-item-HN12345"]').click();await page.locator('[data-panel="P07.S02"]').waitFor();await act('back').click();await page.waitForTimeout(150);assert.equal(await page.locator('[data-panel="P07.S01"]').count(),1,'One Back after selecting product returns to NFC list');});
 await run('picker-cancel-focus',async({page,act})=>{await act('begin').click();await act('change-product').click();await page.locator('[data-p06="back"]').click();await page.locator('[data-panel="P07.S02"]').waitFor();assert.equal(await act('change-product').evaluate(e=>e===document.activeElement),true,'Focus returns to product action');await act('back').click();await page.waitForTimeout(150);assert.equal(await page.locator('[data-panel="P07.S01"]').count(),1);});
 await run('copy-overlap',async({page,act})=>{await page.click('[data-p07-tag="fixture-tag-002"]');await act('copy').click();const m=await act('copy').evaluate(e=>{const b=e.getBoundingClientRect(),n=e.querySelector('.p07-copy-note').getBoundingClientRect();return {bottom:n.bottom,limit:b.bottom,left:n.left,start:b.left};});assert.ok(m.bottom<=m.limit+1&&m.left>=m.start-1,'Copy feedback must remain inside its touch target, not cover the next row');});
 if(!before){
 await run('picker-native-back',async({page,act,snap})=>{await act('begin').click();for(let i=0;i<3;i++){await act('change-product').click();await page.locator('.p06-card[data-p06-item="fixture-item-HN12345"]').click();await page.locator('[data-panel="P07.S02"]').waitFor();}await page.goBack();await page.locator('[data-panel="P07.S01"]').waitFor({timeout:3000});assert.equal((await snap()).itemId,'fixture-item-HN12345');});
 await run('copy-keyboard-late',async({page,act})=>{await page.click('[data-p07-tag="fixture-tag-002"]');await page.evaluate(()=>{window.copyCalls=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>{window.copyCalls++;return new Promise(r=>window.finishCopy=r);}}});});await act('copy').focus();await act('copy').press('Enter');assert.equal(await act('copy').evaluate(e=>document.activeElement===e),true);await act('copy').press('Enter');assert.equal(await page.evaluate(()=>window.copyCalls),1);await page.keyboard.press('Escape');await page.evaluate(()=>window.finishCopy());assert.equal(await page.locator('dialog[open]').count(),0);assert.equal(await page.locator('[data-p07-tag="fixture-tag-002"]').evaluate(e=>document.activeElement===e),true);});
 }
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results));if(!before&&results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();
