const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P19/evidence/revision-01/after';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(9000);
const a=name=>p.locator(`[data-p19="${name}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent()),pause=()=>p.waitForTimeout(180);
async function login(){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p19-tools').evaluate(e=>e.open=true);}
async function open(){await p.click('[data-p19-open]');await p.waitForSelector('.p19-app');}
async function input(value){if(!await p.locator('#p19-code').count())await p.click('[data-scan-action=manual]');await p.fill('#p19-code',value);await p.locator('#p19-manual-form button[type=submit]').click();}
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(name){await p.evaluate(async()=>{await document.fonts.ready;const e=document.querySelector('.p19-app .hn-scan-camera');if(e){const url=getComputedStyle(e).backgroundImage.match(/url\("?(.*?)"?\)/)?.[1];if(url)await new Promise((resolve,reject)=>{const i=new Image();i.onload=resolve;i.onerror=()=>reject(Error('Missing camera asset '+url));i.src=url;});}});await p.locator('.hn-screen').screenshot({path:out+'/'+name+'.png'});}
try{await login();
 await check('Four B19 panels render from isolated verified fixture',async()=>{for(const [i,scene]of ['scan','quantity','review','success'].entries()){await p.click(`[data-p19-demo=${scene}]`);await p.waitForSelector(`[data-panel="P19.S0${i+1}"]`);await pause();await shot('P19-S0'+(i+1)+'-494x950');if(scene==='quantity'){await p.keyboard.press('Escape');await pause();}}});
 await check('Empty review disabled; direct success route cannot fabricate success',async()=>{await open();assert.equal(await a('review').isDisabled(),true);await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-003&panel=4');await pause();assert.equal(await p.locator('[data-panel="P19.S04"]').count(),0);await open();});
 await check('Cancel quantity unchanged; invalid 0/negative/decimal/text/13; backdrop and focus trap',async()=>{await input('BOX-LK-0002-01');const d=p.locator('.p19-sheet');await d.evaluate(e=>e.parentElement.click());assert.equal(await d.count(),1);for(const v of ['0','-1','1.5','abc','13']){await p.fill('#p19-quantity',v);await d.locator('button[type=submit]').click();assert.equal(await p.locator('#p19-quantity').getAttribute('aria-invalid'),'true');assert.equal((await snap()).lines.length,0);}await p.keyboard.press('Tab');assert.equal(await d.evaluate(e=>e.contains(document.activeElement)),true);await d.getByRole('button',{name:'Hủy',exact:true}).click();await pause();assert.equal((await snap()).lines.length,0);assert.equal(await p.locator('.app-modal-host').count(),0);});
 await check('A01 unit1 plus box2 = 2 codes / 3 units; no stock mutation before Post',async()=>{await input('LK0001-HN001');await input('BOX-LK-0002-01');await p.locator('.p19-sheet button[type=submit]').click();await pause();await a('review').click();await pause();assert.deepEqual((await snap()).counts,{codes:2,quantity:3});assert.equal((await snap()).metrics.commits,0);await shot('interactive-review');});
 await check('Removal confirmation cancel and Browser Back preserve lines',async()=>{await a('remove').click();assert.equal(await p.locator('.app-modal-host').count(),1);await p.goBack();await pause();assert.equal((await snap()).lines.length,2);assert.equal(await p.locator('.app-modal-host').count(),0);});
 await check('Explicit rejection retains data; no success',async()=>{await p.selectOption('[data-p19-outcome]','error');await a('post').click();await p.waitForSelector('.hn-action-dialog');assert.equal((await snap()).receipt,null);await p.getByRole('button',{name:'Đóng',exact:true}).click();await pause();});
 await check('Timeout POSTED stays UNKNOWN; double submit locked; reconcile same request confirms once',async()=>{await p.selectOption('[data-p19-outcome]','timeout-posted');await a('post').evaluate(e=>{e.click();e.click();});await p.waitForSelector('.hn-action-dialog');const s=await snap();assert.equal(s.unknown,true);assert.equal(s.metrics.post,2);assert.equal(s.metrics.commits,1);assert.equal(await p.locator('[data-panel="P19.S04"]').count(),0);await shot('unknown');await p.getByRole('button',{name:'Để sau',exact:true}).click();await pause();await a('reconcile').click();await p.waitForSelector('[data-panel="P19.S04"]');const r=await snap();assert.equal(r.receipt.requestId,s.request.id);assert.equal(r.metrics.commits,1);assert.deepEqual(r.counts,{codes:2,quantity:3});await shot('interactive-success');});
 await check('Verified receipt appears in exact P09 case; closed case deep link blocked',async()=>{const id=(await snap()).receipt.id;await a('case').click();await p.waitForSelector('.p09-app');assert.match(await p.locator('.p09-app').innerText(),new RegExp(id));await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-002&panel=3');await pause();assert.match(await p.locator('.p19-app').innerText(),/Hồ sơ đã trả khách/);assert.equal(await a('post').count(),0);});
 await check('20 panel/viewport layouts fit494×950 and footer remains within shell',async()=>{for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});for(const [i,scene]of ['scan','quantity','review','success'].entries()){await p.click(`[data-p19-demo=${scene}]`);await p.waitForSelector(`[data-panel="P19.S0${i+1}"]`);await pause();const g=await p.locator('.hn-screen').evaluate(e=>{const body=e.querySelector('.p19-scroll'),f=e.querySelector('.p19-sheet-footer')||e.querySelector('.p19-footer'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return {w:e.offsetWidth,h:e.offsetHeight,overflow:body.scrollWidth>body.clientWidth+1,verticalOverflow:body.scrollHeight>body.clientHeight+1,footer:fr.bottom<=r.bottom+1&&fr.top>=r.top};});assert.deepEqual(g,{w:494,h:950,overflow:false,verticalOverflow:false,footer:true},JSON.stringify({scene,width,height,g}));await shot(`P19-S0${i+1}-${width}x${height}`);if(scene==='quantity'){await p.keyboard.press('Escape');await pause();}}}});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' browser groups PASS');
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
