const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const out=process.env.P14_EVIDENCE_DIR||'handoff/P14/evidence/revision-01';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);
const panel=n=>p.locator(`[data-panel="P14.S0${n}"]`),action=a=>p.locator(`[data-p14="${a}"]`),modal=()=>p.locator('.app-modal-host dialog');
const check=async(name,f)=>{await f();checks.push({name,status:'PASS'});console.log('PASS '+name);};
async function close(){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));}
async function mode(v){await p.locator('.p14-tools details').evaluate(e=>e.open=true);await p.selectOption('[data-p14-scenario]',v);await p.evaluate(()=>scrollTo(0,0));}
async function reload(){await p.goto('http://localhost:8766/flows/auth-session/');await p.reload();await p.locator('#username').waitFor();}
async function login(){await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home').waitFor({state:'visible'});}
async function shift(){await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await panel(3).waitFor();}
async function confirm(a,label){await action(a).click();await modal().getByRole('button',{name:label,exact:true}).click();}
async function layout(n){for(const [width,height] of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(80);const m=await p.evaluate(()=>{const app=document.querySelector('.p14-app'),s=app.closest('.screen,.hn-screen'),c=app.querySelector('.p14-scroll'),r=s.getBoundingClientRect();return {panel:app.dataset.panel,viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],scroller:[c.clientWidth,c.scrollWidth,c.clientHeight,c.scrollHeight],within:r.width<=innerWidth+1&&r.height<=innerHeight+1};});assert.deepEqual(m.shell,[494,950]);assert.equal(m.scroller[0],m.scroller[1]);assert.ok(m.within,JSON.stringify(m));metrics.push(m);await panel(n).locator('xpath=ancestor::*[contains(@class,"screen")][1]').screenshot({path:path.join(out,`S0${n}-${width}x${height}.png`)});}await p.setViewportSize({width:494,height:950});}
try{
await reload();await p.click('#forgot');
await check('A01 recovery route, no extra credential/OTP fields; required username',async()=>{await panel(1).waitFor();assert.equal(await panel(1).locator('input').count(),1);await p.locator('.p14-app button[type=submit]').click();assert.equal(await p.locator('#p14-username').getAttribute('aria-invalid'),'true');assert.equal(await panel(2).count(),0);await layout(1);});
await check('A02 recovery failure stays on form, text retained; modal Back/trap/backdrop',async()=>{await mode('error');await p.fill('#p14-username','minhanh');await p.locator('.p14-app button[type=submit]').click();await modal().waitFor();assert.equal(await panel(2).count(),0);await p.keyboard.press('Shift+Tab');assert.ok(await modal().evaluate(e=>e.contains(document.activeElement)));await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await modal().count(),1);await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await p.inputValue('#p14-username'),'minhanh');});
await check('A02 missing integration blocks receipt and no account existence disclosure',async()=>{await mode('blocked');await p.fill('#p14-username','unknown-user');await p.locator('.p14-app button[type=submit]').click();await modal().waitFor();assert.match(await modal().textContent(),/Chưa có kết nối/);assert.equal(await panel(2).count(),0);await close();});
await check('A02 successful fixture receipt uses username/system ID/time; fits six viewports',async()=>{await mode('ready');await p.fill('#p14-username','minhanh');await p.locator('.p14-app button[type=submit]').click();await panel(2).waitFor();assert.match(await panel(2).textContent(),/minhanh/);assert.match(await panel(2).textContent(),/RQ-/);await layout(2);await action('login').click();await p.locator('#username').waitFor();});
await check('long250/2000 usernames safely render, full reader retains Unicode and HTML text',async()=>{for(const name of ['Tên_dài_'.repeat(40),'Nguyễn🌸<script>'.repeat(140)]){await p.click('#forgot');await p.fill('#p14-username',name);await p.locator('.p14-app button[type=submit]').click();await panel(2).waitFor();const more=panel(2).locator('[data-hn-read-trigger]').first();await more.waitFor();await more.click();await modal().waitFor();assert.equal(await modal().locator('.app-modal-body').textContent(),name);await p.keyboard.press('Tab');assert.ok(await modal().evaluate(e=>e.contains(document.activeElement)));await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.equal(await panel(2).locator('script').count(),0);await action('login').click();}});
await login();await shift();
await check('A03 profile reaches S03; one real preview draft blocks end',async()=>{assert.ok(await action('end').isDisabled());assert.equal(await p.locator('[data-document]').count(),1);await layout(3);});
let originalId;
await check('A03 continue opens exact P04 draft and Back retains it',async()=>{originalId=await p.locator('[data-document]').getAttribute('data-document');await action('continue').click();await p.locator('[data-p04-note]').waitFor();await p.fill('[data-p04-note]','Ghi chú ca sáng — giữ nguyên 🌸');await p.goBack();await panel(3).waitFor();assert.equal(await p.locator('[data-document]').getAttribute('data-document'),originalId);});
await check('save confirmation Cancel and Escape preserve blocked shift',async()=>{await action('save').click();await modal().waitFor();assert.equal(await modal().getByRole('button',{name:'Hủy',exact:true}).count(),1);await close();assert.ok(await action('end').isDisabled());assert.ok(await action('save').evaluate(e=>document.activeElement===e));});
await check('A04 failed draft save retains source ID and blocks end',async()=>{await mode('error');await confirm('save','Lưu nháp');await modal().waitFor();assert.match(await modal().textContent(),/Chưa hoàn tất/);await close();assert.ok(await action('end').isDisabled());assert.equal(await p.locator('[data-document]').getAttribute('data-document'),originalId);});
await check('A04 save timeout blocks retry; reconciliation keeps request and unlocks end',async()=>{await mode('timeout-recorded');await confirm('save','Lưu nháp');await modal().waitFor();assert.match(await modal().textContent(),/Chưa xác định/);await close();assert.equal(await p.locator('[data-p14=save]:enabled').count(),0);assert.ok(await action('end').isDisabled());await action('check').click();await modal().getByRole('button',{name:'Đã hiểu',exact:true}).waitFor();assert.equal(await modal().getByRole('button',{name:'Hủy',exact:true}).count(),0);await modal().getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await action('end').isEnabled());});
await check('saved draft edited in P04 becomes unfinished again',async()=>{await action('continue').click();await p.locator('[data-p04-note]').waitFor();assert.equal(await p.inputValue('[data-p04-note]'),'Ghi chú ca sáng — giữ nguyên 🌸');await p.fill('[data-p04-note]','Ghi chú cập nhật sau lưu');await p.goBack();await panel(3).waitFor();assert.ok(await action('end').isDisabled());await mode('ready');await confirm('save','Lưu nháp');await modal().getByRole('button',{name:'Đã hiểu',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));});
await check('end failure leaves summary closed and saved draft intact',async()=>{await mode('error');await confirm('end','Kết thúc ca');await modal().waitFor();assert.match(await modal().textContent(),/Chưa hoàn tất/);await close();assert.equal(await panel(4).count(),0);assert.ok(await action('end').isEnabled());});
await check('A05 verified end shows aggregate30, preserves one draft and auth, fixed summary CTA',async()=>{await mode('ready');await confirm('end','Kết thúc ca');await panel(4).waitFor();assert.deepEqual(await p.locator('.p14-kpi strong').allTextContents(),['12','6','4','3','30']);assert.match(await p.locator('.p14-kpi.wide').textContent(),/5 lượt/);assert.equal(await p.locator('.p14-drafts strong').textContent(),'1');assert.ok(await action('logout').isVisible());await layout(4);});
await check('summary header, summary CTA and locked menu stay fixed while scrolling',async()=>{const y=await action('logout').evaluate(e=>e.getBoundingClientRect().y);await p.locator('.p14-scroll').evaluate(e=>e.scrollTop=1000);assert.equal(await action('logout').evaluate(e=>e.getBoundingClientRect().y),y);const dock=await action('logout').evaluate(e=>{const b=e.getBoundingClientRect(),s=document.querySelector('.p14-scroll').getBoundingClientRect();return {below:b.y>=s.bottom,width:b.width};});assert.ok(dock.below);assert.ok(dock.width>400);const c=await p.locator('.hn-nav').evaluate(e=>[getComputedStyle(e).backgroundColor,getComputedStyle(e).borderRadius,getComputedStyle(e.querySelector('.hn-scan-circle')).width]);assert.deepEqual(c,['rgba(255, 255, 255, 0.98)','23px 23px 0px 0px','62px']);await p.click('[data-tab=home]');await p.locator('#hn-home').waitFor({state:'visible'});await p.click('[data-tab=profile]');await p.click('[data-p10=shift]');await panel(4).waitFor();});
await check('Logout then Back/deep-link cannot restore summary or auth',async()=>{await p.locator('.hn-tools details').first().evaluate(e=>e.open=true);await p.click('#hn-logout');await p.locator('#username').waitFor();await p.goBack();await p.locator('#username').waitFor();assert.equal(await panel(4).count(),0);await p.evaluate(()=>location.hash='#p02/shift?panel=4');await p.locator('#username').waitFor();assert.equal(await panel(4).count(),0);});
await check('late recovery response after Back does not reopen receipt',async()=>{await p.click('#forgot');await p.fill('#p14-username','minhanh');await p.locator('.p14-app button[type=submit]').click();await action('back').click();await p.waitForTimeout(550);assert.equal(await panel(2).count(),0);await p.locator('#username').waitFor();});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({status:'PASS',checks,metrics,pageErrors:errors,viewportUnit:'CSS px',DPR:1,zoom:1,font:'Arial',timezone:'Asia/Ho_Chi_Minh',hardwareKeyboard:'NOT_RUN; viewport340x420 simulation only'},null,2));console.log('TOTAL '+checks.length);
}catch(e){fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));await p.screenshot({path:path.join(out,'failure.png')});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
