const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_UX_EVIDENCE_DIR||'handoff/P09/evidence/revision-10/ux');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],errors=[],metrics=[];p.on('pageerror',e=>errors.push(e.message));
const act=a=>p.locator(`[data-p09="${a}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p09-snapshot]').textContent()),panel=n=>p.locator(`[data-panel="P09.S0${n}"]`).waitFor();
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function audit(name){for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});const m=await p.locator('.p09-app').evaluate(a=>{const s=a.closest('.hn-screen'),sc=a.querySelector('.p09-scroll'),f=a.querySelector('.p09-footer'),d=s.querySelector('dialog[open]'),r=s.getBoundingClientRect(),dr=d?.getBoundingClientRect();return {shell:[s.offsetWidth,s.offsetHeight],overflow:sc.scrollWidth>sc.clientWidth+1,footer:!f||sc.getBoundingClientRect().bottom<=f.getBoundingClientRect().top+1,dialogInside:!d||dr.left>=r.left-1&&dr.right<=r.right+1&&dr.top>=r.top-1&&dr.bottom<=r.bottom+1,dialogOverflow:!!d&&d.scrollWidth>d.clientWidth+1,touch:[...s.querySelectorAll('.p09-header button,.p09-quick-filters button,#p09-fault-select,[data-p09=change-product],.p09-update-header [data-close],.p09-fault-picker header [data-cancel]')].filter(e=>e.offsetWidth).every(e=>e.offsetHeight>=44&&e.offsetWidth>=44),dialogFooter:!d||!d.querySelector('footer')||d.querySelector('footer').getBoundingClientRect().bottom<=dr.bottom+1};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.overflow&&m.footer&&m.dialogInside&&!m.dialogOverflow&&m.touch&&m.dialogFooter,JSON.stringify(m));metrics.push({name,width,height,...m});await shot(`${name}-${width}x${height}`);}await p.setViewportSize({width:494,height:1000});}
async function login(){await p.goto('http://127.0.0.1:8766/flows/auth-session/?review=p09-r10');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.click('[data-route=warranty]');await panel(1);}
try{await login();
await check('Quick filters and dialog share selection, query-scoped counts and Cancel semantics',async()=>{assert.deepEqual(await p.locator('.p09-quick-filters .p09-count').allTextContents(),['1','2','1','4']);await p.click('[data-p09-status="Đang kiểm tra"]');assert.equal(await p.locator('.p09-case').count(),2);await act('filter').click();assert.equal(await p.locator('.p08-picker input[value="Đang kiểm tra"]').isChecked(),true);await p.locator('.p08-picker input[value="Đã trả khách"]').check();await p.keyboard.press('Escape');assert.equal(await p.locator('[data-p09-status="Đang kiểm tra"]').getAttribute('aria-pressed'),'true');await p.click('[data-p09-status="Đang kiểm tra"]');assert.equal(await p.locator('.p09-case').count(),8);await p.fill('#p09-query','phuc an');assert.deepEqual(await p.locator('.p09-quick-filters .p09-count').allTextContents(),['0','0','1','0']);assert.equal(await p.locator('.p09-case').count(),1);await p.fill('#p09-query','');await audit('list');});
await check('Successful serial collapses scanner and focuses fault; invalid replacement retains product and draft',async()=>{await act('begin').click();await p.click('[data-scan-action=manual]');await p.fill('#p09-code','SN-XP420B-BK-0008');await p.locator('#p09-code').press('Enter');assert.equal(await p.locator('.hn-scan-entry').count(),0);assert.equal(await act('change-product').count(),1);assert.equal(await p.locator('#p09-fault-select').evaluate(e=>e===document.activeElement),true);await p.fill('[name=note]','Giữ ghi chú khi đổi mã');const prior=(await snap()).draft.item;await act('change-product').click();await p.fill('#p09-code','INVALID-serial');await p.locator('#p09-code').press('Enter');assert.deepEqual((await snap()).draft.item,prior);assert.equal(await act('intake').isDisabled(),true);await act('cancel-change').click();assert.equal(await p.locator('.hn-scan-entry').count(),0);assert.equal(await p.inputValue('[name=note]'),'Giữ ghi chú khi đổi mã');await audit('selected');});
await check('Searchable fault picker supports no accents, current choice, Other-only input and retained text',async()=>{await act('fault').click();await p.fill('.p09-fault-picker input[type=search]','khac');assert.equal(await p.locator('.p09-fault-picker .p08-options label:visible').count(),1);await p.locator('.p09-fault-picker input[value=other]').click();await p.fill('[name=faultOther]','Tiếng kêu lạ khi chạy máy');assert.equal(await act('intake').isEnabled(),true);await act('fault').click();assert.equal(await p.locator('.p09-fault-picker input[value=other]').isChecked(),true);await p.locator('.p09-fault-picker input[value=usb]').click();assert.equal(await p.locator('[name=faultOther]').count(),0);assert.match(await p.locator('#p09-fault-select').textContent(),/Thay đổi/);await act('fault').click();await p.locator('.p09-fault-picker input[value=other]').click();assert.equal(await p.inputValue('[name=faultOther]'),'Tiếng kêu lạ khi chạy máy');await audit('other');await act('fault').click();await audit('fault-picker');await p.keyboard.press('Escape');});
await check('Profile sections keep all data and long content readers retain exact text and Back focus',async()=>{await act('back').click();await p.click('[data-p09-case=BH-007]');assert.deepEqual(await p.locator('.p09-detail-card>h2').allTextContents(),['Thông tin tiếp nhận','Xử lý sửa chữa']);const long='Ghi chú Unicode Hoa Nam 🌸\n'+('Thiết bị <kiểm tra> & '+ 'x'.repeat(250)+'\n').repeat(9);await p.evaluate(async text=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(c=>c.id==='BH-007');m.writeWarrantyCase({...c,note:text});},long);await p.click('[data-p09-tab=parts]');await p.click('[data-p09-tab=info]');await p.getByRole('button',{name:'Xem đầy đủ ghi chú',exact:true}).click();await p.locator('.hn-action-dialog[open]').waitFor();assert.ok((await p.locator('.hn-action-dialog[open]').innerText()).includes(long));assert.equal(await p.locator('dialog[open]').count(),1);await audit('reader');await p.goBack();await p.locator('.hn-action-dialog[open]').waitFor({state:'detached'});assert.equal(await p.getByRole('button',{name:'Xem đầy đủ ghi chú',exact:true}).evaluate(e=>e===document.activeElement),true);await audit('profile-long');});
await check('Update dialog fits six sizes, explains disabled save, validates fields and retains draft on Back',async()=>{await act('update').click();assert.match(await p.locator('.p09-update-context').textContent(),/BH-007.*SN-XP420B-206/);assert.equal(await p.locator('.p09-update-dialog [name=result]').evaluate(e=>e===document.activeElement),true);assert.match(await p.locator('#p09-save-hint').textContent(),/Nhập kết quả/);await audit('update-empty');await p.fill('.p09-update-dialog [name=result]','   ');assert.equal(await p.locator('.p09-update-dialog [name=result]').getAttribute('aria-invalid'),'true');await p.fill('.p09-update-dialog [name=result]','Đã cấu hình cổng USB, kiểm tra in ổn định.');await p.goBack();await p.locator('.p09-update-dialog').waitFor({state:'detached'});await act('update').click();assert.match(await p.inputValue('.p09-update-dialog [name=result]'),/Đã cấu hình/);await p.click('.p09-update-dialog [type=submit]');await panel(4);assert.equal((await snap()).writes,1);await audit('result');await act('list').click();await panel(1);assert.equal(await p.locator('[data-p09-case=BH-007].p09-case-returned').count(),1);});
await check('Filtered-out updated case has direct view without changing caller filter, query or tab Back',async()=>{await p.click('[data-p09-status="Đang kiểm tra"]');await p.fill('#p09-query','BH-001');await p.click('[data-p09-case=BH-001]');await p.click('[data-p09-tab=events]');await act('update').click();await p.fill('.p09-update-dialog [name=result]','Đã sửa chữa và kiểm tra');await p.click('.p09-update-dialog [type=submit]');await panel(4);await act('list').click();await panel(1);assert.equal(await p.inputValue('#p09-query'),'BH-001');assert.equal(await p.locator('[data-p09-status="Đang kiểm tra"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('.p09-case').count(),0);await act('returned-case').click();await panel(3);assert.match(await p.locator('.p09-case-summary').textContent(),/BH-001/);await act('back').click();await panel(1);assert.equal(await p.inputValue('#p09-query'),'BH-001');await shot('filtered-return');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));
}catch(e){await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await b.close();}})();
