const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.SYNC_P0809_EVIDENCE_DIR||'handoff/dialog-sync-2026-09-28/p08-p09');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:494,height:1000},permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const feedback=()=>page.locator('.hn-action-dialog[open]'),w=a=>page.locator(`[data-p09="${a}"]`).first(),h=a=>page.locator(`[data-p08="${a}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent());
const panel=p=>page.locator(`[data-panel="${p}"]`).waitFor();
async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home:visible').waitFor();}
async function route(hash,selector){await page.evaluate(hash=>location.hash=hash,hash);await page.locator(selector).waitFor();}
async function historyPage(business='',p=1){await route('#p02/history-list?panel='+p+(business?'&business='+business:''),'.p08-app');}
async function warranty(id='BH-007'){await route('#p02/warranty?panel=1','.p09-app');await page.fill('#p09-query',id);await page.click(`[data-p09-case="${id}"]`);await panel('P09.S03');}
async function mode(value){if(await page.locator('.p09-tools details').getAttribute('open')===null)await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]',value);}
async function save(value){await w('update').click();await page.fill('.p09-update-dialog [name=result]',value);await page.click('.p09-update-dialog [type=submit]');}
async function dismiss(){await feedback().locator('[data-action-dialog=confirm]').click();await feedback().waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP08Action&&!history.state?.hnP09Action);}
async function capture(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function audit(name,scope='.p09-scroll',expectFit=false){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(({scope})=>{const s=document.querySelector('.hn-screen'),e=document.querySelector(scope),d=s.querySelector('dialog[open]'),r=s.getBoundingClientRect(),dr=d?.getBoundingClientRect(),f=s.querySelector('.p09-footer')||s.querySelector('.hn-nav'),hr=s.querySelector('header').getBoundingClientRect();return {viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],pageOverflow:document.documentElement.scrollWidth>innerWidth,horizontal:e.scrollWidth>e.clientWidth+1,scroll:[e.scrollTop,e.clientHeight,e.scrollHeight],header:hr.top,footer:f?.getBoundingClientRect().top,inside:!d||dr.left>=r.left-1&&dr.right<=r.right+1&&dr.top>=r.top-1&&dr.bottom<=r.bottom+1,focusIn:!d||d.contains(document.activeElement),overlay:s.querySelectorAll('.app-modal-host').length};},{scope});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.pageOverflow&&!m.horizontal&&m.inside&&m.focusIn&&m.overlay<=1,JSON.stringify(m));if(expectFit)assert.ok(m.scroll[2]<=m.scroll[1]+1,JSON.stringify(m));metrics.push({name,...m});await capture(name);return m;}
async function matrix(name,scope,fit=false){for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width,height});await audit(name+'-'+width+'x'+height,scope,fit);}await page.setViewportSize({width:494,height:1000});}
try{
await login();
await check('P08 all six pages: Back/Cancel/Reset only draft; Apply commits; no backdrop close',async()=>{for(const [business,p]of [['',1],['',4],['documents',1],['nfc',1],['warranty',1],['sessions',1]]){await historyPage(business==='documents'?'':business,p);if(business==='documents')await route('#p02/history-list?panel=1&scope=documents','.p08-app');const hash=await page.evaluate(()=>location.hash),before=await page.locator('.p08-filter-summary').textContent();await h('filter').click();await page.click('[data-reset]');const chosen=await page.locator('[name=from]').inputValue();await page.goBack();await page.locator('.p08-picker').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>location.hash),hash);assert.equal(await page.locator('.p08-filter-summary').textContent(),before);await h('filter').click();await page.click('[data-reset]');const host=await page.locator('.app-modal-host').boundingBox();await page.mouse.click(host.x+2,host.y+2);assert.equal(await page.locator('.p08-picker').count(),1);await page.click('.p08-picker [type=submit]');await page.waitForFunction(chosen=>document.querySelector('.p08-filter-summary')?.textContent.includes(chosen),chosen);await h('filter').click();await page.click('[data-cancel]');await page.locator('.p08-picker').waitFor({state:'detached'});await h('clear').click();assert.match(await page.locator('.p08-filter-summary').textContent(),/Tất cả ngày/);}});
await check('P08 clipboard success: dialog only, focus trap, wheel/background stable and six sizes',async()=>{await route('#p02/history-list?panel=2&record=LS-0001','.p08-app');await h('copy').click();await feedback().waitFor();assert.match(await feedback().textContent(),/Đã sao chép/);assert.equal(await page.locator('.p08-feedback').count(),0);await matrix('p08-copy-dialog','.p08-scroll');const before=await page.locator('.p08-scroll').evaluate(e=>e.scrollTop);const host=await page.locator('.app-modal-host').boundingBox();await page.mouse.move(host.x+3,host.y+5);await page.mouse.wheel(0,1000);assert.equal(await page.locator('.p08-scroll').evaluate(e=>e.scrollTop),before);await page.keyboard.press('Tab');assert.equal(await feedback().evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Escape');await feedback().waitFor({state:'detached'});assert.equal(await page.locator('#p08-copy-document').evaluate(e=>document.activeElement===e),true);});
await check('P08 clipboard failure remains on exact record; late clipboard reply does not open on other tab',async()=>{await page.evaluate(()=>navigator.clipboard.writeText=async()=>{throw Error('denied');});await h('copy').click();await feedback().waitFor();assert.match(await feedback().textContent(),/Không thể sao chép/);await page.goBack();await feedback().waitFor({state:'detached'});await page.evaluate(()=>{navigator.clipboard.writeText=()=>new Promise(r=>window.__clipboardResolve=r);});await h('copy').click();await page.click('[data-p08-tab=timeline]');await page.evaluate(()=>window.__clipboardResolve());assert.equal(await feedback().count(),0);assert.equal(await page.locator('[data-p08-tab=timeline]').getAttribute('aria-selected'),'true');});
await check('P08 four panel layouts and persistent empty/loading/source states stay in content',async()=>{for(const p of [1,2,3,4]){await route('#p02/history-list?panel='+p,'.p08-app');await matrix('p08-panel-'+p,'.p08-scroll');}await route('#p02/history-list?panel=1','.p08-app');await page.selectOption('[data-p08-scenario]','loading');assert.match(await page.locator('.p08-state').textContent(),/Đang tải/);assert.equal(await feedback().count(),0);await page.selectOption('[data-p08-scenario]','empty');assert.match(await page.locator('.p08-state').textContent(),/Không có kết quả/);await page.selectOption('[data-p08-scenario]','error');assert.match(await page.locator('.p08-state').textContent(),/Không tải được/);await h('retry').click();assert.equal(await page.locator('.p08-row').count(),6);});
await check('P09 intake confirms Hủy/named action; cancel/backdrop/Back send no request; field validation remains local',async()=>{await login();await route('#p02/warranty?panel=2','.p09-app');await page.click('[data-scan-action=manual]');await page.fill('#p09-code','XP-420B');await page.press('#p09-code','Enter');assert.match(await page.locator('#p09-code-feedback').textContent(),/SKU/);assert.equal(await feedback().count(),0);await page.fill('#p09-code','HN12345');await page.press('#p09-code','Enter');await w('fault').click();await page.click('.p09-fault-picker input[value=power-off]');await w('intake').click();assert.equal(await page.locator('.p09-dialog [data-cancel]').evaluate(e=>e===document.activeElement),true);assert.equal(await page.locator('.p09-dialog [type=submit]').textContent(),'Mở hồ sơ');await matrix('p09-intake-confirm','.p09-scroll');const host=await page.locator('.app-modal-host').boundingBox();await page.mouse.click(host.x+2,host.y+2);assert.equal(await page.locator('.p09-dialog').count(),1);await page.goBack();await page.locator('.p09-dialog').waitFor({state:'detached'});assert.equal((await snap()).request,null);await w('intake').click();await page.click('.p09-dialog [data-cancel]');assert.equal((await snap()).writes,0);});
await check('P09 failed update: form replaced by one feedback dialog; continuation restores draft/request; double submit writes once',async()=>{await login();await warranty();await mode('error');await save('Đã thay dây nguồn và kiểm tra máy');await feedback().waitFor();assert.match(await feedback().textContent(),/Chưa hoàn tất thao tác/);assert.equal(await page.locator('.p09-update-dialog,.p09-feedback,.p09-update-status').count(),0);const before=await snap();assert.equal(before.writes,0);await matrix('p09-update-failure','.p09-scroll');await dismiss();await page.locator('.p09-update-dialog').waitFor();assert.equal(await page.inputValue('.p09-update-dialog [name=result]'),'Đã thay dây nguồn và kiểm tra máy');assert.equal((await snap()).request.id,before.request.id);await page.keyboard.press('Escape');await mode('ready');await w('update').click();await page.locator('.p09-update-dialog [type=submit]').evaluate(e=>{e.click();e.click();});await panel('P09.S04');assert.equal((await snap()).writes,1);assert.equal((await snap()).receipt.requestId,before.request.id);assert.equal(await feedback().count(),0);});
await check('P09 short result naturally fits; wheel does not move header/footer/content at all six sizes',async()=>{await matrix('p09-result','.p09-scroll',true);for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width,height});const before=await audit('wheel-before-'+width,'.p09-scroll',true);await page.locator('.p09-success').hover();await page.mouse.wheel(0,1000);const after=await audit('wheel-after-'+width,'.p09-scroll',true);assert.deepEqual(after.scroll,before.scroll);assert.equal(after.header,before.header);assert.equal(after.footer,before.footer);}await page.setViewportSize({width:494,height:1000});});
await check('P09 UNKNOWN dialog defers with same request; Back retains pending context; reconcile confirms exactly once',async()=>{await login();await warranty();await mode('unknown');await save('Đã kiểm tra nguồn');await feedback().waitFor();assert.match(await feedback().textContent(),/Chưa xác định kết quả/);assert.equal(await feedback().locator('[data-action-dialog=cancel]').textContent(),'Để sau');assert.equal(await feedback().locator('[data-action-dialog=confirm]').textContent(),'Đối chiếu');const before=(await snap()).request;await feedback().locator('[data-action-dialog=cancel]').click();await feedback().waitFor({state:'detached'});assert.equal(await w('update').isDisabled(),true);assert.deepEqual((await snap()).request,before);await w('back').click();await panel('P09.S01');assert.deepEqual((await snap()).request,before);await w('reconcile').evaluate(e=>{e.click();e.click();});await panel('P09.S04');assert.equal((await snap()).writes,1);assert.equal((await snap()).receipt.requestId,before.id);});
await check('P09 UNKNOWN confirm reconciles without stacked overlays; native Back closes notification first',async()=>{await login();await warranty('BH-003');await mode('unknown');await save('Đã xử lý');await feedback().waitFor();const hash=await page.evaluate(()=>location.hash),request=(await snap()).request;await page.goBack();await feedback().waitFor({state:'detached'});assert.equal(await page.evaluate(()=>location.hash),hash);assert.deepEqual((await snap()).request,request);await w('reconcile').click();await panel('P09.S04');assert.equal((await snap()).writes,1);});
await check('P09 verified new intake announces receipt, one dialog, no Hủy; UNKNOWN confirm reconciles once',async()=>{await login();await route('#p02/warranty?panel=2','.p09-app');await page.click('[data-scan-action=manual]');await page.fill('#p09-code','SN-XP420B-BK-0008');await page.press('#p09-code','Enter');await w('fault').click();await page.click('.p09-fault-picker input[value=power-off]');await w('intake').click();await page.click('.p09-dialog [type=submit]');await feedback().waitFor();await panel('P09.S03');assert.match(await feedback().textContent(),/Đã tiếp nhận bảo hành.*BH-009/s);assert.equal(await feedback().locator('[data-action-dialog=cancel]').count(),0);assert.equal((await snap()).writes,1);await capture('p09-intake-success');await dismiss();await mode('unknown');await save('Đã sửa chữa');await feedback().waitFor();const request=(await snap()).request;await feedback().locator('[data-action-dialog=confirm]').evaluate(e=>{e.click();e.click();});await panel('P09.S04');assert.equal((await snap()).writes,2);assert.equal((await snap()).receipt.requestId,request.id);assert.equal(await feedback().count(),0);});
await check('P09 long result has a bounded preview, full reader and accessible footer',async()=>{await login();await warranty();const text='Đã kiểm tra nguồn điện, đầu in, kết nối và chạy thử liên tục. '.repeat(3).slice(0,195);await save(text);await panel('P09.S04');const field=page.locator('.p09-result-table [data-hn-readable="Kết quả sửa chữa"]');await field.waitFor();await page.waitForTimeout(80);const button=field.locator('xpath=following-sibling::button[1]');assert.ok(await button.isVisible());await button.click();await page.locator('.hn-readable-dialog').waitFor();assert.equal(await page.locator('.hn-readable-dialog .app-modal-body p').textContent(),text);await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnAppReadable);await page.locator('.p09-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await audit('p09-long-result');assert.equal(await w('list').isVisible(),true);await w('view').click();assert.equal(await page.locator('[data-p09=update]').isEnabled(),true);});
await check('P09 closed case remains read only; dataset and invalid deep link safe',async()=>{await login();await warranty('BH-002');assert.equal(await w('update').isDisabled(),true);await route('#p02/warranty?panel=4&case=BH-002','[data-panel="P09.S03"]');assert.equal(await page.locator('[data-panel="P09.S04"]').count(),0);await route('#p02/warranty?panel=3&case=MISSING','.p09-app');await feedback().waitFor();assert.match(await feedback().textContent(),/Không tìm thấy hồ sơ/);await dismiss();await panel('P09.S01');assert.equal(await page.locator('.p09-case').count(),1);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors,production:'NOT_RUN',hardware:'NOT_RUN'},null,2));
}catch(error){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,metrics,errors,error:error.stack},null,2));throw error;}finally{await browser.close();}})();
