const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {mockGeography}=require('./outbound_geography_helpers.cjs');
const out=process.env.CREATE_EVIDENCE_DIR||'handoff/P12/evidence/revision-08';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),p=await browser.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);p.setDefaultTimeout(15000);
const a=n=>p.locator('[data-p12="'+n+'"]'),dialog=()=>p.locator('.p12-supplier-picker'),body=()=>dialog().locator('.app-modal-body');
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function settled(){await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);await dialog().waitFor({state:'detached'});}
async function open(){await a('supplier').click();await dialog().waitFor();}
async function cancel(){await dialog().locator('footer [data-cancel]').click();await settled();}
async function shot(name){await p.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function geometry(){return dialog().evaluate(d=>{const r=e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height,bottom:b.bottom,right:b.right}},f=d.querySelector('form'),s=d.querySelector('.app-modal-body');return {dialog:r(d),form:r(f),header:r(d.querySelector('header')),search:r(d.querySelector('.hn-choice-search-dock')),body:r(s),footer:r(d.querySelector('footer')),buttons:[...d.querySelectorAll('footer button')].map(r),shell:r(document.querySelector('.hn-screen')),overflow:[d.scrollHeight-d.clientHeight,f.scrollHeight-f.clientHeight,s.scrollWidth-s.clientWidth],buttonHeights:[...d.querySelectorAll('footer button')].map(e=>e.offsetHeight)};});}
function contains(outer,inner){assert.ok(inner.x>=outer.x-1&&inner.right<=outer.right+1&&inner.y>=outer.y-1&&inner.bottom<=outer.bottom+1,JSON.stringify({outer,inner}));}
try{
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForFunction(()=>location.hash==='#home');await p.click('[data-tab=documents]');await a('create').click();
 await check('Form uses read-only metadata,3 compact operation tiles and unchanged200-char policy',async()=>{assert.equal(await p.locator('#p12-warehouse').textContent(),'Kho Hoa Nam');assert.equal(await p.locator('#p12-warehouse').evaluate(e=>e.tagName),'OUTPUT');assert.equal(await p.locator('#p12-date').textContent(),'Cấp khi tạo phiếu');assert.equal(await p.locator('[data-p12-create-type]').count(),3);assert.equal(await p.locator('#p12-note').getAttribute('maxlength'),'200');assert.equal(await p.locator('#p12-note').evaluate(e=>e.offsetHeight),112);assert.equal(await p.locator('.hn-screen').evaluate(e=>[e.offsetWidth,e.offsetHeight].join('x')),'494x950');});
 await check('Six viewports: short form fits; supplier header/search/footer stay fixed and buttons fully inside',async()=>{
  for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});const form=await p.locator('.p12-scroll').evaluate(e=>({h:e.clientHeight,sh:e.scrollHeight,w:e.clientWidth,sw:e.scrollWidth}));assert.ok(form.sh<=form.h+1,JSON.stringify(form));assert.equal(form.w,form.sw);await shot('create-'+width+'x'+height);await open();const top=await geometry();contains(top.shell,top.dialog);contains(top.dialog,top.form);for(const b of top.buttons)contains(top.footer,b);assert.ok(top.overflow.every(n=>n<=1));assert.deepEqual(top.buttonHeights,[52,52]);assert.ok(Math.abs(top.buttons[0].width-top.buttons[1].width)<1);assert.ok(await dialog().locator('input[type=search]').evaluate(e=>e===document.activeElement));await body().evaluate(e=>e.scrollTop=e.scrollHeight);const bottom=await geometry();for(const k of ['header','search','footer','buttons'])assert.deepEqual(bottom[k],top[k],k);const last=await dialog().locator('.p08-options label').last().boundingBox();assert.ok(last.y+last.height<=bottom.body.bottom+1);assert.ok(last.y>=bottom.body.y);metrics.push({viewport:[width,height],form,top,bottom});await shot('supplier-bottom-'+width+'x'+height);await cancel();}await p.setViewportSize({width:494,height:950});
 });
 await check('Cancel/Escape/Back discard supplier drafts, restore trigger and keep note; Apply commits exactly selected option',async()=>{
  await p.fill('#p12-note','Giữ ghi chú qua bộ chọn nhà cung cấp.');const original=await p.locator('#p12-supplier-value').textContent();
  for(const action of ['cancel','escape','back']){await open();await dialog().locator('input[name=choice]').last().check();assert.equal(await p.locator('#p12-supplier-value').textContent(),original);if(action==='cancel')await cancel();else{if(action==='escape')await p.keyboard.press('Escape');else await p.goBack();await settled();}assert.equal(await p.locator('#p12-supplier-value').textContent(),original);assert.ok(await a('supplier').evaluate(e=>e===document.activeElement));assert.match(await p.inputValue('#p12-note'),/Giữ ghi chú/);}
  await open();await dialog().locator('input[type=search]').fill('thanh cong');assert.equal(await dialog().locator('.p08-options label:visible').count(),1);await dialog().locator('.p08-options label:visible input').check();assert.match(await dialog().locator('.hn-choice-selection').textContent(),/Thành Công/);await dialog().locator('input[type=search]').fill('khong co nha cung cap');assert.ok(await dialog().locator('[data-empty]').isVisible());assert.match(await dialog().locator('.hn-choice-selection').textContent(),/Thành Công/);await shot('supplier-search-empty-keeps-selection');await dialog().locator('[type=submit]').click();await settled();assert.equal(await p.locator('#p12-supplier-value').textContent(),'Công ty Thành Công');assert.match(await p.inputValue('#p12-note'),/Giữ ghi chú/);
 });
 await check('Backdrop,focus trap and keyboard selection cannot scroll or activate background',async()=>{
  await open();assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert));const before=await p.locator('.p12-scroll').evaluate(e=>e.scrollTop);await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await dialog().locator('header button').focus();await p.keyboard.press('Shift+Tab');assert.ok(await dialog().locator('[type=submit]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');assert.ok(await dialog().locator('header button').evaluate(e=>e===document.activeElement));await p.mouse.wheel(0,400);assert.equal(await p.locator('.p12-scroll').evaluate(e=>e.scrollTop),before);await p.keyboard.press('Escape');await settled();assert.equal(await p.locator('#hn-destination').evaluate(e=>e.inert),false);
 });
 await check('Long supplier name and many matches wrap in body without pushing footer or clipping buttons',async()=>{
  await p.evaluate(async()=>{const {openChoiceDialog}=await import('/flows/shared/choice-dialog.mjs');const {INBOUND_SUPPLIERS}=await import('/flows/inbound/catalogue.mjs');const options=INBOUND_SUPPLIERS.map((s,i)=>({...s,name:i===0?'Công ty Thương mại và Thiết bị Hoa Nam '.repeat(30):s.name}));window.stressChoice=openChoiceDialog({screen:document.querySelector('.hn-screen'),tools:document.querySelector('.hn-tools'),title:'Nhà cung cấp',options,value:options[0].id,className:'p12-supplier-picker',fixedSearch:true,selectionSummary:true,initialFocus:'input[type=search]',onApply:()=>{},onClose:()=>{}});});await dialog().locator('input[type=search]').fill('Thương mại');await dialog().locator('.p08-options label:visible input').check();await body().evaluate(e=>e.scrollTop=e.scrollHeight);const g=await geometry();contains(g.dialog,g.form);for(const b of g.buttons)contains(g.footer,b);assert.ok(g.overflow.every(n=>n<=1));assert.match(await dialog().locator('.hn-choice-selection').textContent(),/Thương mại/);await shot('supplier-long-name');await cancel();
 });
 await check('Outbound/warranty reuse owner flows and both Back paths retain the P12 note',async()=>{
  const note=await p.inputValue('#p12-note');await p.click('[data-p12-create-type=outbound]');await p.locator('[data-panel="P05.S01"]').waitFor();await p.click('[data-p05=back]');await p.locator('#p12-note').waitFor();assert.equal(await p.inputValue('#p12-note'),note);await p.click('[data-p12-create-type=warranty]');await p.locator('[data-panel="P09.S02"]').waitFor();await p.goBack();await p.locator('#p12-note').waitFor();assert.equal(await p.inputValue('#p12-note'),note);
 });
 await check('Selected supplier/note reach the existing inbound owner without recording or changing inventory',async()=>{
  await a('continue').click();await p.locator('[data-panel="P04.S02"]').waitFor();const snapshot=JSON.parse(await p.locator('[data-p04-snapshot]').textContent());assert.equal(snapshot.document.supplier,'Công ty Thành Công');assert.match(snapshot.document.note,/Giữ ghi chú/);assert.equal(snapshot.metrics.recordCalls,0);assert.equal(snapshot.metrics.inventoryDelta,0);await p.goBack();await p.locator('#p12-note').waitFor();
 });
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'create-results.json'),JSON.stringify({checks,metrics,errors,visualAcceptance:'NOT_GRANTED'},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'create-failure.json'),JSON.stringify({error:e.message,checks,metrics,errors},null,2));await shot('create-failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
