const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.SECURITY_LAYOUT_EVIDENCE_DIR||'handoff/P11/evidence/revision-03/layout-dialog');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const act=a=>page.locator(`[data-p11="${a}"]`).first(),dlg=()=>page.locator('.p11-dialog');
const sizes=[[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]];
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function settled(){await page.waitForFunction(()=>!history.state?.hnSecurityDialog);}
async function scenario(s){await page.locator('.p11-tools details').evaluate(e=>e.open=true);await page.selectOption('#p11-scenario',s);await page.waitForFunction(()=>document.querySelector('.p11-app').getAttribute('aria-busy')==='false');await page.evaluate(()=>scrollTo(0,0));}
async function revoke(){await page.locator('[data-p11-revoke]').click();await dlg().locator('[data-p11=confirm]').click();await page.locator('.p11-dialog[data-tone=success]').waitFor();}
async function measure(){return page.evaluate(()=>{const s=document.querySelector('.p11-scroll'),shell=document.querySelector('.hn-screen'),body=s.getBoundingClientRect(),head=document.querySelector('.p11-header').getBoundingClientRect(),footer=(document.querySelector('.p11-footer')||document.querySelector('.hn-nav')).getBoundingClientRect();return {viewport:[innerWidth,innerHeight],shell:[shell.offsetWidth,shell.offsetHeight],height:s.clientHeight,content:s.scrollHeight,scroll:s.scrollTop,pageScroll:scrollY,head:head.top,body:body.top,footer:footer.top};});}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-tab=profile]');await page.click('[data-p10=security]');await page.click('[data-p10=password]');await page.fill('#p11-current','preview');await page.fill('#p11-next','preview3');await page.fill('#p11-confirm','preview3');await page.click('[data-p11-save]');await page.locator('[data-panel="P11.S03"]').waitFor();
await check('S03 fits and real mouse wheel cannot move content/header/footer/page in six viewports',async()=>{for(const [w,h]of sizes){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(80);const before=await measure();assert.ok(before.content<=before.height+1,JSON.stringify(before));await page.locator('.p11-summary').hover();await page.mouse.wheel(0,1200);await page.waitForTimeout(180);assert.deepEqual(await measure(),before);await page.mouse.wheel(0,-1200);await page.waitForTimeout(180);assert.deepEqual(await measure(),before);metrics.push({kind:'success-fit',...before});await shot(`success-${w}x${h}`);}});
await page.setViewportSize({width:494,height:1000});await act('back').click();await page.click('[data-p10=sessions]');await page.locator('[data-p11-revoke]:enabled').waitFor();
await check('Confirmation dialog stays inside app with locked background and explicit cancel in six viewports',async()=>{for(const [w,h]of sizes){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>scrollTo(0,0));await page.locator('[data-p11-revoke]').click();await dlg().waitFor();const before=await measure();const bounds=await page.evaluate(()=>{const s=document.querySelector('.hn-screen').getBoundingClientRect(),d=document.querySelector('.p11-dialog').getBoundingClientRect();return {within:d.left>=s.left&&d.right<=s.right+1&&d.top>=s.top&&d.bottom<=s.bottom+1,overlay:document.querySelectorAll('.app-modal-host').length};});assert.ok(bounds.within);assert.equal(bounds.overlay,1);await dlg().locator('h2').hover();await page.mouse.wheel(0,700);await page.waitForTimeout(140);assert.deepEqual(await measure(),before);await page.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dlg().count(),1);await page.keyboard.press('Shift+Tab');assert.ok(await dlg().locator('[data-p11=confirm]').evaluate(e=>e===document.activeElement));await shot(`confirm-${w}x${h}`);await dlg().locator('[data-p11=cancel]').click();await settled();assert.equal(await page.locator('[data-session-row]').count(),2);assert.ok(await page.locator('[data-p11-revoke]').evaluate(e=>e===document.activeElement));metrics.push({kind:'confirm-dialog',...before,...bounds});}});
await page.setViewportSize({width:494,height:1000});
await check('Verified revoke uses one success dialog and no inline toast; acknowledgment preserves result',async()=>{await revoke();assert.equal(await page.locator('.app-modal-host').count(),1);assert.equal(await page.locator('.p11-message').count(),0);assert.equal(await dlg().locator('button').count(),1);assert.equal(await dlg().locator('button').textContent(),'Đã hiểu');assert.equal(await page.locator('[data-session-row]').count(),1);await page.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dlg().count(),1);for(const [w,h]of sizes){await page.setViewportSize({width:w,height:h});const ok=await dlg().evaluate(d=>{const a=document.querySelector('.hn-screen').getBoundingClientRect(),r=d.getBoundingClientRect();return r.top>=a.top&&r.bottom<=a.bottom+1&&r.left>=a.left&&r.right<=a.right+1;});assert.ok(ok);await shot(`result-${w}x${h}`);}await page.setViewportSize({width:494,height:1000});await page.keyboard.press('Enter');await settled();assert.equal(await dlg().count(),0);assert.equal(await page.locator('[data-session-row]').count(),1);assert.ok(await page.locator('.p11-header h1').evaluate(e=>e===document.activeElement));await shot('sessions-after-ack');});
await check('Escape closes result without undo; Back closes dialog before route navigation',async()=>{await scenario('baseline');await revoke();await page.keyboard.press('Escape');await settled();assert.equal(await page.locator('[data-session-row]').count(),1);await scenario('baseline');await revoke();await page.goBack();await settled();assert.equal(await dlg().count(),0);assert.equal(await page.locator('[data-panel="P11.S04"]').count(),1);assert.equal(await page.locator('[data-session-row]').count(),1);});
await check('General revoke failure is a dialog and leaves target intact',async()=>{await scenario('revoke-failed');await page.locator('[data-p11-revoke]').click();await dlg().locator('[data-p11=confirm]').click();await page.locator('.p11-dialog[data-tone=error]').waitFor();assert.equal(await page.locator('[data-session-row]').count(),2);assert.equal(await page.locator('.p11-message').count(),0);await shot('failure-dialog');await dlg().locator('[data-p11=confirm]').click();await settled();});
await check('UNKNOWN dialog allows defer then explicit reconcile; no stacked overlays or blind retry',async()=>{await scenario('revoke-unknown');await page.locator('[data-p11-revoke]').click();await dlg().locator('[data-p11=confirm]').click();await page.getByRole('heading',{name:'Chưa xác định kết quả'}).waitFor();assert.equal(await page.locator('[data-session-row]').count(),2);await shot('unknown-dialog');await dlg().locator('[data-p11=cancel]').click();await settled();assert.ok(await page.locator('[data-p11-revoke]').isDisabled());await act('reconcile').click();await page.locator('.p11-dialog[data-tone=success]').waitFor();assert.equal(await page.locator('.app-modal-host').count(),1);await dlg().locator('[data-p11=confirm]').click();await settled();});
await check('Long identity remains complete through a bounded preview and full reader',async()=>{await act('back').click();await page.click('[data-p10=password]');await scenario('baseline');await page.fill('#p11-current','preview');await page.fill('#p11-next','stress');await page.fill('#p11-confirm','stress');await page.click('[data-p11-save]');await page.locator('[data-panel="P11.S03"]').waitFor();const text='Tên thử nghiệm rất dài '.repeat(35);await page.locator('.p11-summary strong').first().evaluate((e,t)=>e.textContent=t,text);await page.waitForTimeout(80);const m=await measure();const trigger=page.locator('.p11-summary .hn-read-more').first();assert.ok(await trigger.isVisible());await trigger.click();await page.locator('.hn-readable-dialog').waitFor();assert.equal(await page.locator('.hn-readable-dialog .app-modal-body p').textContent(),text);await shot('long-content-reader');await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnAppReadable);assert.equal((await measure()).footer,m.footer);assert.ok(await trigger.evaluate(e=>e===document.activeElement));});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(`${checks.length} groups PASS`);
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
