const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),before=process.argv.includes('--before'),profile=process.argv.includes('--profile'),out='handoff/motion/M19/'+(before?'before':profile?'profile':'evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference'}),p=await c.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);p.setDefaultTimeout(10000);if(before)await p.route('**/flows/**',async route=>{const pathname=new URL(route.request().url()).pathname,file='handoff/motion/M19/before/source/docs'+pathname;if(fs.existsSync(file)&&fs.statSync(file).isFile())await route.fulfill({body:fs.readFileSync(file),contentType:pathname.endsWith('.css')?'text/css':'text/javascript'});else await route.continue();});p.on('pageerror',e=>r.errors.push(e.message));await c.tracing.start({screenshots:true,snapshots:true,sources:true});await p.clock.setFixedTime(new Date('2026-10-01T05:00:00Z'));
await p.addInitScript(()=>{window.fx=[];window.samples=[];window.longTasks=[];window.hardware=0;window.motionListeners=0;const orig=Element.prototype.animate;Element.prototype.animate=function(frames,options){const item={primitive:this.dataset.motionPrimitive||'',frames,duration:options.duration,cancelled:false};fx.push(item);const a=orig.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{item.cancelled=true;cancel();};if(item.primitive.startsWith('Component')||item.primitive.startsWith('Post')||item.primitive.startsWith('SharedModal')){const start=performance.now(),node=this;function tick(){samples.push({primitive:item.primitive,ms:performance.now()-start,opacity:getComputedStyle(node).opacity,transform:getComputedStyle(node).transform});if(node.isConnected&&a.playState==='running')requestAnimationFrame(tick);}requestAnimationFrame(tick);}return a;};const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','issueVisibility'].includes(f?.name))motionListeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','issueVisibility'].includes(f?.name))motionListeners--;return remove.call(this,t,f,o);};new PerformanceObserver(l=>longTasks.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{hardware++;throw Error('Hardware unavailable');};});
const pause=()=>p.waitForTimeout(240),act=n=>p.locator(`.p19-app [data-p19=${n}]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent()),ownerFX=()=>p.evaluate(()=>fx.filter(x=>/^(ComponentScan|Post)/.test(x.primitive)));
async function demo(scene){await p.locator('.p19-tools').evaluate(e=>e.open=true);await p.click(`[data-p19-demo=${scene}]`);await pause();}
async function capture(id){await p.waitForTimeout(300);await p.evaluate(async()=>{await document.fonts.ready;scrollTo(0,0);});r.geometry[id]=await p.locator('.hn-screen').evaluate(e=>{const base=e.getBoundingClientRect();return {frame:[e.offsetWidth,e.offsetHeight],rects:Object.fromEntries(['.p19-header','.p19-scroll','.p19-footer','.p19-context','.hn-scan-camera','.p19-sheet','.p19-sheet-footer','.p19-success-mark'].map(q=>{const n=e.querySelector(q);if(!n)return[q,null];const b=n.getBoundingClientRect();return[q,[b.x-base.x,b.y-base.y,b.width,b.height]];})),nodes:e.querySelectorAll('*').length};});await p.locator('.hn-screen').screenshot({path:out+'/'+mode+'-'+id+'.png'});}
const check=async(name,fn)=>{await fn();r.checks.push(name);console.log('PASS '+mode+' '+name);};
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.locator('#motion-mode').evaluate(e=>{for(let n=e;n;n=n.parentElement)if(n.tagName==='DETAILS')n.open=true;});await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
for(const [i,scene] of ['scan','quantity','review','success'].entries()){await demo(scene);await capture('P19.S0'+(i+1));if(scene==='quantity'){await p.keyboard.press('Escape');await pause();}}
r.panelProfile=await p.evaluate(()=>({longTasks:[...longTasks],resourceDecodedBytes:performance.getEntriesByType('resource').reduce((n,e)=>n+e.decodedBodySize,0),durationMs:performance.now()}));
if(!before&&!profile){

const input=async value=>{if(!await p.locator('#p19-code').count())await p.click('[data-scan-action=manual]');await p.fill('#p19-code',value);await p.locator('#p19-code').press('Enter');};
const route=async hash=>{await p.evaluate(h=>location.hash=h,hash);await pause();};
await check('S01 accepted row160 only; same input/camera connection; counters immediate',async()=>{
 await p.click('[data-p19-open]');await pause();await p.locator('.hn-scan-camera').evaluate(e=>{window.camera=e;window.cameraRemoved=0;window.cameraObserver=new MutationObserver(rs=>{for(const r of rs)for(const n of r.removedNodes)if(n===camera||n.contains?.(camera))cameraRemoved++;});cameraObserver.observe(document.querySelector('.p19-app'),{childList:true,subtree:true});});await p.click('[data-scan-action=manual]');await p.locator('#p19-code').evaluate(e=>window.codeInput=e);await input('LK0001-HN001');assert.deepEqual((await snap()).counts,{codes:1,quantity:1});assert.equal(await p.evaluate(()=>document.querySelector('#p19-code')===codeInput&&document.activeElement===codeInput&&document.querySelector('.hn-scan-camera')===camera&&cameraRemoved===0),true);const rows=(await ownerFX()).filter(x=>x.primitive==='ComponentScan');assert.equal(rows.length,mode==='auto'?1:0);if(rows.length)assert.equal(rows[0].duration,160);await p.waitForTimeout(200);await input('LK0001-HN001');await p.waitForSelector('.app-modal-host');await p.locator('.app-modal-host').getByRole('button',{name:'Đóng',exact:true}).click();await pause();assert.equal((await ownerFX()).filter(x=>x.primitive==='ComponentScan').length,rows.length);
});
await check('S02 enter220/exit160; immediate cancel/quantity; rapid Back; no camera replacement',async()=>{
 const beforeFX=await p.evaluate(()=>fx.length);await input('BOX-LK-0002-01');assert.equal(await p.locator('#p19-quantity').evaluate(e=>document.activeElement===e),true);await p.fill('#p19-quantity','13');assert.equal(await p.locator('#p19-quantity').getAttribute('aria-invalid'),'true');await p.goBack();await pause();assert.equal((await snap()).counts.quantity,1);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.evaluate(()=>document.querySelector('.hn-scan-camera')===camera&&cameraRemoved===0),true);
 await input('BOX-LK-0002-01');await p.locator('.app-modal-host form').evaluate(e=>{e.requestSubmit();e.requestSubmit();});assert.deepEqual((await snap()).counts,{codes:2,quantity:3});assert.equal(await p.locator('.app-modal-host').count(),0);if(mode==='auto')assert.equal(await p.locator('.app-modal-visual-exit').evaluate(e=>e.inert&&e.getAttribute('aria-hidden')==='true'&&!e.querySelector('[id],[data-p19],[role]')),true);await pause();assert.equal(await p.locator('.app-modal-visual-exit').count(),0);assert.equal(await p.locator('#p19-code').evaluate(e=>e===document.activeElement),true);const entries=await p.evaluate(n=>fx.slice(n).filter(x=>x.primitive==='SharedModalPanel'),beforeFX);if(mode==='auto'){assert.ok(entries.some(x=>x.duration===220));assert.ok(entries.some(x=>x.duration===160));}else assert.equal(entries.length,0);await p.evaluate(()=>cameraObserver.disconnect());
});
let originalHash;
await check('S03 immediate2 codes/3units; press100; repeated Post only1; UNKNOWN never success',async()=>{
 await act('review').click();await pause();assert.deepEqual((await snap()).counts,{codes:2,quantity:3});const mark=(await ownerFX()).length;await p.selectOption('[data-p19-outcome]','unknown');await act('post').dispatchEvent('pointerdown');await act('post').evaluate(e=>{e.click();e.click();});assert.equal(await act('post').isDisabled(),true);await p.waitForSelector('.app-modal-host .hn-action-dialog');const now=await snap();assert.equal(now.unknown,true);assert.deepEqual(now.metrics,{post:1,check:0,commits:0});assert.equal(await p.locator('.p19-success-mark').count(),0);const effects=(await ownerFX()).slice(mark);assert.equal(effects.filter(x=>x.primitive==='PostFeedback').length,0);assert.equal(effects.filter(x=>x.primitive==='PostPress').length,mode==='auto'?1:0);await p.locator('.app-modal-host').getByRole('button',{name:'Để sau',exact:true}).click();await pause();originalHash=await p.evaluate(()=>location.hash);
});
await check('S04 confirmed receipt160 once; authoritative not-posted keeps request; Back no replay',async()=>{
 const request=(await snap()).request;await p.selectOption('[data-p19-outcome]','not-posted');await act('reconcile').click();await p.waitForSelector('.app-modal-host .hn-action-dialog');await p.locator('.app-modal-host').getByRole('button',{name:'Đóng',exact:true}).click();await pause();await p.selectOption('[data-p19-outcome]','ready');await act('post').click();await p.waitForSelector('[data-panel="P19.S04"]');assert.deepEqual((await snap()).receipt.request,request);assert.deepEqual((await snap()).metrics,{post:2,check:1,commits:1});const effects=(await ownerFX()).filter(x=>x.primitive==='PostFeedback');assert.equal(effects.length,mode==='auto'?1:0);if(effects.length)assert.equal(effects[0].duration,160);await p.waitForTimeout(190);const hash=await p.evaluate(()=>location.hash);await act('case').click();await p.waitForSelector('.p09-app');assert.ok((await p.locator('.p09-app').innerText()).includes('XLK-DEMO-0001'));await route(hash);assert.equal((await ownerFX()).filter(x=>x.primitive==='PostFeedback').length,effects.length);r.domain={counts:(await snap()).counts,metrics:(await snap()).metrics,status:(await snap()).receipt.status};
});

await check('Old case timeout never opens success on another case; no blind retry',async()=>{
 await route('#p02/component-issue?case=BH-003&panel=1');await input('BOX-LK-0002-01');await p.locator('.app-modal-host button[type=submit]').click();await pause();await act('review').click();await pause();const hash=await p.evaluate(()=>location.hash),before=(await ownerFX()).filter(x=>x.primitive==='PostFeedback').length;await p.selectOption('[data-p19-outcome]','unknown');await act('post').click();await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-002&panel=1');await p.waitForTimeout(650);assert.equal(await p.locator('.p19-success-mark').count(),0);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal((await ownerFX()).filter(x=>x.primitive==='PostFeedback').length,before);await route(hash);assert.equal((await snap()).unknown,true);assert.equal(await act('scan').isDisabled(),true);assert.equal(await act('reconcile').isDisabled(),false);assert.equal((await snap()).metrics.commits,1);
});
await check('Compact sheet and live off mode; inert exit cancels before rapid next sheet',async()=>{
 await p.click('[data-p19-open]');await input('BOX-LK-0002-01');await p.setViewportSize({width:360,height:420});await p.waitForTimeout(260);const g=await p.locator('.app-modal-host').evaluate(e=>{const s=e.closest('.hn-screen').getBoundingClientRect(),f=e.querySelector('footer').getBoundingClientRect(),d=e.querySelector('dialog');return f.bottom<=s.bottom+1&&f.top>=s.top&&d.scrollWidth<=d.clientWidth+1;});assert.equal(g,true);await p.evaluate(()=>{const e=document.querySelector('#home-motion-mode');e.value='off';e.dispatchEvent(new Event('change'));});assert.equal(await p.locator('.p19-sheet').evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length),0);await p.keyboard.press('Escape');await pause();await p.evaluate(value=>{const e=document.querySelector('#home-motion-mode');e.value=value;e.dispatchEvent(new Event('change'));},mode==='off'?'off':'auto');await p.setViewportSize({width:494,height:950});await input('BOX-LK-0002-01');await p.locator('.app-modal-host [data-p19=close]').first().evaluate(e=>e.click());await p.waitForTimeout(35);await p.locator('#p19-manual-form').evaluate(e=>e.requestSubmit());await p.waitForSelector('.app-modal-host');assert.equal(await p.locator('.app-modal-host').count(),1);assert.equal(await p.locator('.app-modal-visual-exit').count(),0);await p.keyboard.press('Escape');await pause();assert.equal(await p.locator('#p19-code').evaluate(e=>document.activeElement===e),true);assert.equal((await snap()).lines.length,0);
});
await check('Lifecycle4x; no listener growth; OS/off/hidden cancel; security removes outgoing instantly',async()=>{
 await route('#home');const baseline=await p.evaluate(()=>motionListeners);for(let i=0;i<4;i++){await p.click('[data-p19-open]');await pause();await input('BOX-LK-0002-01');await p.keyboard.press('Escape');await pause();await route('#home');assert.equal(await p.evaluate(()=>motionListeners),baseline);}await p.click('[data-p19-open]');await input('BOX-LK-0002-01');await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p19-sheet').evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length),0);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.keyboard.press('Escape');await pause();await input('BOX-LK-0002-01');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.p19-sheet').evaluate(e=>e.getAnimations().filter(a=>a.playState==='running').length),0);await p.keyboard.press('Escape');await pause();await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await input('BOX-LK-0002-01');await p.keyboard.press('Escape');await p.evaluate(()=>document.querySelector('[data-system-demo=expired]').click());assert.equal(await p.locator('.app-modal-visual-exit').count(),0);assert.equal(await p.locator('.p19-app:visible').count(),0);
});
const baseline=JSON.parse(fs.readFileSync('handoff/motion/M19/before/results.json','utf8')).find(x=>x.mode===mode);assert.deepEqual(r.geometry,baseline.geometry,'settled geometry must equal pre-motion source');

}
r.fx=await p.evaluate(()=>fx);r.samples=await p.evaluate(()=>samples);r.longTasks=await p.evaluate(()=>longTasks);r.hardware=await p.evaluate(()=>hardware);r.resourceBytes=await p.evaluate(()=>performance.getEntriesByType('resource').reduce((n,e)=>n+e.decodedBodySize,0));assert.deepEqual(r.errors,[]);await c.tracing.stop({path:out+'/'+mode+'-trace.zip'});await c.close();}
fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2));}catch(e){fs.writeFileSync(out+'/failure.json',JSON.stringify({results,error:e.stack},null,2));throw e;}finally{await b.close();}})();
