const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const phase=process.env.P12_AUDIT_PHASE||'after',out='handoff/P12/evidence/revision-10/'+phase;fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,permissions:['clipboard-read','clipboard-write']}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,fn){if(process.env.P12_AUDIT_ONLY&&!name.includes(process.env.P12_AUDIT_ONLY))return;try{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){checks.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);}}
async function close(){if(await p.locator('.app-modal-host').count()){await p.keyboard.press('Escape');await p.waitForSelector('.app-modal-host',{state:'detached'});await p.waitForTimeout(100);}}
async function route(hash){await close();await p.evaluate(h=>location.hash=h,hash);await p.waitForTimeout(150);}
const detail=tab=>'#p02/documents?panel='+(tab==='products'?3:2)+'&doc=p12-stock-PX-0011'+(tab==='info'?'':'&tab='+tab);
try{await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForFunction(()=>location.hash==='#home');
await check('Search Enter must not silently Apply a hidden supplier selection',async()=>{await route('#p02/documents?panel=4');const prior=await p.locator('#p12-supplier-value').textContent();await p.click('[data-p12=supplier]');await p.check('[name=choice][value=fixture-supplier-003]');await p.locator('.p12-supplier-picker input[type=search]').fill('khong co ket qua');await shot('supplier-before-enter');await p.locator('.p12-supplier-picker input[type=search]').press('Enter');await p.waitForTimeout(100);assert.equal(await p.locator('.p12-supplier-picker').count(),1);assert.equal(await p.locator('#p12-supplier-value').textContent(),prior);await close();});
await check('Product result counter updates for no match and totals remain document-wide',async()=>{await route(detail('products'));await p.fill('#p12-product-query','does-not-match');await shot('product-no-results');assert.match(await p.locator('.p12-section-heading').textContent(),/0/);assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['7','2']);await p.fill('#p12-product-query','ZD421');assert.match(await p.locator('.p12-section-heading').textContent(),/1/);assert.equal(await p.locator('.p12-product').count(),1);await p.fill('#p12-product-query','');});
await check('Long document numbers stay within the card text column',async()=>{await p.evaluate(async()=>{const {DOCUMENTS}=await import('/flows/documents/document-model.mjs');const d=DOCUMENTS.find(d=>d.number==='PX-0011');window.auditOriginalNumber=d.number;d.number='PXHOANAM2026123456789012345678901234567890';});try{await route('#p02/documents');await p.locator('[data-p12-doc="p12-stock-PX-0011"]').waitFor();await shot('long-document-number');const m=await p.locator('[data-p12-doc="p12-stock-PX-0011"] .p12-record-copy strong').evaluate(e=>{const range=document.createRange();range.selectNodeContents(e);const parent=e.parentElement.getBoundingClientRect();return {cardRight:e.closest('.p12-record').getBoundingClientRect().right,scrollRight:e.closest('.p12-scroll').getBoundingClientRect().right,parent:parent.right,rects:[...range.getClientRects()].map(r=>r.right),wrap:getComputedStyle(e).overflowWrap,overflow:e.scrollWidth-e.clientWidth};});assert.ok(m.cardRight<=m.scrollRight+1&&m.rects.every(r=>r<=m.parent+1),JSON.stringify(m));}finally{await p.evaluate(async()=>{const {DOCUMENTS}=await import('/flows/documents/document-model.mjs');DOCUMENTS.find(d=>d.id==='p12-stock-PX-0011').number=window.auditOriginalNumber;});}});
await check('Copy result shows literal document code, not escaped HTML entities',async()=>{await p.evaluate(async()=>{const {DOCUMENTS}=await import('/flows/documents/document-model.mjs');DOCUMENTS.find(d=>d.id==='p12-stock-PX-0011').number='PX<&-0011';});try{await route(detail('info'));await p.click('[data-p12=copy]');await p.locator('.app-modal-host').waitFor();await shot('copy-special-characters');assert.ok((await p.locator('.app-modal-host').textContent()).includes('PX<&-0011'));}finally{await close();await p.evaluate(async()=>{const {DOCUMENTS}=await import('/flows/documents/document-model.mjs');DOCUMENTS.find(d=>d.id==='p12-stock-PX-0011').number='PX-0011';});}});
await check('Slow PDF has visible busy state; Back cancels read and leaves the document',async()=>{await route('#p02/documents');await p.locator('[data-p12-doc="p12-stock-PX-0011"]').click();await p.click('[data-p12-tab=files]');let held;await p.route('**/documents/assets/*.pdf',r=>{held=r;});try{await p.locator('[data-p12-download]').first().click();await p.waitForTimeout(100);await shot('slow-download');const busy=await p.locator('[data-p12-download]').first().getAttribute('aria-busy');await p.click('[data-p12=back]');await p.waitForTimeout(180);const left=await p.locator('#p12-query').count();assert.deepEqual({busy,left},{busy:'true',left:1});}finally{await held?.abort().catch(()=>{});await p.unroute('**/documents/assets/*.pdf');await p.waitForTimeout(150);await close();}});
await check('PDF timeout and failed retry preserve context; successful retry downloads real PDF once',async()=>{if(phase==='before')return;await route(detail('files'));let held;await p.route('**/documents/assets/*.pdf',r=>{held=r;});try{await p.locator('[data-p12-download]').first().click();await p.getByRole('heading',{name:'Tải tài liệu quá lâu',exact:true}).waitFor({timeout:22000});assert.equal(await p.locator('.p12-file-spinner').count(),0);assert.equal(await p.locator('[data-p12-download]').first().isDisabled(),false);await shot('download-timeout');await close();}finally{await held?.abort().catch(()=>{});await p.unroute('**/documents/assets/*.pdf');}await p.route('**/documents/assets/*.pdf',r=>r.fulfill({status:404,body:'missing'}));await p.locator('[data-p12-download]').first().click();await p.getByRole('heading',{name:'Không tải được tài liệu',exact:true}).waitFor();await close();await p.unroute('**/documents/assets/*.pdf');const downloadPromise=p.waitForEvent('download');await p.locator('[data-p12-download]').first().click();const d=await downloadPromise,file=path.join(out,d.suggestedFilename());await d.saveAs(file);assert.equal(fs.readFileSync(file).subarray(0,5).toString(),'%PDF-');assert.equal(await p.locator('.p12-context h2').textContent(),'PX-0011');});
await check('Supplier Enter with a match moves focus without committing; IME Enter is not cancelled',async()=>{if(phase==='before')return;await route('#p02/documents?panel=4');const before=await p.locator('#p12-supplier-value').textContent();await p.click('[data-p12=supplier]');const input=p.locator('.p12-supplier-picker input[type=search]');await input.fill('Thien Long');await input.press('Enter');assert.equal(await p.locator('.p12-supplier-picker').count(),1);assert.equal(await p.locator('#p12-supplier-value').textContent(),before);assert.equal(await p.evaluate(()=>document.activeElement.name),'choice');await p.keyboard.press('Enter');assert.equal(await p.locator('.p12-supplier-picker').count(),1);assert.equal(await p.locator('.p12-supplier-picker [name=choice]:checked').inputValue(),'fixture-supplier-003');assert.equal(await p.locator('#p12-supplier-value').textContent(),before);assert.equal(await input.evaluate(e=>{const k=new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true,cancelable:true});e.dispatchEvent(k);return k.defaultPrevented;}),false);await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);});
await check('Attachment keyboard download restores focus after loading',async()=>{await route(detail('files'));const button=p.locator('[data-p12-download]').first(),pending=p.waitForEvent('download');await button.press('Enter');await pending;await p.waitForFunction(()=>!document.querySelector('[data-p12-download]').disabled);assert.ok(await button.evaluate(e=>document.activeElement===e));});
await check('Attachment viewer Back restores the exact document and Files tab',async()=>{await route(detail('files'));await p.locator('[data-p12-file]').first().click();await p.waitForSelector('.p18-app');await p.locator('.p18-app header button').first().click();await p.locator('.p12-tabs').waitFor();assert.equal(await p.locator('[data-p12-tab=files]').getAttribute('aria-selected'),'true');assert.equal(await p.locator('.p12-context h2').textContent(),'PX-0011');});
await check('All four panels and detail tabs fit horizontally; footer remains available at six viewports',async()=>{for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});for(const [name,hash]of [['list','#p02/documents'],...['info','products','files','events'].map(t=>[t,detail(t)]),['create','#p02/documents?panel=4']]){await route(hash);await p.locator('.p12-app').waitFor();const m=await p.evaluate(()=>{const s=document.querySelector('.p12-scroll'),a=document.querySelector('.hn-screen'),foot=document.querySelector('.p12-footer')||document.querySelector('.hn-nav'),ar=a.getBoundingClientRect(),fr=foot.getBoundingClientRect();return {shell:[a.offsetWidth,a.offsetHeight],overflow:s.scrollWidth-s.clientWidth,footer:fr.bottom<=ar.bottom+1,tabHeight:document.querySelector('.p12-tabs')?.offsetHeight||0};});assert.deepEqual(m.shell,[494,950]);assert.ok(m.overflow<=1&&m.footer&&m.tabHeight<=49,JSON.stringify({name,width,height,m}));await shot(name+'-'+width+'x'+height);}}await p.setViewportSize({width:494,height:950});});
fs.writeFileSync(path.join(out,process.env.P12_AUDIT_ONLY?'audit-'+process.env.P12_AUDIT_ONLY.replace(/\W/g,'-')+'-results.json':'audit-results.json'),JSON.stringify({checks,errors},null,2));console.log(checks.filter(c=>c.status==='PASS').length+'/'+checks.length+' PASS');if(phase==='after'&&(checks.some(c=>c.status!=='PASS')||errors.length))process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
