const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.SECURITY_EVIDENCE_DIR||'handoff/P11/evidence/revision-01');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
const act=a=>page.locator(`[data-p11="${a}"]`).first(),p10=a=>page.locator(`[data-p10="${a}"]`).first();
async function panel(p){await page.locator(`.p11-app[data-panel="P11.S0${p}"]`).waitFor();}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(name){await page.evaluate(()=>{scrollTo(0,0);return document.fonts.ready;});await page.waitForTimeout(120);await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function login(scenario='valid'){await page.goto('http://127.0.0.1:8766/flows/auth-session/');if(scenario!=='valid'){await page.locator('.preview-tools details summary').first().click();await page.selectOption('#scenario',scenario);}await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home:visible').waitFor();await page.click('[data-tab=profile]');await p10('security').click();}
async function open(p=1){await p10(p===4?'sessions':'password').click();await panel(p);}
async function scenario(value){await dismissNotice();await page.locator('.p11-tools details').evaluate(e=>e.open=true);await page.selectOption('#p11-scenario',value);await page.evaluate(()=>scrollTo(0,0));if(await page.locator('[data-panel="P11.S04"]').count())await page.waitForFunction(()=>document.querySelector('.p11-app').getAttribute('aria-busy')==='false');}
async function fill(confirm='qa-new-secret'){await page.fill('#p11-current','preview');await page.fill('#p11-next','qa-new-secret');await page.fill('#p11-confirm',confirm);}
async function settle(){await page.waitForFunction(()=>!history.state?.hnSecurityDialog);}
async function dismissNotice(){const d=page.locator('.p11-dialog');if(!await d.count())return;const cancel=d.locator('[data-p11=cancel]');await (await cancel.count()?cancel:d.locator('[data-p11=confirm]')).click();await page.waitForFunction(()=>!history.state?.hnSecurityDialog);}
async function back(){await dismissNotice();await act('back').click();if(await page.locator('.p11-dialog').count()){await page.locator('.p11-dialog [data-p11=confirm]').click();await settle();}await page.locator('.p10-app[data-panel="P10.S04"]').waitFor();}
async function audit(name){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),a=document.querySelector('.p11-app'),b=a.querySelector('.p11-scroll'),footer=a.querySelector('.p11-footer')||s.querySelector('.hn-nav'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,font:getComputedStyle(a).fontFamily,shell:[s.offsetWidth,s.offsetHeight],overflow:b.scrollWidth>b.clientWidth,pageOverflow:document.documentElement.scrollWidth>innerWidth,footerInside:footer.getBoundingClientRect().bottom<=r.bottom+1,contentAboveFooter:b.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1,scroll:[b.scrollHeight,b.clientHeight,b.scrollTop],scale:r.width/s.offsetWidth};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.overflow&&!m.pageOverflow&&m.footerInside&&m.contentAboveFooter,JSON.stringify(m));metrics.push({name,...m});await shot(name);}
async function allSizes(p){for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await audit(`P11-S0${p}-${w}x${h}`);}await page.setViewportSize({width:494,height:1000});await shot(`P11-S0${p}-actual`);}
async function revokeConfirm(){await page.locator('[data-p11-revoke]').first().click();await page.locator('.p11-dialog [data-p11=confirm]').click();await settle();}
try{
await login();await open();await scenario('blocked');
await check('P10 routes to security; explicit disconnected save retains fields without success',async()=>{await fill();await page.click('[data-p11-save]');await page.getByText('Chưa kết nối chức năng đổi mật khẩu.',{exact:false}).waitFor();assert.equal(await page.locator('[data-panel="P11.S03"]').count(),0);assert.ok(await page.inputValue('#p11-next'));await shot('blocked-save');await back();});
await check('Disconnected scenario does not invent devices; retry stays blocked',async()=>{await open(4);await page.getByText('Chưa kết nối danh sách phiên đăng nhập.',{exact:false}).waitFor();assert.equal(await page.locator('[data-session-row]').count(),0);await shot('blocked-sessions');await act('reload').click();await page.getByText('Chưa kết nối danh sách phiên đăng nhập.',{exact:false}).waitFor();await back();});
await open();await scenario('baseline');
await check('S01 genuine password form in six viewports',async()=>{await fill();assert.equal(await page.locator('input[type=password]').count(),3);await allSizes(1);});
await check('A01 mismatch local field error, aria and focus; S02 six viewports',async()=>{await page.fill('#p11-confirm','different');await page.click('[data-p11-save]');await panel(2);assert.equal(await page.locator('#p11-confirm').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#p11-confirm').evaluate(e=>e===document.activeElement),true);await allSizes(2);await page.fill('#p11-confirm','qa-new-secret');await panel(1);assert.equal(await page.locator('#p11-confirm').getAttribute('aria-invalid'),'false');});
await check('A02 three independent eye toggles retain values and conceal on second click',async()=>{for(const k of ['current','next','confirm']){const i=page.locator('#p11-'+k),before=await i.inputValue();await page.locator(`[data-p11-eye=${k}]`).click();assert.equal(await i.getAttribute('type'),'text');assert.ok(await i.inputValue()===before);assert.equal(await page.locator('input[type=text]').count(),1);await page.locator(`[data-p11-eye=${k}]`).click();assert.equal(await i.getAttribute('type'),'password');}assert.ok(!await page.locator('.hn-screen').innerText().then(t=>t.includes('qa-new-secret')));});
await check('A03 busy blocks duplicate submits; verified success S03 six viewports',async()=>{await page.click('[data-p11-save]');assert.equal(await page.locator('[data-p11-save]').isDisabled(),true);await page.evaluate(()=>document.querySelector('#p11-form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await panel(3);assert.equal(await page.locator('.p11-summary strong').first().textContent(),'Minh Anh');await allSizes(3);await back();});
await check('S04 separates current and other fixture sessions in six viewports',async()=>{await open(4);await page.locator('[data-p11-revoke]').waitFor();assert.equal(await page.locator('[data-session-row]').count(),2);assert.equal(await page.locator('[data-session-row="fixture-security-current"] [data-p11-revoke]').count(),0);await allSizes(4);});
await check('Revoke confirmation contained, focus trapped; Escape and Back preserve rows',async()=>{await page.locator('[data-p11-revoke]').click();assert.equal(await page.locator('.app-modal-host').count(),1);const contained=await page.evaluate(()=>{const a=document.querySelector('.hn-screen').getBoundingClientRect(),d=document.querySelector('dialog[open]').getBoundingClientRect();return d.top>=a.top&&d.bottom<=a.bottom&&d.left>=a.left&&d.right<=a.right;});assert.ok(contained);await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('.p11-dialog [data-p11=confirm]').evaluate(e=>e===document.activeElement),true);await shot('revoke-dialog');await page.keyboard.press('Escape');await settle();assert.equal(await page.locator('[data-p11-revoke]').evaluate(e=>e===document.activeElement),true);await page.locator('[data-p11-revoke]').click();await page.goBack();await page.locator('.app-modal-host').waitFor({state:'detached'});await settle();assert.equal(await page.locator('[data-session-row]').count(),2);});
await check('A04 server rejection keeps both sessions with feedback',async()=>{await scenario('revoke-failed');await revokeConfirm();await page.getByText('Không thể đăng xuất thiết bị.',{exact:false}).waitFor();assert.equal(await page.locator('[data-session-row]').count(),2);await shot('revoke-failed');});
await check('UNKNOWN revoke holds row and disables retry until authoritative reconciliation',async()=>{await scenario('revoke-unknown');await revokeConfirm();await act('reconcile').waitFor();await dismissNotice();assert.equal(await page.locator('[data-session-row]').count(),2);assert.ok(await page.locator('[data-p11-revoke]').isDisabled());await act('reconcile').click();await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('[data-session-row="fixture-security-current"]').count(),1);await shot('revoke-confirmed');});
await check('Missing metadata does not infer device location or OS',async()=>{await scenario('missing');assert.ok(!await page.locator('.p11-scroll').innerText().then(t=>t.includes('Hà Nội')));assert.ok(await page.getByText('Chưa có dữ liệu',{exact:false}).count()>0);await shot('missing-metadata');});
await check('Session read failure and reload shown without false empty result',async()=>{await scenario('sessions-failed');await page.getByText('Không tải được danh sách phiên.',{exact:false}).waitFor();assert.equal(await page.locator('[data-session-row]').count(),0);await shot('sessions-failed');await back();});
await check('Server current-password error is separate from mismatch',async()=>{await open();await scenario('wrong-current');await fill();await page.click('[data-p11-save]');await page.getByText('Mật khẩu hiện tại không đúng.').waitFor();assert.equal(await page.locator('#p11-current').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#p11-confirm').getAttribute('aria-invalid'),'false');await shot('wrong-current');});
await check('Generic server rejection never opens success',async()=>{await scenario('rejected');await fill();await page.click('[data-p11-save]');await page.getByText('Hệ thống từ chối thay đổi mật khẩu.',{exact:false}).waitFor();assert.equal(await page.locator('[data-panel="P11.S03"]').count(),0);});
await check('UNKNOWN password change requires reconcile and preserves request over Back/reentry',async()=>{await scenario('unknown');await fill();await page.click('[data-p11-save]');await act('reconcile').waitFor();assert.ok(await page.locator('[data-p11-save]').isDisabled());await back();await open();assert.equal(await page.inputValue('#p11-next'),'');assert.ok(await page.locator('[data-p11-save]').isDisabled());await act('reconcile').click();await panel(3);await back();});
await check('Dirty Back cancel keeps fields; confirm clears them; no password storage',async()=>{await open();await scenario('baseline');await fill();await page.goBack();await page.locator('.p11-dialog').waitFor();await page.locator('.p11-dialog [data-p11=cancel]').click();await settle();assert.ok(await page.inputValue('#p11-next'));await act('back').click();await page.locator('.p11-dialog [data-p11=confirm]').click();await settle();await page.locator('.p10-app').waitFor();await open();assert.equal(await page.inputValue('#p11-next'),'');assert.ok(!await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage,history.state])).then(t=>t.includes('qa-new-secret')));await back();});
await check('P03 scanner dialog restores security session route and footer',async()=>{await open(4);await page.locator('[data-p11-revoke]').waitFor();await page.click('[data-tab=lookup]');await page.locator('.p03-dialog').waitFor();await page.keyboard.press('Escape');await page.locator('.p03-dialog').waitFor({state:'detached'});await panel(4);assert.ok(await page.locator('.hn-screen').evaluate(e=>e.classList.contains('p11-screen')));await back();});
await check('A05 fixture reauthentication clears auth, preserves unrelated storage; Back cannot revive success',async()=>{await open();await scenario('reauthenticate');await page.evaluate(()=>localStorage.setItem('hn-p11-preserve','draft'));await fill();await page.click('[data-p11-save]');await page.locator('#username').waitFor();await page.goBack();assert.equal(await page.locator('.p11-app').count(),0);assert.equal(await page.evaluate(()=>localStorage.getItem('hn-p11-preserve')),'draft');});
await check('Expired response returns through P01 guard',async()=>{await login();await open();await scenario('expired');await fill();await page.click('[data-p11-save]');await page.locator('#username').waitFor();assert.equal(await page.locator('.p11-app').count(),0);});
await check('Other actor identity in success comes from session',async()=>{await login('other-user');await open();await scenario('baseline');await fill();await page.click('[data-p11-save]');await panel(3);assert.equal(await page.locator('.p11-summary strong').first().textContent(),'Lan Nguyễn');});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors,external},null,2));console.log(`${checks.length} browser groups PASS; ${metrics.length} layout captures`);
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,checks,errors,external},null,2));await shot('failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
