const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.LOOKUP_RECENT_EDGE_EVIDENCE_DIR||'handoff/ux-upgrade-2026-09-30/p06/recent-edges');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),page=await b.newPage({viewport:{width:360,height:800}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const longName='Sản phẩm Unicode Á Ê ộ < & >\n'+('TênKhôngCóKhoảngTrắng'.repeat(110));
await page.route('**/lookup/demo-data.mjs',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+`\nDEMO_ITEM_DETAILS.HN12346.name=${JSON.stringify(longName)};`});});
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-scanner').click();await page.locator('.p06-list [data-p06-item="fixture-item-HN12346"]').click();await page.locator('[data-p06="back"]').click();await page.locator('[data-p06-recent]').waitFor();
assert.equal(await page.locator('[data-p06-recent] small').textContent(),longName);assert.equal(await page.locator('[data-p06-recent] button').count(),0);
for(const [width,height]of [[494,1000],[360,800],[340,420]]){await page.setViewportSize({width,height});await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=0);const nav=await page.locator('.hn-nav').boundingBox();assert.ok(await page.locator('[data-p06-recent]').evaluate(e=>e.getBoundingClientRect().right<=document.querySelector('.p06-scroll').getBoundingClientRect().right+1));assert.equal(await page.locator('.p06-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false);await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);assert.deepEqual(await page.locator('.hn-nav').boundingBox(),nav);await page.locator('.hn-screen').screenshot({path:path.join(out,`long-${width}x${height}.png`)});}checks.push({name:'Real source Unicode/newline/2000+ unbroken name retains full raw text, no nested controls or overflow, fixed footer at3viewports',status:'PASS'});
await page.setViewportSize({width:360,height:800});await page.locator('[data-p06-recent] img').dispatchEvent('error');assert.equal(await page.locator('[data-p06-recent] .p06-no-image').count(),1);assert.ok((await page.locator('[data-p06-recent] .p06-no-image').boundingBox()).width<50);assert.equal(await page.locator('.p06-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false);checks.push({name:'Image read failure keeps40px thumbnail placeholder; no expansion into text column',status:'PASS'});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,sourceOverride:'Browser-only mock response for long names; repository demo data unchanged'},null,2));
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
