const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const before=process.argv.includes('--before'),out='handoff/motion/M17/'+(before?'before':'evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];let p;
try{for(const mode of ['auto','os-reduced','off']){
 const ctx=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'});p=await ctx.newPage();p.setDefaultTimeout(25000);await ctx.tracing.start({screenshots:true,snapshots:true,sources:true});await mockGeography(p);
 const r={mode,checks:[],geometry:{},errors:[],writes:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));p.on('request',q=>{if(!['GET','HEAD'].includes(q.method()))r.writes.push(q.method()+' '+q.url());});
 await p.addInitScript(()=>{
  window.fx=[];window.samples=[];window.calls={inboundRecord:0,inboundCheck:0,outboundRecord:0,outboundCheck:0,hardware:0};window.listeners=0;window.longTasks=[];
  const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','statusVisibility','onNfcVisibility'].includes(f?.name))listeners++;return add.call(this,t,f,o);};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&['visibility','statusVisibility','onNfcVisibility'].includes(f?.name))listeners--;return remove.call(this,t,f,o);};
  const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){const e={owner:this.dataset.hnMotionConsumer||this.dataset.motionPrimitive||'',panel:this.closest('.p17-app')?.dataset.panel||'',duration:options.duration,frames,cancelled:false};fx.push(e);const a=animate.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{e.cancelled=true;return cancel();};if(e.panel||e.owner==='SharedModalPanel'){const node=this,start=performance.now();const sample=()=>{samples.push({owner:e.owner,panel:e.panel,ms:performance.now()-start,opacity:getComputedStyle(node).opacity});if(node.isConnected&&performance.now()-start<240)requestAnimationFrame(sample);};requestAnimationFrame(sample);}return a;};
  new PerformanceObserver(l=>longTasks.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});
  if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{calls.hardware++;throw Error('No camera');};
 });
 for(const owner of ['inbound','outbound']){
  await p.route(`**/${owner}/${owner}.mjs*`,q=>q.fulfill({contentType:'text/javascript',body:fs.readFileSync(`docs/flows/${owner}/${owner}.mjs`,'utf8').replace(`const flow = create${owner==='inbound'?'Inbound':'Outbound'}Flow(`,`const flow = window.${owner}Flow = create${owner==='inbound'?'Inbound':'Outbound'}Flow(`)}));
  await p.route(`**/${owner}/fixture-adapter.mjs*`,q=>{let s=fs.readFileSync(`docs/flows/${owner}/fixture-adapter.mjs`,'utf8');for(const op of ['record','check'])s=s.replace(`async ${op}(request) {`,`async ${op}(request) {window.calls.${owner}${op==='record'?'Record':'Check'}++;${op==='check'?'await new Promise(r=>setTimeout(r,650));':''}`);return q.fulfill({contentType:'text/javascript',body:s});});
 }
 await p.clock.setFixedTime(new Date('2026-10-01T01:15:20Z'));
 const act=(o,a)=>p.locator(`[data-${o}="${a}"]`).first(),snapshot=o=>p.evaluate(o=>window[o+'Flow'].snapshot(),o),effects=()=>p.evaluate(()=>fx.filter(x=>x.panel));
 const check=async(name,fn)=>{await fn();r.checks.push({name,status:'PASS'});console.log('PASS '+mode+' '+name);};
 const scan=async(o,code)=>{await p.fill(`#${o}-code`,code);await p.press(`#${o}-code`,'Enter');};
 async function capture(id){await p.waitForTimeout(280);await p.evaluate(()=>scrollTo(0,0));r.geometry[id]=await p.locator('.p17-app').evaluate(e=>{const box=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {text:e.innerText,dom:e.querySelectorAll('*').length,app:box(e),header:box(e.querySelector('header')),scroll:box(e.querySelector('.p17-scroll')),footer:box(e.querySelector('footer')),overflow:e.querySelector('.p17-scroll').scrollWidth>e.querySelector('.p17-scroll').clientWidth};});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});}
 await p.goto('http://localhost:8766/flows/auth-session/');await p.waitForSelector('#username',{timeout:60000});await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#home-motion-mode').evaluate((e,m)=>{e.value=m==='off'?'off':'auto';e.dispatchEvent(new Event('change',{bubbles:true}));},mode);await p.click('[data-route=inbound]');await p.locator('.p04-tools').evaluate(e=>e.open=true);await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');await scan('p04','HN-NOT-FOUND');await capture('P17.S01');
 if(!before)await check('S01 immediate raw/reason, repeated errors preserve accepted; local140/80/off feedback only',async()=>{
  const s=await snapshot('inbound');assert.equal(s.accepted.length,1);assert.equal(s.exception.raw,'HN-NOT-FOUND');const all=await effects();assert.ok(all.every(x=>!x.frames.some(f=>f.transform)));assert.ok(mode==='off'?all.length===0:all.some(x=>x.owner==='ScanFeedback'&&x.duration===(mode==='auto'?140:80)));
  for(let i=0;i<3;i++){await act('p04','exception-manual').click();await scan('p04','HN-NOT-FOUND');assert.equal((await snapshot('inbound')).accepted.length,1);assert.equal(await p.locator('.p17-camera').evaluate(e=>e.getAnimations({subtree:true}).length),0);assert.ok(await p.locator('.p17-app').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length<=1));}
 });
 if(!before)await check('No replay on repaint, Back/Forward or mode changes; rapid cancel does not append codes',async()=>{const n=(await effects()).length;await p.selectOption('[data-p04-outcome]','unknown');await p.waitForTimeout(200);assert.equal((await effects()).length,n);await p.click('[data-tab=home]');const base=await p.evaluate(()=>listeners);await p.click('[data-route=inbound]');await p.waitForTimeout(200);assert.equal((await effects()).length,n);await p.goBack();await p.waitForSelector('[data-panel="P04.S02"]');await p.goForward();await p.waitForTimeout(150);assert.equal(await p.locator('.p17-app').count(),0);for(let i=0;i<5;i++){await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');await p.click('[data-route=inbound]');}await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');assert.equal(await p.evaluate(()=>listeners),base);await p.click('[data-route=inbound]');});
 if(await p.locator('.p17-app').count())await act('p04','exception-manual').click();await act('p04','next').click();await p.selectOption('[data-p04-outcome]','timeout-recorded');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');await capture('P17.S04');
 if(!before)await check('S04 rapid resend stays guarded; spinner only while checking; same request verified once',async()=>{const s=await snapshot('inbound');for(let i=0;i<4;i++)await act('p04','send').dispatchEvent('click');assert.equal(await act('p04','send').isDisabled(),true);assert.equal(await p.locator('.p17-status-spinner').count(),0);assert.equal(await p.evaluate(()=>calls.inboundRecord),1);await act('p04','check').click();assert.equal(await act('p04','check').getAttribute('aria-disabled'),'true');assert.equal(await act('p04','send').isDisabled(),true);const spinner=p.locator('.p17-status-spinner');assert.equal(await spinner.count(),1);assert.equal(await spinner.evaluate(e=>getComputedStyle(e).animationName),mode==='auto'?'p17-status-turn':'none');await act('p04','check').dispatchEvent('click');await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-status-check.png')});await p.waitForSelector('[data-panel="P04.S04"]');assert.deepEqual((await snapshot('inbound')).request,s.request);assert.equal(await p.evaluate(()=>calls.inboundCheck),1);assert.equal((await snapshot('inbound')).recorded,true);assert.equal(await p.locator('.p17-status-spinner').count(),0);});
 await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');await p.click('[data-route=outbound]');await p.locator('.p05-tools').evaluate(e=>e.open=true);await address(p);await act('p05','next').click();await act('p05','manual').click();await scan('p05','HN99999');await capture('P17.S02');
 if(!before)await check('S02 reason immediate, static quantity; conflict notice fade; hidden/OS/off cancellation',async()=>{assert.equal((await snapshot('outbound')).accepted.length,0);assert.equal(await p.evaluate(()=>calls.outboundRecord),0);assert.ok(mode==='off'?(await effects()).filter(x=>x.panel==='P17.S02').length===0:(await effects()).some(x=>x.owner==='ConflictNotice'));await act('p05','exception-back').click();await act('p05','manual').click().catch(()=>{});await p.fill('#p05-code','HN99999');await p.evaluate(()=>{document.querySelector('#p05-code').form.requestSubmit();const e=document.querySelector('#home-motion-mode');e.value='off';e.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('.p17-app').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await p.locator('#home-motion-mode').evaluate((e,m)=>{e.value=m==='off'?'off':'auto';e.dispatchEvent(new Event('change',{bubbles:true}));},mode);const n=(await effects()).length;await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await act('p05','exception-back').click();await p.fill('#p05-code','HN99999');await p.press('#p05-code','Enter');assert.equal((await effects()).length,n);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});if(mode==='auto'){await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.p17-app').evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await p.emulateMedia({reducedMotion:'no-preference'});}await act('p05','exception-back').click();});
 await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');await p.click('[data-route=nfc]');await act('p07','begin').click();await p.locator('.p07-tools details').first().evaluate(e=>e.open=true);await p.selectOption('[data-p07-scenario]','conflict');await p.click('[data-p07-demo-read]');await p.waitForSelector('[data-panel="P17.S03"]');await capture('P17.S03');
 if(!before)await check('S03 reused modal, backdrop/focus/Back/rapid reopen preserve NFC mapping and cancel',async()=>{for(let i=0;i<3;i++){await act('p07','exception-detail').click();assert.equal(await p.locator('.app-modal-host').count(),1);if(i===0){const fx=await p.evaluate(()=>window.fx.filter(x=>x.owner==='SharedModalPanel'));assert.ok(mode==='auto'?fx.length>0:fx.length===0);await p.locator('.app-modal-host').dispatchEvent('click');assert.equal(await p.locator('.app-modal-host').count(),1);}await p.keyboard.press('Escape');await p.waitForTimeout(80);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await act('p07','exception-detail').evaluate(e=>e===document.activeElement),true);}await act('p07','exception-detail').click();await p.goBack();await p.waitForTimeout(80);await p.goBack();await p.waitForSelector('[data-panel="P07.S02"]');assert.equal(JSON.parse(await p.locator('[data-p07-snapshot]').textContent()).stats.mutations,0);});
 if(!before)await check('Compact viewport + cleanup cycles; no additional camera/NFC listeners or operations',async()=>{await p.setViewportSize({width:340,height:420});await p.click('[data-p07-demo-read]');await p.waitForSelector('[data-panel="P17.S03"]');await act('p07','exception-detail').click();assert.ok(await p.locator('.app-modal-host dialog').evaluate(e=>{const r=e.getBoundingClientRect(),s=e.closest('.hn-screen').getBoundingClientRect();return r.bottom<=s.bottom+1&&r.right<=s.right+1;}));await p.keyboard.press('Escape');await p.waitForTimeout(100);await act('p07','exception-cancel').click();await p.waitForSelector('[data-panel="P07.S02"]');await p.waitForTimeout(80);await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');const n=await p.evaluate(()=>listeners);for(let i=0;i<5;i++){await p.click('[data-route=nfc]');await p.evaluate(()=>location.hash='#home');await p.waitForSelector('#hn-home:not([hidden])');}assert.equal(await p.evaluate(()=>listeners),n);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.evaluate(()=>calls.hardware),0);assert.equal(await p.locator('[inert]').count(),0);await p.setViewportSize({width:494,height:950});});
 r.fx=await p.evaluate(()=>fx);r.samples=await p.evaluate(()=>samples);r.longTasks=await p.evaluate(()=>longTasks);r.domain=await p.evaluate(()=>({calls,accepted:inboundFlow.snapshot().accepted.map(x=>[x.raw,x.quantity]),outboundAccepted:outboundFlow.snapshot().accepted.length,inboundRecorded:inboundFlow.snapshot().recorded}));assert.deepEqual(r.errors,[]);assert.deepEqual(r.writes,[]);await ctx.tracing.stop({path:path.join(out,mode+'-trace.zip')});await ctx.close();
}
if(!before){const previous=JSON.parse(fs.readFileSync('handoff/motion/M17/before/results.json'));for(const r of results){assert.deepEqual(r.geometry,previous.results.find(x=>x.mode===r.mode).geometry,'settled panel geometry/text/DOM must match');assert.deepEqual(r.domain,results[0].domain,'same operations/data across modes');}}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({before,results},null,2));console.log('M17 PASS '+results.reduce((n,r)=>n+r.checks.length,0)+' groups');
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,results},null,2));await p?.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e;}finally{await browser.close();}})();
