const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const out='handoff/P17/evidence/revision-02/ux';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(18000);await mockGeography(p);
await p.addInitScript(()=>{window.copyMode='ok';window.copied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copied.push(text);if(copyMode==='error')throw Error('Denied');if(copyMode==='pending')return new Promise(r=>window.resolveCopy=r);}}});});
await p.route('**/inbound/fixture-adapter.mjs*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('docs/flows/inbound/fixture-adapter.mjs','utf8').replace('async check(request) {','async check(request) { await new Promise(r=>setTimeout(r,700));')}));
const act=(o,a)=>p.locator(`[data-${o}="${a}"]`).first(),snap=async o=>JSON.parse(await p.locator(`[data-${o}-snapshot]`).textContent());
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
const shot=async name=>{await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:out+'/'+name+'.png'});};
async function login(route){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click(`[data-route=${route}]`);if(['inbound','outbound'].includes(route))await p.locator(route==='inbound'?'.p04-tools':'.p05-tools').evaluate(e=>e.open=true);}
async function scan(o,code){await p.fill(`#${o}-code`,code);await p.press(`#${o}-code`,'Enter');}
async function entry(){await login('inbound');await act('p04','next').click();await act('p04','manual').click();await scan('p04','HN12345');await act('p04','next').click();}
try{
await login('inbound');await act('p04','next').click();await act('p04','batch').click();await act('p04','manual').click();await p.click('[data-p04-filter=valid]');
await check('Inbound context, capability-aware primary and manual return preserve filters/raw/scroll/selection',async()=>{await p.fill('#p04-code','HN-BAD-RAW');const before=await snap('p04');const y=await p.evaluate(()=>{const input=document.querySelector('#p04-code');input.focus({preventScroll:true});input.setSelectionRange(2,5);const scroll=document.querySelector('.p04-scroll');scroll.scrollTop=130;const y=scroll.scrollTop;input.form.requestSubmit();return y;});await p.waitForSelector('.p17-app');assert.match(await p.locator('.p17-context').innerText(),/PN-0005/);assert.match(await p.locator('.p17-context').innerText(),/11 mã hợp lệ/);assert.equal(await p.locator('.p17-footer .p17-primary').getAttribute('data-p04'),'exception-manual');assert.equal(await p.locator('.p17-footer').innerText().then(t=>t.includes('Quét lại')),false);await shot('S01-primary-manual');await act('p04','exception-manual').click();assert.equal(await p.inputValue('#p04-code'),'HN-BAD-RAW');assert.equal(await p.locator('#p04-code').evaluate(e=>e===document.activeElement),true);assert.deepEqual(await p.locator('#p04-code').evaluate(e=>[e.selectionStart,e.selectionEnd]),[0,10]);assert.equal(await p.locator('[data-p04-filter=valid]').getAttribute('aria-pressed'),'true');assert.ok(Math.abs(await p.locator('.p04-scroll').evaluate(e=>e.scrollTop)-y)<2);assert.deepEqual((await snap('p04')).accepted,before.accepted);await shot('inbound-restored');});
await login('outbound');await address(p);await p.fill('[data-p05-field=planned]','10');await act('p05','next').click();await act('p05','batch').click();await act('p05','manual').click();await act('p05','filter-duplicate').click();
await check('Outbound blocked return restores input selection, filter, position and all accepted codes',async()=>{await p.fill('#p05-code','HN99999');const before=await snap('p05'),y=await p.evaluate(()=>{const i=document.querySelector('#p05-code');i.focus({preventScroll:true});i.setSelectionRange(1,3);const s=document.querySelector('.p05-scroll');s.scrollTop=90;const y=s.scrollTop;i.form.requestSubmit();return y;});await p.waitForSelector('[data-panel="P17.S02"]');await shot('S02-context');await act('p05','exception-return').click();assert.equal(await p.locator('#p05-code').evaluate(e=>e===document.activeElement),true);assert.deepEqual(await p.locator('#p05-code').evaluate(e=>[e.selectionStart,e.selectionEnd]),[1,3]);assert.equal(await act('p05','filter-duplicate').getAttribute('aria-pressed'),'true');assert.ok(Math.abs(await p.locator('.p05-scroll').evaluate(e=>e.scrollTop)-y)<2);assert.deepEqual((await snap('p05')).accepted,before.accepted);});
await entry();await p.selectOption('[data-p04-outcome]','timeout-recorded');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');
await check('Scoped copy has whitelisted identity only; success/failure dialogs restore focus and preserve request',async()=>{const before=await snap('p04');assert.equal(await p.locator('.p17-verifying h2').innerText(),'Chưa xác định kết quả gửi');await p.locator('.p17-identity summary').click();await act('p04','copy-reconciliation').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Đã sao chép/);const text=await p.evaluate(()=>copied.at(-1));assert.ok(text.includes(before.request.requestId));assert.ok(text.includes(before.document.scanSessionId));assert.ok(!text.includes('supplier'));assert.ok(!text.includes('HN12345'));assert.equal((await snap('p04')).metrics.recordCalls,1);await shot('copy-success');await p.keyboard.press('Escape');await p.waitForTimeout(100);assert.equal(await act('p04','copy-reconciliation').evaluate(e=>e===document.activeElement),true);await p.evaluate(()=>copyMode='error');await act('p04','copy-reconciliation').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Không thể sao chép tự động/);assert.ok((await p.locator('.hn-action-dialog[open]').innerText()).includes(before.request.requestId));await shot('copy-fallback');await p.keyboard.press('Escape');await p.waitForTimeout(100);assert.deepEqual((await snap('p04')).request,before.request);});
await check('Checking title, pending focus, single flight and persistent verified announcement',async()=>{const before=await snap('p04');await act('p04','check').click();assert.equal(await p.locator('.p17-verifying h2').innerText(),'Đang kiểm tra kết quả gửi…');assert.equal(await act('p04','check').evaluate(e=>e===document.activeElement),true);assert.equal(await act('p04','check').getAttribute('aria-disabled'),'true');assert.equal(await p.locator('.p17-identity').evaluate(e=>e.open),true);await act('p04','check').dispatchEvent('click');await shot('S04-checking');await p.waitForSelector('[data-panel="P04.S04"]');await p.waitForFunction(()=>document.querySelector('[data-hn-announcement="p04-exception"]')?.textContent.includes('Đã xác minh'));assert.deepEqual((await snap('p04')).request,before.request);assert.equal((await snap('p04')).metrics.recordCalls,1);await shot('verified-announcement');});
await entry();await p.selectOption('[data-p04-outcome]','status-unavailable');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');
await check('Unavailable status does not imply work; delayed clipboard completion after exit opens nothing',async()=>{assert.equal(await p.locator('.p17-verifying h2').innerText(),'Cần đối chiếu trên Web');assert.equal(await act('p04','check').isDisabled(),true);await shot('S04-unavailable');await p.locator('.p17-identity summary').click();await p.evaluate(()=>copyMode='pending');await act('p04','copy-reconciliation').click();await act('p04','home').click();await p.evaluate(()=>resolveCopy());await p.waitForTimeout(100);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('#hn-home').isVisible(),true);});
await entry();await p.selectOption('[data-p04-outcome]','timeout-recorded');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');
await check('Late reconciliation cannot announce a result for a different newly allocated document',async()=>{await act('p04','check').click();await act('p04','home').click();await p.waitForTimeout(1250);await p.click('[data-route=inbound]');await p.waitForSelector('[data-panel="P04.S01"]');assert.equal(await p.locator('[data-hn-announcement="p04-exception"]').innerText(),'');});
await p.route('**/home/home.mjs*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('docs/flows/home/home.mjs','utf8').replace('onSystemError:showSystem,supplierHistory','readList:window.p16Read,onSystemError:showSystem,supplierHistory')}));
await p.addInitScript(()=>{window.mode='ready';window.p16Read=()=>{if(mode==='pending')return new Promise(r=>window.resolveRead=r);if(mode==='error')throw Error('read');return rows;};});
await p.goto('http://localhost:8766/flows/auth-session/');await p.evaluate(async()=>window.rows=(await import('/flows/documents/document-model.mjs')).mergeDocuments([]));await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('[data-tab=documents]');
await check('P16 retry keeps keyboard position in list and announces short loading/result text',async()=>{await p.evaluate(()=>mode='error');await p.fill('#p12-query','PN-0005');await p.press('#p12-query','Enter');await p.waitForSelector('[data-panel="P16.S04"]');await p.evaluate(()=>mode='pending');await act('p12','retry').click();assert.equal(await p.locator('.p12-records').evaluate(e=>e===document.activeElement),true);await p.waitForFunction(()=>document.querySelector('[data-hn-announcement="p16-data"]')?.textContent.includes('Đang'));await p.evaluate(()=>resolveRead(rows));await p.waitForSelector('.p12-record');assert.equal(await p.locator('.p12-records').evaluate(e=>e===document.activeElement),true);assert.equal(await p.inputValue('#p12-query'),'PN-0005');await p.waitForFunction(()=>document.querySelector('[data-hn-announcement="p16-data"]')?.textContent==='Đã tải 1 kết quả chứng từ.');assert.equal(await p.locator('[data-hn-announcement="p16-data"]').getAttribute('aria-atomic'),'true');await shot('P16-retry-focus');await p.click('[data-tab=home]');assert.equal(await p.locator('[data-hn-announcement="p16-data"]').innerText(),'');});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){console.error(e.stack);fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));await p.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});throw e;}finally{await b.close();}})();
