const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.WARRANTY_STABILITY_EVIDENCE_DIR||'handoff/P09/evidence/revision-08');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[];let activeCheck='setup';page.on('pageerror',e=>{errors.push({check:activeCheck,message:e.message,stack:e.stack});console.log('PAGEERROR '+activeCheck+' '+e.stack);});
const act=a=>page.locator(`[data-p09="${a}"]`).first(),dlg=()=>page.locator('.p09-update-dialog'),snap=async()=>JSON.parse(await page.locator('[data-p09-snapshot]').textContent()),panel=p=>page.locator(`[data-panel="${p}"]`).waitFor();
async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('[data-route=warranty]');await panel('P09.S01');}
async function open(id){await page.fill('#p09-query',id);await page.click(`[data-p09-case="${id}"]`);await panel('P09.S03');}
async function close(){await page.keyboard.press('Escape');await dlg().waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.p09Modal);}
async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function check(name,fn){activeCheck=name;await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{
await login();
await check('Search preserves the focused input/IME composition instead of replacing it per keystroke',async()=>{await page.locator('#p09-query').evaluate(e=>{e.dataset.auditIdentity='same-input';e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));});await page.fill('#p09-query','Máy in');assert.equal(await page.locator('#p09-query').getAttribute('data-audit-identity'),'same-input');assert.equal(await page.locator('#p09-query').evaluate(e=>e===document.activeElement),true);assert.ok(await page.locator('.p09-case').count()>0);await page.locator('#p09-query').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await page.fill('#p09-query','');});
await check('Rapid open-case and open-dialog events create one step and one overlay',async()=>{await page.locator('[data-p09-case=BH-001]').evaluate(e=>{e.click();e.click();});await panel('P09.S03');await act('update').evaluate(e=>{e.click();e.click();});await dlg().waitFor();assert.equal(await page.locator('.app-modal-host').count(),1);await page.goBack();await dlg().waitFor({state:'detached'});await panel('P09.S03');await act('back').click();await panel('P09.S01');});
await check('A → B → A retains independent repair drafts; cancel does not write',async()=>{await open('BH-001');await act('update').click();await dlg().locator('[name=result]').fill('Nháp riêng A');await dlg().locator('[name=diagnosis]').fill('Kiểm tra nguồn A');await close();await act('back').click();await panel('P09.S01');await open('BH-007');await act('update').click();assert.equal(await dlg().locator('[name=result]').inputValue(),'');await dlg().locator('[name=result]').fill('Nháp riêng B');await close();await act('back').click();await panel('P09.S01');await open('BH-001');await act('update').click();assert.equal(await dlg().locator('[name=result]').inputValue(),'Nháp riêng A');assert.equal(await dlg().locator('[name=diagnosis]').inputValue(),'Kiểm tra nguồn A');assert.equal((await snap()).writes,0);await capture('case-specific-draft');});
await check('Opening/canceling a later edit does not erase or replace the last confirmed result',async()=>{await dlg().locator('[name=result]').fill('Kết quả A đã lưu');await dlg().locator('[type=submit]').click();await panel('P09.S04');const id=(await snap()).receipt.requestId;await act('view').click();await act('update').click();await dlg().locator('[name=result]').fill('NHÁP KHÔNG ĐƯỢC HIỂN THỊ LÀ THÀNH CÔNG');await close();await page.evaluate(()=>location.hash='#p02/warranty?panel=4&case=BH-001');await panel('P09.S04');assert.match(await page.locator('.p09-result-table').textContent(),/Kết quả A đã lưu/);assert.doesNotMatch(await page.locator('.p09-result-table').textContent(),/NHÁP KHÔNG/);assert.equal((await snap()).writes,1);assert.ok(id);await capture('confirmed-result-retained');});
await check('Stopped warehouse remains readable; forged update cannot bypass guard',async()=>{await login();await page.click('[data-tab=home]');await page.locator('.p03-tools summary').click();await page.selectOption('[data-p03-fixture=warehouse]','stopped');await page.click('[data-route=warranty]');await panel('P09.S01');assert.equal(await act('begin').isDisabled(),true);assert.match(await page.locator('.p09-runtime-note').textContent(),/Kho tạm dừng/);await open('BH-001');assert.equal(await act('update').isDisabled(),true);await capture('warehouse-read-only');await act('update').evaluate(e=>{e.disabled=false;e.click();});assert.equal(await dlg().count(),0);await page.locator('.hn-action-dialog[open]').waitFor();assert.match(await page.locator('.hn-action-dialog[open]').textContent(),/Kho tạm dừng/);await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});assert.equal((await snap()).writes,0);await act('back').click();await panel('P09.S01');await page.selectOption('[data-p03-fixture=warehouse]','active');await page.click('[data-tab=home]');await page.click('[data-route=warranty]');assert.equal(await act('begin').isEnabled(),true);});
await check('Confirmed intake offers Open case after Back, without a duplicate request or extra write',async()=>{await act('begin').click();await page.click('[data-scan-action=manual]');await page.fill('#p09-code','SN-XP420B-BK-0008');await page.locator('#p09-code').press('Enter');await act('fault').click();await page.click('.p09-fault-picker input[value=power-off]');await act('intake').click();await page.click('.p09-dialog [type=submit]');await panel('P09.S03');await page.locator('.hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});const before=await snap();await act('back').click();await panel('P09.S02');assert.equal(await act('intake').count(),0);assert.equal(await act('confirmed-intake').isEnabled(),true);assert.match(await page.locator('.p09-footer-hint').textContent(),/Đã tiếp nhận/);await capture('intake-open-existing');await act('confirmed-intake').click();await panel('P09.S03');assert.equal((await snap()).writes,before.writes);assert.equal((await snap()).receipt.requestId,before.receipt.requestId);});
await check('UNKNOWN banner names the pending case; narrow layout and Return/Back retain request',async()=>{await act('back').click();await panel('P09.S02');await act('back').click();await panel('P09.S01');await open('BH-007');await page.locator('.p09-tools summary').click();await page.selectOption('[data-p09-mode]','unknown');await act('update').click();await dlg().locator('[name=result]').fill('Kết quả cần đối chiếu');await dlg().locator('[type=submit]').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p09-snapshot]').textContent).unknown);const before=(await snap()).request;await page.locator('.hn-action-dialog[open] [data-action-dialog=cancel]').click();await page.locator('.hn-action-dialog[open]').waitFor({state:'detached'});assert.match(await page.locator('.p09-pending-notice').textContent(),/BH-007/);await page.setViewportSize({width:340,height:420});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>{const a=document.querySelector('.p09-app'),s=a.querySelector('.p09-scroll'),f=a.querySelector('.p09-footer'),shell=a.closest('.hn-screen');return{overflow:s.scrollWidth>s.clientWidth,footer:f.getBoundingClientRect().bottom<=shell.getBoundingClientRect().bottom+1,inside:s.getBoundingClientRect().bottom<=f.getBoundingClientRect().top+1};});assert.ok(!m.overflow&&m.footer&&m.inside);await capture('unknown-340x420');await page.setViewportSize({width:494,height:1000});await act('back').click();await panel('P09.S01');assert.deepEqual((await snap()).request,before);await act('reconcile').click();await panel('P09.S04');assert.equal((await snap()).receipt.requestId,before.id);await act('list').click();await panel('P09.S01');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'stability-results.json'),JSON.stringify({checks,errors,production:'NOT_RUN'},null,2));
}catch(e){await page.screenshot({path:path.join(out,'stability-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'stability-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
