const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),{mockGeography,address}=require('./outbound_geography_helpers.cjs');
const out='handoff/P17/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);await mockGeography(p);
const long='Mô tả kiểm tra nhiều dòng\nĐặng Ánh — '.repeat(70)+'W'.repeat(400),medium='Thông tin bổ sung '.repeat(16);
let mode='normal';
await p.route('**/outbound/fixture-adapter.mjs*',r=>{let s=fs.readFileSync('docs/flows/outbound/fixture-adapter.mjs','utf8');if(mode==='long')s=s.replace("reason:'Sản phẩm đã được xuất theo phiếu PX-0004.'",'reason:'+JSON.stringify(long)).replace("name:'Máy in nhiệt XP-420B'",'name:'+JSON.stringify(medium));if(mode==='denied')s=s.replace("readable:true","readable:false");if(mode==='missing')s=s.replace("reason:'Sản phẩm đã được xuất theo phiếu PX-0004.'","reason:null").replace("status:'Đã ghi sổ'","status:null");return r.fulfill({body:s,contentType:'text/javascript'});});
const act=(o,a)=>p.locator(`[data-${o}="${a}"]`).first(),snap=async o=>JSON.parse(await p.locator(`[data-${o}-snapshot]`).textContent());
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
async function login(o='outbound'){await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click(`[data-route=${o}]`);if(o==='outbound')await address(p);await p.locator(o==='outbound'?'.p05-tools':'.p04-tools').evaluate(e=>e.open=true);await act(o==='outbound'?'p05':'p04','next').click();await act(o==='outbound'?'p05':'p04','manual').click();}
async function scan(code,o='p05'){await p.fill(`#${o}-code`,code);await p.press(`#${o}-code`,'Enter');}
async function shot(n){await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});}
try{
mode='long';await login();await scan('HN99999');
await check('250/2000+ Unicode/newlines/long word; full reader preserves source, one modal and Back focus',async()=>{await p.waitForSelector('.hn-read-more:not([hidden])');assert.equal((await snap('p05')).exception.reason,long);const read=p.locator('.p17-reason .hn-read-more');await read.click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok((await p.locator('.app-modal-host').innerText()).includes(long));await shot('reader-long');await p.goBack();await p.waitForTimeout(100);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await read.evaluate(e=>e===document.activeElement),true);for(const [w,h]of [[494,950],[340,420],[1869,940]]){await p.setViewportSize({width:w,height:h});assert.equal(await p.locator('.p17-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false);await p.locator('.p17-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await shot('long-'+w+'x'+h);}assert.equal((await snap('p05')).exception.reason,long);});
await p.setViewportSize({width:494,height:950});mode='denied';await login();await scan('HN99999');
await check('Related document permission false hides details and exposes no route/link',async()=>{await p.waitForSelector('[data-panel="P17.S02"]');assert.equal(await p.locator('.p17-card').count(),1);assert.match(await p.locator('.p17-app').innerText(),/chưa được cấp quyền xem/);assert.equal(await p.locator('.p17-app a').count(),0);assert.equal((await p.locator('.p17-app').innerText()).includes('PX-0004'),false);await shot('restricted-related-document');});
mode='missing';await login();await scan('HN99999');
await check('Missing source reason/status displayed as unknown, never inferred as exported',async()=>{await p.waitForSelector('[data-panel="P17.S02"]');assert.match(await p.locator('.p17-reason').innerText(),/Chưa xác định nguyên nhân/);assert.equal((await p.locator('.p17-card').last().innerText()).includes('Đã ghi sổ'),false);await shot('missing-reason-status');});
mode='normal';await login();await scan('HN12345');await act('p05','next').click();await p.selectOption('[data-p05-outcome]','timeout-recorded');await act('p05','send').click();
await check('Outbound UNKNOWN shares P17.S04 and reconciles existing request, no additional record',async()=>{await p.waitForSelector('[data-panel="P17.S04"]');const before=await snap('p05');assert.match(await p.locator('.p17-header').innerText(),/Gửi phiếu xuất kho/);assert.equal(await act('p05','send').isDisabled(),true);await shot('outbound-unknown');await act('p05','check').click();await p.waitForSelector('[data-panel="P05.S04"]');assert.deepEqual((await snap('p05')).request,before.request);assert.equal((await snap('p05')).metrics.recordCalls,1);});
await login('inbound');await scan('HN12345','p04');await act('p04','next').click();await p.selectOption('[data-p04-outcome]','unknown');await act('p04','send').click();await p.waitForSelector('[data-panel="P17.S04"]');
await check('Explicit status recovery permits same-request retry, result dialog obeys contract',async()=>{const before=await snap('p04');await p.selectOption('[data-p04-outcome]','not-recorded');await act('p04','check').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/chưa được ghi nhận/);assert.equal(await p.locator('.app-modal-host').count(),1);await p.keyboard.press('Escape');await p.waitForTimeout(120);await p.selectOption('[data-p04-outcome]','confirmed');await act('p04','send').click();await p.waitForSelector('[data-panel="P04.S04"]');assert.deepEqual((await snap('p04')).request,before.request);assert.equal((await snap('p04')).metrics.recordCalls,2);});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){console.error(e.stack);await p.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
