const auditOrigin=process.env.PREVIEW_ORIGIN||'http://127.0.0.1:8766';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.LOOKUP_EVIDENCE_DIR||'handoff/P06/evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});
 const checks=[],errors=[],external=[],metrics=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(auditOrigin)&&!r.url().startsWith('data:'))external.push(r.url());});
 await page.addInitScript(()=>{window.__cameraRequests=0;window.__printRequests=0;window.print=()=>window.__printRequests++;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{window.__cameraRequests++;throw Error('no camera');};});
 const act=n=>page.locator(`[data-p06="${n}"]`).first(),snap=async()=>JSON.parse(await page.locator('[data-p06-snapshot]').textContent());
 const feedback=()=>page.locator('.hn-action-dialog[open]');
 const closeFeedback=async()=>{await page.locator('[data-action-dialog="confirm"]').click();await feedback().waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnP06Feedback);};
 const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
 async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),app=document.querySelector('.p06-app'),scroll=app.querySelector('.p06-scroll'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],clientWidth:document.documentElement.clientWidth,dpr:devicePixelRatio,zoom:visualViewport.scale,font:getComputedStyle(app).fontFamily,screen:{width:r.width,height:r.height,bottom:r.bottom},overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,internalOverflow:scroll.scrollWidth>scroll.clientWidth,navBottom:document.querySelector('.hn-nav').getBoundingClientRect().bottom,headerTop:app.querySelector('header').getBoundingClientRect().top,backIcon:app.querySelector('header svg').getBoundingClientRect().width};});metrics.push({name,...m});assert.equal(m.overflow,false);assert.equal(m.internalOverflow,false);const fit=Math.min(1,m.clientWidth/494,m.viewport[1]/950);assert.ok(Math.abs(m.screen.width-494*fit)<1);assert.ok(Math.abs(m.screen.height-950*fit)<1);assert.ok(m.navBottom<=m.screen.bottom+1);assert.ok(m.backIcon>0);}
 async function matrix(name){for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420]]){await page.setViewportSize({width:w,height:h});await capture(name+'-'+w+'x'+h);}await page.setViewportSize({width:494,height:1000});}
 try{
 await page.goto(auditOrigin+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.click('.hn-scanner');
 await check('S01 Home route, count metadata, five items and responsive shell',async()=>{await page.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await page.locator('.p06-card').count(),5);assert.match(await page.locator('.p06-tabs').textContent(),/128.*36/);await matrix('P06-S01');});
 await check('A01 search by code/name/SKU; clear; category+serial; advanced filter has no invented options',async()=>{
  for(const q of ['HN12346','420B (Đen)','XP-420B-BK']){await page.fill('#p06-search',q);assert.equal(await page.locator('.p06-card').count(),1);assert.equal(await page.locator('.p06-card').getAttribute('data-p06-item'),'fixture-item-HN12346');}
  await act('clear').click();assert.equal(await page.locator('.p06-card').count(),5);await page.fill('#p06-search','SN-LK-0001');await page.click('[data-p06-category="components"]');assert.equal(await page.locator('.p06-card').count(),1);assert.equal(await page.locator('#p06-search').inputValue(),'SN-LK-0001');
  await act('clear').click();assert.equal((await snap()).category,'components');await act('filter').click();assert.match(await feedback().textContent(),/chưa có tiêu chí/);await closeFeedback();
  await page.locator('[data-p06-category="components"]').press('ArrowLeft');assert.equal((await snap()).category,'products');assert.equal(await page.locator('[data-p06-category="products"]').evaluate(e=>e===document.activeElement),true);
 });
 await check('A03 zero not unknown; missing serial not SKU, missing stock not zero',async()=>{
  await page.click('[data-p06-item="fixture-item-HN12349"]');assert.match(await page.locator('.p06-hero').textContent(),/Hết hàng/);assert.deepEqual(await page.locator('.p06-stock-link dd').allTextContents(),['0','0','0','0']);await act('back').click();await page.click('[data-p06-category="components"]');await page.locator('.p06-card').click();await page.locator('.p06-tools summary').click();await page.selectOption('[data-p06-scenario]','missing');assert.deepEqual(await page.locator('.p06-stock-link dd').allTextContents(),['—','—','—','—']);await capture('P06-missing-stock');await page.selectOption('[data-p06-scenario]','demo');await act('back').click();await page.click('[data-p06-category="products"]');
 });
 await check('S02 detail correct identity, query/scroll restore by native Back',async()=>{
  await page.fill('#p06-search','XP-420B');await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=75);const before=await page.locator('.p06-scroll').evaluate(e=>e.scrollTop);await page.click('[data-p06-item="fixture-item-HN12345"]');assert.match(await page.locator('.p06-hero').textContent(),/HN12345.*XP-420B.*SN: —/);await page.goBack();await page.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await page.locator('#p06-search').inputValue(),'XP-420B');assert.equal(await page.locator('.p06-scroll').evaluate(e=>e.scrollTop),before);await act('clear').click();await page.click('[data-p06-item="fixture-item-HN12345"]');await matrix('P06-S02');
  await page.locator('[data-p06-image="1"]').click();assert.match(await page.locator('.p06-hero img').getAttribute('src'),/box.png/);await page.locator('[data-p06-image="0"]').click();await act('back').click();await page.click('[data-p06-item="fixture-item-HN12345"]');
 });
 await check('nonzero catalogue scroll restored after native Back under long-content stress',async()=>{
  await act('back').click();const stress=await page.addStyleTag({content:'#home-app .p06-card{min-height:230px!important}'});await page.locator('.p06-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const before=await page.locator('.p06-scroll').evaluate(e=>e.scrollTop);assert.ok(before>100);await page.click('[data-p06-item="fixture-item-HN12349"]');assert.equal((await snap()).listScroll,before);await page.goBack();await page.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await page.locator('.p06-scroll').evaluate(e=>e.scrollTop),before);await stress.evaluate(e=>e.remove());await page.click('[data-p06-item="fixture-item-HN12345"]');
 });
 await check('A04 disabled print keyboard and direct route; warranty permission guard',async()=>{
  assert.equal(await act('print').isDisabled(),true);await act('scan').focus();await page.keyboard.press('Tab');assert.equal(await act('warranty').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.match(await feedback().textContent(),/chưa có serial được xác minh/);await closeFeedback();await act('print').evaluate(e=>{e.disabled=false;e.click();e.disabled=true;});assert.match(await feedback().textContent(),/Không có quyền in/);await closeFeedback();
  await page.evaluate(()=>location.hash='#p02/lookup?panel=2&item=fixture-item-HN12345&action=print');await page.locator('[data-panel="P06.S02"]').waitFor();assert.equal(await page.evaluate(()=>window.__printRequests),0);
 });
 await check('A02 S03 explicit stock and read-only location rows',async()=>{await act('stock').click();assert.deepEqual(await page.locator('.p06-stock-strip strong').allTextContents(),['12','10','1','1']);assert.deepEqual(await page.locator('.p06-location b').allTextContents(),['6','3','2','1']);assert.equal(await page.locator('.p06-location button').count(),0);await matrix('P06-S03');});
 await check('S04 and A05 seven explicit signed events, inclusive type/date and invalid range',async()=>{
  await act('back').click();await act('history').click();assert.equal(await page.locator('.p06-event').count(),7);await matrix('P06-S04');
  await page.selectOption('#p06-type','inbound');assert.equal(await page.locator('.p06-event').count(),3);await page.click('.p06-dates summary');await page.fill('#p06-from','2026-09-01');await page.fill('#p06-to','2026-09-05');await act('dates').click();assert.equal(await page.locator('.p06-event').count(),2);assert.deepEqual(await page.locator('.p06-event-result b').allTextContents(),['+ 10','+ 15']);await capture('P06-history-filtered');
  await page.click('.p06-dates summary');await page.fill('#p06-from','2026-09-09');assert.equal(await act('dates').isDisabled(),true);assert.equal(await page.locator('.p06-event').count(),2);assert.match(await page.locator('#p06-date-error').textContent(),/Ngày bắt đầu không được sau ngày kết thúc/);assert.equal(await page.locator('.p06-dates').evaluate(e=>e.open),true);
  await page.fill('#p06-from','2026-09-01');await page.fill('#p06-to','2026-09-09');await act('dates').click();await page.selectOption('#p06-type','all');await page.locator('.p06-event').first().click();assert.match(await feedback().textContent(),/Chưa xác nhận quyền mở chứng từ/);await closeFeedback();
 });
 await check('P03 scan context, Escape restores focus and one overlay; no camera',async()=>{
  await act('back').click();await act('scan').click();await page.locator('[data-panel="P03.S01"]').waitFor();assert.equal(await page.locator('.p03-dialog').count(),1);await page.keyboard.press('Escape');assert.equal(await act('scan').evaluate(e=>e===document.activeElement),true);await act('scan').click();await page.click('[data-p03-operation="lookup"]');await page.locator('[data-panel="P06.S02"]').waitFor();const nav=JSON.parse(await page.locator('#hn-route-status').textContent());assert.equal(nav.context.itemId,'fixture-item-HN12345');assert.equal(nav.context.returnTo,'P06');assert.equal(await page.evaluate(()=>window.__cameraRequests),0);
 });
 await check('invalid item deep link rejected; read-only lookup works while warehouse stopped',async()=>{
  await page.evaluate(()=>location.hash='#p02/lookup?panel=3&item=missing');await page.locator('[data-panel="P06.S01"]').waitFor();assert.equal(await page.locator('.p06-locations').count(),0);await page.click('.p03-tools summary');await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await page.click('[data-p06-item="fixture-item-HN12345"]');await act('stock').click();assert.equal(await page.locator('.p06-location').count(),4);await page.selectOption('[data-p03-fixture="warehouse"]','active');
 });
 await check('Home/picker re-entry and logout/native Back hides lookup data',async()=>{
  await page.click('[data-tab="home"]');await page.click('[data-tab="lookup"]');await page.click('[data-p03-operation="lookup"]');await page.locator('[data-panel="P06.S01"]').waitFor();await page.locator('.hn-tools > details').first().locator('summary').click();await page.click('#hn-logout');await page.goBack();await page.locator('#login-form').waitFor();assert.equal(await page.locator('.p06-app').count(),0);
 });
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external},null,2));fs.writeFileSync(path.join(out,'render-metrics.json'),JSON.stringify(metrics,null,2));
 }catch(e){await page.screenshot({path:path.join(out,'browser-failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
