const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),base=process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766',out=`handoff/motion/M15/evidence/${before?'before':'after'}`;fs.mkdirSync(out,{recursive:true});
(async()=>{assert.equal(JSON.parse(fs.readFileSync('handoff/flow/FLOW_GATE.json')).gate_status,'PASS');const b=await chromium.launch(),results=[];let p;
try{for(const mode of ['auto','os-reduced','off']){const c=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});p=await c.newPage();p.setDefaultTimeout(20000);const r={mode,checks:[],geometry:{},errors:[],writes:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));p.on('request',q=>{if(!['GET','HEAD'].includes(q.method()))r.writes.push(q.method())});
await p.addInitScript(()=>{window.qaMotion=[];window.qaCamera=0;window.qaVis=0;window.qaSamples=[];window.qaLong=[];const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;EventTarget.prototype.addEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVis++;return add.call(this,t,f,o)};EventTarget.prototype.removeEventListener=function(t,f,o){if(t==='visibilitychange'&&f?.name==='visibility')qaVis--;return remove.call(this,t,f,o)};const native=Element.prototype.animate;Element.prototype.animate=function(frames,o){const item={primitive:this.dataset.motionPrimitive||'',duration:o.duration,frames,cancelled:false};qaMotion.push(item);const a=native.call(this,frames,o),cancel=a.cancel.bind(a);a.cancel=()=>{item.cancelled=true;cancel()};if(item.primitive.startsWith('System')){const node=this,start=performance.now();const sample=()=>{qaSamples.push({primitive:item.primitive,t:performance.now()-start,opacity:getComputedStyle(node).opacity});if(node.isConnected&&performance.now()-start<200)requestAnimationFrame(sample)};requestAnimationFrame(sample)}return a;};if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{qaCamera++;await new Promise(r=>setTimeout(r,30));throw new DOMException('Denied','NotAllowedError')};new PerformanceObserver(l=>qaLong.push(...l.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:true});});
const a=k=>p.locator(`[data-p15="${k}"]`).first(),panel=()=>p.locator('.p15-app:visible'),dialog=()=>p.locator('.app-modal-host dialog');const check=async(name,f)=>{await f();r.checks.push(name);console.log('PASS '+mode+' '+name)};
async function login(){await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#home-app:visible').waitFor();}
async function open(kind){await p.locator('.p15-tools').evaluate(e=>e.open=true);await p.locator(`[data-system-demo="${kind}"]`).evaluate(e=>e.click());await panel().waitFor();}
async function close(){await a('back').click();await p.locator('.p15-app').waitFor({state:'hidden'});await p.waitForTimeout(100);}
async function capture(id){await p.waitForTimeout(260);await p.evaluate(()=>window.scrollTo(0,0));r.geometry[id]=await panel().evaluate(e=>{const s=e.closest('.hn-screen'),box=s.getBoundingClientRect();return {text:e.innerText,rects:Object.fromEntries(['.p15-header','.p15-body','.p15-state-actions','.p15-device-card','.hn-nav'].map(sel=>{const n=s.querySelector(sel),r=n?.getBoundingClientRect();return [sel,r?[r.x-box.x,r.y-box.y,r.width,r.height]:null]}))}});await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});}
await p.goto(base+'/flows/auth-session/');await p.locator('#motion-mode').evaluate(e=>e.closest('details').open=true);await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await login();await c.tracing.start({screenshots:true,snapshots:true,sources:false});
await open('connection');await capture('P15.S01');
if(!before)await check('S01 notice opacity140/80/off, text immediate, no geometry/camera/CTA motion',async()=>{const m=await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='SystemNotice'));assert.equal(m.length,mode==='off'?0:1);if(m.length){assert.equal(m[0].duration,mode==='auto'?140:80);assert.ok(m[0].frames.every(f=>!('transform'in f)&&f.opacity>0));}assert.equal(await p.locator('.p15-state-actions').evaluate(e=>e.getAnimations().length),0);});
await close();if(!before)await check('Old notice does not replay after Back/reopen',async()=>{const n=await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='SystemNotice').length);await open('connection');assert.equal(await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='SystemNotice').length),n);await close();});
await open('forbidden');await capture('P15.S03');if(!before)await check('S03 blocks outgoing content immediately, notice fade only',async()=>{assert.ok(await p.locator('#hn-home').evaluate(e=>e.inert&&getComputedStyle(e).visibility==='hidden'));const e=await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='BlockingGuard'));assert.equal(e.length,mode==='off'?0:1);if(e.length)assert.equal(e[0].duration,mode==='auto'?140:80);});await close();
await open('device');await capture('P15.S04');
if(!before){await check('Live mode switch cancels press without invoking permission or changing content',async()=>{const text=await panel().innerText();const state=await p.evaluate(()=>{document.querySelector('.p15-app [data-p15=camera-guide]').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));const select=document.querySelector('#home-motion-mode');select.value='off';select.dispatchEvent(new Event('change',{bubbles:true}));const root=document.querySelector('.p15-app');const off={mode:root.dataset.hnMotionMode,running:root.getAnimations({subtree:true}).filter(a=>a.playState==='running').length};select.value='auto';select.dispatchEvent(new Event('change',{bubbles:true}));return off});assert.deepEqual(state,{mode:'off',running:0});assert.equal(await panel().innerText(),text);assert.equal(await p.evaluate(()=>qaCamera),0);if(mode==='off')await p.locator('#home-motion-mode').evaluate(e=>{e.value='off';e.dispatchEvent(new Event('change',{bubbles:true}))});});await check('S04 static instructions, one user permission request despite rapid tap',async()=>{assert.equal(await p.evaluate(()=>qaCamera),0);assert.equal(await panel().locator('.p15-device-heading').first().evaluate(e=>e.getAnimations().length),0);await a('camera').evaluate(e=>{e.click();e.click()});await dialog().waitFor();assert.equal(await p.evaluate(()=>qaCamera),1);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));});await close();await check('Ten denied-camera navigation cycles keep permission/listener count stable',async()=>{const listeners=await p.evaluate(()=>qaVis);for(let i=0;i<10;i++){await open('device');await close();}assert.equal(await p.evaluate(()=>qaCamera),1);assert.equal(await p.evaluate(()=>qaVis),listeners);});
await check('Device pressed feedback supports keyboard, guard and shared modal Back/focus',async()=>{await open('device');const n=await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='DeviceFeedback').length);await a('camera-guide').focus();await p.keyboard.press('Enter');await dialog().waitFor();await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await a('camera-guide').evaluate(e=>e===document.activeElement));const e=await p.evaluate(()=>qaMotion.filter(x=>x.primitive==='DeviceFeedback'));assert.equal(e.length-n,mode==='auto'?1:0);await close();});
await check('Offline/online while UNKNOWN never replays mutation; exact owner request retained',async()=>{await p.click('.hn-task[data-route=inbound]');await p.click('[data-p04=next]');await p.locator('.p04-tools').evaluate(e=>e.open=true);await p.click('[data-p04=batch]');await p.click('[data-p04=next]');await p.selectOption('[data-p04-outcome]','timeout-recorded');await p.click('[data-p04=send]');await p.locator('[data-panel="P17.S04"]').waitFor();const snap=async()=>JSON.parse(await p.locator('[data-p04-snapshot]').textContent()),s=await snap();await c.setOffline(true);await p.waitForTimeout(100);await c.setOffline(false);await p.waitForTimeout(100);const t=await snap();assert.equal(t.metrics.recordCalls,1);assert.deepEqual(t.request,s.request);assert.equal(t.unknown,true);r.recordCalls=t.metrics.recordCalls;await open('connection');await close();await p.locator('.p15-tools').evaluate(e=>e.open=true);});
}else await close();
await open('expired');await capture('P15.S02');await c.tracing.stop({path:path.join(out,mode+'-trace.zip')});
if(!before)await check('S02 sensitive caller stays hidden/inert; no security exit or old context snapshot',async()=>{assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert&&getComputedStyle(e).visibility==='hidden'));assert.equal(await panel().locator('.p15-context').count(),0);assert.equal(await panel().evaluate(e=>e.getAnimations({subtree:true}).filter(a=>a.playState==='running').length),0);await p.click('[data-tab=documents]');assert.equal(await panel().getAttribute('data-panel'),'P15.S02');});
await a('login').click();await p.locator('#username').waitFor();if(!before)assert.equal(await p.locator('.p15-app').getAttribute('data-hn-motion-mode'),null);
if(!before){await check('Expiry during pending system history close covers caller in the same task',async()=>{await login();await open('connection');const s=await p.evaluate(()=>{document.querySelector('.p15-app [data-p15=back]').click();document.querySelector('[data-system-demo=expired]').click();const n=document.querySelector('#hn-destination');return {visibility:getComputedStyle(n).visibility,inert:n.inert,expired:document.querySelector('.p15-app:not([hidden])')?.dataset.panel};});assert.deepEqual(s,{visibility:'hidden',inert:true,expired:'P15.S02'});await a('login').click();await p.locator('#username').waitFor();if(!before)assert.equal(await p.locator('.p15-app').getAttribute('data-hn-motion-mode'),null);});
await check('Expiry during shell route fade cancels animations immediately; login has no old data',async()=>{await login();const s=await p.evaluate(()=>{document.querySelector('[data-tab=profile]').click();document.querySelector('[data-system-demo=expired]').click();const d=document.querySelector('#hn-destination');return {hidden:getComputedStyle(d).visibility,inert:d.inert,running:d.getAnimations({subtree:true}).filter(a=>a.playState==='running').length}});assert.deepEqual(s,{hidden:'hidden',inert:true,running:0});await a('login').click();await p.locator('#username').waitFor();if(!before)assert.equal(await p.locator('.p15-app').getAttribute('data-hn-motion-mode'),null);assert.equal(await p.locator('#home-app:visible').count(),0);});
}
if(!before)await check('Auth loss while guide open closes it and blocks caller without an exit snapshot',async()=>{await login();await open('forbidden');await a('contact').click();await dialog().waitFor();const s=await p.evaluate(()=>{document.querySelector('[data-system-demo=expired]').click();const d=document.querySelector('#hn-destination'),modal=document.querySelector('.app-modal-host');return {hidden:getComputedStyle(d).visibility,inert:d.inert,panel:document.querySelector('.p15-app:not([hidden])')?.dataset.panel,modalHidden:!modal||getComputedStyle(modal).visibility==='hidden'}});assert.deepEqual(s,{hidden:'hidden',inert:true,panel:'P15.S02',modalHidden:true});await a('login').click();await p.locator('#username').waitFor();if(!before)assert.equal(await p.locator('.p15-app').getAttribute('data-hn-motion-mode'),null);});
r.camera=await p.evaluate(()=>qaCamera);r.animations=await p.evaluate(()=>qaMotion);r.samples=await p.evaluate(()=>qaSamples);r.longTasks=await p.evaluate(()=>qaLong);assert.deepEqual(r.errors,[]);assert.deepEqual(r.writes,[]);await c.close();}
if(!before){assert.ok(results.every(r=>r.camera===1&&r.recordCalls===1));const old=JSON.parse(fs.readFileSync('handoff/motion/M15/evidence/before/results.json'));for(const r of results)for(const id of ['P15.S01','P15.S02','P15.S03','P15.S04'])assert.deepEqual(r.geometry[id],old.results.find(x=>x.mode===r.mode).geometry[id]);}
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({status:'PASS',before,results},null,2));console.log('PASS M15 '+results.reduce((n,r)=>n+r.checks.length,0)+' groups');
}catch(e){if(p&&!p.isClosed())await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:String(e),results},null,2));throw e;}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
