const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('handoff/P09/evidence/revision-11/audit');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const act=a=>p.locator(`[data-p09="${a}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p09-snapshot]').textContent());
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function enter(serial){if(await act('change-product').count())await act('change-product').click();else await p.click('[data-scan-action=manual]');await p.fill('#p09-code',serial);await p.locator('#p09-code').press('Enter');}
async function shot(name){await p.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
try{await p.goto('http://127.0.0.1:8766/flows/auth-session/?review=p09-r11');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.click('[data-route=warranty]');await act('begin').click();await enter('SN-XP420B-BK-0008');await act('fault').click();await p.click('.p09-fault-picker input[value=usb]');await p.fill('[name=note]','Ghi chú cần giữ');
await check('Same serial with whitespace closes replacement without changing draft/request/receipt',async()=>{const before=await snap();await enter('  SN-XP420B-BK-0008  ');assert.equal(await p.locator('#p09-code').count(),0);assert.equal(await act('intake').isEnabled(),true);assert.deepEqual(await snap(),before);await shot('same-serial-ready');});
await check('Escape and Collapse cancel only unverified replacement, preserve item/fault/note and unlock CTA',async()=>{for(const end of ['Escape','collapse']){const before=await snap();await act('change-product').click();await p.fill('#p09-code','bad-serial');await p.locator('#p09-code').press('Enter');assert.equal(await act('intake').isDisabled(),true);if(end==='Escape')await p.locator('#p09-code').press('Escape');else await p.click('[data-scan-action=collapse]');assert.equal(await p.locator('.hn-scan-entry').count(),0);assert.equal(await act('intake').isEnabled(),true);assert.deepEqual(await snap(),before);assert.equal(await act('change-product').evaluate(e=>e===document.activeElement),true);}await shot('cancel-replacement');});
await check('No-match and matching search Enter cannot silently select a hidden fault or close picker',async()=>{await act('fault').click();for(const text of ['khong-co-loi-nay','nguon']){await p.fill('.p09-fault-picker input[type=search]',text);await p.locator('.p09-fault-picker input[type=search]').press('Enter');assert.equal(await p.locator('.p09-fault-picker').count(),1);assert.equal((await snap()).draft.faultId,'usb');}await p.fill('.p09-fault-picker input[type=search]','');await p.keyboard.press('Escape');assert.equal((await snap()).draft.faultId,'usb');await act('fault').click();await p.fill('.p09-fault-picker input[type=search]','khac');await p.click('.p09-fault-picker input[value=other]');await p.fill('[name=faultOther]','Có tiếng kêu bất thường');assert.equal((await snap()).draft.faultId,'other');});
await check('Known open and closed cases open without entering another fault or creating request',async()=>{for(const [serial,id,closed]of [['HN12345','BH-001',false],['HN12346','BH-002',true]]){await enter(serial);const before=await snap();assert.equal(await act('existing-case').isEnabled(),true);await act('existing-case').click();await p.locator('[data-panel="P09.S03"]').waitFor();assert.match(await p.locator('.p09-case-summary').textContent(),new RegExp(id));assert.equal(await act('update').isDisabled(),closed);assert.equal((await snap()).writes,0);assert.deepEqual((await snap()).request,before.request);await act('back').click();await p.locator('[data-panel="P09.S02"]').waitFor();assert.equal(await p.inputValue('[name=note]'),'Ghi chú cần giữ');}await shot('known-closed-shortcut');});
await check('Existing P18 handoff bridge returns exact case and tab without affecting P09 draft',async()=>{await act('existing-case').click();const before=await snap();await act('handoff').click();await p.locator('.p09-app').waitFor({state:'detached'});await p.goBack();await p.locator('[data-panel="P09.S03"]').waitFor();assert.match(await p.locator('.p09-case-summary').textContent(),/BH-002/);assert.equal(await p.locator('[data-p09-tab=info]').getAttribute('aria-selected'),'true');assert.deepEqual(await snap(),before);await act('back').click();await act('back').click();await p.click('[data-p09-case=BH-007]');});
await check('2000+ identity characters remain fully readable; footer and inputs accessible at six sizes',async()=>{const text=('Thiết bị 🌸 <model> &\n'+'X'.repeat(250)+'\n').repeat(8);await p.evaluate(async text=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(c=>c.id==='BH-007');m.writeWarrantyCase({...c,model:text,serial:'SN-'+text});},text);await p.click('[data-p09-tab=parts]');await p.click('[data-p09-tab=info]');await act('update').click();assert.ok((await p.locator('.p09-update-context').textContent()).includes(text));for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});const m=await p.locator('.p09-update-dialog').evaluate(d=>{const r=d.getBoundingClientRect(),f=d.querySelector('footer').getBoundingClientRect(),c=d.querySelector('.p09-update-context'),body=d.querySelector('.app-modal-body');return {footerInside:f.bottom<=r.bottom+1,bodyHeight:body.clientHeight,contextScrollable:c.scrollHeight>c.clientHeight,overflow:d.scrollWidth>d.clientWidth};});assert.ok(m.footerInside&&m.bodyHeight>200&&m.contextScrollable&&!m.overflow,JSON.stringify(m));metrics.push({width,height,...m});await p.locator('.p09-update-context').focus();await p.keyboard.press('End');await shot('long-identity-'+width+'x'+height);}await p.setViewportSize({width:494,height:1000});});
await check('Validation is not duplicated, textarea Enter does not submit, Escape returns focus and preserves edits',async()=>{await p.fill('.p09-update-dialog [name=result]','   ');assert.equal((await p.locator('.p09-update-dialog').innerText()).split('Nhập kết quả sửa chữa.').length-1,1);await p.fill('.p09-update-dialog [name=result]','Kết quả dòng 1');await p.locator('.p09-update-dialog [name=result]').press('Enter');assert.match(await p.inputValue('.p09-update-dialog [name=result]'),/\n/);assert.equal((await snap()).writes,0);await shot('field-validation-and-footer');await p.keyboard.press('Escape');await p.locator('.p09-update-dialog').waitFor({state:'detached'});assert.equal(await act('update').evaluate(e=>e===document.activeElement),true);await act('update').click();assert.match(await p.inputValue('.p09-update-dialog [name=result]'),/Kết quả dòng 1/);await p.keyboard.press('Escape');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,metrics,errors},null,2));
}catch(e){await p.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await b.close();}})();
