const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.PROFILE_STABILITY_EVIDENCE_DIR||'handoff/P10/evidence/revision-03/stability');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),results=[];
async function check(name,fn){const page=await browser.newPage({viewport:{width:494,height:1000}});page.setDefaultTimeout(4500);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home:visible').waitFor();await page.click('[data-tab=profile]');await page.locator('.p10-app').waitFor();await fn(page);assert.deepEqual(errors,[]);results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message,errors});await page.screenshot({path:path.join(out,`failure-${results.length}.png`),fullPage:true});console.log('FAIL '+name+': '+e.message.split('\n')[0]);}finally{await page.close();}}
const act=(p,a)=>p.locator(`[data-p10="${a}"]`).first();
const panel=(p,n)=>p.locator(`.p10-app[data-panel="P10.S0${n}"]`).waitFor();
await check('UI Back consumes child history; native Back then returns Home, never reopens editor',async p=>{await act(p,'edit').click();await act(p,'back').click();await panel(p,1);await p.goBack();await p.locator('#hn-home:visible').waitFor();});
await check('External hash navigation while a P10 dialog is open reaches matching Home view',async p=>{await act(p,'security').click();await act(p,'security-info').click();await p.locator('.p10-dialog').waitFor();await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home:visible').waitFor();assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.locator('.hn-screen').evaluate(e=>e.inert),false);});
await check('Forward after cancelling native dirty Back retains draft and never duplicates discard dialog',async p=>{await act(p,'edit').click();await p.fill('#p10-name','Bản nhập chưa lưu');await p.goBack();await p.locator('.p10-dialog').waitFor();await act(p,'dialog-close').click();await p.waitForFunction(()=>!history.state?.hnProfileDialog);await panel(p,2);await p.goForward();await p.waitForTimeout(80);assert.equal(await p.locator('.app-modal-host').count(),0);assert.equal(await p.inputValue('#p10-name'),'Bản nhập chưa lưu');await act(p,'back').click();await act(p,'dialog-confirm').click();await panel(p,1);await p.goBack();await p.locator('#hn-home:visible').waitFor();});
await check('S01 scroll/focus returns to invoking menu after child Back',async p=>{await p.locator('.p10-account-group').evaluate(e=>e.style.marginTop='500px');await act(p,'rights').click();await act(p,'back').click();await panel(p,1);assert.equal(await act(p,'rights').evaluate(e=>e===document.activeElement),true);});
await check('Duplicate route delivery does not remount focused editor or jump scroll',async p=>{await act(p,'edit').click();await p.fill('#p10-phone','0909 123 456');await p.locator('#p10-phone').focus();await p.evaluate(()=>{window.p10Input=document.querySelector('#p10-phone');dispatchEvent(new PopStateEvent('popstate',{state:history.state}));});assert.equal(await p.locator('#p10-phone').evaluate(e=>e===window.p10Input&&e===document.activeElement),true);});
await check('No-op Save is disabled; edit enables it; reverting disables it without new validation rules',async p=>{await act(p,'edit').click();assert.equal(await p.locator('[data-p10-save]').isDisabled(),true);await p.fill('#p10-name','Tên khác');assert.equal(await p.locator('[data-p10-save]').isDisabled(),false);await p.fill('#p10-name','Minh Anh');assert.equal(await p.locator('[data-p10-save]').isDisabled(),true);});
await check('Repeated menu click does not add duplicate page entries',async p=>{await p.evaluate(()=>{const b=document.querySelector('[data-p10=rights]');b.click();document.querySelector('[data-p10=back]').click();});await panel(p,1);await p.goBack();await p.locator('#hn-home:visible').waitFor();});
await check('P11 Back followed by P10 Back returns S01 and next Back reaches Home',async p=>{await act(p,'security').click();await act(p,'password').click();await p.locator('.p11-app').waitFor();await p.locator('[data-p11=back]').first().click();await panel(p,4);await act(p,'back').click();await panel(p,1);await p.goBack();await p.locator('#hn-home:visible').waitFor();});
await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({results,passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length},null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();
