const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P20/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
const a=n=>p.locator(`[data-p20="${n}"]`),snap=async()=>JSON.parse(await p.locator('[data-p20-snapshot]').textContent()),pause=()=>p.waitForTimeout(180),shot=async n=>{await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});};
async function route(q){await p.evaluate(q=>location.hash='#p02/component-history?'+q,q);await p.waitForSelector('.p20-app');await pause();}
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p20-tools').evaluate(e=>e.open=true);
await check('First read error never displays empty or false0; retry resolves known empty',async()=>{await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(r=>r.id==='BH-003');m.writeWarrantyCase({...c,ledgerKnown:false});});await route('case=BH-003');await p.waitForSelector('.p20-error');assert.equal(await p.locator('.p20-empty').count(),0);assert.equal(await p.locator('[data-p20-count]').textContent(),'Chưa xác minh');await shot('initial-error');await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(r=>r.id==='BH-003');m.writeWarrantyCase({...c,ledgerKnown:true});});await a('load').click();await p.waitForSelector('.p20-empty');});
await check('Switch case while page loading ignores old response',async()=>{await route('case=BH-001&sample=history');await p.waitForSelector('[data-p20-document]');await p.selectOption('[data-p20-mode]','slow');await a('load').click();await route('case=BH-002');await p.waitForSelector('.p20-end');await p.waitForTimeout(2000);assert.equal((await snap()).caseId,'BH-002');assert.deepEqual((await snap()).items.map(r=>r.id),['XLK-0003']);});
await check('Keyboard load retains focus/end focus; Back restores scroll and control',async()=>{await route('case=BH-001&sample=history');await p.selectOption('[data-p20-mode]','ready');await a('load').focus();await p.keyboard.press('Enter');await p.waitForSelector('.p20-end');assert.equal(await p.locator('.p20-end').evaluate(e=>e===document.activeElement),true);await p.locator('.p20-scroll').evaluate(e=>e.scrollTop=90);const top=await p.locator('.p20-scroll').evaluate(e=>e.scrollTop);await a('info').focus();await p.keyboard.press('Enter');await p.waitForSelector('.p09-app');await p.goBack();await p.waitForSelector('.p20-app');assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollTop),top);assert.equal(await a('info').evaluate(e=>e===document.activeElement),true);});
await check('P20 resumes same P19 draft; verified Post reappears once in same case history',async()=>{await route('case=BH-001');await p.waitForSelector('.p20-end');await a('issue').click();await p.waitForSelector('.p19-app:not(.p20-app)');await p.click('[data-scan-action=manual]');await p.fill('#p19-code','LK0001-HN001');await p.locator('#p19-manual-form button[type=submit]').click();const before=JSON.parse(await p.locator('[data-p19-snapshot]').textContent());await p.goBack();await p.waitForSelector('.p20-app');assert.match(await a('issue').innerText(),/Tiếp tục/);await a('issue').click();const resumed=JSON.parse(await p.locator('[data-p19-snapshot]').textContent());assert.equal(resumed.document.documentId,before.document.documentId);await p.click('[data-p19=review]');await p.click('[data-p19=post]');await p.waitForSelector('[data-panel="P19.S04"]');const r=JSON.parse(await p.locator('[data-p19-snapshot]').textContent()).receipt;await p.click('[data-p19=case]');await p.waitForSelector('.p09-app');await p.click('[data-p09=component-history]');await p.waitForSelector('[data-p20-document="'+r.id+'"]');assert.equal((await snap()).items.filter(d=>d.id===r.id).length,1);assert.equal((await snap()).caseId,'BH-001');await shot('verified-P19-receipt');});
await check('Long context 250/2000 Unicode/newline/unbroken: reader exact, backdrop/Escape/Back/focus and no horizontal overflow',async()=>{const text='Nội dung < & >\n'+('Đầu in 🧰 '.repeat(230))+'X'.repeat(250);await p.evaluate(async text=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(r=>r.id==='BH-005');m.writeWarrantyCase({...c,model:text,customer:text,serial:'SERIAL-'+('Z'.repeat(250))});},text);await route('case=BH-005');await p.waitForSelector('.p20-end');const trigger=p.getByRole('button',{name:'Xem đầy đủ sản phẩm bảo hành',exact:true});await trigger.click();await p.waitForSelector('.hn-action-dialog[open]');assert.equal(await p.locator('.hn-action-dialog[open]').innerText().then(t=>t.includes(text)),true);await p.locator('.app-modal-host').evaluate(e=>e.click());assert.equal(await p.locator('.hn-action-dialog[open]').count(),1);await p.keyboard.press('Tab');assert.equal(await p.locator('.hn-action-dialog[open]').evaluate(e=>e.contains(document.activeElement)),true);await shot('long-reader');await p.keyboard.press('Escape');await pause();assert.equal(await trigger.evaluate(e=>e===document.activeElement),true);await trigger.click();await p.goBack();await pause();assert.equal(await p.locator('.hn-action-dialog[open]').count(),0);assert.match(p.url(),/case=BH-005/);assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await shot('long-context');});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' edge groups PASS');
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
