const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const out=process.env.P14_RECEIPT_DIR||'handoff/P14/evidence/revision-02';fs.mkdirSync(path.join(out,'after'),{recursive:true});
(async()=>{const b=await chromium.launch();const context=await b.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',permissions:['clipboard-read','clipboard-write']});const p=await context.newPage(),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.setFixedTime(new Date('2026-09-29T02:21:00+07:00'));
const dialog=()=>p.locator('.app-modal-host dialog'),copy=()=>p.getByRole('button',{name:'Sao chép mã yêu cầu',exact:true});
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);};
async function receipt(username='minhanh'){await p.goto('http://localhost:8766/flows/auth-session/');await p.click('#forgot');await p.fill('#p14-username',username);await p.locator('.p14-app button[type=submit]').click();await p.locator('[data-panel="P14.S02"]').waitFor();await p.waitForTimeout(90);}
async function close(){await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));}
try{
await receipt();
await check('Receipt three columns and date; native clipboard gets exact complete ID',async()=>{assert.equal(await p.locator('.p14-meta-value time').textContent(),'02:21 · 29/09/2026');assert.equal(await p.locator('.p14-meta-value time').getAttribute('datetime'),'2026-09-28T19:21:00.000Z');const id=await p.locator('[data-hn-readable="Mã yêu cầu"]').textContent();await copy().click();await dialog().getByRole('button',{name:'Đã hiểu',exact:true}).waitFor();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),id);assert.equal(await dialog().getByRole('button',{name:'Hủy',exact:true}).count(),0);await close();assert.ok(await copy().evaluate(e=>document.activeElement===e));});
await check('Six viewport geometries: aligned columns,44px copy,56px dock, short content no scroll',async()=>{for(const [width,height] of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(70);const m=await p.evaluate(()=>{const app=document.querySelector('.p14-app'),s=app.closest('.screen'),rows=[...app.querySelectorAll('.p14-receipt-metadata>div')],r=n=>n.getBoundingClientRect(),btn=app.querySelector('.p14-copy'),scroller=app.querySelector('.p14-scroll'),footer=app.querySelector('.p14-actions'),cta=footer.querySelector('button');return {viewport:[innerWidth,innerHeight],shell:[s.offsetWidth,s.offsetHeight],within:r(s).width<=innerWidth+1&&r(s).height<=innerHeight+1,labels:rows.map(x=>r(x.querySelector('dt')).x),values:rows.map(x=>r(x.querySelector('.p14-meta-value')).x),button:[btn.offsetWidth,btn.offsetHeight],copyCentered:Math.abs((r(btn).top+r(btn).bottom)/2-(r(rows[2].querySelector('.hn-operation-icon')).top+r(rows[2].querySelector('.hn-operation-icon')).bottom)/2)<1,scroll:[scroller.clientWidth,scroller.scrollWidth,scroller.clientHeight,scroller.scrollHeight],dockBelow:r(cta).top>=r(scroller).bottom,ctaHeight:cta.offsetHeight,dividerLeft:getComputedStyle(rows[1],'::before').left};});assert.deepEqual(m.shell,[494,950]);assert.ok(m.within&&m.copyCentered&&m.dockBelow);assert.equal(m.ctaHeight,56);assert.deepEqual(m.button,[44,44]);assert.equal(m.dividerLeft,'58px');assert.ok(m.labels.every(x=>Math.abs(x-m.labels[0])<1));assert.deepEqual(m.labels,m.values);assert.equal(m.scroll[0],m.scroll[1]);assert.equal(m.scroll[2],m.scroll[3]);metrics.push(m);await p.locator('.screen').screenshot({path:path.join(out,`after/S02-${width}x${height}.png`)});}await p.setViewportSize({width:494,height:950});});
await check('Clipboard denied/unavailable uses one failure dialog with source ID; Back/focus/backdrop',async()=>{await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied')}}}));await copy().click();await dialog().waitFor();assert.match(await dialog().textContent(),/Chưa sao chép được/);await p.keyboard.press('Tab');assert.ok(await dialog().evaluate(e=>e.contains(document.activeElement)));await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await copy().evaluate(e=>e===document.activeElement));await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:undefined}));await copy().click();await dialog().waitFor();assert.match(await dialog().textContent(),/Chưa sao chép được/);await close();});
for(const length of [250,2200]){
await check(`Long ${length} source values:2 lines, full reader, exact copy, stable dock and no HTML injection`,async()=>{
const value=Array.from(('Mã🌸<b>_không_mất_\n').repeat(150)).slice(0,length).join('');const username=Array.from(('Nguyễn🌸_dài_').repeat(220)).slice(0,length).join('');
await p.route('**/recovery-shift/model.mjs',async route=>{const r=await route.fetch();let body=await r.text();const original="id:nextReceiptId(issuedAt)";assert.ok(body.includes(original));body=body.replace(original,'id:'+JSON.stringify(value));await route.fulfill({response:r,body});});
await receipt(username);assert.equal(await p.locator('[data-hn-readable="Mã yêu cầu"]').textContent(),value);assert.equal(await p.locator('.p14-meta-value b').count(),0);
for(const label of ['Tên đăng nhập','Mã yêu cầu']){const node=p.locator(`[data-hn-readable="${label}"]`);await p.waitForFunction(label=>document.querySelector(`[data-hn-readable="${label}"]`).dataset.hnTruncated==='true',label);const trigger=p.getByRole('button',{name:'Xem đầy đủ '+label.toLocaleLowerCase('vi'),exact:true});await trigger.click();await dialog().waitFor();assert.equal(await dialog().locator('.app-modal-body').textContent(),label==='Mã yêu cầu'?value:username);await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await trigger.evaluate(e=>document.activeElement===e));}
await p.evaluate(()=>{const write=navigator.clipboard.writeText.bind(navigator.clipboard);navigator.clipboard.writeText=async value=>{window.__p14Copied=value;return write(value);};});await copy().click();await dialog().getByRole('button',{name:'Đã hiểu',exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__p14Copied),value);assert.equal((await p.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n'),value);await close();
const before=await p.locator('[data-p14=login]').boundingBox();await p.locator('.p14-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);assert.deepEqual(await p.locator('[data-p14=login]').boundingBox(),before);const x=await p.locator('.p14-scroll').evaluate(e=>[e.clientWidth,e.scrollWidth]);assert.equal(x[0],x[1]);await p.locator('.screen').screenshot({path:path.join(out,`after/long-${length}.png`)});await p.unroute('**/recovery-shift/model.mjs');
});}
await check('Pinned login CTA returns to login; Back never fabricates a receipt',async()=>{await p.click('[data-p14=login]');await p.locator('#username').waitFor();await p.goBack();assert.equal(await p.locator('[data-panel="P14.S02"]').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'receipt-results.json'),JSON.stringify({status:'PASS',checks,metrics,errors,sourceInjection:'Long receipt IDs only in isolated browser route override; production files and fixture adapter unchanged.'},null,2));
}catch(e){fs.writeFileSync(path.join(out,'receipt-failure.json'),JSON.stringify({error:String(e),checks,errors},null,2));await p.screenshot({path:path.join(out,'failure.png')});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
