const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.SECURITY_LIVE_EVIDENCE_DIR||'handoff/P11/evidence/revision-02/live-preview');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
const p10=a=>page.locator(`[data-p10="${a}"]`).first(),act=a=>page.locator(`[data-p11="${a}"]`).first();
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function login(password='preview'){await page.fill('#username','minhanh');await page.fill('#password',password);await page.click('#submit');}
async function start(){await page.click('#start');await page.locator('#hn-home:visible').waitFor();}
async function account(){await page.click('[data-tab=profile]');await p10('security').click();}
async function dismissNotice(){const d=page.locator('.p11-dialog');if(!await d.count())return;const cancel=d.locator('[data-p11=cancel]');await (await cancel.count()?cancel:d.locator('[data-p11=confirm]')).click();await page.waitForFunction(()=>!history.state?.hnSecurityDialog);}
async function back(){await dismissNotice();await act('back').click();if(await page.locator('.p11-dialog').count()){await page.locator('.p11-dialog [data-p11=confirm]').click();}await page.locator('.p10-app[data-panel="P10.S04"]').waitFor();}
async function shot(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function fill(current,next,confirm=next){await page.fill('#p11-current',current);await page.fill('#p11-next',next);await page.fill('#p11-confirm',confirm);}
async function choose(value){await page.locator('.p11-tools details').evaluate(e=>e.open=true);await page.selectOption('#p11-scenario',value);await page.evaluate(()=>scrollTo(0,0));}
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await login();await start();await account();
await check('Back and immediate reentry during list load settle instead of leaving a spinner',async()=>{await p10('sessions').click();await act('back').click();await p10('sessions').click();await page.locator('[data-p11-revoke]').waitFor();assert.equal(await page.locator('.p11-app').getAttribute('aria-busy'),'false');await back();});
await check('Default session list works without opening review tools',async()=>{await p10('sessions').click();await page.locator('[data-p11-revoke]').waitFor({timeout:7000});assert.equal(await page.locator('[data-session-row]').count(),2);assert.equal(await page.locator('.p11-message:visible').count(),0);await page.waitForFunction(()=>document.querySelector('.p11-app').getAttribute('aria-busy')==='false');await shot('sessions-default');});
await check('Revoke cancel preserves both sessions; confirm removes only selected ID',async()=>{await page.locator('[data-p11-revoke]').click();await page.locator('.p11-dialog [data-p11=cancel]').click();await page.waitForFunction(()=>!history.state?.hnSecurityDialog);assert.equal(await page.locator('[data-session-row]').count(),2);await page.locator('[data-p11-revoke]').click();await page.locator('.p11-dialog [data-p11=confirm]').click();await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('[data-session-row]').count(),1);await shot('session-revoked');await dismissNotice();});
await check('Reenter session list after Home keeps revocation',async()=>{await page.click('[data-tab=home]');await account();await p10('sessions').click();await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('[data-session-row]').count(),1);await back();});
await check('Default password mismatch stays local; correcting it changes shared preview credential',async()=>{await p10('password').click();await fill('preview','preview2','different');await page.click('[data-p11-save]');assert.equal(await page.locator('#p11-confirm').getAttribute('aria-invalid'),'true');await page.fill('#p11-confirm','preview2');await page.click('[data-p11-save]');await page.locator('[data-panel="P11.S03"]').waitFor();assert.equal(await page.locator('input[type=password]').count(),0);await shot('password-changed');await back();});
await check('Old current password is rejected on next change; no stale receipt success',async()=>{await p10('password').click();await fill('preview','unused-next');await page.click('[data-p11-save]');await page.getByText('Mật khẩu hiện tại không đúng.').waitFor();assert.equal(await page.locator('[data-panel="P11.S03"]').count(),0);await back();});
await check('Switching password to sessions clears old error and scroll context',async()=>{await p10('sessions').click();await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('.p11-message:visible').count(),0);assert.equal(await page.locator('.p11-scroll').evaluate(e=>e.scrollTop),0);await shot('sessions-after-password');await back();});
await check('Logout invalidates current session; old password fails and new password logs in via P01',async()=>{await p10('back').click();await p10('logout').click();await p10('dialog-confirm').click();await page.locator('#username').waitFor();await page.goBack();assert.equal(await page.locator('.p11-app').count(),0);await login('preview');await page.getByText('Tên đăng nhập hoặc mật khẩu không đúng.').waitFor();await page.locator('#app .hn-action-dialog[open] [data-action-dialog=confirm]').click();await page.waitForFunction(()=>!history.state?.hnAuthFeedback);await login('preview2');await start();});
await check('New login retains account credential and prior remote revocation',async()=>{await account();await p10('sessions').click();await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('[data-session-row]').count(),1);await back();await p10('password').click();await fill('preview2','preview');await page.click('[data-p11-save]');await page.locator('[data-panel="P11.S03"]').waitFor();await back();});
await check('Explicit disconnected scenario has scoped message; normal preview recovers without account reset',async()=>{await p10('password').click();await choose('blocked');await fill('preview','temporary');await page.click('[data-p11-save]');await page.locator('.p11-dialog').waitFor();await back();await p10('sessions').click();await page.getByText('Chưa kết nối danh sách phiên đăng nhập.',{exact:false}).waitFor();assert.equal(await page.locator('.p11-message:visible').count(),0);await choose('preview');await page.getByText('Không có phiên đăng nhập khác.').waitFor();assert.equal(await page.locator('[data-session-row]').count(),1);});
await check('No secret is persisted to browser storage, history or visible review metadata',async()=>{assert.ok(!await page.evaluate(()=>JSON.stringify([localStorage,sessionStorage,history.state])).then(t=>/preview2|temporary/.test(t)));assert.ok(!await page.locator('.hn-tools').innerText().then(t=>t.includes('preview2')));});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,external},null,2));console.log(`${checks.length} live preview groups PASS`);
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,checks,errors,external},null,2));await shot('failure').catch(()=>{});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
