const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.PROFILE_EVIDENCE_DIR||'handoff/P10/evidence/revision-01');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],metrics=[],errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766')&&!r.url().startsWith('data:'))external.push(r.url());});
const act=a=>page.locator(`[data-p10="${a}"]`).first();
const panel=p=>page.locator(`.p10-app[data-panel="P10.S0${p}"]`).waitFor();
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(name){await page.evaluate(()=>{scrollTo(0,0);return document.fonts.ready;});await page.waitForTimeout(180);await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
async function close(){await act('dialog-close').click();await page.locator('.app-modal-host').waitFor({state:'detached'});await page.waitForFunction(()=>!history.state?.hnProfileDialog);}
async function login(scenario='valid'){await page.goto('http://127.0.0.1:8766/flows/auth-session/');if(scenario!=='valid'){await page.locator('.preview-tools details summary').first().click();await page.selectOption('#scenario',scenario);}await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home:visible').waitFor();await page.click('[data-tab=profile]');await panel(1);}
async function audit(name){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),a=document.querySelector('.p10-app'),b=a.querySelector('.p10-scroll'),footer=a.querySelector('.p10-footer')||s.querySelector('.hn-nav'),r=s.getBoundingClientRect();return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,font:getComputedStyle(a).fontFamily,shell:[s.offsetWidth,s.offsetHeight],overflow:b.scrollWidth>b.clientWidth,pageOverflow:document.documentElement.scrollWidth>innerWidth,footerInside:footer.getBoundingClientRect().bottom<=r.bottom+1,contentAboveFooter:b.getBoundingClientRect().bottom<=footer.getBoundingClientRect().top+1,scroll:[b.scrollHeight,b.clientHeight]};});assert.deepEqual(m.shell,[494,950]);assert.ok(!m.overflow&&!m.pageOverflow&&m.footerInside&&m.contentAboveFooter,JSON.stringify(m));metrics.push({name,...m});await shot(name);}
try{
await login();
await check('Four panels and responsive layout in six viewports; real editable controls',async()=>{for(const p of [1,2,3,4]){if(p!==1){await act(p===2?'edit':p===3?'rights':'security').click();await panel(p);}for(const [w,h]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await page.setViewportSize({width:w,height:h});await audit(`S0${p}-${w}x${h}`);}await page.setViewportSize({width:494,height:1000});if(p!==1){await act('back').click();await panel(1);}}});
await check('Editor locks email role warehouse; blocked save keeps draft and old identity',async()=>{await act('edit').click();for(const k of ['email','role','warehouse'])assert.equal(await page.locator('#p10-'+k).getAttribute('readonly'),'');await page.fill('#p10-name','Nguyễn Minh Ánh');await page.fill('#p10-phone','0909 123 456');await page.click('[data-p10-save]');assert.match(await page.locator('.p10-dialog').textContent(),/Chưa thể lưu/);await shot('save-blocked');await close();assert.equal(await page.inputValue('#p10-name'),'Nguyễn Minh Ánh');});
await check('Avatar unavailable keeps prior avatar and draft without file or hardware calls',async()=>{const before=await page.locator('.p10-avatar').textContent();await act('avatar').click();assert.match(await page.locator('.p10-dialog').textContent(),/giữ nguyên/);await close();assert.equal(await page.locator('.p10-avatar').textContent(),before);assert.equal(await page.inputValue('#p10-phone'),'0909 123 456');});
await check('Dirty Back uses one contained modal; Escape restores focus, no silent save',async()=>{await act('back').click();assert.equal(await page.locator('.app-modal-host').count(),1);const containment=await page.evaluate(()=>{const a=document.querySelector('.hn-screen').getBoundingClientRect(),d=document.querySelector('dialog[open]').getBoundingClientRect();return d.top>=a.top&&d.bottom<=a.bottom&&d.left>=a.left&&d.right<=a.right;});assert.ok(containment);await shot('dirty-confirm');await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnProfileDialog);assert.equal(await page.inputValue('#p10-name'),'Nguyễn Minh Ánh');assert.equal(await act('back').evaluate(e=>e===document.activeElement),true);});
await check('Browser Back dirty cancel stays editor; confirmed discard returns attempted screen',async()=>{await page.goBack();await page.locator('.p10-dialog').waitFor();await close();await panel(2);assert.equal(await page.inputValue('#p10-name'),'Nguyễn Minh Ánh');await page.goBack();await page.locator('.p10-dialog').waitFor();await act('dialog-confirm').click();await panel(1);assert.equal(await page.locator('.p10-person strong').textContent(),'Minh Anh');await act('edit').click();assert.equal(await page.inputValue('#p10-name'),'Minh Anh');await act('back').click();await panel(1);});
await check('Permissions are six read-only unknowns; cannot toggle or elevate access',async()=>{await act('rights').click();assert.equal(await page.locator('.p10-permissions li').count(),6);assert.equal(await page.locator('.p10-permissions [data-status=unknown]').count(),6);assert.equal(await page.locator('.p10-permissions button,.p10-permissions input').count(),0);await page.locator('[data-permission=inbound]').click();assert.equal(await page.locator('[data-permission=inbound]').getAttribute('data-status'),'unknown');await act('back').click();});
await page.evaluate(()=>{window.p10intents=[];document.addEventListener('hn-scanner-preview:dependency',e=>window.p10intents.push(e.detail));});
await check('P11 password and sessions are mounted and return to exact P10 caller',async()=>{await act('security').click();for(const [a,p]of [['password','P11.S01'],['sessions','P11.S04']]){await act(a).click();await page.locator('.p11-app[data-panel=\"'+p+'\"]').waitFor();assert.equal(await page.locator('.p10-dialog').count(),0);await page.locator('[data-p11=back]').first().click();await panel(4);assert.equal(await page.evaluate(()=>location.hash),'#p02/profile?panel=4');}await act('security-info').click();assert.match(await page.locator('.p10-dialog').textContent(),/mật khẩu mạnh/);await page.goBack();await page.locator('.app-modal-host').waitFor({state:'detached'});await panel(4);await act('back').click();});
await check('End shift opens P14; preserves account and draft storage',async()=>{await page.evaluate(()=>localStorage.setItem('hn-p10-qa-draft','preserve'));await act('shift').click();await page.locator('[data-panel="P14.S03"]').waitFor();assert.ok(await page.locator('[data-p14=end]').isDisabled());await page.locator('[data-p14=back]').click();await panel(1);assert.equal(await page.evaluate(()=>localStorage.getItem('hn-p10-qa-draft')),'preserve');});
await check('Shared scanner dialog can open/close above profile; no overlay stack',async()=>{await page.click('[data-tab=lookup]');await page.locator('.p03-screen').waitFor();await page.goBack();await page.locator('.p03-screen').waitFor({state:'detached'});await panel(1);assert.equal(await page.locator('.app-modal-host').count(),0);});
await check('Dialog keyboard focus cycles inside and Enter activates button',async()=>{await act('security').click();await act('security-info').click();await page.keyboard.press('Shift+Tab');assert.equal(await page.locator('.p10-dialog').evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Tab');assert.equal(await page.locator('.p10-dialog').evaluate(e=>e.contains(document.activeElement)),true);await page.keyboard.press('Enter');await page.waitForFunction(()=>!history.state?.hnProfileDialog);await panel(4);await act('back').click();});
await check('Logout invokes P01, preserves draft storage; browser Back cannot restore session',async()=>{const count=await page.evaluate(()=>window.p10intents.length);await act('logout').click();await act('dialog-confirm').click();await page.locator('#username').waitFor();assert.equal(await page.evaluate(()=>window.p10intents.length),count);assert.equal(await page.evaluate(()=>localStorage.getItem('hn-p10-qa-draft')),'preserve');await page.goBack();await page.locator('#username').waitFor();assert.equal(await page.locator('#home-app').isVisible(),false);await page.evaluate(()=>localStorage.removeItem('hn-p10-qa-draft'));});
await check('Other actor shares P01 identity without Minh Anh contact leakage',async()=>{await login('other-user');assert.equal(await page.locator('.p10-person strong').textContent(),'Lan Nguyễn');await act('edit').click();assert.equal(await page.inputValue('#p10-name'),'Lan Nguyễn');assert.equal(await page.inputValue('#p10-email'),'');assert.equal(await page.inputValue('#p10-phone'),'');});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors,externalRequests:external,production:'NOT_RUN'},null,2));fs.writeFileSync(path.join(out,'metrics.json'),JSON.stringify(metrics,null,2));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}
})();
