const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P21/evidence/revision-01/edges';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
const a=n=>p.locator(`[data-p21="${n}"]`),snap=async()=>JSON.parse(await p.locator('[data-p21-snapshot]').textContent()),issue=async()=>JSON.parse(await p.locator('[data-p19-snapshot]').textContent());
const shot=async n=>p.locator('.hn-screen').screenshot({path:out+'/'+n+'.png'});
async function test(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function route(q){await p.evaluate(q=>location.hash='#p02/component-resume?'+q,q);await p.waitForSelector('.p21-app');}
async function demo(scene){await p.click(`[data-p21-demo="${scene}"]`);await p.waitForSelector('.p21-app');await p.waitForTimeout(350);}
try{await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p21-tools').evaluate(e=>e.open=true);
await test('Multiple drafts render from owner; keep each ID and scan session',async()=>{const ids=[];for(const caseId of ['BH-001','BH-003']){await p.evaluate(caseId=>location.hash='#p02/component-issue?case='+caseId,caseId);await p.waitForSelector('#home-app .p19-app');await p.click('[data-scan-action=manual]');await p.fill('#p19-code','BOX-LK-0002-01');await p.locator('#p19-manual-form button[type=submit]').click();await p.locator('.p19-sheet button[type=submit]').click();await p.waitForTimeout(200);ids.push((await issue()).document.documentId);}await route('panel=1');assert.equal((await snap()).drafts.length,2);for(const id of ids){await p.locator('[data-p21=open][data-doc="'+id+'"]').click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.equal((await snap()).current.document.documentId,id);await a('back').click();await p.waitForSelector('[data-panel="P21.S01"]');}await shot('two-drafts');});
await test('Long names/IDs keep original Unicode and readable dialog within app',async()=>{const long='Dữ liệu < & >\n'+('Linh kiện 🧰 '.repeat(230))+'Z'.repeat(250);await p.evaluate(async value=>{const m=await import('/flows/shared/warranty-cases.mjs'),c=m.readWarrantyCases().find(c=>c.id==='BH-001');m.writeWarrantyCase({...c,model:value});},long);await demo('resume');const read=p.getByRole('button',{name:'Xem đầy đủ sản phẩm bảo hành',exact:true});await read.click();await p.waitForSelector('.hn-action-dialog[open]');assert.equal(await p.locator('.hn-action-dialog[open]').innerText().then(t=>t.includes(long)),true);await p.keyboard.press('Tab');assert.equal(await p.locator('.hn-action-dialog[open]').evaluate(e=>e.contains(document.activeElement)),true);await shot('long-reader');await p.keyboard.press('Escape');await p.waitForTimeout(180);assert.equal(await read.evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.p21-scroll').evaluate(e=>e.scrollWidth>e.clientWidth+1),false);await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');m.resetWarrantyCases();});});
await test('Hanging read cancelled on Back; no late repaint or write unlock',async()=>{await demo('resume');await p.selectOption('[data-p21-source]','hanging');await a('back').click();await a('open').click();await p.waitForFunction(()=>document.querySelector('.p21-app')?.getAttribute('aria-busy')==='true');const before=(await snap()).current;await a('back').click();await p.waitForSelector('[data-panel="P21.S01"]');await p.waitForTimeout(300);assert.equal(await p.locator('[data-panel="P21.S01"]').count(),1);await route('panel=2&doc='+before.document.documentId+'&sample=b21');await p.selectOption('[data-p21-source]','ready');await a('back').click();await a('open').click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.deepEqual((await snap()).current.document,before.document);});
await test('Read error is not empty; retry keeps all references and resolves',async()=>{await demo('resume');const before=(await snap()).current;await p.selectOption('[data-p21-source]','error');await a('back').click();await a('open').click();await p.waitForSelector('[data-panel="P21.S03"]');assert.equal((await snap()).current.verification,'unverified');assert.deepEqual((await snap()).current.lines,before.lines);await p.selectOption('[data-p21-source]','ready');await a('reload').click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.deepEqual((await snap()).current.document,before.document);});
await test('Post resolves while P21 visible: subscription removes busy and never permits another Post',async()=>{await p.locator('.p19-tools:not(.p21-tools)').evaluate(e=>e.open=true);await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-003');await p.waitForSelector('.p19-app:not(.p21-app)');await p.click('[data-p19=review]');await p.selectOption('[data-p19-outcome]','ready');const before=await issue();await p.locator('[data-p19=post]').evaluate(e=>{e.click();});await route('panel=4&doc='+encodeURIComponent(before.document.documentId));await p.waitForSelector('[data-p21=posted]');assert.equal((await snap()).current.receipt.status,'POSTED');assert.equal(await a('scan').count(),0);assert.equal(await a('check').count(),0);await shot('post-completed-while-away');});
await test('UNKNOWN status checks repeat safely and explicit not-posted preserves request for deliberate review',async()=>{await p.evaluate(()=>location.hash='#p02/component-issue?case=BH-001');await p.waitForSelector('.p19-app:not(.p21-app)');await p.click('[data-p19=review]');await p.selectOption('[data-p19-outcome]','unknown');await p.click('[data-p19=post]');await p.waitForSelector('.hn-action-dialog[open]');await p.getByRole('button',{name:'Để sau',exact:true}).click();await p.waitForTimeout(200);const before=await issue();await p.click('[data-p19=back]');await p.waitForSelector('[data-p21=check]');await a('check').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Chưa xác định/);await p.getByRole('button',{name:'Đóng',exact:true}).click();await p.waitForTimeout(180);assert.deepEqual((await snap()).current.request,before.request);await p.selectOption('[data-p19-outcome]','not-posted');await a('check').click();await p.waitForSelector('.hn-action-dialog[open]');assert.match(await p.locator('.hn-action-dialog[open]').innerText(),/Đã xác minh chưa xuất/);await p.getByRole('button',{name:'Đóng',exact:true}).click();await p.waitForSelector('[data-p21=scan]:not(:disabled)');assert.deepEqual((await snap()).current.request,before.request);await a('review').click();await p.waitForSelector('[data-p19=post]');assert.equal((await issue()).metrics.post,before.metrics.post);assert.equal((await issue()).document.version,before.document.version);});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
