const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.OUTBOUND_EVIDENCE_DIR||'handoff/P05/evidence/revision-11/before');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1}),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&m.text().includes('Không tải được prototype'))errors.push(m.text());});page.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());await mockGeography(page);
const act=n=>page.locator(`[data-p05="${n}"]`).first(),field=n=>page.locator(`[data-p05-field="${n}"]`),sel=n=>page.locator(`[data-p05-select="${n}"]`),snap=async()=>JSON.parse(await page.locator('[data-p05-snapshot]').textContent());
const ready=async()=>{await page.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="outbound"]').click();await address(page);};
const frames=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function probe(name,fn){try{await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){checks.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+': '+e.message);await page.locator('.hn-screen').screenshot({path:path.join(out,`failure-${checks.length}.png`)});if(!process.env.P05_AUDIT_BEFORE)throw e;}}
try{
 await ready();await probe('one natural click from valid address into group opens picker, no swallowed click',async()=>{
  await sel('group').scrollIntoViewIfNeeded();await field('address').focus();const box=await sel('group').boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await frames();assert.equal(await page.locator('.app-modal-host dialog[open]').count(),1);await page.keyboard.press('Escape');
 });
 await ready();await probe('quantity remains visually anchored when moving focus out of completed shipping',async()=>{
  await field('planned').scrollIntoViewIfNeeded();await field('address').focus();const before=await field('planned').boundingBox();await page.mouse.click(before.x+30,before.y+15);await frames();const after=await field('planned').boundingBox();assert.ok(Math.abs(before.y-after.y)<1,`quantity jumped ${after.y-before.y}px`);await page.keyboard.press('ControlOrMeta+A');await page.keyboard.type('12');assert.equal(await field('planned').inputValue(),'12');
 });
 await ready();await probe('collapsed card opens with focused recipient fully visible inside scroll region',async()=>{
  await act('complete-shipping').click();await page.locator('.p05-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await act('edit-shipping').click();await frames();const visible=await sel('recipient').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.p05-scroll').getBoundingClientRect();return a.top>=b.top&&a.bottom<=b.bottom;});assert.equal(visible,true);await page.locator('.hn-screen').screenshot({path:path.join(out,'shipping-open.png')});
 });
 await ready();await field('planned').fill('10');await act('next').click();await page.locator('.p05-tools summary').click();await act('batch').click();await act('manual').click();
 await probe('continuing already-open manual input does not discard typed raw or resize progress/header',async()=>{await page.fill('#p05-code','HN12352');const h=await page.locator('.p05-live-progress').boundingBox();await act('continue').click();assert.equal(await page.inputValue('#p05-code'),'HN12352');assert.deepEqual(await page.locator('.p05-live-progress').boundingBox(),h);});
 await probe('filter focus stays visible after results shrink and Xem tất cả has actual meaning',async()=>{await act('all').click();await page.locator('.p05-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await act('filter-error').click();assert.equal(await page.locator('.p05-attempt').count(),0);const b=await act('filter-error').boundingBox(),a=await page.locator('.p05-scroll').boundingBox();assert.ok(b.y>=a.y-1&&b.y+b.height<=a.y+a.height+1);assert.equal(await act('all').count(),0);await act('filter-all').click();});
 await probe('blocked scan return and header Back keep exact draft and restore manual path',async()=>{await page.fill('#p05-code','HN99999');await page.locator('#p05-code').press('Enter');await page.locator('[data-panel="P17.S02"]').waitFor();const before=await snap();await page.locator('.p17-header button').click();await page.locator('[data-panel="P05.S02"]').waitFor();assert.deepEqual((await snap()).accepted,before.accepted);assert.equal((await snap()).document.documentId,before.document.documentId);});
 await act('next').click();await probe('quick edit can change metadata then return to review without losing scroll-independent data',async()=>{const before=await snap();await act('edit-review').click();await field('phone').fill('0987654321');await act('next').click();assert.equal((await snap()).step,3);assert.deepEqual((await snap()).accepted,before.accepted);assert.equal((await snap()).document.phone,'0987654321');});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));
}catch(e){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
