const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=process.env.NOTIFICATION_CONTENT_EVIDENCE_DIR||'handoff/P13/evidence/revision-06';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const detail=()=>p.locator('.p13-more-info'),summary=()=>detail().locator('summary'),dialog=()=>p.locator('.app-modal-host dialog');
async function route(id){await p.evaluate(id=>location.hash='#p02/notifications?panel=2&event='+id,id);await p.locator('[data-panel="P13.S02"]').waitFor();await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));}
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-bell');await p.locator('[data-p13-loaded=true]').waitFor();
await check('5 event categories: message first, one timestamp, source available, correct contextual CTA',async()=>{for(const [name,category,doc]of [['warehouse','Thông báo kho',false],['nfc','Thông báo thiết bị NFC',false],['inbound','Thông báo nhập kho',true],['outbound','Thông báo xuất kho',true],['warranty','Thông báo bảo hành',true]]){await route('p13-event-'+name);assert.equal(await detail().evaluate(e=>e.open),false);assert.equal(await p.locator('.p13-detail-card time').count(),1);assert.equal(await p.locator('.p13-detail-card .p13-source').count(),1);const order=await p.evaluate(()=>{const r=e=>e.getBoundingClientRect().top;return r(document.querySelector('.p13-summary'))<r(document.querySelector('.p13-narrative'))&&r(document.querySelector('.p13-narrative'))<r(document.querySelector('.p13-more-info'));});assert.ok(order);assert.equal(await p.locator('[data-p13=document]').count(),doc?1:0);assert.equal(await p.locator('.p13-related').count(),doc?1:0);if(doc)assert.ok(await p.locator('.p13-related .p13-status').isVisible());await summary().click();assert.ok((await detail().textContent()).includes(category));assert.deepEqual(await detail().locator('dt').allTextContents(),['Loại thông báo','Người tạo','Kho']);assert.equal(await detail().locator('time').count(),0);await shot(name+'-expanded');await summary().click();await shot(name+'-collapsed');}});
await check('Disclosure keyboard does not add history; P12 Back retains event-specific expansion',async()=>{await route('p13-event-inbound');const length=await p.evaluate(()=>history.length);await summary().focus();await p.keyboard.press('Enter');assert.ok(await detail().evaluate(e=>e.open));await p.keyboard.press('Space');assert.equal(await detail().evaluate(e=>e.open),false);await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>history.length),length);await p.click('[data-p13=document]');await p.locator('.p12-app').waitFor();await p.goBack();await p.locator('.p13-more-info').waitFor();assert.ok(await detail().evaluate(e=>e.open));await route('p13-event-nfc');assert.equal(await detail().evaluate(e=>e.open),false);await route('p13-event-inbound');assert.ok(await detail().evaluate(e=>e.open));});
await check('Collapsed/expanded layout, CTA and locked footer across7 viewports',async()=>{for(const name of ['warehouse','inbound']){await route('p13-event-'+name);for(const [width,height]of [[494,950],[465,875],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));for(const opened of [false,true]){if(await detail().evaluate(e=>e.open)!==opened)await summary().click();const m=await p.evaluate(()=>{const s=document.querySelector('.p13-scroll'),nav=document.querySelector('.hn-nav').getBoundingClientRect(),scan=document.querySelector('.hn-scan-circle').getBoundingClientRect(),h=document.querySelector('.p13-header').getBoundingClientRect();return {viewport:[innerWidth,innerHeight],width:s.clientWidth,scrollWidth:s.scrollWidth,navY:nav.y,headerY:h.y,navDisplay:getComputedStyle(document.querySelector('.hn-nav')).display,buttons:[...document.querySelectorAll('.p13-actions button')].map(e=>e.getBoundingClientRect().bottom),scanTop:scan.top};});assert.equal(m.width,m.scrollWidth);assert.notEqual(m.navDisplay,'none');for(const y of m.buttons)assert.ok(y<m.scanTop);metrics.push({name,opened,...m});await shot(`${name}-${opened?'open':'closed'}-${width}x${height}`);}}}await p.setViewportSize({width:494,height:950});});
await check('Long narrative/source use shared reader; Unicode preserved, Back/keyboard restores focus',async()=>{await route('p13-event-warehouse');for(const selector of ['.p13-narrative [data-hn-readable]','.p13-source']){const text='Nội dung tiếng Việt 🌸\n\n'+('Không_mất_dữ_liệu_'.repeat(140));await p.locator(selector).evaluate((e,t)=>e.textContent=t,text);const button=selector.includes('source')?p.locator('.p13-summary .hn-read-more:visible'):p.locator('.p13-narrative .hn-read-more:visible');await button.waitFor();await button.click();await dialog().waitFor();assert.equal(await dialog().locator('.app-modal-body').textContent(),text);assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok(await p.locator('.hn-nav').evaluate(e=>e.inert));await p.keyboard.press('Tab');assert.ok(await dialog().evaluate(e=>e.contains(document.activeElement)));await shot(selector.includes('source')?'source-reader':'narrative-reader');await p.goBack();await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await button.evaluate(e=>e===document.activeElement));}});
await check('Mark-read retry only appears after failure; no fake acknowledgment action',async()=>{await p.evaluate(()=>location.hash='#p02/notifications');await p.locator('[data-panel="P13.S01"]').waitFor();await p.locator('.p13-tools details').evaluate(e=>e.open=true);await p.selectOption('#p13-dataset','baseline');await p.locator('[data-p13-loaded=true]').waitFor();await p.selectOption('#p13-scenario','read-error');await p.click('[data-p13-event=p13-event-warehouse]');await dialog().waitFor();assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'3');await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('.app-modal-host'));assert.ok(await p.locator('[data-p13=mark-read]').isVisible());await shot('read-retry');await p.selectOption('#p13-scenario','ready');assert.equal(await p.locator('[data-p13=mark-read]').isVisible(),false);await p.evaluate(()=>location.hash='#p02/notifications');await p.locator('[data-panel="P13.S01"]').waitFor();await p.click('[data-p13-event=p13-event-warehouse]');await p.waitForFunction(()=>!document.querySelector('[data-p13=mark-read]'));assert.equal(await p.locator('.hn-bell .hn-count').textContent(),'2');});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'content-first-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'content-first-failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('content-first-failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
