// Development browser regression for P04 alignment with reviewed P05 UX.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.INBOUND_SYNC_EVIDENCE_DIR || 'handoff/P04/evidence/revision-05');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const checks=[],errors=[],metrics=[];page.on('pageerror',e=>errors.push(e.message));
const act=n=>page.locator(`[data-p04="${n}"]`), snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});};
const capture=async(name)=>{await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});};
const submit=async(raw)=>{await page.fill('#p04-code',raw);await page.locator('#p04-code').press('Enter');};
try{
await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');
await page.locator('.hn-task[data-route="outbound"]').click();await page.locator('.p05-app').waitFor();await page.locator('.hn-screen').screenshot({path:path.join(out,'P05-reference-current.png')});await page.locator('[data-p05="back"]').click();await page.locator('.hn-task[data-route="inbound"]').click();
await check('S01 style and popup matches P05 without pushing fields/footer',async()=>{
 await capture('S01');const before=await page.locator('.p04-footer').boundingBox();await page.locator('[data-p04-select="supplier"]').click();assert.equal(await page.getByRole('listbox').count(),1);assert.equal(await page.locator('.p04-select-popup:not([hidden])').count(),1);assert.deepEqual(await page.locator('.p04-footer').boundingBox(),before);await capture('S01-supplier');await page.keyboard.press('Escape');assert.equal(await page.locator('[data-p04-select="supplier"]').evaluate(e=>e===document.activeElement),true);
 await page.locator('[data-p04-note]').fill('Ghi chú đồng bộ');await page.locator('[data-p04-note]').focus();assert.equal(await page.locator('[data-p04-note]').evaluate(e=>getComputedStyle(e).outlineStyle),'none');
});
await act('next').click();
await check('S02 empty gates and disabled hardware',async()=>{assert.equal(await act('next').isDisabled(),true);assert.equal(await act('torch').isDisabled(),true);await act('continue').click();assert.equal(await page.locator('#p04-code').isVisible(),true);assert.equal(await page.locator('.p04-manual').getAttribute('novalidate'),'');});
await check('Empty input inline only; no scan attempt',async()=>{await submit('   ');assert.match(await page.locator('#p04-error-code').textContent(),/Vui lòng/);assert.equal((await snap()).attempts.length,0);await capture('S02-empty-inline');});
await check('Valid clears field, duplicate/invalid retain raw and feedback',async()=>{
 await submit('HN12345');assert.equal(await page.locator('#p04-code').inputValue(),'');assert.match(await page.locator('#p04-error-code').textContent(),/Đã thêm HN12345/);assert.equal(await act('next').isDisabled(),false);await capture('S02-valid');
 await submit('HN12345');assert.equal(await page.locator('#p04-code').inputValue(),'HN12345');assert.equal(await page.locator('#p04-error-code').getAttribute('data-tone'),'duplicate');assert.equal(await page.locator('#p04-code').getAttribute('aria-invalid'),'false');assert.equal((await snap()).accepted.length,1);await capture('S02-duplicate');
 await submit('<invalid>');assert.equal(await page.locator('#p04-code').inputValue(),'<invalid>');assert.equal(await page.locator('#p04-code').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('.p04-attempt script').count(),0);assert.equal(await page.locator('.p04-feedback').isVisible(),false);await capture('S02-invalid');
});
await check('Escape/collapse retains unsent value and focus; compact camera',async()=>{await page.fill('#p04-code','HN12346');await page.locator('#p04-code').press('Escape');assert.equal(await act('manual').evaluate(e=>e===document.activeElement),true);await act('manual').click();assert.equal(await page.locator('#p04-code').inputValue(),'HN12346');assert.equal(await page.locator('.p04-camera').evaluate(e=>e.offsetHeight),128);await submit('HN12346');});
await check('Responsive popup/form/manual stay inside locked shell at six viewports',async()=>{
 for(const [w,h]of [[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]]){await page.setViewportSize({width:w,height:h});await submit('unknown-code');const m=await page.evaluate(()=>{const app=document.querySelector('.p04-app'),screen=document.querySelector('.hn-screen'),a=screen.getBoundingClientRect(),footer=app.querySelector('.p04-footer').getBoundingClientRect(),row=app.querySelector('.p04-code-row').getBoundingClientRect();return{viewport:[innerWidth,innerHeight],layout:[screen.offsetWidth,screen.offsetHeight],overflow:document.documentElement.scrollWidth>innerWidth,inside:row.right<=a.right+1,footer:footer.bottom<=a.bottom+1};});assert.deepEqual(m.layout,[494,950]);assert.equal(m.overflow,false);assert.ok(m.inside&&m.footer);metrics.push(m);await capture(`S02-${w}x${h}`);}
});
await page.setViewportSize({width:1440,height:1000});await act('next').click();await check('Review back preserves data; record once then direct picker creates clean run',async()=>{
 const before=await snap();await page.locator('.p04-footer [data-p04="back"]').click();assert.deepEqual((await snap()).accepted,before.accepted);await act('next').click();await capture('S03');await act('send').click();await page.locator('[data-panel="P04.S04"]').waitFor();await capture('S04');const done=await snap();
 await page.locator('.p03-tools summary').click();await page.locator('[data-p03-open="picker"]').click();await page.locator('[data-p03-operation="inbound"]').click();assert.equal((await snap()).step,1);assert.notEqual((await snap()).document.documentId,done.document.documentId);assert.equal((await snap()).metrics.recordCalls,1);assert.equal((await snap()).document.note,'');
});
await check('Baseline12/11+1 preserved; UNKNOWN survives both route return and fresh intent',async()=>{
 await act('next').click();assert.equal(await page.locator('#p04-code').count(),0);await page.locator('.p04-tools summary').click();await act('batch').click();assert.equal((await snap()).attempts.length,12);assert.equal((await snap()).accepted.length,11);await act('next').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await act('send').click();await page.locator('.p04-unknown').waitFor();const unknown=await snap();await page.goBack();await page.locator('.hn-task[data-route="inbound"]').click();assert.deepEqual((await snap()).request,unknown.request);assert.equal(await act('send').isDisabled(),true);await act('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.equal((await snap()).metrics.recordCalls,unknown.metrics.recordCalls);
});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({passed:checks.length,viewports:metrics.length,errors}));
}catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,error:e.stack,errors},null,2));throw e;}finally{await browser.close();}})();
