const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs');
const out='handoff/P12/evidence/revision-01';
(async()=>{fs.mkdirSync(out,{recursive:true});const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',permissions:['clipboard-read','clipboard-write']});const checks=[],metrics=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);
const action=a=>p.locator(`[data-p12="${a}"]`).first(),dialog=()=>p.locator('.app-modal-host dialog');
const settle=()=>p.waitForFunction(()=>!history.state?.hnDocumentsDialog);
async function close(){await p.keyboard.press('Escape');await settle();}
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function route(hash){await p.evaluate(h=>location.hash=h,hash);await p.waitForFunction(h=>location.hash===h&&document.querySelector('.p12-app'),hash);await p.waitForTimeout(80);}
async function snapshot(){return JSON.parse(await p.locator('[data-p04-snapshot]').textContent());}
try{
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('[data-tab=documents]');await p.locator('.p12-app').waitFor();
await check('A01 correct type/query/partner/status scope and distinct badges',async()=>{assert.equal(await p.locator('.p12-record').count(),6);assert.equal(await p.locator('.p12-record [data-status=posted]').count(),3);await p.fill('#p12-query','minh phat');assert.equal(await p.locator('.p12-record').count(),4);await p.click('[data-p12-type=inbound]');assert.equal(await p.locator('.p12-record').count(),1);await p.fill('#p12-query','');await p.click('[data-p12-type=all]');});
await check('A01 shared filter dates validate, cancel is draft-only, apply combines scope',async()=>{await action('filter').click();await p.fill('#pick-from','09/09/2026');await p.fill('#pick-to','01/09/2026');assert.ok(await dialog().locator('[type=submit]').isDisabled());await p.fill('#pick-to','09/09/2026');await dialog().locator('input[name=status][value=waiting]').check();await dialog().locator('[type=submit]').click();await settle();assert.equal(await p.locator('.p12-record').count(),1);await action('filter').click();await dialog().locator('[data-reset]').click();await dialog().locator('[data-cancel]').first().click();await settle();assert.equal(await p.locator('.p12-record').count(),1);await action('filter').click();await p.fill('#pick-from','');await p.fill('#pick-to','');await dialog().locator('input[name=status][value=all]').check();await dialog().locator('[type=submit]').click();await settle();assert.equal(await p.locator('.p12-record').count(),6);});
await check('A01 loading/empty/error/retry use same list without mutation',async()=>{await p.locator('.p12-tools details').evaluate(e=>e.open=true);for(const mode of ['loading','empty','error']){await p.selectOption('#p12-scenario',mode);assert.equal(await p.locator('.p12-record').count(),0);await shot('state-'+mode);}await action('retry').click();assert.equal(await p.locator('.p12-record').count(),6);await p.evaluate(()=>scrollTo(0,0));});
await check('A01 sorting is applied explicitly',async()=>{await action('sort').click();await dialog().locator('input[name=sort][value=asc]').check();await dialog().locator('[type=submit]').click();await settle();assert.equal(await p.locator('.p12-record-copy strong').first().textContent(),'BH-002');await action('sort').click();await dialog().locator('input[name=sort][value=desc]').check();await dialog().locator('[type=submit]').click();await settle();});
await check('A03 detail preserves document context through file dialog and Back',async()=>{await p.fill('#p12-query','PN-0005');await p.click('[data-p12-doc="fixture-inbound-0005"]');await p.click('[data-p12-tab=files]');await p.locator('[data-p12-file]').first().click();await shot('file-unavailable-dialog');assert.ok((await dialog().textContent()).includes('PN-0005'));assert.equal(await p.locator('.app-modal-host').count(),1);await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await p.goBack();await settle();assert.equal(await p.locator('.p12-files').count(),1);await p.goBack();await p.waitForSelector('.p12-info');await p.goBack();await p.waitForSelector('#p12-query');assert.equal(await p.inputValue('#p12-query'),'PN-0005');await p.fill('#p12-query','');});
await check('A02 quantity11/SKU3, scoped search, immutable row detail',async()=>{await p.click('[data-p12-doc="fixture-inbound-0005"]');await p.click('[data-p12-tab=products]');assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['11','3']);assert.deepEqual(await p.locator('.p12-qty strong').allTextContents(),['5','4','2']);await p.fill('#p12-product-query','ZD421');assert.equal(await p.locator('.p12-product').count(),1);await p.locator('[data-p12-line]').click();assert.ok((await dialog().textContent()).includes('4 Cái'));await close();assert.equal(await p.inputValue('#p12-product-query'),'ZD421');await p.fill('#p12-product-query','');});
await check('A05 posted documents expose no approve/post/delete/edit controls; unknown lines remain unknown',async()=>{await route('#p02/documents?panel=2&doc=b12-outbound-0004');assert.equal(await p.locator('.p12-context [data-status=posted]').count(),1);assert.equal(await p.locator('.p12-app button').filter({hasText:/Duyệt|Ghi sổ|Xóa|Sửa số lượng/}).count(),0);await p.click('[data-p12-tab=products]');assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['—','—']);assert.equal(await p.locator('.p12-product').count(),0);});
await check('All four panels fit without extra scroll across six viewports; capture geometry',async()=>{for(const panel of [1,2,3,4]){await route(`#p02/documents?panel=${panel}${[2,3].includes(panel)?'&doc=fixture-inbound-0005':''}`);for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(45);const m=await p.evaluate(()=>{const s=document.querySelector('.p12-scroll'),app=document.querySelector('.hn-screen'),a=app.getBoundingClientRect();return {panel:document.querySelector('.p12-app').dataset.panel,viewport:[innerWidth,innerHeight],shell:[app.offsetWidth,app.offsetHeight],client:s.clientHeight,scroll:s.scrollHeight,width:s.clientWidth,contentWidth:s.scrollWidth,within:a.width<=innerWidth+1&&a.height<=innerHeight+1};});assert.deepEqual(m.shell,[494,950]);assert.ok(m.scroll<=m.client+1,JSON.stringify(m));assert.equal(m.width,m.contentWidth);assert.ok(m.within);metrics.push(m);await shot(`S0${panel}-${width}x${height}`);}}await p.setViewportSize({width:494,height:950});});
await check('A04 supplier dialog keyboard/backdrop/Escape and metadata stays in P12 until continuing',async()=>{await action('supplier').click();await p.locator('.app-modal-host').click({position:{x:2,y:2}});assert.equal(await dialog().count(),1);await dialog().locator('input[name=choice][value=fixture-supplier-002]').check();await close();assert.ok((await p.locator('#p12-supplier').textContent()).includes('Minh Phát'));await action('supplier').click();await dialog().locator('input[name=choice][value=fixture-supplier-002]').check();await dialog().locator('[type=submit]').click();await settle();await p.fill('#p12-note','P12 kiểm tra chuyển metadata');});
await check('A04 inbound uses sole P04 draft and continues scan; returning preserves form and existing draft',async()=>{await action('continue').click();await p.locator('[data-panel="P04.S02"]').waitFor();const before=await snapshot();assert.equal(before.document.supplierId,'fixture-supplier-002');assert.equal(before.document.note,'P12 kiểm tra chuyển metadata');assert.equal(before.metrics.recordCalls,0);await p.goBack();await p.waitForSelector('#p12-note');assert.equal(await p.inputValue('#p12-note'),'P12 kiểm tra chuyển metadata');await p.fill('#p12-note','Do not overwrite');await action('continue').click();assert.ok((await dialog().textContent()).includes('Tiếp tục phiếu'));await dialog().locator('[data-action-dialog=cancel]').click();await settle();assert.equal((await snapshot()).document.documentId,before.document.documentId);await action('continue').click();await dialog().locator('[data-action-dialog=confirm]').click();await p.locator('[data-panel="P04.S02"]').waitFor();const after=await snapshot();assert.deepEqual(after.document,before.document);assert.equal(after.metrics.recordCalls,0);});
await check('A04 outbound reuses P05 required metadata; warranty reaches P09 intake',async()=>{await p.goBack();await p.waitForSelector('[data-p12-create-type=outbound]');await p.click('[data-p12-create-type=outbound]');await action('continue').click();await p.locator('[data-panel="P05.S01"]').waitFor();assert.equal(await p.locator('[data-p05-field=address]').count(),1);await p.goBack();await p.waitForSelector('[data-p12-create-type=warranty]');await p.click('[data-p12-create-type=warranty]');await action('continue').click();await p.locator('[data-panel="P09.S02"]').waitFor();});
await check('P04 verified receipt opens exact P12 document with live lines; no draft or duplicate record',async()=>{await p.evaluate(()=>location.hash='#p02/inbound');await p.locator('[data-panel="P04.S02"]').waitFor();await p.click('[data-p04=manual]');await p.fill('#p04-code','HN12345');await p.press('#p04-code','Enter');await p.click('[data-p04=next]');await p.click('[data-p04=send]');await p.locator('[data-panel="P04.S04"]').waitFor();const saved=await snapshot();assert.equal(saved.metrics.recordCalls,1);await p.click('[data-p04=document]');await p.locator('.p12-info').waitFor();assert.ok(p.url().includes(encodeURIComponent(saved.document.documentId)));assert.ok((await p.locator('.p12-info').textContent()).includes(saved.document.note));assert.equal(await p.locator('.p12-file').count(),0);await p.goBack();await p.locator('[data-panel="P04.S04"]').waitFor();assert.equal((await snapshot()).document.documentId,saved.document.documentId);await p.click('[data-p04=document]');await p.locator('.p12-info').waitFor();await p.click('[data-p12-tab=products]');assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['1','1']);await p.locator('[data-p12-line]').click();assert.ok((await dialog().textContent()).includes('HN12345'));await close();await route('#p02/documents');assert.equal(await p.locator('[data-p12-doc="'+saved.document.documentId+'"]').count(),1);});
await check('P05 verified receipt reaches P12 by ID; unknown date/serial stays unknown, no inventory delta',async()=>{await p.evaluate(()=>location.hash='#p02/outbound');await p.locator('[data-panel="P05.S01"]').waitFor();await address(p);await p.click('[data-p05=next]');await p.click('[data-p05=manual]');await p.fill('#p05-code','HN12345');await p.press('#p05-code','Enter');await p.click('[data-p05=next]');await p.click('[data-p05=send]');await p.locator('[data-panel="P05.S04"]').waitFor();const saved=JSON.parse(await p.locator('[data-p05-snapshot]').textContent());assert.equal(saved.metrics.inventoryDelta,0);await p.click('[data-p05=document]');await p.locator('.p12-info').waitFor();assert.ok(p.url().includes(encodeURIComponent(saved.document.documentId)));assert.ok((await p.locator('.p12-info').textContent()).includes('Chưa có dữ liệu'));await p.click('[data-p12-tab=products]');assert.deepEqual(await p.locator('.p12-totals strong').allTextContents(),['1','1']);});
await check('Action dialog traps focus, restores trigger, Back/Escape closes before route; six sizes',async()=>{await route('#p02/documents');for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});await p.evaluate(()=>scrollTo(0,0));await action('scan').click();const ok=await dialog().evaluate(d=>{const s=document.querySelector('.hn-screen').getBoundingClientRect(),r=d.getBoundingClientRect();return r.left>=s.left&&r.right<=s.right+1&&r.top>=s.top&&r.bottom<=s.bottom+1;});assert.ok(ok);assert.equal(await p.locator('.app-modal-host').count(),1);assert.ok(await p.locator('#hn-destination').evaluate(e=>e.inert));await p.keyboard.press('Shift+Tab');assert.ok(await dialog().locator('button').evaluate(e=>e===document.activeElement));await shot(`dialog-${width}x${height}`);await close();assert.ok(await action('scan').evaluate(e=>e===document.activeElement));}await p.setViewportSize({width:494,height:950});});
await check('Copy result appears only after clipboard verification and has no fake cancel',async()=>{await p.click('[data-p12-doc="fixture-inbound-0005"]');await action('copy').click();assert.ok((await dialog().textContent()).includes('Đã sao chép'));assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'PN-0005');assert.equal(await dialog().locator('button').count(),1);await close();assert.equal(await p.locator('.p12-info').count(),1);});
await check('Long content remains internally scrollable, header/nav fixed; list Back restores scroll',async()=>{await route('#p02/documents');await p.locator('.p12-record-copy small').evaluateAll(es=>es.forEach(e=>e.textContent='Đối tác tên dài '.repeat(20)));await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=100);const before=await p.locator('.p12-scroll').evaluate(e=>e.scrollTop);await p.locator('[data-p12-doc="fixture-inbound-0005"]').dispatchEvent('click');await p.goBack();await p.waitForSelector('.p12-records');/* baseline restored, clamp to available content is correct */assert.equal(await p.locator('#p12-query').inputValue(),'');await route('#p02/documents?panel=2&doc=fixture-inbound-0005');await p.locator('.p12-kv dd').last().evaluate(e=>e.textContent='Nội dung dài cần đọc đầy đủ. '.repeat(120));const info=await p.locator('.p12-scroll').evaluate(e=>({h:e.clientHeight,s:e.scrollHeight}));assert.ok(info.s>info.h);const y=await p.locator('.p12-header').evaluate(e=>e.getBoundingClientRect().top);await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=1000);assert.ok(await p.locator('.p12-scroll').evaluate(e=>e.scrollTop>0));assert.equal(await p.locator('.p12-header').evaluate(e=>e.getBoundingClientRect().top),y);await shot('long-content-scroll');});
await check('Real long-list fixture pagination scope preserves query and scroll on detail Back',async()=>{await p.evaluate(async()=>{const m=await import('/flows/documents/document-model.mjs');for(let i=0;i<18;i++)m.DOCUMENTS.push({...m.DOCUMENTS[1],id:'stress-'+i,number:'STRESS-'+i,partner:'<img src=x onerror=window.p12Injected=true>'});});await route('#p02/documents');await p.fill('#p12-query','STRESS');assert.equal(await p.locator('.p12-record').count(),18);assert.equal(await p.locator('.p12-record-copy img').count(),0);assert.equal(await p.evaluate(()=>!!window.p12Injected),false);await p.locator('.p12-scroll').evaluate(e=>e.scrollTop=470);const y=await p.locator('.p12-scroll').evaluate(e=>e.scrollTop);await p.locator('[data-p12-doc="stress-10"]').dispatchEvent('click');await p.goBack();await p.waitForSelector('#p12-query');assert.equal(await p.inputValue('#p12-query'),'STRESS');assert.equal(await p.locator('.p12-scroll').evaluate(e=>e.scrollTop),y);await p.evaluate(async()=>{const m=await import('/flows/documents/document-model.mjs');m.DOCUMENTS.splice(6);});});
await check('Logout followed by browser Back cannot restore P12 authenticated route',async()=>{await p.locator('.hn-tools details').first().evaluate(e=>e.open=true);await p.click('#hn-logout');await p.waitForSelector('#username');await p.goBack();assert.equal(await p.locator('.p12-app').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(`${checks.length} groups PASS`);
}catch(e){fs.writeFileSync(path.join(out,'browser-failure.json'),JSON.stringify({message:e.message,checks,metrics,errors},null,2));await shot('failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
