const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require('./outbound_geography_helpers.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const out=process.env.GUIDANCE_EVIDENCE_DIR||'handoff/P12/evidence/revision-09';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true}),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));await mockGeography(p);p.setDefaultTimeout(12000);
const action=(code,a)=>p.locator('[data-'+code+'='+a+']').first(),snapshot=async code=>JSON.parse(await p.locator('[data-'+code+'-snapshot]').textContent());
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function home(){await p.evaluate(()=>location.hash='#home');await p.locator('#hn-home').waitFor({state:'visible'});}
async function create(){await home();await p.click('[data-tab=documents]');await action('p12','create').click();}
async function supplier(id,apply=true){await action('p12','supplier').click();await p.check('[name=choice][value="'+id+'"]');await p.locator('.p12-supplier-picker footer '+(apply?'[type=submit]':'[data-cancel]')).click();await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);}
async function closeFeedback(){const d=p.locator('.app-modal-host dialog');if(await d.count()){await p.keyboard.press('Escape');await p.waitForSelector('.app-modal-host',{state:'detached'});await p.waitForTimeout(60);}}
async function code(prefix,value){if(!await p.locator('#'+prefix+'-code').count())await action(prefix,'manual').click();await p.fill('#'+prefix+'-code',value);await p.press('#'+prefix+'-code','Enter');}
try{
 await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForFunction(()=>location.hash==='#home');await create();
 await check('Current supplier + session recents are unique; Cancel does not add history; search/count ignores tags',async()=>{
  for(const id of ['003','005','009'])await supplier('fixture-supplier-'+id);await supplier('fixture-supplier-014',false);await action('p12','supplier').click();const ids=await p.locator('.p12-supplier-picker [name=choice]').evaluateAll(es=>es.map(e=>e.value));assert.deepEqual(ids.slice(0,3),['fixture-supplier-009','fixture-supplier-005','fixture-supplier-003']);assert.equal(new Set(ids).size,ids.length);assert.equal(await p.locator('.hn-choice-priority').count(),3);const search=p.locator('.p12-supplier-picker input[type=search]');await search.fill('thien long');assert.equal(await p.locator('.p12-supplier-picker .p08-options label:visible').count(),1);assert.match(await p.locator('.hn-choice-count').textContent(),/^1 /);await search.fill('Gần đây');assert.match(await p.locator('.hn-choice-count').textContent(),/^0 /);await search.fill('');await shot('recent-suppliers');await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnDocumentsDialog);
 });
 let draft;
 await check('P12 information step enters P04 adding step; Back preserves metadata and validates first error',async()=>{
  assert.equal(await p.locator('.hn-flow-progress [aria-current=step]').textContent(),'1Thông tin');await p.fill('#p12-note','Phiếu cần đối chiếu trước khi gửi');await action('p12','continue').click();assert.equal((await snapshot('p04')).step,2);assert.match(await p.locator('.hn-flow-progress [aria-current=step]').textContent(),/Thêm sản phẩm/);await code('p04','HN12345');await action('p04','back').click();await p.locator('[data-p04-note]').evaluate(e=>{e.value='A'.repeat(201);e.dispatchEvent(new Event('input',{bubbles:true}));});await action('p04','next').click();assert.equal((await snapshot('p04')).step,1);assert.equal(await p.locator('[data-p04-note]').getAttribute('aria-invalid'),'true');assert.ok(await p.locator('[data-p04-note]').evaluate(e=>e===document.activeElement));await p.fill('[data-p04-note]','Phiếu cần đối chiếu trước khi gửi');await action('p04','next').click();await action('p04','next').click();draft=await snapshot('p04');assert.match(await p.locator('.hn-flow-progress [aria-current=step]').textContent(),/Kiểm tra/);assert.deepEqual(await p.locator('.hn-review-totals strong').allTextContents(),['Nhập kho','1','1']);
 });
 await check('Resume card reopens exact ID,step,accepted codes and notes without creating another draft',async()=>{
  await create();assert.equal(await p.locator('[data-p12-resume=inbound]').count(),1);assert.match(await p.locator('.p12-draft').textContent(),/Bước 3\/3/);await shot('resume-draft');await p.click('[data-p12-resume=inbound]');await p.locator('[data-panel="P04.S03"]').waitFor();let s=await snapshot('p04');assert.deepEqual(s.document,draft.document);assert.deepEqual(s.accepted,draft.accepted);assert.equal(s.step,3);assert.equal(s.metrics.recordCalls,0);
 });
 await check('UNKNOWN card routes to reconciliation and keeps request; no retry before check',async()=>{
  await p.locator('.p04-tools').evaluate(e=>e.open=true);await p.selectOption('[data-p04-outcome]','unknown',{force:true});await action('p04','send').dblclick();await p.waitForFunction(()=>JSON.parse(document.querySelector('[data-p04-snapshot]').textContent).unknown);await closeFeedback();const before=await snapshot('p04');assert.equal(before.metrics.recordCalls,1);await create();assert.match(await p.locator('.p12-draft').textContent(),/Cần đối chiếu/);await shot('resume-unknown');await p.click('[data-p12-resume=inbound]');await p.locator('[data-panel="P17.S04"]').waitFor();const after=await snapshot('p04');assert.deepEqual(after.request,before.request);assert.equal(after.metrics.recordCalls,1);assert.equal(await action('p04','send').isDisabled(),true);assert.ok(await action('p04','check').isVisible());
 });
 await check('Verified not-recorded resume preserves the same request and successful retry stays waiting Web',async()=>{
  await p.selectOption('[data-p04-outcome]','not-recorded',{force:true});await action('p04','check').click();await p.waitForFunction(()=>JSON.parse(document.querySelector('[data-p04-snapshot]').textContent).outcome==='not-recorded');await closeFeedback();const before=await snapshot('p04');await create();assert.match(await p.locator('.p12-draft').textContent(),/Đã xác minh chưa ghi nhận/);await p.click('[data-p12-resume=inbound]');await p.locator('[data-panel="P04.S03"]').waitFor();assert.deepEqual((await snapshot('p04')).request,before.request);await p.goBack();await p.locator('[data-p12-resume=inbound]').waitFor();await p.goForward();await p.locator('[data-panel="P04.S03"]').waitFor();assert.deepEqual((await snapshot('p04')).request,before.request);await p.selectOption('[data-p04-outcome]','confirmed',{force:true});await action('p04','send').dblclick();await p.locator('[data-panel="P04.S04"]').waitFor();const after=await snapshot('p04');assert.deepEqual(after.request,before.request);assert.equal(after.metrics.recordCalls,2);assert.equal(after.metrics.inventoryDelta,0);assert.match(await p.locator('.p04-app').textContent(),/Chờ xử lý trên Web/);assert.equal(await p.locator('.hn-flow-progress').count(),0);await create();assert.equal(await p.locator('[data-p12-resume=inbound]').count(),0);
 });
 await check('Outbound validates missing shipping info, retains scan progress on resume and sends once',async()=>{
  await p.click('[data-p12-create-type=outbound]');await action('p05','next').click();assert.equal((await snapshot('p05')).step,1);assert.ok(await p.locator('[aria-invalid=true]').count());await address(p);await action('p05','next').click();await code('p05','HN12345');await action('p05','close-manual').click();await action('p05','next').click();assert.deepEqual(await p.locator('.hn-review-totals strong').allTextContents(),['Xuất kho','1','1']);const before=await snapshot('p05');await create();await p.click('[data-p12-resume=outbound]');await p.locator('[data-panel="P05.S03"]').waitFor();assert.deepEqual((await snapshot('p05')).document,before.document);assert.deepEqual((await snapshot('p05')).accepted,before.accepted);await shot('outbound-ready');await action('p05','send').dblclick();await p.locator('[data-panel="P05.S04"]').waitFor();assert.equal((await snapshot('p05')).metrics.recordCalls,1);assert.equal((await snapshot('p05')).metrics.inventoryDelta,0);
 });
 await check('Six viewports keep progress/tab labels and CTA inside shell, fresh P12 form needs no extra scroll',async()=>{
  await create();for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){await p.setViewportSize({width,height});const m=await p.evaluate(()=>{const s=document.querySelector('.p12-scroll'),a=document.querySelector('.hn-screen').getBoundingClientRect(),f=document.querySelector('.p12-footer').getBoundingClientRect(),steps=document.querySelector('.hn-flow-progress');return {scroll:s.scrollHeight-s.clientHeight,x:s.scrollWidth-s.clientWidth,footer:f.bottom<=a.bottom+1,steps:steps.scrollWidth<=steps.clientWidth};});assert.ok(m.scroll<=1&&m.x===0&&m.footer&&m.steps,JSON.stringify(m));await shot('create-'+width+'x'+height);}await p.setViewportSize({width:494,height:950});
 });
 await check('Reload creates a fresh session-local supplier history',async()=>{
  await p.reload();await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForFunction(()=>location.hash==='#home');await create();await action('p12','supplier').click();assert.equal(await p.locator('.hn-choice-priority').count(),1);assert.equal(await p.locator('.p12-supplier-picker [name=choice]').first().inputValue(),'fixture-supplier-001');
 });
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'guidance-results.json'),JSON.stringify({checks,errors,visualAcceptance:'NOT_GRANTED'},null,2));console.log(checks.length+' groups PASS');
}catch(e){fs.writeFileSync(path.join(out,'guidance-failure.json'),JSON.stringify({message:e.message,checks,errors},null,2));await shot('guidance-failure').catch(()=>{});throw e;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
