const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const out='handoff/P18/evidence/revision-03/edges';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',acceptDownloads:true}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(14000);
const act=a=>p.locator(`[data-p18="${a}"]`).first(),painted=()=>p.waitForFunction(()=>document.querySelector('.p18-paper')?.getAttribute('aria-busy')==='false'),shot=async n=>{await p.evaluate(()=>scrollTo(0,0));await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});};
const check=async(name,f)=>{await f();checks.push({name,status:'PASS'});console.log('PASS '+name);};
async function route(panel=1){await p.evaluate(panel=>location.hash='#p02/attachments?panel='+panel+'&doc=fixture-inbound-0005'+(panel===2?'&file=b12-attachment-1':''),panel);await p.waitForSelector(`[data-panel="P18.S0${panel}"]`);}
await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');
try{
await check('PDF text is explicit dialog, no invisible Tab stop, Back/focus/pan restored',async()=>{await route(2);await painted();assert.equal(await p.locator('.p18-pdf-text[tabindex]').count(),0);await act('zoom-in').click();await painted();assert.equal(await p.locator('[data-p18-fit]').inputValue(),'custom');await p.locator('.p18-document-viewport').evaluate(e=>e.scrollTop=80);await act('read-text').click();assert.equal(await p.locator('.app-modal-host').count(),1);assert.match(await p.locator('.app-modal-host').innerText(),/BIÊN BẢN KIỂM ĐẾM/);await p.keyboard.press('Tab');assert.equal(await p.locator('.app-modal-host').evaluate(e=>e.contains(document.activeElement)),true);await shot('text-dialog');await p.goBack();await p.waitForTimeout(150);assert.equal(await act('read-text').evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.p18-document-viewport').evaluate(e=>e.scrollTop),80);await p.selectOption('[data-p18-fit]','width');await painted();assert.equal(await p.locator('[data-p18-zoom]').innerText(),'100%');});
await check('Viewer byte cache cannot serve an older file version under new metadata',async()=>{await p.evaluate(async()=>{const m=await import('/flows/documents/document-model.mjs');window.owner=m.DOCUMENTS.find(d=>d.id==='fixture-inbound-0005');window.original=structuredClone(owner.attachments);owner.attachments[0]={...owner.attachments[0],name:owner.attachments[1].name,url:owner.attachments[1].url,version:'new-source'};});const download=p.waitForEvent('download');await act('download').click();const d=await download;await d.saveAs(path.join(out,'current-version.pdf'));assert.equal(d.suggestedFilename(),'PhieuNhap_PN-0005.pdf');assert.deepEqual(fs.readFileSync(path.join(out,'current-version.pdf')),fs.readFileSync('docs/flows/documents/assets/PhieuNhap_PN-0005.pdf'));await p.keyboard.press('Escape');await p.waitForTimeout(160);await p.evaluate(()=>owner.attachments=structuredClone(original));});
await check('Duplicate downloads show busy feedback, source removal mid-read blocks saving',async()=>{await route(1);let release,calls=0;const gate=new Promise(r=>release=r);await p.route('**/BienBanKiemDem_PN-0005.pdf',async r=>{calls++;await gate;await r.continue().catch(()=>{});});let downloads=0;const dl=()=>downloads++;p.on('download',dl);await act('download').dblclick();await p.waitForTimeout(100);assert.equal(calls,1);assert.equal(await act('download').getAttribute('aria-busy'),'true');assert.match(await act('download').innerText(),/Đang tải/);await shot('download-pending');await p.evaluate(()=>owner.attachments=[]);release();await p.waitForSelector('.app-modal-host');assert.equal(downloads,0);assert.match(await p.locator('.app-modal-host').innerText(),/Không tải được/);await p.keyboard.press('Escape');await p.waitForTimeout(160);await p.unroute('**/BienBanKiemDem_PN-0005.pdf');p.off('download',dl);await p.evaluate(()=>owner.attachments=structuredClone(original));});
await check('Render failure exits busy state, exposes retry, and retries the same file',async()=>{const url='**/attachments/vendor/pdf.mjs';await p.route(url,async r=>{const source=await r.fetch(),body=await source.text();await r.fulfill({response:source,body:body.replace('return this._transport.getPage(pageNumber);',"if(!window.__p18RenderError){window.__p18RenderError=true;return Promise.reject(new Error('Test page render failure'));}return this._transport.getPage(pageNumber);")});});await p.reload();await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await route(2);await p.waitForSelector('[data-p18=reload]');assert.equal(await p.locator('.p18-paper').getAttribute('aria-busy'),'false');assert.equal(await act('zoom-in').isDisabled(),true);await shot('render-error-retry');await act('reload').click();await painted();assert.equal(await p.locator('[data-p18-pages]').textContent(),'1 / 1');await p.unroute(url);});
await check('Invalid restored page clamps to an existing PDF page',async()=>{await p.evaluate(()=>{location.hash='#home';});await p.waitForSelector('#hn-home:not([hidden])');await p.evaluate(()=>{history.pushState({p18Page:-2},'','#p02/attachments?panel=2&doc=fixture-inbound-0005&file=b12-attachment-1');dispatchEvent(new PopStateEvent('popstate',{state:history.state}));});await painted();assert.equal(await p.locator('[data-p18-pages]').textContent(),'1 / 1');assert.equal(await p.locator('.app-modal-host').count(),0);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
