const {mockGeography,address:prepareAddress}=require('./outbound_geography_helpers.cjs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.OUTBOUND_EVIDENCE_DIR || 'handoff/P05/evidence/revision-02');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const act=n=>page.locator(`[data-p05="${n}"]`).first();const snap=async()=>JSON.parse(await page.locator('[data-p05-snapshot]').textContent());
 async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS '+name);}
 async function login(){await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#hn-home').waitFor({state:'visible'});}
 async function enter(picker=false){if(picker){await page.locator('[data-tab="lookup"]').click();if(await page.locator('[data-p03-action=resume]').count())await page.locator('[data-p03-action=resume]').click();else await page.locator('[data-p03-operation="outbound"]').click();}else await page.locator('.hn-task[data-route="outbound"]').click();await page.locator('.p05-app').waitFor();}
 async function full(){await prepareAddress(page);await page.fill('[data-p05-field="planned"]','10');await act('next').click();if(!await page.locator('.p05-tools').evaluate(e=>e.open)) await page.locator('.p05-tools summary').click();await act('batch').click();await act('manual').click();for(const c of ['HN12352','HN12353','HN12354']){await page.fill('#p05-code',c);await page.locator('#p05-code').press('Enter');}await act('close-manual').click();await act('next').click();}
 async function dismissFeedback(){if(await page.locator('.hn-action-dialog[open]').count()){await page.keyboard.press('Escape');await page.locator('.app-modal-host').waitFor({state:'detached'});}}
 async function finish(outcome){await full();await page.selectOption('[data-p05-outcome]',outcome);await act('send').click();await page.waitForFunction(()=>{const s=JSON.parse(document.querySelector('[data-p05-snapshot]').textContent);return !s.busy&&(s.outcome||s.unknown);});if(outcome==='failed'){await page.locator('.hn-action-dialog[open]').waitFor();await dismissFeedback();}}
 async function fresh(previous){let s=await snap();assert.equal(s.step,1);assert.equal(s.document.planned,1);assert.notEqual(s.document.documentId,previous.document.documentId);assert.notEqual(s.document.scanSessionId,previous.document.scanSessionId);assert.equal(s.accepted.length,0);assert.equal(s.attempts.length,0);assert.equal(s.request,null);assert.equal(s.recorded,false);assert.equal(s.unknown,false);assert.equal(s.outcome,null);assert.equal(await page.locator('.p05-success,.p05-unknown,#p05-code').count(),0);assert.equal(await page.locator('.hn-screen').evaluate(e=>e.classList.contains('p05-result')),false);assert.equal(await page.locator('.p05-scroll').evaluate(e=>e.scrollTop),0);}
 try {
 await mockGeography(page);await login();await enter();await finish('confirmed');
 await check('confirmed success Home button → Xuất kho creates clean next run',async()=>{const old=await snap();await page.locator('.hn-screen').screenshot({path:path.join(out,'01-completed.png')});await act('home').click();await enter();await fresh(old);await page.locator('.hn-screen').screenshot({path:path.join(out,'02-home-fresh.png')});});
 await check('confirmed success nav Home → Quét mã → Xuất kho creates clean next run',async()=>{await finish('confirmed');const old=await snap();await page.locator('[data-tab="home"]').click();await enter(true);await fresh(old);});
 await check('confirmed success result Quét mã → cancel retains result; choose Xuất kho starts next run',async()=>{await finish('confirmed');const old=await snap();await page.locator('[data-tab="lookup"]').click();await page.keyboard.press('Escape');assert.equal((await snap()).document.documentId,old.document.documentId);assert.equal((await snap()).step,4);await enter(true);await fresh(old);await page.locator('.hn-screen').screenshot({path:path.join(out,'03-picker-fresh.png')});});
 await check('failure → Home → both entry points reset; same-screen retry keeps request',async()=>{for(const picker of [false,true]){await finish('failed');const old=await snap();await page.locator('.hn-screen').screenshot({path:path.join(out,'04-failed.png')});await act('send').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p05-snapshot]').textContent).outcome==='not-recorded');assert.deepEqual((await snap()).request,old.request);await page.locator('.hn-action-dialog[open]').waitFor();await dismissFeedback();await act('home').click();await enter(picker);if(picker){assert.deepEqual((await snap()).request,old.request);await act('home').click();await enter();}await fresh(old);}});
 await check('native Back after terminal success → both entry points reset',async()=>{for(const picker of [false,true]){await finish('confirmed');const old=await snap();await page.goBack();await page.locator('#hn-home').waitFor({state:'visible'});await enter(picker);await fresh(old);}});
 await check('unfinished accepted codes and metadata survive Home → both entry points',async()=>{await prepareAddress(page);await page.fill('[data-p05-field="planned"]','10');await act('next').click();await act('batch').click();const draft=await snap();for(const picker of [false,true]){await page.goBack();await enter(picker);assert.deepEqual((await snap()).document,draft.document);assert.deepEqual((await snap()).accepted,draft.accepted);assert.equal((await snap()).step,2);}await act('back').click();});
 await login();await enter();
 await check('UNKNOWN → Home → both entry points retain exact request; reconcile before new run',async()=>{await finish('timeout-recorded');const old=await snap();await page.locator('.hn-screen').screenshot({path:path.join(out,'05-unknown.png')});for(const picker of [false,true]){await page.goBack();await enter(picker);assert.deepEqual((await snap()).request,old.request);assert.deepEqual((await snap()).accepted,old.accepted);assert.equal((await snap()).unknown,true);assert.equal(await act('send').isDisabled(),true);}await act('check').click();await page.locator('[data-panel="P05.S04"]').waitFor();assert.equal((await snap()).metrics.recordCalls,1);await act('home').click();await enter();await fresh(old);});
 await check('actual pending submit survives leave/reentry, late receipt never renders over Home',async()=>{await full();await page.selectOption('[data-p05-outcome]','confirmed');await act('send').click();const pending=await snap();assert.equal(pending.busy,true);await page.goBack();await page.locator('#hn-home').waitFor({state:'visible'});await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p05-snapshot]').textContent).busy===true);/* tools snapshot stays last render while hidden */await page.waitForTimeout(500);assert.equal(await page.locator('#hn-home').isVisible(),true);await enter(true);await fresh(pending);await page.locator('.hn-screen').screenshot({path:path.join(out,'06-next-run.png')});});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,errors},null,2));
 }catch(e){await page.screenshot({path:path.join(out,process.env.P05_BEFORE?'before-failure.png':'failure.png')});fs.writeFileSync(path.join(out,process.env.P05_BEFORE?'before-browser.json':'browser-failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}
})();
