const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const before=process.argv.includes('--before');
const out=path.resolve('handoff/P06/polish-2026-09-29/evidence');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:1000}}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const a=k=>p.locator(`[data-p06="${k}"]`).first(),snap=async()=>JSON.parse(await p.locator('[data-p06-snapshot]').textContent());
const check=async(name,fn)=>{try{const result=await fn();checks.push({name,status:result?'PASS':'FAIL'});if(!before)assert.ok(result,name);}catch(e){checks.push({name,status:'FAIL',error:e.message});if(!before)throw e;}};
const route=async(panel=2)=>{await p.evaluate(n=>location.hash=`#p02/lookup?panel=${n}&item=fixture-item-HN12346`,panel);await p.locator(`[data-panel="P06.S0${panel}"]`).waitFor();};
try{
await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.click('.hn-scanner');await p.click('[data-p06-item="fixture-item-HN12346"]');
await check('Back from stock returns to the specific lower stock trigger, not top shortcut',async()=>{await p.locator('.p06-stock-link [data-p06="stock"]').click();await a('back').click();await p.locator('[data-panel="P06.S02"]').waitFor();return await p.locator('.p06-stock-link [data-p06="stock"]').evaluate(e=>e===document.activeElement);});
await check('rapid double Back consumes one P06 step',async()=>{await a('stock').click();await a('back').evaluate(e=>{e.click();e.click();});await p.waitForTimeout(150);return (await snap()).panel===2;});
await route();
await check('last image keeps keyboard focus inside dialog after disabling Next',async()=>{await p.click('[data-p06-image="0"]');await p.locator('[data-image-next]').focus();await p.keyboard.press('Enter');const ok=await p.locator('.p06-image-dialog').evaluate(e=>e.contains(document.activeElement)&&!document.activeElement.disabled);await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnP06Picker);return ok;});
await check('long query preview stays compact and has full-text access',async()=>{await a('back').click();await p.locator('[data-panel="P06.S01"]').waitFor();await p.fill('#p06-search','TừKhóaDài'.repeat(100));await p.waitForTimeout(100);await p.locator('.hn-screen').screenshot({path:path.join(out,`${before?'before':'after'}-long-query.png`)});const height=await p.locator('.p06-search-context').evaluate(e=>e.offsetHeight);return height<230&&await p.locator('.p06-search-context [data-hn-read-trigger]').count()>0;});
await check('IME input does not publish partial composition query/results',async()=>{await a('clear').click();await p.locator('#p06-search').evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='HN12346';e.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'HN12346'}));});const during=(await snap()).query;await p.locator('#p06-search').evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'HN12346'})));return during===''&&(await snap()).query==='HN12346';});
await route();
await check('broken image has recoverable error state instead of a broken image icon',async()=>{await p.click('[data-p06-image="0"]');await p.locator('.p06-large-image').evaluate(e=>e.dispatchEvent(new Event('error')));const ok=await p.locator('[data-image-retry]').isVisible().catch(()=>false);await p.locator('.hn-screen').screenshot({path:path.join(out,`${before?'before':'after'}-image-error.png`)});await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnP06Picker);return ok;});
if(!before){
 await check('search uses one focus outline and empty state has one labeled clear action',async()=>{await a('back').click();await p.fill('#p06-search','no-such-item');const input=await p.locator('#p06-search').evaluate(e=>getComputedStyle(e).outlineStyle),group=await p.locator('.p06-search').evaluate(e=>getComputedStyle(e).outlineStyle);return input==='none'&&group==='solid'&&await p.getByRole('button',{name:'Xóa từ khóa',exact:true}).count()===1;});
 await check('full query reader preserves exact Unicode string and returns focus',async()=>{const query='Tiếng Việt 🧾 <mã> '.repeat(120);await p.fill('#p06-search',query);await p.locator('.p06-search-context [data-hn-read-trigger]').click();assert.equal(await p.locator('.hn-readable-dialog .app-modal-body p').textContent(),query);await p.goBack();await p.locator('.hn-readable-dialog').waitFor({state:'detached'});return await p.locator('#p06-search').inputValue()===query;});
 await check('real image request failure and successful retry keep item and gallery selection',async()=>{
  await p.route('**/box.png',r=>r.abort());await route();await p.locator('[data-p06-image="1"]').click();await p.locator('[data-image-retry]').waitFor();assert.equal(await p.locator('.p06-large-image').isVisible(),false);await p.unroute('**/box.png');await p.click('[data-image-retry]');await p.locator('.p06-large-image').waitFor({state:'visible'});await p.locator('.p06-large-image').evaluate(e=>e.decode());const ok=(await snap()).itemId==='fixture-item-HN12346'&&await p.locator('.p06-large-image').evaluate(e=>e.naturalWidth>0);await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnP06Picker);return ok;
 });
 await check('gallery/stock/search remain inside shell across viewport matrix',async()=>{
  for(const [width,height]of [[494,1000],[360,800],[430,932],[1440,900],[340,420],[1869,940]]){
   await p.setViewportSize({width,height});await route(3);await p.locator('.p06-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);await p.locator('.hn-screen').screenshot({path:path.join(out,`stock-${width}x${height}.png`)});assert.equal(await p.locator('.p06-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false);await a('back').click();await p.locator('[data-panel="P06.S02"]').waitFor();await p.click('[data-p06-image="0"]');const d=await p.locator('.p06-image-dialog').boundingBox(),screen=await p.locator('.hn-screen').boundingBox(),footer=await p.locator('.p06-image-dialog footer').boundingBox();assert.ok(d.y>=screen.y&&d.y+d.height<=screen.y+screen.height+1);assert.ok(footer.y+footer.height<=d.y+d.height+1);await p.locator('.hn-screen').screenshot({path:path.join(out,`viewer-${width}x${height}.png`)});await p.keyboard.press('Escape');await p.waitForFunction(()=>!history.state?.hnP06Picker);
  }return true;
 });
 await check('component-location action uses an accessible control and returns to the same item',async()=>{await p.setViewportSize({width:494,height:1000});await p.evaluate(()=>location.hash='#p02/lookup?panel=3&item=fixture-component-01');await p.locator('[data-panel="P06.S03"]').waitFor();const height=await a('location').evaluate(e=>e.offsetHeight);await p.locator('.hn-screen').screenshot({path:path.join(out,'after-component-location.png')});await a('location').click();await p.locator('[data-panel="P18.S04"]').waitFor();await p.goBack();await p.locator('[data-panel="P06.S03"]').waitFor();return height>=44&&(await snap()).itemId==='fixture-component-01';});
}
fs.writeFileSync(path.join(out,`${before?'before':'after'}-results.json`),JSON.stringify({checks,errors},null,2));console.log(checks);if(!before)assert.deepEqual(errors,[]);
}catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
