const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(process.env.MOTION_P02_EVIDENCE_DIR||'handoff/motion/M02/evidence'),base=process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766',before=process.argv.includes('--before');fs.mkdirSync(out,{recursive:true});
const files=['docs/flows/home/home.mjs','docs/flows/home/style.css','docs/flows/home/motion.mjs','docs/flows/home/motion.css','docs/flows/auth-session/app.mjs','docs/flows/auth-session/index.html','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'];
fs.writeFileSync(path.join(out,(before?'before':'after')+'-source.json'),JSON.stringify(files.filter(f=>fs.existsSync(f)).map(file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),bytes:fs.statSync(file).size})),null,2));
async function geometry(p){return p.locator('#hn-home').evaluate(home=>{const sels=['.hn-hero','.hn-main','.hn-kpis','.hn-tasks','.hn-recent-list','.hn-nav','.hn-scan-circle'];return Object.fromEntries(sels.map(s=>{const n=document.querySelector(s),r=n.getBoundingClientRect();return[s,{x:r.x,y:r.y,width:r.width,height:r.height,background:getComputedStyle(n).backgroundColor}]}));});}
(async()=>{const browser=await chromium.launch(),results=[];try{
for(const mode of before?['auto']:['auto','os-reduced','off']){
 const context=await browser.newContext({viewport:{width:494,height:950},timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{window.motionLog=[];window.hardwareCalls={camera:0,nfc:0};const original=Element.prototype.animate;Element.prototype.animate=function(frames,options){const row={node:this.id||this.className,duration:options.duration,frames,cancelled:false};window.motionLog.push(row);const a=original.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{row.cancelled=true;return cancel();};return a;};if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{window.hardwareCalls.camera++;throw new Error('Hardware disabled in QA');};if(window.NDEFReader)window.NDEFReader.prototype.scan=async()=>{window.hardwareCalls.nfc++;throw new Error('Hardware disabled in QA');};});
 if(process.env.MOTION_PRIVATE_TRACE!=='1')await context.tracing.start({screenshots:true,snapshots:true,sources:true});
 if(!before){
  await p.addInitScript(()=>window.domainCalls={authenticate:0,startShift:0,record:0,check:0});
  await p.route('**/fixture-adapter.mjs*',async route=>{const response=await route.fetch();let body=await response.text();for(const name of ['authenticate','startShift','record','check'])body=body.replace(new RegExp('(async '+name+'\\([^\\n]*\\) \\{)'),`$1 window.domainCalls.${name}++;`);await route.fulfill({response,body});});
 }
 await p.clock.setFixedTime(new Date('2026-09-30T01:15:20Z'));await p.goto(base+'/flows/auth-session/');await p.locator('.preview-tools details summary').click();await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-record').first().waitFor();await p.waitForTimeout(240);
 if(process.env.MOTION_PRIVATE_TRACE==='1')await context.tracing.start({screenshots:false,snapshots:false,sources:false});
 const g=await geometry(p);await p.screenshot({path:path.join(out,(before?'before':mode)+'-home.png')});const row={mode,geometry:g,errors,checks:[]};results.push(row);
 if(!before){
  const check=async(name,fn)=>{try{await fn();row.checks.push(name);console.log('PASS '+mode+' '+name);}catch(e){row.failure={name,error:e.stack};await p.screenshot({path:path.join(out,mode+'-failure.png')});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify(results,null,2));await context.tracing.stop({path:path.join(out,mode+'-failure-trace.zip')});throw e;}};
  const home=async()=>{await p.click('[data-tab=home]');await p.locator('#hn-home').waitFor({state:'visible'});};
  const settled=async()=>{await p.waitForTimeout(220);assert.equal(await p.evaluate(()=>document.querySelector('.hn-screen').getAnimations({subtree:true}).filter(a=>a.effect.target.matches('.hn-main,#hn-destination,.hn-nav button')).length),0);};
  const countBefore=await p.locator('.hn-kpis').innerText(),ids=await p.locator('.hn-record').evaluateAll(ns=>ns.map(n=>n.dataset.recentDocument));
  await check('Home geometry equals pre-motion; effective policy respects OS',async()=>{assert.deepEqual(g,JSON.parse(fs.readFileSync(path.join(out,'before.json')))[0].geometry);assert.equal(await p.locator('.hn-screen').getAttribute('data-hn-motion-mode'),mode==='os-reduced'?'reduced':mode);});
  await check('Tap feedback uses100ms or static; hero/counters/geometry never animate',async()=>{await p.evaluate(()=>{window.motionLog=[];document.querySelector('.hn-task').dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));});const log=await p.evaluate(()=>motionLog);assert.equal(log.length,mode==='auto'?1:0);if(log[0]){assert.equal(log[0].duration,100);assert.ok(log[0].frames.every(f=>!f.transform));}await settled();});
  await check('Unknown counters update synchronously without animation or fake success',async()=>{const observation=await p.evaluate(()=>{window.motionLog=[];const select=document.querySelector('#hn-scenario');select.value='unknown';select.dispatchEvent(new Event('change',{bubbles:true}));return{labels:[...document.querySelectorAll('.hn-kpi-link strong')].map(n=>n.textContent),disabled:[...document.querySelectorAll('.hn-kpi-link')].every(n=>n.disabled),records:document.querySelectorAll('.hn-record').length,animations:motionLog.length};});assert.deepEqual(observation,{labels:['Chưa xác minh','Chưa xác minh'],disabled:true,records:0,animations:0});await p.evaluate(()=>{const select=document.querySelector('#hn-scenario');select.value='baseline';select.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('.hn-kpis').innerText(),countBefore);});
  await check('Route fade only at shell with immediate commit and real RAF evidence',async()=>{
   row.frames=await p.evaluate(()=>{window.motionLog=[];document.querySelector('.hn-task[data-route=inbound]').click();const start=performance.now(),frames=[];return new Promise(resolve=>{function sample(t){const n=document.querySelector('#hn-destination'),r=n.getBoundingClientRect();frames.push({ms:t-start,hash:location.hash,opacity:getComputedStyle(n).opacity,rect:[r.x,r.y,r.width,r.height],homeHidden:document.querySelector('#hn-home').hidden,focused:document.activeElement?.tagName});if(t-start<240)requestAnimationFrame(sample);else resolve(frames);}requestAnimationFrame(sample);});});
   assert.ok(row.frames.every(f=>f.homeHidden&&f.hash==='#p02/inbound'));const log=await p.evaluate(()=>motionLog.filter(x=>x.node==='hn-destination'));assert.equal(log.length,mode==='auto'?1:0);if(log[0])assert.equal(log[0].duration,180);assert.equal(await p.locator('[data-panel="P04.S01"]').isVisible(),true);await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});
  });
  await check('Rapid Home/In/Back/Lookup ends at one interactive destination without queued fade',async()=>{await p.evaluate(()=>{window.motionLog=[];document.querySelector('.hn-task[data-route=inbound]').click();document.querySelector('[data-tab=home]').click();document.querySelector('.hn-scanner').click();});await p.locator('#p06-search').waitFor();assert.equal(await p.locator('#hn-home').isVisible(),false);assert.equal(await p.locator('#hn-destination').isVisible(),true);await settled();if(mode==='auto')assert.ok((await p.evaluate(()=>motionLog)).some(x=>x.cancelled));await home();});
  await check('Draft/scroll/focus survive detail Back; no replay on filter/row repaint',async()=>{await p.locator('.hn-record').last().scrollIntoViewIfNeeded();const top=await p.locator('.hn-main').evaluate(n=>n.scrollTop);await p.locator('.hn-record').last().click();await p.locator('[data-panel="P12.S02"]').waitFor();await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});assert.ok(Math.abs(await p.locator('.hn-main').evaluate(n=>n.scrollTop)-top)<2);assert.equal(await p.locator('.hn-record').last().evaluate(n=>n===document.activeElement),true);assert.deepEqual(await p.locator('.hn-record').evaluateAll(ns=>ns.map(n=>n.dataset.recentDocument)),ids);assert.equal(await p.locator('.hn-kpis').innerText(),countBefore);await p.click('[data-home-documents]');await p.locator('#p12-query').waitFor();await settled();await p.evaluate(()=>window.motionLog=[]);await p.fill('#p12-query','PX-0011');await p.locator('.p12-record').first().waitFor();assert.equal((await p.evaluate(()=>motionLog.filter(x=>x.node==='hn-destination'))).length,0);await home();});
  await check('Selected nav140ms; View all still P12, History still P22; no protected exit clone',async()=>{await p.evaluate(()=>{window.motionLog=[];document.querySelector('[data-home-documents]').click();});await p.locator('#p12-query').waitFor();const log=await p.evaluate(()=>motionLog);const nav=log.filter(x=>x.node===''&&x.duration===140);if(mode==='auto')assert.equal(nav.length,1);if(mode==='off')assert.equal(log.length,0);await home();await p.click('[data-tab=history]');await p.frameLocator('iframe').getByRole('heading',{name:'Lịch sử thao tác',exact:true}).waitFor();await home();});
  await check('P03 cancellation keeps scroll/focus and cancels route motion',async()=>{await p.locator('.hn-record').last().scrollIntoViewIfNeeded();const top=await p.locator('.hn-main').evaluate(n=>n.scrollTop);await p.click('[data-tab=lookup]');await p.locator('.p03-dialog').waitFor();assert.equal(await p.evaluate(()=>document.querySelector('#hn-destination').getAnimations().length),0);await p.keyboard.press('Escape');await p.locator('#hn-home').waitFor({state:'visible'});assert.ok(Math.abs(await p.locator('.hn-main').evaluate(n=>n.scrollTop)-top)<2);});
  await check('Direct destination consumers keep navigation and native focus',async()=>{for(const [selector,ready]of [['.hn-task[data-route=outbound]','[data-panel="P05.S01"]'],['.hn-task[data-route=nfc]','#p07-search'],['.hn-task[data-route=warranty]','#p09-query'],['.hn-avatar','.p10-app'],['.hn-bell','.p13-app']]){await p.click(selector);await p.locator(ready).waitFor();await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});}assert.deepEqual(await p.evaluate(()=>hardwareCalls),{camera:0,nfc:0});});
  await check('Off / OS change interrupts animation without changing data or route',async()=>{await p.locator('.hn-tools > details > summary').first().click();await p.selectOption('#home-motion-mode','auto');await p.evaluate(()=>document.querySelector('.hn-scanner').click());await p.selectOption('#home-motion-mode','off');await p.locator('#p06-search').waitFor();assert.equal(await p.evaluate(()=>document.querySelector('#hn-destination').getAnimations().length),0);await home();await p.selectOption('#home-motion-mode','auto');await p.evaluate(()=>document.querySelector('.hn-scanner').click());await p.emulateMedia({reducedMotion:'reduce'});await p.waitForFunction(()=>document.querySelector('.hn-screen').dataset.hnMotionMode==='reduced');assert.equal(await p.evaluate(()=>document.querySelector('#hn-destination').getAnimations().length),0);await home();await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');});
  await check('Small/keyboard-height viewports preserve layout across modes and last record accessibility',async()=>{row.layouts=[];for(const viewport of [{width:360,height:800},{width:360,height:420}]){await p.setViewportSize(viewport);await p.locator('.hn-record').last().scrollIntoViewIfNeeded();await settled();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);row.layouts.push({viewport,geometry:await geometry(p)});await p.screenshot({path:path.join(out,mode+'-'+viewport.height+'.png')});}await p.setViewportSize({width:494,height:950});});
  await check('Runtime stopped/permission guards act immediately; logout removes animations/content',async()=>{await p.locator('.p03-tools summary').click();await p.selectOption('[data-p03-fixture=warehouse]','stopped');await p.click('.hn-task[data-route=inbound]');await p.locator('[data-panel="P03.S03"]').waitFor();await p.getByRole('button',{name:'Về Trang chủ',exact:true}).click();await p.locator('#hn-home').waitFor({state:'visible'});await p.selectOption('[data-p03-fixture=warehouse]','active');await p.locator('.p15-tools summary').click();await p.evaluate(()=>{document.querySelector('.hn-scanner').click();document.querySelector('[data-system-demo=deny]').click();});await p.locator('[data-panel="P15.S03"]').waitFor();assert.equal(await p.locator('#hn-destination').isVisible(),false);assert.equal(await p.evaluate(()=>document.querySelector('#hn-destination').getAnimations().length),0);await p.click('[data-system-demo=allow]');await home();await p.click('#hn-logout');await p.locator('#username').waitFor();assert.equal(await p.locator('.hn-screen').count(),0);await p.goBack();await p.locator('#username').waitFor();assert.equal(await p.locator('.hn-screen').count(),0);});
  row.operations=await p.evaluate(()=>domainCalls);assert.deepEqual(row.operations,{authenticate:1,startShift:1,record:0,check:0});assert.deepEqual(errors,[]);
 }
 await context.tracing.stop({path:path.join(out,(before?'before':mode)+'-trace.zip')});await context.close();
}
fs.writeFileSync(path.join(out,before?'before.json':'results.json'),JSON.stringify(results,null,2));
}finally{await browser.close();}})();
