const {chromium}=require('C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const out='handoff/P20/evidence/revision-01/after';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),p=await b.newPage({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:'reduce',timezoneId:'Asia/Ho_Chi_Minh'}),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
const snap=async()=>JSON.parse(await p.locator('[data-p20-snapshot]').textContent()),a=n=>p.locator(`[data-p20="${n}"]`),pause=()=>p.waitForTimeout(160);
async function shot(name){await p.evaluate(()=>document.fonts.ready);await p.locator('.hn-screen').screenshot({path:out+'/'+name+'.png'});}
async function route(q){await p.evaluate(q=>location.hash='#p02/component-history?'+q,q);await p.waitForSelector('.p20-app');await pause();}
async function check(name,f){await f();checks.push({name,status:'PASS'});console.log('PASS '+name);}
try{await p.goto('http://localhost:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.waitForSelector('#hn-home:not([hidden])');await p.locator('.p20-tools').evaluate(e=>e.open=true);
await check('Four B20 panel captures',async()=>{for(const [i,s] of ['history','history-loading','history-error','empty'].entries()){await p.click(`[data-p20-demo="${s}"]`);await p.waitForSelector(`[data-panel="P20.S0${i+1}"]`);if(i===0)await p.waitForSelector('[data-p20-document]');await pause();await shot('P20-S0'+(i+1)+'-494x950');}});
await check('A01/A04 overlap + rapid load: one request, quantities not added, explicit end',async()=>{await route('case=BH-001&sample=history');const before=(await snap()).requests.length;await a('load').evaluate(e=>{e.click();e.click();e.click();});await p.waitForSelector('.p20-end');const s=await snap();assert.equal(s.requests.length,before+1);assert.equal(s.items.length,2);assert.equal(await p.locator('[data-p20-document="XLK-0002"]').count(),1);assert.equal(s.items[0].lines[1].quantity,2);assert.equal(await a('load').count(),0);await shot('A01-dedup-end');});
await check('A02 error retains DOM/scroll and retry uses failed cursor',async()=>{await route('case=BH-001&sample=history-error');const before=await snap();await p.locator('.p20-scroll').evaluate(e=>e.scrollTop=80);await p.locator('[data-p20-document]').evaluate(e=>e.dataset.kept='yes');const top=await p.locator('.p20-scroll').evaluate(e=>e.scrollTop);await a('load').click();await p.waitForSelector('.p20-error');assert.equal(await p.locator('[data-kept=yes]').count(),1);assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollTop),top);await p.selectOption('[data-p20-mode]','ready');await a('load').click();await p.waitForSelector('.p20-end');const after=await snap();assert.equal(after.requests.at(-1).cursor,before.nextCursor);assert.equal(after.items.length,2);assert.equal(await p.locator('[data-kept=yes]').count(),1);assert.equal(await p.locator('.p20-scroll').evaluate(e=>e.scrollTop),top);});
await check('P09 entry + same case P20/P19 and information/Back',async()=>{await p.evaluate(()=>location.hash='#p02/warranty?panel=3&tab=parts&case=BH-001');await p.waitForSelector('[data-p09=component-history]');await p.click('[data-p09=component-history]');await p.waitForSelector('.p20-end');assert.equal((await snap()).caseId,'BH-001');await a('info').click();await p.waitForSelector('.p09-app');assert.match(p.url(),/case=BH-001/);await p.goBack();await p.waitForSelector('.p20-app');await a('issue').click();await p.waitForSelector('.p19-app:not(.p20-app)');assert.match(p.url(),/case=BH-001/);await p.goBack();await p.waitForSelector('.p20-app');await a('back').click();await p.waitForSelector('.p09-app');});
await check('A03/A05 genuine empty vs closed case read-only',async()=>{await route('case=BH-003');await p.waitForSelector('.p20-empty');assert.equal((await snap()).loaded,true);assert.equal(await a('issue').isDisabled(),false);await route('case=BH-002');await p.waitForSelector('.p20-end');assert.equal(await a('issue').isDisabled(),true);assert.match(await p.locator('.p20-footer').innerText(),/đã trả khách/i);await shot('closed-read-only');});
await check('Invalid case has no empty state or issue action',async()=>{await route('case=BAD');assert.equal(await p.locator('.p20-empty').count(),0);assert.equal(await a('issue').count(),0);assert.match(await p.locator('.p20-app').innerText(),/Không tìm thấy/);});
await check('5 viewports keep494×950 and visible footer; inner scrolling',async()=>{for(const [width,height]of [[494,950],[360,800],[430,932],[1440,900],[340,420]]){await p.setViewportSize({width,height});await route('case=BH-001&sample=history');const g=await p.locator('.hn-screen').evaluate(e=>{const s=e.querySelector('.p20-scroll'),f=e.querySelector('.p20-footer'),r=e.getBoundingClientRect(),fr=f.getBoundingClientRect();return {width:e.offsetWidth,height:e.offsetHeight,overflow:s.scrollWidth>s.clientWidth+1,footer:fr.bottom<=r.bottom+1&&fr.top>=r.top};});assert.deepEqual(g,{width:494,height:950,overflow:false,footer:true});await shot('viewport-'+width+'x'+height);}});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({checks,errors},null,2));console.log(checks.length+' groups PASS');
}catch(e){await shot('failure').catch(()=>{});fs.writeFileSync(out+'/failure.json',JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await b.close();}})();
