const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(process.env.INBOUND_CATALOGUE_EVIDENCE_DIR || 'handoff/P04/evidence/revision-06');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}});const checks=[],errors=[],metrics=[];page.on('pageerror',e=>errors.push(e.message));
 const act=n=>page.locator(`[data-p04="${n}"]`).first(),trigger=n=>page.locator(`[data-p04-select="${n}"]`),search=()=>page.getByRole('searchbox',{name:'Tìm Nhà cung cấp'}),popup=()=>page.locator('.p04-select-popup:not([hidden])');
 const snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
 const check=async(name,fn)=>{await fn();checks.push({name,status:'PASS'});};const capture=async(name)=>{await page.evaluate(()=>scrollTo(0,0));await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});};
 try{
 await page.goto((process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();
 await check('Three types commit to state, trigger and keyboard focus',async()=>{for(const name of ['Nhập linh kiện','Khác','Nhập sản phẩm']){await trigger('type').click();assert.equal(await popup().getByRole('option').count(),3);await popup().getByRole('option',{name,exact:true}).click();assert.equal((await snap()).document.type,name);assert.equal(await trigger('type').evaluate(e=>e===document.activeElement),true);}await trigger('type').click();await capture('01-types');await page.keyboard.press('Escape');});
 await check('15 suppliers: anchored menu, autofocus search, codes/count and selection',async()=>{const before=await page.locator('.p04-footer').boundingBox();await trigger('supplier').click();assert.equal(await popup().getByRole('option').count(),15);assert.equal(await search().evaluate(e=>e===document.activeElement),true);assert.deepEqual(await page.locator('.p04-footer').boundingBox(),before);assert.match(await popup().textContent(),/15 nhà cung cấp/);await capture('02-suppliers');});
 await check('Accent-insensitive token/name/code search, clear and empty recovery',async()=>{for(const q of ['HAI DANG','hải đăng','dang hai','NCC-008']){await search().fill(q);assert.equal(await popup().getByRole('option').count(),1);assert.match(await popup().getByRole('option').textContent(),/Hải Đăng/);}await capture('03-search');await search().fill('not-a-supplier');assert.equal(await popup().getByRole('option').count(),0);assert.equal(await popup().locator('.p04-select-empty').isVisible(),true);await search().press('Enter');assert.equal(await popup().count(),1);await capture('04-empty');await page.getByRole('button',{name:'Xóa tìm kiếm'}).click();assert.equal(await popup().getByRole('option').count(),15);assert.equal(await search().inputValue(),'');await search().fill('NCC-008');await search().press('Enter');assert.equal((await snap()).document.supplierCode,'NCC-008');});
 await check('Keyboard selected marker, cancellation and query reset preserve supplier',async()=>{await trigger('supplier').click();assert.equal(await search().inputValue(),'');assert.match(await page.locator('[role="option"][aria-selected="true"]:visible').textContent(),/Hải Đăng/);await search().fill('an binh');await search().press('ArrowDown');assert.match(await page.evaluate(()=>document.activeElement.textContent),/An Bình/);await page.keyboard.press('Escape');assert.equal((await snap()).document.supplierCode,'NCC-008');assert.equal(await trigger('supplier').evaluate(e=>e===document.activeElement),true);await trigger('supplier').click();await search().press('ArrowUp');assert.match(await page.evaluate(()=>document.activeElement.textContent),/Thành Công/);await page.keyboard.press('Enter');assert.equal((await snap()).document.supplierCode,'NCC-015');});
 await check('Popup stays inside shell and does not move footer at six viewports',async()=>{for(const [w,h]of [[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const before=await page.locator('.p04-footer').boundingBox();await trigger('supplier').click();await search().fill('minh');const m=await page.evaluate(()=>{const r=s=>document.querySelector(s).getBoundingClientRect();const p=r('.p04-select-popup:not([hidden])'),b=r('.p04-scroll'),a=r('.hn-screen');return{viewport:[innerWidth,innerHeight],inside:p.top>=b.top-1&&p.bottom<=b.bottom+1&&p.left>=a.left-1&&p.right<=a.right+1,layout:[document.querySelector('.hn-screen').offsetWidth,document.querySelector('.hn-screen').offsetHeight],overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(m.inside);assert.equal(m.overflow,false);assert.deepEqual(m.layout,[494,950]);assert.deepEqual(await page.locator('.p04-footer').boundingBox(),before);metrics.push(m);await capture(`05-search-${w}x${h}`);await page.keyboard.press('Escape');}});
 await page.setViewportSize({width:1440,height:1000});
 await check('Review and receipt retain selected type/supplier; scan lock and UNKNOWN freeze',async()=>{await trigger('type').click();await popup().getByRole('option',{name:'Nhập linh kiện',exact:true}).click();await page.locator('[data-p04-note]').fill('Kiểm tra lựa chọn');await act('next').click();await act('manual').click();await page.fill('#p04-code','HN12345');await page.locator('#p04-code').press('Enter');await act('back').click();assert.equal(await trigger('type').isDisabled(),true);assert.match(await trigger('supplier').textContent(),/Thành Công/);await trigger('supplier').click();await search().fill('008');await search().press('Enter');await act('next').click();await act('next').click();assert.match(await page.locator('.p04-review-summary').textContent(),/Nhập linh kiện/);assert.match(await page.locator('.p04-review-summary').textContent(),/Hải Đăng.*NCC-008/);await capture('06-review');await page.locator('.p04-tools summary').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await act('send').click();await page.locator('[data-panel="P17.S04"]').waitFor();const unknown=await snap();assert.equal(unknown.request.document.typeId,'components');assert.equal(unknown.request.document.supplierCode,'NCC-008');await act('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.deepEqual((await snap()).request,unknown.request);await capture('07-result');await page.locator('.p04-footer [data-p04="home"]').click();await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).document.type,'Nhập sản phẩm');assert.equal((await snap()).document.supplierCode,'NCC-001');await trigger('supplier').click();assert.equal(await search().inputValue(),'');await page.keyboard.press('Escape');});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({passed:checks.length,viewports:metrics.length,errors}));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
