const base=process.env.INBOUND_PREVIEW_URL||'http://127.0.0.1:8766';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const before=process.env.INBOUND_AUDIT_BEFORE==='1',out=path.resolve('handoff/P04/evidence/revision-07/'+(before?'before':'final'));fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}});const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 const a=n=>page.locator(`[data-p04="${n}"]`).first(),tr=n=>page.locator(`[data-p04-select="${n}"]`),pop=()=>page.locator('.p04-select-popup:not([hidden])'),search=()=>page.getByRole('searchbox',{name:'Tìm Nhà cung cấp'});
 const snap=async()=>JSON.parse(await page.locator('[data-p04-snapshot]').textContent());
 async function check(name,fn){try{const details=await fn();checks.push({name,status:'PASS',details});}catch(e){checks.push({name,status:'FAIL',error:e.message});if(!before)throw e;}}
 async function shot(name){await page.locator('.hn-screen').screenshot({path:path.join(out,name+'.png')});}
 try{
 await page.goto(base+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="inbound"]').click();
 await check('End opens supplier popup and reveals focused last option',async()=>{await tr('supplier').focus();await page.keyboard.press('End');const m=await page.evaluate(()=>{const e=document.activeElement,r=e.getBoundingClientRect(),b=e.closest('[role="listbox"]').getBoundingClientRect();return{text:e.textContent,top:r.top,bottom:r.bottom,listTop:b.top,listBottom:b.bottom};});await shot('01-keyboard-end');await page.keyboard.press('Escape');assert.match(m.text,/Thành Công/);assert.ok(m.top>=m.listTop-1&&m.bottom<=m.listBottom+1,JSON.stringify(m));return m;});
 await check('Opening and pressing Enter with no search preserves current supplier',async()=>{await tr('supplier').click();await search().fill('008');await search().press('Enter');assert.equal((await snap()).document.supplierCode,'NCC-008');await tr('supplier').click();await search().press('Enter');const selected=(await snap()).document.supplierCode;assert.equal(selected,'NCC-008');return selected;});
 await check('Supplier search clear is keyboard reachable and never commits a selection',async()=>{await tr('supplier').click();await search().fill('an binh');await search().press('Tab');const focus=await page.evaluate(()=>document.activeElement.getAttribute('aria-label'));if(before){await page.keyboard.press('Escape');}else{assert.equal(focus,'Xóa tìm kiếm');await page.keyboard.press('Enter');assert.equal(await search().inputValue(),'');assert.equal(await pop().getByRole('option').count(),15);await page.keyboard.press('Escape');}assert.equal(focus,'Xóa tìm kiếm');});
 // Close menu left open by the before probe, then exercise the real scan form.
 await page.keyboard.press('Escape');await page.locator('[data-p04-note]').fill('Dòng một\nDòng hai');await a('next').click();await a('manual').click();
 await check('Manual blank is inline; valid clears input; invalid raw stays safe',async()=>{await page.fill('#p04-code',' ');await page.locator('#p04-code').press('Enter');assert.equal((await snap()).attempts.length,0);await page.fill('#p04-code','HN12345');await page.locator('#p04-code').press('Enter');assert.equal(await page.locator('#p04-code').inputValue(),'');await page.fill('#p04-code','<wrong>');await page.locator('#p04-code').press('Enter');assert.equal(await page.locator('#p04-code').inputValue(),'<wrong>');assert.equal((await snap()).accepted.length,1);await shot('02-invalid');});
 await check('Collapsing invalid manual input shows user-facing feedback, not fixture/dependency jargon',async()=>{await a('close-manual').click();const text=await page.locator('.p04-feedback').textContent();assert.match(text,/Không tìm thấy sản phẩm/);assert.doesNotMatch(text,/fixture|P06|P17/);return text;});
 await a('next').click();await page.locator('.p04-tools summary').click();await page.selectOption('[data-p04-outcome]','failed');await a('send').click();await page.waitForFunction(()=>JSON.parse(document.querySelector('[data-p04-snapshot]').textContent).outcome==='not-recorded');
 await check('Confirmed rejection stays on review instead of opening a frozen scan form',async()=>{const b=a('back');await shot('03-rejected');assert.equal(await b.isDisabled(),true);assert.match(await page.locator('.p04-request-lock').textContent(),/gửi lại|thử lại/i);});
 if(before){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));return;}
 await check('Explicit retry uses same payload and records once more, then new run clears state',async()=>{const failed=await snap();await page.selectOption('[data-p04-outcome]','confirmed');await a('send').click();await page.locator('[data-panel="P04.S04"]').waitFor();const done=await snap();assert.deepEqual(done.request,failed.request);assert.equal(done.metrics.recordCalls,2);await page.locator('.p04-footer [data-p04="home"]').click();await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).step,1);assert.equal((await snap()).document.note,'');assert.equal((await snap()).attempts.length,0);});
 await check('IME confirmation cannot accidentally submit a raw code',async()=>{await a('next').click();await a('manual').click();await page.fill('#p04-code','HN12346');await page.locator('#p04-code').dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,bubbles:true,cancelable:true});assert.equal((await snap()).attempts.length,0);await page.locator('#p04-code').press('Enter');assert.equal((await snap()).accepted.length,1);});
 await check('Source guards retain manual text and P03 focus, then resume exact draft',async()=>{await page.locator('.p03-tools summary').click();await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await page.fill('#p04-code','HN12347');await page.locator('#p04-code').press('Enter');await page.locator('[data-panel="P03.S03"]').waitFor();assert.equal(await page.locator('.p03-dialog').evaluate(e=>e.contains(document.activeElement)),true);await page.locator('[data-p03-action="home"]').click();await page.selectOption('[data-p03-fixture="warehouse"]','active');await page.locator('.hn-task[data-route="inbound"]').click();assert.equal((await snap()).step,2);assert.equal((await snap()).accepted.length,1);assert.equal(await page.locator('#p04-code').inputValue(),'HN12347');});
 await a('next').click();await page.selectOption('[data-p04-outcome]','timeout-recorded');await a('send').click();await page.locator('.p04-unknown').waitFor();
 await check('UNKNOWN only exposes status check, preserves request across native Back and picker',async()=>{const s=await snap();assert.equal(await a('send').isDisabled(),true);assert.equal(await a('back').isDisabled(),true);await shot('04-unknown');await page.goBack();await page.locator('[data-tab="lookup"]').click();await page.locator('[data-p03-operation="inbound"]').click();assert.deepEqual((await snap()).request,s.request);await a('check').click();await page.locator('[data-panel="P04.S04"]').waitFor();assert.equal((await snap()).metrics.recordCalls,s.metrics.recordCalls);});
 await check('Result palette and responsive shell match shared system; no clipping',async()=>{for(const [w,h]of [[340,420],[390,844],[494,1000],[768,1024],[1440,1000],[1869,940]]){await page.setViewportSize({width:w,height:h});await page.evaluate(()=>scrollTo(0,0));const m=await page.evaluate(()=>{const s=document.querySelector('.hn-screen'),r=s.getBoundingClientRect(),f=document.querySelector('.p04-footer').getBoundingClientRect();return{size:[s.offsetWidth,s.offsetHeight],overflow:document.documentElement.scrollWidth>innerWidth,cta:f.bottom<=r.bottom+1,icons:[...document.querySelectorAll('.p04-summary-row .hn-operation-icon')].map(e=>({op:e.dataset.hnOperation,color:getComputedStyle(e).color,fill:getComputedStyle(e.querySelector('svg')).fill}))};});assert.deepEqual(m.size,[494,950]);assert.equal(m.overflow,false);assert.ok(m.cta);for(const i of m.icons){assert.equal(i.fill,'none');assert.equal(i.color,i.op==='inbound'?'rgb(13, 107, 96)':'rgb(70, 98, 121)');}await shot(`05-result-${w}x${h}`);}});
 await check('Denied note edit restores visible value and counter without losing P03 focus',async()=>{
  await page.setViewportSize({width:494,height:1000});await page.locator('.p04-footer [data-p04="home"]').click();await page.locator('.hn-task[data-route="inbound"]').click();await page.locator('[data-p04-note]').fill('Ghi chú được giữ');
  await page.selectOption('[data-p03-fixture="warehouse"]','stopped');await page.locator('[data-p04-note]').fill('Không được ghi');await page.locator('[data-panel="P03.S03"]').waitFor();
  assert.equal(await page.locator('[data-p04-note]').inputValue(),'Ghi chú được giữ');assert.equal((await snap()).document.note,'Ghi chú được giữ');assert.equal(await page.locator('.p03-dialog').evaluate(e=>e.contains(document.activeElement)),true);
  await page.locator('[data-p03-action="home"]').click();await page.selectOption('[data-p03-fixture="warehouse"]','active');await page.locator('.hn-task[data-route="inbound"]').click();assert.equal(await page.locator('[data-p04-note]').inputValue(),'Ghi chú được giữ');
 });
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({groups:checks.length,errors}));
 }catch(e){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({checks,errors,error:e.stack},null,2));throw e;}finally{await browser.close();}})();
