const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {choose}=require('./outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve('handoff/P05/evidence/revision-07');
(async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:494,height:1000}}),requests=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith('https://provinces.open-api.vn/'))requests.push({method:r.method(),url:r.url(),body:r.postData()});});
 try{await page.goto('http://127.0.0.1:8766/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('.hn-task[data-route="outbound"]').click();await page.waitForFunction(()=>!document.querySelector('[data-p05-select="province"]').disabled,{},{timeout:15000});
 await choose(page,'province','79');await page.waitForFunction(()=>!document.querySelector('[data-p05-select="district"]').disabled,{},{timeout:15000});await choose(page,'district','760');await page.fill('[data-p05-field="address"]','123 Lê Lợi');const s=JSON.parse(await page.locator('[data-p05-snapshot]').textContent());assert.equal(s.geography.provinces.length,63);assert.equal(s.geography.districts.length,22);assert.equal(s.document.districtName,'Quận 1');
 await page.locator('[data-p05-select="province"]').click();await page.locator('.p05-select-search:visible').fill('ho chi minh');await page.locator('.hn-screen').screenshot({path:path.join(out,'live-province-search.png')});await page.keyboard.press('Escape');await page.locator('[data-p05-select="district"]').click();await page.locator('.hn-screen').screenshot({path:path.join(out,'live-district-popup.png')});await page.keyboard.press('Escape');await page.locator('[data-p05="next"]').click();await page.locator('[data-panel="P05.S02"]').waitFor();assert.deepEqual(errors,[]);assert.ok(requests.every(r=>r.method==='GET'&&r.body===null));fs.writeFileSync(path.join(out,'live-api-results.json'),JSON.stringify({status:'PASS',provinces:s.geography.provinces.length,districts:s.geography.districts.length,requests,errors},null,2));console.log('PASS live browser API/CORS:63 provinces,22 HCM districts; ordered address passes next; only public GET requests');
 }catch(e){fs.writeFileSync(path.join(out,'live-api-results.json'),JSON.stringify({status:'FAILED',error:e.stack,requests,errors},null,2));throw e;}finally{await browser.close();}})();
