const fs=require('node:fs'),assert=require('node:assert/strict');
const root='handoff/ux-audit-2026-10-01/',read=file=>JSON.parse(fs.readFileSync(root+file,'utf8').replace(/^\uFEFF/,''));
const checks=read('public/results.json'),flows=read('flow-viewer-public-r02/results.json'),bytes=read('PUBLIC_BYTES.json'),pages=read('PAGES_BUILD.json'),push=read('CODE_PUSH.json'),scan=read('TRACE_SCAN_PUBLIC.json');
assert.equal(checks.checks.length,13);assert.ok(checks.checks.every(c=>c.status==='PASS'));
assert.equal(flows.status,'PASS');assert.equal(flows.checks.length,7);assert.equal(bytes.status,'PASS');assert.equal(pages.status,'built');assert.equal(pages.commit,push.sha);assert.equal(checks.expectedBuild,push.build);assert.equal(scan.alerts.length,0);
const boardRuns=JSON.parse(fs.readFileSync('handoff/flow/evidence/ux-audit-20261001/regression-runs.json'));
const p03=JSON.parse(fs.readFileSync('handoff/flow/evidence/ux-audit-20261001-p03-r03/regression-runs.json'))[0];boardRuns[boardRuns.findIndex(r=>r.board==='P03')]=p03;assert.equal(boardRuns.length,24);assert.ok(boardRuns.every(r=>r.exit_code===0));
const result={status:'PASS_PUBLIC_UI_FIXTURE',verifiedAt:new Date().toISOString(),build:push.build,testedCodeCommit:push.sha,reviewTree:push.reviewTree,pagesBuild:pages.commit,url:'https://duc-nguyen98.github.io/ScannerHNApp/review/?view=review&panel=P01.S01&scenario=default&motion=auto',publicChecks:checks.checks,publicFlowChecks:flows.checks,sourceBytes:bytes.checks,boardRegressions:boardRuns,nodeTests:{pass:765,fail:0},panelLayouts:{panels:91,viewports:[[1440,950],[360,800]],beforeAndAfter:true},journeys:{modes:['auto','os-reduced','off'],perMode:12,passed:36},diagrams:50,downloadLinks:150,retainedEvidence:{allIntermediateLogsAndTraces:true,firstPublicDownloadRun:'One HTTP 503; no source change; full rerun passed. Origin cause unverified. See flow-viewer-public/failure.json.',incompleteHistoricalZip:scan.invalidArchives},preserved:['docs/flows','docs/review/runtime','docs/review/flows','docs/index.html','design','Primary dirty checkout/index'],visualAcceptance:'AWAITING_USER_REVIEW',limits:['Chromium fixture checks; not universal bug-free certification','No real backend, camera or NFC certification','Review links rebuild panel fixtures, not edited drafts']};
fs.writeFileSync(root+'PUBLIC_RESULT.json',JSON.stringify(result,null,2));console.log({status:result.status,build:result.build,code:result.testedCodeCommit});
