const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'handoff/motion/M08');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,'')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const data=read('handoff/motion/M08/evidence/results.json'),prior=read('handoff/motion/M08/evidence/before/results.json'),shell=read('handoff/motion/M08/evidence/shell-regression/results.json');
assert.equal(read('handoff/flow/FLOW_GATE.json').gate_status,'PASS');assert.equal(data.length,3);assert.ok(data.every(r=>r.checks.length===10&&r.errors.length===0));assert.equal(shell.reduce((n,r)=>n+r.checks.length,0),36);assert.ok(shell.every(r=>r.errors.length===0));
for(const r of data){for(const name of ['domain','counters','dayCounts','scanIds','timelineIds','labels'])assert.deepEqual(r[name],data[0][name],r.mode+' '+name);}
const geometry=data.flatMap((r,i)=>Object.entries(r.geometry).map(([panel,g])=>{assert.deepEqual(g,prior[i].geometry[panel],r.mode+' '+panel);return{mode:r.mode,panel,same_as_before:true};}));assert.equal(geometry.length,12);write('handoff/motion/M08/evidence/geometry-comparison.json',geometry);
const testFiles=fs.readdirSync(path.join(root,'tests')).filter(f=>/^(history.*|flow-history-source|business-history|query-date-policy|home.*|motion-p02|motion-p08)\.test\.mjs$/.test(f)).map(f=>'tests/'+f);
const node=cp.spawnSync(process.execPath,['--test','--test-reporter=tap',...testFiles],{cwd:root,encoding:'utf8'});fs.writeFileSync(path.join(out,'evidence/node-tests.log'),node.stdout+node.stderr);assert.equal(node.status,0,node.stdout.slice(-2000));const tests=Number(node.stdout.match(/^# tests (\d+)/m)?.[1]);assert.ok(tests>0);
const before=read('handoff/motion/M08/evidence/before/source.json'),scoped=[...new Set([...before.map(f=>f.file),'docs/flows/history/motion.mjs'])].map(file=>{const bytes=fs.readFileSync(path.join(root,file)),old=before.find(f=>f.file===file);return{file,bytes:bytes.length,sha256:sha(bytes),prior_bytes:old?.bytes||0,prior_sha256:old?.sha256||null};});
for(const file of ['docs/flows/history/style.css','docs/flows/history/history-model.mjs','docs/flows/history/history-source.mjs','docs/flows/history/business-history-data.mjs','docs/flows/shared/history-fixtures.js','docs/flows/home/motion.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css']){const row=scoped.find(r=>r.file===file);assert.equal(row.sha256,row.prior_sha256,'unchanged '+file);}
function list(folder){return fs.readdirSync(path.join(root,folder),{withFileTypes:true}).flatMap(e=>e.isDirectory()?list(folder+'/'+e.name):[folder+'/'+e.name]);}
const files=list('docs/flows').sort().map(file=>{const b=fs.readFileSync(path.join(root,file));return{file,sha256:sha(b),bytes:b.length};}),diffFiles=['docs/flows','scripts','tests'].flatMap(list).sort().map(p=>{const b=fs.readFileSync(path.join(root,p));return{path:p,sha256:sha(b),bytes:b.length};});
const head=cp.execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),appHash=sha(JSON.stringify(files)),diffHash=sha(JSON.stringify({source_commit:head,files:diffFiles})),delta=scoped.reduce((n,r)=>n+r.bytes-r.prior_bytes,0);
const summary={prompt:'MOTION_P08',normal:'PASS',os_reduced:'PASS',off:'PASS',panels:4,node_tests:tests,motion_browser_groups:30,shell_regression_groups:36,domain_equal:true,history_records:data[0].domain.ids.length,scan_reference_sessions:data[0].domain.sessions.length,hardware_calls_per_mode:0,initial_profiles:Object.fromEntries(data.map(r=>[r.mode,r.profile])),append_profiles:Object.fromEntries(data.map(r=>[r.mode,r.listProfile])),source_byte_delta:delta,static_geometry:'PASS12 panel-mode combinations relative to app shell, exact equality with before',visual:'USER_REVIEW_PENDING',virtualization:'NOT_NEEDED current bounded list; long backend list DEFERRED',fps:'NOT_MEASURED',production:'NOT_RUN',hardware:'NOT_RUN',report:'handoff/motion/M08/REPORT.md'};
write('handoff/motion/M08/evidence/summary.json',summary);write('handoff/motion/M08/SOURCE_MANIFEST.json',{source_commit:head,appSourceHash:appHash,working_diff_hash:diffHash,definition:'Sorted normalized paths with SHA256/bytes including untracked source; source byte delta not a production bundle.',fixture:'unchanged HN_HISTORY_FIXTURES and business-history-data; P04/P05 verified projection unchanged',scoped,files,diffFiles});
const state=read('handoff/motion/MOTION_RUN_STATE.json');assert.equal(state.current_prompt,'MOTION_P08','Do not overwrite another active motion task');
const csvPath=path.join(root,'handoff/motion/MOTION_COVERAGE.csv'),csv=fs.readFileSync(csvPath,'utf8'),rows=csv.trim().split(/\r?\n/);assert.equal(rows.length,92);let changed=0;
const panels=[1,2,3,4].map(n=>'P08.S0'+n);const patched=rows.map(line=>{if(!line.startsWith('"MOTION_P08",'))return line;changed++;const id=line.split(',')[1].replaceAll('"','');assert.ok(panels.includes(id));return ['MOTION_P08',id,'PASS','PASS','PASS','PASS',id==='P08.S02'?'REUSED':id==='P08.S03'?'STATIC_BY_DESIGN':'APPLIED','handoff/motion/M08/REPORT.md;handoff/motion/M08/evidence/results.json;handoff/motion/M08/evidence/geometry-comparison.json',''].map(s=>'"'+s+'"').join(',');});assert.equal(changed,4);fs.writeFileSync(csvPath,patched.join('\r\n')+'\r\n');
state.verification_history??={};if(state.verification?.prompt==='MOTION_P07')state.verification_history.M07=state.verification;state.M08=summary;state.verification=summary;state.status='PASS_SCOPED_UI_FIXTURE';state.appSourceHash=appHash;state.working_diff_hash=diffHash;state.completed_panel_ids=[...new Set([...state.completed_panel_ids,...panels])];state.remaining_panel_ids=state.remaining_panel_ids.filter(id=>!panels.includes(id));state.affected_dependencies=['M02 shell route key and mode/security cancellation fanout;36 browser regressions PASS','P08 native append, day scroll and obsolete picker callback guard','P12 document/P18 attachments/P23 reference edges verified in3modes; source data unchanged'];state.next_action='User review M08. Do not execute M09 or deploy without request.';state.artifact_paths=[...new Set([...state.artifact_paths,'handoff/motion/M08/REPORT.md','handoff/motion/M08/SOURCE_MANIFEST.json','handoff/motion/M08/evidence/results.json'])];write('handoff/motion/MOTION_RUN_STATE.json',state);write('handoff/motion/M08/RUN_STATE.json',{current_prompt:'MOTION_P08',status:state.status,remaining_panel_ids:[],verification:summary,affected_dependencies:state.affected_dependencies,next_action:state.next_action});console.log(JSON.stringify(summary,null,2));
