from pathlib import Path
import json,csv,io,re,hashlib,collections,html
root=Path(__file__).resolve().parents[1];base=root/'handoff/P24';ev=base/'evidence/revision-03'
before=json.loads((ev/'before/audit.json').read_text(encoding='utf-8'));after=json.loads((ev/'after/audit.json').read_text(encoding='utf-8'));assert len(after)==16 and all(r['status']=='PASS' for r in after)
fixed=[r['id'] for r in before if r['status']=='FAIL'];assert len(fixed)==14
files=['docs/flows/warranty-components/'+n for n in ['issue-view.mjs','issue-model.mjs','issue-fixture.mjs','issue.css','history-view.mjs','history.css']]+['docs/flows/shared/waiting-web.mjs','docs/flows/shared/UI_STANDARD.md','docs/flows/inbound/inbound.mjs','docs/flows/outbound/outbound.mjs','docs/flows/home/home.mjs','docs/flows/history/warranty-session-view.mjs','tests/scanner-states-r03.test.mjs','scripts/audit_p24_r03.cjs','scripts/check_p24_r03_guards.cjs','scripts/run_p24_r03.cjs','scripts/finalize_p24_r03.py','scripts/verify_p24_r03.cjs']
(base/'SOURCE_MANIFEST_03.json').write_text(json.dumps({'revision':'P24-r03','files':[{'path':p,'sha256':hashlib.sha256((root/p).read_bytes()).hexdigest()} for p in files],'note':'Runtime changes scoped to P24 and direct dependencies; global status files retain unrelated fields.'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
coverage=root/'SCREEN_COVERAGE.csv';lines=coverage.read_text(encoding='utf-8-sig').splitlines();keys=next(csv.reader([lines[0]]));out=[lines[0]]
targets={f'P24.S0{i}' for i in range(1,5)}|{'P04.S04','P05.S04','P19.S02','P20.S01','P23.S02'}
for line in lines[1:]:
 row=dict(zip(keys,next(csv.reader([line]))))
 if row['panel_id'] in targets:
  row['visual_status']='IN_PROGRESS';row['behavior_status']='PASS';row['integration_status']='BLOCKED'
  for ref in ['handoff/P24/REVISION_03.md','handoff/P24/REVIEW_03.html','handoff/P24/evidence/revision-03']:
   if ref not in row['evidence']:row['evidence']+='; '+ref
  note=' P24 r03 audit:14 reproduced cases fixed;173 logic/70 browser groups,35 P24 layouts/4 footer viewports. Visual awaiting review; historical temporary acceptance retained. Production/hardware unverified.'
  if note not in row['blocker']:row['blocker']+=note
  stream=io.StringIO();csv.writer(stream,quoting=csv.QUOTE_ALL,lineterminator='').writerow([row[k] for k in keys]);out.append(stream.getvalue())
 else:out.append(line)
coverage.write_text('\n'.join(out)+'\n',encoding='utf-8');rows=list(csv.DictReader(io.StringIO('\n'.join(out))))
state=json.loads((base/'RUN_STATE.json').read_text(encoding='utf-8'));state.update(revision='P24-r03',node_tests=173,p24_node_tests=14,browser_groups={'audit_r03':16,'guards_r03':4,'p24_main':5,'p24_edges':6,'p24_r02_ux':5,'p19':9,'p20':7,'p21':9,'p23':9},browser_groups_total=70,layout_combinations=35,footer_viewports=4,reproduced_fixed_cases=14,reproduced_case_ids=fixed,report='handoff/P24/REVISION_03.md',review='handoff/P24/REVIEW_03.html',next_action='User visual review P24 r03 after14 reproduced UI/UX cases fixed. Preserve historical temporary acceptance and deferred synchronization states; production/hardware/persistence unverified.')
refs=['handoff/P24/REVISION_03.md','handoff/P24/REVIEW_03.html','handoff/P24/REVISION_03_CONTEXT.md','handoff/P24/STATE_ACCEPTANCE_03.csv','handoff/P24/SOURCE_MANIFEST_03.json','handoff/P24/evidence/revision-03'];state['artifact_paths']=list(dict.fromkeys(state['artifact_paths']+refs))
state['shared_components_changed']=['Shared waiting-web result return controller for P04/P05','P20 context/reader lifecycle and loading selector scope','P19 local long-text/stepper fixes and UNIT/BOX error wording','Home result/new-run history identity; P23 return to verified P20 caller']
state['coverage_reference']={'boards':24,'panels':91,'statuses':{k:dict(collections.Counter(r[k] for r in rows)) for k in ['visual_status','behavior_status','integration_status']},'basis':'Historical report inventory retained. Only scoped P24/dependencies validated by this revision.'}
(base/'RUN_STATE.json').write_text(json.dumps(state,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with (base/'STATE_ACCEPTANCE_03.csv').open('w',encoding='utf-8',newline='') as f:
 w=csv.writer(f);w.writerow(['case','before','after','disposition','visual','integration']);prior={r['id']:r for r in before}
 for r in after:w.writerow([r['id'],prior[r['id']]['status'],r['status'],'FIXED' if r['id'] in fixed else 'ALREADY_PASS','AWAITING_USER_REVIEW','BLOCKED_PRODUCTION'])
global_file=root/'RUN_STATE.json';text=global_file.read_text(encoding='utf-8');old=json.loads(text)
def patch(key,value):
 global text
 match=re.search(r'^  "'+re.escape(key)+r'":\s*',text,re.M);render=json.dumps(value,ensure_ascii=False,indent=2).replace('\n','\n  ')
 if match:
  start=match.end();_,size=json.JSONDecoder().raw_decode(text[start:]);text=text[:start]+render+text[start+size:]
 else:text=text.replace('{','{\n  '+json.dumps(key)+': '+render+',',1)
patch('p24_revision_r03',state)
for k,v in {'current_prompt':'P24','revision':'P24-r03','prompt_status':'P24_R03_AUDITED_VISUAL_REVIEW_PENDING','next_action':state['next_action'],'coverage_summary_p24':state['coverage_reference'],'remaining_scope':'P24 r03 fixes14 reproduced UI/UX cases; visual review pending. Historical acceptance and deferred synchronization states retained; production/hardware/persistence unverified.'}.items():patch(k,v)
patch('artifact_paths',list(dict.fromkeys(old.get('artifact_paths',[])+refs)));json.loads(text);global_file.write_text(text,encoding='utf-8')
titles={'A03':'Footer ổn định khi tải thêm','A04':'Context phản ánh trạng thái đã đóng','A05':'Thời gian dài đọc đầy đủ','A06':'Mã hồ sơ dài không tràn','A07':'Hướng dẫn sheet không tràn ngang','A08':'Back giữ focus kết quả nhập','A09':'Back giữ focus kết quả xuất','A10':'Back giữ cuộn kết quả xuất','A11':'Timeline trở lại đúng nguồn lịch sử','A12':'Stepper giữ focus ở giới hạn','A13':'Lỗi tem đơn đúng ngữ cảnh','A14':'Back từ lịch sử giữ phiếu nhập','A15':'Back từ lịch sử giữ phiếu xuất','A16':'Lượt mới không mắc ID phiếu cũ'}
cards=''.join(f'<details><summary>{id} · {titles[id]} <span>FAIL → PASS</span></summary><div class="pair">'+''.join(f'<figure><figcaption>{label}</figcaption><a href="evidence/revision-03/{phase}/{id}.png"><img loading="lazy" src="evidence/revision-03/{phase}/{id}.png" alt="{id} {label}"></a></figure>' for phase,label in [('before','Trước · r02'),('after','Sau · r03')])+'</div></details>' for id in fixed)
panels=''.join(f'<figure><figcaption>{label}</figcaption><a href="evidence/revision-03/regression/after/after/{name}-494x950.png"><img loading="lazy" src="evidence/revision-03/regression/after/after/{name}-494x950.png"></a></figure>' for name,label in [('S01','S01 · Số lượng'),('S02','S02 · Mã chưa thể xuất'),('S03-inbound','S03 · Nhập'),('S03-outbound','S03 · Xuất'),('S04','S04 · Chỉ đọc')])
page='''<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>P24 r03 · Audit UI/UX</title><style>body{margin:0;background:#eef5f8;color:#12384e;font:16px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:28px 20px}h1{margin-bottom:6px}h2{font-size:22px}a{color:#076c8c}section,details{background:white;padding:24px;border:1px solid #dce9ef;border-radius:16px;margin-top:24px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}.panels{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}figure{margin:0}figcaption{padding:8px 0;font-weight:650}img{width:100%;height:auto;display:block;border:1px solid #dce9ef;border-radius:8px;box-sizing:border-box}.badge{display:inline-block;border-radius:8px;padding:6px 12px;background:#fff2d7;color:#78500b}nav{display:flex;gap:20px;flex-wrap:wrap}.note{padding:16px;background:#eaf5fa;border-radius:10px}summary{cursor:pointer;font-weight:650;min-height:44px}summary span{float:right;color:#176c47}details[open] summary{margin-bottom:16px}@media(max-width:650px){.pair,.panels{grid-template-columns:1fr}main{padding:16px}section,details{padding:14px}}</style><main><h1>P24 r03 · Rà soát UI/UX</h1><p class="badge">14 ca lỗi đã khắc phục · Chờ review hình thức</p><p>173 test logic · 70 nhóm trình duyệt · 35 tổ hợp layout P24 · 4 viewport footer Home/P03. Cả16 ca audit đạt sau sửa; A01/A02 đã đạt trước và không tính là lỗi được sửa.</p><nav><a href="http://localhost:8766/flows/auth-session/?v=p24-r03">Mở preview</a><a href="REVISION_03.md">Báo cáo r03</a><a href="evidence/revision-03/before/audit.json">Audit trước</a><a href="evidence/revision-03/after/audit.json">Audit sau</a><a href="REVIEW_02.html">Review r02</a></nav><p class="note">Giữ6 cải tiến r02, khung494×950 và guard nghiệp vụ. Sửa nguyên nhân về scope CSS loading, focus/cuộn khi trở lại result, dữ liệu context cũ, nội dung dài và identity/caller trong history. Đây là prototype; backend, thiết bị và lưu bền chưa xác minh.</p><section><h2>Giao diện hiện tại</h2><div class="panels">'''+panels+'''</div></section><h2>Ca lỗi trước–sau</h2><p>Mở từng ca và bấm ảnh để xem nguyên kích thước. Cùng viewport494×950/DPR1/font local/timezone Việt Nam; dữ liệu dài/depleted/đổi trạng thái là fixture audit rõ trong script, không phải giao dịch WMS. Chuỗi ID tạo riêng mỗi lượt chạy có thể khác nhau.</p>'''+cards+'''<section><h2>Kiểm bổ sung</h2><p>Tải xong dưới reader không đóng dialog hoặc giành focus; context thay đổi không giữ footer cũ; steppermin không tự commit; callback result không giành focus của lựa chọn mới. UNKNOWN vẫn đối chiếu đúng yêu cầu, không retry Post mù.</p><a href="evidence/revision-03/guards/results.json">Kết quả guard</a><p>24 board/91 panel được giữ. P23 r03 vẫn tạm chốt lịch sử; các state đồng bộ tương lai bổ sung sau. Không push/merge/deploy.</p></section></main></html>'''
(base/'REVIEW_03.html').write_text(page,encoding='utf-8');print(json.dumps({'revision':'P24-r03','fixed':fixed,'counts':state['coverage_reference']},ensure_ascii=False))
