const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const base='handoff/motion',out=base+'/M02/evidence',read=f=>JSON.parse(fs.readFileSync(f,'utf8')),write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const results=read(out+'/results.json'),summary=read(out+'/summary.json');assert.equal(results.length,3);
for(const r of results){assert.equal(r.checks.length,12);assert.deepEqual(r.errors,[]);assert.deepEqual(r.operations,{authenticate:1,startShift:1,record:0,check:0});assert.deepEqual(r.geometry,results[0].geometry);assert.deepEqual(r.layouts,results[0].layouts);}
for(const s of summary.modes)assert.equal(s.static_pixel_difference_bbox,null);
const scoped=read(out+'/after-source.json');for(const s of scoped)assert.equal(sha(fs.readFileSync(s.file)),s.sha256,s.file+' changed after verification');
const old=read(out+'/before-source.json');for(const name of ['docs/flows/home/style.css','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css'])assert.equal(scoped.find(x=>x.file===name).sha256,old.find(x=>x.file===name).sha256);
const list=dir=>fs.readdirSync(dir,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>path.join(e.parentPath,e.name).replaceAll('\\','/')).sort();
const files=list('docs/flows').map(file=>({file,sha256:sha(fs.readFileSync(file)),bytes:fs.statSync(file).size}));
const source_commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),diffFiles=[...list('docs/flows'),...list('scripts'),...list('tests')].sort().map(file=>({path:file,sha256:sha(fs.readFileSync(file)),bytes:fs.statSync(file).size}));
const appSourceHash=sha(JSON.stringify(files)),working_diff_hash=sha(JSON.stringify({source_commit,files:diffFiles}));
write(out+'/source-manifest.json',{source_commit,appSourceHash,working_diff_hash,hash_definition:'appSourceHash: sorted docs/flows file/sha256/bytes array; working_diff_hash: {source_commit,files:[sorted path/sha256/bytes for docs/flows/scripts/tests]}, includes untracked; excludes handoff',files,diffFiles});
const coverage=base+'/MOTION_COVERAGE.csv';let csv=fs.readFileSync(coverage,'utf8');const row='"MOTION_P02","P02.S01","PASS","PASS","PASS","PASS","APPLIED","handoff/motion/M02/REPORT.md;handoff/motion/M02/evidence/results.json;handoff/motion/M02/evidence/summary.json",""';assert.equal(csv.split('\n').filter(l=>l.startsWith('"MOTION_P02"')).length,1);csv=csv.replace(/^"MOTION_P02"[^\r\n]*/m,row);fs.writeFileSync(coverage,csv);
const state=read(base+'/MOTION_RUN_STATE.json');state.verification_history??={};state.verification_history.M01??=state.verification;state.current_prompt='MOTION_P02';state.status='PASS_SCOPED_UI_FIXTURE';state.appSourceHash=appSourceHash;state.working_diff_hash=working_diff_hash;state.completed_panel_ids=[...new Set([...state.completed_panel_ids,'P02.S01'])];state.remaining_panel_ids=state.remaining_panel_ids.filter(p=>p!=='P02.S01');state.verification={focused_tests:82,browser_groups:36,kpi_groups:6,footer_viewports:4,visual:'STATIC_ACTUAL_PRESERVED_MOTION_USER_REVIEW_PENDING',fps:'NOT_MEASURED',report:'handoff/motion/M02/REPORT.md'};state.affected_dependencies=['P02 AppShell RouteTransition/NavFeedback; existing M00 controller reused unchanged','P01 mode handoff only; focused consumer tests pass','P03/P04/P05/P06/P07/P09/P10/P12/P13/P22 entry/Back checks; internal motion pending'];state.artifact_paths=[...new Set([...state.artifact_paths,'handoff/motion/M02/REPORT.md','handoff/motion/M02/evidence/results.json','handoff/motion/M02/evidence/source-manifest.json'])];state.next_action='Review M02 motion; execute MOTION_P03 only when requested. Preserve footer/geometry, business integration and single shell owner.';write(base+'/MOTION_RUN_STATE.json',state);
console.log(JSON.stringify({appSourceHash,working_diff_hash,browser_groups:36,focused_tests:82,remaining:state.remaining_panel_ids.length}));
