// Labels describe the verified preview, not a production API or a new business rule.
const G=(nodes,edges)=>({nodes,edges});
const p=(id,text)=>[id+'\n'+text,'panel'];
const a=text=>[text,'action'],w=text=>[text,'guard'],s=text=>[text,'store'],x=text=>[text,'blocked'];
const boards=[];
function B(id,title,user,data){boards.push({id,title,user,data});}

B('P00','Nền tảng & luồng tổng thể',G({
 entry:a('Mở App Preview\nHoặc chọn mẫu trong Review Mode'),auth:p('P01','Đăng nhập và xác nhận phiên'),guard:w('Phiên · Quyền · Kho\nKiểm tra trước khi vào luồng'),home:p('P02','Trang chủ / AppShell'),scan:p('P03','Chọn tác vụ / Nháp / Kho dừng'),stock:p('P04 · P05','Nhập kho / Xuất kho\nGửi Web, không Post trên App'),read:p('P06 · P07','Tra cứu sản phẩm / NFC'),cases:p('P09 · P19 · P20 · P21','Bảo hành / Xuất linh kiện\nLịch sử POSTED / Tiếp tục phiếu'),records:p('P08 · P12 · P13 · P18','Lịch sử / Chứng từ / Thông báo\nTệp, bàn giao và vị trí'),history:p('P22 · P23','Hub lịch sử / NFC audit\nBảo hành / Phiên quét'),account:p('P10 · P11 · P14','Cá nhân / Bảo mật\nKhôi phục và ca làm việc'),states:p('P15 · P16 · P17 · P24','Hệ thống / Dữ liệu / Ngoại lệ\nTrạng thái dùng lại từ owner'),back:a('Back / Home / Đóng dialog\nGiữ đúng ngữ cảnh màn gọi'),off:x('Hết phiên / Mất quyền\nChặn ngay, không chờ animation')
},[['entry','auth'],['auth','guard'],['guard','home','Đủ điều kiện'],['guard','off','Không đủ'],['off','auth','Đăng nhập lại nếu hết phiên'],['home','scan'],['scan','stock'],['scan','read'],['scan','cases'],['home','records'],['home','history'],['home','account'],['stock','states','Lỗi / UNKNOWN'],['cases','states','Guard / Ngoại lệ'],['read','states','Lỗi dữ liệu / Thiết bị'],['stock','back'],['records','back'],['history','back'],['account','back'],['back','home']]),G({
 session:s('Nguồn phiên P01\nActor · Auth session · Kho · Quyền'),scope:w('Phạm vi phiên được xác minh\nKhông suy quyền từ tên vai trò'),router:a('AppShell / Router\nChỉ truyền ID và ngữ cảnh'),owners:s('Owner theo nghiệp vụ\nP04/P05: record · P19: Post\nP09: hồ sơ · P07: mapping'),request:w('Yêu cầu cố định danh\nRequest ID · Document/Case ID\nScan session · Version'),adapter:a('Adapter hiện có\nDữ liệu mô phỏng trong trang'),unknown:w('UNKNOWN\nGiữ request, khóa gửi lại'),check:a('Đọc / Đối chiếu đúng yêu cầu'),receipt:s('Kết quả đã xác minh\nKhông suy thành công từ timeout'),projection:a('Nguồn dùng chung / Phép chiếu\nKhông tạo lại record theo nhãn PN'),views:p('P01–P24','Màn hiển thị cùng dữ liệu\nBack giữ lọc, tab, focus theo owner'),motion:a('Motion auto / reduced / off\nChỉ trình bày, không phát lệnh ghi'),reset:x('Reload / Reset mẫu\nMất thay đổi trong bộ nhớ trang\nLink review dựng lại mẫu đã chọn')
},[['session','scope'],['scope','router'],['router','owners'],['owners','request'],['request','adapter'],['adapter','receipt','Đã xác minh'],['adapter','unknown','Chưa rõ'],['unknown','check'],['check','unknown','Chưa xác minh'],['check','receipt','Đã xác minh'],['receipt','owners'],['owners','projection'],['projection','views'],['motion','views','Không đổi dữ liệu'],['reset','session','Khởi tạo lại seed'],['views','router','Chuyển màn bằng ID']]));

B('P01','Đăng nhập & xác nhận phiên',G({
 start:a('Mở ứng dụng / Đăng xuất'),s1:p('P01.S01','Đăng nhập\nNhập tài khoản và mật khẩu demo'),valid:w('Kiểm tra dữ liệu nhập'),err:x('Lỗi tại ô / Đăng nhập bị từ chối\nKhông mở dữ liệu Home'),auth:a('Gửi yêu cầu xác thực mô phỏng'),unk:w('Xác thực chưa rõ\nKhông suy là đã đăng nhập'),s2:p('P01.S02','Xác nhận phiên\nĐúng người, kho và quyền'),guard:w('Kho hoạt động?\nQuyền thao tác đã xác nhận?'),deny:x('Chặn bắt đầu ca\nKhông vượt guard bằng deep link'),begin:a('Bắt đầu ca\nChặn nhấn gửi trùng'),pending:w('Kết quả bắt đầu UNKNOWN\nGiữ phiên, chưa vào Home'),home:a('P02 · Home\nChỉ sau receipt bắt đầu hợp lệ'),recover:a('P14.S01 · Khôi phục tài khoản'),logout:a('Xác nhận đăng xuất\nXóa nội dung được bảo vệ')
},[['start','s1'],['s1','valid','Đăng nhập'],['valid','err','Thiếu / Sai'],['err','s1','Sửa'],['valid','auth','Hợp lệ'],['auth','unk','Chưa rõ'],['unk','s1','Thông báo và kiểm tra lại'],['auth','s2','Xác thực thành công'],['s2','guard'],['guard','deny','Không đủ'],['guard','begin','Đủ điều kiện'],['begin','pending','Chưa xác minh'],['pending','s2','Giữ thông tin đối chiếu'],['begin','home','Đã xác minh'],['s1','recover','Quên mật khẩu'],['recover','s1','Back'],['s2','logout'],['logout','s1','Đồng ý']] ),G({
 input:p('P01.S01','Tài khoản + mật khẩu nhập\nKhông lưu mật khẩu vào báo cáo/storage'),epoch:w('Credential epoch\nBỏ callback của lần nhập/phiên cũ'),adapter:a('Auth fixture + Account store\nNguồn credential mô phỏng dùng chung P11'),session:s('Session đã xác minh\nActor ID · Auth session ID\nWarehouse ID · Permissions'),confirm:p('P01.S02','Hiển thị đúng session\nKho / Người / Quyền'),req:w('Yêu cầu bắt đầu ca\nGiữ định danh trong lúc chờ'),result:a('Adapter xác nhận bắt đầu'),unknown:w('Start UNKNOWN\nKhông mở Home, không gửi lại mù'),ready:s('previewReady + thời điểm ca\nChỉ từ kết quả đã xác minh'),home:a('P02 nhận cùng session\nTải UI không tạo thêm ca'),revoke:x('Logout / Hết phiên / Reload\nVô hiệu callback, bỏ DOM bảo vệ')
},[['input','epoch'],['epoch','adapter'],['adapter','session','Xác thực hợp lệ'],['session','confirm'],['confirm','req','Bắt đầu'],['req','result'],['result','unknown','Chưa rõ'],['result','ready','Xác nhận hợp lệ'],['ready','home'],['revoke','session','Vô hiệu'],['revoke','epoch','Đổi thế hệ'],['adapter','input','Từ chối: giữ form']]));

B('P02','Trang chủ',G({
 in:a('P01 xác nhận phiên thành công'),s1:p('P02.S01','Trang chủ\nKPI · Phiếu đang làm · Chứng từ gần đây'),tasks:a('Chọn nghiệp vụ'),scan:a('P03 · Chọn tác vụ quét'),inbound:a('P04 · Nhập kho'),outbound:a('P05 · Xuất kho'),lookup:a('P06 · Tra cứu'),nfc:a('P07 · Thẻ NFC'),warranty:a('P09 · Bảo hành'),recent:a('P12 · Đúng chứng từ đã chọn'),all:a('P12 · Danh sách chứng từ'),history:a('P22.S01 · Hub lịch sử'),notification:a('P13 · Thông báo'),profile:a('P10 · Cá nhân'),resume:a('P04/P05 hoặc P21\nTiếp tục đúng owner đang làm'),guard:x('Hết phiên / Mất quyền / Kho dừng\nP15 hoặc P03 chặn thao tác ghi')
},[['in','s1'],['s1','tasks'],['tasks','inbound'],['tasks','outbound'],['tasks','lookup'],['tasks','nfc'],['tasks','warranty'],['s1','scan','Tab quét'],['s1','recent','Chọn chứng từ'],['s1','all','Xem tất cả gần đây'],['s1','history','Tab Lịch sử'],['s1','notification','Chuông'],['s1','profile','Avatar / Cá nhân'],['s1','resume','Phiếu đang làm'],['s1','guard','Guard tại mọi entry']] ),G({
 session:s('Phiên P01\nActor · Kho · Quyền · Giờ bắt đầu'),docs:s('Nguồn chứng từ P12\nSeed + receipt P04/P05 hợp lệ'),cases:s('Nguồn hồ sơ bảo hành P09'),notif:s('Notification store P13\nTrạng thái đã đọc/chưa đọc'),draft:s('Snapshot owner P04/P05/P19\nKhông dựng draft mới từ tên phiếu'),scope:w('Lọc cùng actor/kho\nChỉ dùng receipt đã xác minh'),view:a('Tính KPI / Badge / Phiếu đang làm\nGần đây tối đa 3 chứng từ'),s1:p('P02.S01','Hiển thị từ nguồn dùng chung\nKhông cộng tồn từ số card'),route:a('Chuyển màn bằng ID thật\nDocument ID / Case ID / Draft ID'),returnState:s('Ngữ cảnh quay lại\nCuộn · Focus · ID lựa chọn'),unknown:x('Nguồn chưa xác minh\nKhông đổi thành số 0 giả')
},[['session','scope'],['docs','scope'],['cases','view'],['notif','view'],['draft','scope'],['scope','view'],['view','s1'],['s1','route','Chọn mục'],['route','returnState'],['returnState','s1','Back'],['scope','unknown','Thiếu nguồn / scope'],['unknown','s1','Hiển thị chưa xác minh']]));

B('P03','Dialog quét & phiếu dở',G({
 entry:a('Từ Home / Tab quét / Luồng ghi'),s1:p('P03.S01','Chọn tác vụ\nNhập / Xuất / Tra cứu / Bảo hành'),dest:a('P04 / P05 / P06 / P09\nMang đúng nghiệp vụ và phạm vi'),s2:p('P03.S02','Có phiếu chưa hoàn tất\nGiữ định danh và dữ liệu'),resume:a('Tiếp tục owner hiện tại\nKhông tạo phiếu thay thế'),save:a('Lưu nháp trong bộ nhớ fixture\nXác nhận rồi về Home'),s4:p('P03.S04','Xác nhận bỏ phiếu'),discard:w('Đúng local draft chưa lưu?\nKhông request/UNKNOWN/recorded?'),blocked:x('Không được xóa\nGiữ dữ liệu để đối chiếu'),gone:a('Bỏ đúng phần chưa lưu\nKhông xóa WMS'),s3:p('P03.S03','Kho tạm dừng\nChặn ghi, không tự đăng xuất'),home:a('P02 · Home / Màn gọi'),legacy:x('Mẫu P03 legacy riêng\nThiếu owner: giữ lại, không import')
},[['entry','s1','Không có nháp đang chọn'],['entry','s2','Có live draft'],['s1','dest','Chọn tác vụ'],['s2','resume','Tiếp tục'],['resume','dest','Khớp owner'],['resume','legacy','Mẫu không khớp'],['s2','save','Lưu nháp'],['save','home','Lưu xác nhận'],['s2','s4','Bỏ phiếu'],['s4','s2','Hủy / Escape'],['s4','discard','Đồng ý'],['discard','blocked','Không đủ'],['discard','gone','Đủ điều kiện'],['gone','home'],['entry','s3','Kho dừng'],['s3','home','Về Home; guard vẫn giữ'],['s1','home','Đóng / Back'],['s2','home','Hủy: không mất phiếu']] ),G({
 owners:s('Live owner P04/P05\nDocument · Scan session · Version\nAccepted rows · Metadata · Request'),projection:a('stock-owner-adapter\nProjection chỉ đọc, không tạo owner'),s2:p('P03.S02','Snapshot giữ đúng định danh\nActor · Kho · Fingerprint'),guard:w('Kiểm lại scope + fingerprint\nTrước lệnh và sau khi dialog đóng'),resume:a('resumeExisting\nMở đúng P04/P05'),s4:p('P03.S04','Lệnh bỏ local draft'),ownerDelete:a('Owner tự kiểm và xóa local\nP05 dọn cache địa chỉ của phiếu'),save:s('Dấu lưu trong bộ nhớ phiên\nKhông đồng nghĩa WMS đã nhận'),s1:p('P03.S01','Operation + Actor ID\nWarehouse ID + Return context'),s3:p('P03.S03','Trạng thái kho\nKhông cho thực hiện lệnh ghi'),legacy:x('Legacy PN-0001 / fixture-p03\nNguồn review riêng, không ánh xạ theo PN'),shift:a('P14 đọc owner một lần\nLoại projection P03 khỏi đếm trùng')
},[['owners','projection'],['projection','s2'],['s2','guard','Tiếp tục / Lưu / Bỏ'],['guard','resume','Khớp'],['guard','s4','Chỉ local chưa lưu'],['s4','ownerDelete'],['ownerDelete','owners','Cập nhật đúng owner'],['guard','save','Lưu fixture'],['s1','resume','Chọn nghiệp vụ, chưa cấp lại nháp'],['s3','guard','Write guard'],['legacy','s2','Review riêng'],['owners','shift'],['guard','s2','Lệch / UNKNOWN: giữ dữ liệu']]));

B('P04','Nhập kho',G({
 in:a('P02 / P03 / P12\nTạo hoặc tiếp tục đúng phiếu'),s1:p('P04.S01','Thông tin phiếu nhập\nLoại nhập · NCC · Kho · Ghi chú'),meta:w('Thông tin bắt buộc hợp lệ?'),s2:p('P04.S02','Quét / Nhập tay\nGiữ nguyên mã gốc'),scan:w('Mã hợp lệ và chưa trùng?'),bad:a('P17.S01 · Mã lỗi\nLượt trùng không cộng số lượng'),accepted:a('Thêm vào danh sách hợp lệ\nPhân biệt số mã và tổng quantity'),s3:p('P04.S03','Kiểm tra phiếu\nCần ít nhất 1 mã hợp lệ'),send:a('Gửi phiếu lên Web\nMột yêu cầu đang chờ'),s4:p('P04.S04','Đã gửi phiếu nhập\nChờ xử lý trên Web'),unknown:a('P17.S04 · UNKNOWN\nChỉ kiểm tra cùng yêu cầu'),failure:x('Từ chối xác định\nGiữ phiếu; retry theo điều kiện'),links:a('P08 Lịch sử / P12 Chứng từ\nCùng document ID'),stop:a('P03.S03 / P15\nKho dừng / Phiên / Quyền')
},[['in','s1'],['s1','meta','Tiếp tục'],['meta','s1','Thiếu: sửa tại ô'],['meta','s2','Đủ'],['s2','scan'],['scan','bad','Lỗi / Trùng'],['bad','s2','Sửa / Quét tiếp'],['scan','accepted','Hợp lệ'],['accepted','s2','Quét tiếp'],['s2','s3','Kiểm tra'],['s3','s2','Back giữ dữ liệu'],['s3','send','Gửi'],['send','s4','Receipt hợp lệ'],['send','unknown','Chưa rõ'],['unknown','s4','Đối chiếu xác nhận record'],['send','failure','Không ghi nhận được xác minh'],['failure','send','Chỉ khi cho phép retry'],['s4','links'],['s1','stop','Guard tại mọi lệnh ghi']] ),G({
 s1:p('P04.S01','Metadata\nDocument ID · Scan session · NCC · Kho'),s2:p('P04.S02','Mã gốc từ nhập tay / fixture camera'),catalog:s('Catalogue kiểm mã hiện hành'),validate:w('Validate · Khử trùng\nMã lỗi/trùng không tăng accepted'),state:s('Owner inbound-flow\nDocument/version · Attempts\nAccepted rows: SKU + Quantity'),s3:p('P04.S03','Review dùng cùng owner\nTổng theo accepted, không theo lượt quét'),request:w('Request ID cố định\nSnapshot document + lines\nChặn gửi trùng'),adapter:a('Record adapter mô phỏng'),unknown:w('UNKNOWN / Timeout\nGiữ cùng request để check'),receipt:s('Receipt được xác minh\nrequest khớp · recorded=true'),s4:p('P04.S04','Chờ Web · Chưa ghi sổ\nInventory delta = 0'),shared:a('P12 projection + P08 receipt history\nCùng Document ID, không tổng hợp event giả')
},[['s1','state'],['s2','validate'],['catalog','validate'],['validate','state','Hợp lệ: thêm dòng'],['validate','s2','Lỗi/trùng: giữ raw và lý do'],['state','s3'],['s3','request'],['request','adapter'],['adapter','unknown','Chưa rõ'],['unknown','adapter','Check cùng request, không record mới'],['adapter','receipt','Đã xác minh'],['receipt','state'],['receipt','s4'],['receipt','shared']]));

B('P05','Xuất kho',G({
 in:a('P02 / P03 / P12\nTạo hoặc tiếp tục đúng owner'),s1:p('P05.S01','Thông tin phiếu xuất\nNguồn phiếu · Người nhận · Địa chỉ · SL'),change:w('Đổi nguồn phiếu?\nXác nhận trước khi thay nội dung'),valid:w('Metadata và địa chỉ hợp lệ?'),s2:p('P05.S02','Quét / Nhập tay'),gate:w('Mã được phép xuất?\nĐúng nhóm, không trùng, không vượt SL'),bad:a('P17.S02 / Thông báo mã\nKhông thêm mã bị chặn'),s3:p('P05.S03','Kiểm tra phiếu xuất\nĐối chiếu số đã soạn / yêu cầu'),enough:w('Đã soạn đủ số lượng?'),send:a('Gửi phiếu lên Web\nChặn double-submit'),s4:p('P05.S04','Đã gửi phiếu xuất\nChờ Web, chưa đổi tồn'),unknown:a('P17.S04 · UNKNOWN\nCheck cùng request'),failed:x('Từ chối xác định\nGiữ yêu cầu để thử lại có điều kiện'),links:a('P08 / P12\nĐúng receipt và chứng từ')
},[['in','s1'],['s1','change','Chọn nguồn khác'],['change','s1','Hủy hoặc xác nhận đổi'],['s1','valid','Tiếp tục'],['valid','s1','Thiếu/sai'],['valid','s2','Hợp lệ'],['s2','gate'],['gate','bad','Bị chặn'],['bad','s2','Quét mã khác'],['gate','s2','Thêm mã hợp lệ'],['s2','s3','Kiểm tra'],['s3','enough'],['enough','s2','Thiếu: quay lại soạn'],['enough','send','Đủ và guard hợp lệ'],['send','s4','Receipt được xác minh'],['send','unknown','Chưa rõ'],['unknown','s4','Check xác nhận'],['send','failed','Không ghi nhận đã xác minh'],['failed','send','Retry cùng yêu cầu khi được phép'],['s4','links']] ),G({
 source:s('Nguồn phiếu / Danh mục người nhận\nĐịa giới theo phiên bản fixture'),s1:p('P05.S01','Metadata + Số lượng yêu cầu\nKho / Người nhận / Điện thoại / Địa chỉ'),s2:p('P05.S02','Mã gốc từ cùng pipeline quét'),validate:w('Đúng sản phẩm/nhóm\nChưa xuất · Không trùng · Không vượt SL'),owner:s('Owner outbound-flow\nDocument ID · Scan session · Version\nAccepted · Attempts · Geography cache'),s3:p('P05.S03','Tổng quantity đã soạn\nSo với số lượng yêu cầu'),req:w('Request cố định danh\nCùng document snapshot + lines'),adapter:a('Record / Check adapter'),unknown:w('UNKNOWN\nKhóa gửi lại, giữ request'),receipt:s('Kết quả recorded đã xác minh\nCùng Request / Document ID'),s4:p('P05.S04','Chờ xử lý Web\nKhông Post và không đổi tồn'),shared:a('P08 / P12 cùng receipt\nKhông map bằng số PX hiển thị'),reset:x('Bỏ đúng local draft đã xác nhận\nKhông xóa phiếu đã record/UNKNOWN')
},[['source','s1'],['s1','owner'],['s2','validate'],['source','validate'],['validate','owner','Chỉ mã được chấp nhận'],['owner','s3'],['s3','req','Đủ số lượng + guard'],['req','adapter'],['adapter','unknown','Chưa rõ'],['unknown','adapter','Check đúng request'],['adapter','receipt','Đã xác minh'],['receipt','s4'],['receipt','shared'],['reset','owner','Dọn đúng draft và cache địa chỉ']]));

B('P06','Tra cứu sản phẩm',G({
 in:a('Home / P03\nHoặc picker từ P07 / P09'),s1:p('P06.S01','Tìm sản phẩm\nMã / SKU / Serial · Bộ lọc · Vừa xem'),exists:w('Nguồn đọc và ID hợp lệ?'),empty:x('Lỗi / Không có kết quả\nKhông tự mở sản phẩm đầu tiên'),s2:p('P06.S02','Thông tin đúng sản phẩm'),s3:p('P06.S03','Tồn kho cùng sản phẩm/kho'),s4:p('P06.S04','Lịch sử giao dịch\nGiữ bộ lọc theo sản phẩm'),loc:a('P18.S04 · Vị trí\nKhông suy sức chứa chưa có nguồn'),nfc:a('Trả item ID + serial về P07\nChỉ khi đang chọn cho NFC'),war:a('P09 · Tiếp nhận / Hồ sơ\nMang theo serial, không dùng SKU thay'),doc:x('Chứng từ chưa có mapping\nBáo chưa khả dụng, không mở giả'),back:a('Về đúng màn gọi / Danh sách\nGiữ tìm kiếm, cuộn và focus')
},[['in','s1'],['s1','exists','Chọn dòng'],['exists','empty','Không xác minh'],['empty','s1','Sửa lọc / Thử đọc lại'],['exists','s2','Đúng ID'],['s2','s3','Xem tồn'],['s2','s4','Xem lịch sử'],['s3','loc'],['s2','nfc','Chọn cho NFC'],['s2','war','Bảo hành'],['s4','doc','Link chưa có mapping'],['s2','back','Back'],['s3','s2','Back'],['s4','s2','Back'],['back','s1']] ),G({
 query:p('P06.S01','Query / Category / Item ID\nNguồn lựa chọn và lịch sử xem'),catalog:s('Catalogue fixture\nMã · SKU · Serial · Ảnh · Vị trí'),scope:w('Scope phiên/kho\nID phải có trong nguồn'),read:a('Read adapter / Cache đọc\nBỏ response cũ sau đổi context'),s2:p('P06.S02','Thông tin sản phẩm đúng ID'),stock:s('Snapshot tồn cùng kho\nThiếu số liệu = chưa xác minh'),s3:p('P06.S03','Hiển thị tồn / Khả dụng'),events:s('Sự kiện giao dịch theo item ID\nKhông dùng để tính ngược tồn'),s4:p('P06.S04','Lọc lịch sử từ cùng nguồn'),cross:a('P07 / P09 / P18\nChỉ truyền item ID / serial / vị trí'),unknown:x('Không đủ nguồn / Mapping thiếu\nKhông thay dữ liệu bằng 0 hoặc ID đầu')
},[['query','scope'],['catalog','scope'],['scope','read'],['read','s2'],['stock','s3'],['events','s4'],['s2','s3','Cùng item'],['s2','s4','Cùng item'],['s2','cross'],['read','unknown','Lỗi / ID không hợp lệ'],['unknown','query','Giữ truy vấn để sửa / retry']]));

B('P07','Thẻ NFC',G({
 in:a('P02 · NFC'),s1:p('P07.S01','Danh sách thẻ\nTìm UID / Lọc / Xem chi tiết'),s2:p('P07.S02','Đọc thẻ mô phỏng\nChọn sản phẩm'),lookup:a('P06 picker\nTrả đúng sản phẩm + serial'),read:w('UID đã đọc?\nThẻ khả dụng, không xung đột?'),conflict:a('P17.S03 · Đã liên kết\nKhông ghi đè tùy ý'),device:a('P15.S04 / Lỗi đọc\nKhông tự xin quyền phần cứng'),s3:p('P07.S03','Xác minh liên kết\nĐúng UID và sản phẩm'),send:a('Xác nhận liên kết\nChặn nhấn trùng'),s4:p('P07.S04','Liên kết được xác nhận'),unknown:w('UNKNOWN sau lưu\nKhóa thao tác mới, đối chiếu trước'),back:a('Chi tiết thẻ / Danh sách\nHoặc đọc thẻ tiếp theo'),audit:a('P22 · Audit là nguồn riêng\nKhông tự có event vì thẻ đổi trạng thái')
},[['in','s1'],['s1','s2','Bắt đầu liên kết'],['s2','lookup','Chọn sản phẩm'],['lookup','s2'],['s2','read','Đọc UID'],['read','conflict','Đã gắn / Xung đột'],['conflict','s2','Hủy / Đọc thẻ khác'],['read','device','Không hỗ trợ / Từ chối / Lỗi'],['read','s3','Đủ dữ liệu'],['s3','s2','Back'],['s3','send'],['send','s4','Receipt hợp lệ'],['send','unknown','Chưa rõ'],['s4','back'],['back','s1'],['s1','audit','Đi qua hub Lịch sử']] ),G({
 tags:s('Nguồn trạng thái thẻ\nTag ID · UID · Mapping hiện tại'),s1:p('P07.S01','Danh sách / Lọc theo nguồn thẻ'),s2:p('P07.S02','Lượt đọc UID + Sản phẩm đã chọn'),product:s('Sản phẩm từ P06\nItem ID · Serial, không suy bằng tên'),check:w('Guard phiên/kho/quyền\nKhóa thẻ · Xung đột · Context hiện tại'),s3:p('P07.S03','Snapshot UID + Sản phẩm\nChờ người dùng xác nhận'),req:w('Request liên kết\nĐúng tag/product + thế hệ tác vụ'),adapter:a('NFC preview adapter\nKhông gọi thiết bị NFC thật'),pending:w('UNKNOWN\nKhông suy đã liên kết từ timeout'),receipt:s('Receipt liên kết hợp lệ\nCallback cũ không ghi sang thẻ mới'),s4:p('P07.S04','Hiển thị kết quả đã xác nhận'),audit:x('P22 cần nguồn event độc lập\nMapping hiện tại không phải audit')
},[['tags','s1'],['s1','s2'],['product','s2'],['s2','check'],['tags','check'],['check','s3','Không xung đột'],['s3','req'],['req','adapter'],['adapter','pending','Chưa rõ'],['adapter','receipt','Xác nhận'],['receipt','tags','Cập nhật mapping'],['receipt','s4'],['tags','audit','Không tự sinh event']]));

B('P08','Lịch sử chung',G({
 in:a('P22 hub / Kết quả P04-P05 / P14'),s1:p('P08.S01','Danh sách lịch sử\nTìm kiếm · Lọc ngày · Loại · Tải tiếp'),id:w('Record ID / Session ID có thật?'),missing:x('Không tìm thấy\nKhông dùng phần tử đầu làm mặc định'),s2:p('P08.S02','Chi tiết lịch sử\nThông tin · Timeline · Tệp'),s3:p('P08.S03','Phiên quét B08 tham chiếu\nXem mã và số lượt trùng'),s4:p('P08.S04','Hoạt động theo ngày\nCùng nguồn và bộ lọc'),doc:a('P12 · Chứng từ\nChỉ khi có mapping rõ'),files:a('P18 · Tệp / Viewer\nĐúng document ID và file ID'),legacy:x('B08 khác B23\nKhông đổi namespace chỉ vì trùng PQ'),back:a('Back về danh sách / Màn gọi\nGiữ query, tab, cuộn, focus')
},[['in','s1'],['s1','id','Chọn dòng / Deep link'],['id','missing','Thiếu / Sai ID'],['id','s2','Đúng record'],['s2','s3','Có session tham chiếu'],['s3','legacy'],['s1','s4','Theo ngày'],['s4','s2','Chọn hoạt động'],['s2','doc','Có sourceDocumentId'],['s2','files','Có tệp đã ánh xạ'],['doc','s2','Back đúng caller'],['files','s2','Back giữ tab tệp'],['s3','s2','Back'],['s2','back'],['back','s1']] ),G({
 seed:s('Seed lịch sử B08\nActivity ID · Record ID · Session ID'),receipts:s('Receipt P04/P05 đã xác minh\nCùng actor/kho + Document ID'),project:a('history-source projection\nID receipt:DocumentID\nKhử trùng theo ID chính xác'),s1:p('P08.S01','Danh sách từ nguồn đã hợp nhất'),filters:w('Lọc / Tìm / Phân trang\nTổng dùng cùng tập dữ liệu'),s4:p('P08.S04','Nhóm theo ngày\nKhông đếm lặp activity ID'),s2:p('P08.S02','Chi tiết đúng record\nKhông suy từ số PN/PX'),s3:p('P08.S03','Đọc session B08 đã tham chiếu'),map:s('Mapping explicit sang P12/P18\nHistory record ID → Document ID → File ID'),other:x('P22 / P23 là nguồn độc lập\nKhông tổng hợp NFC/session từ receipt'),ctx:s('history.state + cache view\nQuery · Tab · Scroll · Focus')
},[['seed','project'],['receipts','project'],['project','filters'],['filters','s1'],['filters','s4'],['s1','s2','Record ID'],['s2','s3','Session ID B08'],['s2','map'],['map','s2','Back đúng ngữ cảnh'],['s1','ctx'],['ctx','s1','Khôi phục view'],['project','other','Không tạo event giả']]));

B('P09','Bảo hành',G({
 in:a('Home / P03 / P12 → Bảo hành'),s1:p('P09.S01','Danh sách bảo hành\nTìm kiếm · Trạng thái · Sắp xếp'),lookup:a('P06 · Tra cứu sản phẩm\nMang theo serial'),s2:p('P09.S02','Tiếp nhận bảo hành'),serial:w('Nhập / Đối chiếu đúng serial'),bad:x('Không hợp lệ\nLỗi tại ô, giữ sản phẩm và bản nhập'),exists:a('Đã có hồ sơ\nMở hồ sơ sẵn, không tạo trùng'),fault:a('Chọn lỗi tiếp nhận\nChỉ chọn Khác mới hiện mô tả'),note:a('Ghi chú / Phụ kiện\nKhông bắt buộc'),confirm:w('Kiểm tra và xác nhận tiếp nhận'),s3:p('P09.S03','Hồ sơ bảo hành\nThông tin · Linh kiện · Lịch sử'),edit:w('Dialog cập nhật xử lý\nChẩn đoán · Kết quả sửa chữa'),s4:p('P09.S04','Kết quả sửa chữa\nCHỜ BÀN GIAO'),issue:a('P19 · Xuất linh kiện'),history:a('P20 · Lịch sử linh kiện'),handoff:a('P18 · Bàn giao\nChưa có nguồn xác nhận thật'),closed:x('Hồ sơ đã trả khách\nChỉ xem, khóa thao tác ghi')
},[['in','s1'],['s1','s2','Tiếp nhận'],['lookup','s2','Serial đã chọn'],['s2','serial'],['serial','bad','Sai / Chưa xác minh'],['bad','serial','Sửa'],['serial','exists','Đã có hồ sơ'],['exists','s3'],['serial','fault','Sản phẩm mới hợp lệ'],['fault','note'],['note','confirm'],['confirm','s3','Được xác nhận'],['s1','s3','Chọn hồ sơ'],['s3','edit','Cập nhật xử lý'],['edit','s4','Lưu được xác nhận'],['s4','s3','Xem hồ sơ'],['s3','s1','Về danh sách'],['s3','issue'],['s3','history'],['s3','handoff'],['s3','closed','Trạng thái đã trả khách']] ),G({
 serial:a('Serial nhập tay / Nhận từ P06'),match:w('Đối chiếu đúng serial\nKhông dùng SKU thay serial'),product:s('Sản phẩm · Khách hàng · Liên hệ\nNguồn fixture hiện hành'),s2:p('P09.S02','Bản nhập tiếp nhận\nLỗi · Mô tả Khác · Ghi chú · Phụ kiện'),shared:s('Nguồn hồ sơ dùng chung\nCase ID · Serial · Status\nVersion · Lịch sử xử lý'),s3:p('P09.S03','Bản cập nhật sửa chữa\nChẩn đoán · Kết quả'),guard:w('Phiên · Quyền · Kho · Hồ sơ đóng\nDữ liệu · Version · Chặn gửi trùng'),req:a('Yêu cầu cố định danh\nRequest ID · Session · Case ID\nVersion · Nội dung gửi'),adapter:a('Bộ xử lý hiện tại\nAdapter mô phỏng'),unknown:w('UNKNOWN\nGiữ request, khóa gửi lại'),check:w('Đối chiếu đúng Request ID'),failed:x('Lỗi xác định\nGiữ bản nhập và định danh'),verified:a('Cập nhật hồ sơ và lịch sử\nReceipt khớp đúng yêu cầu'),ledger:s('Phiếu linh kiện POSTED\nĐúng Case ID, từ P19/P20'),qty:a('Tổng quantity\nTách số phiếu / mã / linh kiện'),s1:p('P09.S01','Danh sách và hồ sơ cùng nguồn'),s4:p('P09.S04','Receipt sửa chữa đã xác minh\nChờ bàn giao, chưa trả khách')
},[['serial','match'],['match','product','Đúng serial'],['product','s2'],['shared','s3'],['s2','guard'],['s3','guard'],['guard','req','Hợp lệ'],['req','adapter'],['adapter','failed','Từ chối xác định'],['failed','guard','Sửa / Retry theo owner'],['adapter','unknown','Chưa rõ'],['unknown','check'],['check','unknown','Chưa xác minh'],['adapter','verified','Xác nhận thành công'],['check','verified','Đã xác minh'],['verified','shared'],['shared','s1'],['shared','s3'],['verified','s4'],['ledger','qty'],['qty','s3','Linh kiện đã xuất']]));

B('P10','Cá nhân',G({
 in:a('P02 · Avatar / Tab Cá nhân'),s1:p('P10.S01','Thông tin cá nhân'),s2:p('P10.S02','Chỉnh sửa bản nhập\nTên · Tên gọi · Điện thoại'),dirty:w('Có thay đổi chưa lưu?'),cancel:w('Xác nhận rời bản nhập'),save:x('Lưu hồ sơ / Upload avatar\nAdapter hiện tại chưa kết nối\nKhông báo thành công giả'),s3:p('P10.S03','Công việc & quyền\nChỉ đọc; quyền riêng chưa có nguồn'),s4:p('P10.S04','Tài khoản & bảo mật'),security:a('P11 · Đổi mật khẩu / Phiên đăng nhập'),shift:a('P14 · Kết thúc / Tổng kết ca'),logout:w('Xác nhận đăng xuất\nCảnh báo dữ liệu đang nhập'),blocked:x('UNKNOWN / Yêu cầu cần đối chiếu\nChặn logout không an toàn'),login:a('P01 · Đăng nhập\nBack không phục hồi dữ liệu cũ')
},[['in','s1'],['s1','s2','Sửa hồ sơ'],['s2','save','Lưu / Đổi ảnh'],['save','s2','Giữ dữ liệu tại màn'],['s2','dirty','Back'],['dirty','s1','Không đổi'],['dirty','cancel','Có thay đổi'],['cancel','s2','Ở lại'],['cancel','s1','Đồng ý bỏ bản nhập'],['s1','s3','Xem quyền'],['s1','s4','Bảo mật'],['s4','security'],['s1','shift'],['s1','logout','Đăng xuất'],['logout','blocked','Có yêu cầu bị khóa'],['logout','login','Đủ điều kiện + Đồng ý']] ),G({
 session:s('Session P01 đã xác minh\nActor · Role · Warehouse'),contact:s('Contact fixture B10 theo actor ID\nKhông phải trường xác thực'),read:a('readProfile\nGhép đúng người / kho'),s1:p('P10.S01','Hiển thị hồ sơ'),s2:p('P10.S02','Editable draft\nName · Nickname · Phone'),diff:w('Chỉ lấy trường đã thay đổi\nKhông gửi mật khẩu / quyền'),adapter:x('Profile adapter\nsave=false · avatar=false\nGiữ draft, account không đổi'),s3:p('P10.S03','Quyền từng nghiệp vụ = chưa xác minh\nKhông suy từ role/warehouseOperations'),s4:p('P10.S04','Ý định mở bảo mật\nActor ID · Kho · Return context'),dest:a('P11 / P14\nOwner đích tự kiểm phạm vi'),end:x('Logout làm mất phiên/DOM bảo vệ\nKhông ghi profile giả để hiển thị mới')
},[['session','read'],['contact','read'],['read','s1'],['s1','s2'],['s2','diff','Bấm Lưu'],['diff','adapter'],['adapter','s2','Bị chặn, giữ bản nhập'],['session','s3'],['session','s4'],['s4','dest'],['s1','end','Đăng xuất được xác nhận']]));

B('P11','Bảo mật tài khoản',G({
 in:a('P10.S04 · Tài khoản & bảo mật'),s1:p('P11.S01','Đổi mật khẩu\nHiện tại · Mới · Xác nhận'),valid:w('Trường bắt buộc / Xác nhận khớp?'),s2:p('P11.S02','Lỗi xác thực thông tin\nSửa tại ô, chưa đổi mật khẩu'),send:a('Gửi thay đổi vào account fixture\nChặn gửi trùng'),s3:p('P11.S03','Đã đổi mật khẩu\nChỉ sau receipt hợp lệ'),unknown:w('UNKNOWN / Mất phản hồi\nGiữ yêu cầu, đối chiếu trước retry'),s4:p('P11.S04','Phiên đăng nhập\nĐọc danh sách cùng tài khoản'),revoke:w('Chọn phiên khác → Xác nhận thu hồi'),done:a('Thu hồi đã xác minh\nChỉ bỏ đúng session ID'),back:a('Back về P10\nDọn ô mật khẩu, không giữ bí mật'),expired:a('P15.S02 → P01\nHết phiên cần xác thực lại')
},[['in','s1','Đổi mật khẩu'],['s1','valid','Lưu'],['valid','s2','Sai / Thiếu'],['s2','s1','Sửa'],['valid','send','Hợp lệ'],['send','s3','Đã xác minh'],['send','unknown','Chưa rõ'],['unknown','s3','Đối chiếu xác nhận'],['in','s4','Quản lý phiên'],['s4','revoke'],['revoke','s4','Hủy'],['revoke','done','Xác nhận thành công'],['done','s4','Tải danh sách mới'],['s1','back'],['s3','back'],['s4','back'],['send','expired','Mất phiên/quyền']] ),G({
 session:s('Account store dùng chung P01–P11\nActor ID · Current auth session ID'),s1:p('P11.S01','Mật khẩu chỉ giữ tạm trong form'),s2:p('P11.S02','Validation tại client\nSai xác nhận: không gọi đổi mật khẩu'),ctx:w('Scope tài khoản / Phiên\nAction + Request ID cố định'),adapter:a('Security preview adapter\nNguồn policy / Session list / Reconcile'),unknown:w('Kết quả chưa xác minh\nGiữ pending, không phát lệnh trùng'),receipt:s('Receipt khớp action + request\nKhông nhận callback khác tài khoản'),s3:p('P11.S03','Xác nhận thay đổi fixture\nLogin sau dùng credential mới trong trang'),s4:p('P11.S04','Danh sách session đã kiểm ID\nĐúng 1 phiên hiện tại'),revoke:a('Thu hồi session ID được chọn\nGiữ phiên hiện tại theo policy fixture'),clear:x('Rời màn / Logout / Reload\nDọn ô mật khẩu; không ghi password vào storage')
},[['session','ctx'],['s1','s2'],['s2','ctx','Hợp lệ'],['ctx','adapter'],['adapter','unknown','Chưa rõ / Receipt sai'],['unknown','adapter','Reconcile cùng request'],['adapter','receipt','Đã xác minh'],['receipt','session','Cập nhật đúng account'],['receipt','s3'],['session','adapter','Đọc phiên'],['adapter','s4','Nguồn xác minh'],['s4','revoke'],['revoke','ctx'],['clear','s1','Xóa dữ liệu nhạy cảm']]));

B('P12','Chứng từ',G({
 in:a('Home gần đây / Xem tất cả\nP08 / P13 / Kết quả nhập-xuất'),s1:p('P12.S01','Danh sách chứng từ\nTìm · Lọc · Chọn đúng ID'),s2:p('P12.S02','Chi tiết chứng từ\nThông tin · Trạng thái · Tệp'),s3:p('P12.S03','Sản phẩm cùng chứng từ\nSKU · Quantity · Tìm trong phiếu'),files:a('P18.S01/S02 · Tệp / Viewer'),s4:p('P12.S04','Tạo chứng từ\nChọn loại · NCC · Ghi chú'),type:w('Nhập / Xuất / Bảo hành?'),draft:w('Đã có phiếu đang làm?'),resume:a('Xác nhận tiếp tục đúng owner\nKhông đè dữ liệu bằng form mới'),create:a('P04 / P05 / P09\nTạo qua owner nghiệp vụ'),missing:x('Sai ID / Thiếu nguồn\nKhông lấy chứng từ đầu tiên'),states:a('P16 · Loading / Empty / Error\nGiữ filter và context khi retry'),back:a('Back đúng caller\nGiữ tab, tìm kiếm, cuộn và focus')
},[['in','s1'],['s1','s2','Chọn ID'],['s2','s3','Tab sản phẩm'],['s3','s2','Thông tin'],['s2','files','Mở đúng file ID'],['files','s2','Back'],['s1','s4','Tạo mới'],['s4','type'],['type','draft','Kiểm owner hiện tại'],['draft','resume','Có đúng draft'],['resume','create','Người dùng đồng ý'],['draft','create','Chưa có draft'],['s2','missing','Không xác minh được ID'],['s1','states','Kết quả đọc'],['s2','back'],['back','s1']] ),G({
 seed:s('DOCUMENTS seed theo scope\nDocument ID · Loại · Trạng thái · Lines'),live:s('Owner P04/P05\nReceipt đã record + Draft đang làm'),merge:a('mergeDocuments / recordedDocuments\nScope actor/kho, dedup đúng ID'),s1:p('P12.S01','Danh sách đã lọc\nHome gần đây dùng cùng nguồn'),s2:p('P12.S02','Chi tiết đúng document ID'),s3:p('P12.S03','Lines/tổng cùng document\nSearch không thay quantity gốc'),files:s('Metadata tệp + File ID + URL\nLiên kết P18 đúng chứng từ'),s4:p('P12.S04','Form tạo tạm\nType · Supplier ID · Note'),guard:w('Quyền / Kho / Metadata\nResume ID phải khớp owner'),handoff:a('Giao lệnh tạo/tiếp tục cho P04/P05/P09\nP12 không tự ghi kho'),reader:a('Read controller P16\nQuery generation · Scope · Cache'),missing:x('Nguồn thiếu / ID sai\nKhông suy thành chứng từ rỗng')
},[['seed','merge'],['live','merge'],['merge','reader'],['reader','s1'],['s1','s2','ID thật'],['s2','s3'],['s2','files'],['s4','guard'],['live','guard','Kiểm draft có sẵn'],['guard','handoff','Được phép'],['reader','missing','Không xác minh'],['missing','s1','Hiển thị state đúng']]));

B('P13','Thông báo & theo dõi Web',G({
 in:a('P02 · Chuông thông báo'),s1:p('P13.S01','Danh sách thông báo\nTất cả / Chưa đọc / Xem thêm'),s2:p('P13.S02','Chi tiết thông báo\nĐúng event, không tự duyệt phiếu'),read:a('Đánh dấu đã đọc\nBadge cập nhật khi nguồn xác nhận'),doc:a('P12 · Đúng chứng từ liên quan'),s3:p('P13.S03','Phiếu chờ xử lý trên Web\nLọc nhập / xuất'),s4:p('P13.S04','Chi tiết phiếu chờ Web\nChỉ xem trong App'),web:x('Hướng dẫn xử lý trên Web\nKhông có URL thì báo chưa cấu hình'),missing:x('Thông báo/chứng từ không tồn tại\nKhông fallback sang ID khác'),back:a('Back về đúng list/tab\nGiữ lọc, số dòng, cuộn và focus')
},[['in','s1'],['s1','s2','Mở event'],['s2','read'],['read','s1','Cập nhật trạng thái đọc'],['s2','doc','Có document ID hợp lệ'],['s2','s3','Các phiếu chờ Web'],['s3','s4','Chọn đúng phiếu'],['s4','doc','Xem chứng từ'],['s4','web','Hướng dẫn Web'],['s2','missing','Thiếu tham chiếu'],['s4','missing','ID sai'],['s2','back'],['s4','s3','Back'],['back','s1']] ),G({
 events:s('Notification store theo scope\nEvent ID · Document ID · Read flag'),docs:s('Nguồn P12 dùng chung\nChứng từ / Trạng thái / Lines'),s1:p('P13.S01','Trang thông báo từ nguồn\nKhông suy badge từ số DOM đã tải'),s2:p('P13.S02','Chi tiết event chính xác'),guard:w('Actor/kho + generation hiện tại\nKhông để UI trễ ghi đè view mới'),read:a('Mark-read request\nChỉ cập nhật event đã xác nhận'),badge:a('Badge chưa đọc P02/P13\nCùng notification store'),waiting:a('Lọc phiếu nhập/xuất chờ Web\nTừ nguồn chứng từ hiện hành'),s3:p('P13.S03','Danh sách chờ xử lý'),s4:p('P13.S04','Chi tiết đọc cùng Document ID'),noWrite:x('Approval cũ đã MIGRATED\nKhông approve/Post/đổi tồn trên App')
},[['events','s1'],['s1','s2','Event ID'],['s2','guard','Đánh dấu đọc'],['guard','read'],['read','events','Kết quả hợp lệ'],['events','badge'],['docs','s2','Tham chiếu hợp lệ'],['docs','waiting'],['waiting','s3'],['s3','s4','Document ID'],['docs','s4'],['s4','noWrite']]));

B('P14','Khôi phục tài khoản & ca làm việc',G({
 login:a('P01 · Quên mật khẩu'),s1:p('P14.S01','Nhập tài khoản cần hỗ trợ'),request:a('Gửi yêu cầu hỗ trợ mô phỏng\nKhông gửi email/SMS thật'),s2:p('P14.S02','Xác nhận yêu cầu hỗ trợ\nChỉ sau receipt hợp lệ'),unk:w('UNKNOWN\nGiữ request, kiểm tra kết quả'),profile:a('P10 · Kết thúc ca'),s3:p('P14.S03','Phiếu đang thực hiện\nTừ đúng owner trong phiên'),resume:a('Tiếp tục P04/P05/P19/P21\nKhông tạo phiếu thay thế'),guard:w('Còn nháp chưa lưu / UNKNOWN?'),save:a('Xác nhận lưu nháp\nGiữ checkpoint trong bộ nhớ'),end:a('Xác nhận kết thúc ca\nKhông tự đăng xuất'),s4:p('P14.S04','Tổng kết ca\nKPI fixture + nháp đã giữ'),logout:w('Đăng xuất khi đủ điều kiện\nGiữ nháp đúng tài khoản/kho trong trang'),blocked:x('Nguồn chưa rõ / Nháp thay đổi\nKhông kết thúc ca giả')
},[['login','s1'],['s1','request','Dữ liệu hợp lệ'],['request','s2','Receipt xác minh'],['request','unk','Chưa rõ'],['unk','s2','Check xác nhận'],['s1','login','Back giữ username, xóa password'],['profile','s3'],['s3','resume','Chọn phiếu'],['s3','guard','Kết thúc ca'],['guard','blocked','UNKNOWN / Đang gửi'],['guard','save','Nháp chưa lưu'],['save','guard','Đã lưu đúng snapshot'],['guard','end','Không còn nháp chưa lưu'],['end','s4','Receipt + dữ liệu còn khớp'],['s4','logout','Đăng xuất']] ),G({
 s1:p('P14.S01','Username khôi phục\nKhông yêu cầu phiên đăng nhập'),recovery:a('Request recovery cố định ID'),s2:p('P14.S02','Receipt recovery\nID + Thời điểm đã xác minh'),owners:s('Snapshot P04/P05/P19\nDocument/Session/Version/Lines\nP03 projection không đếm trùng'),s3:p('P14.S03','Danh sách trong cùng actor/kho'),scope:w('Auth session scope\nFingerprint nội dung checkpoint'),save:s('Dấu nháp đã lưu trong phiên\nCache địa chỉ không làm nháp bẩn giả'),end:a('Request end\nSnapshot ca + Danh sách nháp'),adapter:a('Adapter recovery/save/end/check'),pending:w('Pending / UNKNOWN\nGiữ request, đối chiếu cùng ID'),receipt:s('Receipt end đã kiểm\nRequest/scope khớp, nháp không đổi'),s4:p('P14.S04','KPI từ aggregate B14\nKhông tính từ số dòng client'),retained:s('Retention trong bộ nhớ trang\nNamespace + Actor + Kho\nĐăng nhập lại cùng owner mới phục hồi'),limit:x('Reload trang mất bộ nhớ\nKhông phải lưu bền WMS')
},[['s1','recovery'],['recovery','adapter'],['adapter','s2','Recovery xác nhận'],['owners','s3'],['s3','scope'],['scope','save','Save xác nhận đúng nội dung'],['save','end','Đủ điều kiện'],['end','adapter'],['adapter','pending','Chưa rõ / Snapshot lệch'],['pending','adapter','Check đúng request'],['adapter','receipt','End xác nhận'],['receipt','s4'],['owners','retained','Giữ trước logout được phép'],['retained','owners','Phục hồi đúng owner'],['retained','limit']]));

B('P15','Trạng thái hệ thống',G({
 caller:a('Màn đang đọc / Ghi / Quét\nGiữ context gốc'),classify:w('Phân loại lỗi đúng nguyên nhân'),s1:p('P15.S01','Mất kết nối / Lỗi mạng'),s2:p('P15.S02','Phiên hết hạn'),s3:p('P15.S03','Không có quyền'),s4:p('P15.S04','Camera / NFC\nKhông hỗ trợ hoặc quyền bị từ chối'),retry:w('Có thao tác đọc được phép retry?\nKhông retry lệnh ghi UNKNOWN'),back:a('Về màn gọi\nGiữ dữ liệu, focus và cuộn'),auth:a('P01 · Đăng nhập lại\nNội dung bảo vệ mất ngay'),guide:a('Hướng dẫn / Kênh liên hệ\nThiếu cấu hình thì báo rõ'),check:a('P17 / Owner request\nĐối chiếu thay vì gửi lại'),denied:x('Handler / Deep link vẫn kiểm guard\nKhông chỉ ẩn nút trên giao diện')
},[['caller','classify'],['classify','s1','Kết nối'],['classify','s2','Hết phiên'],['classify','s3','Thiếu quyền'],['classify','s4','Thiết bị'],['s1','retry'],['retry','caller','Read retry hợp lệ'],['retry','check','Yêu cầu ghi chưa rõ'],['s1','back'],['s4','guide'],['guide','back'],['s2','auth'],['s3','denied'],['s3','back','Chỉ trở lại khi guard cho phép']] ),G({
 error:a('Lỗi từ owner / Adapter / Session\nKhông lấy thông báo text làm kết quả ghi'),ctx:s('Ngữ cảnh màn gọi\nRoute · Action · Request ID\nDocument ID · Scope · Focus/scroll'),classify:w('classifySystemError\nIntent: đọc / ghi / đối chiếu'),s1:p('P15.S01','Network state + callback retry hợp lệ'),s2:p('P15.S02','Session expiry\nVô hiệu callback và DOM cũ'),s3:p('P15.S03','Permission denial\nGuard tại handler và route'),s4:p('P15.S04','Trạng thái khả năng/quyền thiết bị'),owner:a('Owner vẫn sở hữu yêu cầu\nP15 không tạo request nghiệp vụ mới'),unknown:w('UNKNOWN giữ nguyên request\nChỉ gọi read/check được cho phép'),back:a('Khôi phục context khi được phép\nKhông phục hồi phiên đã bị thu hồi')
},[['error','classify'],['ctx','classify'],['classify','s1'],['classify','s2'],['classify','s3'],['classify','s4'],['s1','owner','Retry đọc'],['owner','unknown','Ghi chưa rõ'],['unknown','owner','Đối chiếu cùng request'],['ctx','back'],['s4','back'],['s2','owner','Hủy quyền tác vụ cũ ngay']]));

B('P16','Trạng thái dữ liệu',G({
 in:a('P12 · Đọc danh sách chứng từ'),s1:p('P16.S01','Đang tải\nKhông thay đổi kích thước bố cục'),result:w('Kết quả đọc có xác minh?'),list:a('P12.S01 · Có dữ liệu'),s2:p('P16.S02','Nguồn xác nhận rỗng\nKhông có điều kiện lọc'),create:a('P12.S04 · Tạo chứng từ\nChỉ khi được phép'),s3:p('P16.S03','Không có kết quả phù hợp\nGiữ từ khóa / Bộ lọc'),edit:a('Sửa từ khóa / Bỏ điều kiện\nKhông xóa dữ liệu nguồn'),s4:p('P16.S04','Lỗi đọc / Nguồn thiếu\nKhông giả thành kết quả rỗng'),retry:a('Thử lại cùng scope + query'),stale:a('Có cache: giữ dữ liệu cũ\nGhi rõ chưa cập nhật được'),leave:a('Rời màn / Đổi query\nBỏ response cũ, không giành focus')
},[['in','s1'],['s1','result'],['result','list','Có dòng hợp lệ'],['result','s2','Rỗng không lọc'],['result','s3','Rỗng do query/lọc'],['result','s4','Lỗi / Null / Không xác minh'],['s2','create'],['s3','edit'],['edit','s1'],['s4','retry'],['retry','s1'],['s4','stale','Có cache cùng context'],['s1','leave'],['leave','s1','Query mới']] ),G({
 query:a('Query + Filter + Kho + Phiên'),key:w('Cache key + Query generation\nMột read đang chờ cho context'),adapter:a('Read port của nguồn P12\nKhông phải lệnh tạo/ghi chứng từ'),s1:p('P16.S01','Pending read / Loading'),response:w('Kiểm response còn đúng generation\nScope chưa đổi, dữ liệu hợp lệ'),s2:p('P16.S02','Verified empty\nKhông query/filter'),s3:p('P16.S03','Verified no-results\nCó điều kiện tìm kiếm'),s4:p('P16.S04','Read failure / Nguồn không hợp lệ'),cache:s('Cache cùng context\nGiữ hàng đã đọc, gắn trạng thái stale'),rows:a('P12 render rows + metadata\nFocus/cuộn không bị callback cũ lấy lại'),late:x('Response trễ / Đã hủy / Sai scope\nBỏ kết quả, không ghi đè view mới')
},[['query','key'],['key','s1'],['key','adapter'],['adapter','response'],['response','late','Sai thế hệ/phạm vi'],['response','s2','Rỗng không lọc'],['response','s3','Không khớp tìm kiếm'],['response','s4','Lỗi / Thiếu nguồn'],['response','cache','Dữ liệu đã xác minh'],['cache','rows'],['s4','cache','Giữ cache cũ nếu có'],['s4','key','Retry đọc cùng context']]));

B('P17','Ngoại lệ quét',G({
 entry:a('Đang quét / Gửi phiếu\nP04 · P05 · P07'),s1:p('P17.S01','Mã không hợp lệ\nP04 giữ raw và danh sách hợp lệ'),repair:a('Nhập mã / Sửa mã vừa nhập\nQuay lại đúng phiên quét'),s2:p('P17.S02','Mã không thể xuất\nP05 hiển thị lý do từ nguồn'),other:a('Quét mã khác\nKhông cộng mã bị chặn'),s3:p('P17.S03','NFC đã có liên kết / Xung đột'),nfc:a('Xem liên kết / Hủy\nKhông tự ghi đè mapping'),s4:p('P17.S04','Kết quả gửi chưa xác định\nGiữ phiếu, khóa gửi lại'),check:w('Kiểm tra đúng request hiện tại'),yes:a('P04/P05.S04 · Chờ Web\nChỉ khi xác nhận đã record'),no:a('Chưa record được xác minh\nRetry cùng yêu cầu nếu được phép'),unknown:w('Vẫn UNKNOWN / Thiếu nguồn\nGiữ khóa, chờ đối chiếu'),home:a('Rời màn không xóa request\nTrở lại vẫn giữ trạng thái')
},[['entry','s1','Mã nhập không hợp lệ'],['s1','repair'],['repair','entry'],['entry','s2','Nguồn từ chối xuất'],['s2','other'],['other','entry'],['entry','s3','Thẻ xung đột'],['s3','nfc'],['nfc','entry','Hủy / Đọc mã khác'],['entry','s4','Timeout / Mất phản hồi'],['s4','check'],['check','yes','Đã ghi nhận'],['check','no','Chưa ghi nhận + retryAllowed'],['check','unknown','Chưa rõ'],['unknown','check','Thử đọc trạng thái'],['s4','home']] ),G({
 input:a('Raw code / UID\nTừ cùng pipeline của owner'),owner:s('Snapshot P04/P05/P07\nDocument/Tag ID · Scan session\nAccepted · Request · Version'),s1:p('P17.S01','Raw + Lý do không hợp lệ'),s2:p('P17.S02','Nguồn từ chối xuất\nSản phẩm / Chứng từ liên quan nếu có'),s3:p('P17.S03','Mapping thẻ đã xác minh\nUID + Sản phẩm liên kết'),same:w('Không thay accepted/quantity\nKhông tạo phiếu hoặc liên kết khác'),s4:p('P17.S04','Snapshot request UNKNOWN\nChặn lệnh gửi mới'),check:a('Status read bằng request gốc\nKhông gọi record/Post lần nữa'),result:w('Receipt có khớp request/scope?'),record:s('Kết quả record đã xác minh\nCùng Document ID'),notRecorded:a('Kết quả chưa record + quyền retry\nDo adapter/owner quyết định'),keep:x('Không có nguồn / Receipt sai\nGiữ nguyên UNKNOWN và dữ liệu')
},[['input','owner'],['owner','s1','Invalid scan'],['owner','s2','Không thể xuất'],['owner','s3','Conflict NFC'],['s1','same'],['s2','same'],['s3','same'],['owner','s4','Ghi chưa rõ'],['s4','check'],['check','result'],['result','record','Khớp + đã record'],['result','notRecorded','Xác minh chưa record'],['result','keep','Chưa xác minh'],['keep','s4']]));

B('P18','Tệp, bàn giao & vị trí',G({
 docs:a('P12 / P08\nDocument ID + File ID'),s1:p('P18.S01','Danh sách tệp của chứng từ\nTrạng thái tải / Lỗi / Hủy'),s2:p('P18.S02','Viewer PDF / Ảnh\nTrang · Zoom · Fit · Tải xuống'),fileErr:x('Thiếu file / Lỗi đọc\nThử lại nguồn, không đổi chứng từ'),back:a('Back về đúng tệp và màn gọi\nGiữ trang/zoom/cuộn/focus'),caseIn:a('P09 · Đúng hồ sơ bảo hành'),s3:p('P18.S03','Thông tin bàn giao\nKiểm máy · Người nhận · Ngày · Ghi chú'),guard:w('Hồ sơ Chờ bàn giao?\nDữ liệu hợp lệ / Quyền / Kho?'),blocked:x('Chưa có nguồn xác nhận bàn giao\nKhông gửi thật, không đóng hồ sơ'),closed:x('Đã trả khách / Chưa sẵn sàng\nChỉ đọc hoặc chặn thao tác'),item:a('P06.S03 · Vị trí sản phẩm'),s4:p('P18.S04','Vị trí cùng item ID\nSơ đồ sức chứa chỉ khi có nguồn'),readonly:a('Xem chi tiết vị trí / Về P06\nKhông di chuyển hàng hoặc ghi tồn')
},[['docs','s1'],['s1','s2','Đúng file ID'],['s2','fileErr','Lỗi tải'],['fileErr','s2','Retry đọc'],['s2','s1','Back'],['s1','back'],['caseIn','s3'],['s3','guard','Kiểm tra gửi'],['guard','blocked','Thiếu contract/adapter xác nhận'],['guard','closed','Case đóng / Không đủ điều kiện'],['s3','back','Back; giữ bản nhập theo owner'],['item','s4'],['s4','readonly'],['readonly','item','Back đúng item']] ),G({
 docs:s('Nguồn chứng từ P12 / Mapping P08\nDocument ID · Danh sách file'),s1:p('P18.S01','Metadata tệp\nFile ID · Task ID · State · Progress'),queue:a('Upload queue fixture\nRetry/cancel đúng task + generation'),s2:p('P18.S02','Đọc URL file đã xác minh\nPDF bytes / Ảnh + Viewer state'),scope:w('Actor · Auth session · Kho\nKiểm scope trước đọc/tải/nhận callback'),cancel:x('Rời màn / Đổi file / Mất quyền\nAbort read, bỏ callback cũ'),cases:s('Nguồn hồ sơ P09\nCase ID · Status · Closed'),s3:p('P18.S03','Bản nhập bàn giao\nChecked · Receiver · Day · Note'),handoff:x('Nguồn xác nhận bàn giao chưa có\nKhông mutate case, không báo đã trả khách'),items:s('Nguồn vị trí P06\nItem ID · Location'),s4:p('P18.S04','Vị trí / Slot read-only'),capacity:w('Có số liệu sức chứa xác minh?\nKhông có: để chưa xác minh, không suy 0')
},[['docs','s1'],['s1','queue','Sự kiện fixture có task ID'],['queue','s1','Token phải khớp'],['s1','scope','Mở file'],['scope','s2','Hợp lệ'],['cancel','s2','Dừng đọc/không nhận kết quả cũ'],['cases','s3'],['s3','scope','Kiểm phạm vi'],['s3','handoff'],['items','s4'],['capacity','s4','Chỉ hiển thị nguồn đã có']]));

B('P19','Xuất linh kiện bảo hành',G({
 in:a('P09 hồ sơ / P21 tiếp tục\nĐúng Case ID + Draft ID'),guard:w('Case còn mở? Kho/quyền hợp lệ?'),closed:x('Case đóng / Thiếu scope\nKhông mở xuất mới'),s1:p('P19.S01','Quét linh kiện / Nhập tay\nGiữ đúng phiếu và phiên'),code:w('Mã đơn hay BOX?\nMã được phép xuất?'),s2:p('P19.S02','Sheet số lượng BOX\nKhông vượt tồn đã xác minh'),invalid:a('P24.S01 / P24.S02\nLỗi số lượng / Hộp chưa thể xuất'),lines:a('Danh sách linh kiện hợp lệ\nSố mã khác tổng quantity'),s3:p('P19.S03','Kiểm tra linh kiện\nXác nhận xuất trực tiếp'),post:a('Post mô phỏng một lần\nKiểm lại case, tồn và version'),s4:p('P19.S04','ĐÃ XUẤT\nChỉ sau receipt POSTED hợp lệ'),unknown:a('P21.S04 · UNKNOWN\nĐối chiếu cùng request, không repost'),history:a('P09 hồ sơ / P20 lịch sử\nCùng receipt của đúng case'),resume:a('P21.S02 · Giữ phiếu đang làm\nBack không bỏ dữ liệu')
},[['in','guard'],['guard','closed','Không đủ'],['guard','s1','Đủ điều kiện'],['s1','code'],['code','s2','BOX hợp lệ'],['code','lines','Mã đơn hợp lệ'],['code','invalid','Không được xuất'],['s2','invalid','Số lượng sai'],['invalid','s1','Sửa / Quét mã khác'],['s2','lines','Xác nhận số lượng hợp lệ'],['lines','s1','Quét tiếp'],['s1','s3','Có dòng hợp lệ'],['s3','s1','Back'],['s3','post','Xác nhận'],['post','s4','Receipt đã xác minh'],['post','unknown','Chưa rõ'],['s4','history'],['s1','resume','Rời bước quét']] ),G({
 cases:s('Nguồn hồ sơ bảo hành P09\nCase ID · Trạng thái · Kho'),s1:p('P19.S01','Owner phiếu linh kiện\nDocument ID · Scan session · Version'),catalog:s('Danh mục mã đơn / BOX\nSKU · Tồn khả dụng đã xác minh'),s2:p('P19.S02','Quantity tạm trong sheet\nHủy không thêm dòng'),validate:w('Kiểm mã + số lượng + tồn\nCase/quyền/kho vẫn hợp lệ'),lines:s('Accepted lines của cùng owner\nStable code ID · SKU · Quantity'),s3:p('P19.S03','Review từ lines hiện hành'),req:w('Request Post cố định danh\nCase + Document + Session + Version'),adapter:a('Post / Check adapter mô phỏng'),unknown:w('UNKNOWN giữ nguyên request\nKhông tạo lệnh Post thứ hai'),receipt:s('Receipt POSTED đã xác minh\nCase ID · Receipt ID · Request ID'),s4:p('P19.S04','Hiển thị Đã xuất\nKhông dùng trạng thái Chờ Web'),ledger:a('P09 / P20 nhận đúng receipt\nChỉ ledger POSTED của đúng case')
},[['cases','s1'],['s1','validate'],['catalog','validate'],['s2','validate'],['validate','lines','Hợp lệ'],['lines','s3'],['s3','req'],['req','adapter'],['adapter','unknown','Mất phản hồi'],['unknown','adapter','Check cùng request'],['adapter','receipt','Kết quả hợp lệ'],['receipt','s4'],['receipt','ledger'],['receipt','s1','Khóa phiếu đã Post']]));

B('P20','Lịch sử linh kiện đã xuất',G({
 in:a('P09 / P19 / P21 / P23\nMang đúng Case ID'),s1:p('P20.S01','Linh kiện đã xuất\nPhiếu POSTED của hồ sơ'),s2:p('P20.S02','Tải thêm lịch sử\nGiữ các dòng đã đọc'),s3:p('P20.S03','Lỗi tải thêm\nGiữ cursor và cache'),s4:p('P20.S04','Nguồn xác nhận chưa có phiếu'),retry:a('Thử tải lại cùng context\nChỉ đọc, không Post'),detail:a('Mở rộng phiếu / Xem dòng linh kiện\nKhông đổi quantity'),next:w('Có phiếu linh kiện đang làm?'),resume:a('P21 · Tiếp tục / Đối chiếu'),issue:a('P19 · Xuất linh kiện mới\nChỉ khi case mở và được phép'),closed:a('P24.S04 · Hồ sơ đã trả khách\nChỉ đọc; P23 xem quá trình'),back:a('Back đúng caller\nGiữ cuộn, focus, phiếu vừa chọn')
},[['in','s1','Nguồn có phiếu'],['in','s4','Verified empty'],['s1','s2','Tải thêm'],['s2','s1','Thành công / Dedup'],['s2','s3','Lỗi'],['s3','retry'],['retry','s2'],['s1','detail'],['detail','s1','Thu gọn'],['s1','next','Xuất / Tiếp tục'],['s4','next'],['next','resume','Có draft hoặc UNKNOWN'],['next','issue','Không draft + Đủ quyền'],['s1','closed','Case đóng'],['closed','back'],['s1','back']] ),G({
 ctx:a('Case ID + Scope + Caller\nReceipt focus nếu được xác minh'),source:s('Nguồn lịch sử read-only\nSeed riêng + P19 receipts POSTED'),filter:w('Đúng case/kho · POSTED\nImmutable ID · Không nhận trùng'),store:s('Cache lịch sử theo case\nItems · Cursor · Has more · Focus'),s1:p('P20.S01','Danh sách phiếu đã tải'),s2:p('P20.S02','Một read đang chờ\nKhông mất cache khi tải tiếp'),s3:p('P20.S03','Read error giữ cursor\nKhông biến thành empty'),s4:p('P20.S04','Đã đọc và rỗng thật\nKhông phải nguồn unavailable'),late:x('Rời màn / Case khác / Scope khác\nHủy read, bỏ response cũ'),sum:a('Tổng từ dòng của mỗi receipt\nPhân biệt số phiếu / mã / quantity'),draft:s('P19 live draft của cùng case\nĐể mở P21, không trộn vào ledger'),closed:w('Case đã trả khách\nKhóa xuất mới; vẫn đối chiếu request cũ')
},[['ctx','filter'],['source','filter'],['filter','store'],['store','s1'],['s1','s2','Load more cùng cursor'],['s2','source','Read'],['s2','s3','Lỗi'],['s3','s2','Retry cùng cursor'],['store','s4','Verified empty'],['store','sum'],['late','store','Không ghi đè cache khác'],['draft','s1','CTA tiếp tục riêng'],['closed','s1','Read-only guard']]));

B('P21','Tiếp tục phiếu linh kiện',G({
 in:a('Back từ P19 / Tiếp tục từ P09\nChọn đúng draft owner'),s1:p('P21.S01','Phiếu đang thực hiện\nChỉ owner hiện có; B21 là mẫu riêng'),s2:p('P21.S02','Tiếp tục đúng phiếu\nĐọc checkpoint trước khi quét'),check:w('Đúng document/session/version?\nMã đã ghi nhận có xác minh?'),scan:a('P19 · Quét tiếp / Kiểm tra\nGiữ lines và định danh'),s3:p('P21.S03','Cần đối chiếu\nLệch version / Thiếu xác minh'),readonly:x('Không tự thay phiên / Tạo phiếu mới\nKhông cho quét hoặc Post'),s4:p('P21.S04','Kiểm tra kết quả xuất\nRequest Post đang UNKNOWN'),reconcile:w('Đối chiếu cùng request'),posted:a('P20 · Receipt POSTED\nĐúng case và đúng phiếu'),notPosted:a('Chưa Post được xác minh\nĐọc lại checkpoint trước tiếp tục'),unknown:w('Vẫn chưa rõ / Lỗi nguồn\nGiữ khóa và dữ liệu'),back:a('Chi tiết → Danh sách → Home\nKhông xóa draft khi Back')
},[['in','s1'],['s1','s2','Chọn document ID'],['in','s2','Caller đã có ID'],['s2','check'],['check','scan','Khớp + Được phép'],['check','s3','Chưa khớp / Chưa rõ'],['s3','readonly'],['s2','s4','Post đang UNKNOWN'],['s4','reconcile'],['reconcile','posted','Đã Post xác minh'],['reconcile','notPosted','Chưa Post xác minh'],['notPosted','s2','Đọc lại'],['reconcile','unknown','Không xác minh'],['unknown','s4'],['s2','back'],['s1','back']] ),G({
 owner:s('Owner P19 hiện có\nDocument ID · Case ID · Session\nVersion · Lines · Request/receipt'),s1:p('P21.S01','Danh sách pending từ live owner\nKhông dựng lại từ số phiếu'),read:a('Nguồn checkpoint đọc theo ID\nCùng scope và generation'),compare:w('So document/session/version\nRecorded lines / UNKNOWN status'),s2:p('P21.S02','Checkpoint khớp\nMở lại chính owner P19'),s3:p('P21.S03','Conflict / Chưa xác minh\nRead-only, không sửa bằng dữ liệu đoán'),s4:p('P21.S04','Request UNKNOWN được giữ nguyên'),status:a('Đọc trạng thái request\nCase đóng vẫn được check yêu cầu cũ'),receipt:s('Receipt POSTED có nguồn\nCase + Document + Request khớp'),notpost:a('Xác nhận chưa Post\nĐọc lại checkpoint, không auto-Post'),history:a('P20 dùng đúng receipt\nCaller/scroll/focus cùng case'),stale:x('Response cũ / Mất phiên / Đổi owner\nKhông cập nhật vào phiếu khác')
},[['owner','s1'],['s1','read'],['owner','compare'],['read','compare'],['compare','s2','Khớp'],['compare','s3','Lệch / Không rõ'],['compare','s4','Post UNKNOWN'],['s2','owner','Resume cùng đối tượng'],['s4','status'],['status','receipt','Đã Post xác minh'],['receipt','history'],['status','notpost','Chưa Post xác minh'],['notpost','read'],['read','stale','Scope/generation đổi']]));

B('P22','Hub lịch sử & NFC audit',G({
 in:a('P02 · Tab Lịch sử'),s1:p('P22.S01','Hub lịch sử · 6 mục\nKhông có shortcut draft đã bỏ'),general:a('P08.S01 · Lịch sử chung\nHoặc lịch sử chứng từ theo scope'),daily:a('P08.S04 · Hoạt động theo ngày'),war:a('P23.S01 · Lịch sử bảo hành'),sessions:a('P23.S03 · Lịch sử phiên quét'),s2:p('P22.S02','Lịch sử thao tác NFC\nTìm UID / Lọc / Tải thêm'),s3:p('P22.S03','Chi tiết đúng event ID\nKhông suy từ trạng thái thẻ'),s4:p('P22.S04','Nguồn lịch sử chưa khả dụng\nKhông hiển thị rỗng thành công'),retry:a('Thử đọc lại nguồn event'),back:a('Back về list / Hub / Home\nGiữ điều kiện, cuộn và focus')
},[['in','s1'],['s1','general','Lịch sử chung / Chứng từ'],['s1','daily','Theo ngày'],['s1','war','Bảo hành'],['s1','sessions','Phiên quét'],['s1','s2','NFC'],['s2','s3','Chọn event ID'],['s3','s2','Back'],['s2','s4','Nguồn chưa có / Không xác minh'],['s4','retry'],['retry','s2','Nguồn xác minh'],['s2','back'],['s1','back']] ),G({
 s1:p('P22.S01','Chỉ điều hướng 6 nguồn lịch sử\nKhông tạo thêm draft hay sự kiện'),source:s('Nguồn event NFC độc lập\nImmutable event ID · UID · Actor\nKho · Thời điểm · Kết quả'),guard:w('Scope / Envelope / ID hợp lệ\nKhông coi unavailable là empty'),cache:s('Items + Cursor + Complete\nDedup theo event ID'),s2:p('P22.S02','Filter/search từ dữ liệu nguồn\nBadge phản ánh phạm vi đã đọc'),s3:p('P22.S03','Exact event ID\nNội dung và tham chiếu có nguồn'),s4:p('P22.S04','Trạng thái unavailable\nGiữ dữ liệu cũ nếu read lỗi phù hợp'),request:a('Read/reload cùng context\nChặn single-flight, bỏ kết quả trễ'),tag:x('P07 current mapping không phải audit\nKhông chế event sau thao tác thẻ'),sample:a('Mẫu B22 chỉ opt-in\nNguồn mặc định có thể chưa khả dụng')
},[['s1','request','Mở NFC'],['sample','source'],['request','source'],['source','guard'],['guard','cache','Xác minh được'],['guard','s4','Chưa xác minh'],['cache','s2'],['s2','s3','Event ID tồn tại'],['s4','request','Retry chỉ đọc'],['tag','source','KHÔNG tự tổng hợp event','dashed']]));

B('P23','Lịch sử bảo hành & phiên quét',G({
 hub:a('P22 hub / P20 xem quá trình'),s1:p('P23.S01','Danh sách lịch sử bảo hành\nTìm / Lọc đúng nguồn hồ sơ'),s2:p('P23.S02','Quá trình đúng Case ID\nTimeline và linh kiện đã xuất'),parts:a('P20 · Lịch sử linh kiện\nGiữ case và caller quay lại'),s3:p('P23.S03','Lịch sử phiên quét\nNguồn session độc lập'),s4:p('P23.S04','Chi tiết đúng session ID\nTrạng thái phiên khác kết quả phiếu'),links:a('Hồ sơ / Phiếu liên quan\nChỉ mở khi có mapping xác minh'),unavailable:x('Nguồn thiếu / Session không có\nKhông lấy phiên đầu làm mặc định'),back:a('Back giữ query/filter/scroll/focus\nVề đúng hub hoặc P20'),readOnly:w('Case đã trả khách / Phiên kết thúc\nXem lịch sử không phát sinh lệnh ghi')
},[['hub','s1','Bảo hành'],['s1','s2','Chọn Case ID'],['s2','parts','Linh kiện'],['parts','s2','Back đúng caller'],['hub','s3','Phiên quét'],['s3','s4','Session ID xác minh'],['s4','links'],['s3','unavailable','Không có nguồn'],['s4','unavailable','ID sai / Không có sự kiện'],['s2','readOnly'],['s4','readOnly'],['s2','back'],['s4','s3','Back'],['s3','back']] ),G({
 cases:s('Nguồn P09 dùng chung\nCase ID · Status · Timeline xác minh'),s1:p('P23.S01','Danh sách hồ sơ đã lọc'),s2:p('P23.S02','Timeline đúng Case ID\nKhông dựng event từ status cuối'),ledger:s('Receipt POSTED P19/P20\nLiên quan đúng case'),sessions:s('Nguồn phiên quét B23 riêng\nSession ID · Operation · Events\nSession status · Document result'),scope:w('Kho / Session ID / Event schema\nNull số liệu không đổi thành 0'),s3:p('P23.S03','Trang session đã đọc\nSearch trên nguồn, không chỉ DOM'),s4:p('P23.S04','Events đúng session\nAccepted / Rejected / Duplicate\nQuantity theo kết quả đã xác minh'),map:w('Liên kết case/receipt explicit\nENDED không đồng nghĩa POSTED'),legacy:x('B08 và B23 khác namespace\nTrùng mã PQ không phải cùng phiên'),stale:x('Response trễ / Sai scope\nKhông ghi đè visit mới')
},[['cases','s1'],['cases','s2'],['s1','s2','Case ID'],['ledger','s2','Receipt đúng case'],['sessions','scope'],['scope','s3','Hợp lệ'],['s3','s4','Session ID'],['sessions','s4','Event đúng session'],['s4','map'],['ledger','map','Chỉ liên kết receipt thật'],['legacy','sessions','KHÔNG trộn nguồn','dashed'],['scope','stale','Nguồn/thế hệ không khớp']]));

B('P24','Trạng thái Scanner dùng chung',G({
 context:a('Trạng thái phát sinh từ owner\nBốn nhánh độc lập, không phải 4 bước'),qty:a('P19 · Sheet số lượng BOX'),s1:p('P24.S01','Số lượng sai / Vượt tồn\nLỗi tại ô, không xác nhận'),fix:a('Sửa số lượng hợp lệ hoặc Hủy\nKhông cộng dòng khi chưa xác nhận'),scan:a('P19 · Quét BOX chưa thể xuất'),s2:p('P24.S02','Thông báo mã hộp bị chặn\nGiữ accepted list và phiếu'),retry:a('Quét mã khác / Sửa mã vừa nhập'),record:a('P04 / P05 · Record đã xác minh'),s3:p('P24.S03','CHỜ XỬ LÝ TRÊN WEB\nChưa ghi sổ, chưa đổi tồn'),links:a('P12 xem phiếu / P08 lịch sử\nCùng receipt, không Post'),closed:a('P09 / P20 · Case đã trả khách'),s4:p('P24.S04','Hồ sơ chỉ đọc\nKhóa xuất mới'),read:a('P20 lịch sử / P23 quá trình\nUNKNOWN cũ vẫn được đối chiếu')
},[['context','qty'],['qty','s1','Validation không đạt'],['s1','fix'],['fix','qty','Sửa và kiểm lại'],['context','scan'],['scan','s2'],['s2','retry'],['retry','scan','Mã mới cần kiểm nguồn'],['context','record'],['record','s3'],['s3','links'],['context','closed'],['closed','s4'],['s4','read']] ),G({
 owner:a('Không có owner ghi mới cho P24\nDùng lại model/service hiện có'),stock:s('Tồn linh kiện đã xác minh\nQuantity của dòng đang sửa'),s1:p('P24.S01','P19 validation\nSai thì giữ nguyên lines/version'),code:s('Nguồn trạng thái BOX\nMã chưa nhập / Không được xuất'),s2:p('P24.S02','P19 rejection\nRaw + Reason, không tăng quantity'),receipt:s('Receipt P04/P05 đã record\nRequest ID / Document ID khớp'),s3:p('P24.S03','waiting-web projection\nRecord ≠ Post · Inventory delta 0'),caseState:s('Case status P09 dùng chung\nĐã trả khách / Closed'),s4:p('P24.S04','P20 read-only + liên kết P23\nKhông Post mới sau khi đóng'),pending:s('Request Post UNKNOWN đã tồn tại\nĐối chiếu cùng ID vẫn được phép'),motion:a('Thông báo chuyển động là trình bày\nGuard/validation có hiệu lực ngay\nKhông dùng animation callback để ghi')
},[['owner','stock','P19'],['stock','s1'],['owner','code','P19'],['code','s2'],['owner','receipt','P04/P05'],['receipt','s3'],['owner','caseState','P09/P20'],['caseState','s4'],['pending','s4','Cho check, không cho Post mới'],['motion','owner','Chỉ trình bày, guard có hiệu lực ngay']]));

module.exports={boards,G,p,a,w,s,x,B};
