// Source-reviewed state map. These are UI hashes and owner states, not APIs.
const owners={
 P01:['auth-session/app.mjs',['#login','#confirmation']],
 P02:['home/home.mjs',['#home']],
 P03:['scanner-dialogs/dialog-flow.mjs',['caller hash; panel=P03.S01','caller hash; panel=P03.S02','caller hash; panel=P03.S03','caller hash; panel=P03.S04']],
 P04:['inbound/inbound.mjs',[1,2,3,4].map(n=>'#p02/inbound; flow.step='+n)],
 P05:['outbound/outbound.mjs',[1,2,3,4].map(n=>'#p02/outbound; flow.step='+n)],
 P06:['lookup/lookup.mjs',[1,2,3,4].map(n=>'#p02/lookup; flow.panel='+n)],
 P07:['nfc/nfc.mjs',[1,2,3,4].map(n=>'#p02/nfc?panel='+n)],
 P08:['history/history.mjs',['#p02/history-list?panel=1','#p02/history-list?panel=2&record=<recordId>','#p02/history-list?panel=3&session=<B08-sessionId>','#p02/history-list?panel=4']],
 P09:['warranty/warranty.mjs',['#p02/warranty?panel=1','#p02/warranty?panel=2','#p02/warranty?panel=3&case=<caseId>','#p02/warranty?panel=4&case=<confirmed-caseId>']],
 P10:['profile/profile.mjs',[1,2,3,4].map(n=>'#p02/profile?panel='+n)],
 P11:['security/security.mjs',[1,2,3,4].map(n=>'#p02/security?panel='+n)],
 P12:['documents/documents.mjs',['#p02/documents?panel=1','#p02/documents?panel=2&doc=<documentId>','#p02/documents?panel=3&doc=<documentId>','#p02/documents?panel=4']],
 P13:['notifications/notifications.mjs',[1,2,3,4].map(n=>'#p02/notifications?panel='+n+'; selected notification/document IDs in owner')],
 P14:['recovery-shift/view.mjs',['#recovery; recovery form','#recovery; verified recovery receipt','#p02/shift; pending records','#p02/shift; summary']],
 P15:['system/view.mjs',['caller hash; system kind=connection','caller hash; system kind=expired','caller hash; system kind=forbidden','caller hash; system kind=device']],
 P16:['data-states/view.mjs',['#p02/documents; loading','#p02/documents; empty','#p02/documents; filtered no-results','#p02/documents; read-error']],
 P17:['scan-exceptions/view.mjs',['#p02/inbound; invalid scan exception','#p02/outbound; blocked scan exception','#p02/nfc; linked-tag conflict','#p02/inbound or #p02/outbound; UNKNOWN record']],
 P18:['attachments/view.mjs',['#p02/attachments?panel=1&doc=<documentId>','#p02/attachments?panel=2&doc=<documentId>&file=<fileId>','#p02/attachments?panel=3&case=<caseId>','#p02/attachments?panel=4&item=<itemId>']],
 P19:['warranty-components/issue-view.mjs',['#p02/component-issue?case=<caseId>&doc=<documentId>&panel=1','same caller hash; quantity sheet','#p02/component-issue?case=<caseId>&doc=<documentId>&panel=3','#p02/component-issue?case=<caseId>&doc=<documentId>&panel=4; verified receipt required']],
 P20:['warranty-components/history-view.mjs',['#p02/component-history?case=<caseId>; ready','same hash; history-loading','same hash; history-error','same hash; verified empty']],
 P21:['warranty-components/resume-view.mjs',['#p02/component-resume?panel=1','#p02/component-resume?panel=2&doc=<documentId>','#p02/component-resume?panel=3&doc=<documentId>','#p02/component-resume?panel=4&doc=<documentId>']],
 P22:['history/nfc-audit-view.mjs',['#p02/history; iframe history-hub','#p02/history?scene=nfc','#p02/history?scene=nfc-detail&event=<eventId>','#p02/history?scene=events-unavailable']],
 P23:['history/warranty-session-view.mjs',['#p02/history?scene=warranty','#p02/history?scene=warranty-detail&case=<caseId>','#p02/history?scene=sessions','#p02/history?scene=session-detail&session=<sessionId>']],
 P24:['shared/waiting-web.mjs',['P19 quantity sheet; quantity-invalid','P19 scan; scan-error','P04/P05 recorded result; waiting-web','P20 closed case; read-only']]
};
// Per-panel entry edges: from-state, real control/event, response/cancel contract.
const entries={
 P01:[['unauthenticated','load / logout / login CTA','Credential form; no Home data'],['P01.S01','submit credentials','Fixture auth success; validation/failure stays form']],
 P02:[['P01.S02','start','Confirmed start receipt; denied/UNKNOWN cannot enter']],
 P03:[['caller','openPicker / scan tab','Operation not selected; Escape/cancel restores caller'],['caller with live stock draft','openUnfinished / openPicker','Exact owner projection; resumeExisting preserves document/session/version/rows; legacy review fixture stays isolated'],['write caller','writeGuard / showStopped','No write; close does not clear warehouse guard'],['P03.S02','requestDiscard','Cancel retains draft; confirm only discards authorized unsaved data']],
 P04:[['P02/P03/P12','inbound route / create','New owner or exact pending owner; no record'],['P04.S01','data-p04=next','Metadata validated; scan/manual share owner'],['P04.S02','data-p04=next','Review accepted codes; Back preserves draft'],['P04.S03/P17.S04','data-p04=send / check','Only verified record -> waiting Web; no Post/inventory delta']],
 P05:[['P02/P03/P12','outbound route / create','Address/source validation; changing source requires confirm'],['P05.S01','data-p05=next','Preserve document identity and planned quantities'],['P05.S02','data-p05=next','Missing quantity review; exceptions never counted as accepted'],['P05.S03/P17.S04','data-p05=send / check','Verified record -> waiting Web; UNKNOWN forbids duplicate send']],
 P06:[['P02/P03/P07/P09','lookup / onChooseProduct / onLookup','Scoped catalogue and current item source'],['P06.S01','data-p06-item','Exact item ID; invalid has no first-item fallback'],['P06.S02','data-p06=stock','Same item and warehouse; unknown quantities stay unknown'],['P06.S02','data-p06=history','Same item and filter source; unavailable document links remain guarded']],
 P07:[['P02','nfc route','No automatic hardware prompt or mutation'],['P07.S01','data-p07=begin','Read/select flow; cancel keeps owner'],['P07.S02','prepare link in NFC owner','Verified tag and product; conflict -> P17.S03'],['P07.S03','confirm link','Confirmed receipt only; late results cannot cross tag/context']],
 P08:[['P22/P04/P05/P14','history-general / onHistory','Scoped shared receipt projection plus preserved B08 seed'],['P08.S01','data-p08-record','Exact history ID; missing/invalid -> not found'],['P08.S02','data-p08=session','Explicit B08 session reference; no B23 substitution'],['P22/P08','history-daily / data-p08=day','Same record source/filter; unique activityId aggregate']],
 P09:[['P02/P12','warranty route','Shared warranty cases; list filters retained'],['P09.S01/P06','data-p09=begin / onWarranty','Serial identity checked; existing case not duplicated'],['P09.S01/P19/P20','data-p09-case / onCase','Exact shared case; closed remains read-only'],['P09.S03','confirmed update','Per-case confirmed result only; UNKNOWN requires reconciliation']],
 P10:[['P02','avatar / profile tab','Identity from verified session/profile source'],['P10.S01','edit / edit-name / edit-avatar','Dirty form; cancel confirmation retains or discards explicitly'],['P10.S01','rights','Read-only warehouse/permissions'],['P10.S01','security','Links use current account; unavailable capabilities disabled']],
 P11:[['P10.S04','password','Shared account source; no passwords persisted in report'],['P11.S01','invalid verification response','Inline validation; no password update'],['P11.S01','confirmed password change','Verified result only; post-action dialog has no fake cancel'],['P10.S04','sessions','Session source; revoke guard/caller preserved']],
 P12:[['P02/P22','documents / View all recent','Current shared document source; Home recent uses same IDs'],['P12.S01/P08/P13/P04/P05','data-p12-doc / onDocument','Exact document; missing ID not substituted'],['P12.S02','products tab','Same document lines and totals'],['P12.S01','create','Create/resume delegates to P04/P05/P09, not separate mutations']],
 P13:[['P02','Home bell','Shared notification store and unread badge'],['P13.S01','notification row','Exact event/document reference; mark-read scope guarded'],['P13 list tabs','waiting document tab','MIGRATED read-only Web-pending list, not approve'],['P13.S03','waiting document row','MIGRATED read-only detail -> P12; no App Post']],
 P14:[['P01.S01','forgot password','Recovery form; Back restores username, clears password'],['P14.S01','confirmed recovery request','Receipt only on verified source; no notification sent in fixture'],['P10.S01','shift','Read same stock/component draft owners; UNKNOWN blocks unsafe finish'],['P14.S03','confirmed shift completion','Summary verified records; local retention not durable storage']],
 P15:[['read/write caller','onSystem(connection)','Retry only allowed caller action; Back retains context'],['authenticated caller','session expiry','Reauthentication; stale callbacks cannot revive session'],['protected caller','permission guard','Forbidden state; disabled CSS is not authorization'],['scanner/NFC caller','device permission result','Denied/unsupported separated; guide Back restores caller']],
 P16:[['P12.S01','list read start','Pending read; stale response generation guarded'],['P12.S01','verified unfiltered empty response','Not missing-data-as-zero; create delegates owner'],['P12.S01','query/filter returns zero','Clear one condition or edit query; retain other filters'],['P12.S01','read failure','Retry same context; cached data labelled stale']],
 P17:[['P04.S02','invalid manual/camera code','Accepted list unchanged; Back repairs input'],['P05.S02','non-exportable code','No accepted increment; Back same document'],['P07.S02','tag already linked','No relink without verified conflict policy'],['P04/P05 submit','UNKNOWN / timeout-recorded','Same request check only, no retry mutation']],
 P18:[['P12/P08','onAttachments(documentId)','Exact owner document/files; unmapped source unavailable'],['P18.S01','data-p18=view','Local PDF/page source; Back restores file/scroll/focus'],['P09','data-p09=handoff','Shared case; unconfigured backend cannot close case'],['P06.S03','data-p06=location','Same item; no fake capacity/stock from grid']],
 P19:[['P09/P21','issue / scan','Shared per-case owner; closed/stopped/permission guards'],['P19.S01','BOX code','Quantity bounded by verified available stock; cancel does not add line'],['P19.S01/P21','review','Same lines/document/version; empty or unknown blocked'],['P19.S03/P21.S04','post / reconcile','Only confirmed POSTED receipt; duplicate commit guarded']],
 P20:[['P09/P21/P23','component-history / posted / linked receipt','Same case+POSTED receipt source; caller focus preserved'],['P20.S01','data-p20=load','Read only; keep cache/cursor; single flight'],['P20.S02','read error/timeout','No lost cursor; retry read, not Post'],['case history read','verified empty','No invented zero for unavailable history']],
 P21:[['P19 Back/P21 Back','resume list','Live owners only; B21 sample explicit opt-in'],['P09/P19/P21.S01','open exact document','Read checkpoint; same document/session/version before scan'],['checkpoint read','conflict/unverified state','Read-only reconciliation; no auto replace/create'],['UNKNOWN component Post','open / check','Same request can reconcile even if case closes']],
 P22:[['P02','History footer','Six existing hub entries; no removed draft shortcut'],['P22.S01','nfc','Event-only source; unavailable by default'],['P22.S02','event row','Exact immutable event ID; no inference from P07 current tag'],['P22 event source','unavailable response','Not empty-success; retry read only']],
 P23:[['P22 hub','warranty','Shared P09 case source'],['P23.S01/P20 closed','case row / timeline','Same case chronology; missing ID not first row'],['P22 hub/P08','sessions','Independent explicit session source; default unavailable'],['P23.S03','session row','Exact scoped session; ENDED is not POSTED']],
 P24:[['P19 quantity sheet','invalid/excess quantity','Inline error; no quantity commit'],['P19 scan','box not exportable','Accepted list/document unchanged; retry requires valid source'],['P04/P05 verified record','waiting result','Web pending, never Post; links actual receipt ID'],['P09/P20/P23','closed case','Read-only; existing UNKNOWN may be checked, no new Post']]
};
const guards={
 default:'Verified auth session + previewReady + warehouseOperations; payload must match scoped owner. Writes also require active warehouse; async epoch/context checked.',
 P01:'Auth credential epoch; start receipt verified; warehouse and permissions confirmed; UNKNOWN must check before retry.',
 P14:'Recovery mode anonymous; shift mode authenticated. UNKNOWN and unretained draft prevent unsafe logout.',
 P16:'P12 query generation, same session/warehouse/cache key; missing source is not empty success.',
 P22:'Event source scope/complete/confirmed required; read-only; no audit synthesis from tag state.',
 P23:'Same case/session/warehouse; receipt explicit and POSTED; closed cases read-only.'
};
const backs={
 default:'Owner remembers caller/context; route/dialog lifecycle consumes Back before restoring focus. See scoped evidence; no promise of persistence across reload.',
 P08:'history.state.p08 + views/context map retain filters/tab/scroll/action focus; p08Back returns caller; P18 caller remembers scroll/focus.',
 P04:'Owner retains draft in page memory; waiting result return keyed by exact documentId; Back/Forward cannot resend.',
 P05:'Owner retains draft in page memory; waiting result return keyed by exact documentId; Back/Forward cannot resend.',
 P19:'Scan Back -> P21 same owner; review Back -> scan; UNKNOWN stays locked; no discard by navigation.',
 P20:'Remember case/list/cursor/scroll/focus; late reads ignored after leave; p20From returns verified caller.',
 P21:'Detail Back -> drafts; drafts Back -> Home; verified checkpoint required before continuing scan.'
};
// Explicit cross-owner edges with focused browser evidence from the current gate.
const focused=[
 ['F01','P01.S01','submit, then start','session/warehouse/permission receipt','#home','sessionId,actorId,warehouseId','J01'],
 ['F02','P03.S01','inbound','active warehouse; no selected draft','#p02/inbound','operation=inbound,actorId,warehouseId','J01'],
 ['F03','P03.S01','outbound','active warehouse; no selected draft','#p02/outbound','operation=outbound,actorId,warehouseId','J01'],
 ['F04','P03.S01','lookup','verified session','#p02/lookup','operation=lookup','J01'],
 ['F05','P03.S01','warranty','verified session','#p02/warranty','operation=warranty','J01'],
 ['F06','P04.S04','history','verified recorded receipt','#p02/history-list?panel=1','documentId,receipt:<documentId>','J02'],
 ['F07','P08.S02 receipt','document','exact sourceDocumentId','#p02/documents?panel=2&doc=<id>','documentId,historyId','J02'],
 ['F08','P12.S02 from receipt','back','p12From','#p02/history-list?panel=2&record=<id>','same historyId','J02'],
 ['F09','P08 list from result','back / browser Forward / Back','p08Back + p12DocumentReturn','#p02/inbound; step=4','same documentId; recordCalls unchanged','J02'],
 ['F10','P08.S02 LS-0001','document','unique explicit historyRecordId mapping','#p02/documents?panel=2&doc=fixture-inbound-0005','LS-0001,fixture-inbound-0005','J03'],
 ['F11','P08.S02 attachments','attachments','current document has real attachment IDs','#p02/attachments?panel=1&doc=fixture-inbound-0005','documentId,fileId','J03'],
 ['F12','P18.S01','view','exact owner file and URL','#p02/attachments?panel=2&doc=<id>&file=<id>','b12-attachment-1; local PDF','J03'],
 ['F13','P18 viewer/list','back twice','p18From + caller cache','P08 attachments tab','filter,tab,scroll,focus','J03'],
 ['F14','P08.S02 LS-0001','session','explicit B08 reference','#p02/history-list?panel=3&session=PQ-0001','B08 19 scans; not B23 PQ-0001','J04'],
 ['F15','P08 deep link','missing/invalid record or session','no fallback ID','not-found state','4 missing/invalid payload cases','J04'],
 ['F16','P22 hub','nfc / sessions','default unavailable sources','#p02/history?scene=nfc or sessions','no fabricated event/session','J04'],
 ['F17','P12 detail','refresh','auth only in page memory','#login','old protected DOM removed','J05'],
 ['F18','P12','logout then Back','invalidated session','#login','no old document DOM','J05'],
 ['F19','P04.S03','double send -> timeout-recorded','busy + UNKNOWN write lock','P17.S04','same request/document; recordCalls=1','J06'],
 ['F20','P17.S04 inbound','check','same request status source','P04.S04 / P24.S03','same request; no new record; inventoryDelta=0','J06'],
 ['F21','P09.S03 BH-001','issue','open case + active warehouse','#p02/component-issue?case=BH-001&doc=<id>&panel=1','caseId,documentId,scanSessionId,version','J07'],
 ['F22','P19.S03','double post','single-flight; verified stock and case','P19.S04','receiptId,requestId; commits=1','J07'],
 ['F23','P19.S04','case','receipt confirmed by owner','#p02/warranty?panel=3&tab=parts&case=BH-001','same receiptId + focus marker','J07'],
 ['F24','P09 parts','component-history','same case POSTED source','#p02/component-history?case=BH-001','same receiptId','J07'],
 ['F25','P03.S02 legacy review sample','resume','must not impersonate P04/P05 owner','guarded dependency dialog','PN-0001,fixture-p03-scan-*,version,codes retained; not the runtime owner source','J08'],
 ['F26','P09 closed BH-002','component-history','read allowed; write forbidden','#p02/component-history?case=BH-002','caseId; issue disabled','J09'],
 ['F27','P20 closed','timeline then Back','verified caller case','#p02/history?scene=warranty-detail&case=BH-002','caseId + caller return','J09'],
 ['F28','P05.S04','history -> document -> Back','verified record only','P08 -> P12 -> same P05 result','documentId,receipt ID; no Post','J10'],
 ['F29','P05.S03','timeout-recorded then check','UNKNOWN blocks send','P17.S04 -> P05.S04','same request; recordCalls unchanged; inventoryDelta=0','J10'],
 ['F30','P19.S01','back','live current owner','#p02/component-resume?panel=2&doc=<id>','same document/session/version/lines','J11'],
 ['F31','P21.S02','scan','checkpoint verified; writeGuard clear','#p02/component-issue?case=<case>&doc=<id>&panel=1','same document/session/version/lines; commits=0','J11'],
 ['F32','P03.S02 live stock owner','resume','exact scoped owner fingerprint','#p02/inbound or outbound','same document/session/version/rows; recordCalls=0','J12'],
 ['F33','P03.S02 live stock owner','save then Home resume','same owner; page-memory only','Home then same stock owner','no WMS record, no second owner','J12'],
 ['F34','P03.S04 live stock owner','cancel / confirm discard','unsaved local exact fingerprint; no request/UNKNOWN','caller Home','cancel keeps data; confirm clears only selected owner','J12'],
 ['F35','P14.S03','continue','single current stock owner row','#p02/inbound or outbound','same document/session/rows; no P03 projection duplicate','J12']
];
module.exports={owners,entries,guards,backs,focused};
