const fs=require('node:fs');
function edit(file,a,b){const s=fs.readFileSync(file,'utf8');if(!s.includes(a))throw Error(file+' missing '+a.slice(0,100));fs.writeFileSync(file,s.replace(a,b));}
const v='docs/flows/warranty-components/issue-view.mjs';
edit(v,"import {ISSUE_ICONS}","import {quantityControls,pendingIssueForCase} from './issue-experience.mjs';\nimport {ISSUE_ICONS}");
edit(v,'entries=new Map();','entries=new Map(),expandedRequests=new Set();');
edit(v,'<strong>× ${r.quantity}</strong></div></div>',`\${!compact&&r.kind==='BOX'&&!r.recorded?btn('edit-quantity','× '+r.quantity+' <span>Sửa</span>','p19-edit-quantity',\`data-code="\${esc(r.code)}" aria-label="Sửa số lượng \${esc(r.sku)}, hiện tại \${r.quantity}" \${locked()?'disabled':''}\`):\`<strong>× \${r.quantity}</strong>\`}</div></div>`);
const summaryStart='<section class="p19-card p19-scan-summary"><div><strong>${s.counts.codes}</strong><span> mã đã quét</span><small>${s.counts.quantity} linh kiện</small></div>${s.lines.length?part(s.lines.at(-1),true):\'<p>Chưa có mã trong danh sách.</p>\'}</section>';
edit(v,summaryStart,'${scanSummary(s)}');
edit(v,' function scan(s){',` function scanSummary(s){return \`<section class="p19-card p19-scan-summary"><div><strong>\${s.counts.codes}</strong><span> mã đã quét</span><small>\${s.counts.quantity} linh kiện</small></div>\${manual&&s.lines.length?'<p class="p19-recent-label">Mã vừa nhận · mới nhất trước</p>':''}\${s.lines.length?(manual?[...s.lines].reverse():[s.lines.at(-1)]).map(r=>part(r,true)).join(''):'<p>Chưa có mã trong danh sách.</p>'}</section>\`;}
 function syncAccepted(){const s=current(),input=root.querySelector('[data-scan-code]');code='';if(input)input.value='';const t=document.createElement('template');t.innerHTML=scanSummary(s);root.querySelector('.p19-scan-summary')?.replaceWith(t.content.firstElementChild);const review=root.querySelector('[data-p19=review]');if(review)review.disabled=!s.lines.length||locked();syncTools();if(manual)input?.focus({preventScroll:true});}
 function scan(s){`);
const oldPending='${s.unknown?`<section class="p19-card p19-pending"><h2>Chưa xác định kết quả xuất</h2><p>Giữ nguyên phiếu, mã và số lượng. Đối chiếu kết quả trước khi gửi lại.</p><dl>${kv(\'Phiếu đang làm\',s.document.documentId)}${kv(\'Yêu cầu\',s.request?.id)}${kv(\'Phiên quét\',s.scanSessionId)}${kv(\'Version\',s.request?.version)}</dl></section>`:hint(\'Xác nhận để xuất linh kiện ngay cho hồ sơ này.\')}';
edit(v,oldPending,"${s.unknown?'':hint('Xác nhận để xuất linh kiện ngay cho hồ sơ này.')}");
edit(v,'function reviewBody(s){return `${context()}','function reviewBody(s){return `${context()}${s.unknown?pendingBody(s):\'\'}');
edit(v,' function reviewBody(s){',` function pendingBody(s){return \`<section class="p19-card p19-pending"><h2>Chưa xác định đã xuất hay chưa</h2><p>Giữ nguyên phiếu, mã và số lượng. Chọn <strong>Đối chiếu kết quả xuất</strong> bên dưới trước khi gửi lại.</p><details data-p19-request \${expandedRequests.has(s.document.documentId)?'open':''}><summary>Chi tiết đối chiếu</summary><dl>\${kv('Phiếu đang làm',s.document.documentId)}\${kv('Yêu cầu',s.request?.id)}\${kv('Phiên quét',s.scanSessionId)}\${kv('Version',s.request?.version)}</dl></details></section>\`;}
 function reviewBody(s){`);
edit(v,"function quantity(){if(modal||!current()?.pending)return;const pending=current().pending;", "function quantity(){if(modal||!current()?.pending)return;const owner=flow,originPanel=panel,originManual=manual,pending=current().pending,trigger=document.activeElement;");
edit(v,"const validate=()=>{const e=quantityError(field.value,pending.available);", "const syncBounds=()=>{const bounds=quantityControls(field.value,pending.available);for(const a of ['minus','plus'])d.querySelector(`[data-p19=${a}]`).disabled=bounds[a];};\n  const validate=()=>{syncBounds();const e=quantityError(field.value,pending.available);");
edit(v,"d.addEventListener('input',validate);", "field.addEventListener('focus',()=>field.select());field.addEventListener('click',()=>field.select());\n  d.addEventListener('input',validate);");
edit(v,"if(a==='minus'||a==='plus'){const n=", "if((a==='minus'||a==='plus')&&!e.target.closest('button').disabled){const n=");
edit(v,"const result=flow.quantity(field.value);", "const result=owner.quantity(field.value);");
edit(v,"modal.close();void route.ready().then(()=>{if(active){manual=false;code='';render();root.querySelector('[data-p19=review]')?.focus({preventScroll:true});}});", "modal.close();if(originPanel===1)syncAccepted();void route.ready().then(()=>{if(!active||flow!==owner)return;if(originPanel===3){render();root.querySelector(`[data-p19=edit-quantity][data-code=\"${CSS.escape(pending.code)}\"]`)?.focus({preventScroll:true});}else if(originManual){root.querySelector('[data-scan-code]')?.focus({preventScroll:true});}else root.querySelector('[data-p19=review]')?.focus({preventScroll:true});});");
edit(v,"flow?.cancelQuantity();route.closed();root.querySelector('.p19-app')?.setAttribute('data-panel','P19.S01');", "owner.cancelQuantity();route.closed();if(active&&flow===owner){root.querySelector('.p19-app')?.setAttribute('data-panel','P19.S0'+originPanel);if(trigger?.isConnected)trigger.focus({preventScroll:true});}");
edit(v,"root.querySelector('.p19-app').dataset.panel='P19.S02';syncTools();", "syncBounds();field.select();root.querySelector('.p19-app').dataset.panel='P19.S02';syncTools();");
edit(v,"if(result.kind==='accepted'){code='';render();if(manual)root.querySelector('[data-scan-code]')?.focus();return;}","if(result.kind==='accepted'){syncAccepted();return;}");
edit(v,"if(a==='case'){onCase(caseId);return;}","if(a==='case'){onCase(caseId,demo?null:current()?.receipt?.id);return;}");
edit(v,"  if(a==='post')run('post');",`  if(a==='edit-quantity'&&!locked()){const row=current().lines.find(r=>r.code===el.dataset.code);if(row?.kind==='BOX'&&!row.recorded){remember();const result=flow.scan(row.code);if(result.kind==='quantity')quantity();else info('Chưa thể sửa số lượng',result.error);}return;}
  if(a==='post')run('post');`);
edit(v,"const nav=e=>{", "const onToggle=e=>{if(active&&e.target.matches('[data-p19-request]')){const id=current()?.document.documentId;if(e.target.open)expandedRequests.add(id);else expandedRequests.delete(id);}};root.addEventListener('toggle',onToggle,true);\n const nav=e=>{");
edit(v,"  posted:()=>", "  pendingForCase:id=>pendingIssueForCase([...flows.values()].map(f=>f.snapshot()),id,getState()),\n  posted:()=>");
edit(v,"review.remove();root.removeEventListener('compositionstart'", "review.remove();root.removeEventListener('toggle',onToggle,true);root.removeEventListener('compositionstart'");
const h='docs/flows/home/home.mjs';
edit(h,"onNavigate:openIssue,onCase:caseId=>{history.pushState({p09:true,p09From:'#home'},'','#p02/warranty?panel=3&tab=parts&case='+encodeURIComponent(caseId))", "onNavigate:openIssue,onCase:(caseId,receiptId)=>{const confirmed=componentIssue.posted().some(r=>r.caseId===caseId&&r.id===receiptId&&r.status==='POSTED');history.pushState({p09:true,p09From:'#home',...(confirmed?{p19ReceiptFocus:{caseId,receiptId}}:{})},'','#p02/warranty?panel=3&tab=parts&case='+encodeURIComponent(caseId))");
edit(h,"getIssuedDocuments:()=>componentIssue.posted(),onIssue:caseId=>openIssue({case:caseId,panel:1}),", "getPendingIssue:caseId=>componentIssue.pendingForCase(caseId),getIssuedDocuments:()=>componentIssue.posted(),onIssue:(caseId,documentId)=>{if(documentId){const pending=componentIssue.pendingForCase(caseId);if(!pending||pending.document.documentId!==documentId)return;openIssue({case:caseId,doc:documentId,panel:pending.unknown||pending.busy?3:1});}else openIssue({case:caseId,panel:1});},");
const w='docs/flows/warranty/warranty.mjs';
edit(w,'onIssue,getIssuedDocuments=()=>[]})','onIssue,getPendingIssue=()=>null,getIssuedDocuments=()=>[]})');
edit(w,'<article class="p09-document"><header>', '<article class="p09-document" tabindex="-1" data-issued-document="${esc(d.id)}"><header>');
edit(w," function detail(){",` function issueActions(c){const pending=getPendingIssue(c.id);return \`<section class="p09-component-actions"><h2>Tác vụ linh kiện</h2><div>\${pending?button('resume-issue',pending.unknown?'Đối chiếu kết quả xuất':pending.busy?'Đang xác nhận xuất…':'Tiếp tục phiếu · '+pending.counts.codes+' mã / '+pending.counts.quantity+' linh kiện','p09-secondary p09-resume-issue',pending.busy||(!pending.unknown&&c.closed)):button('drafts','Phiếu dở / Tiếp tục','p09-secondary',true)}\${pending?'':button('issue','Xuất linh kiện','p09-secondary',c.closed||!onIssue)}</div><p id="p09-component-availability">\${pending?pending.unknown?'Kết quả chưa rõ. Tiếp tục đối chiếu đúng yêu cầu, không tạo phiếu mới.':'Phiếu đang làm được giữ trong phiên hiện tại.':c.closed?'Hồ sơ đã trả khách, không thể xuất thêm linh kiện.':onIssue?'Xuất linh kiện trực tiếp; phiếu dở được giữ trong phiên đang làm.':'Xuất và tiếp tục phiếu linh kiện chưa khả dụng.'}</p></section>\`;}
 function focusIssuedReceipt(){const target=history.state?.p19ReceiptFocus;if(!target)return;const next={...history.state};delete next.p19ReceiptFocus;history.replaceState(next,'',location.hash);if(panel!==3||tab!=='parts'||target.caseId!==caseId||!postedDocuments(caseId).some(r=>r.id===target.receiptId))return;const row=root.querySelector(\`[data-issued-document="\${CSS.escape(target.receiptId)}"]\`),scroll=root.querySelector('.p09-scroll');if(!row||!scroll)return;row.classList.add('p09-issued-highlight');row.focus({preventScroll:true});const scrollToRow=()=>{if(!active||!row.isConnected||screen.querySelector('.app-modal-host'))return;const scale=scroll.getBoundingClientRect().height/scroll.offsetHeight;scroll.scrollTop+=(row.getBoundingClientRect().top-scroll.getBoundingClientRect().top)/scale-16;positions.set(panel+':'+caseId+':'+tab,scroll.scrollTop);};scrollToRow();requestAnimationFrame(scrollToRow);}
 function detail(){`);
const old='<section class="p09-component-actions"><h2>Tác vụ linh kiện</h2><div>${button(\'drafts\',\'Phiếu dở / Tiếp tục\',\'p09-secondary\',true)}${button(\'issue\',\'Xuất linh kiện\',\'p09-secondary\',c.closed||!onIssue)}</div><p id="p09-component-availability">${c.closed?\'Hồ sơ đã trả khách, không thể xuất thêm linh kiện.\':onIssue?\'Xuất linh kiện trực tiếp; phiếu dở được giữ trong phiên đang làm.\':\'Xuất và tiếp tục phiếu linh kiện chưa khả dụng.\'}</p></section>';
edit(w,old,"${getPendingIssue(c.id)?'':issueActions(c)}");
edit(w,"else if(tab==='parts')content=`<div", "else if(tab==='parts')content=`${getPendingIssue(c.id)?issueActions(c):''}<div");
edit(w," if(a==='issue'||a==='drafts'){", " if(a==='resume-issue'){const pending=getPendingIssue(caseId);if(!pending||pending.busy||sessionGuard(getState())||!onIssue)return;const err=pending.unknown?'':guardWarranty(getState(),caseId);if(err){notify(err);return;}remember();onIssue(caseId,pending.document.documentId);return;}\n if(a==='issue'||a==='drafts'){");
edit(w,"renderedHash=location.hash;render(true);if(message)","renderedHash=location.hash;render(true);focusIssuedReceipt();if(message)");
console.log('P19 six UX enhancements applied.');
