const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path');
const stage=process.env.P09_AUDIT_STAGE||'before',out=path.resolve('handoff/P09/evidence/revision-11/'+stage);fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),observations=[];let p=await b.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});const act=a=>p.locator(`[data-p09="${a}"]`).first();
const snap=async()=>JSON.parse(await p.locator('[data-p09-snapshot]').textContent());
async function shot(n){await p.locator('.hn-screen').screenshot({path:path.join(out,n+'.png')});}
async function login(){if(p.url()!=='about:blank'){await p.close();p=await b.newPage({viewport:{width:494,height:1000},deviceScaleFactor:1});}await p.goto('http://127.0.0.1:8766/flows/auth-session/');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('#hn-home:visible').waitFor();await p.click('[data-route=warranty]');}
try{await login();await act('begin').click();await p.click('[data-scan-action=manual]');await p.fill('#p09-code','SN-XP420B-BK-0008');await p.locator('#p09-code').press('Enter');await act('fault').click();await p.click('.p09-fault-picker input[value=usb]');
await act('fault').click();await p.fill('.p09-fault-picker input[type=search]','khong-co-loi-nay');await shot('fault-no-match');await p.locator('.p09-fault-picker input[type=search]').press('Enter');observations.push({name:'Enter in unmatched fault search must not commit hidden selection',pickerOpen:await p.locator('.p09-fault-picker').count()});if(await p.locator('.p09-fault-picker').count())await p.keyboard.press('Escape');
await act('change-product').click();await p.fill('#p09-code','SN-XP420B-BK-0008');await p.locator('#p09-code').press('Enter');observations.push({name:'Checking the same serial should complete replacement',blocked:await act('intake').isDisabled(),manualStillVisible:await p.locator('#p09-code').count()});await shot('same-serial');if(await act('cancel-change').count())await act('cancel-change').click();
await act('change-product').click();await p.fill('#p09-code','bad-id');await p.locator('#p09-code').press('Enter');await p.locator('#p09-code').press('Escape');observations.push({name:'Escape from replacement should restore selected product',blocked:await act('intake').isDisabled(),manual:await p.locator('#p09-code').count(),hint:await p.locator('.p09-footer-hint').textContent()});await shot('escape-change');
await login();await act('begin').click();await p.click('[data-scan-action=manual]');await p.fill('#p09-code','HN12345');await p.locator('#p09-code').press('Enter');observations.push({name:'Known open case can be viewed without inventing a new fault',blocked:await act('intake').isDisabled(),directView:await act('existing-case').count(),hint:await p.locator('.p09-footer-hint').textContent()});await shot('existing-case');
await login();await p.fill('#p09-query','BH-007');await p.click('[data-p09-case=BH-007]');await act('update').click();await p.fill('.p09-update-dialog [name=result]','   ');observations.push({name:'Whitespace validation footer duplication',text:await p.locator('.p09-update-dialog').innerText()});await shot('update-error');await p.keyboard.press('Escape');
await p.evaluate(async()=>{const m=await import('/flows/shared/warranty-cases.mjs');const c=m.readWarrantyCases().find(c=>c.id==='BH-007');m.writeWarrantyCase({...c,model:'Máy '+('X'.repeat(250)+'\n').repeat(8),serial:'SN-'+('Y'.repeat(250)+'\n').repeat(8)});});await p.click('[data-p09-tab=parts]');await p.click('[data-p09-tab=info]');await act('update').click();
observations.push({name:'Long identity dialog must keep actions accessible',metrics:await p.locator('.p09-update-dialog').evaluate(d=>{const r=d.getBoundingClientRect(),f=d.querySelector('footer').getBoundingClientRect();return {dialogHeight:r.height,footerTop:f.top,footerBottom:f.bottom,dialogBottom:r.bottom,footerInside:f.bottom<=r.bottom+1,bodyHeight:d.querySelector('.app-modal-body').clientHeight,overflow:d.scrollWidth>d.clientWidth};})});await shot('long-identity-dialog');
fs.writeFileSync(path.join(out,'observations.json'),JSON.stringify(observations,null,2));console.log(JSON.stringify(observations,null,2));
}finally{await b.close();}})();
