const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const base='handoff/P24',e=base+'/evidence/revision-02',load=p=>JSON.parse(fs.readFileSync(p,'utf8'));
let groups=0;for(const p of ['after/after/results.json','after/edges/results.json','after/ux/results.json','after/regression/check_p19/results.json','after/regression/check_p20/results.json','after/regression/check_p21/after/browser-results.json','after/regression/check_p23/results.json']){const r=load(e+'/'+p);assert.ok(r.checks.every(x=>x.status==='PASS'),p);assert.deepEqual(r.errors||[],[],p);groups+=r.checks.length;}assert.equal(groups,50);
const main=load(e+'/after/after/results.json'),ux=load(e+'/after/ux/results.json');assert.equal(main.layout.length,25);assert.equal(ux.layouts.length,10);assert.ok(main.layout.every(x=>x.footer&&!x.overflow&&x.small.length===0));assert.ok(ux.layouts.every(x=>x.footer&&!x.overflow));
const logic=fs.readFileSync(e+'/logic.txt','utf8');assert.match(logic,/pass 170/);assert.match(logic,/fail 0/);
const rows=fs.readFileSync('SCREEN_COVERAGE.csv','utf8').trim().split(/\r?\n/).slice(1);assert.equal(rows.length,91);assert.equal(new Set(rows.map(r=>/^"(P\d+)"/.exec(r)[1])).size,24);assert.ok(rows.some(r=>r.startsWith('"P13"')&&r.includes('"MIGRATED"')));
assert.equal(load(base+'/RUN_STATE.json').revision,'P24-r02');assert.equal(load(base+'/RUN_STATE.json').visual,'AWAITING_USER_REVIEW');assert.equal(load('RUN_STATE.json').revision,'P24-r02');assert.equal(load('handoff/P23/RUN_STATE.json').visual,'USER_TEMPORARILY_ACCEPTED');
for(const f of load(base+'/SOURCE_MANIFEST_02.json').files){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.path)).digest('hex'),f.sha256,f.path);if(/\.m?js$/.test(f.path)){const r=spawnSync(process.execPath,['--check',f.path],{encoding:'utf8'});assert.equal(r.status,0,f.path+' '+r.stderr);}}
for(const file of ['REVIEW_02.html','REVISION_02.md','REVISION_02_CONTEXT.md']){const s=fs.readFileSync(base+'/'+file,'utf8');const urls=file.endsWith('.html')?[...s.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]):[...s.matchAll(/\]\(([^)]+)\)/g)].map(m=>m[1]);for(const u of urls)if(!/^(https?:|#)/.test(u))assert.ok(fs.existsSync(path.resolve(base,u)),file+' -> '+u);}
for(const name of ['S01','S02','S03-inbound','S03-outbound','S04'])for(const phase of ['before','after']){const png=fs.readFileSync(e+'/'+phase+'/after/'+name+'-494x950.png');assert.equal(png.readUInt32BE(16),494);assert.equal(png.readUInt32BE(20),950);}
const result={boards:24,panels:91,logic:170,browserGroups:groups,layout:35,footerViewports:4,syntax:'PASS',links:'PASS',sourceHashes:'PASS',visual:'AWAITING_USER_REVIEW',integration:'BLOCKED_PRODUCTION'};fs.writeFileSync(e+'/verification.json',JSON.stringify(result,null,2));console.log(result);
