const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict'),path=require('node:path'),{spawnSync}=require('node:child_process');
const base='handoff/motion/M23/',read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const changed=['docs/flows/history/warranty-session-motion.mjs','docs/flows/history/warranty-session-view.mjs','docs/flows/home/home.mjs'];
const unchanged=['docs/flows/history/warranty-session.css','docs/flows/history/warranty-session-model.mjs','docs/flows/history/warranty-session-experience.mjs','docs/flows/history/warranty-session-fixture.mjs','docs/flows/home/motion.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css','RUN_STATE.json','SCREEN_COVERAGE.csv','handoff/P23/RUN_STATE.json'];
const manifest={source_commit:spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),target:'prototype-local-ui-fixture',fixture:'Existing B23 opt-in three sessions, owner P09 cases; test-only append interception, shipped fixture/model unchanged',files:[]};let diff='';
for(const file of [...changed,...unchanged]){const bp=base+'before/source/'+file,b=fs.existsSync(bp)?fs.readFileSync(bp):null,a=fs.readFileSync(file);manifest.files.push({file,before:b?hash(b):null,after:hash(a),beforeBytes:b?.length||0,afterBytes:a.length,delta:a.length-(b?.length||0),unchanged:b?b.equals(a):false});if(unchanged.includes(file))assert.ok(b.equals(a),'preserve '+file);if(changed.includes(file))diff+=b?spawnSync('git',['diff','--no-index','--',bp,file],{encoding:'utf8'}).stdout:`--- /dev/null\n+++ b/${file}\n@@ -0,0 +1,${a.toString().split('\n').length} @@\n+${a.toString().split('\n').join('\n+')}\n`;}
manifest.sourceBytesDelta=manifest.files.filter(f=>changed.includes(f.file)).reduce((n,f)=>n+f.delta,0);manifest.scopedSourceHash=hash(JSON.stringify(manifest.files.filter(f=>changed.includes(f.file)).map(f=>[f.file,f.after])));fs.writeFileSync(base+'SOURCE_MANIFEST.json',JSON.stringify(manifest,null,2));fs.writeFileSync(base+'changes.patch',diff);
const before=read(base+'before/results.json'),after=read(base+'evidence/results.json'),flow=read(base+'flow-recheck/results.json');assert.equal(after.length,3);assert.deepEqual(after.map(r=>r.domain),after.map(()=>after[0].domain));const geometry=[];
for(const r of after){assert.deepEqual(r.errors,[]);assert.deepEqual(r.mutations,[]);assert.equal(r.checks.length,8);assert.equal(r.domain.writes,0);assert.equal(r.domain.reads,7);for(const [panel,g]of Object.entries(r.geometry)){const prev=before.find(x=>x.mode===r.mode);assert.deepEqual(g,prev.geometry[panel]);assert.equal(r.text[panel],prev.text[panel]);geometry.push({panel,mode:r.mode,equal:true,nodes:g.nodes});}assert.equal(r.append.nodeConnected,true);assert.equal(r.append.focused,true);assert.ok(Math.abs(r.append.before.offset-r.append.after.offset)<2);}
for(const r of flow){assert.equal(r.append.nodeConnected,true);assert.equal(r.append.focused,true);assert.ok(Math.abs(r.append.before.offset-r.append.after.offset)<2);}
let regressionGroups=0;for(const file of ['regression/after/results.json','regression/edges/results.json','ux/results.json','guards/results.json','regression/p22/after/results.json','regression/p20/after/results.json','regression/p09/navigation-results.json']){const r=read(base+'regression/'+file);assert.ok(r.checks.every(x=>x.status==='PASS'));assert.deepEqual(r.errors,[]);regressionGroups+=r.checks.length;}
const audit=read(base+'regression/after/audit.json');assert.equal(audit.length,14);assert.ok(audit.every(r=>r.status==='PASS'));regressionGroups+=audit.length;assert.equal(regressionGroups,67);
const shell=read(base+'regression/shell/results.json'),shellGroups=shell.reduce((n,r)=>n+r.checks.length,0);assert.equal(shellGroups,36);assert.match(fs.readFileSync(base+'regression/regression/logic.txt','utf8'),/pass 153/);assert.match(fs.readFileSync(base+'regression/regression/logic.txt','utf8'),/fail 0/);
const layoutCombinations=['regression/after/layout.json','regression/edges/layout-long.json','ux/layout.json','guards/layout.json'].reduce((n,p)=>n+read(base+'regression/'+p).length,0);assert.equal(layoutCombinations,50);const footer=read(base+'regression/regression/footer/results.json');assert.equal(footer.checks.length,4);assert.deepEqual(footer.errors,[]);assert.ok(footer.checks.every(c=>c.status==='PASS'));
const summary={status:'PASS_SCOPED_UI_FIXTURE',modes:after.map(r=>r.mode),motionGroups:24,regressionGroups,shellGroups,nodeTests:153,geometry,layoutCombinations,footerViewports:4,operations:after.map(r=>({mode:r.mode,...r.domain})),anchorBeforeAfter:after.map(r=>({mode:r.mode,before:before.find(b=>b.mode===r.mode).append,after:r.append})),sourceBytesDelta:manifest.sourceBytesDelta,scopedSourceHash:manifest.scopedSourceHash,performance:{longTasks:'Raw entries recorded; before/after workloads differ, no speed/FPS claim',inputLatency:'NOT_MEASURED separately',droppedFrames:'NOT_MEASURED on target hardware',virtualization:'DEFERRED per M00; native scrolling preserved, no library or paging API added'},visual:'USER_REVIEW_PENDING for motion; P23 r03 temporary acceptance preserved',integration:'BLOCKED_PRODUCTION / hardware NOT_RUN; business tracking unchanged'};fs.writeFileSync(base+'SUMMARY.json',JSON.stringify(summary,null,2));
if(fs.existsSync(base+'REVIEW.html'))for(const m of fs.readFileSync(base+'REVIEW.html','utf8').matchAll(/(?:src|href)="([^"]+)"/g))if(!/^https?:/.test(m[1]))assert.ok(fs.existsSync(path.resolve(base,m[1])),m[1]);
const state=read('handoff/motion/MOTION_RUN_STATE.json');if(state.current_prompt==='MOTION_P23'){assert.ok(!state.remaining_panel_ids.some(id=>id.startsWith('P23.')));const rows=fs.readFileSync('handoff/motion/MOTION_COVERAGE.csv','utf8').trim().split(/\r?\n/);assert.equal(rows.length-1,91);assert.equal(rows.filter(l=>l.startsWith('"MOTION_P23",')&&l.includes('"PASS","PASS","PASS","PASS"')).length,4);}
console.log(JSON.stringify({status:summary.status,motionGroups:24,regressionGroups,shellGroups,nodeTests:153,geometry:geometry.length,layoutCombinations,sourceBytesDelta:manifest.sourceBytesDelta,scopedSourceHash:manifest.scopedSourceHash},null,2));
