const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');const base='handoff/P24',ev=base+'/evidence/revision-03',load=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const before=load(ev+'/before/audit.json'),after=load(ev+'/after/audit.json');assert.equal(before.length,16);assert.equal(after.length,16);assert.equal(before.filter(r=>r.status==='FAIL').length,14);assert.ok(after.every(r=>r.status==='PASS'));assert.deepEqual(before.map(r=>r.id),after.map(r=>r.id));let groups=after.length;
for(const p of ['guards/results.json','regression/after/after/results.json','regression/after/edges/results.json','regression/after/ux/results.json','regression/after/regression/check_p19/results.json','regression/after/regression/check_p20/results.json','regression/after/regression/check_p21/after/browser-results.json','regression/after/regression/check_p23/results.json']){const d=load(ev+'/'+p);assert.ok(d.checks.every(r=>r.status==='PASS'),p);assert.deepEqual(d.errors||[],[],p);groups+=d.checks.length;}assert.equal(groups,70);
const layouts=load(ev+'/regression/after/after/results.json').layout,extra=load(ev+'/regression/after/ux/results.json').layouts;assert.equal(layouts.length+extra.length,35);assert.ok(layouts.every(x=>!x.overflow&&x.footer&&x.small.length===0));assert.ok(extra.every(x=>!x.overflow&&x.footer));assert.equal(load(ev+'/footer/results.json').checks.length,4);
const logic=fs.readFileSync(ev+'/logic.txt','utf8');assert.match(logic,/pass 173/);assert.match(logic,/fail 0/);const coverage=fs.readFileSync('SCREEN_COVERAGE.csv','utf8').trim().split(/\r?\n/).slice(1);assert.equal(coverage.length,91);assert.equal(new Set(coverage.map(r=>/^"(P\d+)"/.exec(r)[1])).size,24);assert.ok(coverage.some(r=>r.startsWith('"P13"')&&r.includes('"MIGRATED"')));
for(const name of [base+'/RUN_STATE.json','RUN_STATE.json'])assert.equal(load(name).revision,'P24-r03');assert.equal(load(base+'/RUN_STATE.json').visual,'AWAITING_USER_REVIEW');assert.equal(load('handoff/P23/RUN_STATE.json').visual,'USER_TEMPORARILY_ACCEPTED');
for(const f of load(base+'/SOURCE_MANIFEST_03.json').files){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.path)).digest('hex'),f.sha256,f.path);if(/\.m?js$/.test(f.path)){const r=spawnSync(process.execPath,['--check',f.path],{encoding:'utf8'});assert.equal(r.status,0,f.path+' '+r.stderr);}}
for(const file of ['REVISION_03.md','REVISION_03_CONTEXT.md','REVIEW_03.html']){const s=fs.readFileSync(base+'/'+file,'utf8'),links=file.endsWith('.html')?[...s.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]):[...s.matchAll(/\]\(([^)]+)\)/g)].map(m=>m[1]);for(const l of links)if(!/^(https?:|#)/.test(l))assert.ok(fs.existsSync(path.resolve(base,l)),file+' -> '+l);}
for(const r of after)for(const phase of ['before','after']){const png=fs.readFileSync(ev+'/'+phase+'/'+r.id+'.png');assert.equal(png.readUInt32BE(16),494);assert.equal(png.readUInt32BE(20),950);}
const result={boards:24,panels:91,reproducedFixed:14,audit:16,logic:173,browserGroups:groups,layout:35,footerViewports:4,links:'PASS',syntax:'PASS',hashes:'PASS',visual:'AWAITING_USER_REVIEW',integration:'BLOCKED_PRODUCTION'};fs.writeFileSync(ev+'/verification.json',JSON.stringify(result,null,2));console.log(result);
