const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const base='handoff/P24',load=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const csv=fs.readFileSync('SCREEN_COVERAGE.csv','utf8').trim().split(/\r?\n/).slice(1).map(line=>line.match(/^"(P\d+)",.*?,"(P\d+\.S\d+)"/));assert.equal(csv.length,91);assert.ok(csv.every(Boolean));assert.equal(new Set(csv.map(r=>r[1])).size,24);assert.equal(new Set(csv.map(r=>r[2])).size,91);
const coverage=fs.readFileSync('SCREEN_COVERAGE.csv','utf8');assert.match(coverage,/"P13"[^\n]*"MIGRATED"/);assert.equal((coverage.match(/^"P24"/gm)||[]).length,4);
const state=load(base+'/RUN_STATE.json');assert.equal(state.visual,'AWAITING_USER_REVIEW');assert.equal(state.integration,'BLOCKED_PRODUCTION');assert.equal(load('handoff/P23/RUN_STATE.json').visual,'USER_TEMPORARILY_ACCEPTED');assert.equal(load('RUN_STATE.json').current_prompt,'P24');assert.deepEqual(state.remaining_panel_ids,[]);
const paths=['after/results.json','edges/results.json','regression/check_p19/results.json','regression/check_p20/results.json','regression/check_p21/after/browser-results.json','regression/check_p23/results.json','regression/check_warranty_navigation/navigation-results.json'];let groups=0;
for(const p of paths){const data=load(base+'/evidence/revision-01/'+p);assert.ok(data.checks.length,p);assert.ok(data.checks.every(c=>c.status==='PASS'),p);assert.deepEqual(data.errors||[],[],p);groups+=data.checks.length;}assert.equal(groups,56);
const main=load(base+'/evidence/revision-01/after/results.json');assert.equal(main.layout.length,25);assert.ok(main.layout.every(r=>r.w===494&&r.h===950&&!r.overflow&&r.footer&&r.small.length===0));
const logic=fs.readFileSync(base+'/evidence/revision-01/logic.txt','utf8');assert.match(logic,/pass 165/);assert.match(logic,/fail 0/);
const manifest=load(base+'/SOURCE_MANIFEST.json');for(const f of manifest.files){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(f.path)).digest('hex'),f.sha256,f.path);if(/\.m?js$/.test(f.path)){const r=spawnSync(process.execPath,['--check',f.path],{encoding:'utf8'});assert.equal(r.status,0,f.path+' '+r.stderr);}}
for(const f of ['REPORT.md','REVIEW.html','COVERAGE_SUMMARY.md','DESIGN_TRACE.md']){const source=fs.readFileSync(base+'/'+f,'utf8');const links=f.endsWith('.html')?[...source.matchAll(/(?:href|src)="([^"]+)"/g)].map(m=>m[1]):[...source.matchAll(/\]\(([^)]+)\)/g)].map(m=>m[1]);for(const l of links)if(!/^(https?:|#)/.test(l))assert.ok(fs.existsSync(path.resolve(base,l)),f+' -> '+l);}
const board=fs.readFileSync(base+'/evidence/revision-01/baseline/B24.png');assert.equal(crypto.createHash('sha256').update(board).digest('hex'),'ad3cc5fdedac0a6351778787f9b87fa7ad8d1e416110f7be1c23cb0118bd9717');
for(const n of ['S01','S02','S03-inbound','S03-outbound','S04'])for(const sub of ['before/panels/'+n+'.png','after/'+n+'-494x950.png']){const file=fs.readFileSync(base+'/evidence/revision-01/'+sub);assert.equal(file.readUInt32BE(16),494,sub);assert.equal(file.readUInt32BE(20),950,sub);}
const result={referenceBoards:24,referencePanels:91,p24Panels:4,logic:165,browserGroups:groups,layout:25,footerViewports:4,links:'PASS',syntax:'PASS',sourceHashes:'PASS',visual:'AWAITING_USER_REVIEW',integration:'BLOCKED_PRODUCTION'};fs.writeFileSync(base+'/evidence/revision-01/verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
