const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const base='handoff/motion/M22/',read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const changed=['docs/flows/history/nfc-audit-motion.mjs','docs/flows/history/nfc-audit-motion.css','docs/flows/history/nfc-audit-view.mjs','docs/flows/history/embedded-history.mjs','docs/flows/home/home.mjs','docs/flows/home/motion.mjs'];
const unchanged=['docs/flows/history/nfc-audit.css','docs/flows/history/nfc-audit-model.mjs','docs/flows/history/nfc-audit-fixture.mjs','docs/flows/shared/motion/motion-primitives.mjs','docs/flows/shared/motion/motion-tokens.css','RUN_STATE.json','SCREEN_COVERAGE.csv','handoff/P22/RUN_STATE.json'];
const manifest={source_commit:spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim(),target:'prototype-local-ui-fixture',fixture:'Existing B22 four immutable event IDs; append test via interception only, seed/model unchanged',files:[]};let patch='';
for(const file of [...changed,...unchanged]){const bp=base+'before/source/'+file,b=fs.existsSync(bp)?fs.readFileSync(bp):null,a=fs.readFileSync(file);manifest.files.push({file,before:b?hash(b):null,after:hash(a),beforeBytes:b?.length||0,afterBytes:a.length,delta:a.length-(b?.length||0),unchanged:b?b.equals(a):false});if(unchanged.includes(file))assert.ok(b.equals(a),'preserve '+file);if(changed.includes(file)){patch+=b?spawnSync('git',['diff','--no-index','--',bp,file],{encoding:'utf8'}).stdout:`--- /dev/null\n+++ b/${file}\n@@ -0,0 +1,${a.toString().split('\n').length} @@\n+${a.toString().split('\n').join('\n+')}\n`;}}
manifest.sourceBytesDelta=manifest.files.filter(f=>changed.includes(f.file)).reduce((n,f)=>n+f.delta,0);manifest.scopedSourceHash=hash(JSON.stringify(manifest.files.filter(f=>changed.includes(f.file)).map(f=>[f.file,f.after])));fs.writeFileSync(base+'SOURCE_MANIFEST.json',JSON.stringify(manifest,null,2));fs.writeFileSync(base+'changes.patch',patch);
const before=read(base+'before/results.json'),after=read(base+'evidence/results.json');assert.equal(after.length,3);assert.deepEqual(after.map(r=>r.domain),after.map(()=>after[0].domain));const geometry=[];for(const r of after){assert.deepEqual(r.errors,[]);assert.deepEqual(r.mutationRequests,[]);assert.equal(r.checks.length,7);for(const [panel,g]of Object.entries(r.geometry)){const prev=before.find(x=>x.mode===r.mode);assert.deepEqual(g,prev.geometry[panel]);assert.equal(r.text[panel],prev.text[panel]);geometry.push({panel,mode:r.mode,equal:true,nodes:g.nodes});}}
let regressionGroups=0;for(const file of ['p22/after/results.json','p22/edges/results.json','p22-r02/results.json','p22-r03/after/audit-results.json','p22-r03/combinations/results.json']){const r=read(base+'regression/'+file);assert.ok(r.checks.every(x=>x.status==='PASS'));if(r.errors)assert.deepEqual(r.errors,[]);regressionGroups+=r.checks.length;}assert.equal(regressionGroups,43);
const shell=read(base+'regression/shell/results.json');assert.equal(shell.length,3);const shellGroups=shell.reduce((n,r)=>n+r.checks.length,0);assert.equal(shellGroups,36);assert.match(fs.readFileSync(base+'regression/p22/logic/node-tests.txt','utf8'),/pass 100/);
const summary={status:'PASS_SCOPED_UI_FIXTURE',modes:after.map(r=>r.mode),motionGroups:21,regressionGroups,shellGroups,nodeTests:100,geometry,layoutCombinations:40,footerViewports:4,operations:after.map(r=>({mode:r.mode,...r.domain})),sourceBytesDelta:manifest.sourceBytesDelta,scopedSourceHash:manifest.scopedSourceHash,performance:{longTasks:'Raw entries in before/results.json and evidence/results.json; workloads differ, no speed/FPS inference',inputLatency:'NOT_MEASURED separately',droppedFrames:'NOT_MEASURED on target hardware',virtualization:'DEFERRED per M00; native list and stable DOM retained, no library added'},visual:'USER_REVIEW_PENDING for motion; P22 r03 temporary acceptance preserved',integration:'BLOCKED_PRODUCTION / hardware NOT_RUN; business tracking unchanged'};
fs.writeFileSync(base+'SUMMARY.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
if(fs.existsSync(base+'REVIEW.html'))for(const m of fs.readFileSync(base+'REVIEW.html','utf8').matchAll(/(?:src|href)="([^"]+)"/g)){if(!m[1].startsWith('http'))assert.ok(fs.existsSync(require('node:path').resolve(base,m[1])),m[1]);}
const state=read('handoff/motion/MOTION_RUN_STATE.json');if(state.current_prompt==='MOTION_P22'){
 assert.ok(!state.remaining_panel_ids.some(id=>id.startsWith('P22.')));
 const rows=fs.readFileSync('handoff/motion/MOTION_COVERAGE.csv','utf8').trim().split(/\r?\n/);assert.equal(rows.length-1,91);assert.equal(rows.filter(l=>l.startsWith('"MOTION_P22",')&&l.includes('"PASS","PASS","PASS","PASS"')).length,4);
 console.log('PASS review links /91 motion panel rows /4 P22 mode rows /current checkpoint');
}
