const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync,spawnSync}=require('node:child_process');
const {owners,entries,guards,backs,focused}=require('./flow_gate_spec.cjs');
const root=path.resolve(__dirname,'..'),hand=path.join(root,'handoff/flow'),ev=path.join(hand,'evidence');
process.chdir(root);fs.mkdirSync(ev,{recursive:true});
const write=(file,data)=>fs.writeFileSync(path.join(hand,file),typeof data==='string'?data:JSON.stringify(data,null,2)+'\n');
const git=(...args)=>execFileSync('git',args,{encoding:'utf8',cwd:root,maxBuffer:20*1024*1024}).trim();
const sha=data=>crypto.createHash('sha256').update(data).digest('hex');
const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const csv=rows=>rows.map(r=>r.map(quote).join(',')).join('\n')+'\n';
const ps=command=>execFileSync('powershell.exe',['-NoProfile','-Command',command],{cwd:root,encoding:'utf8',maxBuffer:10*1024*1024});
const readCsv=file=>JSON.parse(ps(`[Console]::OutputEncoding=[Text.UTF8Encoding]::new($false); @(Import-Csv -LiteralPath '${file}') | ConvertTo-Json -Depth 8`));
const coverage=readCsv('SCREEN_COVERAGE.csv');
const matrix=readCsv('C:/Users/TAN MIE/Desktop/ScannerHNApp_Flow_Motion_P00_P24_v1.0 (1)/ScannerHNApp_Flow_Motion_P00_P24_v1.0/FLOW_PANEL_MATRIX.csv');
const panelIds=coverage.map(r=>r.panel_id),boardIds=[...new Set(coverage.map(r=>r.prompt_id))];
if(panelIds.length!==91||new Set(panelIds).size!==91||boardIds.length!==24||matrix.some(r=>!panelIds.includes(r.panel_id)))throw Error('24/91 inventory mismatch');
for(const [board,[file,states]]of Object.entries(owners)){if(!fs.existsSync('docs/flows/'+file))throw Error('Missing owner '+board+': '+file);if(states.length!==coverage.filter(r=>r.prompt_id===board).length)throw Error('Panel map count '+board);}
const source_commit=git('rev-parse','HEAD');
const files=git('ls-files','--cached','--others','--exclude-standard','-z').split('\0').filter(Boolean).filter(f=>/^(docs\/flows\/|tests\/|scripts\/)/.test(f)&&!f.includes('__pycache__')).sort();
const sourceManifest=files.map(file=>({path:file,sha256:sha(fs.readFileSync(file)),bytes:fs.statSync(file).size}));
const working_diff_hash=sha(JSON.stringify({source_commit,files:sourceManifest}));
write('evidence/tracked-diff.patch',execFileSync('git',['diff','--binary'],{cwd:root}).toString());
write('SOURCE_MANIFEST.json',{source_commit,working_diff_hash,hash_definition:'SHA256 of JSON {source_commit,files:[sorted path,sha256,bytes]}; all tracked/untracked docs/flows assets/code, scripts/tests; excludes handoff, gallery, dist and __pycache__. Not merely git diff.',files:sourceManifest});
write('evidence/git-inventory.txt',[git('worktree','list','--porcelain'),git('branch','-a','-vv'),git('status','--short','--untracked-files=normal')].join('\n\n'));
const journeys=JSON.parse(fs.readFileSync(path.join(ev,'journeys-final-02/results.json'),'utf8'));
if(journeys.checks.length!==11||journeys.checks.some(c=>c.status!=='PASS'))throw Error('Focused journeys not complete');
const regressions=JSON.parse(fs.readFileSync(path.join(ev,'regression-runs.json'),'utf8'));
const rechecks=JSON.parse(fs.readFileSync(path.join(ev,'recheck/regression-runs.json'),'utf8'));
const scope='UI_FIXTURE',fixture_version='hn-flow-gate-2026-09-30-v1';
const blockers=[{id:'B01',severity:'ESSENTIAL',panels:['P03.S02','P14.S03'],description:'Legacy P03 draft PN-0001 (fixture-p03-scan-*, FIXTURE-HN-0001/0002) has no matching P04/P05 owner. Resume retains data but reaches dependency dialog. J08 verifies the guard, not working resume.',source_needed:'Source adapter or approved mapping for legacy documentId, scanSessionId, version, operation, accepted rows, recorded/unsaved flags, supplier and scope; or an explicit decision migrating P03.S02 to real P04/P05 owner. Do not synthesize a replacement or map by PN display number.',evidence:'evidence/journeys-final-02/results.json#J08'},
 {id:'B02',severity:'VERIFICATION',panels:['P03.S02','P03.S04','P04.S01','P05.S01','P08.S01'],description:'24 board suites executed; four retained nonzero suite results use historical expectations. Focused journeys cover repairs and major owner chains, not every essential current edge of all 91 panels.',source_needed:'Refresh obsolete browser suite expectations from current contracts and finish uncovered essential edges. Preserve original failure logs.',evidence:'evidence/regression-runs.json; evidence/recheck/regression-runs.json'}];
const graph=[['edge_id','origin_state','action','guard','payload_ids','destination','source_reference','back_scroll_focus','response_error_cancel','evidence','status']];
for(const row of matrix){const b=row.board_id,i=Number(row.panel_id.split('S')[1])-1,e=entries[b][i];graph.push(['STATE-'+row.panel_id,e[0],e[1],guards[b]||guards.default,'See owner model; IDs not inferred from display labels',owners[b][1][i],'docs/flows/'+owners[b][0],backs[b]||backs.default,e[2],'handoff/flow/evidence/'+b+'-regression.log','SOURCE_REVIEWED_SUITE_EVIDENCE_ONLY']);}
for(const e of focused){const c=journeys.checks.find(c=>c.id===e[6]);graph.push([e[0],e[1],e[2],e[3],e[5],e[4],'docs/flows/home/home.mjs; scripts/check_flow_gate.cjs',backs[e[1].slice(0,3)]||backs.default,c.name+'; '+JSON.stringify(c.details),'handoff/flow/evidence/journeys-final-02/results.json#'+e[6],e[0]==='F25'?'BLOCKED_DEPENDENCY_GUARD_VERIFIED':'PASS_UI_FIXTURE']);}
write('FLOW_GRAPH.csv',csv(graph));
const byBoard=boardIds.map(board=>({board,owner:owners[board][0],panels:coverage.filter(r=>r.prompt_id===board).map(r=>r.panel_id),initial:regressions.find(r=>r.board===board),recheck:rechecks.find(r=>r.board===board),journeys:journeys.checks.filter(c=>c.boards.includes(board)).map(c=>c.id),visual:'UNCHANGED',production:'NOT_VERIFIED'}));write('BOARD_CHECKS.json',byBoard);
const panels=[['board_id','panel_id','title','actual_route_or_state','owner','disposition','edge_guard','back_scroll_focus','current_evidence','status']];
for(const row of matrix){const b=row.board_id,i=Number(row.panel_id.split('S')[1])-1,prior=coverage.find(r=>r.panel_id===row.panel_id);panels.push([b,row.panel_id,row.title,owners[b][1][i],'docs/flows/'+owners[b][0],prior.disposition,guards[b]||guards.default,backs[b]||backs.default,'handoff/flow/BOARD_CHECKS.json#'+b,row.panel_id==='P03.S02'?'BLOCKED_OWNER_MAPPING':'INVENTORIED_SOURCE_REVIEWED_NOT_FULL_EDGE_PASS']);}write('FLOW_PANEL_MATRIX.csv',csv(panels));
write('FIXTURE_MANIFEST.json',{fixture_version,evidence_scope:scope,target:'prototype',source_commit,working_diff_hash,owners:{auth:'hn-scanner-auth-preview-v1',dialogs:'hn-scanner-dialog-preview-v1',inbound:'hn-inbound-preview-v1',outbound:'hn-outbound-preview-v1',history:'hn-history-fixture-v1; verified-stock-receipt projection',warranty:'shared/warranty-cases.mjs + P19 confirmed receipts',nfc_audit:'P22 event-only; default unavailable; B22 opt-in',sessions:'P23 distinct sessions; default unavailable; B23 opt-in'},scenarios:[{name:'B08',session:'PQ-0001',scan_total:19,quantity:17,not_equivalent_to:'B23/PQ-0001'},{name:'B23',session:'PQ-0001',operation:'lookup',scan_total:5,document:null},{name:'verified-stock-receipt',rule:'recordedDocuments checks actor/warehouse/recorded/outcome; projection only verified receipt event; dedup exact ID; replace exact P12 legacy mapping only; no synthetic scan/NFC event'},{name:'P03-legacy',document:'PN-0001',owner_mapping:'MISSING',codes:['FIXTURE-HN-0001','FIXTURE-HN-0002']},{name:'B19/B20/B21/B24',rule:'Existing explicit samples retained; seed not regenerated; runtime owner UUIDs retained within each journey'}],persistence:'In-memory page. Refresh requires login and loses prototype drafts. P14 local retention is not durable WMS storage.',source_files:sourceManifest.filter(f=>/fixture|catalogue|warranty-cases|document-model/.test(f.path)&&/\.(mjs|js)$/.test(f.path)),dispositions:coverage.map(r=>({panel:r.panel_id,disposition:r.disposition})),limitations:['No backend/WMS/hardware/delivery acceptance','No production writes','Home View all -> P12; History footer -> P22; no removed draft shortcut','P18 handoff backend unavailable; no fake case closure','P06 fixture-event-doc-* unmapped; feedback guarded, no display-ID link']});
const tests=spawnSync(process.execPath,['--test','tests/*.mjs','tests/*.cjs'],{cwd:root,encoding:'utf8',maxBuffer:20*1024*1024});write('evidence/node-tests.log',tests.stdout+tests.stderr);
const summary={command:'node --test tests/*.mjs tests/*.cjs',exit_code:tests.status,tests:Number(/(?:ℹ|#) tests (\d+)/.exec(tests.stdout)?.[1]),pass:Number(/(?:ℹ|#) pass (\d+)/.exec(tests.stdout)?.[1]),fail:Number(/(?:ℹ|#) fail (\d+)/.exec(tests.stdout)?.[1])};write('evidence/node-summary.json',summary);
const syntax=[];for(const f of files.filter(f=>/\.(mjs|cjs|js)$/.test(f))){const r=spawnSync(process.execPath,['--check',f],{cwd:root,encoding:'utf8'});syntax.push({file:f,exit_code:r.status,error:r.status?r.stderr:undefined});}write('evidence/syntax.json',syntax);
const diff=spawnSync('git',['diff','--check'],{cwd:root,encoding:'utf8'});write('evidence/diff-check.json',{exit_code:diff.status,output:diff.stdout+diff.stderr});
const gate={source_commit,working_diff_hash,working_diff_hash_definition:'See SOURCE_MANIFEST.json; includes untracked source and assets',target:'prototype-local-ui-fixture',fixture_version,board_count:boardIds.length,panel_count:panelIds.length,graph_edge_count:graph.length-1,tested_edges:focused.map(e=>({id:e[0],journey:e[6],status:e[0]==='F25'?'BLOCKED_DEPENDENCY_GUARD_VERIFIED':'PASS_UI_FIXTURE'})),blockers,evidence_paths:['SOURCE_MANIFEST.json','FLOW_GRAPH.csv','FLOW_PANEL_MATRIX.csv','BOARD_CHECKS.json','evidence/journeys-final-02/results.json','evidence/regression-runs.json','evidence/recheck/regression-runs.json','evidence/node-summary.json','evidence/syntax.json','evidence/diff-check.json'],gate_status:'INCOMPLETE',evidence_scope:scope,tests:summary,scope_exclusions:['animation','deploy','production backend/hardware acceptance'],inventory_missing_panels:[],next_step:'Resolve B01 and complete B02 verification; rerun gate before MOTION_P00'};write('FLOW_GATE.json',gate);
write('EVIDENCE_SUMMARY.md',`# Verification\n\nNode: ${summary.pass}/${summary.tests} PASS; ${summary.fail} FAIL. Syntax: ${syntax.length} files, ${syntax.filter(r=>r.exit_code!==0).length} failures. git diff --check: ${diff.status}.\n\n| Board | Panels | Selected Suite | Journeys |\n|---|---:|---|---|\n`+byBoard.map(b=>`| ${b.board} | ${b.panels.length} | ${(b.recheck||b.initial).exit_code===0?'PASS':'NONZERO - inspect log'} | ${b.journeys.join(', ')||'selected suite only'} |`).join('\n')+'\n');
console.log(JSON.stringify({gate:gate.gate_status,boards:24,panels:91,graph_edges:graph.length-1,tests:summary,syntax:syntax.length}));
if(tests.status||syntax.some(r=>r.exit_code)||diff.status)process.exitCode=1;
