const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {mockGeography,address}=require(process.cwd()+'/scripts/outbound_geography_helpers.cjs');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.MOTION_BASE||'http://127.0.0.1:8775',out=path.resolve('handoff/motion/M17/regression/m05');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
 const context=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,timezoneId:'Asia/Ho_Chi_Minh',reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const p=await context.newPage(),r={mode,checks:[],errors:[],frames:[],layouts:[]};results.push(r);p.on('pageerror',e=>r.errors.push(e.message));await mockGeography(p);
 await p.addInitScript(()=>{window.m05Log=[];window.m05Calls={record:0,check:0,camera:0};const original=Element.prototype.animate;Element.prototype.animate=function(frames,options){const row={owner:this.dataset.hnMotionConsumer||'',node:this.className,duration:options.duration,frames,cancelled:false};m05Log.push(row);const a=original.call(this,frames,options),cancel=a.cancel.bind(a);a.cancel=()=>{row.cancelled=true;return cancel();};const node=this,start=performance.now();row.liveSamples=[];const capture=()=>{row.liveSamples.push(+getComputedStyle(node).opacity);if(node.isConnected&&performance.now()-start<options.duration+40)requestAnimationFrame(capture);};requestAnimationFrame(capture);return a;};if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=async()=>{m05Calls.camera++;throw Error('No hardware');};});
 await p.route('**/outbound/outbound.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('const flow = createOutboundFlow(','const flow = window.m05Flow = createOutboundFlow(')});});
 await p.route('**/outbound/fixture-adapter.mjs*',async route=>{const response=await route.fetch();let text=await response.text();for(const key of ['record','check'])text=text.replace('async '+key+'(request) {','async '+key+'(request) {window.m05Calls.'+key+'++;');await route.fulfill({response,body:text});});
 await p.route('**/inbound/inbound.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('const flow = createInboundFlow(','const flow = window.m05Inbound = createInboundFlow(')});});
 await p.clock.setFixedTime(new Date('2026-09-30T01:15:20Z'));
 const a=n=>p.locator(`[data-p05="${n}"]`).first(),snap=()=>p.evaluate(()=>m05Flow.snapshot()),log=()=>p.evaluate(()=>m05Log.filter(x=>x.owner)),reset=()=>p.evaluate(()=>m05Log=[]);
 async function check(name,fn){try{await fn();r.checks.push({name,status:'PASS'});console.log('PASS '+mode+' '+name);}catch(e){r.failure={name,error:e.stack};await p.screenshot({path:path.join(out,mode+'-failure.png')});throw e;}}
 async function shot(id){await p.evaluate(()=>{scrollTo(0,0);document.querySelector('.p05-scroll').scrollTop=0;});await p.waitForTimeout(240);await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+id+'.png')});const g=await p.evaluate(()=>Object.fromEntries(['.p05-header','.p05-sheet','.p05-scroll','.p05-footer','.p05-section-title','.p05-camera','.p05-counter','.p05-products','.hn-waiting-hero'].map(s=>{const n=document.querySelector(s),r=n?.getBoundingClientRect();return[s,r?[r.x,r.y,r.width,r.height]:null]})));assert.deepEqual(g,JSON.parse(fs.readFileSync(path.join(out,'before/geometry.json'))).find(x=>x.id===id).geometry);(r.panels??=[]).push({id,geometry:g,status:'PASS'});}
 async function frame(label,action){await reset();await action();const samples=await p.evaluate(()=>new Promise(resolve=>{const samples=[],start=performance.now();function sample(t){samples.push({ms:t-start,nodes:[...document.querySelectorAll('[data-hn-motion-consumer]')].map(n=>({owner:n.dataset.hnMotionConsumer,opacity:getComputedStyle(n).opacity,transform:getComputedStyle(n).transform}))});if(t-start<230)requestAnimationFrame(sample);else resolve(samples);}requestAnimationFrame(sample);}));r.frames.push({label,samples,log:await log()});}
 async function manual(code){if(!await p.locator('#p05-code').count())await a('manual').click();await p.fill('#p05-code',code);await p.locator('#p05-code').press('Enter');}
 async function fresh(){await a('home').click();await p.locator('.hn-task[data-route="outbound"]').click();}
 async function one(){await address(p);await a('next').click();await manual('HN12345');await a('next').click();}
 try{
 await p.goto(base+'/flows/auth-session/');await p.locator('.preview-tools details summary').click();await p.selectOption('#motion-mode',mode==='off'?'off':'auto');await p.fill('#username','minhanh');await p.fill('#password','preview');await p.click('#submit');await p.click('#start');await p.locator('.hn-task[data-route="outbound"]').click();await address(p);await p.fill('[data-p05-field="planned"]','10');
 await check('S01 validation immediate, CTA fixed and FormFeedback140/80/0',async()=>{const before=await a('next').boundingBox();await frame('form-error',()=>p.evaluate(()=>{const n=document.querySelector('[data-p05-note]');n.value='X'.repeat(201);n.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('[data-p05="next"]').click();}));assert.equal((await snap()).step,1);assert.equal(await p.locator('[data-p05-note]').getAttribute('aria-invalid'),'true');assert.deepEqual(await a('next').boundingBox(),before);const effects=(await log()).filter(x=>x.owner==='FormFeedback'&&x.node==='p05-field-error');assert.equal(effects.length,mode==='off'?0:1);if(effects.length)assert.equal(effects[0].duration,mode==='auto'?140:80);await p.locator('[data-p05-note]').fill('');await shot('P05.S01');});
 await a('next').click();await p.locator('.p05-tools summary').click();await p.evaluate(()=>window.cameraBefore=document.querySelector('.p05-camera'));
 await check('S02 seed7/10 and1duplicate: exactly7 new row events160ms, camera/counter static',async()=>{await reset();await a('batch').click();const s=await snap();assert.equal(s.accepted.length,7);assert.equal(s.attempts.length,8);assert.equal(new Set(s.attempts.map(a=>a.eventId)).size,8);assert.equal((await log()).filter(x=>x.owner==='ScanFeedback').length,mode==='auto'?7:0);assert.ok((await log()).filter(x=>x.owner==='ScanFeedback').every(x=>x.duration===160));assert.equal(await p.evaluate(()=>cameraBefore===document.querySelector('.p05-camera')&&cameraBefore.isConnected),true);await shot('P05.S02');});
 await check('S03 missing3 appears immediately and cannot send; notice140ms/no row replay on Back',async()=>{await frame('missing-three',()=>a('next').click());assert.match(await p.locator('.p05-warning').textContent(),/Còn thiếu 3/);assert.equal(await a('send').isDisabled(),true);assert.equal(await p.evaluate(()=>m05Flow.send()),false);const effects=(await log()).filter(x=>x.owner==='FormFeedback');assert.equal(effects.length,mode==='off'?0:1);if(effects.length)assert.equal(effects[0].duration,mode==='auto'?140:80);await shot('P05.S03');await reset();await a('back').click();await a('next').click();assert.equal((await log()).filter(x=>['ScanFeedback','FormFeedback'].includes(x.owner)).length,0);await a('back').click();});
 await check('duplicate feedback is immediate and manual input stays connected',async()=>{await a('manual').click();await p.evaluate(()=>window.inputBefore=document.querySelector('#p05-code'));await reset();await manual('HN12345');assert.equal((await snap()).accepted.length,7);assert.match(await p.locator('#p05-error-code').textContent(),/Không cộng/);assert.equal((await log()).filter(x=>x.owner==='ScanFeedback').length,0);assert.equal(await p.evaluate(()=>inputBefore===document.querySelector('#p05-code')&&inputBefore.isConnected&&inputBefore===document.activeElement),true);});
 await check('new camera-fixture scan preserves visible row anchor and does not replay through filter',async()=>{await a('all').click();await p.locator('.p05-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);const anchor=await p.evaluate(()=>{const area=document.querySelector('.p05-scroll').getBoundingClientRect(),row=[...document.querySelectorAll('[data-scan-event]')].find(n=>n.getBoundingClientRect().bottom>area.top&&n.getBoundingClientRect().top<area.bottom);return{id:row.dataset.scanEvent,offset:row.getBoundingClientRect().top-area.top};});await reset();await p.evaluate(()=>m05Flow.bindScan('camera-fixture')('HN12352','09:15:23'));await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const delta=await p.evaluate(a=>{const n=[...document.querySelectorAll('[data-scan-event]')].find(n=>n.dataset.scanEvent===a.id);return n.getBoundingClientRect().top-document.querySelector('.p05-scroll').getBoundingClientRect().top-a.offset;},anchor);r.anchor={...anchor,delta,scroll:await p.locator('.p05-scroll').evaluate(e=>({top:e.scrollTop,height:e.scrollHeight,client:e.clientHeight}))};assert.ok(Math.abs(delta)<1,JSON.stringify(r.anchor));assert.equal((await snap()).accepted.length,8);await reset();await a('filter-error').click();await p.evaluate(()=>m05Flow.bindScan('camera-fixture')('HN12353','09:15:24'));await a('filter-all').click();assert.equal((await log()).filter(x=>x.owner==='ScanFeedback').length,0);});
 await check('accepted final row: real RAF opacity changes only in auto and counter immediately10',async()=>{await p.fill('#p05-code','HN12354');await frame('accepted-row',()=>p.locator('#p05-code').press('Enter'));assert.equal((await snap()).accepted.length,10);const effects=(await log()).filter(x=>x.owner==='ScanFeedback');assert.equal(effects.length,mode==='auto'?1:0);const values=r.frames.at(-1).samples.flatMap(f=>f.nodes.filter(n=>n.owner==='ScanFeedback').map(n=>+n.opacity));assert.ok(values.length);assert.ok(mode==='auto'?values.some(v=>v<1):values.every(v=>v===1));assert.equal(await p.locator('.p05-camera').evaluate(n=>n.getAnimations({subtree:true}).length),0);r.listProfile=await p.evaluate(()=>({rows:document.querySelectorAll('.p05-attempt').length,nodes:document.querySelector('.p05-app').querySelectorAll('*').length,accepted:m05Flow.snapshot().accepted.length}));});
 await a('next').click();
 await check('S04 only after matched receipt; rapid send once; Back fromP12 never replays result',async()=>{await frame('verified-result',async()=>{await p.evaluate(()=>{m05Flow.send();m05Flow.send();});assert.equal((await log()).filter(x=>x.owner==='SubmitFeedback').length,0);await p.locator('[data-panel="P05.S04"]').waitFor();});const heroValues=r.frames.at(-1).samples.flatMap(f=>f.nodes.filter(n=>n.owner==='SubmitFeedback').map(n=>+n.opacity)).concat((await log()).filter(x=>x.owner==='SubmitFeedback').flatMap(x=>x.liveSamples||[]));assert.ok(heroValues.length);assert.ok(mode==='auto'?heroValues.some(v=>v<1):heroValues.every(v=>v===1));const effects=(await log()).filter(x=>x.owner==='SubmitFeedback');assert.equal(effects.length,mode==='auto'?1:0);if(effects.length)assert.equal(effects[0].duration,160);assert.equal(await p.evaluate(()=>m05Calls.record),1);assert.match(await p.locator('.hn-waiting-web').textContent(),/Chờ xử lý trên Web/);await shot('P05.S04');await reset();await a('document').click();await p.locator('[data-panel="P12.S02"]').waitFor();await p.goBack();await p.locator('[data-panel="P05.S04"]').waitFor();assert.equal((await log()).filter(x=>x.owner==='SubmitFeedback').length,0);});
 await fresh();await one();await p.selectOption('[data-p05-outcome]','timeout-recorded');
 await check('UNKNOWN remains guarded; confirm fade only after reconciliation using same request',async()=>{await reset();await a('send').click();await p.locator('[data-panel="P17.S04"]').waitFor();const old=(await snap()).request;assert.equal((await log()).filter(x=>x.owner==='SubmitFeedback').length,0);assert.equal(await a('send').isDisabled(),true);assert.equal(await p.evaluate(()=>m05Flow.send()),false);await a('check').click();await p.locator('[data-panel="P05.S04"]').waitFor();assert.deepEqual((await snap()).request,old);assert.equal(await p.evaluate(()=>m05Calls.record),2);});
 await fresh();await one();await p.selectOption('[data-p05-outcome]','confirmed');
 await check('rapid submit then native Back records once without rendering success over Home',async()=>{await p.evaluate(()=>{m05Flow.send();m05Flow.send();});await p.goBack();await p.locator('#hn-home').waitFor({state:'visible'});await p.waitForFunction(()=>m05Flow.snapshot().recorded);assert.equal(await p.evaluate(()=>m05Calls.record),3);assert.equal(await p.locator('#hn-home').isVisible(),true);await p.locator('.hn-task[data-route="outbound"]').click();assert.equal((await snap()).step,1);assert.equal((await snap()).attempts.length,0);});
 await address(p);await p.fill('[data-p05-field="planned"]','10');await a('next').click();await a('manual').click();
 await check('P04→P05 isolation and callback epochs: no callbacks/codes from old owner',async()=>{await p.evaluate(()=>window.outboundLate=m05Flow.bindScan('camera-fixture'));await p.goBack();await p.locator('.hn-task[data-route="inbound"]').click();await p.locator('[data-p04="next"]').click();await p.evaluate(()=>{window.inboundLate=m05Inbound.bindScan('camera-fixture');inboundLate('HN12345');});assert.equal(await p.evaluate(()=>outboundLate('HN12346')),false);await p.goBack();await p.locator('.hn-task[data-route="outbound"]').click();assert.equal(await p.evaluate(()=>inboundLate('HN12347')),false);assert.equal((await snap()).accepted.length,0);assert.equal(await p.evaluate(()=>outboundLate('HN12346')),false);});
 await check('live mode/OS/hidden cancellation never replays and does not change domain',async()=>{await p.locator('.hn-tools > details > summary').first().click();await p.selectOption('#home-motion-mode','auto');await p.evaluate(()=>{m05Flow.bindScan()('HN12345');const n=document.querySelector('#home-motion-mode');n.value='off';n.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(await p.locator('.p05-app').evaluate(n=>n.getAnimations({subtree:true}).length),0);await p.selectOption('#home-motion-mode','auto');await p.emulateMedia({reducedMotion:'reduce'});await reset();await p.evaluate(()=>m05Flow.bindScan()('HN12346'));assert.equal((await log()).filter(x=>x.owner==='ScanFeedback').length,0);await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{m05Flow.bindScan()('HN12347');Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('.p05-app').evaluate(n=>n.getAnimations({subtree:true}).length),0);await reset();await p.evaluate(()=>{m05Flow.bindScan()('HN12348');delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));document.querySelector('[data-p05="filter-all"]').click();});assert.equal((await log()).filter(x=>x.owner==='ScanFeedback').length,0);await p.emulateMedia({reducedMotion:mode==='os-reduced'?'reduce':'no-preference'});await p.selectOption('#home-motion-mode',mode==='off'?'off':'auto');});
 await check('security guard removes active effects immediately, restore retains codes',async()=>{await p.evaluate(()=>{m05Flow.bindScan()('HN12349');document.querySelector('[data-system-demo="deny"]').click();});await p.locator('[data-panel="P15.S03"]').waitFor();assert.equal(await p.locator('#hn-destination').isVisible(),false);assert.equal(await p.locator('#hn-destination').evaluate(n=>n.getAnimations({subtree:true}).length),0);await p.evaluate(()=>document.querySelector('[data-system-demo="allow"]').click());await p.locator('.p05-app').waitFor({state:'visible'});assert.equal((await snap()).accepted.length,5);});
 r.domain=await snap();
 await check('compact viewports preserve input/CTA and logout cleans controllers',async()=>{for(const [width,height]of [[360,800],[360,420]]){await p.setViewportSize({width,height});await p.locator('#p05-code').focus();const m=await p.locator('.hn-screen').evaluate(n=>{const r=n.getBoundingClientRect(),f=n.querySelector('.p05-footer').getBoundingClientRect();return{size:[n.offsetWidth,n.offsetHeight],footer:f.bottom<=r.bottom+1,overflow:document.documentElement.scrollWidth>innerWidth};});assert.deepEqual(m.size,[494,950]);assert.ok(m.footer&&!m.overflow);r.layouts.push(m);await p.locator('.hn-screen').screenshot({path:path.join(out,mode+'-small-'+height+'.png')});}await p.evaluate(()=>{window.detachedOwner=document.querySelector('#hn-destination');document.querySelector('#hn-logout').click();});await p.locator('#username').waitFor();assert.equal(await p.evaluate(()=>detachedOwner.getAnimations({subtree:true}).length),0);assert.equal(await p.evaluate(()=>detachedOwner.hasAttribute('data-hn-motion-mode')),false);});
 r.operations=await p.evaluate(()=>m05Calls);assert.deepEqual(r.operations,{record:3,check:1,camera:0});assert.deepEqual(r.errors,[]);await context.tracing.stop({path:path.join(out,mode+'-trace.zip')});await context.close();
 }catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify(results,null,2));await context.tracing.stop({path:path.join(out,mode+'-failure-trace.zip')});throw e;}
 }for(const r of results)assert.deepEqual(r.domain,results[0].domain,'mode domain parity');fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({modes:3,groups:results.reduce((n,r)=>n+r.checks.length,0)}));}finally{await browser.close();}})();
