const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/TAN MIE/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const before=process.argv.includes('--before'),out=path.resolve('handoff/motion/M17/regression/m07'+(before?'/before':''));fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),results=[];try{for(const mode of ['auto','os-reduced','off']){
 const context=await browser.newContext({viewport:{width:494,height:950},deviceScaleFactor:1,reducedMotion:mode==='os-reduced'?'reduce':'no-preference',timezoneId:'Asia/Ho_Chi_Minh'}),page=await context.newPage(),r={mode,checks:[],geometry:{},errors:[]};results.push(r);page.on('pageerror',e=>r.errors.push(e.message));
 await context.tracing.start({screenshots:true,snapshots:true,sources:true});await page.clock.setFixedTime(new Date('2026-09-30T01:15:20Z'));
 await page.addInitScript(()=>{window.qaAnimations=[];window.qaFrames=[];window.qaVisibility=0;window.qaHardware=0;const add=EventTarget.prototype.addEventListener,remove=EventTarget.prototype.removeEventListener;
 EventTarget.prototype.addEventListener=function(type,fn,opts){if(type==='visibilitychange'&&['visibility','onNfcVisibility'].includes(fn?.name))qaVisibility++;return add.call(this,type,fn,opts);};
 EventTarget.prototype.removeEventListener=function(type,fn,opts){if(type==='visibilitychange'&&['visibility','onNfcVisibility'].includes(fn?.name))qaVisibility--;return remove.call(this,type,fn,opts);};
 const animate=Element.prototype.animate;Element.prototype.animate=function(frames,options){qaAnimations.push({consumer:this.dataset.hnMotionConsumer,node:this.className,duration:options.duration,frames});const animation=animate.call(this,frames,options);if(['NfcVerified','NfcConfirmed'].includes(this.dataset.hnMotionConsumer)){const node=this,consumer=node.dataset.hnMotionConsumer,start=performance.now();const sample=()=>{qaFrames.push({consumer,t:performance.now()-start,opacity:getComputedStyle(node).opacity,connected:node.isConnected});if(node.isConnected&&performance.now()-start<230)requestAnimationFrame(sample);};requestAnimationFrame(sample);}return animation;};window.NDEFReader=class{constructor(){qaHardware++;throw Error('No hardware allowed');}};
 });
 const act=n=>page.locator(`[data-p07="${n}"]`).first(),snap=()=>page.locator('[data-p07-snapshot]').evaluate(e=>JSON.parse(e.textContent));
 async function check(name,fn){await fn();r.checks.push(name);}
 async function settle(){await page.waitForTimeout(240);}
 async function capture(panel){await settle();await page.evaluate(()=>scrollTo(0,0));r.geometry[panel]=await page.locator('.p07-app').evaluate(app=>Object.fromEntries(['.hn-screen','.p07-header','.p07-scroll','.p07-footer','.p07-art-frame','.p07-phone','.p07-success-symbol'].map(s=>{const e=document.querySelector(s);if(!e)return[s,null];const q=e.getBoundingClientRect();return[s,[q.x,q.y,q.width,q.height]];})));await page.locator('.hn-screen').screenshot({path:path.join(out,mode+'-'+panel+'.png')});}
 async function read(){await page.locator('[data-p07-demo-read]').evaluate(b=>{b.click();b.click();});await page.waitForFunction(()=>!JSON.parse(document.querySelector('[data-p07-snapshot]').textContent).busy);}
 await page.goto((process.env.PREVIEW_BASE_URL||'http://127.0.0.1:8766')+'/flows/auth-session/');await page.fill('#username','minhanh');await page.fill('#password','preview');await page.click('#submit');await page.click('#start');await page.locator('#home-motion-mode').evaluate(e=>e.closest('details').open=true);await page.selectOption('#home-motion-mode',mode==='off'?'off':'auto');await page.click('[data-route="nfc"]');
 await capture('P07.S01');r.profile=await page.locator('.p07-app').evaluate(e=>({nodes:e.querySelectorAll('*').length,rows:e.querySelectorAll('.p07-tag').length}));await act('begin').click();await capture('P07.S02');await read();await act('next').click();await capture('P07.S03');await act('confirm').evaluate(b=>{b.click();b.click();});await page.locator('[data-panel="P07.S04"]').waitFor();await capture('P07.S04');r.domain={receipt:(await snap()).receipt,stats:(await snap()).stats};
 if(!before){
  await check('verified card140/check160 only; OS reduced/off follows M00',async()=>{const effects=await page.evaluate(()=>qaAnimations.filter(a=>['NfcVerified','NfcConfirmed'].includes(a.consumer)));assert.equal(effects.filter(a=>a.consumer==='NfcVerified').length,mode==='off'?0:1);assert.equal(effects.filter(a=>a.consumer==='NfcConfirmed').length,mode==='auto'?1:0);if(mode==='auto'){assert.equal(effects.find(a=>a.consumer==='NfcVerified').duration,140);assert.equal(effects.find(a=>a.consumer==='NfcConfirmed').duration,160);}if(mode==='os-reduced')assert.equal(effects[0].duration,80);});
  await check('Back/restored confirmed state does not replay; no legacy ripple loops',async()=>{const n=await page.evaluate(()=>qaAnimations.length);await act('detail').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP07Detail);assert.equal(await page.locator('.p07-wave').count(),0);await page.evaluate(()=>location.hash='#p02/nfc?panel=4');await settle();assert.equal(await page.evaluate(()=>qaAnimations.slice(-20).filter(a=>a.consumer==='NfcConfirmed').length),mode==='auto'?1:0);});
  await act('new-link').click();await page.locator('.p07-tools>details>summary').click();await page.selectOption('[data-p07-scenario]','failed');await read();await act('next').click();await act('confirm').click();await page.locator('.hn-action-dialog[open]').waitFor();await check('read UID then failed mapping never shows success',async()=>{assert.equal((await snap()).receipt,null);assert.equal((await snap()).stats.mutations,1);assert.equal(await page.locator('.p07-success-symbol').count(),0);});await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP07Feedback);await page.selectOption('[data-p07-scenario]','ready');await act('back').click();
  await check('actual adapter listening only; hide cancels read, late completion cannot map',async()=>{await page.click('[data-p07-demo-read]');assert.equal((await snap()).listening,true);assert.equal(await page.locator('[data-nfc-listening="true"]').count(),1);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await page.locator('[data-nfc-listening="true"]').count(),0);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));location.hash='#home';});await page.locator('#hn-home').waitFor({state:'visible'});await settle();await page.click('[data-route="nfc"]');assert.equal((await snap()).listening,false);assert.equal((await snap()).busy,false);assert.equal((await snap()).read,null);assert.equal((await snap()).stats.mutations,1);});
  await check('ten enter/leave cycles do not leak motion listeners or sessions',async()=>{await page.click('[data-tab="home"]');const base=await page.evaluate(()=>qaVisibility);for(let i=0;i<10;i++){await page.click('[data-route="nfc"]');await act('begin').click();await page.click('[data-p07-demo-read]');await page.evaluate(()=>location.hash='#home');await page.locator('#hn-home').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>qaVisibility),base);}assert.equal(await page.evaluate(()=>qaHardware),0);});
  await page.click('[data-route="nfc"]');await check('native list scroll, tabs, search and dialog focus stay usable',async()=>{await page.locator('.p07-scroll').evaluate(e=>e.scrollTop=240);const top=await page.locator('.p07-scroll').evaluate(e=>e.scrollTop);await page.locator('[data-p07-tag="fixture-tag-008"]').evaluate(e=>e.click());await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP07Detail);assert.equal(await page.locator('.p07-scroll').evaluate(e=>e.scrollTop),top);await page.fill('#p07-search','TAG-002');await page.locator('#p07-search').press('Enter');await page.locator('#p07-detail-title').waitFor();await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP07Detail);await act('clear-query').click();});
  await act('begin').click();await page.selectOption('[data-p07-read-tag]','NFC-8A2F');await read();await page.locator('.hn-action-dialog[open]').waitFor();await check('already linked UID remains blocked, no motion bypass or overwrite',async()=>{assert.equal(await act('next').isDisabled(),true);assert.equal((await snap()).receipt,null);assert.equal((await snap()).stats.mutations,1);});await page.keyboard.press('Escape');await page.waitForFunction(()=>!history.state?.hnP07Feedback);
  r.finalStats=(await snap()).stats;r.frames=await page.evaluate(()=>qaFrames);if(mode==='auto')for(const consumer of ['NfcVerified','NfcConfirmed'])assert.ok(r.frames.some(f=>f.consumer===consumer&&Number(f.opacity)<1),'actual moving frame '+consumer);
  r.effects=await page.evaluate(()=>qaAnimations);r.lifecycle={visibilityListeners:await page.evaluate(()=>qaVisibility),hardware:await page.evaluate(()=>qaHardware)};
 }
 assert.deepEqual(r.errors,[]);await context.tracing.stop({path:path.join(out,mode+'-trace.zip')});await context.close();
 }if(!before){assert.deepEqual(results.map(r=>r.domain),[results[0].domain,results[0].domain,results[0].domain]);assert.deepEqual(results.map(r=>r.finalStats),[results[0].finalStats,results[0].finalStats,results[0].finalStats]);const b=JSON.parse(fs.readFileSync(path.join(out,'before/results.json')));const relative=g=>Object.fromEntries(Object.entries(g).map(([panel,boxes])=>{const origin=boxes['.hn-screen'];return [panel,Object.fromEntries(Object.entries(boxes).map(([selector,rect])=>[selector,rect?[rect[0]-origin[0],rect[1]-origin[1],rect[2],rect[3]]:null]))];}));for(let i=0;i<3;i++)assert.deepEqual(relative(results[i].geometry),relative(b[i].geometry),'settled geometry relative to shell vs before '+results[i].mode);}
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('PASS '+(before?'12 before captures':results.reduce((n,r)=>n+r.checks.length,0)+' mode/state checks; equal domain and geometry'));
 }catch(e){fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.stack,results},null,2));throw e;}finally{await browser.close();}
})();
