const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const store=__dirname,state=JSON.parse(fs.readFileSync(path.join(store,'staging/archive-state.json'),'utf8')),root=state.root;
const env={...process.env,GIT_DIR:state.repo,GIT_WORK_TREE:root,GIT_INDEX_FILE:path.join(store,'staging/archive.index'),GIT_TERMINAL_PROMPT:'0',GCM_INTERACTIVE:'never'};
const opts=['-c','credential.username=Duc-Nguyen98','-c','core.autocrlf=false','-c','user.name=Duc-Nguyen98','-c','user.email=52225998+Duc-Nguyen98@users.noreply.github.com'];
const git=(args,input)=>execFileSync('git',[...opts,...args],{cwd:root,env,input,encoding:'utf8',maxBuffer:100e6}).trim();
const target=path.join(root,'handoff/REVIEW_FLOW_INTEGRATION');
assert.equal(state.status,'VERIFIED');
const snapshot=state.commits.at(-1).sha;
assert.equal(git(['ls-remote','origin','refs/heads/'+state.branch]).split(/\s/)[0],snapshot);
fs.copyFileSync(path.join(store,'staging/file-manifest.json'),path.join(target,'ARCHIVE_MANIFEST.json'));
fs.copyFileSync(path.join(store,'evidence/node-tests.log'),path.join(target,'evidence/node-tests.log'));
fs.copyFileSync(path.join(store,'evidence/cross-board.json'),path.join(target,'evidence/cross-board.json'));
fs.copyFileSync(path.join(store,'evidence/check-cross-board.cjs'),path.join(target,'evidence/check-cross-board.cjs'));
fs.copyFileSync(__filename,path.join(target,'FINALIZE_ARCHIVE.cjs'));
fs.mkdirSync(path.join(target,'evidence/git-transfer'),{recursive:true});
for(const f of fs.readdirSync(path.join(store,'staging')).filter(f=>/^(add|push)-\d+\.log$/.test(f)))fs.copyFileSync(path.join(store,'staging',f),path.join(target,'evidence/git-transfer',f));
const summary={status:'SNAPSHOT_VERIFIED_AND_PUSHED',sourceFiles:state.files,sourceBytes:state.bytes,batches:state.batches.length,verifiedFiles:state.verifiedFiles,verifiedAt:state.verifiedAt,snapshotCommit:snapshot,archiveBranch:state.branch,baseCommit:state.base,repository:'https://github.com/Duc-Nguyen98/ScannerHNApp',manifest:'ARCHIVE_MANIFEST.json',allIntermediateTracesAndLogs:true,exactBytes:true,noWorkingCopyReset:true,commits:state.commits,notes:['Original remote design/static/history objects inherited unchanged unless explicitly present in current source.','Known incomplete historical trace retained; see TRACE_SCAN.json.','Publication evidence is added after main/Pages verification.']};
fs.writeFileSync(path.join(target,'ARCHIVE_RESULT.json'),JSON.stringify(summary,null,2)+'\n');
const files=fs.readdirSync(target,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()).map(e=>path.relative(root,path.join(e.parentPath,e.name)).replaceAll('\\','/'));
const list=path.join(store,'staging/final-meta.nul');fs.writeFileSync(list,files.map(f=>':(literal)'+f).join('\0')+'\0');
git(['read-tree',snapshot]);git(['add','--pathspec-from-file='+list,'--pathspec-file-nul']);const tree=git(['write-tree']);const sha=git(['commit-tree',tree,'-p',snapshot],'Record full archive checksums and review-flow verification\n');
git(['update-ref','refs/heads/'+state.branch,sha]);git(['push','origin',sha+':refs/heads/'+state.branch]);
const remoteMain=git(['ls-remote','origin','refs/heads/main']).split(/\s/)[0];assert.equal(remoteMain,state.base,'Main changed; merge required before promotion');
git(['push','origin',sha+':refs/heads/main']);git(['update-ref','refs/heads/main',sha]);
fs.writeFileSync(path.join(store,'staging/promotion.json'),JSON.stringify({sha,tree,snapshot,branch:state.branch,promotedAt:new Date().toISOString()},null,2));console.log({promoted:sha,snapshot,files:state.files,bytes:state.bytes});
